aws-amplify/amplify-cli

package.json, packages/amplify-category-api/commands/api.js, packages/amplify-category-function/provider-utils/awscloudformation/index.js, packages/amplify-category-notifications/commands/notifications/remove.js, packages/amplify-cli/src/extensions/amplify-helpers/path-manager.js
https://github.com/aws-amplify/amplify-cli/issues/10
* Due to module hoisting, grunt is not able to find the grunt-aws-lambda package in the plugin node modules in prod environment. This fix makes it possible to invoke a lambda function locally in prod environments.
* Improved some validation/error messages.
=> Fixes lambda invoke issue + better validation error if not working inside amplify project

packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts, packages/graphql-transformer-common/src/ModelResourceIDs.ts
Changing naming convention to align with existing console.
=> Change default from onXCreated to onCreateX

packages/graphql-appsync-transformer/package.json, packages/graphql-auth-transformer/package.json, packages/graphql-connection-transformer/package.json, packages/graphql-dynamodb-transformer/package.json, packages/graphql-elasticsearch-transformer/package.json, packages/graphql-mapping-template/package.json, packages/graphql-transformer-common/package.json, packages/graphql-transformer-core/package.json, packages/graphql-transformers-e2e-tests/package.json, packages/graphql-versioned-transformer/package.json
Removing linting from graphql packages temporarily.
=> Removing linting from graphql packages temporarily.

packages/amplify-codegen/tests/walkthrough/add.test.js
=> Update failing codegen test

.circleci/config.yml, Readme.md, package.json
- Add circle ci config
- update Readme
=> Add ci config and update readme

.github/ISSUE_TEMPLATE.md
*Issue #, if available:* None
* Make questions bold
* Adds **Steps to reproduce the issue** section
* Breaks down **Additional environment details** into small list of items
* Explicitly calls out **Output of ``amplify --version``** option
* Explicitly calls out for **NodeJS version and JS framework if applies**
=> Improves issue template doc with bold text and explicit call outs

graphql-transform-tutorial.md
*Issue #, if available:* https://github.com/aws-amplify/amplify-cli/issues/46
Addresses typo in GraphQL query so it can generate code successfully from gluegun
=> Addresses typo in the listBlog query example so it generates code successfully

packages/amplify-category-notifications/lib/channel-APNS.js, packages/amplify-category-notifications/lib/notifications-manager.js, packages/amplify-category-notifications/lib/p12decoder.js, packages/amplify-category-notifications/lib/pinpoint-helper.js, packages/amplify-cli/src/extensions/amplify-helpers/get-resource-outputs.js, packages/amplify-cli/src/extensions/amplify.js, packages/amplify-frontend-android/index.js, packages/amplify-frontend-ios/index.js, packages/amplify-frontend-javascript/index.js
#17 
- p12 file decoder improved
older version of openssl generates rsa private key.
updated the p12 decoder to scan for all possibilities.
- add frontend config file generation for notifications 
=> Notifications update 

packages/amplify-cli/src/extensions/amplify-helpers/get-resource-outputs.js
=> Some lint fixes from notifications PR

lerna.json
=> Remove npm client from lerna json

packages/amplify-provider-awscloudformation/lib/upload-appsync-files.js
fIXES - https://github.com/aws-amplify/amplify-cli/issues/82
=> Clear parameters.json cache for GraphQL API's

packages/amplify-category-auth/provider-utils/awscloudformation/assets/string-maps.js, packages/amplify-category-auth/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js, packages/amplify-category-auth/provider-utils/supported-services.json
=> removes twitter option

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts, packages/graphql-auth-transformer/src/resources.ts
#55 
- Skip protection if no resolver
- apply identityField
=> Skip protection if no resolver, apply identityField

packages/amplify-provider-awscloudformation/lib/build-resources.js
Issue #125 
- Replaced changes detection for src directory
- Now looking for first file with mtime > lastPackageTimeStamp
=> Fixes function category src files changes detection

packages/amplify-category-hosting/lib/S3AndCloudFront/template.json
Fixes -> https://github.com/aws-amplify/amplify-cli/issues/107
=> Gzip static assets when deploying to cloudfront

packages/amplify-graphql-docs-generator/package.json
=> change license and author for amplify-graphql-docs-generator

packages/amplify-graphql-docs-generator/package.json
=> fix cli file name

packages/graphql-transformer-core/Readme.md
=> Update docs to make connections on models

packages/amplify-provider-awscloudformation/lib/upload-appsync-files.js
Fixes: https://github.com/aws-amplify/amplify-cli/issues/210
Also addresses - https://github.com/aws-amplify/amplify-cli/issues/168
=> Fix S3 bucket file paths for windows

Readme.md
Update CLI Readme.md  to change Node version requirement
=> Update CLI repo Readme.md  to change Node version requirement

packages/amplify-category-api/commands/api/remove.js, packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js, packages/amplify-cli/src/extensions/amplify-helpers/remove-resource.js, packages/amplify-codegen/src/codegen-config/AmplifyCodeGenConfig.js, packages/amplify-codegen/src/commands/add.js, packages/amplify-codegen/src/constants.js, packages/amplify-codegen/src/utils/getAppSyncAPIInfo.js, packages/amplify-codegen/src/utils/index.js, packages/amplify-codegen/src/utils/selectAPIKey.js, packages/amplify-codegen/src/utils/updateAmplifyMeta.js, packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js, packages/amplify-provider-awscloudformation/lib/utility-functions.js
=> Ability to add external AppSync API to an Amplify project as a part of the codegen add command

packages/amplify-category-api/commands/api/update.js, packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js, packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
Fixes: https://github.com/aws-amplify/amplify-cli/issues/243
=> Fix provider check when compiling GraphQL schema

packages/amplify-graphql-docs-generator/__integration__/__snapshots__/e2e.test.ts.snap, packages/amplify-graphql-docs-generator/__integration__/e2e.test.ts, packages/amplify-graphql-docs-generator/src/generator/getFields.ts
Integration tests were failing in circle CI. After updating the test, discovered an stack overflow happening due to recursive reference in the fixture data. 
=> fix (ampplify-cli/amplify-graphql-docs-generator) integration test

packages/amplify-cli/src/cli.js
#250 
local plugin searching updated
=> fix local package matching issue

.circleci/config.yml, .circleci/delete_api.sh, .circleci/delete_auth.sh
Delete the deployment bucket after integration tests
=> Integration test cleanup

.circleci/config.yml, package.json, packages/graphql-auth-transformer/src/resources.ts, packages/graphql-transformers-e2e-tests/package.json, packages/graphql-transformers-e2e-tests/src/CloudFormationClient.ts, packages/graphql-transformers-e2e-tests/src/S3Client.ts, packages/graphql-transformers-e2e-tests/src/__tests__/AppSyncTransformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/CustomRoots.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/DynamoDBModelTransformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/ModelAuthTransformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/VersionedModelTransformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/deploy.ts
Fixing transform tests to run in CI/CD environment.
=> Integration tests

.circleci/config.yml
=> running graphql integration tests only for merged PRs

packages/amplify-category-function/commands/function/add.js
=> fixes(#303)

packages/amplify-cli/src/lib/config-steps/c1-configFrontendHandler.js, packages/amplify-cli/src/lib/init-steps/s0-analyzeProject.js
=> fix frontend config

cypress/integration/auth_spec.js
=> Fixing Auth Integration tests after updates to amplify-react-ui package

native_guide.md
=> Fix typo in instructions iOS to Android

packages/amplify-category-interactions/Readme.md
=> Update Interactions Readme.md

.circleci/config.yml, package.json
=> Update release scripts

packages/graphql-appsync-transformer/src/AppSyncTransformer.ts, packages/graphql-transformer-core/src/GraphQLTransform.ts, packages/graphql-transformer-core/src/validation.ts, packages/graphql-transformers-e2e-tests/src/__tests__/CustomRoots.e2e.test.ts
#342 
Allows "aws_auth" to be used by the transform.
=> Fixing #342

packages/amplify-category-api/commands/api/console.js, packages/amplify-category-api/index.js, packages/amplify-category-api/package.json, packages/amplify-category-api/provider-utils/awscloudformation/index.js, packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js
=> feat: add option to open AppSync console using the CLI

packages/amplify-codegen/package.json
=> Update package.json to include latest version of Graphql as a part of codegen package

packages/graphql-transformers-e2e-tests/src/__tests__/DynamoDBModelTransformer.e2e.test.ts
=> test(graphql-transformers-e2e-tests): cleanup dynamo tables

Readme.md
=> build: force publish

packages/amplify-cli/sample-headless-scripts/headless_add_external_env.sh, packages/amplify-cli/sample-headless-scripts/headless_configure_project.sh, packages/amplify-cli/sample-headless-scripts/headless_init_env.sh, packages/amplify-cli/sample-headless-scripts/headless_init_new_project.sh, packages/amplify-cli/sample-headless-scripts/headless_publish.sh, packages/amplify-cli/sample-headless-scripts/headless_push.sh, packages/amplify-cli/src/commands/env/get.js, packages/amplify-cli/src/commands/env/list.js
=> feat: add json option to env display commands and add sample headless scripts

packages/amplify-category-api/provider-utils/awscloudformation/cloudformation-templates/apigw-cloudformation-template-default.json.ejs, packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.js
=> feat: multi-environment support for API Gateway

.circleci/config.yml
Adding github back to known hosts
=> CI: Update deployment config to add ssh keys

packages/amplify-cli/src/commands/env/get.js, packages/amplify-cli/src/commands/env/list.js
=> fix: stringify env json outputs

packages/graphql-appsync-transformer/src/AppSyncTransformer.ts, packages/graphql-appsync-transformer/src/__tests__/AppSyncTransformer.test.ts, packages/graphql-appsync-transformer/src/resources.ts, packages/graphql-auth-transformer/src/resources.ts, packages/graphql-dynamodb-transformer/src/resources.ts, packages/graphql-elasticsearch-transformer/src/resources.ts, packages/graphql-transformer-common/src/ResourceConstants.ts
This adds support for multiple environments in the transform.
=> Multienv support in the transform.

packages/amplify-category-auth/provider-utils/awscloudformation/assets/cognito-defaults.js, packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs, packages/amplify-category-auth/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js
removing hardcoded roles in parameters.json
=> fix for roleattachment update error

packages/amplify-cli/sample-headless-scripts/headless_init_env.sh, packages/amplify-cli/src/commands/env.js, packages/amplify-cli/src/commands/env/checkout.js, packages/amplify-cli/src/commands/env/sync.js, packages/amplify-cli/src/extensions/amplify-helpers/get-project-details.js, packages/amplify-cli/src/extensions/amplify-helpers/path-manager.js, packages/amplify-cli/src/extensions/amplify-helpers/show-all-help.js, packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.js, packages/amplify-cli/src/lib/init-steps/s0-analyzeProject.js, packages/amplify-cli/src/lib/initialize-env.js, packages/amplify-provider-awscloudformation/lib/initialize-env.js, packages/amplify-provider-awscloudformation/src/aws-utils/aws-s3.js
=> feat: added amplify env sync and amplify env checkout command & added help commands for env 

Readme.md
=> Fixed a couple of links to the new docs

packages/amplify-graphql-types-generator/src/swift/codeGeneration.ts, packages/amplify-graphql-types-generator/test/swift/__snapshots__/codeGeneration.ts.snap
Update codegen repo based on PR -> https://github.com/awslabs/aws-appsync-codegen/pull/9/files
=> Update codegen repo based on PR -> https://github.com/awslabs/aws-appsync-codegen/pull/9/files

packages/amplify-category-auth/index.js, packages/amplify-category-auth/package.json, packages/amplify-cli/src/extensions/amplify-helpers/envResourceParams.js, packages/amplify-cli/src/extensions/amplify-helpers/remove-resource.js, packages/amplify-cli/src/extensions/amplify.js, packages/amplify-cli/src/lib/initialize-env.js
updated the logic of init env hook for auth to add/remove env specific config based on resource
changes
=> refactor: change auth init env logic

packages/amplify-provider-awscloudformation/lib/configuration-manager.js
=> fix a configure project bug

packages/amplify-cli/src/extensions/amplify-helpers/envResourceParams.js
move team specific category config to categories key in team provider
=> refactor(@aws-amplify/cli): update team specific config

packages/amplify-category-storage/index.js, packages/amplify-cli/src/cli.js, packages/amplify-cli/src/extensions/amplify-helpers/get-git-ignore-blob.js, packages/amplify-cli/src/lib/constants.js, packages/amplify-cli/src/lib/init-steps/s0-analyzeProject.js, packages/amplify-cli/src/lib/init-steps/s9-onSuccess.js, packages/amplify-cli/src/lib/migrate-project.js, packages/amplify-codegen/tests/codegen-config/utils/graphQlToAmplifyConfig.test.js
=> feat: core metadata migration of projects using the old version of the CLI

packages/amplify-category-auth/index.js, packages/amplify-category-auth/provider-utils/awscloudformation/index.js, packages/amplify-cli/src/extensions/amplify-helpers/envResourceParams.js, packages/amplify-cli/src/extensions/amplify-helpers/remove-resource.js, packages/amplify-provider-awscloudformation/src/resourceParams.js
=> Multienv auth migrate

packages/amplify-category-analytics/index.js, packages/amplify-category-analytics/provider-utils/awscloudformation/service-walkthroughs/pinpoint-walkthrough.js
=> feat(amplify-category-analytics): migrate script for multienv

packages/amplify-cli/src/extensions/amplify-helpers/get-project-details.js, packages/amplify-cli/src/lib/migrate-project.js
=> feat: Add second level of messaging when migrating projects from old version to newer version

packages/amplify-cli/src/extensions/amplify-helpers/delete-project.js
=> typo(@aws-amplify/cli) fix typo

packages/amplify-category-analytics/provider-utils/awscloudformation/service-walkthroughs/pinpoint-walkthrough.js
=> fix(amplify-category-analytics): migration update auth rolename to ref

packages/amplify-category-api/commands/api/gql-compile.js, packages/amplify-cli/src/lib/migrate-project.js
=> feat: add a warning on migration and force compile gql schema

packages/amplify-codegen/commands/codegen/remove.js, packages/amplify-codegen/src/codegen-config/AmplifyCodeGenConfig.js, packages/amplify-codegen/src/commands/remove.js, packages/amplify-codegen/src/constants.js, packages/amplify-codegen/src/index.js
Add support for removal of API from codegen
#496
=> feat(amplify-codegen): add remove support

packages/amplify-codegen/commands/codegen/remove.js, packages/amplify-codegen/src/codegen-config/AmplifyCodeGenConfig.js, packages/amplify-codegen/src/commands/remove.js, packages/amplify-codegen/src/constants.js, packages/amplify-codegen/src/index.js
Add support for removal of API from codegen
=> feat(amplify-codegen): add remove support (#510)

packages/amplify-provider-awscloudformation/lib/configuration-manager.js
=> fix(amplify-provider-awscloudformation): fix: #559

.circleci/amplify_init.exp, .circleci/config.yml, packages/amplify-category-notifications/lib/pinpoint-helper.js, packages/amplify-category-notifications/lib/writeAmplifyMeta.js, packages/amplify-provider-awscloudformation/lib/configuration-manager.js, packages/amplify-provider-awscloudformation/lib/initializer.js
some code refactoring in 
amplify-provider-awscloudformation
amplify-category-notifications
also updated the circleci integration test script 
=> fix(amplify-provider-awscloudformation): integration test

packages/amplify-category-interactions/provider-utils/awscloudformation/service-walkthroughs/lex-walkthrough.js, packages/amplify-category-interactions/provider-utils/supported-services.json
Adding default voiceId to bot sample, fix book hotel question
=> feat(amplify-category-interactions) Adding default voiceId to bot sample, fix book hotel question

packages/amplify-category-interactions/provider-utils/awscloudformation/service-walkthroughs/lex-walkthrough.js, packages/amplify-category-interactions/provider-utils/supported-services.json
Add default voiceId for bot samples, fix book hotel question
=> feat(amplify-category-interactions) Add default voide for samples, fix book hotel question

packages/graphql-dynamodb-transformer/src/resources.ts, packages/graphql-elasticsearch-transformer/src/resources.ts
Fixing #591
See PR #596 for details. This is an exact copy of that PR on a different branch.
=> Fixing #591

packages/amplify-graphql-types-generator/package.json
=> fix: lock version number of @types/yargs

packages/amplify-category-auth/commands/auth/console.js, packages/amplify-category-auth/index.js, packages/amplify-category-auth/package.json, packages/amplify-category-auth/provider-utils/awscloudformation/index.js
Implemented console command for auth
=> feat(amplify-category-auth): console

packages/amplify-cli/bin/amplify
Fails with comment on  Mac, so removed the comment line.
=> Removed Comment line to work on Mac

packages/amplify-provider-awscloudformation/lib/configuration-manager.js, packages/amplify-provider-awscloudformation/lib/initializer.js, packages/amplify-provider-awscloudformation/lib/system-config-manager.js, packages/amplify-provider-awscloudformation/src/aws-utils/aws-pinpoint.js
#613 
allows cli to assume IAM role to access aws resources, as described in [this doc](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html#cli-configure-role-mfa)
Note that this implementation does not include using MFA
=> feat(amplify-provider-awscloudformation): assume role

packages/amplify-provider-awscloudformation/index.js, packages/amplify-provider-awscloudformation/lib/configuration-manager.js, packages/amplify-provider-awscloudformation/lib/initializer.js, packages/amplify-provider-awscloudformation/lib/system-config-manager.js, packages/amplify-provider-awscloudformation/src/aws-utils/aws.js
=> fix(amplify-provider-awscloudformation): fix profile loading

packages/amplify-provider-awscloudformation/src/aws-utils/aws-pinpoint.js
Related to #513, #695
This extends #522 for the new supported region.
=> feat(amplify-provider-awscloudformation): add pinpoint eu-central-1 region

packages/amplify-category-hosting/lib/S3AndCloudFront/configuration-manager.js, packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/configure-CloudFront.js, packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/configure-Publish.js, packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/configure-Website.js, packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/file-scanner.js, packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/file-uploader.js, packages/amplify-category-hosting/lib/S3AndCloudFront/index.js
#261
#593
- index and error doc configuration input validation
- sanity check before uploading files, warn user if index file is missing, error out if distribution folder is missing or empty
- If hosting bucket has not been created yet (in between `add` and a successful `push`), `configure` allows the user to change the bucket name. 
=> refactor(amplify-category-hosting): hosting ux improvement

packages/amplify-category-analytics/provider-utils/awscloudformation/cloudformation-templates/pinpoint-cloudformation-template.json, packages/amplify-category-notifications/lib/auth-helper.js
In order to get the context of Pinpoint endpoints of certain user.
=> Add a new Pinpoint policy to the auth and unauth role

packages/amplify-category-function/provider-utils/awscloudformation/cloudformation-templates/lambda-cloudformation-template.json.ejs
=> feat: add metadata in lambda CFN for it to be compatible and worked with using SAM CLI

packages/amplify-category-analytics/provider-utils/awscloudformation/cloudformation-templates/pinpoint-cloudformation-template.json, packages/amplify-category-notifications/lib/auth-helper.js
=> add getUserEndpoints Policy to Pinpoint

packages/amplify-category-hosting/lib/S3AndCloudFront/configuration-manager.js, packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/configure-CloudFront.js, packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/configure-Publish.js, packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/configure-Website.js, packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/file-scanner.js, packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/file-uploader.js, packages/amplify-category-hosting/lib/S3AndCloudFront/index.js, packages/amplify-provider-awscloudformation/src/aws-utils/aws-pinpoint.js
#261
#593
- index and error doc configuration input validation
- sanity check before uploading files, warn user if index file is missing, error out if distribution folder is missing or empty
- If hosting bucket has not been created yet (in between `add` and a successful `push`), `configure` allows the user to change the bucket name. 
=> refactor(amplify-category-hosting): multienv hosting ux improvement

packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.js, packages/amplify-cli/src/extensions/amplify-helpers/update-backend-config.js
Fixes issue - https://github.com/aws-amplify/amplify-cli/issues/708
=> fix: update dependsOn block when updating api

packages/amplify-cli/src/commands/env.js
Fix help message `sync` to `pull`.
=> fix: Fix help message `sync` to `pull`.

packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/configure-Website.js, packages/amplify-provider-awscloudformation/commands/awscloudformation/reset-cache.js, packages/amplify-provider-awscloudformation/lib/configuration-manager.js, packages/amplify-provider-awscloudformation/lib/constants.js, packages/amplify-provider-awscloudformation/lib/initializer.js, packages/amplify-provider-awscloudformation/lib/system-config-manager.js
#680
#709 
#719
#59
add mfa support when assume role
add cache for temp credentials. 
=>  feat(amplify-provider-awscloudformation): mfa support (multienv)

packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs
Adds the UpdateReplacePolicy ('retain') to the Auth User Pool template.
=> UpdateReplacePolicy (multienv)

package.json
update release script to remove --cd-version
=> ci: update release script

package.json
=> build: update the release script to mark multienv pre release

packages/amplify-category-interactions/provider-utils/awscloudformation/cloudformation-templates/lex-cloudformation-template.json.ejs
=> fix(amplify-category-interactions): fix interactions unauth role policy

package.json
=> build: update multienv release to be canary

packages/graphql-elasticsearch-transformer/src/resources.ts
=> Fixing typo bug in search resolvers

packages/amplify-cli/src/lib/migrate-project.js, packages/amplify-graphql-docs-generator/package.json, packages/graphql-connection-transformer/package.json, packages/graphql-dynamodb-transformer/package.json, packages/graphql-elasticsearch-transformer/package.json, packages/graphql-http-transformer/package.json, packages/graphql-transformer-core/package.json
=> Add warning message for migration + fix cloudform package versions in transformer

packages/amplify-codegen/src/constants.js
=> docs(amplify-codegen): make codegen max depth msg descriptive

packages/amplify-cli/src/lib/init-steps/s0-analyzeProject.js, packages/amplify-provider-awscloudformation/lib/push-resources.js
=> Remove beta version warning + add check for s3 templates when forming nested stacks

packages/amplify-cli/CHANGELOG.md, packages/amplify-cli/package.json, packages/amplify-codegen/CHANGELOG.md, packages/amplify-codegen/package.json, packages/amplify-provider-awscloudformation/CHANGELOG.md, packages/amplify-provider-awscloudformation/package.json
- @aws-amplify/cli@1.1.1
- amplify-codegen@1.0.7
- amplify-provider-awscloudformation@1.0.7
=> Release: v 1.1.1

packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js, packages/amplify-provider-awscloudformation/lib/upload-appsync-files.js, packages/graphql-transformer-core/src/util/amplifyUtils.ts
#888, #881
This fixes the revert behavior for certain failure cases in the Amplify migration process.
=> Fixing revert bug with failed seconday update during migration

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/usage-question.md
=> Update issue template 

packages/amplify-graphql-docs-generator/package.json
=> fix(amplify-graphql-docs-generator): update prettier version

packages/amplify-category-notifications/lib/notifications-manager.js, packages/amplify-provider-awscloudformation/lib/display-helpful-urls.js
=> fix(amplify-provider-awscloudformation): fix pinpoint console url

packages/amplify-category-notifications/lib/notifications-manager.js, packages/amplify-category-storage/provider-utils/awscloudformation/cloudformation-templates/s3-cloudformation-template.json
=> feat(amplify-category-storage): add s3 multipart upload to cfn

packages/amplify-category-api/index.js
=> fix(amplify-category-api): add check for provider during migration

package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js
When push fails due to cloud formation errors show the error message from cloud formation in console and provide a link to failed stack events
=> feat(amplify-provider-awscloudformation): show CFN error when push fail 

packages/amplify-e2e-tests/package.json
=> test(amplify-e2e-tests): add setup profile step for e2e tests

.circleci/config.yml
=> ci: use team account's NPM_TOKEN

packages/amplify-provider-awscloudformation/lib/initialize-env.js
=> fix(amplify-provider-awscloudformation): fix #931

.circleci/config.yml
=> build: temporarily remove amplify e2e tests

packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs, packages/amplify-cli/src/extensions/amplify-helpers/get-when-function.js, packages/amplify-cli/tests/amplify-helpers/get-when.test.js
=> Fixing #882

packages/amplify-cli/src/commands/env/remove.js
- Fix mispelling in delete instructions
=> fix: mispelling with amplify delete instructions

packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/file-uploader.js, packages/amplify-category-hosting/lib/S3AndCloudFront/index.js, packages/amplify-category-hosting/lib/S3AndCloudFront/template.json
*Issue #, if available:* N/A
Transition from public bucket to private bucket with public objects. This is to follow AWS best practices around bucket policies.
Rebase as asked for here: #798
=> feat(amplify-provider-awscloudformation): transition to private bucket

packages/amplify-provider-awscloudformation/lib/aws-regions.js
=> feat: added EU-WEST-2(London) support

.circleci/config.yml, packages/amplify-e2e-tests/__tests__/delete.test.ts, packages/amplify-e2e-tests/__tests__/init.test.ts
=>  test(amplify-e2e-tests): increase timeout 

packages/amplify-category-auth/provider-utils/awscloudformation/assets/cognito-defaults.js, packages/amplify-category-auth/provider-utils/awscloudformation/assets/string-maps.js, packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs, packages/amplify-category-auth/provider-utils/awscloudformation/index.js, packages/amplify-category-auth/provider-utils/awscloudformation/question-factories/core-questions.js, packages/amplify-category-auth/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js, packages/amplify-category-auth/provider-utils/supported-services.json, packages/amplify-provider-awscloudformation/src/resourceParams.js
=> auth-flow to feature branch

packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs, packages/amplify-frontend-android/lib/frontend-config-creator.js, packages/amplify-frontend-ios/lib/frontend-config-creator.js, packages/amplify-frontend-javascript/lib/frontend-config-creator.js, packages/amplify-provider-awscloudformation/lib/display-helpful-urls.js
=> feat(amplify-category-auth): support for setup of hosted ui/oAuth

Readme.md
- sentence structure
- Using which in back-to-back sentences
- Missing period leads to inconsistency
=> Minor Changes to README.md

packages/amplify-category-auth/provider-utils/awscloudformation/assets/cognito-defaults.js, packages/amplify-category-auth/provider-utils/awscloudformation/assets/string-maps.js, packages/amplify-category-auth/provider-utils/awscloudformation/question-factories/core-questions.js, packages/amplify-category-auth/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js
fixes warning messages, muli-dimensional array bug, and username mapping
=> fixes warning messages, muli-dimensional array bug, and username mapping

packages/amplify-category-notifications/commands/notifications/add.js, packages/amplify-category-notifications/commands/notifications/configure.js, packages/amplify-category-notifications/commands/notifications/remove.js, packages/amplify-category-notifications/lib/multi-env-manager.js, packages/amplify-cli/src/extensions/amplify-helpers/on-category-outputs-change.js, packages/amplify-cli/src/lib/initialize-env.js, packages/amplify-codegen/src/commands/add.js, packages/amplify-codegen/src/utils/updateAmplifyMeta.js, packages/amplify-frontend-javascript/lib/frontend-config-creator.js
promise not awaited, resulting aws-exports not generating.
https://github.com/aws-amplify/amplify-cli/issues/186
https://github.com/aws-amplify/amplify-cli/issues/1051
return promise from ```copyBatch``` to the top.
please do let me know how can i create a test for this change.
=> fix(amplify-cli): promise not resolving in lts/dubnium

packages/amplify-category-auth/provider-utils/awscloudformation/index.js, packages/amplify-category-auth/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js, packages/amplify-category-auth/provider-utils/supported-services.json
Syncs hostedUICreds in team provider upon env update.
=> implemented env updating

packages/amplify-category-auth/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js
=> fixing unneeded userNameAttributes when username selected

packages/amplify-category-auth/provider-utils/awscloudformation/question-factories/core-questions.js
=> missing function param

packages/amplify-category-auth/provider-utils/awscloudformation/index.js
=> headless mode

packages/amplify-category-auth/provider-utils/awscloudformation/assets/string-maps.js, packages/amplify-category-auth/provider-utils/awscloudformation/index.js, packages/amplify-category-auth/provider-utils/awscloudformation/question-factories/core-questions.js, packages/amplify-category-auth/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js, packages/amplify-category-auth/provider-utils/supported-services.json
fixing bug with amazon key name
=> fixing bug with amazon key name

packages/amplify-category-auth/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js, packages/amplify-category-auth/provider-utils/supported-services.json
=> Hosted ui and crud

packages/amplify-category-api/provider-utils/awscloudformation/cloudformation-templates/apigw-cloudformation-template-default.json.ejs, packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js
Cloud formation and parameters fixes for API and Storage.
=> cloudformation error fixes

packages/amplify-category-auth/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js, packages/amplify-category-auth/provider-utils/supported-services.json
Asks basic questions on default.
=> asks basic questions even on default

packages/amplify-category-auth/provider-utils/awscloudformation/assets/string-maps.js, packages/amplify-category-auth/provider-utils/awscloudformation/question-factories/core-questions.js, packages/amplify-category-auth/provider-utils/supported-services.json, packages/amplify-category-auth/tests/provider-utils/core-questions.test.js
=> unit tests and minor fixes (regex)

packages/graphql-auth-transformer/package.json
=> revert dependency change

packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs
re #1105 
Lambda is ending support for creation of functions with Node 6.10, hence upgrading the node versions for custom resources to 8.10.
=> feat: upgrade custom resources (in auth cfn) node version to 8.10 from 6.10

packages/amplify-provider-awscloudformation/lib/display-helpful-urls.js
=> fix: fix the hosted UI links after a push and on amplify status

packages/amplify-e2e-tests/Readme.md
=> docs(amplify-e2e-test): Create Readme.md

packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs, packages/amplify-frontend-android/lib/frontend-config-creator.js, packages/amplify-frontend-ios/lib/frontend-config-creator.js
=> fix: fixing native appclient config and auth cfn template

packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs
=> fix: remove extra app client settings

packages/amplify-category-auth/provider-utils/awscloudformation/assets/string-maps.js
=> fix: fix edit label for default configuration

.circleci/enable_auth.exp
=> test: fix auth integration test

.circleci/enable_auth.exp
=> test: fix integ test for auth

packages/amplify-category-auth/provider-utils/supported-services.json
=> fix: fix redirect URI regex

packages/amplify-category-xr/lib/auth-helper.js, packages/amplify-category-xr/lib/xr-manager.js, packages/amplify-category-xr/package.json
- Revert fuzzy scene configuration match plugin
=> Revert fuzzy

packages/amplify-category-xr/lib/xr-manager.js
- use validate prompt for file path error
=> chore: use validate prompt for file path error

packages/amplify-cli/src/lib/init-steps/s9-onSuccess.js, packages/amplify-cli/src/lib/initialize-env.js
=> fix: fixes update of aws exports when switching envs

packages/amplify-cli/src/extensions/amplify-helpers/get-resource-outputs.js
=> fix: fix #1201

.gitignore, packages/amplify-cli/.gitignore
=> build: add package-lock.json file to amplify-cli package

.gitignore, packages/amplify-cli/.gitignore
Reverts aws-amplify/amplify-cli#1207
=> Revert "build: add package-lock.json file to amplify-cli package"

package.json
Reverts aws-amplify/amplify-cli#1208
=> Revert "build: avoid removing package-lock files in production-build command"

packages/amplify-category-storage/provider-utils/awscloudformation/cloudformation-templates/s3-cloudformation-template.json, packages/amplify-category-storage/provider-utils/awscloudformation/default-values/s3-defaults.js, packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js
Fixes bug on auth access only selection.
=> fixing bug fix for no guest access

packages/amplify-category-auth/provider-utils/supported-services.json, packages/amplify-e2e-tests/Readme.md, packages/amplify-e2e-tests/__tests__/auth.test.ts, packages/amplify-e2e-tests/sample.env, packages/amplify-e2e-tests/src/categories/auth.ts, packages/amplify-e2e-tests/src/init/amplifyPush.ts, packages/amplify-e2e-tests/src/init/index.ts, packages/amplify-e2e-tests/src/utils/index.ts, packages/amplify-e2e-tests/src/utils/sdk-calls.ts
First pass at e2e tests for auth.
=> auth e2e tests

packages/amplify-category-auth/provider-utils/awscloudformation/assets/string-maps.js
=> fix: fix #1254

packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs
makes schema attribute conditional
fix #1247
#1247 
=> fix(amplify-category-auth): fixes cloudformation template

packages/amplify-category-function/provider-utils/awscloudformation/function-template-dir/crud-app.js.ejs
in the sample lambda function, add the error status code in the http response
fix #1003
=> fix(amplify-category-function): add error status code

packages/amplify-category-auth/provider-utils/awscloudformation/assets/string-maps.js
=> fix: fix #1264

packages/amplify-graphql-types-generator/src/angular/index.ts
angular types generator crashed when an query/mutation or subscription had a scalar return type.
Conditionally rendering Typescript interfaces for object type and setting the correct type for the
method signature
fix #1121
=> fix(amplify-graphql-types-generator): angular service gen scalar support

packages/amplify-e2e-tests/src/init/deleteProject.ts
=> test:(amplify-e2e-tests)delete S3 bucket after test

.circleci/config.yml, packages/graphql-transformers-e2e-tests/src/__tests__/ConnectionsWithAuthTests.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/PerFieldAuthTests.e2e.test.ts
Fixing the CircleCI issues introduced by per-field-auth merge.
=> test(graphql-transformers-e2e-tests): fix integration tests

packages/amplify-category-auth/provider-utils/awscloudformation/assets/string-maps.js
#1335 
Changes 'default' to 'public_profile' for login with facebook attribute mapping scope value.
=> fix(amplify-category-auth) #1335

packages/amplify-category-analytics/provider-utils/awscloudformation/cloudformation-templates/pinpoint-cloudformation-template.json, packages/amplify-category-interactions/provider-utils/awscloudformation/cloudformation-templates/lex-cloudformation-template.json.ejs, packages/amplify-category-interactions/provider-utils/awscloudformation/function-template-dir/index.js.ejs
=> refactor(amplify-category-analytics): update lambda node version

packages/amplify-graphql-types-generator/src/swift/helpers.ts
Added a black list to prevent singularization of `delta` -> `deltum`
fixes #1328
=> fix(amplify-graphql-types-generator): add inflection black list

packages/amplify-frontend-android/lib/frontend-config-creator.js, packages/amplify-frontend-ios/lib/frontend-config-creator.js
=> feat: add ClientDatabasePrefix to support mixed auth

packages/amplify-provider-awscloudformation/package.json
=> feat: bump aws-sdk ver to support mixed auth

packages/amplify-provider-awscloudformation/lib/upload-appsync-files.js
#1430
#1430
Ensuring build directory exists before write.
=> fix(amplify-provider-awscloudformation): ensure build directory exist

package.json
=> chore(@aws-amplify/cli): pin monorepo pkg versions

packages/amplify-category-hosting/__tests__/lib/S3AndCloudFront/s3Index.test.js
=> build: fix hosting unit tests

packages/amplify-frontend-android/lib/frontend-config-creator.js, packages/amplify-frontend-ios/lib/frontend-config-creator.js
=> fix: conditionally generation of oAuth config for iOS and Android

packages/amplify-category-auth/provider-utils/awscloudformation/index.js
=> fix: fix cognito user pool and idpool console links 

packages/amplify-category-auth/provider-utils/awscloudformation/assets/cognito-defaults.js, packages/amplify-category-auth/provider-utils/awscloudformation/index.js
Issue #389
Updated cognito project names to reflect names of client project.
=> Add project name to cognito user & identity pool name

packages/amplify-provider-awscloudformation/lib/initializer.js, packages/amplify-provider-awscloudformation/lib/system-config-manager.js, packages/amplify-provider-awscloudformation/package.json, packages/amplify-provider-awscloudformation/src/aws-utils/aws-pinpoint.js, packages/amplify-provider-awscloudformation/src/aws-utils/aws.js
fix #459
Issue #459
Add proxy support for amplify-cli. Second pull request because I've messed up the rebase in #869 
=> #459 feat: add proxy support

packages/graphql-function-transformer/src/FunctionTransformer.ts, packages/graphql-function-transformer/src/lambdaArns.ts, packages/graphql-transformers-e2e-tests/src/__tests__/NoneEnvFunctionTransformer.e2e.test.ts
Updating for comment here #1346 (comment)
Handling NONE env in @function directive.
=> fix(graphql-function-transformer): Handling NONE env in @function.

packages/graphql-relational-schema-transformer/src/RelationalDBTemplateGenerator.ts
=> fix(graphql-relational-schema-transformer): add additional RDS Policies

packages/amplify-category-function/provider-utils/awscloudformation/cloudformation-templates/lambda-cloudformation-template.json.ejs
=> fix: stringify region in function Cloudformation file

packages/amplify-category-auth/provider-utils/supported-services.json
fix #1513 
modifies hostedUIDomainName to exclude aws, amazon reserved words
=> fix(amplify-category-auth): fix domain reserved words

packages/amplify-category-hosting/__tests__/lib/S3AndCloudFront/helpers/cloudfront-manager.test.js, packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/cloudfront-manager.js
=> fix(amplify-category-hosting): fix CloudFront invalidation bug

packages/graphql-key-transformer/src/KeyTransformer.ts, packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformer.e2e.test.ts
Fixes #1554
Correctly parses a filter expression returned by a utility method.
=> fix(graphql-key-transformer) - Fixing #1554

packages/amplify-category-analytics/lib/pinpoint-helper.js, packages/amplify-category-notifications/lib/pinpoint-helper.js
A simple fix for a couple of spelling mistakes in CLI output
=> fix: spelling mistakes in cli output

packages/amplify-category-function/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js
=> fix: fixing auth update flow

packages/amplify-provider-awscloudformation/lib/initializer.js, packages/amplify-provider-awscloudformation/lib/system-config-manager.js
=> fix(amplify-provider-awscloudformation): fix general configeLevel init

packages/amplify-provider-awscloudformation/lib/initializer.js, packages/amplify-provider-awscloudformation/lib/system-config-manager.js
=> fix(amplify-provider-awscloudformation): fix http proxy 

packages/amplify-category-function/provider-utils/awscloudformation/cloudformation-templates/lambda-cloudformation-template.json.ejs, packages/amplify-category-function/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js
=> fix: fixing ref name values in function cfn templates

packages/amplify-category-auth/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js
*Issue ##1595*
Fix cognito ARN for Permission Policies
=> fix(amplify-category-auth): provide correct arn in permission policies

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js
=> fix: fixing the IAM policies for AppSync API

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js
=> feat: add graphQLEndpoint as an env var to lambda functions

packages/amplify-e2e-tests/package.json, packages/amplify-graphql-docs-generator/package.json, packages/amplify-graphql-types-generator/package.json, packages/amplify-graphql-types-generator/src/flow-modern/helpers.ts, packages/graphql-auth-transformer/package.json, packages/graphql-connection-transformer/package.json, packages/graphql-dynamodb-transformer/package.json, packages/graphql-elasticsearch-transformer/package.json, packages/graphql-http-transformer/package.json, packages/graphql-mapping-template/package.json, packages/graphql-relational-schema-transformer/package.json, packages/graphql-transformer-common/package.json, packages/graphql-transformer-core/package.json, packages/graphql-transformers-e2e-tests/package.json, packages/graphql-versioned-transformer/package.json, yarn.lock
=> build: upgrade typescript to 3.5.1

packages/amplify-category-function/provider-utils/awscloudformation/cloudformation-templates/lambda-cloudformation-template.json.ejs
add index to the lambda function execution policy resource so that the lambda function can carry out
actions on GSIs
fix #791
=> fix(amplify-category-function): add policy for GSI

packages/amplify-category-function/provider-utils/awscloudformation/index.js, packages/amplify-category-function/provider-utils/supported-services.json
*Issue #691*
*Issue #1187*
Provides third question on `amplify function xxx invoke` which allows to points custom event json file
=> feat(amplify-category-function): provide evntName arg to lambda_invoke

packages/amplify-category-api/index.js
=> fix(amplify-category-api): fix init env bug

packages/graphql-transformer-core/package.json, packages/graphql-transformer-core/src/index.ts, packages/graphql-transformer-core/src/util/amplifyUtils.ts, packages/graphql-transformer-core/src/util/fileUtils.ts, packages/graphql-transformer-core/src/util/transformConfig.ts, yarn.lock
Refactors the creepingly large `amplifyUtils.ts` file into `amplifyUtils.ts`, `fileUtils.ts`, and `transformConfig.ts`. This change adds more structural clarity to how the `transform.conf.json` file is read and saved. These changes enable future changes that will be using the `transform.conf.json` file to enable more detailed user configuration options. This change makes no significant functional changes.
=> refactor(graphql-transformer-core) - Refactoring amplifyUtil.ts

packages/graphql-transformer-core/src/util/amplifyUtils.ts
There was a possible error during API creation that under a NodeJS 8 version ```fs.exists``` in ```fs-extras``` was throwing an error when the argument was ```undefined``` and cause this functionality to fail.
The error message was: 
```
Failed compiling GraphQL schema:
path must be a string or Buffer
```
Under NodeJS 10 this error was not reproducible.
=> Add check for variable value in ensureMissingStackMappings

packages/amplify-category-function/provider-utils/awscloudformation/cloudformation-templates/lambda-cloudformation-template.json.ejs
update the runtime from nodejs8.10 to nodejs10.x
=> refactor(amplify-category-function): update node version

packages/amplify-category-function/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js
#1776
added semi-colon to function in policy json obj
=> style(amplify-category-function): fn cfn template style fix

packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs, packages/amplify-category-auth/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js, packages/amplify-category-function/provider-utils/awscloudformation/index.js, packages/amplify-cli/src/extensions/amplify-helpers/trigger-flow.js, packages/amplify-cli/tests/amplify-helpers/trigger-flow.test.js, packages/amplify-e2e-tests/__tests__/auth.test.ts, packages/amplify-provider-awscloudformation/lib/build-resources.js, packages/amplify-provider-awscloudformation/lib/push-resources.js
=> Triggers auth

packages/amplify-category-function/provider-utils/awscloudformation/index.js
Fixes broken e2e test by removing extra space from openEditor prompt.
=> fix(amplify-category-function): open Editor fix for displayname

packages/amplify-category-auth/provider-utils/awscloudformation/index.js, packages/amplify-category-auth/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js, packages/amplify-category-auth/provider-utils/awscloudformation/utils/trigger-flow-auth-helper.js, packages/amplify-cli/src/extensions/amplify-helpers/trigger-flow.js, packages/amplify-cli/tests/amplify-helpers/trigger-flow.test.js
Replacing relative paths w/ getCategoryPlugins.  Also accompanying unit test fixes.
=> Relative path fix

packages/amplify-e2e-tests/__tests__/init.test.ts, packages/amplify-e2e-tests/src/init/index.ts, packages/amplify-e2e-tests/src/init/initProjectHelper.ts
=> test(amplify-e2e-tests): add headless init e2e test

packages/amplify-e2e-tests/__tests__/init.test.ts, packages/amplify-e2e-tests/src/configure/index.ts
=> ci(amplify-e2e-tests): fix e2e test

packages/amplify-provider-awscloudformation/lib/initializer.js
=> fix(amplify-provider-awscloudformation): fix MFA prompt during init

packages/amplify-category-function/index.js, packages/amplify-category-function/package.json, packages/amplify-category-function/provider-utils/awscloudformation/index.js, packages/amplify-category-function/provider-utils/awscloudformation/utils/invoke.js
=> fix: remove grunt-lambda dependency for local function testing

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, yarn.lock
=> chore(cli): fix npm audit security issues

packages/amplify-cli/CHANGELOG.md, packages/amplify-cli/package.json
=> chore(release): Publish [ci skip]

packages/amplify-category-function/provider-utils/awscloudformation/index.js, packages/amplify-cli/src/extensions/amplify-helpers/push-resources.js, packages/amplify-cli/src/extensions/amplify-helpers/resource-status.js, packages/amplify-provider-awscloudformation/index.js, packages/amplify-provider-awscloudformation/lib/push-resources.js, yarn.lock
=>  feat: allow for individual resource/category push

packages/amplify-category-function/provider-utils/awscloudformation/index.js, packages/amplify-cli/src/extensions/amplify-helpers/push-resources.js
=>  fix: fix async push

.github/ISSUE_TEMPLATE/bug_report.md
=> Update amplify console forum link to GitHub

Readme.md, packages/amplify-category-predictions/.eslintignore, packages/amplify-category-predictions/Readme.md, packages/amplify-category-predictions/provider-utils/supportedPredictions.js, packages/amplify-e2e-tests/__tests__/predictions.test.ts
=> PR Feedback Changes

packages/amplify-cli/src/lib/initialize-env.js
=> fix: fixing force push on init of new env

packages/amplify-category-storage/provider-utils/awscloudformation/cloudformation-templates/dynamoDb-cloudformation-template.json.ejs
=> fix(amplify-category-storage): remove unnecessary comma

packages/amplify-category-predictions/provider-utils/supportedPredictions.js
changed wording when when selecting a predictions category
=> refactor(amplify-category-predictions): changed question wording

packages/amplify-frontend-javascript/lib/frontend-config-creator.js
https://github.com/aws-amplify/amplify-cli/issues/1205#issuecomment-517519101
Wrap evaluation of Object.keys with if statement to check if the object exists before attempting to create iterable.
=> fix: fix #1205

packages/amplify-cli/src/extensions/amplify-helpers/delete-project.js
=> Fix space in prompt

packages/amplify-category-function/provider-utils/awscloudformation/index.js, packages/amplify-e2e-tests/src/categories/predictions.ts
=> fix(amplify-e2e-tests): fixing predictions e2e tests

packages/amplify-cli/package.json, packages/amplify-dynamodb-simulator/package.json, yarn.lock
=> build: move graphqljs dep to root package

packages/amplify-appsync-simulator/src/server/operations.ts, packages/amplify-appsync-simulator/src/server/subscription.ts
=> Local mock use ip

packages/amplify-category-function/provider-utils/awscloudformation/index.js, packages/amplify-cli/package.json, packages/amplify-cli/scripts/post-install.js
=>  feat: adding post-install script

packages/amplify-provider-awscloudformation/lib/build-resources.js
*Related issue:* #659
You can now add a custom build script to the main package.json file which is executed before a function is deployed. This can be used to transpile code with babel/typescript or to copy files (like src/graphql/* to amplify/backend/function/mySpecialFunction/src/graphql).
The script must be defined in the root package.json file because npm which is executed by buildResource() will ignore any scripts defined in the resource's package.json. The name must follow the convention `amplify:<resource name>`.
**Example: Transpiling with Babel**
Add the hook to the `scripts` section of `package.json` (in the project root folder) and add dependencies:
```json
{
"scripts": {
"amplify:mySpecialFunction": "cd amplify/backend/function/mySpecialFunction; …
```
=> feat(amplify-provider-awscloudformation): hooks

packages/amplify-category-function/provider-utils/awscloudformation/index.js, packages/amplify-provider-awscloudformation/lib/push-resources.js, packages/amplify-provider-awscloudformation/lib/rootStackTemplate.json, packages/amplify-provider-awscloudformation/lib/update-idp-roles-cfn.json, packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js
=> feat: narrow-down idp roles scope

packages/amplify-category-function/provider-utils/awscloudformation/index.js, packages/amplify-provider-awscloudformation/lib/push-resources.js
=> fix: fix metric agent for tracking CLI usage

.circleci/config.yml, packages/amplify-category-function/provider-utils/awscloudformation/index.js
=>  fix: fixing installation of zip dependency on circleCI

packages/graphql-function-transformer/src/FunctionTransformer.ts
Reverts aws-amplify/amplify-cli#1746
=> Revert "Fix for invalid JSON in pipeline resolver"

packages/amplify-category-function/commands/function.js
Fixes #1978
Add 'update' command to function category command listing.
=> fix: #1978, adding update command to function category command list

.circleci/config.yml
change intendation for android test
=> fix: intendation in config.yml

.circleci/config.yml, packages/amplify-ui-tests/src/main/setup_aws_resources.ts, packages/amplify-ui-tests/src/utils/command.ts
Remove reading test user info from process
=> fix: sign up user issue

packages/amplify-util-mock/src/utils/lambda/execute.ts
=> fix(amplify-util-mock): support large response from lambda

packages/amplify-category-function/provider-utils/awscloudformation/function-template-dir/crud-app.js.ejs
#223
Generate table name instead of resource name in CRUD Lambda
=> fix: #223 - Generate table name instead of resource name in CRUD Lambda

packages/graphql-auth-transformer/src/resources.ts, packages/graphql-transformers-e2e-tests/src/__tests__/ModelAuthTransformer.e2e.test.ts
#2013 
A dedicated e2e test added beside the bugfix.
=> fix: #2013 - Dynamic group auth when groups field is null

packages/amplify-appsync-simulator/src/schema/appsync-scalars/index.ts
#2032
- add AWSTimestamp and AWSIPAddress types to mock
- fix regression for EmailAddress and URL types with mock
=> fix: #2032 - add AWSTimestamp and AWSIPAddress types to mock

packages/graphql-transformer-core/src/util/amplifyUtils.ts, packages/graphql-transformer-core/tsconfig.json
#1581 
Fix stack enumeration so transform.conf.json will be generated
=> fix: #1581 - Fix stack enumeration bug

packages/amplify-cli/src/extensions/amplify-helpers/open-editor.js
=> fix(cli): fix cli crash when opening editor

packages/amplify-cli/src/extensions/amplify-helpers/open-editor.js
=> style(cli): lint fix

.circleci/config.yml
change iOS,Android sample apps github references to AWS repos.
=> change iOS,Android sample apps github references to AWS repos

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts, packages/graphql-auth-transformer/src/ModelDirectiveConfiguration.ts, packages/graphql-auth-transformer/src/__tests__/OperationsArgument.test.ts, packages/graphql-auth-transformer/src/__tests__/__snapshots__/OperationsArgument.test.ts.snap, packages/graphql-auth-transformer/src/resources.ts, packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts, packages/graphql-dynamodb-transformer/src/ModelDirectiveArgs.ts, packages/graphql-transformers-e2e-tests/src/__tests__/ConnectionsWithAuthTests.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/PerFieldAuthTests.e2e.test.ts
re #1916 
Changed ModelSubscriptionLevel to lowercase to better fit naming
Added ModelDirectiveConfiguration
- Changed Subscriptions to use this class
Updated tests based on ModelSubscriptionLevel change
=> Added ModelDirectiveConfiguration

packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/add-to-group.js
fix(#2214)
Adds try/catch to add-to-group template.
=> fix(amplify-category-auth): fix add to group cognito trigger bug

packages/graphql-transformer-core/src/util/amplifyUtils.ts
=> fix(graphql-transformer-core): handle stack mapping on a new project

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js
=> fix(amplify-category-api): include userpool id in parameter.json

packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthModelAuthTransformer.e2e.test.ts
Fix multi-auth e2e test failure
=> fix: multiauth e2e test fix

package.json
=> change beta and release release scripts to not bump up major versions

packages/amplify-util-mock/src/__e2e__/utils/index.ts
=> test(amplify-util-mock): update logDebug to use console.log in CI flow

packages/amplify-graphql-types-generator/src/compiler/index.ts
Types generator used to fail for operations that were declared in the operation documents, that were
not supported in the schema. Updated types generator to show warning for missing operation and still
continue generation of types
fix #2228 and #1434
=> feat(amplify-graphql-types-generator): show error msg for missing query

packages/amplify-cli/src/commands/plugin/add.ts, packages/amplify-cli/src/input-manager.ts
=> refactor(cli): enhance the plugin add command to take input argument

packages/amplify-util-mock/src/storage/storage.ts
Safe access check for LambdaConfiguration when mocking S3 - this was blowing up locally.
I don't have an issue for this, I just found it.  Please let me know if I need to do anything else as required for PRs.  Thanks.
=> fix(amplify-util-mock): safe access to LambdaConfiguration

packages/graphql-transformers-e2e-tests/src/__tests__/NewConnectionWithAuth.e2e.test.ts
=> Fixe2etests

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts, packages/graphql-auth-transformer/src/__tests__/__snapshots__/OperationsArgument.test.ts.snap, packages/graphql-auth-transformer/src/resources.ts
re #2241
ensure multiple static group rules are verified per each field
=> fix(graphql-auth-transformer): verify multiple static group auth rules

package.json
=> chore: update beta publish script

packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
=> fix: fixing no-gql-override param usage in amplify push command

packages/amplify-cli/src/commands/env.js, packages/amplify-cli/src/input-manager.ts, yarn.lock
=> fix the amplify env checkout command

packages/amplify-codegen/src/codegen-config/AmplifyCodeGenConfig.js, packages/amplify-codegen/src/codegen-config/index.js, packages/amplify-codegen/src/commands/add.js, packages/amplify-codegen/src/commands/configure.js, packages/amplify-codegen/src/commands/generateStatementsAndType.js, packages/amplify-codegen/src/commands/remove.js, packages/amplify-codegen/src/commands/statements.js, packages/amplify-codegen/src/commands/types.js, packages/amplify-codegen/tests/codegen-config/index.test.js, packages/amplify-codegen/tests/commands/configure.test.js, packages/amplify-codegen/tests/commands/generateStatementsAndTypes.test.js, packages/amplify-codegen/tests/commands/statements.test.js, packages/amplify-codegen/tests/commands/types.test.js
Change loadConfig for without init
=> Load config fix

packages/graphql-transformer-core/src/TransformFormatter.ts, packages/graphql-transformer-core/src/util/amplifyUtils.ts, packages/graphql-transformer-core/src/util/splitStack.ts
N/A
As I was going through cloudformation transform files, I found some comments that were not easy
to understand. Cleaned those up, and added commentary that I think might help others understand
the current state of the object graph.
=> docs: cleaned up, added some helpful JS doc

packages/amplify-codegen/src/commands/add.js, packages/amplify-codegen/src/commands/generateStatementsAndType.js
Allow for schema.graphql as well as schema.json
=> Codegen schema graphql

packages/amplify-cli/src/context-extensions.ts
=> fix(cli): add context.print.fancy

packages/amplify-provider-awscloudformation/src/aws-utils/aws.js
=> fix(amplify-provider-awscloudformation): fix amplify configure

packages/graphql-transformer-core/src/util/transformConfig.ts
re pr #2348
added a try catch on loadConfig for transformConfig
=> [transformConfig] try/catch on loadConfig

packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
Fixes #2335 
The ```Version``` property check in ```transform.conf.json``` is changed to not to overwrite local file with cloud deployed version under any circumstances.
=> fix: #2335 - change the transform.conf.json version flag check logic

packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts, packages/graphql-transformer-common/src/definition.ts
=> fix: #2347 - enum validation for key directive

.circleci/config.yml, packages/amplify-util-mock/.gitignore, packages/amplify-util-mock/package.json, packages/amplify-util-mock/src/__e2e__/connections-with-auth-tests.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/function-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/key-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/key-with-auth.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/model-auth-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/multi-auth-model-auth-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/per-field-auth-tests.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/utils/cognito-utils.ts, yarn.lock
=> Run mock e2e as part of PR process

packages/graphql-auth-transformer/src/resources.ts
added staticgroupVar function to staticGroupAuthorizationVariable function
=> fix(graphql-auth-transformer): added staticgroupVar function

.circleci/config.yml, codecov.yml, package.json, yarn.lock
=> ci: collect code coverage and publish it to codecov

packages/amplify-appsync-simulator/package.json, packages/amplify-category-hosting/package.json, packages/amplify-category-notifications/package.json, packages/amplify-category-xr/package.json, packages/amplify-cli/package.json, packages/amplify-dynamodb-simulator/package.json, packages/amplify-graphql-types-generator/package.json, packages/graphql-auth-transformer/package.json, packages/graphql-connection-transformer/package.json, packages/graphql-dynamodb-transformer/package.json, packages/graphql-elasticsearch-transformer/package.json, packages/graphql-function-transformer/package.json, packages/graphql-http-transformer/package.json, packages/graphql-key-transformer/package.json, packages/graphql-mapping-template/package.json, packages/graphql-transformer-core/package.json
=> ci: collect coverage from all unit tests

packages/amplify-util-mock/package.json, packages/amplify-util-mock/src/__e2e__/subscriptions-with-auth.e2e.test.ts, packages/graphql-transformers-e2e-tests/package.json, packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts, yarn.lock
adding e2e subscriptions with auth
depedent on pr #2368
=> test(graphql-transformers-e2e-tests): adding subscriptions with auth e2e

.circleci/config.yml, package.json
=> ci: run unit test serially to prevent running out of memory

.circleci/config.yml, packages/amplify-ui-tests/src/utils/command.ts, yarn.lock
=> ci(amplify-ui-tests): update the cypress test status determination

packages/amplify-appsync-simulator/src/server/operations.ts
appsync simulator gave generic error "Invalid token specified: Cannot read property 'replace' of undefined" if the JWT token passed
to the mock server was not a valid token. Update the authorization code to show friendlier error message when the JWT token is invalid
fix #2473
=> fix(amplify-appsync-simulator): handle jwt decode error gracefully

packages/amplify-category-predictions/provider-utils/awscloudformation/assets/convertQuestions.js
Update language options to support new languages in Amazon Translate:
[Greek, Hungarian, Romanian, Thai, Ukrainian, Urdu and Vietnamese](https://aws.amazon.com/blogs/aws/new-languages-for-amazon-translate-greek-hungarian-romanian-thai-ukrainian-urdu-and-vietnamese/)
=> update translate options

Third Party Licenses.txt
=> chore: add mosca attribution

.editorconfig
Add an ```.editorconfig``` to the project to complement the prettier settings.
=> feat: add editorconfig to project

packages/amplify-util-mock/src/__e2e__/model-connection-transformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/ModelConnectionTransformer.e2e.test.ts
added e2e tests to test connection limit
=> test: add limit connection e2e tests

packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js, packages/graphql-transformer-core/src/util/amplifyUtils.ts
allows gql-compile to create a build parameters file
#1960 
=> fix(amplify-provider-awscloudformation): build api project w/ params

packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js, packages/graphql-auth-transformer/package.json, packages/graphql-auth-transformer/src/ModelAuthTransformer.ts, packages/graphql-auth-transformer/src/__tests__/SearchableAuthTransformer.test.ts, packages/graphql-auth-transformer/src/__tests__/__snapshots__/SearchableAuthTransformer.test.ts.snap, packages/graphql-auth-transformer/src/resources.ts, packages/graphql-elasticsearch-transformer/src/resources.ts, packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/SearchableWithAuthTests.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/cognitoUtils.ts
re #1043
added auth logic for `@searchable`
=> auth on @searchable

packages/amplify-util-mock/package.json, packages/graphql-transformers-e2e-tests/package.json, packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts, yarn.lock
- update correct logic for auth on subscriptions e2e
- add ws version 4.0.0 to subscription e2e tests
=> test: update auth on subs e2e

packages/amplify-graphiql-explorer/src/serviceWorker.ts, packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts, packages/graphql-http-transformer/src/resources.ts, packages/graphql-transformer-core/src/GraphQLTransform.ts
=> fix: fixed typo on serviceWorker for graphiql explorer package 🐜

packages/amplify-dynamodb-simulator/.npmignore, packages/amplify-dynamodb-simulator/package.json
=>  build(amplify-dynamodb-simulator): download ddb local when building pkg

packages/amplify-provider-awscloudformation/lib/initializer.js
=> feat: add amplify prefix to every cfn stack provisioned via the CLI

packages/graphql-auth-transformer/src/resources.ts, packages/graphql-elasticsearch-transformer/src/SearchableModelTransformer.ts
add total field in SearchableXObjectConnection and add auth logic to protect that response
#2600
=> feat(graphql-elasticsearch-transformer): add total in es response

lerna.json, package.json, packages/amplify-appsync-simulator/package.json, packages/amplify-cli/package.json, packages/amplify-e2e-tests/package.json, packages/amplify-graphiql-explorer/package.json, packages/amplify-graphql-docs-generator/package.json, packages/amplify-graphql-types-generator/package.json, packages/amplify-storage-simulator/package.json, packages/amplify-ui-tests/package.json, packages/amplify-util-mock/package.json, packages/amplify-util-mock/src/__e2e__/subscriptions-with-auth.e2e.test.ts, packages/graphql-auth-transformer/package.json, packages/graphql-connection-transformer/package.json, packages/graphql-dynamodb-transformer/package.json, packages/graphql-elasticsearch-transformer/package.json, packages/graphql-function-transformer/package.json, packages/graphql-http-transformer/package.json, packages/graphql-key-transformer/package.json, packages/graphql-mapping-template/package.json, packages/graphql-relational-schema-transformer/package.json, packages/graphql-transformer-common/package.json, packages/graphql-transformer-core/package.json, packages/graphql-transformers-e2e-tests/package.json, packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformerLocal.e2e.test.ts, packages/graphql-versioned-transformer/package.json, yarn.lock
Fix build break caused by a recent merge.
=> fix: build break, chore: typescript, lerna update

packages/amplify-e2e-tests/__tests__/auth.test.ts
=> test: fix auth e2e test

packages/amplify-e2e-tests/src/categories/storage.ts
=> test: fix storage e2e tests

packages/amplify-cli/src/commands/pull.js, packages/amplify-cli/src/commands/push.js, packages/amplify-cli/src/lib/initialize-env.js, packages/amplify-provider-awscloudformation/lib/amplify-service-manager.js
=> Console integration

packages/graphql-key-transformer/src/KeyTransformer.ts, packages/graphql-transformers-e2e-tests/src/__tests__/MutationCondition.e2e.test.ts
fix: build break after recent merges
=> fix: build break after recent merges

packages/graphql-key-transformer/src/KeyTransformer.ts
=> fix(graphql-key-transformer): fix merge errors

.circleci/config.yml, packages/amplify-category-storage/provider-utils/awscloudformation/default-values/s3-defaults.js, packages/amplify-category-storage/provider-utils/supported-services.json, packages/amplify-e2e-tests/__tests__/migration/api.connection.migration.test.ts
=> Test update

packages/graphql-key-transformer/src/KeyTransformer.ts, packages/graphql-mapping-template/src/dynamodb.ts
=> Fix issues discovered when running graphql e2e tests

packages/amplify-e2e-tests/src/categories/api.ts
=> test(amplify-e2e-tests): update test to account for updated API workflow

package.json
updated canary release script to force publish all the packages and to include the merge tags
=> ci: update canary release script

packages/graphql-dynamodb-transformer/src/resources.ts, yarn.lock
=> fix(graphql-dynamodb-transformer): fix cloudformation error config

packages/amplify-app/src/index.js, packages/amplify-app/src/xcodeHelpers.js
Create ios config files and add files/folders to xcode
=> (feat) iOS helper files

packages/amplify-cli/src/commands/push.js, packages/amplify-cli/src/lib/initialize-env.js, packages/amplify-e2e-tests/__tests__/auth.test.ts, packages/amplify-e2e-tests/src/init/amplifyPush.ts
=> fix(cli): remove extra prompt in the new push workflow

packages/amplify-cli/src/commands/publish.js, packages/amplify-cli/src/commands/push.js
=> feat(cli): update publish command to use the updated push command

packages/amplify-appsync-simulator/src/velocity/value-mapper/string.ts
Add length() functionality to string type when running in mock. 
=> feat: add the length support for strings in mock

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js, packages/amplify-cli/src/context-extensions.ts, packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
=> API Workflow Changes

__tests__/visitors/appsync-visitor.test.ts, packages/amplify-codegen-appsync-model-plugin/package.json, packages/amplify-codegen-appsync-model-plugin/src/__tests__/utils/process-connections.test.ts, packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-visitor.test.ts, packages/amplify-codegen-appsync-model-plugin/src/configs/java-config.ts, packages/amplify-codegen-appsync-model-plugin/src/languages/swift-declaration-block.ts, packages/amplify-codegen-appsync-model-plugin/src/preset.ts, packages/amplify-codegen-appsync-model-plugin/src/scalars/supported-directives.ts, packages/amplify-codegen-appsync-model-plugin/src/utils/addFieldToType.ts, packages/amplify-codegen-appsync-model-plugin/src/utils/process-connections.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-java-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-json-metadata-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-swift-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts, packages/amplify-codegen/src/commands/models.js, packages/amplify-e2e-tests/src/init/initProjectHelper.ts, packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts, yarn.lock
=> Model Gen fixes

packages/amplify-app/package.json, packages/amplify-app/src/index.js, yarn.lock
Use the semver package to validate node and cli versions, updating cli version if necessary
=> (fix) Use semver package

packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-java-visitor.ts
added fromId static method to the generated java class
=> feat(amplify-codegen-appsync-model-plugin): add fromId method

packages/amplify-cli/src/extensions/amplify-helpers/trigger-flow.js, packages/amplify-e2e-tests/src/categories/api.ts, packages/amplify-e2e-tests/src/categories/storage.ts
Fix e2e test failures:
- init a project and add/update ddb table with & without trigger
- init a project and add the simple_model api with multiple authorization providers
=> fix: e2e tests, lint error

packages/amplify-codegen-appsync-model-plugin/src/configs/swift-config.ts, packages/amplify-codegen-appsync-model-plugin/src/languages/swift-declaration-block.ts, packages/amplify-codegen-appsync-model-plugin/src/scalars/index.ts, packages/amplify-codegen-appsync-model-plugin/src/utils/fieldUtils.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-java-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-javascript-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-json-metadata-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-swift-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-typescript-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts
=> Codegen connection

package.json, packages/amplify-codegen-appsync-model-plugin/package.json, yarn.lock
=> Missing pkg

packages/amplify-provider-awscloudformation/lib/amplify-service-manager.js, yarn.lock
fix #2868
In collecting the existing local appId in the team-provider-info.json, the current CLI does not check for duplicate entries, and causes the bug reported by the customer. This PR fixes that. 
=> fix(amplify-provider-awscloudformation): fix multi env creation bug

packages/amplify-codegen-appsync-model-plugin/src/__tests__/utils/process-connections.test.ts, packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-visitor.test.ts, packages/amplify-codegen-appsync-model-plugin/src/utils/process-connections.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-java-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-swift-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts
=> Codegen fixes

packages/amplify-app/src/index.js, yarn.lock
move installation to separate function and make error check before version check
=> (fix) amplify version check in amplify app

packages/amplify-codegen-appsync-model-plugin/package.json, packages/amplify-codegen-appsync-model-plugin/src/__tests__/utils/validate-java.ts, packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap, packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-java-visitor.test.ts, packages/amplify-codegen-appsync-model-plugin/src/scalars/supported-directives.ts, yarn.lock
=> Codegen tests

packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthModelAuthTransformer.e2e.test.ts
Fix GraplQL e2e tests after policy change
=> fix: graphql e2e test deployment

packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthModelAuthTransformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/MutationCondition.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/cognitoUtils.ts
=> fix: remaining e2e tests

packages/amplify-app/src/index.js, packages/amplify-app/src/xcodeHelpers.js
Add resources instead of add sources adds files to copy bundle resources phase
=> fix: add resources in xcode helper

packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-swift-visitor.ts
Updated the swift protocol for Class loader
=> fix(amplify-codegen-appsync-model-plugin): update swift protocol

packages/graphql-transformer-core/src/util/syncUtils.ts
changed base table ttl to 30 days
=> refactor(graphql-transformer-core): change base table ttl

packages/amplify-category-api/package.json, packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js, packages/amplify-category-api/provider-utils/awscloudformation/sync-conflict-handler-assets/syncAssets.js, packages/amplify-e2e-tests/src/categories/api.ts, yarn.lock
- Added DataStore learn more text
- Removed env flag
=> API Workflow DS Update

packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-javascript-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-typescript-visitor.ts
=> fix(amplify-codegen-appsync-model-plugin): revert lazy load

packages/amplify-codegen-appsync-model-plugin/src/scalars/index.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-json-metadata-visitor.ts
added additional scalars in schema.js
=> fix(amplify-codegen-appsync-model-plugin): add additional scalars

packages/amplify-app/src/scripts/amplify-push.js
=> fix(amplify-app): support app without profile

packages/amplify-app/src/index.js
Have datastoreSync as false by default in android/ios config files
=> fix: add datastoreSync option to config files

packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
Fix transformer loading by deduplicating the code for transformer factory that was introduced in a recent PR and regressed the transformer loading.
=> fix(amplify-provider-awscloudformation): transformer loading

packages/amplify-codegen-appsync-model-plugin/src/scalars/index.ts
fix #2945
#2945
Change string to String
=> fix: correct the casing of string type

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js, packages/amplify-category-api/provider-utils/awscloudformation/sync-conflict-handler-assets/syncAssets.js
=> fix(amplify-category-api): fix conflict resolution learn more

packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js
=> fix(amplify-category-storage): add policy for GSI

packages/amplify-app/src/index.js
*Description of changes
Install cli if it doesn't satisfy the min version
=> fix: update cli if it doesn't satisify minimum version

packages/graphql-elasticsearch-transformer/streaming-lambda/python_streaming_function.py
=> fix(graphql-elasticsearch-transformer): use comma for logging

packages/amplify-codegen/package.json, yarn.lock
=> build(amplify-codegen): remove unned dependecy aws-appsync-codegen

Readme.md
Adding the changelog to the readme
No issue
Add the changelog to readme
=> Add the changelog to readme

packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js
When a stack gets updates, cloudformation provider checks the existance of root stack by running a
describe stack API call. On Amplify console, it is possible sometimes these call can be throttled if
multiple deployments are happening. Update code to retry if describeStack encounters throttling
error
fix #3019
fix #3027
=> fix(amplify-provider-awscloudformation): add retry logic

packages/amplify-category-function/provider-utils/awscloudformation/function-template-dir/index.js.ejs
added arrow function support in nodejs function template
=> arrow function support

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js, packages/amplify-e2e-tests/src/__tests__/api.test.ts, packages/amplify-e2e-tests/src/categories/api.ts
- Add resolver config in transformer config if a project/models config is present
- Add resolver config e2e test
=> resolver config workflow change + e2e tests

packages/graphql-function-transformer/package.json, packages/graphql-function-transformer/src/FunctionTransformer.ts, packages/graphql-transformer-common/package.json, packages/graphql-transformer-common/src/FunctionResourceIDs.ts, packages/graphql-transformers-e2e-tests/src/__tests__/FunctionTransformerTests.e2e.test.ts, yarn.lock
re #2468
- generated a short uuid along with the role name to keep them unique
- updated e2e tests
=> fix(graphql-function-transformer): add hash to function iam role name

packages/amplify-codegen-appsync-model-plugin/src/__tests__/utils/process-auth.test.ts, packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-visitor.test.ts, packages/amplify-codegen-appsync-model-plugin/src/utils/process-auth.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-java-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-javascript-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-json-metadata-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-swift-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-typescript-visitor.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts
Updated JS/TS data store schema to include auth directive details
=> fix(amplify-codegen-appsync-model-plugin): add auth directive info

packages/amplify-provider-awscloudformation/lib/amplify-service-migrate.js
=> fix(amplify-provider-awscloudformation): prevent console build error

packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/function-template-dir/trigger-index.js, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CustomMessage/function-template-dir/trigger-index.js, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/DefineAuthChallenge/function-template-dir/trigger-index.js, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostAuthentication/function-template-dir/trigger-index.js, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/function-template-dir/trigger-index.js, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreAuthentication/function-template-dir/trigger-index.js, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreSignup/function-template-dir/trigger-index.js, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreTokenGeneration/function-template-dir/trigger-index.js, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/VerifyAuthChallengeResponse/function-template-dir/trigger-index.js, packages/amplify-category-function/provider-utils/awscloudformation/function-template-dir/trigger-index.js
#3083 
Updates path in trigger index files to use './' instead of inherent sibling.
=> fix(amplify-category-auth)

packages/amplify-cli/src/project-config-version-check.ts
=> chore: add link to node version update info in the migration warning step

packages/graphql-elasticsearch-transformer/streaming-lambda/python_streaming_function.py, packages/graphql-transformer-core/src/index.ts, packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/stringSetMutations.ts
convert sets to lists when sending payload to es
re #2860
=> feat(graphql-elasticsearch-transformer): support sets in es fn

packages/amplify-provider-awscloudformation/lib/amplify-service-manager.js, yarn.lock
add environment variable for CLI package live update in the createapp Amplify Servce API call
Implemented console team requirement: add environment variable for CLI package live update in the createapp Amplify Servce API call
Also updated the Amplify Client to allow "general" config level
=> perf(amplify-provider-awscloudformation): update create app param

packages/amplify-appsync-simulator/package.json, packages/amplify-appsync-simulator/src/__tests__/index.test.ts, packages/amplify-appsync-simulator/src/index.ts, packages/amplify-appsync-simulator/src/mqtt-server/client.ts, packages/amplify-appsync-simulator/src/mqtt-server/server.ts, packages/amplify-appsync-simulator/src/schema/appsync-scalars/index.ts, packages/amplify-appsync-simulator/src/schema/index.ts, packages/amplify-appsync-simulator/src/server/operations.ts, packages/amplify-appsync-simulator/src/server/subscription.ts, packages/amplify-appsync-simulator/src/type-definition.ts, packages/amplify-appsync-simulator/src/velocity/index.ts, packages/amplify-appsync-simulator/src/velocity/util/general-utils.ts, packages/amplify-appsync-simulator/src/velocity/util/time.ts, packages/amplify-appsync-simulator/tsconfig.json
=> fix(amplify-appsync-simulator): normalize resolver path in windows

packages/amplify-e2e-tests/src/utils/awsExports.ts
=> test(amplify-e2e-tests): added missing src extension

packages/amplify-cli/src/lib/attach-backend-steps/a30-initFrontend.js, packages/amplify-cli/src/lib/attach-backend-steps/a40-generateFiles.js, packages/amplify-provider-awscloudformation/lib/amplify-service-manager.js
`amplify pull` will now
- respect the existing project config file if yes flag is present.
- respect the `categories` field in the team provider info file.
This PR should fix the two Amplify Console issues 
- [342](https://github.com/aws-amplify/amplify-console/issues/342)
- [350](https://github.com/aws-amplify/amplify-console/issues/350)
=> fix(cli): fix console issue 342 and 350

packages/amplify-app/src/index.js
N/A
Minor code refactoring aimed at eliminating redundant code.
`By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.`
=> refactor(amplify-app): Eliminate code redundancy

how-to-write-a-transformer.md
N/A
As a developer, I would like an accurate link to the page that describes how to write a custom transformer.
=> docs: update link for how to write custom transformer

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts, packages/graphql-auth-transformer/src/__tests__/MultiAuth.test.ts
Fixes: #3064 for all auth providers
This PR will handle ```@aws_*``` auth directive propagation for nested types which ones doesn't have a ```@model``` attribute in the schema. In case of a ```private``` or ```public``` auth rule for ```iam``` provider the appropriate policy entry will be added to the policy as well.
=> fix (graphql-auth-transformer): handle @auth propagation for non-model nested types

packages/amplify-app/package.json
=> chore: bump min version of cli in amplify-app

packages/amplify-graphql-docs-generator/__integration__/__snapshots__/e2e.test.ts.snap, packages/amplify-graphql-docs-generator/templates/_renderToVariable.hbs
Adds a comment to the generated GraphQL operations for syntax highlighting and parsing.
becomes:
=> Magic comment for syntax highlighting and parsing

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-swift-visitor.test.ts.snap, packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts, packages/amplify-codegen-appsync-model-plugin/src/languages/swift-declaration-block.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-swift-visitor.ts, packages/amplify-codegen-appsync-model-plugin/tsconfig.json
=> fix(amplify-codegen-appsync-model-plugin): fix typo in swift model gen

packages/amplify-graphql-types-generator/src/angular/index.ts, packages/amplify-graphql-types-generator/src/typescript/codeGeneration.ts, packages/amplify-graphql-types-generator/test/angular/__snapshots__/index.js.snap, packages/amplify-graphql-types-generator/test/typescript/__snapshots__/codeGeneration.js.snap
=> chore: append eslint-disable to generated files

packages/amplify-graphql-types-generator/test/angular/__snapshots__/index.js.snap
update jest snapshot test for eslint
=> fix: update snapshot for eslint

LICENSE, Readme.md
* add env checkout command
* add link to the contribution guide
* fix markdown
* update copyright year
=> docs: update Readme.md and LICENSE

.gitignore, packages/amplify-util-mock/package.json, packages/graphql-transformers-e2e-tests/package.json
Configure ts-jest to use test tsconfig for e2e to fix e2e test run.
=> fix: test config update for e2e

packages/graphql-auth-transformer/src/__tests__/__snapshots__/OperationsArgument.test.ts.snap, packages/graphql-connection-transformer/src/resources.ts, packages/graphql-dynamodb-transformer/src/resources.ts, packages/graphql-elasticsearch-transformer/src/resources.ts, packages/graphql-key-transformer/src/KeyTransformer.ts, packages/graphql-predictions-transformer/src/resources.ts
SanitIze the input in resovers
=> Sanitize input

packages/graphql-relational-schema-transformer/package.json, packages/graphql-transformers-e2e-tests/package.json, yarn.lock
- fix: update to proper dependency for subscription testing in e2e
- fix #3344 which is a regression dependency from previous change
=> fix: e2e test and relational generator dependencies, fixes #3344

packages/amplify-app/package.json
Update the min cli version to 4.13.2
=> refactor: update min cli version

packages/amplify-e2e-tests/package.json
=> test(amplify-e2e-tests): disable ts-jest diagnostics

package.json, packages/amplify-appsync-simulator/package.json, packages/amplify-cli/package.json, packages/amplify-graphql-docs-generator/package.json, packages/amplify-graphql-types-generator/package.json, packages/amplify-ui-tests/package.json, packages/amplify-util-mock/package.json, packages/graphql-connection-transformer/package.json, packages/graphql-dynamodb-transformer/package.json, packages/graphql-elasticsearch-transformer/package.json, packages/graphql-function-transformer/package.json, packages/graphql-http-transformer/package.json, packages/graphql-key-transformer/package.json, packages/graphql-mapping-template/package.json, packages/graphql-predictions-transformer/package.json, packages/graphql-relational-schema-transformer/package.json, packages/graphql-transformer-common/package.json, packages/graphql-transformer-core/package.json, packages/graphql-versioned-transformer/package.json, scripts/link-bin.js, yarn.lock
=> chore: windows dev setup support

.circleci/config.yml
=> chore: fix integ test setup error

Readme.md
=> docs: update node version on Readme.md

yarn.lock
Regenerate yarn.lock before release.
=> chore: update yarn.lock before release

packages/amplify-e2e-tests/src/amplify-app-helpers/amplify-app-setup.ts
Use correct arguments when running npx amplify-app in circle-ci
=> test: fixing spawn in amplify-app tests to work in CI

packages/amplify-e2e-tests/src/__tests__/hosting.test.ts, packages/graphql-transformers-e2e-tests/src/emptyBucket.ts
=> test: waiting on deletion of bucket and deleting project for hosting

packages/amplify-cli/src/commands/env/remove.js, packages/amplify-cli/src/extensions/amplify-helpers/delete-project.js, packages/amplify-e2e-tests/src/__tests__/delete.test.ts, packages/amplify-e2e-tests/src/environment/add-env.ts
=> fix(cli): 'remove env' wording

.circleci/config.yml, .circleci/local_publish_helpers.sh
unset registry after verdaccio script, start and set again before e2e
=> Restart verdaccio server and registry path before e2e 

.circleci/config.yml, .circleci/local_publish_helpers.sh, packages/amplify-e2e-tests/src/__tests__/amplify-app.test.ts, packages/amplify-e2e-tests/src/amplify-app-helpers/amplify-app-setup.ts
=> E2e without npx

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
=> fix: fix typo in comment

packages/amplify-util-mock/src/__e2e__/key-transformer.e2e.test.ts, packages/graphql-key-transformer/src/KeyTransformer.ts, packages/graphql-key-transformer/src/__tests__/KeyTransformer.test.ts, packages/graphql-key-transformer/src/__tests__/__snapshots__/KeyTransformer.test.ts.snap, packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformer.e2e.test.ts
=> prevent double escape of nextToken in @key

packages/amplify-cli/src/index.ts
=> fix: #3304 - MaxListenersExceededWarning

packages/amplify-util-mock/src/__e2e__/subscriptions-with-auth.e2e.test.ts, packages/graphql-auth-transformer/src/ModelAuthTransformer.ts, packages/graphql-auth-transformer/src/__tests__/OwnerAuthTransformer.test.ts, packages/graphql-transformer-core/src/util/getFieldArguments.ts, packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts
support list ownerFields in subscriptions
re #3148
=> fix(graphql-auth-transformer): add list support for ownerField in subs

packages/amplify-e2e-tests/package.json, packages/amplify-e2e-tests/src/__tests__/function.test.ts, packages/amplify-e2e-tests/src/utils/sdk-calls.ts, packages/amplify-e2e-tests/tsconfig.json
- added longer delay on e2e grabbing cloudwatch
- added minor config changes to
- package.json
- tsconfig.json
=> test(amplify-e2e-tests): added longer delay to cloudwatchlogs collection

packages/graphql-transformer-core/src/util/amplifyUtils.ts, packages/graphql-transformer-core/src/util/transformConfig.ts
There are instances where it is helpful to be able to override a top-level api function.
Example: /amplify/backend/[category]/[resource]/functions includes
ElasticSearchStreamingLambdaFunction.zip, a helper lambda function to stream DDB
data into ElasticSearch. Issue #3359 has caused me to want to replace that function with
a similar function that contains a minor, but important change. This enhancement now
allows for this, and joins other overrides the user can affect (ex: resolvers, stacks, schema).
#3359 
=> feat(graphql-transformer-core): allow user overrides for functions

.circleci/config.yml, .eslintrc.js, jest.config.js, packages/amplify-console-integration/Readme.md, packages/amplify-console-integration/__tests__/pullAndInit.test.ts, packages/amplify-console-integration/package.json, packages/amplify-console-integration/sample.env, packages/amplify-console-integration/src/pullAndInit/amplifyArtifactsManager.ts, packages/amplify-console-integration/src/pullAndInit/amplifyConsoleOperations.ts, packages/amplify-console-integration/src/pullAndInit/deleteProject.ts, packages/amplify-console-integration/src/pullAndInit/initProject.ts, packages/amplify-console-integration/src/pullAndInit/pullProject.ts, packages/amplify-console-integration/src/setup-profile.ts, packages/amplify-console-integration/src/setup-tests.ts, packages/amplify-console-integration/src/util.ts, packages/amplify-console-integration/tsconfig.json, yarn.lock
=> test(cli): add integration tests for Amplify Console

.circleci/config.yml, packages/amplify-console-integration/__tests__/pullAndInit.test.ts, packages/amplify-console-integration/src/pullAndInit/amplifyConsoleOperations.ts, packages/amplify-console-integration/src/util.ts, yarn.lock
=> test(cli): fix the console integration test

.circleci/config.yml
=> Remove consolee2e dependencies

jest.config.js, packages/amplify-cli/package.json, packages/amplify-cli/src/plugin-helpers/platform-health-check.ts, packages/amplify-e2e-tests/src/categories/consoleHosting/consoleHosting.ts, yarn.lock
=> refactor(cli): add console hosting as official plugin

packages/amplify-e2e-tests/src/__tests__/plugin.test.ts
=> fix: fixing plugin e2e tests

packages/amplify-cli/scripts/post-install.js
updated post install script to remove the stale esm cache
=> chore(cli): remove stale esm cache postinstall

packages/amplify-codegen-appsync-model-plugin/package.json, packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap, packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts, packages/amplify-codegen-appsync-model-plugin/src/languages/swift-declaration-block.ts, packages/amplify-codegen-appsync-model-plugin/src/plugin.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-swift-visitor.ts, packages/amplify-e2e-tests/schemas/modelgen/model_gen_schema_with_aws_scalars.graphql, packages/amplify-e2e-tests/schemas/modelgen/model_gen_schema_with_errors.graphql, packages/amplify-e2e-tests/src/__tests__/datastore-modegen.test.ts, packages/amplify-e2e-tests/src/categories/codegen.ts, packages/amplify-e2e-tests/src/utils/nexpect.ts, yarn.lock
Updated codegen to escape swift reserved words
fix #3297 and #3298
=>  fix(amplify-codegen-appsync-model-plugin): escape swift resverd words 

.circleci/config.yml, packages/amplify-e2e-tests/Readme.md, packages/amplify-e2e-tests/src/__tests__/consoleHosting.test.ts, packages/amplify-e2e-tests/src/__tests__/delete.test.ts, packages/amplify-e2e-tests/src/amplify-app-helpers/amplify-app-setup.ts, packages/amplify-e2e-tests/src/categories/analytics.ts, packages/amplify-e2e-tests/src/categories/api.ts, packages/amplify-e2e-tests/src/categories/auth.ts, packages/amplify-e2e-tests/src/categories/codegen.ts, packages/amplify-e2e-tests/src/categories/consoleHosting/consoleHosting.ts, packages/amplify-e2e-tests/src/categories/function.ts, packages/amplify-e2e-tests/src/categories/hosting.ts, packages/amplify-e2e-tests/src/categories/interactions.ts, packages/amplify-e2e-tests/src/categories/predictions.ts, packages/amplify-e2e-tests/src/categories/storage.ts, packages/amplify-e2e-tests/src/codegen/add.ts, packages/amplify-e2e-tests/src/configure/index.ts, packages/amplify-e2e-tests/src/environment/add-env.ts, packages/amplify-e2e-tests/src/init/amplifyPush.ts, packages/amplify-e2e-tests/src/init/deleteProject.ts, packages/amplify-e2e-tests/src/init/initProjectHelper.ts, packages/amplify-e2e-tests/src/plugin/index.ts, packages/amplify-e2e-tests/src/plugin/new-plugin.ts, packages/amplify-e2e-tests/src/utils/nexpect.ts, packages/amplify-e2e-tests/src/utils/pinpoint.ts
=> ci(amplify-e2e-tests): remove verbose flag from E2E tests

packages/amplify-e2e-tests/src/__tests__/auth.test.ts
Updated the auth test to use the right config from amplify-meta.json
=> test(amplify-e2e-tests): fix auth test

packages/amplify-e2e-tests/src/__tests__/analytics.test.ts, packages/amplify-e2e-tests/src/__tests__/function.test.ts
=> test(amplify-e2e-tests): remove - from kenisis stream name

packages/amplify-cli/scripts/post-install.js
I know this is a dumb PR but I saw it and it's an easy fix!
=> Updated casing on CLI

packages/amplify-cli/src/extensions/amplify-helpers/git-manager.js, packages/amplify-cli/src/init-steps/preInitSetup.js, packages/amplify-e2e-tests/src/amplify-app-helpers/amplify-app-validation.ts
#3617 
append gitignore when creating amplify skeleton
=> refactor: add gitignore with amplify-app

packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js
*Issue #3509 
* added policy specific to Cognito user groups for List Bucket operation
=> fix(amplify-category-function): adds policy for list Bucket for user groups

packages/amplify-category-function/package.json, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/functionPluginLoader.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts, packages/amplify-cli/src/domain/amplify-toolkit.ts, packages/amplify-cli/src/extensions/amplify-helpers/constants.js, packages/amplify-cli/src/extensions/amplify-helpers/hash-dir.js, packages/amplify-cli/src/extensions/amplify-helpers/leave-breadcrumbs.js, packages/amplify-cli/src/extensions/amplify-helpers/read-breadcrumbs.js, packages/amplify-cli/src/extensions/amplify-helpers/read-json-file.js, packages/amplify-cli/src/extensions/amplify-helpers/write-object-as-json.js, packages/amplify-function-plugin-interface/src/index.ts, packages/amplify-nodejs-runtime-provider/amplify-plugin.json, packages/amplify-nodejs-runtime-provider/package.json, packages/amplify-nodejs-runtime-provider/src/index.ts, packages/amplify-nodejs-runtime-provider/src/utils/legacyBuild.ts, packages/amplify-nodejs-runtime-provider/src/utils/legacyPackage.ts, packages/amplify-provider-awscloudformation/lib/build-resources.js, packages/amplify-python-runtime-provider/src/index.ts
Integrate the build() and package() methods of the function plugin refactor into the amplify build logic
=> working build / push integration

packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts
My previous refactor changed the method signature of invoke which caused failures when trying to invoke a function locally. Reverting that.
=> fix(amplify-category-function): revert invoke method signature

packages/amplify-graphql-docs-generator/__integration__/__snapshots__/e2e.test.ts.snap, packages/amplify-graphql-docs-generator/templates/typescript.hbs
=> chore: append eslint-disable to template

packages/amplify-category-notifications/__tests__/lib/channel-APNS.test.js, packages/amplify-category-notifications/lib/channel-APNS.js
APNS Sandbox channel will be enabled/disabled when regular APNS channel is enabled/disabled
fix #3247
=> fix(amplify-category-notifications): add apns sandbox channel

packages/amplify-e2e-tests/src/init/pull-headless.ts
=> fix: update import

packages/amplify-category-api/provider-utils/awscloudformation/appsync-schemas/many-relationship-schema.graphql
Update the one-to-many schema to reflect the newer @connection directive style
#3513 
=> fix: update graphql schema to match docs

packages/amplify-e2e-tests/src/__tests__/api.test.ts, packages/amplify-e2e-tests/src/categories/api.ts
=> test: E2E tests for apis (REST)

packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
=> fix: fixing searchable migration document link in the cli flow

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/functionPluginLoader.ts
Adds code to protect against an undefined/null value for the 'runtime' contributor parameter.
=> fix(amplify-function-plugin-interface): guard against undefined runtime

packages/amplify-e2e-tests/src/__tests__/delete.test.ts, packages/amplify-e2e-tests/src/categories/storage.ts, packages/amplify-e2e-tests/src/utils/projectMeta.ts, packages/amplify-provider-awscloudformation/lib/delete-env.js, packages/amplify-provider-awscloudformation/lib/system-config-manager.js, packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js, packages/amplify-provider-awscloudformation/src/aws-utils/aws-s3.js, packages/amplify-storage-simulator/src/__tests__/test-data/upload/abc.json
The purpose of this pull request is to fix deletion of s3 buckets having more than 1000< objects and end to end test, testing this functionality
=> fix(amplify-provider-awscloudformation): fix deletion for large bucket

packages/amplify-provider-awscloudformation/lib/attach-backend.js, packages/amplify-provider-awscloudformation/src/aws-utils/aws-amplify.js
fix ##3292
this fixes the bug for headless pull when config level is set to 'general'. 
=> fix(amplify-provider-awscloudformation): fix a bug in headless pull

packages/amplify-category-auth/provider-utils/awscloudformation/question-factories/core-questions.js, packages/amplify-e2e-tests/src/__tests__/auth.test.ts, packages/amplify-e2e-tests/src/categories/auth.ts
skipping validate for multilist and update in auth
#3785
=> fix(amplify-category-auth): fixed issue with updating urls in auth

packages/amplify-e2e-tests/src/categories/api.ts, packages/amplify-e2e-tests/src/categories/function.ts, packages/amplify-e2e-tests/src/categories/storage.ts
Fix function e2e tests for new template orderings
=> fix: update function e2e tests with new template orderings

.circleci/config.yml, packages/amplify-e2e-tests/src/__tests__/function.test.ts
Update circle ci config to install python and run e2e test to add python function
=> feat: Add python function creation e2e test

packages/amplify-cli/package.json, packages/amplify-dotnet-function-runtime-provider/package.json, packages/amplify-dotnet-function-runtime-provider/resources/localinvoke/Program.cs, packages/amplify-dotnet-function-runtime-provider/src/constants.ts, packages/amplify-dotnet-function-runtime-provider/src/index.ts, packages/amplify-dotnet-function-runtime-provider/src/utils/build.ts, packages/amplify-dotnet-function-runtime-provider/src/utils/detect.ts, packages/amplify-dotnet-function-runtime-provider/src/utils/invoke.ts, packages/amplify-dotnet-function-runtime-provider/src/utils/package.ts, packages/amplify-dotnet-function-runtime-provider/tsconfig.json, packages/amplify-dotnet-function-template-provider/amplify-plugin.json, packages/amplify-dotnet-function-template-provider/package.json, packages/amplify-dotnet-function-template-provider/src/index.ts, packages/amplify-dotnet-function-template-provider/tsconfig.json, packages/amplify-go-function-runtime-provider/package.json, packages/amplify-go-function-template-provider/package.json, packages/amplify-nodejs-function-runtime-provider/package.json, packages/amplify-nodejs-function-template-provider/package.json, packages/amplify-python-function-runtime-provider/package.json, packages/amplify-python-function-template-provider/package.json
- dotnet function provider fixes and refactor
- add missing packages to dotnet provider
- package.json cleanup, standardization
=> fix: dotnet function provider fixes, package.json cleanup, add pkg refs

packages/amplify-e2e-tests/src/categories/api.ts
=> test: fix failing api e2e tests

packages/amplify-e2e-tests/src/__tests__/delete.test.ts
=> test(amplify-e2e-tests): waiting on bucket deletion

packages/amplify-cli/package.json, packages/amplify-dotnet-function-runtime-provider/.npmignore, packages/amplify-dotnet-function-template-provider/.npmignore, packages/amplify-function-plugin-interface/.npmignore, packages/amplify-go-function-runtime-provider/.npmignore, packages/amplify-go-function-template-provider/.npmignore, packages/amplify-java-function-runtime-provider/.npmignore, packages/amplify-java-function-runtime-provider/package.json, packages/amplify-java-function-template-provider/.npmignore, packages/amplify-java-function-template-provider/package.json, packages/amplify-nodejs-function-runtime-provider/.npmignore, packages/amplify-nodejs-function-template-provider/.npmignore, packages/amplify-python-function-runtime-provider/.npmignore, packages/amplify-python-function-template-provider/.npmignore
- enable java function runtime
- add npmignore files to new packages
=> chore: enable java function runtime, add npmignores to new pkgs

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/cronHelper.ts, packages/amplify-e2e-tests/src/__tests__/function.test.ts
* Fix string error on cron tests
* Cron week expr fix
=> chore:  Fix cron e2e tests and week cron expr

.circleci/config.yml, packages/amplify-dotnet-function-runtime-provider/amplify-plugin.json, packages/amplify-dotnet-function-runtime-provider/src/constants.ts, packages/amplify-dotnet-function-template-provider/amplify-plugin.json, packages/amplify-e2e-tests/src/__tests__/function.test.ts, packages/amplify-e2e-tests/src/categories/function.ts, packages/amplify-java-function-runtime-provider/package.json, packages/amplify-java-function-runtime-provider/src/index.ts, packages/amplify-java-function-runtime-provider/src/utils/build.ts, packages/amplify-java-function-runtime-provider/src/utils/constants.ts, packages/amplify-java-function-runtime-provider/src/utils/detect.ts, packages/amplify-java-function-runtime-provider/src/utils/invoke.ts, packages/amplify-java-function-runtime-provider/src/utils/package.ts
Adding mock function and cloud invoke e2e tests for all runtimes
=> multi-runtime e2e updates

.circleci/config.yml, packages/amplify-e2e-tests/src/__tests__/api.test.ts, packages/amplify-e2e-tests/src/categories/function.ts
- move circle ci installations to build step to be persisted across workflow steps
- fix function e2e tests 
=> fix: e2e fixes and circle ci install change

package.json, packages/amplify-e2e-tests/src/__tests__/function.test.ts
- fix beta release script to do proper versioning
- fix e2e test naming (extra space)
=> chore: update beta publish script, e2e test naming

packages/amplify-cli/src/extensions/amplify-helpers/read-breadcrumbs.js
=> fix: add default editor if not present

.circleci/config.yml
Update integration test machine size in circle ci
=> chore: update integ test machine size

packages/amplify-cli/package.json
=> fix: add function plugin interface to cli deps

packages/amplify-cli/package.json
Reverts aws-amplify/amplify-cli#3905
=> Revert "fix: add function plugin interface to cli deps"

packages/amplify-cli/src/extensions/amplify-helpers/trigger-flow.js
fix #3915 
fix #3926
Update destMap so that files needed in src are copied over.
This includes:
index.js for lambda event.handler
event.json for mocking
package.json for node build
=> Update trigger dest

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/project-name-validation.test.ts, packages/amplify-cli/src/config-steps/c0-analyzeProject.js, packages/amplify-cli/src/extensions/amplify-helpers/project-name-validation.js, packages/amplify-cli/src/init-steps/s0-analyzeProject.js
fix #3687
#3687
Prevent projects from being created with a hyphenated name
=> fix: prevent hyphenated project names

packages/amplify-cli/src/init-steps/s9-onSuccess.js
N/A
To be consistent with other welcome messages. Also, feel free to close this if it's not really necessary. :)
=> fix(cli): fix amplify console welcome message format

packages/amplify-e2e-tests/src/__tests__/delete.test.ts, packages/amplify-e2e-tests/src/__tests__/env.test.ts, packages/amplify-e2e-tests/src/environment/add-env.ts, packages/amplify-e2e-tests/src/init/amplifyPull.ts, packages/amplify-e2e-tests/src/init/index.ts, packages/amplify-provider-awscloudformation/lib/delete-env.js, packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js
checking for deleted bucket in env
=> fix(amplify-provider-awscloudformation): check before fetching backend

packages/amplify-e2e-tests/src/__tests__/delete.test.ts, packages/amplify-provider-awscloudformation/lib/delete-env.js, packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js
Check for an unavailable bucket and then print out message
=> fix: check for unavailable bucket

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-java-visitor.ts
=> feat(amplify-codegen-appsync-model-plugin): java tostring (#3772)

packages/amplify-dotnet-function-template-provider/resources/lambda/.gitignore, packages/amplify-dotnet-function-template-provider/src/providers/crudProvider.ts, packages/amplify-dotnet-function-template-provider/src/providers/helloWorldProvider.ts, packages/amplify-dotnet-function-template-provider/src/providers/serverlessProvider.ts, packages/amplify-dotnet-function-template-provider/src/providers/triggerProvider.ts
Adds a .gitignore file to keep customers from committing files that should remain untracked by git.
=> fix(amplify-dotnet-function-template-provider): added .gitignore file

.circleci/config.yml
=> ci: temp pause e2e

.circleci/config.yml, packages/amplify-e2e-tests/src/init/initProjectHelper.ts
=> ci: add e2e back and change region

.circleci/amplify_init.exp
=> fix: remove comment from integ test init file

packages/amplify-category-interactions/provider-utils/awscloudformation/cloudformation-templates/lex-cloudformation-template.json.ejs, packages/amplify-category-interactions/provider-utils/awscloudformation/function-template-dir/index.js.ejs, packages/amplify-category-interactions/provider-utils/awscloudformation/index.js, packages/amplify-provider-awscloudformation/index.js, packages/amplify-provider-awscloudformation/lib/utility-functions.js, packages/amplify-provider-awscloudformation/src/aws-utils/aws-lex.js
Update the interaction lambda function to use region mapping to
create Lex Chatbot
=> fix(amplify-category-interactions): make chatbot category region aware

.circleci/config.yml, scripts/split-e2e-tests.ts
=> chore: change split test name

packages/amplify-category-api/provider-utils/awscloudformation/appsync-schemas/many-relationship-schema.graphql
Fixes https://github.com/aws-amplify/amplify-js/issues/5211
=> fix: incorrect type on graphql boilerplate schema

packages/amplify-category-auth/provider-utils/supported-services.json, packages/amplify-cli/src/init-steps/s0-analyzeProject.js
Fix for #3854. Also simplifies validation logic and adjusts wording of input validation errors.
=> fix: prevent naming conflicts with new env names

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap, packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-java-visitor.test.ts, packages/amplify-codegen-appsync-model-plugin/src/configs/java-config.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-java-visitor.ts
Updated model gen to support non model types in Android
re #3586
=> feat(amplify-codegen-appsync-model-plugin): add non-model support - Java

.circleci/config.yml, packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
Updated Java codegen snapshot to include toString method
=> test(amplify-codegen-appsync-model-plugin): update snapshot

.circleci/config.base.yml, .circleci/config.yml
ci: update split test workflow CI/CD
=> ci: update split test workflow CI/CD

packages/amplify-e2e-tests/src/__tests__/delete.test.ts
=> test: checking bucket once after deletion

packages/graphql-connection-transformer/src/__tests__/NewConnectionTransformer.test.ts, packages/graphql-connection-transformer/src/__tests__/__snapshots__/NewConnectionTransformer.test.ts.snap, packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts, packages/graphql-transformer-core/src/index.ts, packages/graphql-transformer-core/src/util/transformConfig.ts, yarn.lock
fix: #3438
When conflict resolution is enabled on an API, many-to-many connections with @connection and @key could generate a wrong schema, where mutation input types would have nested non-scalar types.
=> fix: #3438, many-to-many with conflict resolution generated wrong schema

Readme.md, amplifycli_react_tutorial.md, graphql-transform-tutorial.md, how-to-write-a-transformer.md, native_guide.md, packages/amplify-category-predictions/provider-utils/supportedPredictions.js, packages/amplify-category-xr/lib/xr-manager.js, packages/amplify-cli/scripts/post-install.js, packages/amplify-cli/src/plugin-helpers/create-new-plugin.ts, packages/amplify-cli/src/project-config-version-check.ts, packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js, packages/amplify-provider-awscloudformation/src/aws-utils/aws-amplify.js, packages/amplify-util-mock/src/api/api.ts
N/A
- Replaces all docs v1 links to docs v2 link
=> fix(): replaced v1 docs references with v2 docs references

packages/amplify-category-auth/provider-utils/awscloudformation/assets/string-maps.js
=> fix: (amplify-category-auth)change auth method copy

packages/amplify-cli/src/plugin-helpers/create-new-plugin.ts, packages/amplify-e2e-tests/src/plugin/new-plugin.ts
=> fix(cli): add information on pre/post pull in learn more

.github/stale.yml
=> ci: Added stale.yml for stale bot

packages/amplify-cli/CHANGELOG.md
=> Fix typo in changelog

packages/amplify-graphql-types-generator/src/polyfills.js
=> Update to be compatible with core-js 3

.github/stale.yml
=> Add missing exempt labels, fix wording.

packages/amplify-util-mock/src/CFNParser/intrinsic-functions.ts, packages/amplify-util-mock/src/utils/lambda/loadMinimal.ts
#4085 #4012
Loading resources from Amplify Meta if not found from CFN
=> fix(amplify-util-mock): loading resources from amplify-meta

packages/amplify-cli/src/extensions/amplify-helpers/delete-project.js
=> fix(cli): update the warning message for delete command

packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformer.e2e.test.ts
=> searchable e2e fix

packages/amplify-e2e-tests/src/environment/add-env.ts
=> test(amplify-e2e-tests): change delete env expect prompt

.github/stale.yml
=> ci: adding stale.yml file with question and pending-triage

packages/amplify-e2e-tests/src/__tests__/delete.test.ts
Reverts aws-amplify/amplify-cli#3742
=> Revert "test(amplify-e2e-tests):test uncommented"

packages/amplify-e2e-tests/src/__tests__/delete.test.ts
=> test(amplify-e2e-tests): removed amplify app tests

packages/amplify-app/package.json
By using the current version lerna will update the packages going forward
=> fix: update amplify app package dependencies to latest

packages/amplify-e2e-core/src/categories/lambda-function.ts, packages/amplify-e2e-core/src/utils/nexpect.ts
=> fix: update function e2e tests with new layer wording

packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts
=> test(graphql-transformers-e2e-tests): fix typo on mutation functions

packages/amplify-category-function/src/commands/function/remove.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambdaLayerWalkthrough.ts, packages/amplify-cli/src/extensions/amplify-helpers/remove-resource.js, packages/amplify-e2e-core/src/categories/lambda-layer.ts, packages/amplify-e2e-tests/src/__tests__/layer.test.ts
Lambda layers can be removed with `amplify remove function`
=> Lambda layer remove

.eslintrc.js, package.json, yarn.lock
- chore: update codecov package as instructed to see if coverage reports will work again
- refresh yarn.lock after release
=> chore: update codecov package, refresh yarn.lock

packages/amplify-category-function/resources/awscloudformation/cloudformation-templates/lambda-function-cloudformation-template.json.ejs, packages/amplify-category-function/src/constants.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/permissionMapUtils.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/updateTopLevelComment.ts, packages/amplify-category-function/src/provider-utils/supportedServicesType.ts, packages/amplify-cli/bin/amplify, packages/amplify-e2e-core/src/categories/lambda-function.ts, packages/amplify-function-plugin-interface/src/index.ts
Refactor existing function update code to prepare for adding layers to functions
=> refactor function update flow

packages/amplify-e2e-tests/src/__tests__/delete.test.ts
=> test(amplify-e2e-tests): adding timeout after deleting pinpoint app

.circleci/config.base.yml, .circleci/config.yml
Make migration tests a dependency of deployment for stricter releases
=> ci: make deploy require migration tests

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/functionPluginLoader.ts, packages/amplify-e2e-core/src/categories/function.ts
=> fix: make Hello World the default choice for function templates

.circleci/config.yml
=> chore: remove missing test from e2e

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts, packages/amplify-cli/src/extensions/amplify-helpers/remove-resource.js, packages/amplify-dotnet-function-runtime-provider/src/index.ts, packages/amplify-e2e-core/src/categories/lambda-layer.ts, packages/amplify-e2e-tests/src/__tests__/layer.test.ts, packages/amplify-go-function-runtime-provider/src/index.ts, packages/amplify-java-function-runtime-provider/src/index.ts, packages/amplify-nodejs-function-runtime-provider/src/index.ts, packages/amplify-python-function-runtime-provider/src/index.ts
=> Lambda layers

packages/amplify-category-function/src/index.ts
=> fix: added error message when amplify mock function with layers

packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts, packages/amplify-e2e-core/src/categories/lambda-layer.ts, packages/amplify-e2e-tests/src/__tests__/layer.test.ts
Removed the extra folder with the layer's name in the runtime directory. Fixed 1/3 e2e tests.
=> fix: remove unnecessary folder in layer dir, fix simplelayer e2e test

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/addLayerToFunctionWalkthrough.test.ts, packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/addLayerToFunctionUtil.test.ts, packages/amplify-category-function/src/index.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/addLayerToFunctionWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambdaLayerWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/addLayerToFunctionUtils.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/lambda-layer-cloudformation-template.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerParams.ts, packages/amplify-provider-awscloudformation/lib/push-resources.js
* Added layer parameters in function update
* Added warning message to update function dependent on layer
=> bugbash fixes for lambda layers

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/addLayerToFunctionUtil.test.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/addLayerToFunctionWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambdaLayerWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/addLayerToFunctionUtils.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/lambda-layer-cloudformation-template.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerParams.ts
=> chore: small refactor of layer metadata to add back unit tests

packages/amplify-category-auth/provider-utils/awscloudformation/utils/trigger-file-uploader.js, packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/cloudfront-manager.js, packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/file-uploader.js, packages/amplify-category-notifications/lib/auth-helper.js, packages/amplify-category-predictions/provider-utils/awscloudformation/triggers/s3/index.js, packages/amplify-cli/src/commands/push.js, packages/amplify-cli/src/config-steps/c9-onFailure.js, packages/amplify-cli/src/init-steps/postInitSetup.js, packages/amplify-provider-awscloudformation/lib/push-resources.js, packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js, packages/graphql-transformer-core/src/util/sanity-check.ts
=> fix: occurred spelling mistake

.eslintrc.js, package.json, packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.js, packages/amplify-category-function/src/index.ts, packages/amplify-cli/src/commands/plugin/configure.ts, packages/amplify-cli/src/extensions/amplify-helpers/trigger-flow.js, packages/amplify-cli/src/migrate-project.js, packages/amplify-cli/src/plugin-helpers/create-new-plugin.ts, packages/amplify-cli/src/plugin-helpers/verify-plugin.ts, packages/amplify-cli/src/project-config-version-check.ts, packages/amplify-console-hosting/utils/build-utils.js, packages/amplify-dotnet-function-template-provider/src/utils/dynamoDBWalkthrough.ts, packages/amplify-e2e-core/src/categories/function.ts, packages/amplify-nodejs-function-template-provider/src/utils/dynamoDBWalkthrough.ts, packages/amplify-provider-awscloudformation/lib/amplify-service-migrate.js, packages/amplify-provider-awscloudformation/lib/attach-backend.js, packages/amplify-provider-awscloudformation/src/aws-utils/aws-s3.js, packages/graphql-key-transformer/src/KeyTransformer.ts, packages/graphql-relational-schema-transformer/src/__tests__/RelationalDBMappingTemplate.test.ts, packages/graphql-transformer-core/src/TransformerContext.ts, yarn.lock
chore: fix additional spelling errors
=> chore: fix additional spelling errors

packages/amplify-provider-awscloudformation/src/aws-utils/aws-s3.js
=> fix(amplify-provider-awscloudformation): fixing unhandled promise

packages/amplify-e2e-core/src/categories/api.ts, packages/amplify-e2e-core/src/init/amplifyPush.ts, packages/amplify-e2e-tests/schemas/migrations_key/simple_key.graphql, packages/amplify-migration-tests/src/__tests__/migration_tests/transformer_migration/api.key.migration.test.ts
init key schema at given CLI version, force push with the codebase
=> test: cli migration force push with key

packages/amplify-category-function/src/index.ts, packages/amplify-e2e-core/src/categories/lambda-function.ts, packages/amplify-e2e-core/src/categories/lambda-layer.ts, packages/amplify-e2e-core/src/utils/index.ts, packages/amplify-e2e-tests/layerdata/python/index.py, packages/amplify-e2e-tests/layerdata/python/testfunc.py, packages/amplify-e2e-tests/src/__tests__/function.test.ts, packages/amplify-provider-awscloudformation/lib/build-resources.js, packages/amplify-python-function-runtime-provider/src/index.ts
* Added Test for NodeJS and Python Runtime for layers
* Skipping Java Tests 
* Added a fix for building function if layer is also present
=> e2e tests for NodeJS and Python

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/functionPluginLoader.ts, packages/amplify-dotnet-function-runtime-provider/amplify-plugin.json, packages/amplify-e2e-core/src/categories/lambda-layer.ts, packages/amplify-e2e-tests/src/__tests__/layer.test.ts, packages/amplify-go-function-runtime-provider/amplify-plugin.json, packages/amplify-java-function-runtime-provider/amplify-plugin.json
* Removes not suppported runtimes for LambdaLayers 
* Fixes  tests for the same
=> chore: small change to remove non-supported runtimes in LambdaLayer

packages/amplify-dotnet-function-runtime-provider/src/index.ts, packages/amplify-e2e-core/src/categories/lambda-layer.ts, packages/amplify-go-function-runtime-provider/src/index.ts, packages/amplify-java-function-runtime-provider/src/index.ts, packages/amplify-nodejs-function-runtime-provider/src/index.ts, packages/amplify-python-function-runtime-provider/src/index.ts
=> fix: remove trailing slash from runtime paths and update tests

packages/amplify-provider-awscloudformation/lib/delete-env.js
*Issue #4298 
* deletes the temp directory created while deleting environment
=> chore(amplify-provider-awscloudformation): deletes temp dir

packages/amplify-provider-awscloudformation/lib/delete-env.js
*Issue #4298 *
* removing LGTM error. The function Definition was missing one argument
=> chore: removing LGTM errors

packages/amplify-provider-awscloudformation/lib/delete-env.js
Adds the missing require for fs introduced in #4398
=> fix(amplify-provider-awscloudformation): add missing require

packages/amplify-e2e-core/src/index.ts, packages/amplify-e2e-core/src/utils/sdk-calls.ts, packages/amplify-e2e-tests/src/__tests__/hostingPROD.test.ts
Delete the hosting bucket after running the e2e tests
=> test(amplify-e2e-tests): delete hosting bucket after running test

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts
I incorrectly changed the object key name in the previous PR, not realizing this was correct for the CFN template.
=> fix: erroneous changes in prior PR. LambdaFunction is correct for CFN

packages/amplify-e2e-core/package.json, packages/amplify-e2e-core/src/categories/auth.ts, packages/amplify-e2e-core/src/categories/hosting.ts, packages/amplify-e2e-core/src/utils/sdk-calls.ts, packages/amplify-e2e-core/tsconfig.json, packages/amplify-e2e-tests/package.json, packages/amplify-e2e-tests/src/__tests__/delete.test.ts, packages/amplify-e2e-tests/src/__tests__/hostingPROD.test.ts, packages/amplify-e2e-tests/tsconfig.json
Updated e2e test to remove the hosting bucket content before deleting the bucket
=> test(amplify-e2e-tests): remove files before deleting hosting bucket

packages/amplify-cli/src/__tests__/version-manager.test.ts, packages/amplify-cli/src/domain/amplify-telemetry/getTelemetryUrl.ts
=> test(cli): fixed test check against url

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/addLayerToFunctionUtil.test.ts, packages/amplify-category-function/src/index.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts
=> fix: updateConfigOnEnvInit parameters, stub syncVersions for unit tests

.circleci/config.yml, packages/amplify-e2e-core/src/categories/api.ts
=> test: update text in api e2e helper function

packages/amplify-provider-awscloudformation/lib/push-resources.js
Fixes interactions e2e test failure
=> fix: only call ll package funcs with ll resources

.circleci/config.yml, packages/amplify-e2e-core/src/categories/lambda-function.ts
=> test: update service selection text in e2e helper for functions

packages/amplify-category-auth/package.json, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts, packages/amplify-category-predictions/package.json, packages/amplify-category-storage/package.json, yarn.lock
fixes aut, storage, and predictions e2e tests
=> fix: depend on correct version of function category

packages/amplify-cli/src/__tests__/config.test.ts, packages/amplify-cli/src/app-config/config.ts
=> fix(cli): config init wasn't reading string

packages/amplify-e2e-tests/src/__tests__/api.test.ts
=> test(amplify-e2e-tests): randomize ddb table name for api test

.circleci/config.yml, package.json
=> chore: turn on e2e tests for headless branch

.circleci/config.yml, packages/amplify-e2e-core/src/categories/lambda-layer.ts, packages/amplify-e2e-tests/src/__tests__/layer.test.ts, packages/amplify-migration-tests/package.json, packages/amplify-migration-tests/src/__tests__/update_tests/function_migration_update.test.ts
Migration test for adding layer to pre-update function
Refactor metadata validation for Lambda layers
Update config.yml to latest e2e changes
=> test: add migration test for Lambda layers

packages/amplify-console-integration-tests/__tests__/pullAndInit.test.ts, packages/amplify-console-integration-tests/src/pullAndInit/amplifyConsoleOperations.ts, packages/amplify-e2e-core/src/categories/auth.ts, packages/amplify-e2e-core/src/init/deleteProject.ts, packages/amplify-e2e-core/src/utils/envVars.ts, packages/amplify-e2e-core/src/utils/sdk-calls.ts
- allow delete project to pass a project config when calling cloudformation
=> test(amplify-console-integration-tests): fix afterEach

packages/amplify-cli/scripts/post-install.js, packages/amplify-cli/src/__tests__/context-manager.test.ts, packages/amplify-cli/src/context-manager.ts
=> fix(cli): disabling usage-data until new end point is enabled

packages/amplify-e2e-tests/src/__tests__/analytics.test.ts, packages/amplify-e2e-tests/src/__tests__/delete.test.ts, packages/amplify-e2e-tests/src/__tests__/hosting.test.ts, packages/amplify-e2e-tests/src/__tests__/hostingPROD.test.ts
=> test(amplify-e2e-tests): remove unused deleteBucket argument from tests

.circleci/config.yml, scripts/split-e2e-tests.ts
=> Split test

.circleci/config.yml, scripts/split-e2e-tests.ts
=> more concurrency

.circleci/config.yml, packages/amplify-category-auth/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js
Added a warning if Identity pool is getting deleted via ```amplify update auth```
=> fix: warning added for identity pool deletion

.circleci/config.yml, packages/amplify-cli/scripts/post-install.js, packages/amplify-cli/src/__tests__/context-manager.test.ts, packages/amplify-cli/src/commands/configure.js, packages/amplify-cli/src/context-manager.ts
=> fix(cli): change in usage data ux and revert usage data disable

packages/graphql-key-transformer/src/__tests__/__snapshots__/KeyTransformer.test.ts.snap
=> test(graphql-key-transformer): snapshot fix for graphql key transformer

.circleci/config.yml
=> chore: run split script on circleci config

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts, packages/amplify-e2e-tests/src/__tests__/function_2.test.ts
#4822
Files placed in the opt/ folder can be referenced correctly in Lambda functions
=> fix: /opt folder should be packaged at the root of the zipped dir

packages/amplify-category-interactions/provider-utils/supported-services.json
=> fix: remove incorrect string in "add interactions" message

packages/amplify-category-storage/commands/storage/add.js, packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js
Warn users to update storage for IAM groups if a user is part of a user pool group
=> docs(amplify-category-storage): warn to update storage for IAM groups

.circleci/config.yml, packages/graphql-transformers-e2e-tests/src/__tests__/MutationCondition.e2e.test.ts
Fixed expected pattern to match unpredictable error pattern
=> test(graphql-transformers-e2e-tests): changed in recieved error pattern

.circleci/config.yml, packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/rest-api-path-utils.test.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/utils/rest-api-path-utils.ts, yarn.lock
#3868 
CloudFormation and API Gateway support creating a root path proxy API endpoint, but the CLI doesn't. This PR introduces the ability to create an endpoint at the root path. Also, this PR adds checks to see if any new paths that are to be added overlap with each other. If they do, a warning message is presented, and the user must confirm whether they are okay with the situation or not.
=> feat: allow creation of REST API endpoint at root path (/)

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap, packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-java-visitor.test.ts, packages/amplify-codegen-appsync-model-plugin/src/configs/java-config.ts, packages/amplify-codegen-appsync-model-plugin/src/utils/process-auth.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-java-visitor.ts
#4509 
Add auth model annotations according to https://github.com/aws-amplify/amplify-android/pull/559
=> refactor(amplify-codegen-appsync-model-plugin): auth model annotation

.circleci/config.yml, packages/amplify-category-api/package.json, packages/amplify-category-api/src/__tests__/commands/api/add-graphql-datasource.test.js, packages/amplify-category-api/src/__tests__/commands/api/mock-data/schema.graphql, packages/amplify-category-api/src/commands/api/add-graphql-datasource.js
*Issue #3082 
* Checks schema in the schema folder  and root folder while adding graphql rds datasource
=> fix(amplify-category-api): added check to read schema in schema dir

.circleci/config.yml, packages/amplify-graphql-docs-generator/package.json, packages/amplify-velocity-template/package.json, packages/amplify-velocity-template/tests/runner/mocha.js, yarn.lock
=> chore: update dependencies

.circleci/config.yml
Commenting integration tests as per CircleCI issues
=> chore: comment integrationTests

.circleci/config.yml, packages/amplify-category-auth/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js, packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts, packages/amplify-e2e-tests/src/__tests__/env.test.ts, packages/amplify-e2e-tests/src/environment/env.ts
*Issue #4639 
* Added check to stop prompts for cognito triggers while using env commands
=> fix: Added check to stop prompts for cognito triggers while using env commands

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts, packages/graphql-auth-transformer/src/__tests__/PerFieldAuthArgument.test.ts, packages/graphql-auth-transformer/src/__tests__/__snapshots__/PerFieldAuthArgument.test.ts.snap
add auth mode check on non model fields
re #3700
=> fix(graphql-auth-transformer): add authmode check

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap, packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-java-visitor.test.ts, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-java-visitor.ts
*Issue #4864 
* Fixes invalid syntax in Codegen for Android generates  in CopyOfBuilder
* Added Tests for the same
=> fix: bug in CopyofBuilder class with no nullable and non nullable fields

packages/amplify-console-hosting/modules/questions/question-generator.js
=> fix(amplify-console-hosting): fix the cicd hosting serve

packages/amplify-category-auth/src/index.js
Fix an import path that was missed in #5165
=> fix: update auth supported services path

packages/amplify-e2e-tests/schemas/key-conflict-detection.graphql, packages/amplify-e2e-tests/src/__tests__/api_2.test.ts, packages/graphql-mapping-template/src/dynamodb.ts
=> fix(graphql-mapping-template): fix @key issue when datastore enabled

packages/amplify-cli/src/extensions/amplify-helpers/resource-status.ts, packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts
=> fix: tags invoking update when no resource present

packages/amplify-provider-awscloudformation/src/aws-utils/aws-s3.js
#4113 #4946 
The s3 uploadfile switches to `upload` when a file exceeding 5 MB is uploaded. This fixes the issue with error `Your socket connection to the server was not read from or written to within the timeout period`
=> fix(amplify-provider-awscloudformation): large file upload

packages/amplify-provider-awscloudformation/lib/system-config-manager.js
=> fix(amplify-provider-awscloudformation): set credentials file permission

packages/amplify-provider-awscloudformation/src/aws-utils/aws-lex.js
https://github.com/aws-amplify/amplify-cli/issues/5186
Updating interactions service to include additional regions supported by lex.
=> fix(Interactions): Added all supported regions to service

packages/amplify-provider-awscloudformation/lib/setup-new-user.js
Updated the user addition URL to include selected region instead of undefined. Updated code to use async/await
instead of promises
fix #4735
=> fix(amplify-provider-awscloudformation): include region configure url

packages/amplify-frontend-javascript/lib/configuration-manager.js, packages/amplify-frontend-javascript/lib/framework-config-mapping.js, packages/amplify-frontend-javascript/package.json
Added support for detecting the distribution directory for angular project
fix #4669
=> feat(amplify-frontend-javascript): detect dist dir in angular

packages/amplify-frontend-javascript/lib/framework-config-mapping.js, packages/amplify-frontend-javascript/package.json
Updated function export to commonjs to support amplify-app
=> fix(amplify-frontend-javascript): changed exports to common js

packages/amplify-provider-awscloudformation/lib/system-config-manager.js
=> Configureissue

.circleci/config.yml, packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts
*Issue #5114 
* Change addResource function to return resourceName instead of functionName
=> fix: returns resourename instead of function

packages/amplify-frontend-javascript/lib/configuration-manager.js, packages/amplify-frontend-javascript/lib/framework-config-mapping.js
*Issue #5228 
* Revert changes in files for the above error
=> fix: revert frontend config files

.circleci/config.yml, packages/amplify-cli/src/init-steps/postInitSetup.ts, packages/amplify-cli/src/packageManagerHelpers.ts
fix #5068
#5068
Use ```serve``` command if the script exists in package.json
=> fix: support serve script

.circleci/config.yml, packages/amplify-category-auth/src/provider-utils/awscloudformation/index.js
*Issue #5219
* Change the old trigger assets path to new one
=> fix: change trigger assets path

packages/amplify-cli/src/commands/console.ts
=> fix(cli): fix amplify console url

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/get-env-info.test.ts
=> test: update unit test for stateManager refactor of get-env-info

packages/amplify-category-auth/src/index.js, packages/amplify-category-auth/src/provider-utils/awscloudformation/handlers/get-add-auth-handler.ts
Fix imports and return value of addResource 
=> fix: imports and addResource return val

packages/amplify-cli-core/src/state-manager/pathManager.ts, packages/amplify-cli/src/index.ts, packages/amplify-cli/tsconfig.json, packages/amplify-provider-awscloudformation/lib/system-config-manager.js
=> fix: update default file permissions for credentials/config

.circleci/config.yml, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/appSyncHelper.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/cloudformationHelpers.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/constants.ts
=> fix(amplify-category-function): removing envVariable for appsync storage

packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js, packages/amplify-e2e-core/src/categories/storage.ts, packages/amplify-e2e-tests/src/__tests__/storage.test.ts
=> fix(amplify-category-storage): fix storage update with trigger added

.circleci/config.yml, packages/amplify-e2e-tests/src/__tests__/amplify-configure.test.ts, packages/amplify-provider-awscloudformation/lib/setup-new-user.js
=> fix(amplify-provider-awscloudformation): validate config input

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/__snapshots__/appSync-walkthrough.test.ts.snap, packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.test.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts
*Issue #5240 
* Introduce case where no configure additional auth type option selected
* Added test for the same case
=> fix: removes duplicate auth types

packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts
*Issue:#5240
* checks for null Config in add api flow
=> fix: checking undefined auth config

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/funcParamsUtils.ts
=> fix: duplicate dependsOn entries for layers on update function

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts, packages/amplify-e2e-core/src/categories/lambda-function.ts, packages/amplify-e2e-tests/src/__tests__/function_1.test.ts, packages/amplify-nodejs-function-template-provider/resources/lambda/hello-world/index.js.ejs
=> feat: added commented out cors headers

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts
=> Function comments

packages/amplify-cli/src/__tests__/test-aborting.test.ts, packages/amplify-cli/src/index.ts, packages/amplify-cli/src/version-notifier.ts
=> fix: abort being called multiple times

packages/amplify-category-function/package.json, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/lambda-layer-cloudformation-template.ts, yarn.lock
=> chore(amplify-category-function): add missing cloudform-types dependency

.circleci/config.yml, packages/amplify-console-integration-tests/__tests__/pullAndInit.test.ts, packages/amplify-console-integration-tests/src/pullAndInit/amplifyArtifactsManager.ts, packages/amplify-console-integration-tests/src/pullAndInit/pullProject.ts, packages/amplify-frontend-javascript/lib/configuration-manager.js, packages/amplify-frontend-javascript/lib/framework-config-mapping.js
Updated the headless pull to use the updated framework detection methods
fix #5228
=> fix(amplify-frontend-javascript): fix headless pull

.circleci/config.yml, packages/amplify-e2e-tests/src/schema-api-directives/tests/function-differentRegion.ts
=> test(amplify-e2e-tests): change test region

packages/amplify-category-predictions/index.js
=> fix: fixed bad import

packages/amplify-util-mock/src/utils/git-ignore.ts
=> refactor(amplify-util-mock): fix a regex

packages/amplify-category-predictions/provider-utils/awscloudformation/prediction-category-walkthroughs/identify-walkthrough.js, packages/amplify-nodejs-function-template-provider/src/utils/eventSourceWalkthrough.ts
=> fix: fixed typos and bad import

packages/amplify-codegen/src/commands/models.js, packages/amplify-codegen/src/utils/getSchemaDownloadLocation.js, packages/amplify-codegen/tests/utils/getSchemaDownloadLocation.test.js
*Issue #5226 
* Checks for the project config for sourceDir 
=> fix: changed default config to user defined config

packages/amplify-category-auth/src/index.js, packages/amplify-e2e-core/src/categories/auth.ts, packages/amplify-e2e-tests/src/__tests__/auth_1.test.ts
=> fix(amplify-category-auth): fix auth console

packages/amplify-category-function/src/__tests__/__snapshots__/index.test.ts.snap, packages/amplify-category-function/src/__tests__/index.test.ts, packages/amplify-category-function/src/index.ts
*Issue #4761
* Added a Check on DependsOn Array
=> fix: check on  dependsOn Array

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-json-metadata-visitor.test.ts, packages/amplify-codegen-appsync-model-plugin/src/utils/get-type-info.ts
isListNullable needs to return true when list is nullable due to the name change from PR #5327 
=> fix(amplify-codegen-appsync-model-plugin): fixed nullable lists

packages/amplify-cli/src/__tests__/get-tags.test.ts, packages/amplify-cli/src/extensions/amplify-helpers/get-tags.ts, packages/amplify-e2e-tests/src/__tests__/tags.test.ts
=> fix(cli): fixed projName and envName

packages/amplify-cli/src/utils/mobilehub-support.ts
fix: mobile hub check miss for uninitialized projects
=> fix: mobile hub check miss for uninitialized projects

packages/amplify-dotnet-function-template-provider/package.json
=> chore: added amplify-cli-cire dependency to dotnet-function

packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js, packages/amplify-provider-awscloudformation/src/initialize-env.js
fix: filter our providers when processing meta
=> fix: filter our providers when processing meta

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts
fix: extra check for permission add for storage and functions.
=> fix: extra check for permission add for storage and functions

packages/amplify-util-mock/src/utils/lambda/execute.ts
=> fix: fixed exit codes on message

packages/amplify-category-auth/src/provider-utils/supported-services.ts
update login with amazon instructions with more friendly URL that has better information.
*Issue #, if available:* this is an update of https://github.com/aws-amplify/amplify-cli/pull/5294/ after some more user testing.
=> chore: update login with Amazon instructions in CLI

packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthrough-types.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-request-adaptors.ts
Fixes the bug caught here: https://31980-145880460-gh.circle-artifacts.com/0/~/repo/packages/amplify-e2e-tests/amplify-e2e-reports/index.html
=> fix: username is default signin, doesn't need to be specified

packages/amplify-console-integration-tests/__tests__/pullAndInit.test.ts
fix the two tests that need Amplify Console App created
=> test(amplify-console-integration-tests): fix test

packages/amplify-cli/src/__tests__/test-aborting.test.ts, packages/amplify-cli/src/index.ts
=> fix(cli): fix print.warn to print.warning

packages/amplify-cli/src/index.ts
=> Disable MobileHub Compatibility Check

packages/amplify-cli/package.json, packages/amplify-cli/src/domain/amplify-usageData/UsageDataPayload.ts, packages/amplify-cli/src/domain/amplify-usageData/VersionManager.ts
=> feat: add isTerminal to payload

Readme.md, yarn.lock
Similar to the [JavaScript repository](https://github.com/aws-amplify/amplify-js/blob/main/README.md), I wanted to provide the same breakdown for Amplify CLI so customers are able to see what are open bugs, what are open feature requests, enhancements, and closed issues.
Screenshot:
=> chore:(README) Update README to show bug count and feature count

packages/amplify-e2e-core/src/categories/analytics.ts
=> Fix on Analytics E2E

packages/amplify-e2e-core/src/categories/analytics.ts, packages/amplify-e2e-tests/src/__tests__/import_auth_1.test.ts, packages/amplify-e2e-tests/src/import-helpers/expects.ts
chore: fix e2e import auth tests, raise kinesis timeout
=> chore: fix e2e import auth tests, raise kinesis timeout

packages/amplify-e2e-tests/src/import-helpers/expects.ts
chore: fix e2e import auth tests
=> chore: fix e2e import auth tests

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json
=> test: added dependencies for amplify logger

packages/amplify-cli-logger/src/AmplifyLogger.ts
=> fix: winston error with 0 transports

packages/amplify-provider-awscloudformation/src/system-config-manager.js, packages/amplify-provider-awscloudformation/src/utility-functions.js, packages/amplify-provider-awscloudformation/src/zip-util.js
=> chore: added absolute path for lib

packages/amplify-cli/src/domain/amplify-usageData/UsageData.ts, packages/amplify-cli/src/domain/amplify-usageData/UsageDataPayload.ts, packages/amplify-cli/src/domain/amplify-usageData/VersionManager.ts
=> fix: ci undefined flag

packages/amplify-graphql-types-generator/test/angular/__snapshots__/index.js.snap
update snapshot test to account for newly added subscriptionResponse interface
=> test(amplify-graphql-types-generator): update snapshot test

packages/amplify-graphiql-explorer/package.json, yarn.lock
Updated react-scripts module and dependencies in yarn.lock
=> fix: updated react-scripts module

packages/amplify-e2e-tests/src/schema-api-directives/tests/key-howTo4.ts, packages/graphql-key-transformer/src/KeyTransformer.ts, packages/graphql-key-transformer/src/__tests__/__snapshots__/KeyTransformer.test.ts.snap
* Fix resolver template parsing error in VTL
* Updated Snapshot and e2e tests
=> fix: fixes sync resolver for mock api

packages/amplify-cli/src/extensions/amplify-helpers/delete-project.ts
=> feat: add env to retain amplify app

packages/graphql-auth-transformer/src/__tests__/__snapshots__/SearchableAuthTransformer.test.ts.snap, packages/graphql-elasticsearch-transformer/src/SearchableModelTransformer.ts, packages/graphql-elasticsearch-transformer/src/__tests__/__snapshots__/SearchableModelTransformer.test.ts.snap, packages/graphql-elasticsearch-transformer/src/definitions.ts, packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformer.e2e.test.ts
=> Add Range Option on String Queries

packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs
Reverts aws-amplify/amplify-cli#3534
=> Revert "For Auth, add PreventUserExistenceErrors parameter and update NodeJS runtime version"

packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformer.e2e.test.ts
fix e2e range test as it tests for gte - lte
=> test(graphql-transformers-e2e-tests): fix e2e range test

packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformer.e2e.test.ts
=> test: update expected result

packages/amplify-provider-awscloudformation/src/zip-util.js
fix unhandled promise rejection in downloading zip file from deployment bucket
fix #4880
=> fix(amplify-provider-awscloudformation): fix unhandled promise rejection

CONTRIBUTING.md
re https://github.com/aws-amplify/amplify-cli/issues/5646
=> docs: add description on git hooks

packages/graphql-transformers-e2e-tests/src/cognitoUtils.ts
=> test(graphql-transformers-e2e-tests): remove console.log

packages/graphql-transformer-core/src/util/sanity-check.ts
increase stack resource limit per aws cfn limit increase
=> fix(graphql-transformer-core): increase stack resource limit

packages/amplify-e2e-tests/schemas/migrations_key/cant_add_multiple_gsi.graphql, packages/amplify-e2e-tests/schemas/migrations_key/four_key_model_schema.graphql, packages/amplify-e2e-tests/schemas/migrations_key/two_key_model_schema.graphql, packages/amplify-e2e-tests/src/__tests__/migration/api.key.migration2.test.ts, packages/graphql-transformer-core/src/util/sanity-check.ts
allow diff tables to push single gsi changes
=> fix(graphql-transformer-core): fix gsi update sanity check

packages/amplify-e2e-tests/src/__tests__/migration/api.key.migration2.test.ts
=> test(amplify-e2e-tests): fix path in gsi e2e

packages/amplify-e2e-tests/src/__tests__/migration/api.key.migration2.test.ts
=> e2e casing fix

package.json
=> chore: fix backendManager npm publish script

.circleci/config.base.yml, .circleci/config.yml
fix git complaining about not knowing how to make commits
=> fix: add dummy git config for pub to verdaccio

packages/amplify-provider-awscloudformation/src/admin-login.ts, packages/amplify-provider-awscloudformation/src/utils/admin-login-server.ts
=> Admin login fix

packages/amplify-cli/src/commands/pull.ts, packages/amplify-cli/src/pre-deployment-pull.ts
=> chore: change backendManagerAppId to sandboxId

packages/amplify-e2e-core/src/utils/projectMeta.ts
=> test: fix for default deploymentSecrets

packages/amplify-migration-tests/src/__tests__/migration_tests/auth-deployment-migration/auth.deployment.secrets.test.ts
=> test: fixed assertion deployment secret migration tests

.circleci/config.base.yml, .circleci/config.yml, packages/amplify-migration-tests/src/__tests__/migration_tests/auth-deployment-migration/auth.deployment.secrets.test.ts
=> Test fix status

packages/amplify-console-integration-tests/__tests__/pullAndInit.test.ts, packages/amplify-e2e-tests/src/__tests__/auth_2.test.ts
=> test: check for truthy and falsy

packages/amplify-e2e-core/src/utils/projectMeta.ts
=> test: check for rootstackid

packages/amplify-codegen/src/commands/models.js
Fixes https://github.com/aws-amplify/amplify-cli/issues/5864
=> fix(amplify-codegen): generate eslintignore in js

packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js
Fix `resourceName` reference in update storage walkthrough.
=> fix: fix resourceName ref

packages/amplify-provider-awscloudformation/src/delete-env.js
Due to the retention policy CF does not remove S3 storage bucket, this fix explicitly deleting it after the stack is gone.
=> fix: explicitly remove storage bucket after stack delete

packages/amplify-category-api/src/commands/api/console.js, packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/index.js, packages/amplify-cli/src/commands/console.ts, packages/amplify-provider-awscloudformation/src/index.ts, packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts
=> fix: support disabling admin

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-dart-visitor.ts
=> fix: revert changes for toJson

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap, packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-dart-visitor.ts
Quick fix for datetime tostring method
=> fix: change the datetime tostring method

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
Fix the snapshot for dart modelgen unit tests
=> fix: snapshot for dart modelgen

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/envResourceParams.test.ts, packages/amplify-cli/src/extensions/amplify-helpers/envResourceParams.ts, packages/amplify-cli/src/utils/team-provider-migrate.ts
=> fix: removing deployment secrets and skip check on get

packages/amplify-e2e-tests/src/__tests__/api_1.test.ts, packages/amplify-frontend-flutter/lib/amplify-config-helper.js, packages/amplify-frontend-flutter/lib/configuration-manager.js
Adds API functionality to flutter plugin.
=> feat(amplify-frontend-flutter): adds api construction to flutter

packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js
=> fix: check hostedUI flag

packages/amplify-cli-core/src/feature-flags/featureFlags.ts, packages/amplify-codegen/package.json, packages/amplify-codegen/src/commands/models.js, packages/amplify-codegen/src/utils/getCodegenPackageName.js, packages/amplify-codegen/src/utils/index.js, packages/amplify-codegen/tests/utils/getCodegenPackage.test.js, yarn.lock
* Added FF for Codegen  Migration
* Added test to check for migrating package
=> chore: Added FF to facilitate Codegen Migration

packages/amplify-provider-awscloudformation/src/push-resources.js
=> change root-stack description based on if admin app is created or not

packages/amplify-cli-core/src/__tests__/deploymentSecretsHelper.test.ts, packages/amplify-cli-core/src/deploymentSecretsHelper.ts
=> fix: fix to ignore deployment secret if not found

packages/amplify-cli/src/utils/team-provider-migrate.ts
=> fix: migrate check for env command

packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs, packages/amplify-e2e-tests/src/import-helpers/expects.ts, packages/amplify-frontend-android/lib/frontend-config-creator.js, packages/amplify-frontend-ios/lib/frontend-config-creator.js
=> Revert: "fix: remove app client secret as best practice"

packages/amplify-cli/src/commands/configure.ts, packages/amplify-cli/src/commands/pull.ts, packages/amplify-provider-awscloudformation/src/attach-backend.js, packages/amplify-provider-awscloudformation/src/configuration-manager.js, packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts, packages/amplify-provider-awscloudformation/src/utils/resolve-appId.ts
Broke some flows in amplify pull in previous commit
=> fix: amplify pull in backendManager branch

packages/amplify-provider-awscloudformation/src/attach-backend.js, packages/amplify-provider-awscloudformation/src/configuration-manager.js, packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts
=> fix: amplify pull for backendManager branch 2.0

packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/index.js, packages/amplify-cli/src/commands/console.ts, packages/amplify-cli/src/commands/pull.ts, packages/amplify-cli/src/pre-deployment-pull.ts, packages/amplify-provider-awscloudformation/src/configuration-manager.js, packages/amplify-provider-awscloudformation/src/index.ts, packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts, packages/amplify-provider-awscloudformation/src/utils/admin-login-server.ts, yarn.lock
Address feedback and fix bugs on PR #5941.
=> fix: address more PR feedback

packages/amplify-cli/src/initialize-env.ts, packages/amplify-provider-awscloudformation/src/attach-backend.js, packages/amplify-provider-awscloudformation/src/utils/resolve-appId.ts
=> fix: typo, rework misleading error message

packages/amplify-cli-core/src/errors/index.ts, packages/amplify-cli/src/commands/configure.ts, packages/amplify-cli/src/commands/console.ts, packages/amplify-cli/src/commands/logout.ts, packages/amplify-cli/src/pre-deployment-pull.ts, packages/amplify-provider-awscloudformation/src/admin-login.ts, packages/amplify-provider-awscloudformation/src/configuration-manager.js, packages/amplify-provider-awscloudformation/src/utils/admin-login-server.ts
=> fix: handle missing region for configure, address PR feedback

.circleci/config.base.yml, .circleci/config.yml, package.json
=> chore: add pkg cli to release workflow

packages/amplify-category-auth/src/provider-utils/awscloudformation/index.js
=> fix: appId is only required for admin

packages/amplify-category-auth/src/provider-utils/awscloudformation/index.js
=> fix: add check for undefined appId

packages/amplify-provider-awscloudformation/src/amplify-service-manager.js, packages/amplify-provider-awscloudformation/src/amplify-service-migrate.js, packages/amplify-provider-awscloudformation/src/amplify-service-permission-check.js, packages/amplify-provider-awscloudformation/src/attach-backend.js, packages/amplify-provider-awscloudformation/src/initialize-env.js, packages/amplify-provider-awscloudformation/src/initializer.js, packages/amplify-provider-awscloudformation/src/push-resources.js, packages/amplify-provider-awscloudformation/src/upload-appsync-files.js
=> fix: fixed requires referencing 'src' in path

packages/amplify-cli-logger/package.json, packages/amplify-nodejs-function-template-provider/package.json
=> fix: fixed core references

packages/amplify-e2e-tests/src/__tests__/function_1.test.ts, packages/amplify-nodejs-function-template-provider/resources/lambda/crud/app.js.ejs, packages/amplify-nodejs-function-template-provider/resources/lambda/hello-world/index.js.ejs, packages/amplify-nodejs-function-template-provider/resources/lambda/serverless/app.js.ejs
*Issue #5763 
* Added ```"Access-Control-Allow-Headers" ``` to ``` " * "```. 
=> fix: added CORS headers to allow all types

packages/amplify-category-analytics/provider-utils/awscloudformation/cloudformation-templates/kinesis-cloudformation-template.json
N/A
typo in cloudformation template for kinesis
=> fix: typo in cloudformation template for Kinesis

packages/amplify-cli/src/extensions/amplify-helpers/git-manager.ts
It appears briefly during `amplify push`.
Add a temporary directory to .gitignore.
=> Add .temp file to .gitignore.

packages/amplify-provider-awscloudformation/src/aws-utils/aws-s3.ts
Clean up logging during push. Currently, the output flickers between upper and lower case.
=> Use consistent case for messaging during uploads.

packages/amplify-provider-awscloudformation/src/configuration-manager.js, packages/amplify-provider-awscloudformation/src/push-resources.ts
=> fix: incorrect params and return value check

packages/amplify-e2e-tests/src/__tests__/__snapshots__/function_2.test.ts.snap, packages/amplify-nodejs-function-template-provider/resources/lambda/hello-world/index.js.ejs
*Issue #5763 
* Updated snapshot and added comments for CORS headers in lambda boilerplate code
=> fix: update snapshot

.circleci/config.yml
Testing the install script pipeline and pointing the workflow to merge to install-script-prod
=> Point pkg cli install script to install-script-prod branch

packages/amplify-app/src/index.js, packages/amplify-cli/src/pre-deployment-pull.ts
=> fix: check amplify/backend to determine project existence

packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js
=> revert(amplify-provider-awscloudformation): removed cfn logging

packages/amplify-cli/src/conditional-local-logging-init.ts, packages/amplify-cli/src/index.ts
=> fix: disabling local logging

packages/amplify-provider-awscloudformation/resources/rootStackTemplate.json, packages/amplify-provider-awscloudformation/src/push-resources.ts
=> fix: version bucket conditional

packages/amplify-category-api/.npmignore
=> fix: only ignore root src folder

packages/amplify-category-api/src/provider-utils/awscloudformation/ecs-alb-stack.ts, packages/amplify-container-hosting/lib/ElasticContainer/index.js, packages/amplify-container-hosting/resources/express-template/Dockerfile
containers - don't wait for pipeline on hosting
=> fix: containers - don't wait for pipeline on hosting

packages/amplify-cli/src/__tests__/redaction.test.ts, packages/amplify-cli/src/domain/amplify-usageData/identifiable-input-regex.ts
=> feat: added exception item into options

packages/amplify-cli/src/__tests__/redaction.test.ts, packages/amplify-cli/src/domain/amplify-usageData/identifiable-input-regex.ts
Reverts aws-amplify/amplify-cli#6018
=> Revert "feat: added exception item into options"

packages/amplify-cli-core/src/feature-flags/featureFlags.ts, packages/amplify-frontend-ios/event-handlers/handle-PostCodegenModels.js, packages/amplify-frontend-ios/event-handlers/handle-PostInit.js
This PR adds a new feature flag for controlling the [CLI integration with Xcode](https://github.com/aws-amplify/amplify-cli/pull/5977).
=> feat(amplify-frontend-ios): xcode integration feature flag

packages/amplify-e2e-tests/schemas/migrations_key/four_gsi_model_schema.graphql, packages/amplify-e2e-tests/schemas/migrations_key/three_gsi_model_schema.graphql, packages/amplify-e2e-tests/src/__tests__/migration/api.key.migration2.test.ts, packages/graphql-transformer-core/src/util/sanity-check.ts
fixes #6013
fix gsi cant mutate multiple gsi to only look for gsi changes and not ks or attr changes
=> fix(graphql-transformer-core): fix gsi mutate san check

CONTRIBUTING.md
=> chore: add setup and test notes in contributing.md

packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js
=> fix(amplify-provider-awscloudformation): infinite loop on stack failure

packages/amplify-cli/src/__tests__/team-provider-migrate.test.ts, packages/amplify-cli/src/__tests__/test-aborting.test.ts, packages/amplify-cli/src/extensions/amplify-helpers/envResourceParams.ts, packages/amplify-cli/src/utils/team-provider-migrate.ts
=> fix: hostedUIProviderCreds Not found and check for localenv

packages/amplify-cli/src/extensions/amplify-helpers/remove-pinpoint-policy.ts, packages/amplify-cli/src/extensions/amplify-helpers/resource-status.ts, packages/amplify-e2e-tests/src/__tests__/analytics.test.ts
=> refactor: remove getUserEndpoints on push

packages/amplify-cli/src/extensions/amplify-helpers/remove-pinpoint-policy.ts
=> fix: check that cfn template exists

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/auth-defaults-appliers.test.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-defaults-appliers.ts
Reverts aws-amplify/amplify-cli#6071
=> Revert "fix: ensure auth selections overwrite defaults"

packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts, packages/graphql-connection-transformer/src/__tests__/NewConnectionTransformer.test.ts, packages/graphql-connection-transformer/src/__tests__/__snapshots__/NewConnectionTransformer.test.ts.snap, packages/graphql-connection-transformer/src/resources.ts, packages/graphql-dynamodb-transformer/src/definitions.ts, packages/graphql-key-transformer/src/KeyTransformer.ts, packages/graphql-key-transformer/src/__tests__/KeyTransformer.test.ts, packages/graphql-transformer-common/src/definition.ts
Reverts aws-amplify/amplify-cli#5319
=> Revert "fix(graphql-key-transformer): prevent non-scalar key fields"

packages/graphql-auth-transformer/src/__tests__/__snapshots__/SearchableAuthTransformer.test.ts.snap, packages/graphql-connection-transformer/src/__tests__/__snapshots__/ModelConnectionTransformer.test.ts.snap, packages/graphql-connection-transformer/src/__tests__/__snapshots__/NewConnectionTransformer.test.ts.snap, packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts, packages/graphql-dynamodb-transformer/src/__tests__/__snapshots__/DynamoDBModelTransformer.test.ts.snap, packages/graphql-dynamodb-transformer/src/definitions.ts, packages/graphql-elasticsearch-transformer/src/__tests__/__snapshots__/SearchableModelTransformer.test.ts.snap, packages/graphql-transformer-common/src/definition.ts
Reverts aws-amplify/amplify-cli#6160
=> Revert fix: #6108

packages/amplify-provider-awscloudformation/src/push-resources.ts
=> fix: throw error on failed push

packages/amplify-provider-awscloudformation/src/download-api-models.ts
Adds Flutter to Javascript for rest client file generation exclusions.
=> fix(amplify-provider-awscloudformation): fixes rest client generation

packages/amplify-cli-core/src/index.ts, packages/amplify-cli/src/commands/configure.ts, packages/amplify-cli/src/commands/pull.ts, packages/amplify-cli/src/extensions/amplify-helpers/make-id.ts, packages/amplify-e2e-core/src/utils/projectMeta.ts, packages/amplify-provider-awscloudformation/src/aws-utils/CognitoUserPoolService.ts, packages/amplify-provider-awscloudformation/src/aws-utils/DynamoDBService.ts, packages/amplify-provider-awscloudformation/src/aws-utils/IdentityPoolService.ts, packages/amplify-provider-awscloudformation/src/aws-utils/S3Service.ts, packages/amplify-provider-awscloudformation/src/aws-utils/aws-apigw.ts, packages/amplify-provider-awscloudformation/src/aws-utils/aws-ecr.ts, packages/amplify-provider-awscloudformation/src/aws-utils/aws-s3.ts, packages/amplify-provider-awscloudformation/src/configuration-manager.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/amplify-graphql-resource-manager.ts, packages/amplify-provider-awscloudformation/src/iterative-deployment/deployment-manager.ts, packages/amplify-provider-awscloudformation/src/network/environment-info.ts, packages/amplify-provider-awscloudformation/src/question-flows/configuration-questions.ts
=> chore: convert configuration-manager to TS

packages/amplify-cli/src/commands/publish.ts, packages/amplify-provider-awscloudformation/src/attach-backend.js, packages/amplify-provider-awscloudformation/src/configuration-manager.ts, packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts, yarn.lock
=> fix: #6168, update error messages, yarn.lock

packages/amplify-cli/src/utils/team-provider-migrate.ts
=> fix: skip check on delete and go ahead on force

packages/amplify-cli-core/src/state-manager/stateManager.ts, packages/amplify-provider-awscloudformation/src/configuration-manager.ts
=> fix(amplify-provider-awscloudformation): load correct file

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
=> fix: updateSnaphot for #6145

packages/amplify-provider-awscloudformation/src/push-resources.ts
=> fix: print warnings for CFN lint

packages/amplify-provider-awscloudformation/src/__tests__/utils/aws-logging.test.ts, packages/amplify-provider-awscloudformation/src/system-config-manager.js
Test for undefined
https://github.com/aws-amplify/amplify-cli/pull/6161
=> feat: added tests and logging coverage for system config

packages/amplify-e2e-tests/src/__tests__/api_1.test.ts
Update flutter e2e test to match latest changes
=> test: update flutter codegen prompt not expected

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/service-select-prompt.test.ts, packages/amplify-cli/src/extensions/amplify-helpers/service-select-prompt.ts
*Issue #, if available: #6285
*Description of changes: Handled the providers being undefined and also refactored a bit for readability. Added 4 unit tests as well
=> fix(cli): handle undefined enabledProviders

packages/amplify-e2e-core/src/init/amplifyPull.ts, packages/amplify-e2e-core/src/init/initProjectHelper.ts, packages/amplify-e2e-core/src/utils/admin-ui.ts, packages/amplify-e2e-core/src/utils/index.ts, packages/amplify-e2e-tests/src/__tests__/init.test.ts, packages/amplify-e2e-tests/src/types/SandboxApp.ts
A test covering the amplify pull sandbox workflow
=> test: sandbox id pull schema and init test

packages/amplify-headless-interface/schemas/api/1/AddApiRequest.schema.json, packages/amplify-headless-interface/schemas/api/1/UpdateApiRequest.schema.json, packages/amplify-headless-interface/schemas/auth/1/AddAuthRequest.schema.json, packages/amplify-headless-interface/schemas/auth/1/UpdateAuthRequest.schema.json, packages/amplify-headless-interface/schemas/storage/1/AddStorageRequest.schema.json, packages/amplify-headless-interface/src/interface/api/add.ts, packages/amplify-headless-interface/src/interface/api/update.ts, packages/amplify-headless-interface/src/interface/auth/add.ts, packages/amplify-headless-interface/src/interface/auth/update.ts, packages/amplify-headless-interface/src/interface/storage/add.ts
The schema.json files are autogenerated. You only need to look at the .ts files for the diff
=> chore: add headless interface comments and remove unused params

packages/amplify-category-api/resources/awscloudformation/container-templates/dockercompose-rest-express/express/package.json, packages/amplify-category-auth/resources/adminAuth/admin-auth-package.json, packages/amplify-util-mock/package.json, packages/graphql-transformers-e2e-tests/package.json, yarn.lock
=> chore: dependency version bumps for axios and others

packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts
*Issue : fixes layer tests after removeing  Node modules from #CurCloudbackend
* Added check to remove node_modules from Lambda functions
=> fix: fixes Layer tests after removing nodeModules from #CurrentCloudbackend

packages/amplify-frontend-android/lib/amplify-config-helper.js, packages/amplify-frontend-flutter/lib/amplify-config-helper.js, packages/amplify-frontend-ios/lib/amplify-config-helper.js, packages/amplify-frontend-ios/lib/configuration-manager.js, packages/amplify-frontend-javascript/lib/configuration-manager.js, packages/amplify-provider-awscloudformation/src/configuration-manager.ts
Native projects were missing to enable container based deployments
=> fix: container based deployments on native projects

packages/amplify-cli-core/src/index.ts, packages/amplify-cli/src/commands/push.ts, packages/amplify-cli/src/extensions/amplify-helpers/construct-exeInfo.ts, packages/amplify-cli/src/extensions/amplify-helpers/get-all-envs.ts, packages/amplify-cli/src/extensions/amplify-helpers/push-resources.ts, packages/amplify-cli/src/extensions/amplify-helpers/service-select-prompt.ts, packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts, packages/amplify-provider-awscloudformation/src/admin-login.ts, packages/amplify-provider-awscloudformation/src/configuration-manager.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts, packages/amplify-provider-awscloudformation/src/question-flows/configuration-questions.ts, packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts, packages/amplify-provider-awscloudformation/src/utils/admin-login-server.ts, packages/amplify-provider-awscloudformation/src/utils/auth-types.ts
Separating some refactoring I did from feature work to make the diff easier to read.
=> refactor: improve TS types, update file name

packages/amplify-cli-core/src/errors/index.ts, packages/amplify-frontend-javascript/lib/configuration-manager.js, packages/amplify-frontend-javascript/lib/framework-config-mapping.js
Improves the error message in #6246.
=> fix: better error message when angular.json is missing

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts, packages/graphql-auth-transformer/src/__tests__/PerFieldAuthArgument.test.ts, packages/graphql-auth-transformer/src/__tests__/__snapshots__/PerFieldAuthArgument.test.ts.snap, packages/graphql-auth-transformer/src/resources.ts
make sure to return the result if auth is used on a connection field
fix #4760
=> fix(graphql-auth-transformer): fix field auth with connection

packages/amplify-cli-core/src/__tests__/statemanager.getTags.test.ts, packages/amplify-cli-core/src/state-manager/pathManager.ts, packages/amplify-cli-core/src/state-manager/stateManager.ts, packages/amplify-cli-core/src/tags/Tags.ts, packages/amplify-cli/src/__tests__/get-tags.test.ts, packages/amplify-cli/src/extensions/amplify-helpers/get-tags.ts, packages/amplify-cli/src/extensions/amplify-helpers/resource-status.ts, packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts, packages/amplify-cli/src/init-steps/s0-analyzeProject.ts, packages/amplify-provider-awscloudformation/src/initializer.js, packages/amplify-provider-awscloudformation/src/push-resources.ts
The goal of this PR is to apply tags when the rootstack is initialized
=> fix: apply tags on create and push nested stack

.eslintrc.js, .gitignore, packages/amplify-console-integration-tests/src/util.ts
Fix console integration test by updating an `fs.readfilesync` signature.
=> chore: update console integration test

packages/amplify-frontend-android/lib/amplify-config-helper.js
N/A
Fix a regression from #6132 when frontend configuration for Android projects did not include the resources after push
=> fix: regression from #6132

packages/amplify-e2e-core/src/categories/lambda-function.ts
Fix E2E test prompt check for resource permissions
=> chore: fix e2e test prompt check

.github/ISSUE_TEMPLATE/bug_report.md
Updated template to include log output location.
=> docs: log output statement to issue template

packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs
Generates condition only when userPool is enabled in the template
=> fix: generating condition for user pool

packages/amplify-e2e-core/src/categories/lambda-function.ts, packages/amplify-e2e-tests/src/__tests__/function_2.test.ts
Fixes test introduced by #5342
=> test: fixes e2e function with api perm test

packages/amplify-e2e-tests/src/__tests__/import_auth_2.test.ts
=> test: update the profile name for auth headless import

packages/amplify-e2e-tests/src/__tests__/import_auth_1.test.ts
=> test: update auth test to pass appClientWeb

packages/amplify-category-analytics/package.json, packages/amplify-category-api/package.json, packages/amplify-dotnet-function-template-provider/package.json, packages/amplify-graphql-transformer-core/package.json, packages/amplify-nodejs-function-template-provider/package.json, packages/graphql-transformer-core/package.json, yarn.lock
=> chore: update internal dependencies to latest versions

packages/amplify-e2e-tests/src/__tests__/tags.test.ts, packages/amplify-provider-awscloudformation/src/amplify-service-manager.js
Reverts aws-amplify/amplify-cli#6381, needs additional permission breaks dependencies
=> Revert "feat: provide tags on create app"

packages/amplify-e2e-tests/src/__tests__/function_2.test.ts, packages/amplify-migration-tests/src/__tests__/migration_tests/auth-deployment-migration/auth.deployment.secrets.test.ts
Remove it only left over from an earlier test fix
=> test: removed left over it.only

packages/amplify-e2e-core/src/categories/lambda-function.ts, packages/amplify-e2e-tests/src/__tests__/function_3.test.ts
https://50678-145880460-gh.circle-artifacts.com/0/%7E/repo/packages/amplify-e2e-tests/amplify-e2e-reports/index.html
Increase python mock timeout in test.
=> test: update python mock timeout

.circleci/config.yml, packages/amplify-category-function/src/index.ts, packages/amplify-cli/src/initialize-env.ts, packages/amplify-cli/src/pull-backend.ts, packages/amplify-e2e-core/src/categories/lambda-function.ts, packages/amplify-e2e-tests/src/__tests__/function_5.test.ts
=> fix: persist s3bucket metadata on pull and env change

packages/amplify-category-storage/src/index.js, packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js
*Issue #6131 e2e fix
* fixed the return type of GetPermissionsPolices fn.
=> fix: issue #6131 e2e fix

packages/amplify-util-mock/package.json
=> chore: dedupe amplify-cli-core dependecy in amplify-util-mock

packages/amplify-e2e-tests/src/__tests__/amplify-app.test.ts, packages/amplify-e2e-tests/src/__tests__/interactions.test.ts, packages/amplify-e2e-tests/src/configure_tests.ts, packages/amplify-provider-awscloudformation/package.json, packages/amplify-provider-awscloudformation/src/configuration-manager.ts
=> fix: check --yes flag instead of CI env vars, clean up test imports

packages/amplify-provider-awscloudformation/src/configuration-manager.ts
=> fix: add missing check for undefined

packages/amplify-migration-tests/src/__tests__/migration_tests/auth-deployment-migration/auth.deployment.secrets.test.ts, packages/amplify-migration-tests/src/__tests__/migration_tests/transformer_migration/api.key.migration.test.ts, packages/amplify-migration-tests/src/__tests__/migration_tests/transformer_migration/api.searchable.migration.test.ts, packages/amplify-migration-tests/src/__tests__/update_tests/api_migration_update.test.ts, packages/amplify-migration-tests/src/__tests__/update_tests/auth_migration_update.test.ts, packages/amplify-migration-tests/src/__tests__/update_tests/function_migration_update.test.ts, packages/amplify-migration-tests/src/__tests__/update_tests/storage_migration_update.test.ts, packages/amplify-migration-tests/src/migration-helpers/init.ts, packages/amplify-provider-awscloudformation/src/configuration-manager.ts
=> test: update migration tests to handle new text

packages/amplify-migration-tests/src/__tests__/migration_tests/auth-deployment-migration/auth.deployment.secrets.test.ts, packages/amplify-migration-tests/src/__tests__/migration_tests/transformer_migration/api.key.migration.test.ts, packages/amplify-migration-tests/src/__tests__/migration_tests/transformer_migration/api.searchable.migration.test.ts, packages/amplify-migration-tests/src/__tests__/update_tests/api_migration_update.test.ts, packages/amplify-migration-tests/src/__tests__/update_tests/auth_migration_update.test.ts, packages/amplify-migration-tests/src/__tests__/update_tests/function_migration_update.test.ts, packages/amplify-migration-tests/src/__tests__/update_tests/storage_migration_update.test.ts, packages/amplify-migration-tests/src/migration-helpers/check-version.ts, packages/amplify-migration-tests/src/migration-helpers/index.ts, packages/amplify-migration-tests/src/migration-helpers/init.ts, packages/amplify-provider-awscloudformation/src/configuration-manager.ts, packages/amplify-provider-awscloudformation/src/delete-env.js
=> test(amplify-migration-tests): fix cci test failures, add version helper

packages/amplify-cli/scripts/post-install.js, packages/amplify-frontend-flutter/lib/configuration-manager.js
Removes 'Developer Preview' text from the Flutter project init flow.
=> refactor(amplify-frontend-flutter): removes Flutter dev preview text

packages/amplify-app/src/index.js
=> fix: generate flutter amp config in lib

packages/amplify-appsync-simulator/src/velocity/index.ts, packages/amplify-appsync-simulator/src/velocity/util/errors.ts, packages/amplify-appsync-simulator/src/velocity/util/general-utils.ts, packages/amplify-util-mock/src/__e2e__/util-method-e2e.test.ts, packages/amplify-util-mock/src/__e2e__/utils/index.ts
Updated the simulator to expose util.errors
fix #6068
=> fix(amplify-appsync-simulator): expose errors from util.validate

packages/amplify-category-hosting/package.json
=> build(amplify-category-hosting): update amplify-cli-core version

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/__snapshots__/legacy-update-resource.test.ts.snap, packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/legacy-update-resource.test.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/legacy-add-resource.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/legacy-update-resource.ts
*Issue #6113
*  added code to set the policy resource name in api update flow
=> fix: sets policy resource name in api update flow

packages/amplify-e2e-tests/package.json, packages/graphql-transformers-e2e-tests/package.json
This reverts commit 918eb4f735f0d667bca7ecf591e1a08667b419d6.
=> Revert "chore: update amplify lib version (#6544)"

CONTRIBUTING.md
#6585 
Fix minor typo on line 64 under Getting Started with Development section
=> Minor fix in development setup section under CONTRIBUTING.md

CONTRIBUTING.md
*Issue #, if available:* fixes #6614
Added a note for Windows users in CONTRIBUTING.md
=> docs: add note for Windows users in CONTRIBUTING.md

packages/amplify-appsync-simulator/package.json, packages/amplify-category-api/resources/awscloudformation/container-templates/dockercompose-rest-express/express/package.json, packages/amplify-category-api/resources/awscloudformation/container-templates/dockerfile-rest-express/package.json, packages/amplify-category-api/resources/awscloudformation/container-templates/graphql-express/package.json, packages/amplify-category-auth/package.json, packages/amplify-category-auth/resources/adminAuth/admin-auth-package.json, packages/amplify-category-predictions/package.json, packages/amplify-cli/package.json, packages/amplify-console-hosting/package.json, packages/amplify-console-integration-tests/package.json, packages/amplify-dynamodb-simulator/package.json, packages/amplify-e2e-tests/package.json, packages/amplify-migration-tests/package.json, packages/amplify-nodejs-function-template-provider/resources/lambda/crud/package.json.ejs, packages/amplify-provider-awscloudformation/package.json, packages/amplify-storage-simulator/package.json, packages/amplify-util-import/package.json, packages/amplify-util-mock/package.json, packages/graphql-relational-schema-transformer/package.json, packages/graphql-transformers-e2e-tests/package.json, yarn.lock
=> chore: update aws-sdk version

packages/amplify-cli/src/extensions/amplify-helpers/delete-project.ts
fix: #6153 
This PR highlights the destructive delete project operation:
=> fix: #6153 highlight the destructive delete prompt

packages/amplify-provider-awscloudformation/src/iterative-deployment/deployment-manager.ts
Update the code to use the correct credentials when waiting for DynamoDB table
=> fix(amplify-provider-awscloudformation): use right creds when waiting  for DDB table

CONTRIBUTING.md, Readme.md
*Issue #, if available:* fixes #6654 
Makes the CONTRIBUTING.md more comprehensive with better flow and easier to understand for new contributors.
CONTRIBUTING.md
- Adds table to contents
- Adds following sections:
- Getting Started
- Local Environment Setup
- Architecture of the codebase
- Steps towards contributions
- Code of Conduct
- Security Issue Reporting
- Community
- Adds discord link
- Finding Contributions
- Debugging
Readme.md
- Adds link to Local Environment Setup in Developing section
- Fixes the lint commands and description
=> docs: improves CONTRIBUTING.md

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts, packages/graphql-auth-transformer/src/__tests__/MultiAuth.test.ts
fix #6557
allow appsync auth directives to merge on non model types which are referrenced by model types with
different auth providers
=> fix(graphql-auth-transformer): fix auth on non model types

packages/amplify-category-auth/src/provider-utils/awscloudformation/index.js, packages/amplify-cli/src/extensions/amplify-helpers/envResourceParams.ts, packages/amplify-provider-awscloudformation/src/resourceParams.js
#5942 #6430
This change check if hostedUI is enabled and if the hostedUIProviderCreds are not available it inserts it
=> fix: insert hostedUIProviderCreds empty array on hostedUI

packages/amplify-category-auth/src/provider-utils/awscloudformation/index.js, packages/amplify-provider-awscloudformation/src/resourceParams.js
Reverts aws-amplify/amplify-cli#6485
=> Revert "fix: insert hostedUIProviderCreds empty array on hostedUI"

packages/graphql-key-transformer/src/KeyTransformer.ts, packages/graphql-key-transformer/src/__tests__/__snapshots__/KeyTransformer.test.ts.snap
Remove extra paren introduced in previous PR
=> fix(graphql-key-transformer): fix delta with selective sync query

packages/amplify-go-function-runtime-provider/src/runtime.ts
#6679
Fix ternary to select correct main binary on windows vs other platforms
tested on a windows machine
=> fix: go build on win

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/service-walkthrough-result-to-add-api-request.test.ts, packages/amplify-category-function/src/__tests__/index.test.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts, packages/amplify-dotnet-function-runtime-provider/package.json, packages/amplify-dotnet-function-runtime-provider/src/utils/detect.ts, packages/amplify-dotnet-function-runtime-provider/src/utils/package.ts, packages/amplify-function-plugin-interface/package.json, packages/amplify-go-function-template-provider/package.json, packages/amplify-java-function-runtime-provider/src/index.ts, packages/amplify-java-function-runtime-provider/src/utils/detect.ts, packages/amplify-java-function-runtime-provider/src/utils/package.ts, packages/amplify-java-function-template-provider/package.json, packages/amplify-nodejs-function-runtime-provider/package.json, packages/amplify-nodejs-function-runtime-provider/src/utils/legacyPackage.ts, packages/amplify-python-function-runtime-provider/src/util/buildUtils.ts, packages/amplify-python-function-runtime-provider/src/util/depUtils.ts, packages/amplify-python-function-runtime-provider/src/util/invokeUtil.ts, packages/amplify-python-function-runtime-provider/src/util/packageUtils.ts, packages/amplify-python-function-template-provider/package.json, yarn.lock
bumped up the package version and updated the import
=> build: update package versions

packages/amplify-category-interactions/provider-utils/awscloudformation/function-template-dir/index.js.ejs
*Issue #6347 
* Added envName in interactions Lambda
=> fix: adding envName for intents

packages/amplify-provider-awscloudformation/src/push-resources.ts
#6420
Add check for undefined dependsOn attributes when pushing
=> fix: add check for undefined attributes during push

.github/ISSUE_TEMPLATE/new_bug_report.yaml
[fix] New issue form structure fix indentation level in markdown block
=> (fix) update new_bug_report.yaml

.circleci/config.yml, Dockerfile
=> build: update PATH to include .net tools path

.github/ISSUE_TEMPLATE/bug_report.md
Include a statement to handle regression issues 
=> docs: prior working version

.github/ISSUE_TEMPLATE/new_bug_report.yaml
Correct validation errors:
- fix option `required` field syntax
- replace `None`(reserved word) with `Not applicable`
=> (fix)Update new_bug_report.yaml

packages/amplify-cli/src/__tests__/attach-backend-steps.test.ts, packages/amplify-console-integration-tests/__tests__/pullAndInit.test.ts
This PR fixes the failing console integration test.
=> test: fix console integ test project version comparison

packages/amplify-e2e-tests/src/__tests__/api_2.test.ts
This PR fixes the failing e2e test.
=> test: fix failing admin ui test

.circleci/config.base.yml, .circleci/config.yml, packages/amplify-provider-awscloudformation/src/iterative-deployment/stack-event-monitor.ts
=> Fix throttle

packages/amplify-cli-core/src/feature-flags/featureFlags.ts
=> fix: e2e fix PR #6059

.circleci/config.base.yml, .circleci/config.yml
chore: change base image to node10 for build
=> chore: change base image to node10 for build

.circleci/config.base.yml, .circleci/config.yml
=> ci: remove context for build and tests
