packages/amplify-category-notifications/Readme.md
packages/amplify-category-notifications/commands/notifications.js
packages/amplify-category-notifications/commands/notifications/configure.js
packages/amplify-category-notifications/commands/notifications/remove.js

- add `Cancel` option to the `amplify notifications delete`
- minor readme/help text changes

add cancel to delete and minor readme/help text changes

---

how-to-write-a-transformer.md
packages/graphql-appsync-transformer/src/AppSyncTransformer.ts
packages/graphql-appsync-transformer/src/__tests__/AppSyncTransformer.test.ts
packages/graphql-connection-transformer/src/definitions.ts
packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts
packages/graphql-dynamodb-transformer/src/definitions.ts
packages/graphql-elasticsearch-transformer/src/SearchableModelTransformer.ts
packages/graphql-transformer-common/src/ModelResourceIDs.ts
packages/graphql-transformer-common/src/definition.ts
packages/graphql-transformer-core/src/stripDirectives.ts
packages/graphql-transformers-e2e-tests/src/__tests__/AppSyncTransformer.e2e.test.ts
packages/graphql-versioned-transformer/src/VersionedModelTransformer.ts

Adds subscription support to @model. The @model transformer directive definition has been expanded to:
```graphql
directive @model(
queries: ModelQueryMap,
mutations: ModelMutationMap,
subscriptions: ModelSubscriptionMap
) on OBJECT
input ModelMutationMap { create: String, update: String, delete: String }
input ModelQueryMap { get: String, list: String }
input ModelSubscriptionMap {
onCreate: [String]
onUpdate: [String]
onDelete: [String]
}
```
*Subscription Details*
- By default you get `onXCreated`, `onXUpdated`, and `onXDeleted` for each @model type "X".
- Since a single subscription field can subscribe to multiple mutations, this should be allowed. For example:
```graphql
type Post @model(
subscriptions: {
onCreate: ["onFeedUpdated", "onCreatePost"], …
```

Add support for subscriptions in the @model transformer.

---

packages/amplify-cli/src/extensions/amplify-helpers/path-manager.js
packages/amplify-cli/src/lib/init-steps/s0-analyzeProject.js

The issue was raised by @rohandubal. If the project name is not alphanumeric it later creates issues when generating ID Pools etc
Add a validation -regex check

Add validation/regex check for project name entered to be alphanumeric during init

---

packages/amplify-category-function/provider-utils/awscloudformation/function-template-dir/crud-package.json.ejs
packages/amplify-category-function/provider-utils/awscloudformation/function-template-dir/serverless-app.js.ejs
packages/amplify-category-function/provider-utils/awscloudformation/function-template-dir/serverless-package.json.ejs
packages/amplify-category-hosting/lib/S3AndCloudFront/configuration-manager.js
packages/amplify-category-notifications/lib/pinpoint-helper.js
packages/amplify-cli/src/extensions/amplify-helpers/path-manager.js

https://github.com/aws-amplify/amplify-cli/issues/25
Some basic logging and socket issues resolved in the new version of aws-serverless-express

 Change aws-serverless-express package to latest used by lambda functions

---

packages/graphql-elasticsearch-transformer/package.json
packages/graphql-transformer-core/src/__tests__/GraphQLTransform.test.ts
packages/graphql-transformers-e2e-tests/package.json

Fixes unit tests. e2e package test command changed to e2e.

Fixing unit tests in graphql packages

---

packages/amplify-cli/package.json

Remove not functional test command from amplify core package

Remove ava from test in core amplify cli package

---

packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts
packages/graphql-connection-transformer/src/__tests__/ModelConnectionTransformer.test.ts

https://github.com/aws-amplify/amplify-cli/issues/24
Fixing #24 and creating the correct filter objects.

Fixing #24 where connection transformer doesn't make filters

---

packages/amplify-codegen/src/index.js
packages/amplify-provider-awscloudformation/lib/utility-functions.js

Fixes #50 
Updated codegen generate code to make sure that the configured API in .graphqlconfig.yml file indeed exist in the current amplify project

Fix(aws-amplify/amplify-cli) #50 Check if the API exists during codegen

---

packages/amplify-provider-awscloudformation/lib/configuration-manager.js
packages/amplify-provider-awscloudformation/lib/initializer.js

copy of #96 
amplify-cli does not seem to apply the profile name specified on init.
Looking at: packages/amplify-provider-awscloudformation/lib/{configuration-manager.js,initializer.js}
process.env.AWS_PROFILE is being set to the profile name.
However, the AWS library has already been loaded and AWS_PROFILE env variable will not be read again.
Need to explicitly reconfigure credentials.
see ref: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html

 Enforce profile name: set AWS.config.credentials - copy

---

packages/amplify-category-function/provider-utils/awscloudformation/cloudformation-templates/lambda-cloudformation-template.json.ejs

https://github.com/aws-amplify/amplify-cli/issues/110
Adding cloudwatch logs to standalone lambda functions - Right now it is adding only when the lambda function is backed up by a DDB table

Add cloudwatch policies to lambda functions

---

packages/amplify-provider-awscloudformation/lib/upload-appsync-files.js

Fixes -> https://github.com/aws-amplify/amplify-cli/issues/118
Fixes -> https://github.com/aws-amplify/amplify-cli/issues/113

Retain cognito user pool id after graphql schema update

---

packages/amplify-codegen/src/walkthrough/add.js

Fixes  #103
Amplify creates schema.graphql which has special directives that are meant
only for transformers and its stored in amplify directory. Code gen should ignore
this schema.graphql. Updated the codegen config to make amplify path explicit

Update exclude path to be more explicit

---

packages/amplify-provider-awscloudformation/lib/upload-appsync-files.js
packages/graphql-appsync-transformer/src/AppSyncTransformer.ts
packages/graphql-appsync-transformer/src/resources.ts

https://github.com/aws-amplify/amplify-cli/issues/99
https://github.com/aws-amplify/amplify-cli/issues/11
These changes stop the bleeding on issues https://github.com/aws-amplify/amplify-cli/issues/99 and https://github.com/aws-amplify/amplify-cli/issues/11. This reorganizes the transform so only 3 parameters are needed to configure the resolver s3 locations instead of (2 x the number of resolvers). This is still not a long-term fix and I suspect the next limit we hit will be the max of 200 resources per stack. I am also working on another solution that uses nested stacks but this will take a bit longer to finish.

Fixing 60 parameter limit error on graphql api create.

---

packages/amplify-category-api/commands/api/gql-compile.js
packages/amplify-provider-awscloudformation/lib/upload-appsync-files.js
packages/graphql-appsync-transformer/src/AppSyncTransformer.ts
packages/graphql-appsync-transformer/src/resources.ts
packages/graphql-auth-transformer/src/ModelAuthTransformer.ts

https://github.com/aws-amplify/amplify-cli/issues/55
@auth checks the resolver exists first before applying the auth rule correcting a bug.

Fixing #55. @auth checks the resolver exists first.

---

packages/graphql-elasticsearch-transformer/package.json

Issue #135 
Changes are made to the graphql-elasticsearch-transformer package.
- Added npm package bestzip
- Using bestzip instead of zip in packages.json

Fix zip command not found on Windows

---

packages/graphql-transformer-core/Readme.md

The documentation listed at [`packages/graphql-transformer-core/Readme.md`](https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-transformer-core/Readme.md) does not match the implementation at [`packages/graphql-auth-transformer/src/ModelAuthTransformer.ts`](https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-auth-transformer/src/ModelAuthTransformer.ts#L74-L86)
This pull request aims to bring this documentation up to date.

Fix Readme.md docs for the `@auth` directive

---

packages/amplify-codegen/src/commands/add.js
packages/amplify-codegen/src/commands/generateStatementsAndType.js
packages/amplify-codegen/src/commands/statements.js
packages/amplify-codegen/src/commands/types.js
packages/amplify-codegen/src/constants.js
packages/amplify-codegen/src/utils/downloadIntrospectionSchema.js
packages/amplify-codegen/src/utils/generateIntrospectionSchemaWithProgress.js
packages/amplify-codegen/src/utils/getAppSyncAPIInfo.js
packages/amplify-codegen/src/utils/getProjectAWSRegion.js
packages/amplify-codegen/src/utils/index.js
packages/amplify-codegen/src/walkthrough/changeAppSyncRegions.js
packages/amplify-codegen/src/walkthrough/questions/changeRegion.js
packages/amplify-codegen/src/walkthrough/questions/selectRegions.js
packages/amplify-codegen/tests/commands/add.test.js
packages/amplify-codegen/tests/commands/generateStatementsAndTypes.test.js
packages/amplify-codegen/tests/commands/statements.test.js
packages/amplify-codegen/tests/commands/types.test.js
packages/amplify-provider-awscloudformation/lib/utility-functions.js
packages/amplify-provider-awscloudformation/src/aws-utils/aws-appsync.js

amplify codegen add --apiId <api-id>` fails if you run this command in a project which is set to use `<region1 >` and the AppSync API is in <region2>`. 
Updated add command to detect this and prompt user to choose different region.

Add support to add cross region AppSync API to codegen

---

packages/amplify-codegen/src/callbacks/prePushUpdateCallback.js
packages/amplify-codegen/src/constants.js
packages/amplify-codegen/src/walkthrough/questions/updateDocs.js
packages/amplify-codegen/tests/callbacks/prePushUpdateCallback.test.js
packages/amplify-codegen/tests/walkthrough/questions/updateDocs.test.js

When user did an amplify api push, code gen workflow gets triggered. The workflow
updates/overwrites both GraphQL types and Statements. The workflow did not ask the right
question about updating statements and did not inform user that the files will be over written
Updated the workflow to show the right question and inform user about file over write

(packages/amplify-codegen) Update api push (update workflow) of codegen

---

packages/amplify-cli/src/lib/get-global-prefix.js

System Information:
Yarn:
```
yarn --version
1.9.4
```
OS:
```
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```
Installation:
yarn global - using `yarn global add @aws-amplify/cli`
Issue:
When i'm executing `amplify init` at step `s1-initFrontendHandler` i couln't find any fronted option
Output:
```
hostname :: _debug/react-native/vanillaapp % amplify init 
Note: It is recommended to run this command from the root of your app directory
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building (Use arrow keys)
```
Solution:
Turns out it was looking at  `~/.config/yarn/global` instead of `~/.config/yarn/global/_node_modules` ( where the frontend package lived ),
```
hostname :: …
```

Fix yarn global path

---

packages/amplify-cli/package.json

Issue #218 
As there are core functions used that depend on a minimum node version, we can indicate this in package.json so users who need to upgrade get a warning on install.

Indicate the minimum node version

---

graphql-transform-tutorial.md

In response to feature request #98 update the graphql-transform-tutorial.md docs to include note about adding `@searchable` to `@model` types that have existing data.

Update docs with note for @searchable and existing data

---

packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts
packages/graphql-versioned-transformer/src/VersionedModelTransformer.ts

While looking at how the `@connection` directive works, I noticed that there were a few types (namely: `QueryNameMap`, `MutationNameMap` and `ModelDirectiveArgs`) that were not used.
It looks as though these were possibly copied over from the `@model` directive when this was first created in commit https://github.com/aws-amplify/amplify-cli/commit/88e36f360258778b4684cd88a82fa1148cc8426b#diff-04ea72e1d9d6b9165d1777f19e9fed9aR22.
While removing those, I did a quick scan of the other `graphql-*` packages and found some imports in `VersionedModelTransformer` that also were not being used. I've removed those as well.
Thank you for the work you've done here!
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Remove stale types and imports

---

packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-transformers-e2e-tests/src/__tests__/DynamoDBModelTransformer.e2e.test.ts

This is related to [Issue #214](https://github.com/aws-amplify/amplify-cli/pull/214)
When a non-model type is referenced within multiple @model types, the transformer ran into issues.
For example, this test used to fail before:
```graphql
type Post @model {
id: ID!
title: String!
createdAt: AWSDateTime
updatedAt: AWSDateTime
metadata: PostMetadata
entityMetadata: EntityMetadata
appearsIn: [Episode!]
}
type Author @model {
id: ID!
name: String!
postMetadata: PostMetadata
entityMetadata: EntityMetadata
}
type EntityMetadata {
isActive: Boolean
}
type PostMetadata {
tags: Tag
}
type Tag {
published: Boolean
metadata: PostMetadata
}
enum Episode {
NEWHOPE
EMPIRE
JEDI
}
```
By submitting this pull request, I confirm that my contribution is …

Ensures we don't add multiple non-model input types

---

packages/amplify-graphql-docs-generator/src/generator/getFields.ts

Fixes #222
GraphQL statements generator by default resolves fields 3 level deep, it
counted a list as a level but we should diregard list as a level. Updated
code to disregard list as a level

Update statement generator to skip level for Lists

---

packages/amplify-category-api/provider-utils/awscloudformation/appsync-schemas/single-object-auth-schema.graphql
packages/graphql-appsync-transformer/src/AppSyncTransformer.ts
packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-dynamodb-transformer/src/resources.ts
packages/graphql-elasticsearch-transformer/src/SearchableModelTransformer.ts
packages/graphql-elasticsearch-transformer/src/resources.ts
packages/graphql-transformer-core/src/GraphQLTransform.ts
packages/graphql-transformer-core/src/TransformerContext.ts
packages/graphql-transformer-core/src/defaultSchema.ts
packages/graphql-transformer-core/src/validation.ts
packages/graphql-transformers-e2e-tests/src/__tests__/CustomRoots.test.ts

These changes allow users to provide their own Query, Mutation and Subscription root object types.
For example,
```graphql
type Post @model {
id: ID!
title: String
}
type Query {
customQuery: String
}
```
With this input, after compilation the root query type will be:
```graphql
type Query {
customQuery: String
getPost(id: ID!): Post
listPosts(...): PostConnection
}
```
You can also now turn off mutations/subscriptions entirely simply by leaving them out in your schema definition without having to update every @model or @searchable:
```graphql
schema {
query: Query
}
type Query {
customQuery: String
}
type Post @model { # NOTE: I do not have to set mutations: null to turn off mutations.
id: ID!
title: String!
}
```
You can also change the name of the root object …

Allow users to provide their own Query, Mutation, and Subscription root object types.

---

packages/amplify-cli/src/extensions/amplify-helpers/get-frontend-plugins.js
packages/amplify-provider-awscloudformation/lib/push-resources.js

Include update calls in the user agent metrics"
New format example:
'fu:c au:u ap:c '
In the above string, a new function is created,  an auth resource is updated and an API category is created as well/ Using the first two chars of the category as the category identifier.

Change user agent action string to include cfn update calls

---

.circleci/config.yml

Circle CI configuration was changed to use npm instead of yarn to package publishing. While changing one of the npm command was not converted to use `install` and this is failing integration tests

fix: Integration tests

---

packages/amplify-graphql-docs-generator/templates/_renderOp.hbs

Fixes #264
Statement generator generated invalid graphql statements when an operation had scalar type as return by adding an empty body around the statement. Updated code to conditionally add body.
If the graphql schema had an mutation
```graphql 
deletePodcast(input: DeletePodcastInput!): String
```
the statement generator used to generate
```graphql
mutation DeletePodcast($input: DeletePodcastInput!) {
deletePodcast(input: $input) {
}
}
``` 
which is not valid graphql. With this update the generated statement looks like
```graphql
mutation DeletePodcast($input: DeletePodcastInput!) {
deletePodcast(input: $input)
}
```

fix(amplify-graphql-docs-generator): Support scalar returns in statements

---

packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts
packages/graphql-connection-transformer/src/__tests__/ModelConnectionTransformer.test.ts
packages/graphql-transformer-common/src/definition.ts

https://github.com/aws-amplify/amplify-cli/issues/221
This PR fixes #221 and now respects nonNulls in @connection fields. This PR was rebased off https://github.com/aws-amplify/amplify-cli/pull/281 so we should get that PR merged first.

Fixing #221

---

packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/configure-CloudFront.js
packages/amplify-category-hosting/lib/S3AndCloudFront/index.js
packages/amplify-category-hosting/lib/S3AndCloudFront/template.json

This change makes the S3 bucket private when CloudFront is enabled for hosting. This allows Amplify to be used in environments where security policies do not allow public buckets to be created.

feat(amplify-category-hosting):Change prod hosting to use private S3 bucket

---

packages/graphql-auth-transformer/src/resources.ts

Saw in the CloudFormation template that the resource is a Cognito UserPool. The change is a small re-name of the resource's description.
I'm really liking this project 👍 Keep up the great work!

fix(graphql-auth-transformer): re-names user pool resource in description

---

packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js

By default, the GraphQL annotated schema gets compiled on each push and overrides any changes in the resolvers or cfn files. 
Added option/flag in amplify push command to not automatically re-compile annotated GraphQL schema and override the above-mentioned files.
Command -> `amplify push --no-gql-override`

Add option/flag in amplify push command to not automatically re-compile annotated GraphQL schema

---

packages/graphql-auth-transformer/src/AuthRule.ts
packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-auth-transformer/src/constants.ts
packages/graphql-auth-transformer/src/resources.ts
packages/graphql-dynamodb-transformer/src/resources.ts
packages/graphql-mapping-template/src/ast.ts
packages/graphql-mapping-template/src/print.ts
packages/graphql-transformer-common/src/ResourceConstants.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelAuthTransformer.e2e.test.ts

https://github.com/aws-amplify/amplify-cli/issues/183
This PR fixes #183 and totally revamps the logic for all @auth checks. This also adds extensive new e2e testing suites in addition to all the existing tests that were already in place. The resolver codegen is now much cleaner and more efficient + it works with much more complex rule combinations.
I have also added more docs to this PR https://github.com/aws-amplify/docs/pull/12 that explains the upgraded functionality.
For example, this is from the tests:
```graphql
type AllThree
@auth(rules: [
{allow: owner},
{allow: owner, ownerField: "editors"},
{allow: groups, groups: ["Admin"]},
{allow: groups, groups: ["Execs"]},
{allow: groups, groupsField: "groups"},
{allow: groups, …
```

Fixing #183

---

packages/amplify-category-analytics/provider-utils/awscloudformation/cloudformation-templates/pinpoint-cloudformation-template.json
packages/amplify-category-notifications/lib/auth-helper.js

Due to a recent change with Pinpoint API's, IAM policies need to be changed for the newly created Pinpoint API's. This PR modifies the IAM policies generated for a pinpoint endpoint using the CLI.

fix: update pinpoint IAM policy to use mobiletargeting instead of mobileanalytics

---

packages/graphql-connection-transformer/src/resources.ts
packages/graphql-transformer-common/src/util.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelConnectionTransformer.e2e.test.ts

#262 
This fixes an issue where if you create an object that has a connection without associating the object to another and then query it, an error is thrown from DynamoDB.
This puts a missing `$util.defaultIfNullOrBlank` check in the connection GetItem call as well as adds e2e tests to verify the fix.

Fixing 262

---

packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts
packages/graphql-connection-transformer/src/__tests__/ModelConnectionTransformer.test.ts
packages/graphql-connection-transformer/src/definitions.ts
packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts
packages/graphql-dynamodb-transformer/src/definitions.ts
packages/graphql-dynamodb-transformer/src/resources.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ConnectionsWithAuthTests.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/DynamoDBModelTransformer.e2e.test.ts

#352
#56 
#313
This change implements the simplest way to solve for a common complaint around providing a custom value for an `@model` types `id` field. This change removes a check that removed the `id` field from the `Create<Model>Input` input type. Now, instead, the `id` field remains in the `Create<Model>Input` input type but is always optional. The corresponding `create<Model>` resolver now has this `$util.defaultIfNullOrBlank($ctx.args.input.id, $util.autoId())` statement instead of `$util.autoId()`.
You can now do this:
```graphql
mutation Create {
createPost(input:{id:"1234", title:"post title"}) {
id
title
}
}
```
which returns:
```javascript
{
"data": {
"createPost": {
"id": "1234",
"title": "post title"
}
}
}
```
And can still …

This adds support to allow clients to provide their own ids for objects.

---

packages/amplify-graphql-docs-generator/__tests__/generator/getArgs.test.ts
packages/amplify-graphql-docs-generator/__tests__/generator/utils/isRequired.test.ts
packages/amplify-graphql-docs-generator/src/generator/getArgs.ts
packages/amplify-graphql-docs-generator/src/generator/utils/isList.ts
packages/amplify-graphql-docs-generator/src/generator/utils/isRequired.ts
packages/amplify-graphql-docs-generator/src/generator/utils/isRequiredList.ts
packages/amplify-graphql-docs-generator/templates/_renderArgDeclaration.hbs

statement generator did not honor the list types in input. It used to coerce a list into a non list
type and the check for non null type was a shallow check. Updated code to support list in input
types
fix #295

fix(amplify-graphql-docs-generator): support list types in input

---

packages/amplify-graphql-docs-generator/src/generator/types.ts
packages/amplify-graphql-docs-generator/src/generator/utils/isRequired.ts
packages/amplify-graphql-docs-generator/templates/_renderArgDeclaration.hbs

This is a tested fix for issues with the code-gen module so that it properly handles all four permutations of GraphQL LIST arguments, which are:
Nullable List Type: [] e.g. [String]
Nullable List of Non-null Types: [!] e.g . [String!]
Non-null List Type: []! e.g. [String]!
Non-null List of Non-null Types: [!]! e.g [String!]!

Fix codegen to handle all permutations of LIST args

---

package.json
packages/amplify-category-analytics/package.json
packages/amplify-category-api/package.json
packages/amplify-category-function/package.json
packages/amplify-category-notifications/package.json
packages/amplify-category-storage/package.json
packages/amplify-cli/package.json
packages/amplify-codegen/package.json

inquirer <5.0.0 is not functioning properly under windows, after first prompt the console hangs and 3.2.1 was used by various modules and the main cli too.
*Issue #355 
* Update package versions to 6.0.0 so it is the same now across the whole repo
* Update the setup-dev-win npm script to be in sync with the non-windows version.

Fix #355 - Consolidating inquirer package versions to ^6.0.0

---

packages/graphql-auth-transformer/src/constants.ts
packages/graphql-auth-transformer/src/resources.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelAuthTransformer.e2e.test.ts

N/A
When using Cognito access tokens, the key for the username in `$ctx.identity.claims` is **username** but when using id tokens, it is **cognito:username**. Now, it looks for **username** first as access tokens are recommended and then looks at **cognito:username** as a fallback.

Fixing bug with username vs cognito:username when using access token vs id token

---

packages/amplify-category-analytics/package.json
packages/amplify-category-api/package.json
packages/amplify-category-function/package.json
packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/configure-CloudFront.js
packages/amplify-category-hosting/lib/S3AndCloudFront/template.json
packages/amplify-category-notifications/package.json
packages/amplify-category-storage/package.json
packages/amplify-cli/package.json
packages/amplify-codegen/package.json

- fixed a typo in the hosting category
- changed hosting category's cloudfront's default cache behavior, Viewer Protocol Policy:  'allow-all' -> 'redirect-to-https' 
- unified the requirer packages' versions to "^6.0.0"

Hosting update / fix typo

---

.circleci/config.yml

The CI script used to use `product-build` script to bootstrap the package. This script hoisted the dependencies to the monorepo root. In the integration tests, we run `setup-dev` script to make sure `amplify` command is available globally. But when the `setup-dev` script is run, it causes a conflict in what packages to use for building typescript packages.
Updating the `build` script to use `setup-dev` to prevent the conflict.

CI: Use setup-dev script for build

---

.circleci/config.yml
packages/graphql-transformers-e2e-tests/package.json
packages/graphql-transformers-e2e-tests/tsconfig.json

- Reverting ci to use production build
- Adding skipLibCheck to ensure e2e test package builds

Ci publish fix

---

.circleci/api.sh
.circleci/auth.sh
.circleci/config.yml
.circleci/delete_api.sh
.circleci/delete_auth.sh

updated integration tests not to use the cache from build. Build uses lerna hoist and tests use non
hoisted build. Hoisting causes npm clashes and tests fail. Also updated the integration test
packages to be checkout outside the monorepo

ci: update integration test to build without cache

---

.circleci/config.yml
package.json

CircleCI publish of the packages use to fail due to missing ssh keys. This was caused because ci script was using the wrong key to restore the ssh cache. 
Also updated the post publish release hook to explicitly push master branch

CI: fix circle ci publish failures

---

packages/amplify-category-auth/commands/auth/update.js
packages/amplify-category-auth/index.js
packages/amplify-category-auth/package.json
packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/index.js
packages/amplify-category-auth/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js
packages/amplify-category-auth/tests/commands/enable.test.js
packages/amplify-category-auth/tests/commands/remove.test.js
packages/amplify-category-auth/tests/commands/update.test.js
packages/amplify-cli/src/cli.js
packages/amplify-cli/src/extensions/amplify-helpers/get-plugin-instance.js
packages/amplify-cli/src/extensions/amplify-helpers/remove-resource.js
packages/amplify-cli/src/extensions/amplify-helpers/stageResourceParams.js
packages/amplify-cli/src/extensions/amplify.js
packages/amplify-cli/src/lib/initialize-env.js
packages/amplify-provider-awscloudformation/index.js
packages/amplify-provider-awscloudformation/lib/push-resources.js
packages/amplify-provider-awscloudformation/src/resourceParams.js

Add auth support for multi env. Updated the cloud formation templates to create new instances of resources based on env name.
Another PR to follow adding support for env specific third party auth providers

feat(amplify-category-auth) add support for multi env 

---

packages/amplify-category-auth/index.js
packages/amplify-category-auth/provider-utils/awscloudformation/index.js

Auth can be added automatically by other categories like storage or interactions
as they are depenedent on auth. Updated auth add method to support multienv

feat(amplify-category-auth) support multienv for dependent services

---

packages/amplify-graphql-types-generator/src/angular/index.ts

- fix sort function to push nullable vars to end of array
- add comma in input generator (dangling comma removed by prettier)

fix nullable parameter order and command in gqlAPIServiceArguments

---

packages/amplify-provider-awscloudformation/lib/setup-new-user.js

`amplify configure` would during the creation of an IAM role not get the right region. It would try to fetch it from `answers` which only contains the username at that point.
Instead of fetching from `answers` it now fetches from the global `awsConfig`

fix(amplify-provider-awscloudformation): no region

---

packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js

Current Dynamo CFN's have a trailing comma (accepted by CFN),
but fails on JSON.parse(), hence removing it before a JSON.parse() call

fix: handle dirty JSON for dynamo CFN during migration

---

packages/amplify-provider-awscloudformation/lib/build-resources.js

AWS Cloudformation did not handle nested directories inside resource directory. The method that
generated a list of source file did not flatten the array of files inside nested directory. Updated
the code to flatten the files array
#404

fix(amplify-provider-awscloudformation): support nested resource dir

---

packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js

when user added NoSQL storage, the wizard failed to ask if the user wanted to add additional column after the first answer and chose default Yes. This change makes sure to ask every time a field is added
#528

fix(amplify-category-storage): confirm before adding column

---

packages/amplify-category-notifications/commands/notifications/remove.js
packages/amplify-category-notifications/lib/pinpoint-helper.js

the `amplify notificaitons remove` command prompts for what to remove, previously pinpoint project is always an option, this PR checks to see if a Pinpoint project exists, if not, it will just print out error message without prompt, because there's nothing to remove. 

feat: detect if Pinpoint project exists before prompt for remove command

---

packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js

when user added NoSQL storage, the wizard failed to ask if the user wanted to add additional column
after the first answer and chose default Yes. This change makes sure to ask every time a field is
added

fix(amplify-category-storage): confirm before adding column (#537)

---

packages/amplify-graphql-types-generator/src/cli.js
packages/amplify-graphql-types-generator/src/generate.ts
packages/amplify-graphql-types-generator/src/utilities/complextypes.ts

Types generator expected users to pass add-s3-wrapper param to CLI if they wanted to include the S3
Wrapper code when generating swift code. Changed the param to complex-object-support and accept
either yes, no or detect. When user passes detect, the types generator loops through the types used
and adds the S3 wrapper code if the types use S3 Object
#375

feat(amplify-graphql-types-generator): detect complex types

---

packages/amplify-provider-awscloudformation/lib/setup-new-user.js

AWS profile name can not contain empty chars at the begining or end. Trimming the profile name
before saving it to disk
#542

fix(amplify-provider-awscloudformation): trim profile name

---

packages/amplify-category-analytics/provider-utils/awscloudformation/service-walkthroughs/pinpoint-walkthrough.js
packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js
packages/amplify-category-function/provider-utils/awscloudformation/index.js
packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js
packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js
packages/amplify-cli/src/extensions/amplify-helpers/build-resources.js
packages/amplify-cli/src/extensions/amplify-helpers/confirm-prompt.js
packages/amplify-cli/src/extensions/amplify-helpers/delete-project.js
packages/amplify-cli/src/extensions/amplify-helpers/push-resources.js
packages/amplify-cli/src/extensions/amplify-helpers/remove-resource.js
packages/amplify-cli/src/extensions/amplify.js
packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js

prompt.confirm is unreliable and sometimes fails to take user input
create a confirm prompt helper that uses inquirer prompt instead
refactor helper defined in dynamoDb-walkthrough.js
https://github.com/aws-amplify/amplify-cli/issues/528

fix(cli): remove calls to gluegun's prompt.confirm

---

packages/amplify-graphql-docs-generator/__integration__/__snapshots__/e2e.test.ts.snap
packages/amplify-graphql-docs-generator/__tests__/generator/getFields.test.ts
packages/amplify-graphql-docs-generator/src/cli.ts
packages/amplify-graphql-docs-generator/src/generator/getFields.ts

docs generator did not decrease the depth for fields that were list or a non null type and it also
discounted them from depth calculation by calling getType. This caused over-fetching of data

fix(amplify-graphql-docs-generator): fix overfetching of lists (#571)

---

packages/graphql-dynamodb-transformer/src/resources.ts
packages/graphql-elasticsearch-transformer/src/resources.ts

#591
This change fixes a bug with how the transformed template's dependsOn statements are configured. Previously the code was trying to chain `dependsOn()` from the `cloudform` library when it was really supposed to be passed a list.

Fixing #591

---

packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.js

When removing a category completely, say all of the lambda functions, from a project, it becomes impossible to successfully push the changes due to an error.
`Cannot read property 'lambdaFunctionName' of undefined`

Fix null dereference when a category is removed

---

packages/amplify-category-storage/provider-utils/awscloudformation/cloudformation-templates/s3-cloudformation-template.json

https://github.com/aws-amplify/amplify-js/issues/61
to enable s3 multipart (and files larger than 5MB), ETag is added to the CORS configuration for the bucket

feat(amplify-category-storage): add s3 multipart upload to cfn

---

packages/amplify-provider-awscloudformation/lib/upload-appsync-files.js

and then those `@model` directives are removed, a file not found
error is thrown and the stack is unable to be deployed.
*Issue #, if available:* N/A
*Description of changes:* Checked for existence of `resolvers` folder when calling uploadAppSyncFiles.

Fix issue where if a GraphQL API is deployed with `@model`

---

packages/amplify-frontend-javascript/lib/framework-config-mapping.js

Fixes https://github.com/aws-amplify/amplify-cli/issues/562
Adds Ember to the list of frontend frameworks when running `amplify init`. I have tested this locally and it does successfully create a fully working project 👍 

feat(amplify-frontend-javascript): adding Ember config for amplify-cli

---

packages/amplify-provider-awscloudformation/lib/system-config-manager.js
packages/amplify-provider-awscloudformation/src/aws-utils/user-agent.js

#709 
#719
Allows the user to directly manage the session of a temp credential until a more comprehensive solution is found.
The possible temp credentials expiration during an amplify push can happen, but the user should be able to push again after updating the credentials.

 fix(amplify-provider-awscloudformation): add session token

---

packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js

Cloud formation provider polls cloud formation to get the list of events to show when pushing the
stack. When a project has more than 20 resources, this causes throtlling. Fixing this issue by
batching the polling and retrying
#705

fix(amplify-provider-awscloudformation): batch cfn status polling

---

packages/amplify-codegen/src/commands/types.js
packages/amplify-graphql-docs-generator/src/index.ts

Prettier has deprecated use of babylon parser to parse JS files. Updating the config to user babel
Hide the types generated status message if there is no types to be generated. This happens when the output type is either JS or graphql.

Update codegen to hide warnings

---

packages/amplify-codegen/commands/codegen/add.js
packages/amplify-codegen/src/constants.js
packages/amplify-codegen/src/utils/input-params-manager.js
packages/amplify-codegen/src/walkthrough/add.js

Codegen external api add failed due to a missing null check and failed with error "Cannot convert
undefined or null to object". Fixing this error.
Added parameter validation logic to codegen add
#726

    fix(amplify-codegen): fix codegen external add error

---

.circleci/config.yml
packages/graphql-transformers-e2e-tests/src/CloudFormationClient.ts

GraphQL Transformer has e2e test which does not run in
multienv branch. Updating configuration to run the
test in multienv branch and updating e2e tests
to include the env name in the CFN document

ci: run e2e test in multienv branch

---

packages/amplify-provider-awscloudformation/lib/delete-env.js

After adding MFA support, the arity of getProfiledAwsConfig changed. Updating delete to command to use the same arity

fix(amplify-provider-awscloudformation): fix amplify delete error

---

packages/amplify-provider-awscloudformation/lib/delete-env.js

Amplify project can be initialized with access key and secrete key (without profile). When a project
is configured without profile and user does not have default profile, running amplify delete of the
project threw Missing region in config error. This update fixes it by using default configuration
loader

fix(amplify-provider-awscloudformation): delete project without profile

---

packages/amplify-category-interactions/provider-utils/awscloudformation/cloudformation-templates/lex-cloudformation-template.json.ejs
packages/amplify-category-interactions/provider-utils/awscloudformation/function-template-dir/index.js.ejs

#790
Fix:
Added checking and creation of Lex service role which is required for the clients to access the CLI created lex bots.

(multienv)Lex bot fix: Issue #790

---

packages/amplify-category-interactions/provider-utils/awscloudformation/cloudformation-templates/lex-cloudformation-template.json.ejs
packages/amplify-category-interactions/provider-utils/awscloudformation/function-template-dir/index.js.ejs

#790
Fix:
Added checking and creation of Lex service role which is required for the clients to access the CLI created lex bots.

(master)Lex bot fix: Issue #790

---

CONTRIBUTING.md

Updated CONTRIBUTING.md to include details about conventional commit and command that can be used to generate conventional commit messages

docs: Update CONTRIBUTING.md (#804)

---

package.json
packages/amplify-graphql-docs-generator/package.json
packages/amplify-graphql-types-generator/package.json
packages/graphql-appsync-transformer/package.json
packages/graphql-auth-transformer/package.json
packages/graphql-connection-transformer/package.json
packages/graphql-dynamodb-transformer/package.json
packages/graphql-elasticsearch-transformer/package.json
packages/graphql-http-transformer/package.json
packages/graphql-mapping-template/package.json
packages/graphql-transformer-common/package.json
packages/graphql-transformer-core/package.json
packages/graphql-transformers-e2e-tests/package.json
packages/graphql-versioned-transformer/package.json

Pinned the version of @types/jest to ensure that it works with typescript v2.x.x

build: pin the version of @types/jest

---

packages/amplify-codegen/commands/codegen/codegen.js
packages/amplify-codegen/commands/codegen/statements.js
packages/amplify-codegen/src/commands/add.js
packages/amplify-codegen/src/commands/generateStatementsAndType.js
packages/amplify-codegen/src/commands/statements.js
packages/amplify-codegen/src/constants.js
packages/amplify-codegen/src/walkthrough/add.js
packages/amplify-codegen/src/walkthrough/configure.js
packages/amplify-codegen/src/walkthrough/questions/maxDepth.js
packages/amplify-codegen/tests/commands/generateStatementsAndTypes.test.js
packages/amplify-codegen/tests/walkthrough/add.test.js
packages/amplify-codegen/tests/walkthrough/configure.test.js

codegen had hardcode max depth of 2 for the statement generation. Exposed a new configuration and
flag (--max-depth) to configure the maximum level that an object needs to expand when generating statements
re #715 #745 #638 #775

feat(amplify-codegen): add support for max-depth for statements

---

packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts
packages/graphql-dynamodb-transformer/package.json
packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-dynamodb-transformer/src/definitions.ts
packages/graphql-transformer-common/src/ModelResourceIDs.ts
packages/graphql-transformers-e2e-tests/package.json
packages/graphql-transformers-e2e-tests/src/__tests__/DynamoDBModelTransformer.e2e.test.ts

Enum fileds were not included in the filters generated for quries. Updated the transformer to
include filters for enum types
closes #712

feat(graphql-dynamodb-transformer): support filter enums in query

---

packages/amplify-graphql-types-generator/src/swift/codeGeneration.ts
packages/amplify-graphql-types-generator/test/swift/__snapshots__/codeGeneration.ts.snap

Swift codegen did not handle underscores field names. The generated code used undescore name for map
but getters/setters used camelCase name similar to the name of the property. Udated code to use
underscore name for gettters and setters
fix #643

fix(amplify-graphql-types-generator): underscore support in swift

---

packages/amplify-provider-awscloudformation/lib/initialize-env.js

fix: copy providerMetadata to amplify-meta during env init

---

packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts

DyanmoDBTransformer generates filter input type if and only if queries are enbled for a type. This used to work fine
when transformer did not support enum filters. ID, String, Int, Float are not unique to a schema and are generated all the time. With EnumFilter if the Type does not have queries enabled, these filter input types never gets generated  but they may gets referenced in connections queries. Updated code to generate Filters even when queries are disabled.
fixes #865

fix(graphql-dynamodb-transformer): generate filters for connection

---

packages/amplify-cli/src/commands/env.js

Fix typo in the word overwrite displayed after hitting `amplify env`.

fix: typo on `amplify env` help text

---

.circleci/config.yml

Reverts aws-amplify/amplify-cli#929
Tokens not allowed to publish

Revert "ci: use team account's NPM_TOKEN"

---

packages/amplify-graphql-docs-generator/__integration__/__snapshots__/e2e.test.ts.snap
packages/amplify-graphql-docs-generator/src/generator/getFields.ts

statement generation skipped enum type when traversing fields and when the depth reached 0. It
treated enums similar to that of a field which has subfield. Updating code to treat enums like a
scalar.
fix #623

fix(amplify-graphql-docs-generator): render enums like scalar fields

---

packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts

#939
This no longer generated mutation inputs when mutations are disabled. It also adds a check to make sure the transform does not override any user created inputs that may have the same name as the auto-generated inputs.

Fixing #939

---

packages/amplify-codegen/src/commands/generateStatementsAndType.js
packages/amplify-codegen/src/commands/statements.js
packages/amplify-codegen/src/commands/types.js
packages/amplify-codegen/tests/commands/generateStatementsAndTypes.test.js
packages/amplify-codegen/tests/commands/statements.test.js
packages/amplify-codegen/tests/commands/types.test.js

Updated codegen to generate statements and types to be written to files relative to project root
instead of current working directory
fixes #886

fix(amplify-codegen): use path relative to project root for codegen

---

packages/amplify-provider-awscloudformation/lib/push-resources.js
packages/graphql-transformer-core/src/util/amplifyUtils.ts

When generating files during a push, amplify-cli is iterating through various directories in ```amplify```. It currently lists all files. If you have something open in your editor which generates a temp file e.g. .filename.swp amplify tries to run cfn-lint on it as well and you get an error.
This commit ignores all files starting with a ```.```

fix: ignore file starting with a dot when compiling configs

---

packages/amplify-cli/src/extensions/amplify-helpers/push-resources.js
packages/amplify-cli/src/extensions/amplify-helpers/resource-status.js
packages/amplify-provider-awscloudformation/lib/build-resources.js
packages/amplify-provider-awscloudformation/lib/push-resources.js

Make push performant by
1. Deleting older function builds which were retained in the dist folder of function category.
With this change only the latest build package is maintained
2. Excluding build/dist/node_modules from getting included in the current-cloud snapshot. This decreases the size of the snapshot substantially (when functions are included in the project) and decreases the upload time
3. Bail quickly if there are no resources to be update
closes #914

perf: speed up push

---

packages/amplify-graphql-types-generator/src/angular/index.ts
packages/amplify-graphql-types-generator/test/angular/__snapshots__/index.js.snap

Angular service produced string as the __typename for top-level operations and actual string literal
of type for all the sub object in the response. This change ensures that all the __typesname use
String literal of GraphQL type
fix #953 

fix(amplify-graphql-types-generator): generate consistent __typename

---

packages/amplify-cli/src/lib/global-prefix.js

Global Plugins were not found under windows because the default path for node_modules is not inside a lib folder.
I have added an OS check. If on windows, it returns the correct path (without lib subdirectory).

fix(cli): added global windows npm path to plugin import

---

packages/graphql-connection-transformer/src/resources.ts

To my [reading](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-secondary-indexes), GSI limit is 20, not 5 — also, this works for adding more indicies when changed thusly.

Increase GSI limit from 5 to 20, per the DynamoDB Docs

---

packages/amplify-cli/src/extensions/amplify-helpers/on-category-outputs-change.js

*Issue #, if available:* #748 
*Description of changes:* Adds functionality for callbacks to be implemented by any plugin that amplify supports (both 3rd party and 1st party plugins can be supported with this). This just builds on top of the callback for frontend development and adds support for the categories.

Returnhook

---

packages/graphql-dynamodb-transformer/src/resources.ts
packages/graphql-transformer-common/src/ResourceConstants.ts
packages/graphql-transformers-e2e-tests/src/__tests__/DynamoDBModelTransformer.e2e.test.ts

Adds an option to turn on point in time recovery for DyanmoDB.

feat(graphql-dynamodb-transformer): add DyanmoDB point in time recovery

---

packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.js

* fix(cli): Allow update value to be other types other then dictionary or an array.
*Issue #, if available:* N/A . Just adding what was lost on the env push.
*Description of changes:* Same thing as #650 

fix(cli): allow update value to be other types

---

packages/amplify-provider-awscloudformation/lib/initializer.js
packages/amplify-provider-awscloudformation/lib/push-resources.js
packages/amplify-provider-awscloudformation/src/utils/archiver.js

Current cloud backend included Lambda functions node_modules. This can cause errors when checking
out an env where node_modules has reference to local node_package. By skipping node_modules folder
the size of current_cloud_backend.zip file size reduces and also fixes the error when referencing
local packages
fixes #1077

fix:skip inclusion node_modules form current_cloud_backend.zip

---

packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts

Provide connection name when throwing an error for a ManyToMany connection type being unsupported
*Issue #, if available:* N/A
*Description of changes:* Change to an error message text to provide more useful feedback to developers

Improve error message for ManyToMany within GQL Compile

---

packages/amplify-cli/src/extensions/amplify-helpers/get-resource-outputs.js
packages/amplify-cli/src/extensions/amplify-helpers/on-category-outputs-change.js
packages/amplify-cli/src/extensions/amplify-helpers/push-resources.js
packages/amplify-cli/src/lib/config-steps/c1-configFrontend.js
packages/amplify-cli/src/lib/config-steps/c9-onSuccess.js
packages/amplify-frontend-android/index.js
packages/amplify-frontend-android/lib/frontend-config-creator.js
packages/amplify-frontend-ios/index.js
packages/amplify-frontend-ios/lib/frontend-config-creator.js
packages/amplify-frontend-javascript/index.js
packages/amplify-frontend-javascript/lib/frontend-config-creator.js

re #419
#419
Previously, the CLI didn't respect user provided custom keys as a part of the awsconfiguration.json and aws_exports.js files (it used to overwrite the custom contents after an 'amplify push'). This PR, allows users t0 provide custom config keys for aws_exports.js (for javascript projects) and awsconfiguration.json(for native projects) which the CLI won't blow up on a push.

feat: allow custom frontend configs

---

packages/amplify-category-xr/lib/xr-manager.js

- Allow absolute path for scene configuration to override no fuzzy match results
- Improve file path error messaging

fix: allow absolute path for scene config

---

package.json

- Run lint during pre-push to eliminate CI lint failure

build: run lint during pre-push

---

packages/graphql-auth-transformer/src/resources.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelAuthTransformer.e2e.test.ts

Transformer added group auth expression even when the auth had an empty group. This caused DynamoDB to error. Adding auth expression only if there is a group specified.
fixes #360 
Adds a missing check in generated update & delete resolver to fix an issue caused when the logged in user is not enrolled in any Cognito User Pools groups.

fix(graphql-auth-transformer): conditional group expression

---

package.json

build: avoid removing package-lock files in production-build command

---

packages/amplify-provider-awscloudformation/lib/push-resources.js

*Issue #, if available:* #1135
*Description of changes:* Ignores vim .swp files, or any other files starting with . when pushing to cloudformation

fix(amplify-provider-awscloudformation): ignore dot files, fixes #1135

---

Readme.md

The README doesn’t mention multi-env. This is a start by referencing the `amplify env …` commands in the commands list.

Add `amplify env …` info to README

---

packages/amplify-provider-awscloudformation/lib/aws-regions.js

Since Amplify console in ap-northeast-2 was opened but not CLI.
Reference: https://aws.amazon.com/about-aws/whats-new/2019/04/amplify-console-now-available-in-five-additional-regions

feat: add support for ap-northeast-2

---

packages/graphql-relational-schema-transformer/src/AuroraServerlessMySQLDatabaseReader.ts
packages/graphql-relational-schema-transformer/src/RelationalDBSchemaTransformer.ts
packages/graphql-relational-schema-transformer/src/__tests__/AuroraServerlessMySQLDBReader.test.ts

Two fixes that I found in the new RDS tool.
1. Disabling broken connection fields inferred from foreign keys. There was no support at the resolver level any way and this was breaking tables with foreign keys.
2. Disabling importing tables with no explicit primary keys. This was breaking. The tool now warns that it is skipping a table.

fix(graphql-relational-schema-transformer fixes) fix rds import issues

---

packages/amplify-cli/src/extensions/amplify-helpers/read-json-file.js
packages/amplify-cli/src/extensions/amplify.js
packages/amplify-frontend-android/lib/frontend-config-creator.js

fix #1280
Certain text editors insert a BOM character in front of the file contents, and JSON.parse(.) can not handle it, JSON.parse(.) throws "SyntaxError: Unexpected token ﻿ in JSON at position 0" when the argument string contains the BOM character. This was logged as a [node issue](https://github.com/nodejs/node/issues/20649)
This PR adds an utility method `readJsonFile` in the amplify extension to read json files, and it has built in logic to handle the BOM character. 
In this PR, the`readJsonFile` utility method is only used in the amplify-frontend-android's frontend-config-creator to fix issue #1280, its usage should be extended to other places where JSON.parse(fs.readFileSync(.)) is directly used. 
By submitting this pull request, …

fix(cli): check BOM in json read

---

packages/amplify-category-xr/lib/xr-manager.js

- Use JSON parse instead of require to prevent file path inconsistencies

fix: use JSON parse instead of require in xr

---

packages/amplify-category-api/commands/api/add-datasource.js
packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-walkthrough.js
packages/graphql-relational-schema-transformer/src/AuroraDataAPIClient.ts
packages/graphql-relational-schema-transformer/src/AuroraServerlessMySQLDatabaseReader.ts
packages/graphql-relational-schema-transformer/src/__tests__/AuroraDataAPIClient.test.ts
packages/graphql-relational-schema-transformer/src/__tests__/AuroraServerlessMySQLDBReader.test.ts

- RDS import plugin did not use the configured AWS credentials form the Amplify Project. Updated to use the configured profile
- RDS import plugin showed only 10 secrets. Added fetching all the results 
closes: #1314 and #1315

fix(amplify-category-api):add-graphql-datasource use selected profile

---

packages/amplify-provider-awscloudformation/lib/initializer.js

Adding env name to stack name and bucket to easily distinguish them
closes #1340

feat(amplify-provider-awscloudformation): append env name

---

packages/amplify-codegen/src/callbacks/postPushCallback.js
packages/amplify-codegen/src/codegen-config/AmplifyCodeGenConfig.js
packages/amplify-codegen/src/commands/add.js
packages/amplify-codegen/src/commands/generateStatementsAndType.js
packages/amplify-codegen/src/commands/statements.js
packages/amplify-codegen/src/commands/types.js
packages/amplify-codegen/tests/callbacks/postPushCallback.test.js
packages/amplify-codegen/tests/commands/add.test.js
packages/amplify-codegen/tests/commands/generateStatementsAndTypes.test.js
packages/amplify-codegen/tests/commands/statements.test.js
packages/amplify-codegen/tests/commands/types.test.js

Amplify codegen relied graphql config file to figure out the AppSync API ID to download the
introspection schema. With the introduction of multienv, the API ID changes based on the current
environment. Updated codegen to use the API ID from amplify meta to make codegen multienv aware
fix #1243

fix(amplify-codegen): make codegen multienv aware

---

packages/graphql-http-transformer/src/HttpTransformer.ts
packages/graphql-http-transformer/src/__tests__/HttpTransformer.test.ts
packages/graphql-http-transformer/src/resources.ts

Adds support for http headers for the @http directive.
Usage:
```
type Comment {
id: ID!
content: String @http(
url: "https://www.api.com/ping", 
headers: [
{
key: "X-Header", 
value: "X-Header-Value"
}
]
)
}
```

Adds http headers for @http directive

---

packages/amplify-provider-awscloudformation/lib/push-resources.js
packages/amplify-provider-awscloudformation/lib/upload-appsync-files.js

Fixes a bug related to pushing on CI/CD platforms. This change causes every push invocation to
update the S3DeploymentRootKey using a fixed hash function. This is in response to #1342. After
updating to this new version of the CLI, you will need to run `amplify push` one time with changes
to the api category and then every subsequent CI/CD push should succeed regardless of if you are
updating the api category or not.
re #1342

fix(1342): Fixes a bug related to pushing on CI/CD platforms.

---

packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js

Added support to color code the Cloudformation output. ERROR status will be red and SUCCESS status will be green
re: #1389

feat(amplify-provider-awscloudformation):color code cfn output

---

packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts
packages/graphql-connection-transformer/src/__tests__/ModelConnectionTransformer.test.ts
packages/graphql-connection-transformer/src/resources.ts
packages/graphql-dynamodb-transformer/src/definitions.ts
packages/graphql-mapping-template/src/dynamodb.ts
packages/graphql-transformer-common/src/ModelResourceIDs.ts
packages/graphql-transformer-common/src/definition.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelConnectionTransformer.e2e.test.ts

Implements work item one from #1062
Solves #1242
Adds support for key condition input objects on @connection types.
Quoted from the RFC:
There is currently no support for passing sort key conditions to query operations created by the @connection directive. Key conditions offer a different set of operator than filter expressions so we are unable to reuse the `ModelXFilterInput` types that are currently generated. Read more about key conditions in the Amazon DynamoDB docs https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.KeyConditions.html.
Given a schema:
```graphql
type Post @model {
id: ID!
name: String!
comments: [Comment] @connection(name: "PostComments", keyField: "postId", sortField: …
```

Adding support for KeyConditionInput types

---

packages/amplify-category-storage/provider-utils/awscloudformation/index.js
packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js

The arity of migrate method on DDB and S3 were not the same and caused issues when migrating DynamoDB resources. This fixes the arity by passing context as the first argument of migrate method DynamoDB category
fix #1384 
See commit message above.

fix(amplify-category-storage): pass context to DDB migration helper

---

packages/graphql-http-transformer/src/HttpTransformer.ts
packages/graphql-http-transformer/src/__tests__/HttpTransformer.test.ts
packages/graphql-http-transformer/src/resources.ts

Adds support to ${env} on the hostname and URI
It is also fixing one regex which was removing 'www' from the URLs
Usage:
```
type Comment {
id: ID!
content: String @http(url: "https://${env}.api.com/ping-${env}")
}
```

Add multi env on @http

---

packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-dynamodb-transformer/src/resources.ts

fix #982 
fix #1030 
fix #1141 
By **always** exporting the **DataSource** name output, it prevents `amplify push` to fails if a **@connection** directive or a model with a **@connection** is removed.

fix(graphql-dynamodb-transformer): always output datasource name

---

packages/amplify-provider-awscloudformation/src/aws-utils/aws.js

aws.configureWithCreds trys to load aws config and when the configuration is general configuration,
it returns null. Conditionally setting the credentials iff user has project specific config
fix #1424

fix(amplify-provider-awscloudformation): check creds before setting

---

packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-dynamodb-transformer/src/resources.ts
packages/graphql-elasticsearch-transformer/src/resources.ts
packages/graphql-transformer-common/src/ModelResourceIDs.ts

solve #987 and fix #980
Modify the **graphql-dynamodb-transformer** to **always** output and export the DynamoDB table `StreamArn`. It will prevent that removing the **@searchable** directive from a model makes the `amplify push` fails.

feat(graphql-dynamodb-transformer): always output stream arn

---

packages/amplify-category-auth/provider-utils/awscloudformation/assets/cognito-defaults.js

Updated the default password policy used in Cognito userpool to follow nist password guideline[1]
[1] - https://pages.nist.gov/800-63-3/sp800-63b.html#appA
re #1375

feat(amplify-category-auth):update default password policy

---

packages/amplify-category-auth/provider-utils/awscloudformation/assets/cognito-defaults.js

In pr #1199 the name of coginto userpool was changed to include the project name and a random
number. We use the this to name to the resource and - char is not supported in resource name.
Updated the resource name not to include -. Updated the policyname to use substring of resource name
as there is a limit of 65 chars in policy name

fix(amplify-category-auth): add policy name char length limit

---

packages/amplify-codegen/src/commands/types.js
packages/amplify-codegen/tests/commands/types.test.js

Codegen has capabilites to detect if an S3 object is used in AppSync looking at the schema and
document. This feature was added to types generator but was not switched on in codege. Updated the
code to turn the autodetection on
fix #1468

fix(amplify-codegen): auto detect S3Object in swift codegen

---

packages/amplify-graphql-types-generator/src/flow/types.js
packages/amplify-graphql-types-generator/src/typescript/types.ts

AWSTimestamp is serialized to number type. Updating codegen to use number type instead of string
fix #1348

fix(amplify-graphql-types-generator): set AWSTimestamp to number type

---

packages/graphql-transformers-e2e-tests/src/__tests__/NoneEnvFunctionTransformer.e2e.test.ts

Make the policy name unique for both NoneEnvFunctionTransformer test and FunctionTransformerTests as these can run concurrently and cause name collisions and cause CFN to fail

test(graphql-transformers-e2e-tests): fix policy name

---

packages/graphql-relational-schema-transformer/package.json
packages/graphql-relational-schema-transformer/src/RelationalDBResolverGenerator.ts
packages/graphql-relational-schema-transformer/src/RelationalDBSchemaTransformer.ts
packages/graphql-relational-schema-transformer/src/__tests__/RelationalDBResolverGenerator.test.ts
packages/graphql-relational-schema-transformer/src/__tests__/RelationalDBTemplateGenerator.test.ts

Adding a RDS table with underscore using graphql-relational-schema-transformer caused error in
cloudformation due to the way resources were named. This change strips non supported chars from
generated resource names
fix #1504

fix(graphql-relational-schema-transformer): support _ in table name

---

packages/amplify-category-auth/provider-utils/supported-services.json

Increased the range from 365 to 3650 to match the constraints defined by Cognito
fix #1385
#1385
Change Cognito Token Value from 365 to 3650.

fix(amplify-category-auth): match cognito token expiration date range

---

packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformer.e2e.test.ts

- Adding back the afterAll hook in KeyTransformer.e2e.tests
- Removing unnecessary console log.

fix(graphql-key-transformer)

---

packages/amplify-provider-awscloudformation/lib/push-resources.js

*Issue #1586
Filter files in dir in respect to file extension

fix(amplify-provider-awscloudformation): filter by template extensions

---

packages/amplify-cli/src/commands/env.js
packages/amplify-cli/src/commands/env/get.js
packages/amplify-cli/src/commands/env/list.js

Issue: #1616 
- Use `print.fancy` for console output when `--json` is specified
- For `env get` when a non-existent environment name is specified, output a JSON object to make it processable by `jq` and other tools.
Example output:
```
{
"error": "No environment found with name: 'myenv'"
}
```

fix(amplify-cli): remove console coloring from env get and list commands when --json is specified

---

packages/amplify-category-analytics/provider-utils/awscloudformation/service-walkthroughs/pinpoint-walkthrough.js
packages/amplify-category-notifications/index.js
packages/amplify-category-notifications/lib/multi-env-manager.js
packages/amplify-category-notifications/lib/pinpoint-helper.js

remove env name from the resource name in the notification category
in both the amplify-meta.json file and the backend-config.json file
projects configured by the previous versions will be automatically handled without customers' efforts. 
fix #1372

fix(amplify-category-notifications): remove env name

---

packages/amplify-cli/package.json
packages/amplify-cli/src/cli.js
packages/amplify-frontend-javascript/lib/frontend-config-creator.js
yarn.lock

Amplify CLI generates the the export file which uses es6 exports. When the config files are updated,
we try to read the value from aws-export to keep the custom setting in aws-export.js. Adding support
for es6 import/export makes it easier to get read the settings
fixes #1623

fix(cli): support es6 import/export

---

packages/amplify-codegen/src/commands/types.js
packages/amplify-codegen/tests/commands/types.test.js

Add checks before running types generator. If the codegen config doesn't require generation of types
bail before doing any other operation
partial fix #1585

refactor(amplify-codegen): skip types gen early

---

packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformerLocal.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/testUtil.ts

bug fix for 1587 which should now allow list type members for create and update inputs
fix #1587
#1587 
- Changed the KeyTransformer Create/Update Input Functions to return the Input Value Definition as is if it is not a keyfield.
- Added Unit & E2E Tests to test this change.

fix(graphql-key-transformer): 1587 bug fix

---

packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.js

updateamplifyMetaAfterResourceAdd expected an object to be passed but not all the categories pass
them. Setting default value
fix #1621 

fix(cli): add default value for options in updateAmplifyMeta

---

packages/amplify-category-interactions/commands/interactions/add.js
packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.js
packages/amplify-e2e-tests/__tests__/interactions.test.ts
packages/amplify-e2e-tests/src/categories/interactions.ts
packages/amplify-e2e-tests/src/utils/index.ts
packages/amplify-e2e-tests/src/utils/sdk-calls.ts

When adding interaction category, updateMateAfterAdd got called multiple times and if a resource
already exists with the name, no data is added to amplify-meta. Update interaction category to call
the method only once. Update the updateMetaAfterAdd to throw error when called multiple times for
the same resource. Also added integration test to ensure interaction add works
fix #1621

fix(amplify-category-interactions): call updateMetaAfterAdd only once

---

packages/amplify-provider-awscloudformation/lib/setup-new-user.js

Amplify CLI tries to open AWS Console links when adding new user. In some windows system, opening
browser fail and cause the CLI to terminate abruptly. Handling failure gracefully

fix(amplify-provider-awscloudformation): prevent abrupt closing of CLI

---

packages/amplify-category-function/provider-utils/awscloudformation/index.js

*Issue Number:* #1663 
*Description of changes:* Changed the openEditor method to read the function's package.json and open the function's entry point automatically.

fix(amplify-category-function): fixed openEditor

---

packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-transformer-common/src/dynamodbUtils.ts
packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformer.e2e.test.ts

Fixing #1572 
- Add capability to resolve a given type from context when the base type is non-scalar, which is true for enums. If a type could not be resolved with this fix a customer friendly error message is shown.
- Enhance the error message for keys with no name, when a non-existant field is specified in `@key` directive. Instead of `undefined` the error message show `<unnamed>` for `@key` name.

fix(graphql-key-transformer): Fix type resolve for 2 field @key when second field is an Enum

---

packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js

N/A
This was annoying me. So hopefully this is the only place the fix is needed. When going through the walkthrough it asks for a name for the GSI but then it doesn't use that name. This *should* fix that

fix CF Template for DynamoDB GSI name

---

packages/amplify-provider-awscloudformation/lib/build-resources.js

Amplify CLI used to use date to ensure that the functions S3 key was changing every time it got
pushed to the cloud. This caused multi env with multi branch workflow to have git merge conflict as
these keys kept changing based on the time when the function gets pushed. Updated the code to use the
folder hash of function so the key is consistent if the content has not changed
fix #1666

fix(amplify-provider-awscloudformation): generate consistent S3 keys

---

packages/amplify-provider-awscloudformation/lib/build-resources.js

Functions need files to uopload the file to s3 to support deployment. Recently the name of the build file was changed from timestamp to hash, which can include / character. Updated the file name to use hex value so there are no / in the name

feat(amplify-provider-awscloudformation): update fn build file name

---

packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformer.e2e.test.ts

KeyTransformer E2E tests were leaving some data behind that caused test suite run failure, but individual tests were ok, it is fixed by deleting the conflicting data.

Fix KeyTransformer E2E tests

---

packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts
packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-elasticsearch-transformer/src/SearchableModelTransformer.ts
packages/graphql-function-transformer/src/FunctionTransformer.ts
packages/graphql-http-transformer/src/HttpTransformer.ts
packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-transformer-core/src/DeploymentResources.ts
packages/graphql-transformer-core/src/GraphQLTransform.ts
packages/graphql-transformer-core/src/TransformFormatter.ts
packages/graphql-transformer-core/src/TransformerContext.ts
packages/graphql-transformer-core/src/__tests__/TransformFormatter.test.ts
packages/graphql-transformer-core/src/index.ts
packages/graphql-transformer-core/src/util/amplifyUtils.ts
packages/graphql-transformer-core/src/util/splitStack.ts
packages/graphql-transformer-core/src/util/transformConfig.ts
packages/graphql-transformers-e2e-tests/src/__tests__/TestComplexStackMappingsLocal.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/testUtil.ts

*Issues*
#1581
#1652 - This behavior pattern is now fixed. If you have previously deployed an API with this issue, the new utility method updates `transform.conf.json` such that any subsequent pushes with the fixed implementation do not try to move existing resources out of their existing stacks.
Fixing an issue with an internal mechanism called the stack mapping. The issue materialized when you tried to create an API with types that share name parts (e.g. Post & UserPost & User). When using names that share parts, the order of the types in the input document could impact which stack a resource got mapped to. This fix removes using regular expressions and replaces the stack map with a full mapping where each resource is explicitly mapped to a stack.
*Testing:* …

fix(graphql-transformer-core) - Fixing stack mapping.

---

packages/graphql-transformer-core/src/util/amplifyUtils.ts

N/A. This fixes a bug that has not been released.
Adds a missing null check to a new function that compares the current deployment against the last deployment in the current cloud backend.

fix(graphql-transformer-core) Adds a missing null check for the current cloud backend.

---

packages/amplify-provider-awscloudformation/lib/initializer.js
packages/amplify-provider-awscloudformation/lib/push-resources.js
packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js
packages/graphql-transformers-e2e-tests/src/CloudFormationClient.ts

#1740 - Add CAPABILITY_AUTO_EXPAND to CloudFormation stack create and update calls.
By adding CAPABILITY_AUTO_EXPAND to the capabilities parameters this enables customers to use SAM templates for Lambda functions.
If the resource type is ```AWS::Serverless::Function``` the ```CodeUri``` property will be emitted instead of ```Code```.

fix(amplify-category-function): enable SAM templates for functions

---

packages/amplify-category-function/provider-utils/awscloudformation/cloudformation-templates/lambda-cloudformation-template.json.ejs
packages/amplify-category-storage/provider-utils/awscloudformation/cloudformation-templates/s3-cloudformation-template.json.ejs
packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js
packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js
packages/amplify-category-storage/provider-utils/awscloudformation/triggers/dynamoDB/lambda-cloudformation-template.json.ejs
packages/amplify-category-storage/provider-utils/awscloudformation/triggers/s3/lambda-cloudformation-template.json.ejs
packages/amplify-e2e-tests/__tests__/storage.test.ts
packages/amplify-e2e-tests/src/categories/auth.ts
packages/amplify-e2e-tests/src/categories/storage.ts
packages/amplify-e2e-tests/src/utils/index.ts
packages/amplify-e2e-tests/src/utils/sdk-calls.ts

New features based on feedback:
* Auto-add S3 bucket access permissions on adding a trigger to S3
* Option to edit lambda trigger when adding a new trigger for S3 or Dynamo

Storage Triggers Integration Tests + address DA/PM Feedback

---

packages/amplify-category-function/provider-utils/awscloudformation/index.js

*Issue #, if available:* [1806](https://github.com/aws-amplify/amplify-cli/issues/1806)
Functions in projects created with an older version of the Amplify cli seem not to have a `function-parameters.json` file. We should check if this file exists before trying to read it.

fix: check that function-parameters.json exists before trying to read it

---

packages/amplify-category-function/provider-utils/awscloudformation/index.js

Fixes #1826 
Fixes issue when headless init does not pass function category or any categories.

fix(amplify-category-function): fixing headless params

---

packages/amplify-category-analytics/package.json
packages/amplify-category-api/package.json
packages/amplify-category-auth/package.json
packages/amplify-category-function/package.json
packages/amplify-category-interactions/package.json
packages/amplify-category-notifications/package.json
packages/amplify-category-storage/package.json
packages/amplify-category-xr/package.json
packages/amplify-cli/package.json
packages/amplify-e2e-tests/package.json

Circle CI failed to update the versions after npm publish, manually update the package versions to
clear the deployment path

chore(cli): manual update versions

---

packages/amplify-codegen/src/callbacks/postPushCallback.js
packages/amplify-codegen/tests/callbacks/postPushCallback.test.js

Codegen use to reset the location of downloaded introspection shcema to the default location when a
push was done. Updated code to prevent chaning of schema location
Fix #1818

 fix(amplify-codegen): prevent schema location change on push

---

packages/amplify-category-storage/provider-utils/awscloudformation/cloudformation-templates/s3-cloudformation-template.json.ejs
packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js

fix #1852
Change to reference actual S3 bucket name instead of `bucketName` parameter.

fix(amplify-category-storage): consider env in S3TriggerBucketPolicy

---

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js
packages/graphql-dynamodb-transformer/src/resources.ts
packages/graphql-transformer-common/src/ResourceConstants.ts

#1867 
Adds a new CFN parameter that toggles the value of `SSESpecification.SSEEnabled` property of the `AWS::DynamoDB::Table` resources created by `@model`. New projects are now initialized with DynamoDB's `SSEEnabled` set to **false**. Users who have deployed an API already are able to change their table's encryption settings via the DynamoDB console. There is currently a limitation in the DynamoDB CFN implementation that prevents changing this setting via CFN for now. Users are also free to create a new env and manually set the parameter in parameter.json for the new environment.
*How to use*
Add this to your `parameter.json`:
```json
{
"DynamoDBEnableServerSideEncryption": false
}
```
> Note: If you have deployed this API previously …

enhancement(graphql-dynamodb-transformer) - Adding parameter to configure server side encryption

---

packages/amplify-graphql-docs-generator/__integration__/__snapshots__/e2e.test.ts.snap
packages/amplify-graphql-docs-generator/templates/javascript.hbs

The current handlebar template use `// eslint-disable` at the beginning of the file, [which is invalid](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments).
Here is the eslint error I have:
```
1:1  error  Prefer default export  import/prefer-default-export
```
If I manually replace the comment type, then it works.
Because these files are autogenerated and will be erased regularly, this forces me to disable the rule in all my project (I could override the eslint config for these specific files, but using the right comment seems to be a better solution 🙂).

style(amplify-codegen): eslint-disable comment style

---

packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelConnectionTransformer.e2e.test.ts

fix #1799
#1799
Prevents self connection from associating with its own field

fix(graphql-connection-transformer): fix self connection bug

---

packages/amplify-util-mock/src/CFNParser/appsync-resource-processor.ts

API Mock server did not handle unsupported data source such as elastic search well. Updated the code
to handle it gracefully and use NONE as the data source when not supported
fix #1997

fix(amplify-util-mock): handle unsupported data source gracefully

---

packages/amplify-category-api/provider-utils/awscloudformation/cloudformation-templates/apigw-cloudformation-template-default.json.ejs

#1905
Create parity between `auth` and `unauth` policies when updating APIGW. 
`auth` policy currently allows resource invocation for `route_name` on:
`/{route_name}`
`/{route_name}/*`
`unauth` policy currently only allows resource invocation for `route_name` on:
`/{route_name}/*`
`unauth` policy will henceforth allow resource invocation for `route_name` on:
`/{route_name}`
`/{route_name}/*`

fix(amplify-provider-awscloudformation): apigw unauth access

---

packages/amplify-util-mock/src/api/resolver-overrides.ts

Amplify mock creates the files that are generated by the GraphQL transformer to make it easy to
customize them. If a resolver was customized and mock server was started on windows, the customized resolver file got overwritten with the generated file from the transformer on windows. This was caused due difference in the file path separator produced by transformer and filesystem. Fixed it by normalizing the file path
fix #2006

fix(amplify-util-mock): prevent resolver file overwrite in windows

---

packages/graphql-function-transformer/src/FunctionTransformer.ts

The JSON generated for the pipeline resolver is invalid and results in an error when sending any requests.  The two fields removed appear to be DynamoDB specific, so I removed them since we are resolving to a Lambda function.
The current resulting pipeline resolver is:
```
{
"version": "2018-05-29",
"operation": "Invoke",
"payload": {
"typeName": "$ctx.stash.get("typeName")",
"fieldName": "$ctx.stash.get("fieldName")",
"arguments": $util.toJson($ctx.arguments),
"identity": $util.toJson($ctx.identity),
"source": $util.toJson($ctx.source),
"request": $util.toJson($ctx.request),
"prev": $util.toJson($ctx.prev)
}
}
```
The new pipeline resolver is:
```
{
"version": "2018-05-29",
"operation": "Invoke",
"payload": {
"arguments": $util.toJson($ctx.arguments), …
```

Fix for invalid JSON in pipeline resolver

---

packages/amplify-graphql-types-generator/src/swift/codeGeneration.ts

Codegen automatically adds localUri and mimeTypes for S3Object.
Prevent adding these fields if they are already declared in S3ObjectInput
fix #1903

fix(amplify-graphql-types-generator): generate valid swift code

---

packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformerLocal.e2e.test.ts

made sure that all the e2e tests for key account for the sortDirection change

test(graphql-transformers-e2e-tests): key transformer fixes

---

packages/amplify-provider-awscloudformation/lib/build-resources.js

E2E tests with functions and with no package.json in the project dir are failing.
Fix function hooks 'package.json' exists check.

fix: Fix package.json exists check for functions

---

packages/amplify-codegen/commands/codegen/codegen.js

`Generates GraphQL statements(queries, mutations and subscriptions) and type annotations. ` -> `Generates GraphQL statements (queries, mutations and subscriptions) and type annotations.`

Simple grammar fix in codegen.js

---

package.json
packages/amplify-e2e-tests/package.json
packages/amplify-e2e-tests/src/categories/api.ts
packages/amplify-e2e-tests/src/categories/function.ts
packages/amplify-e2e-tests/src/categories/interactions.ts
packages/amplify-e2e-tests/src/categories/predictions.ts
packages/amplify-e2e-tests/src/categories/storage.ts
packages/amplify-e2e-tests/src/configure/index.ts
packages/amplify-e2e-tests/src/init/amplifyPush.ts
packages/amplify-e2e-tests/src/init/deleteProject.ts
packages/amplify-e2e-tests/src/init/initProjectHelper.ts
packages/amplify-e2e-tests/src/utils/nexpect-modified/lib/nexpect.js
packages/amplify-graphql-docs-generator/package.json
packages/amplify-graphql-types-generator/package.json
yarn.lock

- Chore to move to our modified version of ```nextpect```
- Move back to node 8.x compatible commitizen
- Add engines requirement to docs and types generator tool

chore: fix nexpect references, add missing engines in 2 other CLI

---

packages/amplify-category-auth/provider-utils/awscloudformation/index.js
packages/amplify-cli/src/cli.js
packages/amplify-cli/src/commands/env/checkout.js
packages/amplify-cli/src/commands/push.js
packages/amplify-cli/src/extensions/amplify-helpers/get-env-info.js
packages/amplify-cli/src/extensions/amplify-helpers/get-project-details.js
packages/amplify-cli/src/extensions/amplify-helpers/push-resources.js
packages/amplify-cli/src/lib/config-steps/c0-analyzeProject.js
packages/amplify-cli/src/lib/config-steps/c9-onSuccess.js
packages/amplify-codegen/src/commands/remove.js
packages/amplify-provider-awscloudformation/lib/configuration-manager.js
packages/amplify-util-mock/src/storage/storage.ts

#1056
- Add uncaught error handler to CLI for friendlier error messages, due to the lack of GlueGun capability for this
- Throw friendly error message when environment seems to be uninitialized for various commands
- Deduplicate the code when reading the environment file
- Fix some typos

fix: #1056, dedup environment file reading

---

packages/graphql-key-transformer/package.json
packages/graphql-key-transformer/src/KeyTransformer.ts
yarn.lock

#1720
Make sure that for 2+ part @key names valid GraphQL type names will be generated, with proper pascal casing.

fix: #1720 - fix GraphQL name generation for @key

---

.gitignore
packages/amplify-e2e-tests/package.json
packages/amplify-e2e-tests/src/categories/api.ts
packages/amplify-e2e-tests/src/categories/auth.ts
packages/amplify-e2e-tests/src/categories/function.ts
packages/amplify-e2e-tests/src/categories/interactions.ts
packages/amplify-e2e-tests/src/categories/predictions.ts
packages/amplify-e2e-tests/src/categories/storage.ts
packages/amplify-e2e-tests/src/configure/index.ts
packages/amplify-e2e-tests/src/init/amplifyPush.ts
packages/amplify-e2e-tests/src/init/deleteProject.ts
packages/amplify-e2e-tests/src/init/initProjectHelper.ts
packages/amplify-e2e-tests/src/utils/nexpect-modified/index.d.ts
yarn.lock

- Due to a recent change for nexpect related references e2e were broken, this PR fixes it by properly referencing and removing dependency on ```@types/nexpect``` as well.
- amplify-integ*/ added to .gitignore

fix: regression for e2e tests because of nexpect reference

---

packages/graphql-elasticsearch-transformer/src/SearchableModelTransformer.ts
packages/graphql-elasticsearch-transformer/src/resources.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformer.e2e.test.ts

re #2080
change the numberTypes to nonKeyword type as there can other data types in es which will not include keywords, such as date (ref AWSDate, AWSDateTime)

fix(graphql-elasticsearch-transformer): changed nonKeyword types

---

packages/amplify-codegen/src/callbacks/postPushCallback.js
packages/amplify-codegen/tests/callbacks/postPushCallback.test.js

Amplify CLI generate types based on the statemnt that got generated when pushing the API. The
statement generation method is an async method. Updated the code to await statement generation
before kicking off types generation
fix #2129

fix(amplify-codegen): await statement generation before generating types

---

packages/graphql-transformer-core/src/util/amplifyUtils.ts

GraphQL transformer splits resources into multiple stack to get over the cloudformation limit on the
number of resource a stack can have. If a resource gets moved to different stack it would cause
cloudformation to delete and recreate the same  resource. To prevent this transformer tries to put
the resources in the same stack in subsequent deployment. We used to include custom resources in
the stack mapping which should not be the case as these are custom stacks. Updated the code not to
include custom stack in stack mapping computation.
fix #2167

fix(graphql-transformer-core): dont incl custom stacks in stack mapping

---

packages/amplify-frontend-javascript/lib/frontend-config-creator.js

Ensure that aws-exports file's `oauth.responseType' value is 'token' when the implicit grant flow is selected.  This ensures that the correct response_type is used in the query string that amplify.js builds.

fix(amplify-frontend-javascript): fix implicit grant oauth bug

---

packages/graphql-transformer-core/src/util/amplifyUtils.ts
packages/graphql-transformer-core/src/util/sanity-check.ts

Updated stack sanity check and stack mapping code to work with older version of project when
migrating project
partial fix to #2196

fix(graphql-transformer-core): fix migration errors

---

packages/amplify-codegen/package.json
packages/amplify-codegen/src/codegen-config/AmplifyCodeGenConfig.js
packages/amplify-codegen/tests/codegen-config/AmplifyCodegenConfig.test.js
yarn.lock

Codegen generates grpaql configuration file which contains paths for schema and documents. These
paths used to be platform specific path which caused issues when the same projects were used in
different Operating Systems. Updated codegen to normalize path to posix style path as it is
supported by all the platforms
fix #2147 and #2002

fix(amplify-codegen): support multi os team workflow in codegen

---

.circleci/config.yml

remove dependency on js integ test for other integ tests to run

---

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-auth-transformer/src/__tests__/MultiAuth.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthModelAuthTransformer.e2e.test.ts
yarn.lock

Fixes #2272, #2273
- When IAM is the default authentication mode, an empty policy was generated, because @aws_iam directives were not added, so it did not add the policy resource.
- @key generated queries were not properly protected, they missed the directives and the IAM policy resource entries.

fix: #2272, #2273 - create correct policies when IAM is the default auth

---

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-auth-transformer/src/__tests__/MultiAuth.test.ts

When a `groups` @auth rule is specified not all the operations were getting the proper @aws_* auth directives. This PR fixes that issue.

fix: directive generation for groups auth

---

packages/graphql-transformers-e2e-tests/src/__tests__/NewConnectionTransformer.e2e.test.ts

test: fixing the graphql_e2e_tests AppSyncApiName missing error

---

packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthModelAuthTransformer.e2e.test.ts

Fix a typo in the multi auth test GraphQL schema that caused e2e test failures for the whole suite.

fix: multiauth-e2e typo

---

packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
packages/graphql-transformer-core/src/index.ts
packages/graphql-transformer-core/src/util/amplifyUtils.ts

The API project is built twice because of the StackMapping feature. To make sure that Transformer instances (and their states) are not reused between the independent build phases the transformer instantiation is moved out to a factory function and it is getting invoked within ```buildProject```.

fix: ensure that transformer instances are not reused

---

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-auth-transformer/src/resources.ts
packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthModelAuthTransformer.e2e.test.ts

fixed bug with per field auth not using same variable 'field_isStaticAuthorizedVariable'
re pr #2316

fix(graphql-auth-transformer): fixed bug with per field auth on create

---

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-auth-transformer/src/__tests__/PerFieldAuthArgument.test.ts
packages/graphql-auth-transformer/src/__tests__/__snapshots__/PerFieldAuthArgument.test.ts.snap
packages/graphql-auth-transformer/src/resources.ts

- made sure mutationTypeName is set as opposed to the name of the actual operation
- operation is set mutliple times per field - it only needs to be set one with the operationTypeName
- set correct resolver id to delete `protectDeleteForField`

fix duplicate operation being set in mutation vtl response resolvers

---

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-transformers-e2e-tests/src/__tests__/NewConnectionWithAuth.e2e.test.ts

added resolverID for delete in the event subscriptions onDelete is enabled
- added resolverID for delete in the event subscriptions onDelete is enabled
- updated NewConnectionWithAuthTests

fix(graphql-auth-transformer): fixed per field delete logic

---

packages/amplify-codegen/src/commands/add.js

Only add framework to project config if in a javascript project

fix(amplify-codegen): add framework only if javascript

---

packages/graphql-key-transformer/src/KeyTransformer.ts

KeyTransformer class name was FunctionTransformer, it was working because it is a default export, but would have failed otherwise.

fix: the KeyTransformer class name was incorrect

---

packages/amplify-appsync-simulator/src/data-loader/lambda/index.ts
packages/amplify-appsync-simulator/src/resolvers/function.ts
packages/amplify-appsync-simulator/src/resolvers/pipeline-resolver.ts
packages/amplify-appsync-simulator/src/resolvers/unit-resolver.ts
packages/amplify-appsync-simulator/src/schema/directives/auth.ts
packages/amplify-appsync-simulator/src/schema/index.ts
packages/amplify-appsync-simulator/src/server/operations.ts
packages/amplify-appsync-simulator/src/utils/expose-graphql-errors.ts
packages/amplify-appsync-simulator/src/velocity/index.ts
packages/amplify-appsync-simulator/src/velocity/util/errors.ts
packages/amplify-appsync-simulator/src/velocity/util/general-utils.ts
packages/amplify-appsync-simulator/src/velocity/util/index.ts
packages/amplify-util-mock/src/__e2e__/connections-with-auth-tests.e2e.test.ts
packages/amplify-util-mock/src/__e2e__/per-field-auth-tests.e2e.test.ts

Mock server did have support for Resolver versions. Updated mock implementation to support template
version and surface errors raised using $util.appendError
fix #2134 #2211 and #2299

fix(amplify-appsync-simulator): add support for AppSync template version

---

packages/amplify-util-mock/src/CFNParser/appsync-resource-processor.ts
yarn.lock

Mock inferred names of request and response mapping template path based on the filed name and type name instead of using the defined values in the cloudformation template. Updated resource processor to honor the template path defined in the cloudformation stack
fix #2306

fix(amplify-util-mock): add support for custom resolver template name

---

packages/amplify-appsync-simulator/src/data-loader/none/index.ts

None data source handler use to return the data it got instead of returning the payload part of
data. Updated the handler to adhere to appsync behavior

fix(amplify-appsync-simulator): fix none data source handler

---

packages/amplify-util-mock/src/CFNParser/lambda-resource-processor.ts
packages/amplify-util-mock/src/api/api.ts
packages/amplify-util-mock/src/utils/lambda/invoke.ts
packages/amplify-util-mock/src/utils/lambda/load.ts
packages/amplify-util-mock/tsconfig.json

Mock implementation used lambda function resource name instead of the function name when mocking API. Update the implementation to parse lambda cloudformation to get function name, handler and enviornment variables and use them for mock invocation
fix #2280

fix(amplify-util-mock): use lambda fn name instead of resource name

---

packages/amplify-codegen/src/utils/updateAmplifyMeta.js

Fixes #2360 
meta.json was writing out the JS object instead of the JSON version of the object upon codegen add api operation.
This happened because context.filesystem.write is different with the new plugin system.

fix: #2360 - meta json was written as object

---

packages/amplify-util-mock/src/api/api.ts
packages/amplify-util-mock/src/utils/ddb-utils.ts

Stop mutating input config object when configuring data sources. This is addressing the [comment](https://github.com/aws-amplify/amplify-cli/pull/2357#discussion_r326508567)

refactor(amplify-util-mock): stop mock config mutation

---

packages/graphql-elasticsearch-transformer/src/SearchableModelTransformer.ts
packages/graphql-elasticsearch-transformer/src/resources.ts
packages/graphql-transformer-core/src/TransformerContext.ts
packages/graphql-transformer-core/src/__tests__/TransformFormatter.test.ts
packages/graphql-transformer-core/src/util/blankTemplate.ts
packages/graphql-transformer-core/src/util/splitStack.ts

Using a map to determine the correct arn layer from the region of the user
fix #2386
#2386
Add a layer that contains the previous version of the SDK to the lambda resource based on the region of the user

fix(graphql-elasticsearch-transformer): add layer based on region

---

packages/amplify-appsync-simulator/package.json
packages/amplify-appsync-simulator/src/__tests__/velocity/util/time.test.ts
packages/amplify-appsync-simulator/src/velocity/util/index.ts
packages/amplify-appsync-simulator/src/velocity/util/time.ts
yarn.lock

Implemented missing time releated method in velocity template utils. Updated the method to support
Java Date format string
fix #2300

fix(amplify-appsync-simulator): impl missing methods in velocity utils

---

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-auth-transformer/src/__tests__/OwnerAuthTransformer.test.ts

add support for ownerField in auth subscriptions
- re #2361
- If there are no static group rules and only owner rules then the owner rules are required int the subscription operation this also applies to owner rules with an ownerField.

fix(graphql-auth-transformer): add support for ownerfield

---

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-walkthrough.js

when the CLI prompt the user to select from some options, it uses the inquirer library, and if the
options are empty, inquirer throws error, which leads the CLI to exit without proper messages given
to the user. This PR safeguard against such situation for the RDS selection, and it will print out
proper error message before the CLI exits.
fix #2423

fix(amplify-category-api): safeguard prompt with empty options

---

.circleci/config.yml
.gitignore
packages/amplify-e2e-tests/package.json
packages/amplify-ui-tests/package.json
packages/graphql-transformers-e2e-tests/package.json

Update e2e test configuration to generate test results in JUnit format and updated circle ci config
to upload those results for analysis

ci: upload test run reports from e2e tests

---

packages/amplify-provider-awscloudformation/lib/update-idp-roles-cfn.json

amplify delete command failed to delete the complete stack due to the invalid lambda response sent
from UpdateRolesWithIDPFunction. Updated the response to send an empty object

fix(amplify-provider-awscloudformation): amplify delete delete the stack

---

packages/amplify-codegen/src/walkthrough/add.js

When a new API is added and if the api is pushed with yes flag (headless mode), then codegen fails
with error proj.inclues || []).map is not a function. Updated codegen to return a array of include
pattern when using headless mode
fix #2365

fix(amplify-codegen): support headless push for newly added api

---

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js
packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-auth-transformer/src/resources.ts

fix: change default length for api key back to 7 days

fix: change default length for api key back to 7 days

---

packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts
packages/graphql-connection-transformer/src/__tests__/ModelConnectionTransformer.test.ts
packages/graphql-connection-transformer/src/resources.ts

The @connection directive can optionally accept a limit which overrides
the default limit of 10.
*Issue #, if available:* #1703
The `ModelConnectionTransformer` sets the limit in the vtl file if it was provided in the `@connection` directive, e.g.:
```graphql
type Post @model {
id: ID!
title: String!
comments: [Comment] @connection(limit: 50)
}
type Comment @model {
id: ID!
content: String
}
```

feat(graphql-connection-transformer): limit

---

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-walkthrough.js

Fixes 'No RDS access credentials found in the AWS Secret Manager' when Query Editor secret is found
*Issue:* #2498
*Description of changes:* Adds nested `if` to fix exit logic if generated secret was found.

fix(amplify-category-api): Fix #2498

---

packages/amplify-frontend-android/lib/frontend-config-creator.js
packages/amplify-frontend-ios/lib/frontend-config-creator.js

If an GraphQL API is provisioned using older version CLI its possible that the cloudformation output
might have authConfig missing. The frontend config creator for andorid and iOS did not handle
missing authConfig. Updated to code to handle missing authConfig
fix #2480

fix: handle missing authConfig gracefully

---

packages/amplify-category-analytics/provider-utils/supported-services.json
packages/amplify-e2e-tests/__tests__/analytics.test.ts
packages/amplify-e2e-tests/src/categories/analytics.ts

#1877 
Modified the regex to allow hyphen characters in resource name
Created test to add analytics pinpoint resource and cleanup after

fix(amplify-category-analytics): Allow hyphens for pinpoint resources name

---

.circleci/config.yml

Cypress tests that run on circle ci have been unreliable and flaky. These tests are stopping our CI
from running the rest of the tests

ci: don't fail pipeline on failure of JS tests

---

packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs

fix #2284 
Adds a check in auth yml for supported login providers; this block should NOT display if
authproviders length is 1 and there are audiences, as this scenario indicates that google is the
only selected provider for a native project, and in this case the open id lambda will perform all
configuration

fix(amplify-category-auth): checks for google idp federation on native

---

packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js

Cloud formation push fails in amplify console when a project has GraphQL API but changes are in non
GraphQL API resource. When pushing resources to cloud, Amplify CLI expects the api build directory
to present. When the push is running in the console,  API build directory will be missing because of
the gitignore rule. Updating the build steps to generate build folder when they are missing
https://github.com/aws-amplify/amplify-console/issues/10

fix: mitigate push failuer when graphql api backend is missing

---

packages/amplify-category-hosting/lib/S3AndCloudFront/index.js
packages/amplify-e2e-tests/__tests__/hosting.test.ts
packages/amplify-e2e-tests/src/categories/hosting.ts

remove CloudFrontOriginAccessIdentity from the hosting template output when CloudFront is not
enabled
fix #2551

fix(amplify-category-hosting): fix hosting bug

---

packages/amplify-util-mock/src/__e2e__/subscriptions-with-auth.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts

add a wait time after setting up a subscription to avoid hanging

test: add wait time on subs e2e

---

packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts
packages/graphql-dynamodb-transformer/src/definitions.ts

ref #1984
- allow id as a type for non model objects
- lint fixes 

fix(graphql-dynamodb-transformer): allow id for non model objects

---

packages/amplify-category-analytics/commands/analytics/add.js
packages/amplify-category-api/commands/api/add-graphql-datasource.js
packages/amplify-category-api/commands/api/add.js
packages/amplify-category-api/commands/api/console.js
packages/amplify-category-api/commands/api/update.js
packages/amplify-category-function/commands/function/add.js
packages/amplify-category-function/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js
packages/amplify-category-storage/commands/storage/add.js
packages/amplify-category-storage/commands/storage/update.js
packages/amplify-cli/src/extensions/amplify-helpers/remove-resource.js
packages/amplify-cli/src/extensions/amplify-helpers/trigger-flow.js
packages/amplify-codegen/src/utils/updateAmplifyMeta.js
packages/amplify-util-mock/src/utils/lambda/load.ts

use standard amplify cli provided json read to avoid json parse bug
fix #2580 #2550

fix(amplify-category-api): use standard json read

---

packages/amplify-category-api/commands/api.js

s/it's/its/ in output of `amplify api help`

Remove incorrect apostrophe in command description

---

.circleci/enable_api.exp
packages/amplify-cli/src/extensions/amplify-helpers/service-select-prompt.js
packages/amplify-e2e-tests/src/categories/api.ts
packages/amplify-e2e-tests/src/categories/auth.ts
packages/amplify-e2e-tests/src/categories/storage.ts
packages/amplify-ui-tests/src/categories/api.ts
packages/amplify-ui-tests/src/categories/storage.ts

In the CLI, the current output looks like:
> ? Please select from one of the below mentioned services Content (Images, audio, video, etc.)
This adds a `:` to make the output clearer.  _(This originated as a nit in a PR)_

chore: add : to "Please select from one of the below mentioned services"

---

packages/amplify-category-auth/index.js
packages/amplify-category-auth/provider-utils/awscloudformation/index.js

fix(#2309 )
Calls removeDeprecatedProps before passing values to CFN in externalAuthEnable. Also fixes copy/paste error in removeDeprecatedProps function.

fix(amplify-category-auth): removes deprecated props for external auth

---

packages/amplify-category-api/provider-utils/supported-datasources.json

I bumped into a missing availability region while playing with Aurora Serverless and AppSync.
I was trying the `amplify api add-graphql-datasource` command in the CLI.
According to [this blog](https://aws.amazon.com/blogs/aws/new-data-api-for-amazon-aurora-serverless/), the necessary Data API feature has only recently been added to more regions.
I only had a brief look through the codebase, but I think this is the only change necessary - hope it's a helpful first contribution :) Btw, thanks to the AppSync and Amplify team for the great work!
~

Add new available regions for Aurora Serverless

---

packages/amplify-util-mock/src/__e2e__/per-field-auth-tests.e2e.test.ts
packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-auth-transformer/src/__tests__/PerFieldAuthArgument.test.ts
packages/graphql-auth-transformer/src/__tests__/__snapshots__/PerFieldAuthArgument.test.ts.snap

#2591 
removing unnecessary enforce check for @model in when adding @auth on a field

fix(graphql-auth-transformer): remove enforce model check for field

---

packages/amplify-util-mock/src/CFNParser/appsync-resource-processor.ts
packages/amplify-util-mock/src/__e2e__/key-transformer.e2e.test.ts

#2606
LSIs were not copied to tables definitions passed to DynamoDB Local when using mock services.

fix(mock): #2606 - mocking does not start when there are LSIs in DynamoDB table

---

packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs
packages/amplify-category-storage/provider-utils/awscloudformation/cloudformation-templates/s3-cloudformation-template.json.ejs
packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js

Randomizing account-wide unique names like IAM role names, S3 bucket names (based on the Cloudformation Stack ID).
This prevents deployment issues for S3Buckets and Auth resources (when deploying same project in the same account).

fix: randomize role-names and bucket-name for auth and storage category

---

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-auth-transformer/src/__tests__/__snapshots__/OperationsArgument.test.ts.snap
packages/graphql-auth-transformer/src/__tests__/__snapshots__/SearchableAuthTransformer.test.ts.snap
packages/graphql-auth-transformer/src/resources.ts
packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts
packages/graphql-dynamodb-transformer/src/definitions.ts
packages/graphql-dynamodb-transformer/src/resources.ts
packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-mapping-template/src/dynamodb.ts
packages/graphql-transformer-common/src/ModelResourceIDs.ts
packages/graphql-transformers-e2e-tests/src/__tests__/MutationCondition.e2e.test.ts

This PR adds a new parameter to the generated mutations where additional conditions can be specified for the mutation.
Beside the new parameter, a new input type is also added to the schema for each type that has mutations generated, the naming follows the ```Model{name}ConditionInput``` convention.
It works together with the existing directives like ```@key```, ```@versioned```, ```@auth```, ```@connection```, the ones that modifying the schema.
From this source schema: 
```graphql
type Post
@model
@versioned
@auth(rules: [
{ allow: owner }
{ allow: groups }
])
@key(fields: ["id", "type", "slug"])
@key(name: "byTypeSlugLikeCount", fields: ["type", "slug", "likeCount"])
{
id: ID!
content: String
type: String!
category: String
owner: String
groups: [String!]
slug: …
```

Add condition support to mutations

---

packages/amplify-codegen/src/walkthrough/add.js

#2365
Add back fix that was removed by prettier

fix(amplify-codegen): fix headless push with codegen

---

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts

* fix: ignored ApiKeyConfig for additional providers
* fix bug with use of Array.concat()

fix: ignored ApiKeyConfig for additional providers (#2741)

---

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelAuthTransformer.e2e.test.ts

#2727 
This PR changes an issue when owner and group auth rules was used together with public/private (userPool provider).
After this change since a ```{ allow: private }``` rule allows access to the underlying data, no matter what is the authenticated user's name (owner) or group membership, the CLI will not generate the authz check logic for the resolvers.

fix: #2727

---

packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.js
packages/amplify-cli/tsconfig.json
packages/amplify-provider-awscloudformation/lib/display-helpful-urls.js
packages/amplify-provider-awscloudformation/lib/push-resources.js
packages/amplify-provider-awscloudformation/lib/upload-appsync-files.js
packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js

This PR is fixing some API key management related issues:
- Setting CreateAPIKey: 0 will be honored even if API_KEY authentication is used, just like it was before multi-auth with  APIKeyExpirationEpoch: -1.
- After an API was deployed with CreateAPIKey: 1 and then it is deployed with CreateAPIKey: 0 the API key will be correctly removed from the CloudFormation templates and ```amplify-meta.json```.
- When an API is deployed without an actual API key but with API_KEY auth a warning will be printed after push.
- When CreateAPIKey and APIKeyExpirationEpoch is used together a warning is printed.
Chore:
- Upload is "asyncified"
- CLI is compiled to ES6 target
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

fix: api key creation/deletion logic

---

packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js

Fixes e2e test that fails due to two policies having the same name

fix: Give ddb trigger policy different name from lambda execution policy

---

packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-javascript-visitor.ts
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-typescript-visitor.ts

fix(amplify-codegen-appsync-model-plugin): include enums in JS exports

---

packages/amplify-provider-awscloudformation/src/utils/archiver.js

The zip file the CLI uploads to the cloud requires the build folder of the APIs, because sanity check requires it to succeed. A change in CLI push phases surfaced this existing error.

fix: include api build directory in cloud zip

---

packages/amplify-e2e-tests/__tests__/auth.test.ts
packages/amplify-e2e-tests/src/init/amplifyPush.ts

In the new push workflow, a pull is executed first, this leads to extra prompt to the user if API category is added, which causes the e2e tests to fail. this PR fixes the broken auth e2e tests.

test(amplify-e2e-tests): fix auth e2e tests

---

packages/amplify-e2e-tests/package.json
packages/amplify-util-mock/package.json
packages/amplify-util-mock/tsconfig.json
packages/graphql-transformers-e2e-tests/package.json
packages/graphql-transformers-e2e-tests/src/__tests__/ConnectionsWithAuthTests.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/KeyWithAuth.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelAuthTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthModelAuthTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/MutationCondition.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/NewConnectionWithAuth.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/PerFieldAuthTests.e2e.test.ts
yarn.lock

Fix: Jest is now configured to use node test environment and that caused some e2e tests for fail.

fix: e2e test failures with node env

---

packages/graphql-transformers-e2e-tests/package.json
yarn.lock

added amplify next dependency to handle missing navigator in node environment
related to https://github.com/aws-amplify/amplify-js/issues/4305

fix(graphql-transformers-e2e-tests): update  aws-amplify to 2.x

---

packages/amplify-cli/src/extensions/amplify-helpers/trigger-flow.js
packages/amplify-cli/src/lib/pull-backend.js
packages/amplify-frontend-android/lib/amplify-config-helper.js
packages/amplify-frontend-ios/lib/amplify-config-helper.js

The latest CLI (4.x.x) generates amplifyconfiguration.json for native projects. It's based on the latest amplify-meta format, in which, for the AppSync API, the default auth type is under `output.authConfig.defaultAuthentication.authenticationType`, but if the amplify-meta was generated by older versions of the CLI, the default auth type is under `output.securityType`. 
This PR update allows for the legacy amplify-meta format when generating the amplifyconfiguration.json file.

fix(cli): fix appsync api native config file for legacy metadata

---

packages/amplify-appsync-simulator/package.json
packages/amplify-appsync-simulator/src/velocity/util/general-utils.ts

fix(amplify-appsync-simulator): add js-string-escape to package.json

---

packages/amplify-codegen-appsync-model-plugin/src/languages/java-declaration-block.ts
packages/amplify-codegen-appsync-model-plugin/src/preset.ts
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-java-visitor.ts
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts
packages/amplify-codegen-appsync-model-plugin/tsconfig.json
yarn.lock

Remvoed targetName from Java model and update the models to preserve the case of type in generated
code

fix(amplify-codegen-appsync-model-plugin): remove targetName from model

---

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-auth-transformer/src/__tests__/MultiAuth.test.ts
packages/graphql-auth-transformer/src/resources.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelAuthTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthModelAuthTransformer.e2e.test.ts

fixed: #2703
Use managed policies instead of policies for GraphQL API policy generation for auth and unauth roles. Also take into account the policy size and create multiple policies of needed. This means that 6144 bytes long can be 1 policy and 10 Managed Policies can be attached to a single role and that 10 can be raised to 20 by AWS Support, which raises the maximum policy size to ~120kb, which is 10 times the currently supported size.
This PR does not solve the policy size issue for API Gateway (#2084), but since sizes are adding up, perhaps customers can be unblocked by this change.

fix: use managedpolicies and slice them, fixes: #2703

---

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-java-visitor.ts

Updated the QueryField name for Computed fields. The field used for input used for BelongsTo field
is an id field and the field itself is computed based on the value of input. Updated codegen to
generate the right input varaible in QueryField

fix(amplify-codegen-appsync-model-plugin): update QueryField name (java)

---

packages/amplify-cli/src/lib/attach-backend-steps/a10-queryProvider.js
packages/amplify-cli/src/lib/init-steps/s2-initProviders.js

Current behavior of the CLI plugin platform: If there are not active provider plugins, in the `init` or the `pull` workflows, it prompts the customer to select from an empty list. 
This PR address this bug by printing more relevant error message when it occurs, and then throws an error to properly end the commands' executions. 

fix(cli): print correct message if no provider plugins are active

---

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts

Make the id field the first field so arity of the constructor is maintained

fix(amplify-codegen-appsync-model-plugin): make id field the first field

---

packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/cloudformation-templates/CreateAuthChallenge.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CustomMessage/cloudformation-templates/CustomMessage.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/DefineAuthChallenge/cloudformation-templates/DefineAuthChallenge.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostAuthentication/cloudformation-templates/PostAuthentication.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/cloudformation-templates/PostConfirmation.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreAuthentication/cloudformation-templates/PreAuthentication.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreSignup/cloudformation-templates/PreSignup.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreTokenGeneration/cloudformation-templates/PreTokenGeneration.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/VerifyAuthChallengeResponse/cloudformation-templates/VerifyAuthChallengeResponse.json.ejs

Export execution role so that policies can be associated later. This brings them in line with
function category provider.
re #2303

feat(amplify-category-auth): export lambda trigger roles in template

---

packages/amplify-e2e-tests/src/categories/auth.ts

removed additional send which caused expect next line issues

test(amplify-e2e-tests): fixed add auth with max options

---

packages/graphql-elasticsearch-transformer/streaming-lambda/python_streaming_function.py

#2938 
Replaced print with logger.debug in python_streaming_function.py to avoid unneeded logging.

fix(graphql-dynamodb-transformer): fixed KeyError for unset DEBUG

---

packages/amplify-util-mock/src/utils/git-ignore.ts

Original bug: On Windows, path.relative returns a path with escaped backslashes. This entry is incompatible with .gitignore and results in new entries being added every time "amplify mock" is run.  
Fix: Convert escaped backslash to forward slash for detection and entry in .gitignore.
#2624 

Fix for .gitignore duplicating amplify\mock-data

---

packages/graphql-auth-transformer/src/__tests__/MultiAuth.test.ts
packages/graphql-auth-transformer/src/resources.ts

fix: #2703 - Policy size calculation used a smaller value for region name and certain regions could cause a miscalculation, so policy was larger than possible.

fix: #2703 - policy size calculation

---

packages/amplify-app/src/index.js

Use relative paths so there is not a conflict when using source control.
https://github.com/aws-amplify/amplify-ios/issues/247

fix: use relative path for xcode and android studio helper files

---

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js

if resolver config exists and it either has syncconfig for a project for model(s) then write it to
the transform conf

fix(amplify-category-api): check to see resolverConfig exists

---

packages/amplify-codegen-appsync-model-plugin/src/__tests__/utils/process-connections.test.ts
packages/amplify-codegen-appsync-model-plugin/src/utils/process-connections.ts

Model gen did not handle a connection if it was referencing itself
partial fix to #3040

fix(amplify-codegen-appsync-model-plugin): support self referncing conn

---

packages/amplify-codegen-appsync-model-plugin/src/__tests__/utils/process-auth.test.ts
packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/utils/process-auth.ts

Changed userClaim to identityClaim and convert username to cognito:username

fix( amplify-codegen-appsync-model-plugin): field name errors

---

packages/amplify-cli/src/domain/amplify-toolkit.ts

#2458 
forceRemoveResource was left out of the amplify-toolkit lazy-loader.  This commit adds the function.

fix(cli): fixes cognito trigger removal bug

---

packages/amplify-category-analytics/provider-utils/awscloudformation/cloudformation-templates/pinpoint-cloudformation-template.json
packages/amplify-category-auth/provider-utils/awscloudformation/assets/adminAuth/admin-queries-function-template.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/user-pool-group-template.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/cloudformation-templates/CreateAuthChallenge.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CustomMessage/cloudformation-templates/CustomMessage.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/DefineAuthChallenge/cloudformation-templates/DefineAuthChallenge.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostAuthentication/cloudformation-templates/PostAuthentication.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/cloudformation-templates/PostConfirmation.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreAuthentication/cloudformation-templates/PreAuthentication.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreSignup/cloudformation-templates/PreSignup.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreTokenGeneration/cloudformation-templates/PreTokenGeneration.json.ejs
packages/amplify-category-auth/provider-utils/awscloudformation/triggers/VerifyAuthChallengeResponse/cloudformation-templates/VerifyAuthChallengeResponse.json.ejs
packages/amplify-category-interactions/provider-utils/awscloudformation/cloudformation-templates/lex-cloudformation-template.json.ejs
packages/amplify-category-predictions/provider-utils/awscloudformation/assets/identifyCFNGenerate.js
packages/amplify-category-predictions/provider-utils/awscloudformation/cloudformation-templates/identify-template.json.ejs
packages/amplify-category-predictions/provider-utils/awscloudformation/triggers/s3/lambda-cloudformation-template.json.ejs
packages/amplify-category-storage/provider-utils/awscloudformation/triggers/dynamoDB/lambda-cloudformation-template.json.ejs
packages/amplify-category-storage/provider-utils/awscloudformation/triggers/s3/lambda-cloudformation-template.json.ejs
packages/amplify-cli/src/extensions/amplify-helpers/constants.js
packages/amplify-cli/src/index.ts
packages/amplify-cli/src/project-config-version-check.ts
packages/amplify-provider-awscloudformation/lib/update-idp-roles-cfn.json
packages/graphql-transformers-e2e-tests/src/LambdaHelper.ts

re #2999
re #2617 
This PR updates the nodejs runtime version, from nodejs8.10 to nodejs10.x,  for all the Lambda backed custom resources in the Cloudformation templates used by the Amplify CLI. 
This is done according to the Lambda runtime support's [deprecation schdule](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html)
There's also logic to automatically check and update the nodejs versions for projects initialized by Amplify CLI prior to this PR update. So the customers do not need to manually update the versions. 

refactor(cli): update lambda custom resource nodejs runtime version

---

packages/amplify-cli/src/lib/init-steps/s9-onSuccess.js

Confusing initialization instructions.
Change `amplify <category> add` print to `amplify add <category>` in correspondence with api.

chore: update print info in s9-onSuccess.js

---

packages/amplify-app/src/index.js

#2955 
Use npm.cmd when amplify-app is run on windows

fix: support amplify-app on windows

---

packages/amplify-provider-awscloudformation/src/aws-utils/aws-amplify.js

general config level is not correctly handled for the amplify service client. This PR fixes it.
If the project is set to have 'general' config level for credentials and region, the configurationManger.loadConfiguration will return undefined, to allow the aws sdk to resolve the configuration. 
The getConfiguredAmplifyClient method checks for region and if the region is not covered by the Amplify Service, it will return undefined. But this does not work for general config level, because at that point region is unknown (configurationManger.loadConfiguration returned undefined), so for general config level the getConfiguredAmplifyClient method will always return undefined, nullify the Amplify Service related logic in the Amplify CLI …

fix(amplify-provider-awscloudformation): hand general config

---

.circleci/config.yml
packages/amplify-app/package.json
packages/amplify-appsync-simulator/package.json
packages/amplify-appsync-simulator/src/server/subscription.ts
packages/amplify-cli/package.json
packages/amplify-e2e-tests/package.json
packages/amplify-graphiql-explorer/package.json
packages/amplify-graphql-docs-generator/package.json
packages/amplify-graphql-types-generator/package.json
packages/amplify-ui-tests/package.json
packages/amplify-util-mock/package.json
packages/graphql-auth-transformer/package.json
packages/graphql-connection-transformer/package.json
packages/graphql-dynamodb-transformer/package.json
packages/graphql-elasticsearch-transformer/package.json
packages/graphql-http-transformer/package.json
packages/graphql-transformer-common/package.json
packages/graphql-transformer-core/package.json
packages/graphql-transformers-e2e-tests/package.json
packages/graphql-versioned-transformer/package.json
yarn.lock

As Node 8 became unsupported the CLI is moving to Node 10 as a minimum requirement, this PR implements those changes.

fix: upgrade to node10 as min version for CLI

---

packages/amplify-codegen/package.json
packages/amplify-codegen/src/codegen-config/AmplifyCodeGenConfig.js
yarn.lock

Replaced upath lib with slash, as updath does not work with latest version of node
fix #3131

fix(amplify-codegen): replace upath with slash

---

packages/amplify-appsync-simulator/src/server/operations.ts

set the body size limit to 10MB
fix #3086

fix(amplify-appsync-simulator): set max payload size for request

---

packages/amplify-cli/src/lib/init-steps/postInitSetup.js
packages/amplify-cli/src/lib/init-steps/s9-onSuccess.js
packages/amplify-cli/templates/plugin-template-frontend/event-handlers/handle-PostInit.js
packages/amplify-cli/templates/plugin-template-frontend/event-handlers/handle-PostPush.js
packages/amplify-cli/templates/plugin-template-frontend/event-handlers/handle-PreInit.js
packages/amplify-cli/templates/plugin-template-frontend/event-handlers/handle-PrePush.js
packages/amplify-cli/templates/plugin-template-provider/event-handlers/handle-PostInit.js
packages/amplify-cli/templates/plugin-template-provider/event-handlers/handle-PostPush.js
packages/amplify-cli/templates/plugin-template-provider/event-handlers/handle-PreInit.js
packages/amplify-cli/templates/plugin-template-provider/event-handlers/handle-PrePush.js
packages/amplify-cli/templates/plugin-template/event-handlers/handle-PostInit.js
packages/amplify-cli/templates/plugin-template/event-handlers/handle-PostPush.js
packages/amplify-cli/templates/plugin-template/event-handlers/handle-PreInit.js
packages/amplify-cli/templates/plugin-template/event-handlers/handle-PrePush.js

fix #2642
removed process.exit(0) in postInitSetup.js to raise the Amplify CLI platform's PostInit event

fix(cli): fix postinit invokation

---

packages/amplify-e2e-tests/src/__tests__/delete.test.ts
packages/amplify-e2e-tests/src/utils/awsExports.ts
packages/amplify-e2e-tests/src/utils/projectMeta.ts
packages/amplify-frontend-android/lib/frontend-config-creator.js
packages/amplify-frontend-ios/lib/frontend-config-creator.js
packages/amplify-frontend-javascript/lib/frontend-config-creator.js

point to aws exporsts in js deleteConfig and include amplify configuration in the delete for android
and ios
re #2997

fix: point to correct file to delete for amplify config

---

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-auth-transformer/src/__tests__/MultiAuth.test.ts

Currently, amplify-cli doesn't support groups authorization for oidc provider.
https://aws-amplify.github.io/docs/cli-toolchain/graphql#allowed-authorization-mode-vs-provider-combinations
However, generated VTLs are already generalized enough to reuse it for oidc. I try to enable it.

feat(graphql-auth-transformer): enable groups authentication for oidc

---

packages/amplify-codegen-appsync-model-plugin/src/scalars/supported-directives.ts
packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
packages/graphql-transformer-core/src/index.ts
packages/graphql-transformer-core/src/validation.ts
yarn.lock

AppSync service has some custom directives defined in the service. These directives are defiend in
transformer, so the documents that have them pass graphql validation. Passing them to model gen
plugin from transformer to keep these directives in sync

fix: pass appsync specific directives to model gen

---

packages/amplify-appsync-simulator/package.json
packages/amplify-appsync-simulator/src/velocity/index.ts

updated the appsync resolver parsing to use plain JSON parse instead of using JSON5 which is a
looser spec
fix #3180

fix(amplify-appsync-simulator): make resolver result parsing strict

---

packages/graphql-elasticsearch-transformer/src/definitions.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformer.e2e.test.ts

allows the use of lt lte gt gte on `@searchable`
re #2775

fix(graphql-elasticsearch-transformer): allow range on searches

---

packages/amplify-codegen-appsync-model-plugin/src/languages/swift-declaration-block.ts
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-swift-visitor.ts

fixed iOS model gen to handle non-codeable type arrays to use [] instead of List<> type
fix #3035

fix(amplify-codegen-appsync-model-plugin): support non-codeable types

---

packages/amplify-provider-awscloudformation/lib/amplify-service-migrate.js
packages/amplify-provider-awscloudformation/lib/initializer.js

This PR fixes the Amplify Console issue [#355](https://github.com/aws-amplify/amplify-console/issues/355); 
Add check on if a project is fully setup for the amplify service migration logic.

fix(amplify-provider-awscloudformation): add condition for migration

---

packages/amplify-provider-awscloudformation/lib/amplify-service-manager.js
packages/amplify-provider-awscloudformation/lib/amplify-service-migrate.js
packages/amplify-provider-awscloudformation/lib/attach-backend.js

N/A
CLI reads:
Amplify AppID found: xxx. Amplify App name is: name}
The brace was used in JS to interpolate the string, but one too many left one being
printed for no reason. Removing.

fix: remove extra curly brace in CLI output

---

packages/amplify-cli/bin/amplify
yarn.lock

ESM cache gets out of sync and causes hard to diagnose issue like the ones reported in #3199.
Disabling the caching
fix #3199

fix(cli): disable ESM cache

---

packages/amplify-e2e-tests/src/__tests__/delete.test.ts
packages/amplify-e2e-tests/src/__tests__/predictions.test.ts

- use waitFor when checking that bucket is deleted
- removed unnecessary logging from predictions test

test(amplify-e2e-tests): use waitFor on bucket deletion check

---

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js
yarn.lock

removes the fine grain auth schema option if aws cognito is not selected as an auth mode
re #2967

fix(amplify-category-api): edit auth workflow if cognito is not used

---

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-auth-transformer/src/__tests__/MultiAuth.test.ts

- fix: non-model @auth propagation fails enum fields

fix (graphql-auth-transformer): non-model @auth propagation fails enums

---

packages/amplify-velocity-template/src/compile/compile.js
packages/amplify-velocity-template/tests/return.test.js

No issue exists
When the same resolver is called several times and a `#return` directive is in the template, it stops working the second time.
This is because the same [`Compiler`](https://github.com/aws-amplify/amplify-cli/blob/6795e783c104004a2b2576f6903b35c1c6d2ed03/packages/amplify-appsync-simulator/src/velocity/index.ts#L34) is being reused and `state.stop` is not being reset before the following `render()` is called.

fix(amplify-velocity-template): #Return directive called several times

---

packages/amplify-appsync-simulator/src/__tests__/velocity/util/general-utils.test.ts
packages/amplify-appsync-simulator/src/velocity/util/general-utils.ts

Fixes #3202
Based on the [AppSync docs](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-util-reference.html) $util.error(string, string, data) and $util.appendError(string, string, data) should filter the fields of data based on the query selection set.

Filter graphql error.data based on query selection set

---

.circleci/config.yml
.circleci/local_publish_helpers.sh
.circleci/verdaccio.yaml
package.json
packages/amplify-e2e-tests/package.json
packages/amplify-e2e-tests/src/utils/index.ts

updated Amplify E2E tests to use package published to verdaccio instead of using the development
version of the packages

ci: update amplify e2e tests to use packages from verdaccio

---

packages/amplify-app/src/index.js
packages/amplify-app/src/scripts/amplify-modelgen.js
packages/amplify-app/src/scripts/amplify-push.js

fix #3396
#3396
Use amplify.cmd on windows to avoid spawn error

fix: fix amplify-app on windows

---

packages/amplify-codegen/package.json
yarn.lock

using an appsync scalar in the schema caused issues when generating data store model due to the
change in graphql-codegenerator library. Fixing the version of the lib which is known to work when
plugins use addToSchema method to extend the schema in the plugin
partial fix #3296

fix(amplify-codegen): support appsync scalars in modelgen

---

packages/amplify-appsync-simulator/src/__tests__/velocity/value-mapper/string.test.ts
packages/amplify-appsync-simulator/src/velocity/value-mapper/string.ts

Fixes #3389 
Add the following methods for JavaString:
- concat
- contains
- endsWith
- indexOf
- isEmpty
- lastIndexOf
- replace
- replaceFirst
- matches
- split
- startsWith
- substring
- toLowerCase
- toUpperCase
- trim
split() implementation has been adapted from ConduitVC/aws-utils repository (which AFAIU was the starting point for the amplify mock).

feat(amplify-appsync-simulator): implement missing string methods (#3389)

---

packages/amplify-appsync-simulator/src/resolvers/function.ts

According to docs, stash should live across functions inside a pipeline resolver. Currently, the stash returned from the requestMappingTemplate is not forwarded to the responseMappingTemplate, therefore parameters set during request are not passed through. 
Ref: https://docs.aws.amazon.com/appsync/latest/devguide/pipeline-resolvers.html#ctx-stash
This PR fixes this by forwarding the requestTemplateResult stash to the responseMappingTemplate.

fix(amplify-appsync-simulator): forward stash to responseMappingTemplate

---

packages/graphql-dynamodb-transformer/src/resources.ts
packages/graphql-transformers-e2e-tests/src/__tests__/DynamoDBModelTransformer.e2e.test.ts

Updated the resolver code not to escape nextToken in list resolver since the response object as a whole gets sanitized
fix #3411

fix(graphql-dynamodb-transformer): prevent double escape of nextToken

---

.circleci/config.yml

The build pipeline broke due to some upstream *nix OS dependencies and Java failed to install. This PR adds apt-get update before Java installation to unblock the pipeline. 

chore: add apt-get update to circle ci tasks

---

packages/amplify-app/package.json

fix #3465
#3465
Add graphql as a dependency to support amplify-frontend-javascript

fix: add graphql dependency

---

packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts
packages/graphql-connection-transformer/src/__tests__/NewConnectionTransformer.test.ts

added validation around composite sort key when used with fields. The validation prevents passing of
partial sort key to connection directives field argument

fix(graphql-connection-transformer): validate composite sortkey

---

.circleci/config.yml
.circleci/local_publish_helpers.sh

E2E tests were failing in circleci because after spawning Verdaccio the package registry values were not reset, so when a function was deployed and invoked ```npm install``` it failed to connect to the previously set Verdaccio repository url. This fix resets the urls after Amplify CLI install, so function deployment happens as normal.

chore: e2e test failure for trigger tests, update verdaccio to latest

---

.circleci/config.yml
.circleci/local_publish_helpers.sh
packages/amplify-e2e-tests/src/__tests__/amplify-app.test.ts

- Fix ```amplify-app``` related e2e setup in circle ci to fix the previous file permission issues
- Increase timeout and remove extra async statement from ```amplify-app``` e2e test
- Standardize task names in circle ci

chore: fix amplify-app related e2e execution

---

packages/amplify-e2e-tests/src/__tests__/amplify-app.test.ts
packages/amplify-e2e-tests/src/amplify-app-helpers/amplify-app-setup.ts

use amplify-app instead of npx to pull the version published to verdaccio
add integtest profile to config since default profile doesn't exist in circleCI

test: remove npx from amplify-app testing

---

.vscode/settings.json
packages/amplify-category-api/package.json
packages/amplify-category-api/provider-utils/__tests__/apigw-walkthroughs.test.js
packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.js
packages/amplify-category-function/provider-utils/awscloudformation/function-template-dir/crud-app.js.ejs
packages/amplify-category-function/provider-utils/awscloudformation/function-template-dir/serverless-app.js.ejs
yarn.lock

#3357
Adds support for path parameters in REST APIs. For example, specifying path `/item/{itemId}` will populate the params object in the resulting ExpressJS lambda with an itemId field and value corresponding to the request.
Because CFN and ExpressJS have different syntax for path parameters, there is some translation logic between the two.
Tested with both DynamoDB CRUD Lambda and ExpressJS Lambda.

feat(amplify-category-api): support path parameters in REST APIs

---

packages/amplify-storage-simulator/src/server/utils.ts

*Issue #3215
* Replacing the invalid win32 chars with "%" in the request parameters path.

fix(amplify-storage-simulator): fixes aws-amplify#3215 Invalid win chars

---

packages/amplify-app/src/index.js
packages/amplify-e2e-tests/src/amplify-app-helpers/amplify-app-validation.ts

Will create amplifyconfiguration.json and awsconfiguration.json at build time in amplify-tools android plugin

fix: add configuration.json placeholders

---

packages/amplify-appsync-simulator/src/server/operations.ts

This commit adds support for IAM-based authorization (@aws_iam) of GraphQL operations.
Previously, only API key, OpenID Connect and Cognito User Pools were supported by amplify mock. This PR adds IAM auth.

feat(amplify-appsync-simulator): add support for IAM authorization

---

packages/amplify-graphiql-explorer/src/App.tsx
packages/amplify-graphiql-explorer/src/AuthModal.tsx

Fixes #3376
This PR fixes the above mentioned issue, when only IAM authentication was configured for the GraphQL API it failed to initialize. The PR adds support for IAM authentication, when IAM is selected, then no access check will be done as mock does not support the evaluation of policies, but enables mocking of APIs with IAM auth. It augments well the #3476 PR which added the simulator side support for IAM.

fix: #3376 - AppSync Simulator with IAM fails to load

---

packages/amplify-provider-awscloudformation/lib/push-resources.js

When pushing resources, previously the code would search for cloudformation templates in the build/ folder, if the build folder exists.
This was intended for use by the API resource, but has the unintended effect of causing templates to not be found in other resource folders,
which may contain build folders but still hold their template file in the root resource directory.
To reproduce this issue, create a function and inside the function resource directory create a build/ folder.
When pushing, the cloudformation file will not be found and not uploaded to S3.
The resolve the issue, if a cloudformation file is not found inside the build folder, continue to search for templates in the root directory.
By submitting this pull request, I …

fix(amplify-provider-awscloudformation): fix template not found

---

packages/amplify-util-mock/src/storage/storage.ts

*Issue #3510 
* changed the code in storage.ts to avoid adding stackId to bucket name in mock storage

fix(amplify-util-mock): fixes #3510 bucketname error

---

packages/amplify-cli/package.json
packages/amplify-cli/src/extensions/amplify-helpers/read-json-file.js
packages/amplify-cli/src/utils/readJsonFile.ts

I'm tired to see useless error messages like `SyntaxError: Unexpected token } in JSON at position 6`
This CL improves error messaage like following:
```
JSONParseError: some.json:3:2: Unexpected token } in JSON at position 6
```

chore(cli): improve error message in readJsonFile

---

packages/graphql-connection-transformer/src/resources.ts
packages/graphql-transformers-e2e-tests/src/__tests__/NewConnectionTransformer.e2e.test.ts

Connection transformer did not support sort key that were of non string type. Fixing
fix #3403

fix(graphql-connection-transformer): support non string type in sort key

---

packages/graphql-key-transformer/package.json

jest was testing the snapshot, changed patter to include ts

test(graphql-key-transformer): fixed testing snapshot

---

packages/graphql-relational-schema-transformer/src/RelationalDBSchemaTransformer.ts
packages/graphql-relational-schema-transformer/src/RelationalDBSchemaTransformerUtils.ts
packages/graphql-relational-schema-transformer/src/__tests__/RelationalDBSchemaTransformerUtils.test.ts

Modify RDS schema transformer to match the AST generated by graphql.parse, resolving mergeTypes conflicts
fix #2510
#2510
Prevent conflicts when updating datasource by matching schema generated from RDS tables to the AST generated by parsing the current schema
-Create placeholders for empty directives/interfaces (if the current schema has directives, they won't be overwritten)
-Modify list query to use list type instead of named type

fix(graphql-relational-schema-transformer): fix add datasource update

---

packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/user-pool-group-template.json.ejs
packages/amplify-cli/src/commands/push.js
packages/amplify-provider-awscloudformation/lib/push-resources.js

1) Scope down the IAM roles assigned to user pool groups by the following condition:
'Condition': {
'StringEquals': {'cognito-identity.amazonaws.com:aud': <idpId>},
'ForAnyValue:StringLike': {'cognito-identity.amazonaws.com:amr': 'authenticated'
}
2) Implement `amplify push --force` with force as an optional parameter to trigger Cloud-formation deployments without any changes to the CFN files or going through any update flows.

fix: scoping down user pool group IAM roles and adding --force to amplify push command

---

packages/amplify-e2e-tests/src/__tests__/function.test.ts

Increase timeout to make sure lambda logs appear in cloudwatch

test(amplify-e2e-tests): increase cloudwatch timeout to 100 seconds

---

packages/amplify-codegen-appsync-model-plugin/src/scalars/index.ts

#3593
Use Java object Long instead of primitive long so that it can be set to null.

fix(amplify-codegen): use Java Long for AWSTimestamp

---

packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/user-pool-group-template.json.ejs

A bug was recently introduced into the CLI in this commit https://github.com/aws-amplify/amplify-cli/commit/e8e9322e910259e04d063883d5acbfe46a96d191
It added a condition to the Trust policy in the CloudFormation template, but unfortunately was using a literal string reference to the `IdentityPoolId` parameter instead of using a `Ref`.
This resulted in a pretty significant bug where all calls to a REST API would fail if you were using Cognito Roles.
The cloud formation template ended up looking like this: 
`"StringEquals": {"cognito-identity.amazonaws.com:aud": "somelabel123IdentityPoolId"}`
Whereas it should be:
`"StringEquals": {"cognito-identity.amazonaws.com:aud": {"Ref":"somelabel123IdentityPoolId"}}`
By submitting this pull request, …

Fix string literal to be a `Ref` in the cloud formation template

---

packages/amplify-cli/src/extensions/amplify-helpers/resource-status.js

Simplify return statements, change `i += 1` to `++i` for more idiomatic code and slightly better perf

refactor: simplify return statements, change i += 1 to ++i in for loops

---

packages/amplify-e2e-tests/src/__tests__/auth.test.ts
packages/amplify-e2e-tests/src/__tests__/migration/api.connection.migration.test.ts
packages/amplify-e2e-tests/src/__tests__/migration/api.key.migration.test.ts
packages/amplify-e2e-tests/src/utils/sdk-calls.ts

test(amplify-e2e-tests): update SDK call to use congito application ids from meta file
test(amplify-e2e-tests): assert exit code in migration tests

test(amplify-e2e-tests): assert exit code in migration tests

---

packages/amplify-e2e-tests/src/utils/pinpoint.ts

Delete pinpoint e2e test needs to expect the new analytics prompt [here](https://github.com/aws-amplify/amplify-cli/blob/b25cfd00b21416a82ecefda1f6498206ef71531b/packages/amplify-category-analytics/commands/analytics/add.js#L12)

fix(amplify-e2e-tests): fix addPinpointAnalytics to expect new prompt string

---

packages/amplify-e2e-tests/src/__tests__/analytics.test.ts
packages/amplify-e2e-tests/src/__tests__/function.test.ts

Randomize Kenisis stream name to enable concurrent execution of tests

test(amplify-e2e-tests): randomize kenisis stream name

---

packages/amplify-e2e-tests/src/__tests__/function.test.ts

Randomize the function and ddb names to support parallel test runs

test(amplify-e2e-tests): randomize ddb and fnnames

---

packages/amplify-graphql-types-generator/src/angular/index.ts

By using the utility function non-null lists will be included in the check to use an array return
type
fix #3632
#3632

fix(amplify-graphql-types-generator): use isList utility function

---

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/functionPluginLoader.ts

Previous function refactor used flatMap but we support node 10 which does not support flatmap so changing to use reduce and concat instead.

use reduce instead of flatmap for node compatibility

---

packages/amplify-e2e-tests/src/categories/codegen.ts
packages/amplify-e2e-tests/src/utils/pinpoint.ts

Update import of nexpect to use new amplify-e2e-core package

fix: update import

---

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/functionPluginLoader.ts
packages/amplify-function-plugin-interface/src/index.ts
packages/amplify-nodejs-runtime-provider/src/index.ts
packages/amplify-nodejs-template-provider/src/index.ts

Some function plugins need access to the functionName and resourceName to properly construct templates and runtimes. This exposes a ContributionRequest object that has these parameters instead of just the raw selection string.

feat(amplify-function-plugin-interface): update contribute params

---

packages/amplify-function-plugin-interface/src/index.ts
packages/amplify-nodejs-runtime-provider/src/utils/legacyBuild.ts
packages/amplify-nodejs-template-provider/amplify-plugin.json
packages/amplify-nodejs-template-provider/src/index.ts
packages/amplify-provider-awscloudformation/lib/build-resources.js
packages/amplify-python-runtime-provider/amplify-plugin.json
packages/amplify-python-runtime-provider/package.json
packages/amplify-python-runtime-provider/src/index.ts
packages/amplify-python-runtime-provider/src/util/buildUtils.ts
packages/amplify-python-runtime-provider/tsconfig.json
packages/amplify-python-template-provider/amplify-plugin.json
packages/amplify-python-template-provider/package.json
packages/amplify-python-template-provider/resources/hello-world/Pipfile
packages/amplify-python-template-provider/resources/hello-world/index.py
packages/amplify-python-template-provider/src/index.ts
packages/amplify-python-template-provider/tsconfig.json

Implements python runtime function plugin and hello world template.
Note that E2E tests will fail until they are updated with the new runtime question in the function creation flow.

feat(amplify-python-runtime-provider): implement python runtime provider

---

packages/amplify-dynamodb-simulator/index.js
packages/amplify-util-mock/src/api/api.ts
packages/amplify-util-mock/src/utils/mock-config-file.ts

Allows to configure JAVA_OPTS in a mock.json config file.
Relates to https://github.com/aws-amplify/amplify-console/pull/453.
- When the file `amplify/mock.json` exists, its contents will be passed to the DynamoDB emulator. Currently, the only supported parameter is `javaOpts`.

feat(amplify-util-mock): add mock config for JAVA_OPTS

---

packages/amplify-codegen-appsync-model-plugin/src/configs/java-config.ts

In the pre-release version of amplify-android, `com.amplifyframework.core.Immutable` has moved to `com.amplifyframework.util.Immutable`.

Android Code Gen: Update import for Immutable utility

---

packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts

when the provider-utils/awscloudformation/index.ts was refactored
the path for initTriggerEnvs was one directory traversal short.
Issue #3746
added an additional ../ to the function initTriggerEnvs amplify-category-function/provide-utils/awscloudformation/index.ts
In amplify 4.16.1 when initializing an existing amplify project and you answer No to creating a Lambda the project initializes successfully, when initializing an project with 4.17.1 it fails regardless of the answer.

updated path for amplify-category-function

---

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/cloudformationHelpers.ts

fixes #3748 fixes #3737
Correct the DynamoDB table name in lambdas that access model dynamo tables.
Before we were attempting to construct the table name using the naming schema. This updates it to directly reference the exported value from the GraphQL CFN.

fix(amplify-category-function): fix ddb table name env var

---

packages/amplify-cli/src/context-extensions.ts

The new function plugin infrastructure does not function properly on Windows; it supplies an empty directory, and the cli's context extensions assume that A) there will be a directory defined for the ejs copy job and B) it's OK to prepend the path with a "/" even when there is not a directory. On Windows, this results in paths like "/C:\Users\foo\repos...." which is invalid. This fix has the generate method check for an empty directory and only append a directory separator between the directory nd the file to be templatized when one has been supplied.

fix(cli): added logic for use of dir separator in generate()

---

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/functionPluginLoader.ts
packages/amplify-function-plugin-interface/src/index.ts

Added support for providing runtime info to template providers.
Also adds support for function runtime template packages to support more than one runtime identifier. This is originally intended to support multiple versions of the same runtime, but could also be used to add a plugin for the same kind of template across multiple runtimes.

Runtime support enhancement

---

packages/amplify-util-mock/src/CFNParser/resource-processors/appsync.ts
packages/amplify-util-mock/src/__tests__/utils/lambda/hydrate-env-vars.test.ts
packages/amplify-util-mock/src/api/api.ts
packages/amplify-util-mock/src/func/index.ts
packages/amplify-util-mock/src/utils/index.ts
packages/amplify-util-mock/src/utils/lambda/hydrate-env-vars.ts

Updated the mock lambda invoker to pass the env vars related to resources suck as API Key and
GraphQL endpoint
fix #2453 and #2690

fix(amplify-util-mock): pass env vars to lambda when invoked with mock

---

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/functionPluginLoader.ts
packages/amplify-cli/src/extensions/amplify-helpers/build-resources.js
packages/amplify-cli/src/extensions/amplify-helpers/load-runtime-plugin.js
packages/amplify-util-mock/src/func/index.ts
packages/amplify-util-mock/src/utils/lambda/loadMinimal.ts

Support `amplify function build --yes` to bypass "are you sure" prompt
Support `amplify mock function <func name> --event <path to event json>` to bypass CLI prompt for event name
Load environment substitution when parsing CFN for local function invoke
Adds a sanity check to finding runtime plugins to ensure the list is not undefined
Changes some `console.log()` lines to `context.print.info()`
Sorts runtime and template selections so that list order is deterministic (for testing)

feat: minor tweaks to multi-runtime platform changes

---

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js

New amplify update api flow:
f45c89966b0d:datstore kaustavg$ amplify-dev update api
? Please select from one of the below mentioned services: GraphQL
? Select from the options below (Use arrow keys)
❯ Walkthrough all configurations 
Update auth settings 
Enable DataStore for entire API 

feat: uplevel enabling of datastore and update of auth configs to top

---

packages/amplify-provider-awscloudformation/lib/push-resources.js

checking for truthy of exeinfo before reading forcepush
closes #3793

fix(amplify-provider-awscloudformation): push failing from mock

---

packages/amplify-go-function-runtime-provider/package.json
packages/amplify-go-function-runtime-provider/tsconfig.json
packages/amplify-go-function-template-provider/package.json
packages/amplify-go-function-template-provider/tsconfig.json
packages/amplify-nodejs-function-runtime-provider/package.json
packages/amplify-nodejs-function-runtime-provider/tsconfig.json
packages/amplify-nodejs-function-template-provider/package.json
packages/amplify-nodejs-function-template-provider/tsconfig.json

chore: fix the build for nodejs-function-runtime-provider, standardize tsconfigs, add missing @types/node package references

chore: fix the build for nodejs-function-runtime-provider, standardize tsconfigs, add missing @types/node package references

---

.circleci/config.yml
packages/amplify-cli/package.json
packages/amplify-e2e-tests/src/categories/function.ts
packages/amplify-go-function-template-provider/tsconfig.json
packages/amplify-python-function-runtime-provider/package.json
packages/amplify-python-function-template-provider/package.json
packages/amplify-python-function-template-provider/tsconfig.json

chore: enable python for e2e provider selection

chore: enable python for e2e provider selection

---

.circleci/config.yml

Test regions are centered around UTC+9, and Seattle Time is UTC-7. Setting daily test time at 14:00
UTC, so the test occurs close to mid night for the test regions, and at 7AM for Seattle.

test(cli): change the scheduled daily console test time

---

packages/amplify-app/package.json

Bump amplify-cli dependency of amplify-app to new release (4.18)

feat: bump amplify cli version in amplify-app

---

packages/amplify-e2e-core/src/index.ts

VS code jest plugin sets CI env var. This additional check prevents circle CI config from being used locally

fix: update circle ci check to not conflict with vs code jest

---

packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts
packages/amplify-function-plugin-interface/src/index.ts

#3821
Saves the template provided defaultEditorFile in the function breadcrumb and then loads in on update so the file can be opened again.
For older projects, we default to opening the function folder if no defaultEditorFile can be found
Also only set useLegacyBuild breadcrumb param if the runtime is node

fix: save default editor on add and load on update

---

packages/amplify-e2e-tests/src/__tests__/function.test.ts

Quick and dirty attempt to fix eventual consistency failures
Long-term we need to poll the kinesis stream status until it is active and the triggers are connected before firing the test event.

fix: increase kinesis and cloudwatch sleeps

---

packages/amplify-e2e-core/src/utils/nexpect.ts

fix: e2e raise test timeout because of CFN

fix: e2e raise test timeout because of CFN

---

packages/amplify-dotnet-function-runtime-provider/src/utils/package.ts

This change replaces the call to zip the dist directory with one that uses a glob '**' combined with the option to ignore the target zip file; on Windows, the zip file would occasionally contain the zipfile and cause the Lambda deployment to fail.

fix(amplify-dotnet-function-runtime-provider): packaging now uses glob

---

packages/amplify-dotnet-function-template-provider/src/providers/serverlessProvider.ts

This change removes the extra/spurious child directory that the Serverless template creates under the src folder.

fix(amplify-dotnet-function-runtime-provider): remove extra child dir

---

.circleci/local_publish_helpers.sh

Verdaccio release step started failing and bumping up the version appears to fix it.
Tested by running the "publish to verdaccio" circle ci steps locally and verifying no errors

fix: update verdaccio version

---

package.json

When we publish to verdaccio we append an -alpha to the package versions. However, this can conflict with actual alpha publishes, so change to set verdaccio version to x.y.z-verdaccio.0 which will not conflict with anything

fix: set custom verdaccio version id

---

packages/amplify-category-api/commands/api/gql-compile.js
packages/amplify-provider-awscloudformation/lib/push-resources.js
packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
packages/graphql-transformer-core/src/util/amplifyUtils.ts

#2914 #162 #185 #151
This adds an optional cli flag `--minify-stack-templates` to `amplify push` and `amplify gql-compile` commands to generate minified CloudFront templates to circumvent the 460800 bytes size limit of CloudFront templates.
This significantly reduces the size of the templates which solves issues encountered with schemas with a large number of connections, functions etc. 
```
amplify api gql-compile --minify-stack-templates
amplify push --minify-stack-templates
``` 

feat(amplify-category-api): allow minified CF stack templates

---

packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts
packages/graphql-dynamodb-transformer/src/__tests__/__snapshots__/DynamoDBModelTransformer.test.ts.snap

#3141 
If only queries are specified in a schema, the ModelAttributeTypes enum was not added to the generated schema but the enum was referenced in Input and Filter types causing failures. This change adds the ModelAttributeTypes if list operations are specified.
Also, if only get was specified in the query (and not list) we were still generating a bunch of input and filter types that are not necessary, so this PR removes that.

fix(graphql-dynamodb-transformer): add attribute type enum for queries

---

packages/amplify-dotnet-function-template-provider/resources/lambda/Serverless/FunctionHandler.cs.ejs

This PR changes the response of the Serverless template to return a JSON object and sets the Content-Type header to "application/json" so that callers can receive a valid response from API.get() "out of the box."

fix(amplify-dotnet-function-template-provider): s'less returns app/json

---

packages/amplify-nodejs-function-runtime-provider/src/utils/execute.ts

fix: pass deserialized obj to node lambda when mocking

---

packages/amplify-category-function/src/constants.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts
packages/amplify-e2e-tests/src/__tests__/__snapshots__/function.test.ts.snap
packages/amplify-e2e-tests/src/__tests__/function.test.ts

#3744
Store env vars in a set to eliminate possibility of duplicates.
Also removes JS specific syntax for listing the environment variables because we support different languages now
Add a snapshot test to ensure the expected env vars are generated in an add => update scenario

fix: remove duplicate env vars in top level comment

---

packages/amplify-provider-awscloudformation/lib/display-helpful-urls.js

#3428
Check for response type on Allowed Oauth flow when creating the hosted UI endpoint and then setting the `response_type` in the URL

fix(amplify-provider-awscloudformation): response type fix on grant

---

packages/amplify-e2e-tests/src/__tests__/__snapshots__/function.test.ts.snap
packages/amplify-e2e-tests/src/__tests__/function.test.ts
packages/amplify-e2e-tests/src/categories/function.ts

A new .NET function template was added that also needed to be added to the list in the e2e tests so that correct templates can be selected by nexpect
Also there was a random number in a snapshot test causing it to fail

fix(amplify-e2e-tests): add .NET template and remove ddb uuid

---

packages/amplify-provider-awscloudformation/lib/configuration-manager.js
packages/amplify-provider-awscloudformation/lib/setup-new-user.js

Change prompts where we ask for IAM User credentials from "input" to "password" so that the values are not printed to stdout

fix(amplify-provider-awscloudformation): hide IAM secrets on entry

---

.circleci/amplify_init.exp
packages/amplify-e2e-tests/src/categories/api.ts
packages/amplify-e2e-tests/src/categories/function.ts
packages/amplify-e2e-tests/src/configure/index.ts
packages/amplify-e2e-tests/src/configure_tests.ts
packages/amplify-e2e-tests/src/utils/selectors.ts
packages/amplify-provider-awscloudformation/lib/aws-regions.js

fix: select us-east-2 in integ tests

---

packages/amplify-e2e-tests/package.json
packages/amplify-e2e-tests/src/utils/pinpoint.ts

pinpoint is missing region mapping in e2e test when checking if pinpoint app exists

test(amplify-e2e-tests): add region mapping to e2e

---

packages/amplify-e2e-core/src/index.ts
packages/amplify-e2e-core/src/utils/retrier.ts
packages/amplify-e2e-core/src/utils/sleep.ts
packages/amplify-e2e-tests/src/__tests__/function.test.ts
packages/amplify-e2e-tests/src/init/amplifyPush.ts
packages/amplify-e2e-tests/src/init/deleteProject.ts
packages/amplify-e2e-tests/src/utils/index.ts
packages/amplify-e2e-tests/src/utils/sdk-calls.ts

Should reduce e2e test flakiness by:
1. removing sleeps() from tests and instead polling resource status to determine availability
2. there is some inconsistency between when lambda event sources report that they are active and when the lambda is actually triggered by the events. To mitigate this, the tests retry the event twice
3. On `amplify push` wait for the CFN stack to report UPDATE_COMPLETE rather than waiting for CLI output. Sometimes if a stack took a long time to provision, nexpect would timeout even though everything was fine.

test: implement retries and CFN polls in e2e tests

---

package.json

Updated proudction build to run only 3 concurrent builds in circle ci to address memory issue

ci: update build to run 3 process concurrently

---

.circleci/config.base.yml
package.json
packages/amplify-cli/package.json
packages/amplify-console-integration-tests/package.json
packages/amplify-e2e-tests/package.json
packages/amplify-graphiql-explorer/package.json
packages/amplify-graphiql-explorer/src/App.tsx
packages/amplify-graphql-docs-generator/package.json
scripts/split-e2e-tests.ts
yarn.lock

Added a script to split amplify-e2e-tests test suites into separate CircleCI jobs to make it easier
to retry the failed tests without re-running all the suites. The splitting happens as part of pre
commit hook

ci: split amplify-e2e-tests test suites into separate circleci jobs

---

packages/amplify-category-interactions/provider-utils/awscloudformation/cloudformation-templates/lex-cloudformation-template.json.ejs

Update cloudformation template to render the region mapped region in the out instead of rendering
the current AWS region

fix(amplify-category-interactions): render the correct region in CFN

---

packages/amplify-dotnet-function-template-provider/src/utils/analyticsWalkthrough.ts
packages/amplify-dotnet-function-template-provider/src/utils/dynamoDBWalkthrough.ts
packages/amplify-dotnet-function-template-provider/src/utils/eventSourceWalkthrough.ts

#4037, #4042 
Fixes incomplete porting of ddb gql/analytics walkthroughs from NodeJS templates.

fix(amplify-dotnet-function-template-provider): ddb/kinesis templates

---

packages/amplify-cli/package.json
packages/amplify-cli/src/index.ts

Will notify on every amplify call with a daily interval if an update to the CLI is available.
re #2488 
Notify if an update to the CLI is available with a daily interval.

feat: notify if a CLI update is available

---

packages/amplify-nodejs-function-template-provider/src/providers/triggerProvider.ts

#3914
Change defaultEditorFile of dynamodb trigger to correct name

fix: point editor to correct nodejs trigger template file

---

packages/amplify-go-function-runtime-provider/src/runtime.ts

*Issue #, if available:* #3892
Executable path and name should be evaluated irrespective of local build and use full executable
path to build

fix(amplify-go-function-runtime-provider): fix issue #3892

---

.circleci/config.base.yml

fix: dotnet lambda tool install was missing from base yaml file used for parallel test generation.

fix: add dotnet tool install to base yaml

---

.circleci/config.base.yml

Fix: add dotnet global tools path to $PATH

fix: add dotnet global tools path to $PATH in CI/CD

---

.circleci/config.yml
scripts/split-e2e-tests.ts

Sort the sequencing of amplify e2e tests to optimize the excution timing when splitting them as
separate jobs

ci: sort e2e tests based on execution time

---

packages/amplify-dotnet-function-runtime-provider/src/utils/build.ts
packages/amplify-dotnet-function-runtime-provider/src/utils/invoke.ts

This PR changes the build process so that mock builds generate a fresh Debug build to ensure the Lambda test tool can execute.

fix(amplify-dotnet-function-runtime-provider): added mock/debug build

---

packages/amplify-e2e-core/src/index.ts
packages/amplify-e2e-core/src/utils/index.ts

-Alphabetical ordering of exports
-Remove redundant exporting of nexpect and retry in core index
-Include appsync export in utils

test: cleaning up exports in e2e core

---

packages/amplify-dotnet-function-runtime-provider/src/utils/build.ts

aws/aws-lambda-dotnet#594
This PR modifies the behavior of the mock build to use the the "dotnet build" command under the Debug configuration, passing in the CopyLocalLockFileAssemblies property to ensure that all required runtime assemblies are in the output folder (a workaround for the referenced issue)

fix(amplify-dotnet-function-runtime-provider): mock build fix

---

packages/graphql-connection-transformer/src/__tests__/ModelConnectionTransformer.test.ts
packages/graphql-connection-transformer/src/resources.ts
packages/graphql-dynamodb-transformer/src/resources.ts
packages/graphql-elasticsearch-transformer/src/resources.ts
packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-key-transformer/src/__tests__/__snapshots__/KeyTransformer.test.ts.snap
packages/graphql-transformer-common/src/ResourceConstants.ts

For generated GraphQL queries for types, ```@searchable``` and ```@connection``` directive the default item count was 10, this default limit has been raised to 100, without specifying the ```limit``` parameter DynamoDB and ElasticSearch is queried for 100 items.

feat(amplify-category-api): change default graphql query limit to 100

---

packages/graphql-dynamodb-transformer/src/resources.ts

fix: missing rename of constant

fix: github partial rename for sync query constant

---

packages/amplify-console-integration-tests/src/pullAndInit/amplifyConsoleOperations.ts
packages/amplify-console-integration-tests/tsconfig.json

https://circleci.com/gh/aws-amplify/amplify-cli/16201?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Enable esModuleInterop and include root node_module types

chore: fix compiler errors in console integ tests

---

packages/amplify-e2e-tests/src/__tests__/delete.test.ts

Added a delay of 30 seconds for the check between tests for 'bucketNotExists'

test(amplify-e2e-tests): added delay to waitFor

---

packages/amplify-codegen/src/commands/models.js

Updated model gen to use the Applications ResDirectory to compute the output path for generated
models
fix #3993

fix(amplify-codegen): use ResDir directory to compute modelgen output

---

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts
packages/amplify-e2e-core/src/utils/retrier.ts
packages/amplify-e2e-tests/schemas/two-model-schema.graphql
packages/amplify-e2e-tests/src/__tests__/function.test.ts

#4051
The call to `getPermissionPolicies` was passing in an object of all resources that was appended to on every iteration of a loop through all of the selected resources, thus adding n^2/2 resource policies when only n were selected. Amended the call to only pass in the resource of the current iteration of the loop rather than the full list.

fix: remove duplicate permissions from resources in same category

---

packages/amplify-appsync-simulator/src/__tests__/server/subscription/websocket-server/server.test.ts
packages/amplify-appsync-simulator/src/__tests__/server/subscription/websocket-server/utils/decode-headers.test.ts
packages/amplify-appsync-simulator/src/__tests__/utils/graphql-runner/query-and-mutation.test.ts
packages/amplify-appsync-simulator/src/server/subscription/websocket-server/utils/decode-header.ts
packages/amplify-appsync-simulator/tsconfig.json
packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
packages/amplify-provider-awscloudformation/package.json
yarn.lock

Current implementation misuses createRequireFromPath API.
Unfortunately this API doesn't support directory path well.
For example,
```
createRequireFromPath("/my/project")("./node_modules/mylib")
```
isn't same as
```
require("/my/project/node_modules/mylib")
```
Actually, it's
```
require("/my/node_modules/mylib")
```

fix(amplify-provider-awscloudformation): custom transformer imports

---

packages/amplify-cli/src/commands/plugin/add.ts
packages/amplify-cli/src/commands/plugin/new.ts
packages/amplify-cli/src/plugin-helpers/create-new-plugin.ts
packages/amplify-cli/src/plugin-helpers/verify-plugin.ts
packages/amplify-cli/src/plugin-manager.ts

- fix: optimize plugin scan performance, to lazy load plugins
before:
```amplify plugin scan  5.86s user 1.58s system 89% cpu 8.327 total```
after:
```amplify-dev plugin scan  0.68s user 0.12s system 116% cpu 0.684 total```
- remove extra verification functions

perf: plugin scan perf optimization

---

packages/amplify-cli/src/init-steps/s0-analyzeProject.js

Make 'dev' the default environment name if it's a new project or doesn't exist yet

feat: make 'dev' the default envname if it's not present

---

packages/amplify-console-hosting/hosting/index.js
packages/amplify-console-integration-tests/__tests__/consoleHosting.test.ts
packages/amplify-console-integration-tests/src/consoleHosting/consoleHosting.ts
packages/amplify-console-integration-tests/src/consoleHosting/constants.ts
packages/amplify-console-integration-tests/src/consoleHosting/utils.ts

When frontend is created in Amplify Console, but hosting is not added locally, if the user execute
amplify hosting remove, this update will print out a more informative error message
fix #4086

fix(amplify-console-hosting): printout more informative message

---

packages/amplify-appsync-simulator/src/server/operations.ts

Fixed an error  when there were more than 1 operation in query document
fix #4181

fix(amplify-appsync-simulator): support more than 1 operation in query

---

packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
packages/amplify-util-mock/src/api/resolver-overrides.ts
packages/amplify-util-mock/src/api/run-graphql-transformer.ts
packages/graphql-transformer-core/src/util/amplifyUtils.ts
packages/graphql-transformer-core/src/util/transformConfig.ts

Add support for overriding pipeline function tempalte in graphql transformer. Updated mock to
support this as well
fix #4192

feat: support for overriding pipeline function templates in transformer

---

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts

Function update walkthroguh used to overwrite everything in parameter.json and
function-parameter.json when an update was done. Update flow does not account for all the
configuration options function can have and causes deletion of cognito trigger configuration.
Updated this to retain last configuration and only update the parts that have changed
fix #4065

fix(amplify-category-function): prevent overwriting of parameters

---

packages/amplify-cli/bin/amplify
packages/amplify-cli/scripts/post-install.js

perf: If CLI is running under Node 12 or later, use its new async capable module loader instead of ESM package. This change affects the overall startup time for any command.
before:
```
> time amplify -v
amplify -v  0.64s user 0.10s system 120% cpu 0.613 total
```
after:
```
> time amplify-dev -v
amplify-dev -v  0.22s user 0.05s system 108% cpu 0.249 total
```
note: version 4.18.1 because it is running on dev build.

perf: use node's async esm module loader above node>=12

---

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/envResourceParams.test.ts
packages/amplify-cli/src/extensions/amplify-helpers/envResourceParams.js

#3240
Modify saveEnvResourceParameters() to append to the existing map of environment parameters rather than overwriting them

fix: append env resource params instead of replacing them

---

packages/amplify-cli/bin/amplify
packages/amplify-cli/scripts/post-install.js

fix: revert ESM change as it failed with ES6 imports, will re-enable after TS changes and further investigations.

fix: revert esm change temporarily, it conflicts with some imports

---

packages/amplify-dotnet-function-runtime-provider/src/utils/detect.ts

#4226
Dotnet version regex matched the first version in the list rather than any version in the list. Change to match per line.

fix: match dotnet version per line

---

packages/amplify-codegen-appsync-model-plugin/src/__tests__/utils/process-connections.test.ts
packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/utils/process-connections.ts

Update modelgen to support @connection directive with `keyName`. 
related change in Amplify JS: https://github.com/aws-amplify/amplify-js/pull/5778

feat(packages/amplify-codegen-appsync-model-plugin): add support for keyName in connection

---

packages/amplify-appsync-simulator/src/__tests__/index.test.ts
packages/amplify-appsync-simulator/src/__tests__/resolvers/pipeline-resolver.test.ts
packages/amplify-appsync-simulator/src/__tests__/resolvers/unit-resolver.test.ts
packages/amplify-appsync-simulator/src/index.ts
packages/amplify-appsync-simulator/src/resolvers/base-resolver.ts
packages/amplify-appsync-simulator/src/resolvers/function.ts
packages/amplify-appsync-simulator/src/resolvers/pipeline-resolver.ts
packages/amplify-appsync-simulator/src/resolvers/unit-resolver.ts
packages/amplify-appsync-simulator/src/schema/index.ts
packages/amplify-appsync-simulator/src/type-definition.ts
packages/amplify-util-mock/src/CFNParser/appsync-resource-processor.ts
packages/amplify-util-mock/src/CFNParser/resource-processors/appsync.ts
packages/amplify-util-mock/src/api/api.ts

Updated mock to support inline resolver templates
fix #3834

fix(amplify-appsync-simulator): support inline resolver templates 

---

packages/graphql-auth-transformer/src/__tests__/__snapshots__/OperationsArgument.test.ts.snap
packages/graphql-auth-transformer/src/__tests__/__snapshots__/SearchableAuthTransformer.test.ts.snap
packages/graphql-connection-transformer/src/__tests__/__snapshots__/ModelConnectionTransformer.test.ts.snap
packages/graphql-connection-transformer/src/__tests__/__snapshots__/NewConnectionTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-dynamodb-transformer/src/ModelDirectiveArgs.ts
packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts
packages/graphql-dynamodb-transformer/src/__tests__/ModelDirectiveArgs.test.ts
packages/graphql-dynamodb-transformer/src/__tests__/__snapshots__/DynamoDBModelTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/definitions.ts
packages/graphql-dynamodb-transformer/src/resources.ts
packages/graphql-elasticsearch-transformer/src/__tests__/__snapshots__/SearchableModelTransformer.test.ts.snap
packages/graphql-key-transformer/src/__tests__/__snapshots__/KeyTransformer.test.ts.snap
packages/graphql-transformers-e2e-tests/src/__tests__/DynamoDBModelTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformerLocal.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/KeyWithAuth.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelAuthTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelConnectionTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/VersionedModelTransformer.e2e.test.ts

Expose createdAt and updatedAt automatically in the transformed schema. Added capability to change the createdAt and updatedAt field names using timestamps
```graphql
type Post @model(timestamps:{createAt: "createdOn", updateAt: "updatedOn"}) {
id: ID!
title: String!
tags: [String!]!
}
```
The above schema will generate Post with `createdOn` and `updatedOn` fields as shown
```graphql
type Post {
id: ID!
title: String!
tags: [String!]!
createdOn: AWSDateTime!
updatedOn: AWSDateTime!
}
```
fix #401
doc: https://github.com/aws-amplify/docs/pull/1678

feat: expose createdAt and updatedAt on model

---

packages/amplify-category-auth/provider-utils/awscloudformation/assets/cognito-defaults.js
packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs
packages/amplify-e2e-core/src/categories/auth.ts
packages/amplify-e2e-tests/src/__tests__/auth.test.ts

#4186
Fixes issues with creating auth pushing and then removing it and pushing a newly configured auth

fix(amplify-category-auth): create a new name when generating user roles

---

packages/amplify-util-mock/src/__e2e__/key-transformer.e2e.test.ts
packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-key-transformer/src/__tests__/__snapshots__/KeyTransformer.test.ts.snap
packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformer.e2e.test.ts

added composite sort key validation in create - udpated unit test and e2e test
re #1756

fix(graphql-key-transformer): add key validation in create

---

packages/amplify-nodejs-function-runtime-provider/package.json
packages/amplify-nodejs-function-runtime-provider/src/__tests__/utils/__snapshots__/execute.test.ts.snap
packages/amplify-nodejs-function-runtime-provider/src/__tests__/utils/execute.test.ts
packages/amplify-nodejs-function-runtime-provider/src/__tests__/utils/handlers.js
packages/amplify-nodejs-function-runtime-provider/src/utils/execute.ts
packages/amplify-util-mock/src/utils/lambda/execute.ts

Fixes #4019
Non-async Lambda handlers should only rely on the value returned by the callback function.
See https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html

fix(amplify-util-mock): non-promise lambda failing

---

packages/amplify-e2e-tests/src/__tests__/auth.test.ts

Makes sure Auth works with a long env name

test(amplify-e2e-tests): added test for creating roles with long envname

---

packages/amplify-util-mock/src/api/api.ts

Mock kept on triggering reload on windows even when there were no changes to the API. Added
additional check to ensure reload happens only if the actual content in the file has changed
fix #2736

fix(amplify-util-mock): fix API Mock inifinte reload on windows

---

packages/amplify-frontend-android/index.js
packages/amplify-frontend-android/lib/amplify-config-helper.js
packages/amplify-frontend-android/lib/frontend-config-creator.js
packages/amplify-frontend-ios/lib/amplify-config-helper.js
packages/amplify-frontend-ios/lib/frontend-config-creator.js

Create an auth block that contains the contents of awsconfiguration.json
Copy awsconfiguration.json contents into amplifyconfiguration.json according to specification in this readme: https://github.com/aws-amplify/amplify-android/tree/AuthCategory/aws-auth-cognito (step 11)

refactor: copy awsconfig into amplifyconfig

---

packages/amplify-codegen-appsync-model-plugin/src/__tests__/utils/process-auth.test.ts
packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/utils/process-auth.ts
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-swift-visitor.ts
tsconfig.base.json

Updated model gen to generate schema with auth rules

feat(amplify-codegen-appsync-model-plugin): iOS add suport for auth

---

packages/amplify-app/src/index.js
packages/amplify-app/src/xcodeHelpers.js
packages/amplify-cli/src/extensions/amplify-helpers/git-manager.js
packages/amplify-e2e-tests/src/amplify-app-helpers/amplify-app-validation.ts

**Notes:**
- change `amplifyxc.config` to `amplifytools.xcconfig` to match standard
xcode config files extension
- create an Xcode group called `AmplifyConfig` and add all
config-related files
- `amplifytools.xcconfig`
- `amplifyconfiguration.json`
- `awsconfiguration.json`
- `schema.graphql`
- create an Xcode group called `AmplifyModels` and add the generated
models to it and also as project source files
- files are added as references and not copied, so updates to the
original files are automatically reflected

feat(amplify-app): group amplify files in xcode integration

---

packages/amplify-app/src/xcodeHelpers.js

prevent xcode logic when not in an xcode project

fix: fix amplify-app ios when not in xcode project

---

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js
packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-tests/src/__tests__/api.test.ts

added option to toggle datastore for the api
re #4058

fix(amplify-category-api): toggle datastore in update

---

packages/amplify-appsync-simulator/src/__tests__/velocity/value-mapper/string.test.ts
packages/amplify-appsync-simulator/src/velocity/value-mapper/string.ts

equals method is required for VTL functionality present in the console that is currently missing in
the simulator
*Issue #4334, if available:*

fix(amplify-appsync-simulator): adds equals method to JavaString class

---

packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts
packages/graphql-connection-transformer/src/__tests__/ModelConnectionTransformer.test.ts
packages/graphql-connection-transformer/src/__tests__/__snapshots__/ModelConnectionTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/definitions.ts

#4081
The connection transformer did not add the enum type filter to connections even though the list item filter referenced it.

fix: add custom enum filter to connection filter

---

packages/amplify-appsync-simulator/src/__tests__/resolvers/pipeline-resolver.test.ts
packages/amplify-appsync-simulator/src/resolvers/pipeline-resolver.ts

AS per the doc:
> The response mapping template of a pipeline resolver or also called the After step, allows to perform some final mapping logic from the output of the last function to the expected GraphQL field type. The output of the last function in the functions list is available in the pipeline resolver mapping template as $ctx.prev.result or $ctx.result.
`$ctx.result` stopped working after #4225 
This PR resolves the issue.

fix(amplify-appsync-simulator): after pipeline template mapping

---

packages/amplify-appsync-simulator/src/server/subscription/mqtt-server/server.ts

There was "extend" dependency imported in
amplify-appsync-simulator/src/server/subscription/mqtt-server/server.ts but it was missing in
package.json
In https://github.com/bboure/serverless-appsync-simulator/issues/22 I stumbled upon error `Cannot find module 'extend'`. I've traced this error to [amplify-appsync-simulator/src/server/subscription/mqtt-server/server.ts#L5](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-appsync-simulator/src/server/subscription/mqtt-server/server.ts#L5)
I found out that the dependency `extend` is not in `package.json`. 
So accordingly to @jhockett suggestion, I've replaced the `extend` library with "extend" function from `lodash`.
By submitting this pull request, I confirm that my contribution is made under …

fix(amplify-appsync-simulator): replace "extend" library with lodash

---

packages/graphql-auth-transformer/src/__tests__/__snapshots__/OperationsArgument.test.ts.snap
packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-dynamodb-transformer/src/__tests__/__snapshots__/DynamoDBModelTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/resources.ts
packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-key-transformer/src/__tests__/__snapshots__/KeyTransformer.test.ts.snap
packages/graphql-transformers-e2e-tests/package.json
packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformerLocal.e2e.test.ts

Added support for auto population of id, createdAt and updatedAt fields even when they are part of
the primary key
fix #2671
fix #1657 

feat(graphql-key-transformer): auto population of id and timestamp

---

packages/amplify-graphql-types-generator/src/angular/index.ts
packages/amplify-graphql-types-generator/test/angular/__snapshots__/index.js.snap

https://github.com/aws-amplify/amplify-cli/issues/4419
As of 3.0.13, aws-amplify is using `zen-onservable-ts`. (See: https://github.com/aws-amplify/amplify-js/commit/49d295eee25d287ad705d878facf07bd6a3cfab9)
While upgrading our project, which was using aws-amplify 2.x.x, our TypeScript failed to compile.
As soon as I make the changes that are part of this PR,  to thé API service generated by thé CLI, TypeScript compilation is succesfull again.
This PR is a first draft for further discussing. I can update the PR accordingly.

fix(amplify-graphql-types-generator): use zen-observable-ts

---

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-auth-transformer/src/__tests__/MultiAuth.test.ts

fix: #3910 - propagate non-model auth to nested types
For non-model types then the 1st level type had nested non-model types, @auth was not propagated properly on nested types.

fix: #3910 - propagate non-model auth to nested types

---

packages/amplify-provider-awscloudformation/lib/push-resources.js
packages/amplify-provider-awscloudformation/package.json

fix: #3096 - glob *template*.+(yaml|yml|json) files only as cfn template
Strict and proper globbing or file patterns when looking for cloudformation templates in category directories.
For non-model types then the 1st level type had nested non-model types, @auth was not propagated properly on nested types.

fix: #3096 - glob *template*.+(yaml|yml|json) files only as cfn template

---

packages/amplify-category-function/package.json
packages/amplify-category-function/resources/awscloudformation/cloudformation-templates/lambda-function-cloudformation-template.json.ejs
packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/addLayerToFunctionWalkthrough.test.ts
packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/addLayerToFunctionUtil.test.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/addLayerToFunctionWalkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/addLayerToFunctionUtils.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerArnConverter.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/stubLayerMetadataFactory.ts
packages/amplify-e2e-core/src/categories/lambda-function.ts
packages/amplify-e2e-core/src/categories/lambda-layer.ts
packages/amplify-e2e-tests/src/__tests__/__snapshots__/function.test.ts.snap
packages/amplify-e2e-tests/src/__tests__/function.test.ts
packages/amplify-function-plugin-interface/src/index.ts
yarn.lock

also added a boatload of tests
because all of the changes for storing state regarding LL is not implemented yet, I stubbed out retrieving the LL version into a factory function that can easily be updated with the real implementation later.
Also, because pushing LL doesn't work yet, the e2e test for adding layers to functions just tests that the right stuff is added in the CFN template.

feat: add and update layers on functions

---

packages/amplify-nodejs-function-template-provider/resources/lambda/crud/index.js
packages/amplify-nodejs-function-template-provider/resources/lambda/serverless/index.js
packages/amplify-nodejs-function-template-provider/resources/lambda/trigger/trigger-dynamodb.js
packages/amplify-nodejs-function-template-provider/resources/lambda/trigger/trigger-kinesis.js

#3995
The serverless and crud node templates used a deprecated version of `awsServerlessExpress.proxy()` which called the deprecated `context.succeed()` lambda operation under the hood. This updates to use the newer `proxy()` function call that returns a promise.
Also replaced the deprecated `context.done()` calls in the dynamo and kinesis trigger templates with promises.

fix: remove use of deprecated context.done() and context.succeed()

---

packages/amplify-nodejs-function-runtime-provider/src/__tests__/utils/__snapshots__/execute.test.ts.snap
packages/amplify-nodejs-function-runtime-provider/src/utils/execute.ts

- `_.assign` on an `Error` removes all the fields.
- `JSON.stringify()` also does not work on Errors (serializes to empty object).
This lead to errors becoming empty when reaching the response template, and the following would not work:
````vtl
#if($context.error)
$util.error($context.error.message, $context.error.type)
````

fix(amplify-nodejs-function-runtime-provider): unhandled errors

---

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-java-visitor.ts

*Issue #, if available:* https://github.com/aws-amplify/amplify-android/issues/555
*Description of changes:* Add delimiter in Android `toString` output
Generated models include a `toString` method which isn't optimally human readable. The model attribute's value is concatenated with the next field's key name.
Instead, insert a comma as a delimiter in our calls to `append` on all but the last field.

fix(amplify-codegen-appsync-model-plugin): Add delimiter in Android `toString` output

---

packages/amplify-frontend-ios/lib/frontend-config-creator.js

fix #4519
Prevent root files being deleted when generatedfilename is empty

fix: do not delete if generated filename is empty

---

packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
packages/amplify-provider-awscloudformation/lib/upload-appsync-files.js
packages/amplify-provider-awscloudformation/src/aws-utils/aws-s3.js
packages/graphql-transformer-core/package.json
packages/graphql-transformer-core/src/util/amplifyUtils.ts
packages/graphql-transformer-core/src/util/fileUtils.ts

perf: optimize appsync file upload to use globbing to collect the files and upload all the files in parallel
perf: cache environment and bucket name for S3 operations
perf: optimize bucket exist check to use head operation instead of list and filtering
chore: remove duplicated hashing function
Test schema with 20 simple @model types ~300 files.
before: 2 minutes 19 seconds 
after: 2.9 seconds

perf: optimize appsync file upload and bucket exist check

---

packages/amplify-provider-awscloudformation/lib/display-helpful-urls.js

Closes: #3919
`amplify status` will show the endpoint url for the REST API if exist in the project. The first part of the URL is the actual API Id that was requested in the feature.

feat: show rest api url on amplify status

---

packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/configure-Publish.js
packages/amplify-cli/src/attach-backend.js
packages/amplify-cli/src/extensions/amplify-helpers/delete-project.js
packages/amplify-cli/src/extensions/amplify-helpers/get-project-meta.js
packages/amplify-cli/src/extensions/amplify-helpers/path-manager.js
packages/amplify-cli/src/extensions/amplify-helpers/resource-status.js
packages/amplify-cli/src/migrate-project.js
packages/amplify-codegen/src/constants.js

fix: #4549 #4550
- Remove duplicated error message about uninitialized environment, enrich the error with name, clear stack from error, without stack customers are seeing a friendlier error message without tech details 
- Add check for backup folder existence to prevent further errors
- Remove unused error message constant

fix: #4549 #4550 init and folder exist checks

---

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/preset.ts
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-swift-visitor.ts

- Renamed `customType` to `embedded(type)` and `embeddedCollection(of)`
- Adds support in `amplify codegen models` to generate Extensions for embedded types

fix(amplify-codegen-appsync-model-plugin):  Support Embeddable Types for iOS 

---

packages/amplify-app/src/xcodeHelpers.js

check if resources group exists and add it iff it does not
fix #4518
get or create resources logical group instead of adding and then removing it

fix: do not remove resources group

---

packages/amplify-nodejs-function-runtime-provider/src/__tests__/utils/legacyBuild.test.ts
packages/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts

#4479
fIx glob pattern and filter to include files in the root of the function directory when determining a stale build

fix: nodejs staleBuild glob

---

packages/amplify-cli/src/extensions/amplify-helpers/delete-project.js

#4579 
After running `$ amplify delete`, an "are you sure you want to continue" prompt appears. This PR proposes to change that prompt's default response value from "yes" to "no."

feat: change `amplify delete` prompt default value from yes to no

---

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/addLayerToFunctionUtil.test.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/addLayerToFunctionUtils.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerParams.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts
packages/amplify-dotnet-function-runtime-provider/src/index.ts
packages/amplify-e2e-core/src/categories/lambda-layer.ts
packages/amplify-go-function-runtime-provider/src/index.ts
packages/amplify-java-function-runtime-provider/src/index.ts
packages/amplify-nodejs-function-runtime-provider/src/index.ts
packages/amplify-python-function-runtime-provider/src/index.ts

Prompt user for previous/default permissions on new layer version created during push
Fix default files being rewritten to disk every time a version update occurred. They are only created when the directory structure is also created.

feat: Prompt user for previous/default permissions on new layer version created during push

---

.eslintrc.js
packages/amplify-cli/templates/plugin-template-frontend/index.js
packages/amplify-frontend-javascript/lib/publisher.js

Updated lint rule to throw error when and undefined variable is used in code. Update the offending
code to adhere to this rule

chore: update lint rule to fail on undefined variables

---

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js
packages/amplify-category-auth/package.json
packages/amplify-category-auth/provider-utils/awscloudformation/index.js
packages/amplify-category-function/src/commands/function/remove.ts
packages/amplify-category-function/src/index.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/cloudformationHelpers.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/constants.ts
packages/amplify-category-function/src/provider-utils/supported-services.ts
packages/amplify-category-function/src/provider-utils/supportedServicesType.ts
packages/amplify-category-predictions/package.json
packages/amplify-category-predictions/provider-utils/awscloudformation/prediction-category-walkthroughs/identify-walkthrough.js
packages/amplify-category-storage/package.json
packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js
packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js
packages/amplify-cli/src/extensions/amplify-helpers/trigger-flow.js
packages/amplify-cli/tsconfig.json
packages/amplify-dotnet-function-runtime-provider/amplify-plugin.json
packages/amplify-dotnet-function-template-provider/amplify-plugin.json
packages/amplify-e2e-tests/src/__tests__/api.test.ts
packages/amplify-go-function-runtime-provider/amplify-plugin.json
packages/amplify-go-function-template-provider/amplify-plugin.json
packages/amplify-java-function-runtime-provider/amplify-plugin.json
packages/amplify-java-function-template-provider/amplify-plugin.json
packages/amplify-nodejs-function-runtime-provider/amplify-plugin.json
packages/amplify-nodejs-function-template-provider/amplify-plugin.json
packages/amplify-python-function-runtime-provider/amplify-plugin.json
packages/amplify-python-function-template-provider/amplify-plugin.json
packages/amplify-util-mock/src/__tests__/utils/lambda/hydrate-env-vars.test.ts
packages/amplify-util-mock/src/mockAll.ts

Prevents breaking Lambda layers for existing Lambda functions

fix: revert service name 'LambdaFunction' to 'Lambda'

---

packages/amplify-category-function/package.json
packages/amplify-category-function/src/index.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerParams.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts
packages/amplify-cli/src/extensions/amplify-helpers/resource-status.js
packages/amplify-e2e-tests/src/__tests__/layer.test.ts
packages/amplify-nodejs-function-runtime-provider/src/index.ts
yarn.lock

slightly hacky method for using the layer hashing function for amplify status if the resource is a layer
also fixed the pretty-printing of the default package.json that gets put in the layer folder and only storing necessary layer properties in amplify-meta.json and layer-parameters.json
and a few other housekeeping things

fix: use same hashing func for amplify status and layer hash

---

packages/amplify-category-function/package.json
packages/amplify-category-function/src/index.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambdaLayerWalkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/addLayerToFunctionUtils.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/lambda-layer-cloudformation-template.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerParams.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts
packages/amplify-cli/src/extensions/amplify-helpers/resource-status.js
packages/amplify-e2e-core/src/categories/lambda-layer.ts
packages/amplify-e2e-core/src/utils/selectors.ts
packages/amplify-e2e-tests/src/__tests__/layer.test.ts

Moved a lot of the logic for maintaining layer state to the layer state class
Call "syncVersions()" when we need to check if a new layer version has been created outside of a CLI flow
also did a significant refactor of the layer update flow
still need to check the  e2e tests -- they probably need to be updated with the new update flow (moved the order of one question)

feat: reflect proper layer versions without push

---

.circleci/config.yml
packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts
packages/amplify-e2e-core/src/categories/lambda-layer.ts
packages/amplify-provider-awscloudformation/lib/push-resources.js

Also remove unused import, show "updated" on `amplify update function`, updated relevant e2e helper functions

fix: display relative paths on success output for layers

---

packages/amplify-e2e-core/src/categories/lambda-function.ts

fixes e2e test failure in "should fail with approp message when adding lambda triggers to unexisting resources" test

test: early return on function flow expect failure

---

packages/amplify-category-function/package.json
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/updateTopLevelComment.ts

Fixes functions e2e test "environment vars comment should update on permission update"

fix: env vars comment on func update

---

.circleci/enable_api.exp
packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts

fixes AWS::Region being added as a CFN parameter causing e2e failure
fixes function addResource not returning resourceName
adds lambda layer question to cypress test flow

fix: remove env and region from dependsOn

---

packages/amplify-category-auth/index.js
packages/amplify-category-auth/provider-utils/awscloudformation/index.js
packages/amplify-cli/src/attach-backend.js
packages/amplify-console-integration-tests/__tests__/pullAndInit.test.ts
packages/amplify-console-integration-tests/src/pullAndInit/amplifyConsoleOperations.ts
packages/amplify-console-integration-tests/src/pullAndInit/pullProject.ts
packages/amplify-e2e-core/src/categories/auth.ts
packages/amplify-e2e-core/src/utils/envVars.ts
packages/amplify-e2e-core/src/utils/index.ts
packages/amplify-e2e-core/src/utils/projectMeta.ts
yarn.lock

https://github.com/aws-amplify/amplify-console/issues/206
https://github.com/aws-amplify/amplify-cli/issues/3642
- This allows authConfig (inside Categories) to be passed into headless pull.
- When doing a pull with hostedUI enabled the pull will prompt for the social provider info
- Removed error log from `attach-backend` as this a duplicate error that is logged.
- added e2e tests for headless and question pull workflow 

Allow AuthConfig to be passed into headless pull

---

packages/amplify-category-api/package.json
packages/amplify-category-api/src/index.ts
packages/amplify-category-api/tsconfig.json
packages/amplify-cli/src/domain/constants.ts
packages/amplify-cli/src/execution-manager.ts
packages/amplify-cli/src/utils/headless-input-utils.ts

includes a small refactor of the executeAmplifyHeadlessCommand in the CLI to eliminate code duplication between the existing method of invoking plugins and invoking them in headless mode.

feat: headless add api working e2e

---

packages/amplify-category-function/src/index.ts

fix: isMockable() handles Lambda functions without dependsOn array

---

packages/amplify-category-function/src/__tests__/index.test.ts
packages/amplify-category-function/src/index.ts

#4770, #4774
Filter result of `amplify.getResourceStatus` to only include function resources

fix: filter init env resources by function category

---

packages/amplify-cli/src/extensions/amplify-helpers/remove-resource.js
packages/amplify-cli/src/utils/headless-input-utils.ts

Implement headless mode for remove resource. Just implemented a --yes check on the removal confirmation prompt
Also, had to change the headless flag from --yes to --headless because overloading --yes causes the headless plugin entry to execute regardless of the command.

feat: implement headless remove resource

---

packages/amplify-cli/src/attach-backend.js
packages/amplify-cli/src/initialize-env.js

throw pull error when running into issues on attaching backend and move spinner back until
categories are initialized to show success message

fix(cli): throw error on attach backend

---

packages/amplify-category-auth/provider-utils/awscloudformation/utils/trigger-file-uploader.js
packages/amplify-category-auth/tests/commands/push.test.js
packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/file-uploader.js

#4158 
When uploading multiple files to S3 after running `$ amplify publish`, those uploads are handled one after the other when they could be handled concurrently. Rather than fulfilling promises to upload each file sequentially, this PR proposes that we let the node runtime handle fulfilling those promises concurrently with `Promise.all()`.

perf: fulfill promises to upload files to S3 concurrently

---

packages/amplify-cli/src/__tests__/commands/delete.test.ts
packages/amplify-cli/src/commands/delete.js

#4115 
Since `$ amplify delete` is a sensitive and dangerous command, there should be checks in place to ensure that users truly mean to execute it. `$ amplify delete` may be confused with `$ amplify remove <category>`. If `$ amplify delete` is executed with any additional command line arguments, then an error message should be displayed indicating that the `delete` command does not accept any arguments, and a suggestion should be printed that asks the user if they meant to use the `remove` command instead of `delete`.

feat: add check for extra command line args provided with amplify delete

---

packages/amplify-cli/src/extensions/amplify-helpers/build-resources.js
packages/amplify-python-function-runtime-provider/src/util/buildUtils.ts
packages/amplify-python-function-runtime-provider/src/util/pyUtils.ts

changed execa, removed outputOnStderr as it's not needed for py3, remove console.log from build
process since the err is thrown
ref #4621

fix(amplify-python-function-runtime-provider): change exec to execa

---

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/addLayerToFunctionWalkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/permissionMapUtils.ts
yarn.lock

`amplify update function` was not correctly loading previously selected values and would overwrite
other values as a result
Added filter selecting permissions to prevent adding layers or a function to itself
#4785

fix: update function not loading previous selections

---

packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-auth-transformer/src/__tests__/MultiAuth.test.ts
packages/graphql-auth-transformer/src/constants.ts

allow auth progation to recursive types - once auth has been added to a non model type it will not
re-add auth to said type
re #4631

fix(graphql-auth-transformer): allow auth progation to recursive types

---

packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts
packages/graphql-connection-transformer/src/__tests__/ModelConnectionTransformer.test.ts
packages/graphql-connection-transformer/src/resources.ts
packages/graphql-transformer-common/src/definition.ts

re #4236
- throw an invalid directive error if the primary/sort field does not exist in the related type
- remove unused imports
- update definition for `attributeTypeFromScalar` function

fix(graphql-connection-transformer): error if field not in relatedType

---

packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js
packages/amplify-e2e-core/src/categories/api.ts
packages/graphql-auth-transformer/src/resources.ts

added a time delay to the expiration date
re #4460

fix(graphql-auth-transformer): add a time delay when creating apiKey

---

packages/amplify-console-hosting/utils/table-utils.js

added a null check for prefix on domain so that it no longer prints null when not existing
fix #4737
#4737
Added a simple null check that should avoid the error described in the issue.
PS: I only changed rows 44-48 the rest I assume was auto-linted on commit/push?

fix(amplify-console-hosting): added a null check for prefix on domain

---

packages/amplify-codegen/commands/codegen/codegen.js

fix spelling mistake in `amplify codegen --help` output

fix: codegen statements spelling mistake

---

packages/amplify-cli/src/commands/env/import.js

fix #3569
*Issue #, if available:* #3569
When using the 'amplify env import', check that passed in config object exists and has expected properties before creating new env.

fix: Check that config object exists before creating new env

---

packages/amplify-cli/src/initialize-env.js
packages/amplify-e2e-core/src/utils/envVars.ts

stopping the spinner before running category init tasks since the spinner can swallow outputs (such
as questions via inquirer)
related issue: https://github.com/sindresorhus/ora/issues/90
re #4795
change type to intersection type in e2e

fix(cli): moving the spinner above category initialization tasks

---

packages/amplify-category-analytics/provider-utils/awscloudformation/service-walkthroughs/pinpoint-walkthrough.js

Adds /* resource to the policy document to allow the sendMessages API method to work correctly.
https://github.com/aws-amplify/amplify-cli/issues/4844
Adds another resource to the policy document to allow the Pinpoint.sendMessages API method to work correctly. See the issue raised here: https://github.com/aws-amplify/amplify-cli/issues/4844 

fix(amplify-category-analytics): adds another resource to the policy doc

---

packages/amplify-appsync-simulator/src/velocity/index.ts
packages/amplify-util-mock/src/__e2e__/model-auth-transformer.e2e.test.ts
packages/amplify-util-mock/src/__e2e__/per-field-auth-tests.e2e.test.ts
packages/amplify-util-mock/src/__e2e__/versioned-model-transformer.e2e.test.ts
packages/graphql-auth-transformer/src/ModelAuthTransformer.ts
packages/graphql-auth-transformer/src/__tests__/PerFieldAuthArgument.test.ts
packages/graphql-auth-transformer/src/__tests__/__snapshots__/OperationsArgument.test.ts.snap
packages/graphql-auth-transformer/src/__tests__/__snapshots__/PerFieldAuthArgument.test.ts.snap
packages/graphql-auth-transformer/src/resources.ts
packages/graphql-connection-transformer/src/resources.ts
packages/graphql-dynamodb-transformer/src/__tests__/__snapshots__/DynamoDBModelTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/resources.ts
packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-key-transformer/src/__tests__/__snapshots__/KeyTransformer.test.ts.snap
packages/graphql-mapping-template/src/dynamodb.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelAuthTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/PerFieldAuthTests.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/VersionedModelTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/stringSetMutations.ts

- update resolver config to 2018 for better error handling on failed operations
- return errorType for ver 2018 resolvers
- previously for 2018 the error type was null
- additive update on e2e and mock e2e tests

Update Resolver Ver in @model

---

packages/amplify-category-api/src/index.ts
packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/__snapshots__/storeResources.test.ts.snap
packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/loadFunctionParameters.test.ts
packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/storeResources.test.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/loadFunctionParameters.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts

#4849
Remove "mutableParametersState" from the JSON object that is stored in function-parameters.json
When reading the file, check for that field and flatten the contents into the root object if present

fix: remove mutableParametersState from stored function-params

---

package.json
packages/amplify-appsync-simulator/package.json
packages/amplify-category-api/package.json
packages/amplify-category-auth/package.json
packages/amplify-category-hosting/package.json
packages/amplify-category-notifications/package.json
packages/amplify-category-xr/package.json
packages/amplify-cli/package.json
packages/amplify-codegen-appsync-model-plugin/package.json
packages/amplify-codegen/package.json
packages/amplify-dynamodb-simulator/package.json
packages/amplify-frontend-ios/package.json
packages/amplify-graphql-docs-generator/package.json
packages/amplify-graphql-types-generator/package.json
packages/amplify-nodejs-function-runtime-provider/package.json
packages/amplify-util-mock/package.json
packages/amplify-velocity-template/package.json
packages/graphql-auth-transformer/package.json
packages/graphql-connection-transformer/package.json
packages/graphql-dynamodb-transformer/package.json
packages/graphql-http-transformer/package.json
packages/graphql-mapping-template/package.json
packages/graphql-relational-schema-transformer/package.json
packages/graphql-transformer-common/package.json
packages/graphql-transformer-core/package.json
packages/graphql-versioned-transformer/package.json

Our current method of running "test-ci" to run unit tests in circle ci was missing many packages because not all of them define a "test-ci" script. Updated the root "test-ci" lerna command to run "test" with the [--ci](https://jestjs.io/docs/en/cli#--ci) jest option. This will ensure that as we add new packages we don't have to remember to add a "test-ci" command in order to have them picked up on circle ci runs.
Also removed the "test-ci" script in the packages where it was defined because it's no longer needed

chore: fix test-ci script to run all unit tests

---

packages/amplify-category-function/src/index.ts
packages/amplify-go-function-runtime-provider/resources/localinvoke/main.go
packages/amplify-util-mock/package.json

re aws-amplify#4487
- Changed go local invoke function
- Added check to see if resourceName exists when checking if function is mockable

fix(amplify-category-function): allow response object when runnning go local invoke

---

packages/amplify-appsync-simulator/package.json
packages/amplify-appsync-simulator/src/__tests__/resolvers/unit-resolver.test.ts
packages/amplify-appsync-simulator/src/data-loader/index.ts
packages/amplify-appsync-simulator/src/data-loader/lambda/index.ts
packages/amplify-appsync-simulator/src/resolvers/unit-resolver.ts
yarn.lock

Fixes #4404
Implements, `BatchInvoke` for lambda resolvers.
Payloads are batched by `parentType` and `fieldName`

feat(amplify-appsync-simulator): implement BatchInvoke

---

packages/amplify-nodejs-function-runtime-provider/src/utils/invoke.ts

I usually print out some logs in my Lambda functions for debugging purpose.
Since https://github.com/aws-amplify/amplify-cli/pull/4906, the logs are gone in the terminal.
This PR restores them.

fix(amplify-nodejs-function-runtime-provider): restore console.log

---

.circleci/config.yml
packages/amplify-cli/src/index.ts
packages/amplify-e2e-core/src/init/initProjectHelper.ts
packages/amplify-e2e-tests/src/__tests__/init.test.ts

Fixes #4950
When `.gitignore` does not have the `amplify/.config/local-*` files excluded - which is added by the CLI during init - and it gets checked into source control, then Amplify CLI can fail when the persisted project path is not matching the current one. This easily happens in CI/CD scenarios. This fix makes an additional check on the existence of the project directory.

fix: #4950 amplify cli fails with checked in local settings

---

.circleci/config.yml
packages/amplify-category-function/src/index.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts
packages/amplify-e2e-tests/src/__tests__/function_1.test.ts
packages/amplify-nodejs-function-runtime-provider/package.json

Previously, if answering 'no' to "Do you want to update the Lambda function permissions to access
other resources in this project?", the function's dependencies would be removed. Now, permissions
must be removed explicitly by answering 'yes' to the question and the relevant permissions have to
be deselected.
#4932, #4852, #4892

fix: function update no longer removes dependsOn array implicitly

---

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/resolver-config-to-conflict-resolution-bi-di-mapper.test.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/resolver-config-to-conflict-resolution-bi-di-mapper.ts
packages/amplify-e2e-tests/src/__tests__/api_1.test.ts

Skip writing resolver config to transform.conf if return object is empty
#4965

fix(amplify-category-api): skip writing resolver config

---

.circleci/config.yml
packages/graphql-transformer-core/src/__tests__/util/__snapshots__/syncUtils.test.ts.snap
packages/graphql-transformer-core/src/__tests__/util/syncUtils.test.ts
packages/graphql-transformer-core/src/util/syncUtils.ts

There were 2 issues with the generated lambda resolver CFN. 1. the env map had an ";" in the key causing a CFN error and the SyncConfig of the AWS::AppSync::Resolver was malformed. see: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-resolver-syncconfig.html#cfn-appsync-resolver-syncconfig-lambdaconflicthandlerconfig

fix: lambda resolver CFN syntax

---

packages/graphql-elasticsearch-transformer/scripts/ddb_to_es.py

fix migration script to use key schema over attribute definitions
re #3786

fix(graphql-elasticsearch-transformer): fix script to use keyschema

---

packages/graphql-auth-transformer/src/resources.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelAuthTransformer.e2e.test.ts

resolves #5018
Sets a default owner value of an empty array to compare against when the owner field is null

fix(graphql-auth-transformer): fix null owner auth assignment

---

.circleci/config.yml
packages/amplify-category-function/src/__tests__/__snapshots__/index.test.ts.snap
packages/amplify-category-function/src/__tests__/index.test.ts
packages/amplify-category-function/src/index.ts

*Issue #4992 *
* Changed the logic to mock functions with layers when dependency on a function

fix: change logic to separate functions from layers in mock

---

packages/amplify-appsync-simulator/src/velocity/util/general-utils.ts
packages/amplify-util-mock/src/__e2e__/dynamo-db-model-transformer.e2e.test.ts

return null if on util.toJson if the value does not exist
re #5003

fix(amplify-appsync-simulator): fix returning null on nonexistent fields in util.toJson

---

packages/amplify-app/package.json

fix #4272
#4272
When running amplify status on a project created with amplify-app with the latest CLI a stacktrace will no longer be shown and a message will be shown that init must be run.

chore: bump min cli to latest for stacktrace removal

---

packages/amplify-util-mock/src/__tests__/utils/index.test.ts
packages/amplify-util-mock/src/utils/index.ts

#5044 
- Change regexp to make a Java's first major version(it is only number `14` if it is `openjdk 14.0.0`) able to run mock server.
- Fix the check expression in `checkJavaVersion`, for Java 7 not to pass, and for Java N and Java A.B.C to pass.
- Add tests for these changes.

fix wrong Java version check

---

packages/amplify-nodejs-function-runtime-provider/package.json
packages/amplify-nodejs-function-runtime-provider/src/utils/execute.ts
yarn.lock

#4439
As per NodeJs doc: 
> Calling process.exit() will force the process to exit as quickly as possible even if there are still asynchronous operations pending that have not yet completed fully, including I/O operations to process.stdout and process.stderr.
This causes sometimes [the output](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-nodejs-function-runtime-provider/src/utils/invoke.ts#L23) to be truncated, making `JSON.parse` fail, when the output has not been completely processed.
I changed `process.exit` for https://github.com/cowboy/node-exit which ensures that stdout is fully drained.
After testing it, this solution seems to work.
Credits: This comment helped: …

Fix truncated results

---

packages/amplify-python-function-runtime-provider/src/util/pyUtils.ts

N/A
`getPipenvDir` failed under Windows since process output had a `\r` appended so `path.join` generated some obscure path which made python functions fail. This regression was introduced in 4.24.1 by this [PR](https://github.com/aws-amplify/amplify-cli/pull/4673) and only affected Windows.

fix: trim process stdout in python runtime provider

---

packages/amplify-category-api/resources/awscloudformation/cloudformation-templates/apigw-cloudformation-template-default.json.ejs
packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/__snapshots__/legacy-add-resource.test.ts.snap
packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/legacy-add-resource.test.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/legacy-add-resource.ts

#4492
When a REST API path contained a path parameter (`/path/{param}`) and this API had an IAM policy associated with it, we were putting this path directly in the resource of the policy, meaning it would never match. This PR replaces {param} path components in the policy resource with a wildcard (*).

fix: sub * for path parms in CFN policy

---

packages/amplify-util-mock/src/__tests__/api/lambda-arn-to-config.test.ts
packages/amplify-util-mock/src/api/api.ts
packages/amplify-util-mock/src/api/lambda-arn-to-config.ts

#4438 
Before we were assuming that the lambda ARN was a string of a certain format and extracting the lambda name from it.
Now there is some logic to account for strings as well as Fn::Sub and Fn::GetAtt references to lambdas when initializing the lambda resolvers in mock. It is probably not comprehensive, but it should cover most cases

fix: match Fn::GetAtt and Fn::Sub when initializing lambda resolvers

---

packages/amplify-cli-core/src/state-manager/stateManager.ts
packages/amplify-cli/src/attach-backend-steps/a40-generateFiles.ts
packages/amplify-cli/src/commands/pull.ts
packages/amplify-console-integration-tests/__tests__/pullAndInit.test.ts

This PR fixes the 2 failing nightly console integration tests, which caused by a missing condition during attach backend. 
- add missing condition check during attach backend
- add missing awaits to console test cleanup
- fix typo in `projectPath`

chore: fix state management for pull

---

packages/amplify-category-api/package.json
packages/amplify-category-api/src/commands/api/add-graphql-datasource.js
packages/amplify-codegen-appsync-model-plugin/package.json
packages/amplify-codegen-appsync-model-plugin/src/plugin.ts
yarn.lock

Fix these npm warnings
```
npm WARN deprecated merge-graphql-schemas@1.7.8: Merge GraphQL Schemas has been deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-merge-graphql-schemas for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
npm WARN deprecated @graphql-toolkit/common@0.9.7: GraphQL Toolkit is deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-toolkit for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
```
replace …

refactor: replace deprecated dependencies

---

.circleci/config.yml
packages/amplify-cli-core/src/__tests__/tags.test.ts
packages/amplify-cli-core/src/index.ts
packages/amplify-cli-core/src/state-manager/pathManager.ts
packages/amplify-cli-core/src/state-manager/stateManager.ts
packages/amplify-cli-core/src/tags/Tags.ts
packages/amplify-cli-core/src/tags/index.ts
packages/amplify-cli/src/domain/amplify-toolkit.ts
packages/amplify-cli/src/extensions/amplify-helpers/constants.ts
packages/amplify-cli/src/extensions/amplify-helpers/get-tags.ts
packages/amplify-cli/src/extensions/amplify-helpers/resource-status.ts
packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts
packages/amplify-cli/src/init-steps/s9-onSuccess.ts
packages/amplify-e2e-core/src/utils/projectMeta.ts
packages/amplify-e2e-tests/src/__tests__/tags.test.ts
packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js

Enable to customers to add tags using `/amplify/backend/tags.json` file

feat: resource Tagging Support

---

packages/graphql-elasticsearch-transformer/streaming-lambda/python_streaming_function.py
packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformer.e2e.test.ts

Updated the streaming lambda function support to handle non string type in key directive fields
fix #5140

fix(graphql-elasticsearch-transformer): to support non string key in es

---

packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts
packages/graphql-dynamodb-transformer/src/__tests__/__snapshots__/DynamoDBModelTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/definitions.ts
packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-key-transformer/src/__tests__/KeyTransformer.test.ts

Updatd graphql-dynamodb-transformer to automatically add id to the model when
id is missing in the type. Id will not be added if `@key` directive changes
the primary index
fix #4502 

fix(graphql-dynamodb-transformer): support model without id

---

packages/amplify-provider-awscloudformation/lib/configuration-manager.js

(fix) url of docs on AWS CLI profiles has changed
just updating a URL so it doesnt link users to a path that doesnt exist (though it is covered by a redirect for now)

fix: url of docs on AWS CLI profiles has changed

---

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/get-env-info.test.ts
packages/amplify-cli/src/extensions/amplify-helpers/get-env-info.ts

Fixes: #4970
Description of changes: Provide empty stack with `UndeterminedEnvironmentError `to show only error message.

fix(cli): do not display stack trace on env list

---

packages/amplify-storage-simulator/src/server/S3server.ts
packages/amplify-storage-simulator/src/server/utils.ts

#4222 
- return correct keys for objects
- fix slash/backslash in returned keys for objects when it has them
- handle 404 for folders to return correctly instead of 'error' message in console and no response on the wire
- add `text/xml` content type for all responses where XML is being returned
- change `fs` and `path` imports to `* as` syntax

fix: #4222 - mock S3 list returns undefined keys under Windows

---

packages/amplify-category-auth/src/index.js
packages/amplify-category-auth/src/provider-utils/awscloudformation/handlers/get-add-auth-handler.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/post-add-auth-message-printer.ts

Internal calls to add auth use a different entry point into the category which had some logic that was duplicated since the refactor

fix: internal add auth entry point

---

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerParams.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts

The CLI was incorrectly looking for layer-runtimes.json when layer-parameters.json was present
#5250 

fix: migration issue with layers created before 4.29.0

---

packages/amplify-category-auth/src/provider-utils/supported-services.ts

this fixes a hole compared to the other login options in that we dont offer instructions to our own docs.

[minor fix] add link to login with Amazon

---

.circleci/config.yml
packages/amplify-category-auth/src/provider-utils/awscloudformation/handlers/get-add-auth-handler.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/add-auth-defaults-applier.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/add-auth-request-adaptor.ts

I don't think anyone has reported it yet
When refactoring auth for headless mode, the new logic did not properly add "oAuthMetadata" to the props passed into the CFN template. It also didn't add the client id and client secret in the hostedUIProviderCreds stored in team provider info.

fix: translate include oAuthMetadata and fix hostedUI meta

---

packages/amplify-util-mock/src/api/api.ts

pass transform config into generateCode should a schema config exist write that into the schema path
to generate new code from changed schema
re #5055

fix(amplify-util-mock): pass transform config into generateCode

---

packages/amplify-util-mock/src/__tests__/func/__snapshots__/index.test.ts.snap
packages/amplify-util-mock/src/__tests__/func/index.test.ts
packages/amplify-util-mock/src/api/api.ts
packages/amplify-util-mock/src/func/index.ts

#5159
Add a Promise.race() against a timeout when invoking a function
Also added a --timeout parameter that can be used to configure the timeout
By default set to 10 seconds. Don't really have a reason for that number other than it will timeout quickly if a developer is expecting a quick response and if they know it should take a while, the error message specifies how to use the --timeout option

fix: timeout mock function invocation

---

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/funcParamsUtils.ts

fix: use _.uniqWith instead of _.uniqBy to remove duplicates

---

packages/graphql-transformer-common/src/ResolverResourceIDs.ts
packages/graphql-transformer-common/src/util.ts
packages/graphql-transformers-e2e-tests/src/__tests__/FunctionTransformerTests.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/PerFieldAuthTests.e2e.test.ts

support underscore names by making logical ids unique to support graphql spec
updated e2e test with underscore named field
re #5212

fix(graphql-transformer-common): support underscore names

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/question-factories/core-questions.js
packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js
packages/amplify-category-interactions/package.json
packages/amplify-category-predictions/package.json
packages/amplify-category-predictions/provider-utils/supportedPredictions.js
yarn.lock

#3284
- Update `inquirer-auto-complete` dependency explicitly to solve peer-dependency issue.
- Remove `chalkpipe` as a dependency, replace with standard `chalk` functionality.

chore: fix #3282, update autocomplete, remove chalkpipe

---

packages/amplify-go-function-runtime-provider/src/runtime.ts

#5209 #5269
Only output executables with a `.exe` suffix for local invocation on windows.
Change build target from `main.go` to `.` to enable building multiple go source files.

fix: enable building multiple go files, .exe extension for local invoke on Windows only

---

packages/amplify-codegen-appsync-model-plugin/package.json
packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-javascript-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-json-metadata-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/utils/process-auth.ts
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-json-metadata-visitor.ts
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-typescript-visitor.ts

https://github.com/aws-amplify/amplify-js/issues/5687
Add owner field to generated schema if it does not exist in the original schema but owner auth is included in auth rules.

fix: add owner field if owner auth is included in auth rules

---

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/utils/get-type-info.ts
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-json-metadata-visitor.ts
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts

Issue #, if available: #5139
I added a check to getTypeInfo to check if the current node is NonNullType and its' child node is ListType to set isListNullable, new attribute in TypeInfo, to to true.
The metadata-visitor then sets isArrayRequired to true whe isListNullable is not allowed.
To add support in DataStore, this PR should do: https://github.com/aws-amplify/amplify-js/pull/6784
This PR should support the table below:
declaration | null | [] | [null] | [{ foo: 'BAR' }]
-- | -- | -- | -- | --
[Type!]! | no | yes | no | yes
[Type]! | no | yes | yes | yes
[Type!] | yes | yes | no | yes
[Type] | yes | yes | yes | yes

fix(amplify-codegen-appsync-model-plugin): DataStore Array Support

---

packages/amplify-cli-core/src/errors/index.ts
packages/amplify-cli/src/commands/publish.ts

*Issue #2809
* Added try/catch block when angular build fails and return with exitcode 1 

fix: publish returns with exitcode 1

---

packages/amplify-appsync-simulator/src/utils/auth-helpers/helpers.ts

fix: #5372 - cut signing url ending slash when matching in mock

---

packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts
packages/graphql-dynamodb-transformer/src/__tests__/__snapshots__/DynamoDBModelTransformer.test.ts.snap
packages/graphql-transformer-core/src/TransformerContext.ts

fix #4944
fix #5332 
#4944: If the schema has a `schema` element without `subscription` ensure that we have it when subscription field addition happens.
#5332: Add reserved type name usage validation to @model directive to prevent further errors.

fix: #4944, #5332

---

packages/amplify-dotnet-function-template-provider/src/providers/crudProvider.ts
packages/amplify-dotnet-function-template-provider/src/providers/helloWorldProvider.ts
packages/amplify-dotnet-function-template-provider/src/providers/serverlessProvider.ts
packages/amplify-dotnet-function-template-provider/src/providers/triggerProvider.ts
packages/amplify-e2e-core/src/categories/lambda-function.ts
packages/amplify-e2e-tests/src/__tests__/function_2.test.ts

fix #5354 
for .NET Core templates the friendly name will be used for the project file name which will default to be the compiled assembly name as well.

fix: #5354 .net core lambda project file naming

---

packages/amplify-cli-core/src/index.ts
packages/amplify-cli/src/__tests__/test-aborting.test.ts
packages/amplify-cli/src/migrate-project.ts
packages/amplify-cli/src/utils/mobilehub-support.ts

Having mobile hub flag in `context.migrationInfo` interfered with other parts of the CLI so it is moved out to context directly.

fix: move mobile hub flag to context directly

---

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts

fix: storage permission resource check - appsync.
Additional Resource existence check is needed since an appsync storage resource does not exist in the meta file directly.

fix: storage permission resource check - appsync

---

packages/amplify-codegen/src/commands/configure.js

insert prompt to run `amplify codegen` - partially addressing the core confusion in https://github.com/aws-amplify/amplify-cli/issues/4858
*Issue #, if available:* https://github.com/aws-amplify/amplify-cli/issues/4858
*Description of changes:* inserting a small log message to prevent confusion, in place of actually running the command for them.

[minor UX fix] insert prompt to run `amplify codegen`

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/question-factories/core-questions.test.js
packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/__snapshots__/auth-request-adaptor.test.ts.snap
packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/auth-request-adaptor.test.ts
packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/trigger-flow-auth-helper.test.js
packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthrough-types.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-request-adaptors.ts

The headless add auth transformer set username attributes as a string instead of an array causing CFN failures.
Note this error is only encountered in headless mode, not when using the auth walkthrough

fix: headless auth username attributes must be an array

---

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts
packages/amplify-e2e-tests/src/__tests__/function_1.test.ts

fix the bug that updating ddb trigger function permission removes the StreamArn attributes from the
dependsOn array
fix #5333

fix(amplify-category-function): fix function dependsOn bug

---

packages/amplify-go-function-runtime-provider/src/runtime.ts

#5209
Use [build-lambda-zip](https://github.com/aws/aws-lambda-go#for-developers-on-windows) for zipping go lambdas on windows.
The tool does not support including other assets outside of the go binary in the zip file so I included a warning telling customers they will need to manually build the lambda or use a layer for their assets.

fix: use go lambda zip tool for packaging go lambda on win

---

packages/amplify-cli/src/utils/mobilehub-support.ts

fix: #5520 exclude pinpoint from provider check for false positives
For pinpoint resources the CLI does not emit the `providerPlugin` field and projects using notifications and multi-env could get a false positive for any `env` command execution because of this.

fix: #5520 exclude pinpoint from provider check for false positives

---

packages/amplify-e2e-core/src/categories/analytics.ts
packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-core/src/categories/auth.ts
packages/amplify-e2e-core/src/categories/codegen.ts
packages/amplify-e2e-core/src/categories/hosting.ts
packages/amplify-e2e-core/src/categories/interactions.ts
packages/amplify-e2e-core/src/categories/lambda-function.ts
packages/amplify-e2e-core/src/categories/lambda-layer.ts
packages/amplify-e2e-core/src/categories/predictions.ts
packages/amplify-e2e-core/src/categories/storage.ts
packages/amplify-e2e-core/src/configure/index.ts
packages/amplify-e2e-core/src/init/amplifyPull.ts
packages/amplify-e2e-core/src/init/deleteProject.ts
packages/amplify-e2e-core/src/init/initProjectHelper.ts
packages/amplify-e2e-core/src/init/pull-headless.ts
packages/amplify-e2e-core/src/utils/nexpect.ts
packages/amplify-e2e-core/src/utils/pinpoint.ts
packages/amplify-e2e-core/src/utils/projectMeta.ts
packages/amplify-e2e-core/src/utils/selectors.ts
packages/amplify-provider-awscloudformation/src/attach-backend.js

fix: handle cli.json copy upon pull to empty dir
chore(amplify-e2e-core): cleanup, new nexpect methods
- disable amplify app creation upon push command
- remove extra 'src' from imports
- add new methods to nexpect
- add delay to flaky test for kinesis

fix: cli.json update on pull, E2E enhancements

---

packages/amplify-appsync-simulator/src/data-loader/dynamo-db/index.ts

When you map a unit or a function to use a DynamoDB data source and use the operation UpdateItem and
do not set condition.expressionNames or update.expressionNames in the payload the
amplify-appsync-simulator stops execution. The AppSync DynamoDB template reference says that those
attributes are optional.
fix #5573
Replace to null if the object is empty, the same approach used in the `Query` operator. 

fix(amplify-appsync-simulator): make ExpressionAttributeNames optional

---

packages/amplify-appsync-simulator/src/__tests__/velocity/index.test.ts
packages/amplify-appsync-simulator/src/__tests__/velocity/util/general-utils.test.ts
packages/amplify-velocity-template/src/compile/expression.js

When used with amplify-appsync-simulator the not equals (!=) expression doesn't work properly. Two
strings are considered inequal when should be considered equals.
fix #5570

fix(amplify-velocity-template): expression not equals works improperly

---

packages/amplify-console-hosting/hosting/manual/publish.js

closes https://github.com/aws-amplify/amplify-cli/issues/4532
*Description of changes:* this builds in a fix to the failure message so that users know how to resolve their own issues.

(fix) suggest fix for zipping failure message

---

packages/amplify-cli-core/src/index.ts
packages/amplify-cli-core/src/isPackaged.ts
packages/amplify-cli/bin/amplify
packages/amplify-cli/src/domain/constants.ts
packages/amplify-cli/src/plugin-helpers/scan-plugin-platform.ts
packages/amplify-cli/src/utils/copy-override.ts
packages/amplify-frontend-javascript/lib/frontend-config-creator.js
packages/amplify-frontend-javascript/package.json

The following are some workarounds required to package the CLI using pkg
- esm is not supported
- fs.copyFile and fs.copyFileSync are not supported
- An additional directory in the snapshot filesystem needs to be scanned for plugins
There are a couple other changes needed to the CLI to support packaging, but in the spirit of keeping PRs small, I'm publishing this one.
Also note, all of the changes in functionality in this PR are behind and "isPackaged" check which is only true when the CLI is running as a packaged binary. There are no changes in functionality when the CLI is running in Node

feat: changes for native packaging

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/__snapshots__/auth-defaults-appliers.test.ts.snap
packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/auth-defaults-appliers.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/handlers/resource-handlers.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-defaults-appliers.ts

Headless update auth was missing a call to format the oAuthMetadata field in parameters.json. Added that and a test to cover it.

fix: store oauthMetadata properly on headless update

---

.circleci/config.yml
packages/amplify-e2e-tests/src/__tests__/import_auth_1.test.ts
packages/amplify-e2e-tests/src/__tests__/import_auth_2.test.ts
packages/amplify-provider-awscloudformation/src/push-resources.js
scripts/split-e2e-tests.ts

Extend auth import tests with a dummy project to make sure test has at least 2 user pools and identity pools so can be more deterministic.

chore: fix e2e import auth tests

---

packages/amplify-codegen/src/commands/generateStatementsAndType.js
packages/amplify-codegen/src/commands/statements.js
packages/amplify-codegen/src/commands/types.js
packages/amplify-codegen/src/utils/ensureSchemaCompiled.js
packages/amplify-codegen/src/utils/existsAppSyncAPIResource.js
packages/amplify-codegen/src/utils/index.js
packages/amplify-codegen/tests/commands/generateStatementsAndTypes.test.js
packages/amplify-codegen/tests/commands/statements.test.js
packages/amplify-codegen/tests/commands/types.test.js

fix #4882 
Added graphql schema compiling in command `amplify codegen`, `amplify codegen statements` and `amplify codegen types`. 

feat(amplify-codegen): add schema compile process in codegen commands

---

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-java-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-javascript-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-json-metadata-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts

fix #5499
Added field level process for `@auth`
```GraphQL
type Employee @model
@auth(rules: [
{ allow: owner },
{ allow: groups, groups: ["Admins"] }
]) {
id: ID!
name: String!
address: String!
ssn: String @auth(rules: [{allow: owner}])
}
```
```Java
@ModelConfig(pluralName = "Employees", authRules = {
@AuthRule(allow = AuthStrategy.OWNER, ownerField = "owner", identityClaim = "cognito:username", operations = { ModelOperation.CREATE, ModelOperation.UPDATE, ModelOperation.DELETE, ModelOperation.READ }),
@AuthRule(allow = AuthStrategy.GROUPS, groupClaim = "cognito:groups", groups = { "Admins" }, operations = { ModelOperation.CREATE, ModelOperation.UPDATE, ModelOperation.DELETE, ModelOperation.READ })
})
public final class Employee …
```

fix(amplify-codegen-appsync-model-plugin): add field level @auth process

---

packages/amplify-app/src/index.js
packages/amplify-cli/src/init-steps/preInitSetup.ts
packages/amplify-e2e-tests/src/__tests__/amplify-app.test.ts
packages/amplify-e2e-tests/src/amplify-app-helpers/amplify-app-validation.ts

Updated amplify-app to initialize feature flags and part of init process. Updated the Amplify App to load `amplify-dev` if the `amplify-app-dev` command is used

fix(amplify-app): initialize feature flag 

---

packages/amplify-category-analytics/commands/analytics/add.js
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.ts
packages/amplify-category-auth/src/commands/auth/update.js
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts
packages/amplify-category-hosting/commands/hosting/remove.js
packages/amplify-category-interactions/provider-utils/awscloudformation/service-walkthroughs/lex-walkthrough.js
packages/amplify-category-notifications/commands/notifications/add.js
packages/amplify-category-notifications/commands/notifications/remove.js
packages/amplify-category-notifications/lib/multi-env-manager.js
packages/amplify-category-notifications/lib/notifications-manager.js
packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js
packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js
packages/amplify-cli/src/extensions/amplify-helpers/remove-resource.ts
packages/amplify-cli/src/index.ts
packages/amplify-cli/src/utils/mobilehub-support.ts
packages/amplify-provider-awscloudformation/src/initialize-env.js

The Mobile Hub migrator plugin has changed to include a `mobileHubMigrated` property on migrated resources. This PR updated the previous checks to be done against this property.
Also mobile hub checks for `env` commands are re-enabled.

fix: refactor mobile hub migration checks

---

packages/amplify-codegen/src/codegen-config/AmplifyCodeGenConfig.js
packages/amplify-codegen/src/utils/getOutputFileName.js
packages/amplify-graphql-types-generator/package.json
packages/amplify-graphql-types-generator/src/angular/index.ts
packages/amplify-graphql-types-generator/src/generate.ts
packages/amplify-graphql-types-generator/test/angular/__snapshots__/index.js.snap
packages/amplify-graphql-types-generator/test/angular/index.js
packages/amplify-graphql-types-generator/test/fixtures/misc/subscriptionSchema.graphql
packages/amplify-graphql-types-generator/test/fixtures/misc/subscriptionSchema.json

- add additional layer about the response type to align with docs
- use `fs-extra` to create generate types file when the directories if they don't exist
- pass proper config when loading projects fro `gqlConfig`
- amend default value name for files so `API.service.service.ts` does not happen
re #5284

fix(amplify-codegen): add proper response type for subs

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/constants.ts
packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts
packages/amplify-e2e-core/src/utils/projectMeta.ts
packages/amplify-e2e-tests/src/__tests__/auth_5.test.ts
packages/amplify-provider-awscloudformation/src/push-resources.js

Update #current-cloud-backend/backend-config.json on resource removal
Also remove autoVerifiedAttributes from auth immutable attribute list as it is mutable: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-autoverifiedattributes

fix: update current-cloud backend-config on resource removal

---

packages/amplify-dynamodb-simulator/package.json
packages/amplify-go-function-runtime-provider/package.json
packages/amplify-java-function-runtime-provider/package.json
packages/amplify-python-function-runtime-provider/package.json

Use latest version of amplify-cli-core in all packages

fix: use correct version of amplify-cli-core

---

packages/amplify-provider-awscloudformation/src/attach-backend.js

N/A
Show Amplify Application ID when listing applications upon `pull` to help customers disambiguate if more applications are having the same name.

fix: show app id when listing console apps

---

.circleci/config.base.yml
.circleci/config.yml
package.json
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/functionPluginLoader.ts

Because the migration tests do not install the CLI from verdaccio, the post-install script was never being run. Added a step to the job to explicitly run the post-install step
Tested by sshing to a circleci job

test: run amplify post-install before migration tests

---

packages/amplify-appsync-simulator/src/__tests__/velocity/index.test.ts
packages/amplify-appsync-simulator/src/velocity/index.ts

When theres has a Lexical error in the velocity template the VelocityTemplate constructor don't
handle it correctly
fix #5621

fix(amplify-appsync-simulator): handle Lexical error correctly

---

packages/amplify-nodejs-function-runtime-provider/src/utils/execute.ts

I get an error even though Lambda is running correctly.
I tried to test the Lambda resolver using [GraphiQL](https://github.com/graphql/graphiql), but I got an error.
However, looking at the output, the Lambda resolver appears to be handling it correctly.
```fish
Lambda Data source failed with the following error
Command failed with exit code 1: /Users/nika/.anyenv/envs/nodenv/versions/12.18.3/bin/node /Users/nika/Documents/workspace/project/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js
{ username: 'test' }
{"data":{"listUsers":{"items":[{"id":"8d7105ff-fd2a-0d77-d817-cb032e7626b0","username":"test","email":"test@test.com","type":"Admin","channel_ids":["eedc2c40-f714-cb81-29a6-6c8abae660c3"],"created_at":"12345","updated_at":"12345","__typename":"User"}],"nextT …
```

fix(amplify-nodejs-function-runtime-provider): change the exit status appropriately

---

packages/amplify-category-auth/src/provider-utils/supported-services.ts

This prompt is duplicated from the prompt above it. It is very frustrating to hit "Learn More" and get an unhelpful answer, it is beyond frustrating to get a duplicate answer.

[fix] Helpful "Learn More" answer for "Do you want to add an admin queries API?" 

---

packages/graphql-auth-transformer/src/__tests__/__snapshots__/SearchableAuthTransformer.test.ts.snap
packages/graphql-elasticsearch-transformer/src/SearchableModelTransformer.ts
packages/graphql-elasticsearch-transformer/src/__tests__/__snapshots__/SearchableModelTransformer.test.ts.snap
packages/graphql-elasticsearch-transformer/src/resources.ts
packages/graphql-mapping-template/src/elasticsearch.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformer.e2e.test.ts

*Issue #, if available:* closes #5086 
adds offset pagination for searchable queries. Uses the elasticsearch parameter 'from'.
adds test for new feature to verify offset.
updates snapshots for searchable template.

feat(graphql-elasticsearch-transformer): add 'from' query parameter

---

packages/amplify-cli/src/extensions/amplify-helpers/editor-selection.ts

I'm proposing a developer experience improvement to Amplify, specifically targeting new users.
Consider the following scenario:
A new user decide is trying out Amplify for the first time.
Forgetting to use the CLI, they attempt to modify the metadata files directly.
They didn't read the docs, and certainly the not the small section at the end explain the Reference > Files and Folders section.
So the only outcome is they get stuck. This causes frustration and a bad new user experience.
Good thing it's totally avoidable. This change visually hides those metadata files so new users aren't tempted to fiddle with them.
With basic workspace configuration settings, we can provide a better user experience for new users by directing their energies and focus towards things in their control, like …

feat(amplify-cli-core): visually hide "immutable files" for VSCode users

---

packages/graphql-relational-schema-transformer/src/AuroraDataAPIClient.ts
packages/graphql-relational-schema-transformer/src/__tests__/AuroraDataAPIClient.test.ts

*Issues:*
#5525, #2293
Escape reserved keywords used in table names when executing `DESCRIBE tableName`.

fix(graphql-relational-schema-transformer): escape SQL reserved keywords

---

packages/graphql-transformer-core/src/util/sanity-check.ts

Issue: #5689
This change fixes a problem with "innerDiffs is not iterable" when there are changes to a schema but after diffing changed structures nothing is actually detected.
This can occur when for example when changing order of `@key` directives, all of the keys are the same and there is no change the only thing changing is their order in the schema.

fix(graphql-transformer-core): "innerDiffs is not iterable" error on push

---

packages/amplify-cli/src/commands/pull.ts
packages/amplify-cli/src/initialize-env.ts

In a multi-backend workflow, if a teammate removes your backend/env from team-provider-info, amplify will fail on most env commands with a non-helpful error. This fixes that.
New CLI response:
On the failing code, this applies a more descriptive error message.

More descriptive error on env cmd

---

.circleci/config.base.yml
.circleci/config.yml

Adding Docker Hub authentication to the CircleCI pipeline to accommodate [this change](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress) in Docker's ToS.
Here's the same change in JS for reference: https://github.com/aws-amplify/amplify-js/pull/7007
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

ci: add docker hub auth to config
