packages/amplify-provider-awscloudformation/src/push-resources.js

Redoing the PR as the previous repo ran into conflicting error from recent merges, let me know if this is good and if I am missing anything. Thanks
Given it is pretty trivial, there is no issue # associated with it.
Something short and sweet.
When I do amplify push with either zero or two or more CloudFormation Template, the error message stays the same which is confusing and misleading for me.
On my team, due to someone mistakenly removing one of the cloudformation template, our amplify push did not work and the error messages was very misleading and suggested there might be more hidden Cloudformation template somewhere getting used until I realized it was just missing the template instead.
By submitting this pull request, I confirm that my …

fix(amplify-provider-awscloudformation): add new error message

---

packages/amplify-provider-awscloudformation/src/push-resources.js

There may be reasons to have a multiple lambda function resources inside a single function resource. This may be because the function is doing one-off deployment tasks as a custom resource, or handling other processing duties related to the main lambda. For example, one lambda may handle domain logic and handle CRUD for a dynamodb table, another Lambda may do the stream processing of the dynamodb table, and another might setup dynamodb ttl properties, or perform a data migration. At the same time, the details of these functions do not need to be exposed as a top level function and are best served by being encapsulated in another resource. Having the top level resources littered with tiny lambdas can lead to messy code.
This PR changes the …

enhance(amplify-provider-awscloudformation): multiple lambdas per resource

---

packages/amplify-e2e-tests/src/__tests__/env.test.ts

Fix e2e test failure
Test was failing because internal flag was being set to not create an Amplify App causing subsequent pull operations to fail.

test: enable app creation for test that does pull

---

packages/amplify-provider-awscloudformation/src/push-resources.js

Reverts aws-amplify/amplify-cli#5032
Caused several e2e test failures: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/2514/workflows/2982ec79-ca20-4cd4-ac3f-e154f3f8a5e4

Revert "enhance(amplify-provider-awscloudformation): multiple lambdas per resource"

---

packages/graphql-predictions-transformer/src/__tests__/PredictionsTransformer.test.ts
packages/graphql-predictions-transformer/src/__tests__/__snapshots__/PredictionsTransformer.test.ts.snap
packages/graphql-predictions-transformer/src/resources.ts

fix json validation in predictions transformer so valid strings are allowed in the payload
re #4346

fix(graphql-predictions-transformer): fix json validation

---

packages/amplify-appsync-simulator/package.json
packages/amplify-appsync-simulator/src/__tests__/scalars/AWSJSON.test.ts
packages/amplify-appsync-simulator/src/__tests__/scalars/__snapshots__/AWSJSON.test.ts.snap
packages/amplify-appsync-simulator/src/schema/appsync-scalars/index.ts
packages/amplify-appsync-simulator/src/schema/index.ts

Fixes #5207
Several issues here.
1) AWS scalars were not used at all
AWS scalars were defined, but never injected in the schema. This is now fixed.
**Please let me know if this was intentional** (for some reason)
2) `AWSPhone` was needs to be instantiated in order to be injected into the schema.
Instead, the class itself was passed. 
`AWSPhone` also seems to accept [some options](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-appsync-simulator/src/schema/appsync-scalars/index.ts#L13) for the country. Since this was not used at all until now, I just left the defaults.
3) `AWSJSON`
Finally, this fixes #5207 
AWSJSON are stringified in AppSync but were returned as objects in the simulator. 
According to [the …

fix(amplify-appsync-simulator): appsync scalars

---

packages/amplify-category-auth/resources/adminAuth/admin-auth-app.js
packages/amplify-category-auth/resources/adminAuth/admin-auth-cognitoActions.js
packages/amplify-category-auth/resources/adminAuth/admin-queries-function-template.json.ejs

Select the type of change that you're committing: feature
Write a short, imperative tense description of the change: Add the ability to list Amazon Cognito groups
Provide a longer description of the change: If someone wants to dynamically display a list of Amazon Cognito groups in an application, that is not currently possible.  This change opens up that use case.
Are there any breaking changes? N
Does this change affect any open issues? N

Add the ability to list Amazon Cognito groups

---

packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-javascript-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-json-metadata-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts

Revert the changes of PR #5335 #5455 . `ownerField` will not be added to modelgen output automatically in implicit cases for @auth. 

fix(amplify-codegen-appsync-model-plugin): revert changes of adding ownerField for implicit cases for @auth

---

packages/graphql-elasticsearch-transformer/streaming-lambda/python_streaming_function.py

Sample JSON payload as `es_ret_str`:
```
{
"took": 74,
"errors": true,
"items": [
{
"index": {
"_index": "table-v2",
"_type": "doc",
"_id": "c352f721-4bd0-4895-xxx",
"status": 409,
"error": {
"type": "version_conflict_engine_exception",
"reason": "[doc][xxx]: version conflict, current version [1] is higher or equal to the one provided [1]",
"index_uuid": "fVEyrXaZTXCTQxxx",
"shard": "1",
"index": "table-v2"
}
}
},
{
"delete": {
"_index": "table-v2",
"_type": "doc",
"_id": "id=c352f721-4bd0-4895-xxx",
"_version": 1,
"result": "not_found",
"_shards": {
"total": 2,
"successful": 1,
"failed": 0
},
"_seq_no": 2288,
"_primary_term": 3,
"status": 404
}
}
]
}
```
You will hit the error below:
```
{
"errorMessage": "'NoneType' object has no attribute 'get'",
"errorType": …
```

fix(graphql-elasticsearch-transformer): Fixed NoneType when attempting to retrieve error on streaming-lambda

---

packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/function-template-dir/trigger-index.js

fix #3212
This change extracts the module loading outside the handler function to don't load the modules at
every runtime execution. It also reduces a lot the cold start duration.

refactor(amplify-category-auth): stop loading module at runtime

---

packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformer.e2e.test.ts

test: update expected result length

---

packages/amplify-cli-core/src/__tests__/featureFlags.test.ts
packages/amplify-cli-core/src/__tests__/testFiles/project-with-feature-off/cli.json
packages/amplify-cli-core/src/feature-flags/featureFlags.ts
packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts

#5554
When we fixed the bug to validate and fail on using reserve words as type names in the gql schema, customers who were using those reserve words can no longer compile their schema. This change introduces a feature flag that will be on for existing and new project, but can manually be turned off for customers using reserve words in their schema.
This PR also includes a bug fix in the FF framework where false values were not correctly initialized

feat: ff to turn off schema reserve word validation

---

packages/amplify-e2e-tests/src/plugin/verifyPluginStructure.ts
packages/amplify-e2e-tests/src/schema-api-directives/authHelper.ts
packages/graphql-transformers-e2e-tests/src/CloudFormationClient.ts
packages/graphql-transformers-e2e-tests/src/LambdaHelper.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ConnectionsWithAuthTests.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/DynamoDBModelTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/FunctionTransformerTests.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/HttpTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformerLocal.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/KeyWithAuth.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelAuthTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelConnectionTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/ModelConnectionWithKeyTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthModelAuthTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/MutationCondition.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/NewConnectionTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/NewConnectionWithAuth.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/NonModelAuthFunction.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/NoneEnvFunctionTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/PerFieldAuthTests.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/PredictionsTransformerTests.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SearchableWithAuthTests.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/VersionedModelTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/cognitoUtils.ts
packages/graphql-transformers-e2e-tests/src/deployNestedStacks.ts
packages/graphql-transformers-e2e-tests/src/emptyBucket.ts
packages/graphql-transformers-e2e-tests/tsconfig.tests.json

N/A
- This PR removes the excessive `console.log` statements from the GraphQL E2E tests.
- Consolidate test cleanup code into 1 method.

chore: remove console.logs from e2e tests

---

packages/amplify-python-function-runtime-provider/package.json
packages/amplify-python-function-runtime-provider/src/util/depUtils.ts
packages/amplify-python-function-runtime-provider/src/util/invokeUtil.ts
packages/amplify-python-function-runtime-provider/src/util/pyUtils.ts

#5662 
Fixes #5662 by adding a fallback support for 'python' as binary beside 'python3' which has a higher precedence. 

fix: #5662 - python fallback from python3

---

packages/graphql-transformers-e2e-tests/src/__tests__/PredictionsTransformerTests.e2e.test.ts

noun can potentially change adding regex to keep end phrase similar

test(graphql-transformers-e2e-tests): add regex for noun change

---

packages/amplify-category-storage/resources/cloudformation-templates/s3-cloudformation-template.json.ejs

#5794 
Fixes missing ListBucket permission when Groups are used with Storage category. 

fix: #5794 - storage access problem with groups

---

packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs
packages/amplify-frontend-android/lib/frontend-config-creator.js
packages/amplify-frontend-ios/lib/frontend-config-creator.js

Remove the optional appClientSecret for future Android and iOS apps created with the CLI

fix: remove appClientSecret as best practice

---

packages/amplify-e2e-tests/src/import-helpers/expects.ts

The optional appClientSecret is no longer generated

test: remove appClientSecret from e2es

---

packages/amplify-cli/src/extensions/amplify-helpers/open-editor.ts

Title says it all.
Got hit with this error message on my machine, and noticed the extra space.
------------

Removed extra blank space in error message in open-editor.ts

---

package.json

Fixes the issue where the github release version is behind the CLI version

chore: fix pub to verdaccio script

---

.circleci/config.base.yml
.circleci/config.yml
scripts/unified-changelog.ts

update the unified changelog script to work with recent changes to publish-to-verdaccio script.
Also update installation sanity check

chore: pipeline updates

---

packages/amplify-cli/package.json
packages/amplify-cli/src/amplify-service-helper.ts
packages/amplify-cli/src/attach-backend.ts
packages/amplify-cli/src/extensions/amplify-helpers/get-category-pluginInfo.ts
packages/amplify-cli/src/pre-deployment-pull.ts
packages/amplify-cli/src/pull-backend.ts
packages/amplify-cli/tsconfig.json
packages/amplify-codegen/src/commands/models.js
packages/amplify-provider-awscloudformation/src/configuration-manager.js
packages/graphql-transformer-core/src/util/transformConfig.ts
yarn.lock

On pull, if DataStore is enabled perform codegen models automatically. Adds a new --no-codegen flag to pull to skip this behavior if not desired

feat: codegen on pull

---

packages/amplify-codegen/package.json
packages/amplify-codegen/src/commands/models.js

N/A
`.eslintignore` file generation failed on uninitialized projects when project was created with `amplify-app`, this PR changes how the `projectPath` is read, to make it work in those situations as well.

fix: eslintignore creation with uninitialized project

---

packages/amplify-category-analytics/provider-utils/awscloudformation/cloudformation-templates/pinpoint-cloudformation-template.json
packages/amplify-category-notifications/lib/auth-helper.js

Change in pinpoint policy actions based on discussion

fix: changing pinpoint policy

---

packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/constants.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/index.js
packages/amplify-cli-core/src/index.ts
packages/amplify-cli-core/src/state-manager/stateManager.ts
packages/amplify-cli/src/commands/console.ts
packages/amplify-cli/src/pre-deployment-pull.ts
packages/amplify-provider-awscloudformation/src/index.ts
packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts

fix: file existence checks, enable admin console

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/__snapshots__/auth-request-adaptor.test.ts.snap
packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/auth-request-adaptor.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-request-adaptors.ts
packages/amplify-headless-interface/schemas/auth/1/UpdateAuthRequest.schema.json
packages/amplify-headless-interface/src/interface/auth/update.ts

Specifying an empty oAuth config in a headless auth update request (`"oAuth": {}`) now removes the oAuth configuration from the auth resource. Additionally, a partial oAuth config can be specified in a headless update and only the parameters specified will be updated; omitted parameters will retain their current value

fix: headless auth remove oauth when empty config specified

---

packages/amplify-category-auth/src/index.js

`externalAuthEnabled` was returning an incorrect value
N/A
Updating return value for `externalAuthEnabled` function

fix(amplify-category-auth): external auth enabled bugfix

---

packages/amplify-category-storage/src/provider-utils/awscloudformation/import/import-s3.ts
packages/amplify-provider-awscloudformation/src/aws-utils/S3Service.ts

For import S3 buckets when they reside in `us-east-1`, `getBucketLocation` returns empty, so meta file ends up with no region. This PR fixes that edge case.

fix: imported s3 bucket us-east-1 not getting region assigned

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-defaults-appliers.ts

previous commit caused a few e2e tests to fail because new auth trigger selections were not overwriting previous selections

fix: new auth triggers overwrite previous selections

---

packages/amplify-cli/package.json
packages/amplify-cli/src/commands/console.ts
yarn.lock

fix: bump amplify-app version, remove unsused import

---

packages/amplify-cli/src/init-steps/s9-onSuccess.ts
packages/amplify-console-integration-tests/src/consoleHosting/consoleHosting.ts
packages/amplify-e2e-core/src/init/index.ts
packages/amplify-e2e-core/src/init/initProjectHelper.ts
packages/amplify-e2e-core/src/utils/add-circleci-tags.ts
packages/amplify-e2e-core/src/utils/index.ts
packages/amplify-e2e-core/src/utils/pinpoint.ts
packages/amplify-e2e-tests/src/init-special-cases/index.ts

fix: preserve `tags.json` content if it exists during `amplify init`
chore: This PR adds Circle CI related tags that helps with the cleaning up of leftover resources after a cancelled or failed pipeline run.
Tags include:
- `circleci`: to enable filtering
- `circleci:branch`: GitHub branch
- `circleci:sha1`: Commit hash
- `circleci:workflow_id`: Id of the Circle CI workflow 

chore: add circle ci tags to cf resources in e2e test projects

---

packages/amplify-app/src/scripts/amplify-push.js

fix #5394
Use string profile instead of object

fix: use profile as key when asking for profile

---

scripts/github-prerelease.ts

Remove "not for production" warning from GH release title and description

chore: remove 'not for production' notice from GH release

---

packages/amplify-velocity-template/README.md

*Issue #, if available:* N/A
I've started using the `amplify-velocity-template` package and I found a couple of potential improvements to its `README.md` file, I hope you won't mind me creating a PR to improve the docs a little bit :)

Fix some typos and wording in amplify-velocity-template README.md

---

packages/amplify-app/package.json

#6039
Bump min CLI version required by amplify-app

fix: bump min version of cli required by amplify-app

---

packages/amplify-appsync-simulator/src/schema/directives/auth.ts
packages/amplify-appsync-simulator/src/velocity/util/errors.ts

In current master the simulate server can respond with `"message": "Cannot read property 'key' of undefined",` when using the auth directive. Which I tracked down to this line:
https://github.com/aws-amplify/amplify-cli/blob/296ae55d1252168380dbac99d26e816221ddd470/packages/amplify-appsync-simulator/src/velocity/util/errors.ts#L11
the auth directive handler seemingly passes down the wrong field from the Graphql info object. 
-------------------
Fixed by passing the correctly shaped info object and typing the constructor params. 

fix(amplify-appsync-simulator): auth directive unauthorized message

---

package.json
pkg/babel.config.json

Fix pkg cli build failures as a result of pulling in octokit as a dependency: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/3256/workflows/bedb748a-1663-4d09-8e2b-8ee3402e1546/jobs/45374

fix: update pre-pkg babel config

---

packages/amplify-appsync-simulator/src/__tests__/velocity/util/general-utils.test.ts
packages/amplify-appsync-simulator/src/velocity/util/general-utils.ts

`$utils.toJson(false)` should return `false` (as a json). Currently, it returns `null`.
I also added some tests

fix(amplify-appsync-simulator): utils.toJson false value

---

packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-key-transformer/src/__tests__/KeyTransformer.test.ts

add ModelSortDirection and ModelXFilterInput if they don't exist in the schema (ex. list query is
null)
re #6029

fix(graphql-key-transformer): support sortEnum and filterInput

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/auth-defaults-appliers.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-defaults-appliers.ts

#5681
Switch from lodash merge to lodash assign when overwriting defaults with walkthrough selections. merge will append to lists (in the case of the issue above causing the default requiredAttribute 'email' to stick around even when deselecting all attributes in the walkthrough). assign will overwrite any defined field with the new value (so [] overwrites ['email'])

fix: ensure auth selections overwrite defaults

---

packages/amplify-provider-awscloudformation/src/configuration-manager.js

fixes #6087
Default to {} instead of undefined in _.get() appId

fix: undefined appId destructuring

---

packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs
packages/amplify-category-auth/src/provider-utils/awscloudformation/constants.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthrough-types.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-defaults-appliers.ts
packages/amplify-cli-core/src/feature-flags/featureFlags.ts

fix: #4175 - enable Cognito case insensitive usernames for new projects behind a feature flag.
`auth.enableCaseInsensitivity` feature flag was added to not to break existing deployment. When a new auth resource is added and the flag's value is true case insensitivity for Cognito User Pools will be enabled.
New projects created will have this enabled by default.

fix: #4175 - enable Cognito case insensitive usernames for new projects and new auth resources

---

.circleci/config.yml
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts
packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts

fix: #6097 - don't create build folder during dry run
This PR fixes the 2nd half, the root cause of the referenced issue, so a full API build will happen upon push.

fix: #6097 - don't create build folder during dry run

---

packages/amplify-appsync-simulator/src/__tests__/velocity/index.test.ts
packages/amplify-appsync-simulator/src/velocity/index.ts
packages/amplify-nodejs-function-runtime-provider/src/utils/execute.ts
packages/amplify-nodejs-function-runtime-provider/src/utils/invoke.ts

fix: #6067
This fixes the error scenarios with mock when Lambda resolvers are used, either with `throw` or the `callback('error')` way.

fix: #6067 - nodejs mock return error from lambda

---

packages/amplify-category-analytics/package.json
packages/amplify-category-api/package.json
packages/graphql-transformer-core/package.json

fix: #6123 - add missing `amplify-cli-core` dependencies to packages
`amplify-cli-core` dependency was missing from some packages where it is referenced, this PR adds those entries.

fix: #6123 - add missing amplify-cli-core dependencies to packages

---

packages/amplify-provider-awscloudformation/src/graphql-transformer/utils.ts
packages/graphql-transformer-core/src/util/sanity-check.ts

fix: #6097 - check for root stack when loading projects for sanity check
This fix adds an additional check to sanity check project loading in case if the `cloudformation-template.json` file is not present in the `#current-cloud-backend/api/<apiname>/build` folder. This enables api gql-compile to succeed. 

fix: #6097 - check for root stack when loading projects for sanity check

---

packages/graphql-auth-transformer/src/__tests__/__snapshots__/SearchableAuthTransformer.test.ts.snap
packages/graphql-connection-transformer/src/__tests__/__snapshots__/ModelConnectionTransformer.test.ts.snap
packages/graphql-connection-transformer/src/__tests__/__snapshots__/NewConnectionTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts
packages/graphql-dynamodb-transformer/src/__tests__/__snapshots__/DynamoDBModelTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/definitions.ts
packages/graphql-elasticsearch-transformer/src/__tests__/__snapshots__/SearchableModelTransformer.test.ts.snap
packages/graphql-transformer-common/src/definition.ts

fix: #6108 - add proper AWSJSON mapping in generated filter input types
This PR adds support to generrate `ModelAWSJSONFilterInput` type for `AWSJSON` type fields for the `List` operations.

fix: #6108 - add proper AWSJSON mapping in generated filter input types

---

packages/graphql-auth-transformer/src/__tests__/__snapshots__/SearchableAuthTransformer.test.ts.snap
packages/graphql-connection-transformer/src/__tests__/__snapshots__/ModelConnectionTransformer.test.ts.snap
packages/graphql-connection-transformer/src/__tests__/__snapshots__/NewConnectionTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts
packages/graphql-dynamodb-transformer/src/__tests__/__snapshots__/DynamoDBModelTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/definitions.ts
packages/graphql-elasticsearch-transformer/src/__tests__/__snapshots__/SearchableModelTransformer.test.ts.snap
packages/graphql-transformer-common/src/definition.ts

Reverts aws-amplify/amplify-cli#6112

Revert "fix: #6108 - add proper AWSJSON mapping in generated filter input types"

---

.github/CODEOWNERS

> You can use a CODEOWNERS file to define individuals or teams that are
> responsible for code in a repository.
This will cause the "Amplify CLI" team to automatically be included to
the "Reviewers" list on all incoming Pull Requests.
Refer: https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners

chore: add cli team to github codeowners file

---

packages/amplify-codegen-appsync-model-plugin/src/__tests__/utils/process-connections.test.ts
packages/amplify-codegen-appsync-model-plugin/src/utils/process-connections.ts
packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-swift-visitor.ts

https://github.com/aws-amplify/amplify-ios/issues/920
This adds the targetName for hasOne relationships, closely mirroring the same logic applied for belongsTo. 
*Testing done*
schema
```
type Project2 @model {
id: ID!
name: String
teamID: ID! // Explicit field for Team association
team: Team2 @connection(fields: ["teamID"])
}
type Team2 @model {
id: ID!
name: String!
}
```
Generated swift schema class without this change:
```swift
// swiftlint:disable all
import Amplify
import Foundation
extension Project2 {
// MARK: - CodingKeys 
public enum CodingKeys: String, ModelKey {
case id
case name
case teamID
case team
}
public static let keys = CodingKeys.self
//  MARK: - ModelSchema 
public static let schema = defineSchema { model in
let …
```

fix(amplify-codegen-appsync-model-plugin): pass targetName for hasOne relationships

---

packages/graphql-auth-transformer/src/__tests__/__snapshots__/SearchableAuthTransformer.test.ts.snap
packages/graphql-connection-transformer/src/__tests__/__snapshots__/ModelConnectionTransformer.test.ts.snap
packages/graphql-connection-transformer/src/__tests__/__snapshots__/NewConnectionTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts
packages/graphql-dynamodb-transformer/src/__tests__/__snapshots__/DynamoDBModelTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/definitions.ts
packages/graphql-elasticsearch-transformer/src/__tests__/__snapshots__/SearchableModelTransformer.test.ts.snap
packages/graphql-transformer-common/src/definition.ts

Reverts aws-amplify/amplify-cli#6158

Revert "Revert "fix: #6108 - add proper AWSJSON mapping in generated filter input types""

---

packages/amplify-cli/src/plugin-helpers/create-new-plugin.ts

Replacing https://docs.amplify.aws/cli/usage/plugin which is 404 with https://docs.amplify.aws/cli/plugins/architecture#plugin-types at `amplify plugin init`.
Fixes https://github.com/aws-amplify/amplify-cli/issues/6196.

fix(cli): update plugin type details url

---

packages/amplify-provider-awscloudformation/src/zip-util.js

Downloading current cloud backend from S3 did not reject the promise on error. Updated the code to reject on network error
fix #6198  

fix: download s3 file to reject on network errors

---

packages/amplify-codegen-appsync-model-plugin/src/scalars/index.ts

According to the [GraphQL spec](https://graphql.org/learn/schema/#scalar-types), a `Float` type is:
> Float: A signed double-precision floating-point value
The CLI maps GraphQL's `Float` to a `Double` in Swift, and a `double` in TypeScript, respectively. However, the codegen maps  the GraphQL type to __Java `Float`__, which is a single-precision value. In a perfect world, this would have always been the Java double-precision type, `java.lang.Double`.
Android customers have existing models in the field that use the `Float` we've generated for them. As a result, the Android library has been updated to support _both_. This compat support was released in Amplify Android 1.6.7 (See https://github.com/aws-amplify/amplify-android/pull/1040.)
After #6145, _Double_ will be generated for all _new_ …

fix(graphql-connection-transformer): store graphql float as java double

---

packages/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts

Update the package script to handle error when package manager is mising and child process returns
with NOENT error

fix(amplify-nodejs-function-runtime-provider): handle lambda pkg errors

---

packages/amplify-console-hosting/hosting/index.js
packages/amplify-console-hosting/hosting/manual/enable.js
packages/amplify-console-hosting/hosting/manual/publish.js
packages/amplify-console-hosting/package.json
packages/amplify-console-hosting/utils/amplify-console-utils.js
packages/amplify-e2e-tests/package.json
yarn.lock

*Description of changes:* Replaces deprecated `request` and `request-promise` dependencies and replace them with `node-fetch`. Also bump minor version of `graphql-schema-diff`.

chore: replace deprecated dependencies

---

packages/amplify-codegen/src/callbacks/prePushAddCallback.js

Makes sure that flutter project customers are not asked about generating GraphQL statements and
types.

fix(amplify-codegen): excludes flutter projects from gql gen

---

packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts
packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts
packages/amplify-util-mock/src/api/lambda-arn-to-config.ts

#6280 
Some messages output "old-docs-url" like
"https://docs.amplify.aws/cli/graphql-transformer/directives#auth".
So, modify it to "new-docs-url" like
"https://docs.amplify.aws/cli/graphql-transformer/auth".

fix: change to new docs url in some messages

---

packages/amplify-cli/package.json
packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts
packages/amplify-e2e-core/src/categories/lambda-function.ts
packages/amplify-e2e-tests/src/__tests__/auth_2.test.ts

Removing NodeModules folder from the #currentcloudbackend

fix: removes nodeModules from curBackend

---

packages/amplify-app/src/framework-config-mapping.js
packages/amplify-frontend-javascript/lib/framework-config-mapping.js

#6269
change default SourceDir from `/` to `src` for react-native projects. This is consistent with other project structures and removes a disparity between where types were generated and where the CLI tries to locate them by default.
Tested in projects initialized using expo and react-native CLI

fix: set default sourceDir for react-native projects to 'src'

---

packages/amplify-appsync-simulator/src/__tests__/velocity/util/list-utils.test.ts
packages/amplify-appsync-simulator/src/__tests__/velocity/util/math.test.ts
packages/amplify-appsync-simulator/src/__tests__/velocity/util/str.test.ts
packages/amplify-appsync-simulator/src/velocity/util/index.ts
packages/amplify-appsync-simulator/src/velocity/util/list-utils.ts
packages/amplify-appsync-simulator/src/velocity/util/math.ts
packages/amplify-appsync-simulator/src/velocity/util/str.ts

Implements new utils as described in doc:
https://docs.aws.amazon.com/appsync/latest/devguide/resolver-util-reference.html#list-helpers-in-util-list
and
https://docs.aws.amazon.com/appsync/latest/devguide/resolver-util-reference.html#str-helpers-in-util-str
`$utils.list.sortList()`
`$utils.str.toUpper()`
`$utils.str.toLower()`
`$utils.str.toReplace()`
`$utils.str.normalize()`
`$util.math.roundNum()`
`$util.math.roundNum()`
`$util.math.maxVal()`
`$util.math.minVal()`
`$util.math.randomWithinRange()`
`$util.math.randomDouble()`
Note concerning `$utils.list.sortList()`:
I have honoured what the documentation states in the simulator:
> Only lists containing a maximum of 1000 objects are supported.
However, during my tests in a real AppSync API, it worked fine with > 1000 elements. (tested …

feat(amplify-appsync-simulator): implement new utils

---

packages/amplify-provider-awscloudformation/src/system-config-manager.js

The constructed request parameter for `assumeRole` wasn't used. Thus, AWS profile using `role_arn`
never succeeded. This commit fixes it and now the parameter is passed to `assumeRole`.
Fixes #6233 , Fixes #6220
I have confirmed by `amplify-dev`:
```shell
$ amplify-dev pull --appId aaaaaaaa
For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use dev
Amplify AppID found: aaaaaaaa. Amplify App name is: SampleApp
```
Without this change:
```shell
$ amplify --version
4.40.1
$ amplify pull --appId aaaaaaaa
For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
? Do you want to use an …
```

fix(amplify-provider-awscloudformation): pass assumeRoleRequest

---

packages/amplify-appsync-simulator/src/velocity/value-mapper/array.ts

When a request to an external data source returns a single value that is of type number, the array is incorrectly initialized. This scenario means that all requests to ElasticSearch with results sorted by date fail.
For example, when querying a locally running ElasticSearch instance with results sorted by date, the date is always returned is in milliseconds: 1608657312744. Since that value is a number, the call to 
`super(...values)` 
becomes 
`super(1608657312744)`
Which tries to initialize an array of length 1608657312744. See the documentation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Array
> A JavaScript array is initialized with the given elements, except in the case where a single …

fix: correctly initialize Array when values contain a single integer element

---

packages/graphql-elasticsearch-transformer/scripts/ddb_to_es.py

Script ddb_to_ess.py used for repopulating ElasticSearch with data from DynamoDB, was not accepting session token and also ignoring AWS session token from credentials. It's needed if user is using temporary credentials. Due to this, I was not able to run the script using temporary credentials.
Docs references:
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html

feat(graphql-elasticsearch-transformer): ddb_to_ess now accepts AWS session token

---

packages/amplify-console-integration-tests/__tests__/pullAndInit.test.ts
packages/amplify-console-integration-tests/src/pullAndInit/amplifyArtifactsManager.ts

Fix console integration test which failed, because it created a half initialized environment between pull operations and led to a failing - otherwise not possible - code path.

chore: update console integration test

---

packages/amplify-appsync-simulator/src/__tests__/utils/auth-helpers/helpers.test.ts
packages/amplify-appsync-simulator/src/utils/auth-helpers/helpers.ts

*Issue:* https://github.com/aws-amplify/amplify-cli/issues/6368
https://github.com/aws-amplify/amplify-cli/issues/5372#issuecomment-758247839
- Improved isValidOIDCToken(): Added support for token.iss ending with slash. (Auth0)
- Added unit tests

fix(amplify-appsync-simulator): allow token.iss ending with slash

---

packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts
packages/amplify-category-function/src/constants.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/permissionMapUtils.ts
packages/amplify-cli-core/src/feature-flags/featureFlags.ts
packages/amplify-e2e-core/src/categories/lambda-function.ts
packages/amplify-e2e-tests/src/__tests__/function_2.test.ts

fix #4306
4306
The current implementation of appsync permissions is using an incorrect understanding of [IAM policies for AppSync](https://docs.aws.amazon.com/appsync/latest/devguide/security.html). This PR updates the IAM Policy generation process for lambdas from `amplify function create/update` walkthroughs.
This PR is ready for merging. :rocket: 

fix: fix appsync permission assignment from functions

---

packages/amplify-nodejs-function-runtime-provider/src/__tests__/utils/handlers.js
packages/amplify-nodejs-function-runtime-provider/src/__tests__/utils/invoke.test.ts
packages/amplify-nodejs-function-runtime-provider/src/__tests__/utils/invokeExecute.test.ts
packages/amplify-nodejs-function-runtime-provider/src/utils/execute.ts
packages/amplify-nodejs-function-runtime-provider/src/utils/invoke.ts
packages/amplify-nodejs-function-runtime-provider/src/utils/invokeOptions.ts
packages/amplify-nodejs-function-runtime-provider/src/utils/invokeUtils.ts

fix #5553
return proper error message and stack if a string error is provided return string error as is

fix(amplify-nodejs-function-runtime-provider): fix lambda error format

---

packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs
packages/amplify-category-auth/src/provider-utils/awscloudformation/assets/cognito-defaults.js
packages/amplify-e2e-core/src/utils/projectMeta.ts
packages/amplify-e2e-tests/src/__tests__/auth_1.test.ts
packages/amplify-e2e-tests/src/import-helpers/expects.ts
packages/amplify-frontend-android/lib/frontend-config-creator.js
packages/amplify-frontend-ios/lib/frontend-config-creator.js

Rework off reverted previous change https://github.com/aws-amplify/amplify-cli/pull/5992. This change sets the cognito default to generate the AppClientSecret to false and writes the secret to the native config files when the secret is configured in the app client.
The previous change did not take into consideration of an existing appClient with a configure client. In the new change the configuration files will possess the secret only if it's configured
*New Projects*
There will be two app clients same as before but the native app client will not be configured to generate a secret and the configuration file for IOS/Android will contain the secret either.
*Existing Projects with Auth Enabled*
The change will not affect any existing configuration of their app …

feat: app client secret omission

---

packages/amplify-appsync-simulator/src/__tests__/utils/graphql-runner/query-and-mutation.test.ts
packages/amplify-appsync-simulator/src/resolvers/pipeline-resolver.ts
packages/amplify-appsync-simulator/src/resolvers/unit-resolver.ts
packages/amplify-appsync-simulator/src/utils/expose-graphql-errors.ts
packages/amplify-appsync-simulator/src/velocity/index.ts
packages/amplify-util-mock/src/__e2e__/key-transformer.e2e.test.ts
packages/amplify-velocity-template/src/compile/references.js
packages/amplify-velocity-template/tests/compile.js

The implementation of set and get methods of an array in velocity is not working like in the real
environment.
fix is based on https://github.com/shepherdwind/velocity.js/pull/133
fix #5741

fix(amplify-velocity-template): support 'get' and 'set' of array vars

---

packages/amplify-graphql-types-generator/src/angular/index.ts
packages/amplify-graphql-types-generator/src/compiler/index.ts
packages/amplify-graphql-types-generator/src/flow/codeGeneration.js
packages/amplify-graphql-types-generator/src/flow/language.js
packages/amplify-graphql-types-generator/src/serializeToJSON.ts
packages/amplify-graphql-types-generator/src/typescript/codeGeneration.ts
packages/amplify-graphql-types-generator/src/typescript/language.ts
packages/amplify-graphql-types-generator/test/__snapshots__/jsonOutput.ts.snap
packages/amplify-graphql-types-generator/test/angular/__snapshots__/index.js.snap
packages/amplify-graphql-types-generator/test/compiler/legacyIR.js
packages/amplify-graphql-types-generator/test/flow/__snapshots__/codeGeneration.js.snap
packages/amplify-graphql-types-generator/test/typescript/__snapshots__/codeGeneration.js.snap

Fixes #3323
* accumulate return type of operation
* accumulate object types, interface types and union types
* generate object types, interface types and union types (for TypeScript)
This PR mainly handles TypeScript. Other frontends may have similary issue.

feat(amplify-graphql-types-generator): generate model types

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/import/messages.ts
packages/amplify-e2e-tests/src/__tests__/import_auth_1.test.ts
packages/amplify-e2e-tests/src/__tests__/import_auth_2.test.ts
packages/amplify-e2e-tests/src/import-helpers/types.ts
packages/amplify-e2e-tests/src/import-helpers/utilities.ts
packages/amplify-e2e-tests/src/import-helpers/walkthroughs.ts

Update auth import support importing cognito user pool app client (for native) with or without secret. The CLI has been updated (in #6333) to support generation of App client for native not to generate App Secret. By updating the import path, customers can import the auth provisioned by the CLI in a different project.

feat: add support for importing userpool with no appclient secret

---

packages/amplify-e2e-tests/src/__tests__/import_auth_1.test.ts
packages/amplify-e2e-tests/src/__tests__/import_auth_2.test.ts

updated the e2e tests to support auth import to use the correct app client for web

test: update e2e tests to support auth import

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/auth-defaults-appliers.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-defaults-appliers.ts

#5681
fixes an issue that caused some tests to fail in PR #6071 which were reverted in #6179
Use _.assignWith with a customizer to not assign undefined values instead of using _.merge which would not overwrite empty arrays

fix: apply empty arrays as default values but not undefined values

---

packages/amplify-e2e-tests/src/__tests__/tags.test.ts
packages/amplify-provider-awscloudformation/src/amplify-service-manager.js

This includes tags when creating an amplify App

feat: provide tags on create app

---

packages/amplify-e2e-core/src/categories/hosting.ts
packages/amplify-e2e-tests/src/__tests__/hostingPROD.test.ts
packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js

fix hosting category output after CloudFront is removed
fix #402

fix(amplify-provider-awscloudformation): fix hosting output

---

packages/amplify-category-function/resources/awscloudformation/cloudformation-templates/lambda-function-cloudformation-template.json.ejs
packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/storeResources.test.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/lambda-layer-cloudformation-template.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts
packages/amplify-cli-core/src/index.ts
packages/amplify-cli/src/extensions/amplify-helpers/copy-batch.ts
packages/amplify-cli/src/extensions/amplify-helpers/leave-breadcrumbs.ts
packages/amplify-cli/src/extensions/amplify-helpers/read-breadcrumbs.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts

fix(amplify-category-function): use ref for S3Bucket and S3Key in CFN

---

packages/amplify-e2e-tests/src/__tests__/delete.test.ts

`expect(...).toBeTruthy()` => `expect(...).toBe(true)`
`.toBeTruthy()` will return `true` if the `expect`'s argument is an `Error`

test: fix delete test to fail as expected

---

packages/amplify-util-mock/package.json
packages/amplify-util-mock/src/CFNParser/intrinsic-functions.ts
packages/amplify-util-mock/src/CFNParser/lambda-resource-processor.ts
packages/amplify-util-mock/src/__tests__/func/index.test.ts
packages/amplify-util-mock/src/func/index.ts
packages/amplify-util-mock/src/utils/lambda/execute.ts
packages/amplify-util-mock/src/utils/lambda/hydrate-env-vars.ts
packages/amplify-util-mock/src/utils/lambda/load.ts
packages/amplify-util-mock/src/utils/lambda/loadMinimal.ts

Removes deprecated `util` functions: https://nodejs.org/docs/latest-v8.x/api/util.html#util_util_isstring_object

fix(amplify-util-mock): off-by-one array reference and general refactor

---

packages/amplify-e2e-tests/src/__tests__/function_3.test.ts
packages/amplify-python-function-template-provider/resources/hello-world/index.py

*Issue #5914 *
* enables cors support for lambda proxy integrations for python

fix: enables cors support for lambda proxy integrations for python

---

packages/amplify-provider-awscloudformation/src/push-resources.ts

Fixes regression from #6358 where team-provider-info parameters would be overwritten

fix(amplify-provider-awscloudformation): don't overwrite team-provider params

---

packages/amplify-e2e-core/src/categories/lambda-function.ts
packages/amplify-e2e-tests/src/__tests__/function_2.test.ts

E2E tests got stuck due to case mistmatch

test: fix casing for AppSync options when adding function

---

packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-tests/schemas/iterative-push/add-one-key-multiple-models/final-schema.graphql
packages/amplify-e2e-tests/schemas/iterative-push/add-one-key-multiple-models/initial-schema.graphql
packages/amplify-e2e-tests/src/__tests__/schema-iterative-update-2.test.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/amplify-graphql-resource-manager.ts
packages/amplify-provider-awscloudformation/src/iterative-deployment/deployment-manager.ts
packages/amplify-provider-awscloudformation/src/iterative-deployment/helpers.ts
packages/amplify-provider-awscloudformation/src/iterative-deployment/state-machine.ts
packages/amplify-provider-awscloudformation/src/utils/amplify-resource-state-utils.ts

create deployment record which includes previously deployed parameters and capabilities - add action
to bubble up error within state machine

fix(amplify-provider-awscloudformation): use prev deployment vars

---

packages/amplify-cli-core/src/feature-flags/featureFlags.ts
packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-core/src/utils/projectMeta.ts
packages/amplify-migration-tests/src/__tests__/migration_tests/transformer_migration/api.key.migration.test.ts
packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts
packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-transformer-core/src/util/amplifyUtils.ts
packages/graphql-transformer-core/src/util/sanity-check.ts
packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformerLocal.e2e.test.ts

- changed the default to adding GSI when creating a secondary index
- Added sanity check when removing an LSI from an already existing table
- Will maintain previous behavior via a feature flag
```json
{
"features":
{
"graphqltransformer":
{
"secondaryKeyAsGSI": true
}
}
}
```
- re #2702 

feat(graphql-key-transformer): change default to add GSIs when using @key

---

packages/amplify-cli/src/__tests__/get-tags.test.ts
packages/amplify-cli/src/extensions/amplify-helpers/get-tags.ts

The local env file is not present when the root stack is initialized on an existing project. The envName and projectName are extracted from the exeInfo as a fall back

fix: check for local env file and then fall back on exeinfo

---

packages/amplify-e2e-tests/schemas/migrations_key/cant_add_lsi.graphql
packages/amplify-e2e-tests/src/__tests__/migration/api.key.migration1.test.ts

schema fix to use the same type as initial and add ff to keep old lsi

test(amplify-e2e-tests): fix api key lsi migration e2e

---

.github/stale.yml

Removed the pending triage from exempt labels

chore: removed pending triage from stale.yml

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/assets/string-maps.js

#4981
Update Facebook Cognito attribute mapping to be "given_name" => "last_name" instead of "given_name" => "given_name"

fix: correct given_name fb attribute mapping

---

packages/amplify-category-storage/src/index.js
packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js
packages/amplify-e2e-tests/src/__tests__/function_2.test.ts

*Issue #5528
* Added List bucket actions for S3 Triggers in both storage category and functions category.

fix: update list bucket policies for s3 triggers

---

packages/amplify-provider-awscloudformation/src/configuration-manager.ts

fix(amplify-provider-awscloudformation): check local aws config before env vars

---

packages/amplify-provider-awscloudformation/src/attach-backend.js
packages/amplify-provider-awscloudformation/src/configuration-manager.ts

fix(amplify-provider-awscloudformation): ask auth flow type for new envs

---

packages/amplify-app/src/framework-config-mapping.js
packages/amplify-codegen/src/callbacks/postPushCallback.js
packages/amplify-codegen/src/utils/getSchemaDownloadLocation.js
packages/amplify-codegen/tests/callbacks/postPushCallback.test.js
packages/amplify-codegen/tests/utils/getSchemaDownloadLocation.test.js
packages/amplify-frontend-javascript/lib/framework-config-mapping.js

This is based off of #5654. Creating a new PR as I dont have permission to push to MLH fork
#5334 c630145 changed amplify-codegen from hard coding src to using SourceDir in the config file.
This resulted in the default sourceDir value / (system root) for reactnative being used. The PR ensures the schema download location is always with in the project root and mitigates permission issues.
Also the `push` command will show an warning if codegen fails instead failing the whole push operation
fix #5483
Other:
Docs PR: aws-amplify/docs#2581

Codegen fix

---

package.json
packages/amplify-category-predictions/package.json
packages/amplify-category-xr/package.json
packages/amplify-migration-tests/package.json
packages/amplify-migration-tests/src/migration-helpers/check-version.ts
packages/amplify-migration-tests/src/migration-helpers/init.ts
packages/amplify-migration-tests/tsconfig.tests.json
packages/graphql-transformers-e2e-tests/package.json
yarn.lock

updated the husky hooks to compile test file before pushing as these files are not compiled with regular build. With this update errors in the test files will be discovered upfront instead of it happening in CCI

 build: compile test files before push

---

.circleci/config.base.yml
.circleci/config.yml
packages/amplify-cli-core/src/__tests__/tags.test.ts
packages/amplify-cli-core/src/state-manager/stateManager.ts
packages/amplify-cli-core/src/tags/Tags.ts
packages/amplify-e2e-core/src/categories/hosting.ts
packages/amplify-e2e-core/src/cli-test-environment.js
packages/amplify-e2e-core/src/utils/add-circleci-tags.ts
packages/amplify-e2e-core/src/utils/nexpect.ts
packages/amplify-e2e-tests/src/__tests__/hosting.test.ts
packages/amplify-e2e-tests/src/__tests__/tags.test.ts
yarn.lock

1. Added tags to resources created by CircleCI. These tags include build number and build url
2. Updated hosting test to delete the hosting buckets after running the tests
The e2e tests get tags like below:
This change will help identifying which tests are not cleaning up after themselves.

ci: update circle ci build to include tags

---

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/generalQuestionsWalkthrough.ts

#6064
Since we are using the function name as the resource name as well, it must conform to the more restrictive CFN logicId requirements of [a-zA-Z0-9]

fix: correct function resource name validation

---

packages/amplify-go-function-runtime-provider/src/runtime.ts
yarn.lock

https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/3763/workflows/ffd47f18-bd59-4ffb-b904-c16ad2709633
Fix incorrect import

fix: incorrect import and update yarn lock

---

packages/amplify-category-function/src/commands/function/build.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/build.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/package.ts
packages/amplify-dotnet-function-runtime-provider/src/utils/invoke.ts
packages/amplify-e2e-tests/src/__tests__/function_3.test.ts
packages/amplify-e2e-tests/src/__tests__/function_4.test.ts
packages/amplify-java-function-runtime-provider/src/utils/invoke.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts
packages/amplify-util-mock/src/utils/lambda/populate-lambda-mock-env-vars.ts

Fixes the remaining e2e test issues with my previous PRs.
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/3781/workflows/87bc7f52-f22d-4713-873a-97d078a0c7c6
Changed a confirm prompt back to original text to match tests, updated some test expect values to match new mock output (changes now pretty print json instead of printing on single line) and updated function build / package logic to handle cases where other categories depend on the zipping logic (we should remove this tight coupling in the future). Also fixed a couple bugs in the dotnet and java mock executors.

fix: mock bug fixes and e2e test updates

---

packages/amplify-provider-awscloudformation/package.json
packages/amplify-provider-awscloudformation/src/admin-login.ts
packages/amplify-provider-awscloudformation/src/configuration-manager.ts
packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts

https://github.com/aws-amplify/amplify-cli/issues/6593 #6635
Fall back to admin login if token refresh fails. Also fixed a couple of bugs in `amplify configure project`.

fix(amplify-provider-awscloudformation): admin token refresh, configure project

---

packages/amplify-codegen/package.json
packages/amplify-codegen/src/utils/getGraphQLDocPath.js
packages/amplify-codegen/src/walkthrough/add.js
packages/amplify-codegen/src/walkthrough/configure.js
packages/amplify-codegen/tests/utils/getGraphQLDocPath.test.js
packages/amplify-codegen/tests/walkthrough/add.test.js
yarn.lock

fix #6468 
fix #5835 
fix #4147
The generation path for doc files are now correctly configured by sync up with user's prompt glob expression in `includes` field. The fix applies to the following commands.
- `amplify codegen add`
- `amplify codegen configure`

fix(amplify-codegen): correct docFilePath in codegen add and configure

---

packages/amplify-util-mock/src/__tests__/func/index.test.ts
packages/amplify-util-mock/src/func/index.ts

#6653
Handle case where no options are specified to mock

fix: handle no mock args

---

packages/amplify-category-auth/src/provider-utils/supported-services.ts

*Issue #, if  #available:* #6599 
updated oauth prompt help text that appears on doing `amplify update auth` and selecting `I want to learn more` under the question "Do you want to use an OAuth flow? " to mention that selecting "no" will remove existing configuration, if any.

fix(auth): update oauth prompt help text to mention that selecting "no" will remove existing configuration

---

packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-key-transformer/src/__tests__/__snapshots__/KeyTransformer.test.ts.snap

https://github.com/aws-amplify/amplify-js/issues/7495
Currently, when the sync query request resolver for a model receives a sync expression that maps to a DynamoDB Query operation, we're ignoring the `lastSync` value and performing a query against the Base Table. 
In other words,
If we have a model like:
```gql
type User
@model
@key(
name: "byUsername"
queryField: "userByUsername"
fields: ["username", "sortOrder"]
)
```
The following query variables
```json
{
"limit":1000,
"nextToken":null,
"filter":{"and":[{"username":{"eq":"user1"}}]},
"lastSync":1613615765839
}
```
Result in a query on the Base Table
We [should instead be](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-delta-sync.html#sync-queries) retrieving records …

fix(graphql-key-transformer): fix delta with selective sync query

---

packages/amplify-codegen/package.json
packages/amplify-codegen/src/utils/getGraphQLDocPath.js
packages/amplify-codegen/tests/utils/getGraphQLDocPath.test.js

The includePattern in amplify codegen walkthrough is the array type. Fix the wrong type casting issue.

fix(amplify-codegen): use correct array type for includePattern

---

packages/amplify-provider-awscloudformation/src/configuration-manager.ts
packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts

https://github.com/aws-amplify/amplify-cli/issues/6720
https://github.com/aws-amplify/amplify-cli/issues/6593
In some cases appId was not passed back into `getConfigurationForEnv()`, now fixed.
Fixes https://github.com/aws-amplify/amplify-cli/pull/6433, which caused the refreshToken to be overwritten with an empty object.

fix(amplify-provider-awscloudformation): Amplify Admin authentication token refresh

---

packages/amplify-cli/src/__tests__/attach-backend-steps.test.ts
packages/amplify-cli/src/attach-backend-steps/a20-analyzeProject.ts
packages/amplify-cli/src/extensions/amplify-helpers/project-name-validation.ts

*Description of changes:* 
Normalize app names on pull because app names in Amplify console have different validation rules. This change will not rename the app in the cloud.

fix: normalize app names on pull

---

.circleci/config.yml
packages/amplify-e2e-tests/schemas/multi-gsi.graphql
packages/amplify-e2e-tests/src/__tests__/api_4.test.ts
packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-key-transformer/src/__tests__/KeyTransformer.test.ts
packages/graphql-key-transformer/src/__tests__/__snapshots__/KeyTransformer.test.ts.snap
packages/graphql-transformer-common/src/ResourceConstants.ts

#6634
Only sets the composite sort key in the VTL resolver if all fields in the key are preset in the mutation.
Also adds unit and e2e tests for this case.

feat(graphql-key-transformer): only modify GSI sort key when present

---

packages/amplify-velocity-template/src/compile/blocks.js

*Issue #, if available:* #6450
In the velocity template parser, some block statements can return `null` (for example `#return`). The use of the `||` operator was causing `null` to be replaced with the empty string. This commit allows the `null` values to be propagated back up the call stack.
Line 37 in `packages/amplify-velocity-template/src/compile/blocks.js` is the only change. Everything else was changed by automation.

fix(amplify-velocity-template): propagate null block return values

---

packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts
packages/amplify-e2e-core/src/categories/api.ts

Customers often struggle quite a bit to figure out how to enable/disable conflict detection with the CLI.   They can do it via the top level "Enable DataStore for entire API" or "Disable DataStore for entire API" options, but if they choose to walk through all options, they are forced to explicit decide if conflict detection should be enabled or not.  I've been confused by this myself.  Initially I thought that the "Configure conflict detection?" step was just a question asking if I wanted to make a _change_ to the current value.  That's not the case.  If you answer "y", it _enables_ conflict detection.  If you answer "n", it _disables_ conflict detection.  This PR changes the wording so that customers know that this is causing an action.
By submitting this pull request, I confirm that my …

fix: Enable, instead of Configure, conflict detection

---

packages/amplify-appsync-simulator/package.json
packages/amplify-appsync-simulator/src/__tests__/scalars/AWSEmail.test.ts
packages/amplify-appsync-simulator/src/__tests__/scalars/AWSURL.test.ts
packages/amplify-appsync-simulator/src/__tests__/scalars/__snapshots__/AWSEmail.test.ts.snap
packages/amplify-appsync-simulator/src/__tests__/scalars/__snapshots__/AWSURL.test.ts.snap
packages/amplify-appsync-simulator/src/schema/appsync-scalars/index.ts

*Issue #, if available:* #6656
This commit removes the dependency on `graphql-scalars` and adds the implementations for the `AWSEmail` and `AWSURL` scalars.

fix(amplify-appsync-simulator): remove graphql-scalars dependency

---

packages/amplify-appsync-simulator/src/__tests__/resolvers/pipeline-resolver.test.ts
packages/amplify-appsync-simulator/src/resolvers/function.ts
packages/amplify-appsync-simulator/src/resolvers/pipeline-resolver.ts
packages/amplify-appsync-simulator/src/resolvers/unit-resolver.ts
packages/amplify-appsync-simulator/src/velocity/index.ts

*Issue #, if available:* #6640
*Description of changes:* This commit detects templates that use `$util.error` and stops execution from propagating further.

fix(amplify-appsync-simulator): bail out early on exceptions

---

packages/amplify-cli/src/execution-manager.ts

*Issue #, if available:* #6757
This commit adds optional chaining and nullish coalescing to the `isContainersEnabled()` function. It also stores the project config in a variable instead of parsing it multiple times.

fix(cli): add defensive coding to isContainersEnabled()

---

packages/amplify-cli/src/extensions/amplify-helpers/get-frontend-plugins.ts
packages/amplify-cli/src/index.ts
packages/amplify-cli/src/init-steps/s9-onFailure.ts

- fix: #6681 - provide proper DX when frontend plugins cannot be found in the system during init.
- add an `uncaughtException` and `unhandledRejection` handler to the CLI process to get better error handling when errors are raised from some async or `EventEmitter` handler based code.

fix: #6681, handling case when no frontend plugins found

---

packages/amplify-cli-core/src/feature-flags/featureFlags.ts

Added Feature Flags for some of the enhancements made to `amplify-codegen` in the migrated packages. 
This PR needs to be looked into in combination with:
- https://github.com/aws-amplify/amplify-codegen/pull/85
- https://github.com/aws-amplify/amplify-codegen/pull/89
And the relevant docs PR: 
https://github.com/aws-amplify/docs/pull/2983

Add feature flags for new codegen features

---

packages/amplify-dynamodb-simulator/__test__/index.test.js
packages/amplify-dynamodb-simulator/index.js

*Issue #, if available:* #5078
This commit updates the dynamodb simulator to detect errors logged to stderr by the Java process. Currently, only a single error type is detected, but others could be added as well.
Note - there are other ways to handle the error reported in #5078. For example, `dbPath` could be validated as an absolute path before trying to launch the simulator. I went with the current approach because I thought it could be extended to other errors that the simulator process might report. I can change the approach here if that is desirable.

fix(amplify-dynamodb-simulator): detect errors logged to stderr

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/index.js
packages/amplify-console-integration-tests/src/pullAndInit/pullProject.ts
packages/amplify-e2e-tests/src/environment/env.ts
packages/amplify-provider-awscloudformation/src/resourceParams.js

fix #5942 #6430
This change check if hostedUI is enabled and if the hostedUIProviderCreds are not available it inserts it
Rework with test fix from https://github.com/aws-amplify/amplify-cli/pull/6485

feat: remove OAuth prompt from pull and new env

---

packages/amplify-graphiql-explorer/package.json
packages/amplify-graphql-docs-generator/package.json
packages/amplify-graphql-types-generator/package.json
yarn.lock

- chore: change back min version of node to 10.x for docs generator and type generator
- update react-scripts to 4.0.3 to removed immer dependabot warning

chore: update react-script dependency and set min nodejs version to 10.x for  2 packages

---

packages/amplify-provider-awscloudformation/src/__tests__/utils/admin-login-server.test.ts
packages/amplify-provider-awscloudformation/src/utils/admin-login-server.ts

CLI uses express server in `amplify-provider-awscloudformation` to listen to POST request from Admin UI login page when `amplify configure`. The default of the hostname is localhost, 0.0.0.0 and 127.0.0.1 on macOS, but Ubuntu on WSL on Windows uses the only localhost by default. Since 127.0.0.1 seems to be coded in Admin UI, we should specify 127.0.0.1 as the hostname in CLI so that CLI can finish `amplify configure`.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/6779
Fixes: https://github.com/aws-amplify/amplify-adminui/issues/134

fix(amplify-provider-awscloudformation): specify 127.0.0.1 as hostname

---

packages/amplify-cli/src/project-config-version-check.ts

This PR enhances a case for NodeJS version detection when the project is not yet initialized or or is a broken state (after ctrl+c during a pull) to not to fail but handle it accordingly or give back meaningful error message when a non-version value was found in `project-config.json`.

chore: enhance project version detection

---

packages/amplify-category-api/resources/awscloudformation/container-templates/dockercompose-rest-express/express/Dockerfile
packages/amplify-category-api/resources/awscloudformation/container-templates/dockercompose-rest-express/python/Dockerfile
packages/amplify-category-api/resources/awscloudformation/container-templates/dockerfile-rest-express/Dockerfile
packages/amplify-category-api/resources/awscloudformation/container-templates/graphql-express/Dockerfile
packages/amplify-container-hosting/resources/express-template/Dockerfile
packages/amplify-container-hosting/resources/simple-template/Dockerfile

Remove pinned version from container deployed images to make sure the latest prod image is deployed always on fresh deployments.

chore: use latest prod versions of docker images

---

packages/amplify-e2e-core/src/index.ts
packages/amplify-e2e-core/src/init/adminUI.ts
packages/amplify-e2e-core/src/init/index.ts
packages/amplify-e2e-core/src/utils/projectMeta.ts
packages/amplify-e2e-core/src/utils/sdk-calls.ts
packages/amplify-e2e-tests/src/__tests__/api_2.test.ts
packages/amplify-provider-awscloudformation/src/admin-modelgen.ts
packages/amplify-provider-awscloudformation/src/aws-utils/aws-amplify-backend.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts

This PR calls the Amplify Admin Service API post-deployment/post-push in the CLI to generate DataStore models in the cloud for the Admin UI CMS. This action is triggered only when Admin UI is enabled for the app + DataStore is enabled for the API.

feat: generate datastore models for Admin CMS to consume post-deployment from CLI

---

packages/amplify-cli/package.json
packages/amplify-provider-awscloudformation/package.json
packages/amplify-util-mock/package.json
yarn.lock

These changes will fix the failing beta CLI builds due to codegen specifying the upstream CLI dependencies incorrectly. Please refer to this PR: https://github.com/aws-amplify/amplify-codegen/pull/101/files

fix(amplify-codegen): update dependency on amplify-codegen to latest

---

packages/amplify-cli-core/src/feature-flags/featureFlags.ts
packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-key-transformer/src/__tests__/KeyTransformer.test.ts

*Issue #5715 
* Added a check @key to skip updating Input types when user defined input in mutation
* Added a FF : skipOverrideMutationInputTypes to skip changes in existing projects
* added unit tests for the same

fix: gql compiler fix for user defined mutation

---

.circleci/config.yml
packages/amplify-cli/src/index.ts
packages/amplify-provider-awscloudformation/src/admin-modelgen.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts

- Restrict NodeJS migration to happen only during `push` command and don't run under CI/CD
- Remove AdminUI modelgen error message

chore: restrict nodejs version migration execution, remove adminui modelgen error message

---

packages/amplify-cli/src/project-config-version-check.ts
packages/amplify-e2e-tests/src/__tests__/migration/node.function.test.ts

chore: fix nodejs migration e2e test
chore: fix configuration for yaml parser to handle Fn::GetAtt correctly

chore: fix nodejs migration e2e test and yaml parsing

---

packages/amplify-e2e-core/src/init/initProjectHelper.ts
packages/amplify-e2e-core/src/utils/nexpect.ts
packages/amplify-e2e-tests/src/__tests__/migration/node.function.test.ts

chore: add CI detection disable capability to e2e tests, update nodejs migration test

chore: add ci detect disable to e2e test

---

.circleci/config.base.yml
.circleci/config.yml
packages/amplify-e2e-core/src/utils/sdk-calls.ts
packages/amplify-e2e-tests/package.json
packages/amplify-e2e-tests/sample.env
packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts
scripts/e2e-test-regions.ts
scripts/split-e2e-tests.ts
yarn.lock

updated the repository to include a cleanup script which deletes stale
resources left over by the e2e test. These scripts get run at the end
of each e2e test and at the end of the workflow.
The script will also run twice a day to clean up any resources that
were left out due to the cancellation of test workflow
Sample run: https://app.circleci.com/pipelines/github/yuth/amplify-cli/888/workflows/c1bf1141-4615-4180-8fa2-1c5c1005cf40

ci: update CircleCI workflow to run cleanup script

---

packages/graphql-transformers-e2e-tests/src/cognitoUtils.ts

Fix the missing region in the new docker image to fall back to us-west-2 in case no `CLI_REGION` env var is defined.

test(graphql-transformers-e2e-tests): set fallback region for cognito

---

packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs

Fix issue where custom sms auth message was not set in CFN template

fix: add sms auth message to cfn template

---

packages/amplify-python-function-runtime-provider/shim/shim.py

Fixes issue with mocking python handlers that import other relative dependencies

fix: set sys.modules when loading python handler

---

install

Rosetta will automatically kick in when x64 architecture is detected. We should still allow M1 MacBooks to install the packaged CLI.
- https://github.com/aws-amplify/amplify-cli/issues/6312
- Forces the x64 binary download of the packaged CLI
- Rosetta built-in to M1 MacBooks will automatically translate the x64 binary during runtime

Enables M1 MacBooks support for packaged CLI support

---

packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-key-transformer/src/__tests__/__snapshots__/KeyTransformer.test.ts.snap

https://github.com/aws-amplify/amplify-js/issues/7923
Minor change that adds a check if `lastSync == 0` in the sync query resolver when attempting to construct a query expression.

fix(graphql-key-transformer): check if lastSync == 0 in selective sync resolver

---

packages/amplify-appsync-simulator/src/__tests__/velocity/util/graphql-info.test.ts
packages/amplify-appsync-simulator/src/velocity/util/info.ts

When the parameter values contains objects, the `selectionSetGraphQL` field from `context.info` is wrongly generated.
See:
https://github.com/bboure/serverless-appsync-simulator/issues/49

fix(amplify-appsync-simulator): graphql info selectionset

---

packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/add-to-group.js

*Description of changes:* we use both `async` and `callback` style lambda functions in the functions we generate for people. [this is an antipattern](https://dev.to/theburningmonk/common-node-js-mistakes-in-lambda-4a4j)

fix add-to-group.js template from using mixed async/sync AWS Lambda code style

---

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/constants.test.ts
packages/amplify-cli/src/extensions/amplify-helpers/constants.ts

fix(cli): freeze constants object to not be changed

---

packages/amplify-provider-awscloudformation/src/__tests__/aws-utils/aws-cfn.test.js
packages/amplify-provider-awscloudformation/src/__tests__/iterative-deployment/stack-progress-printer.test.ts
packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js
packages/amplify-provider-awscloudformation/src/iterative-deployment/stack-progress-printer.ts

fix(amplify-provider-awscloudformation): reverse asc events

---

packages/amplify-provider-awscloudformation/src/__tests__/utils/admin-login-server.test.ts

This PR is to address @jhockett's comment on https://github.com/aws-amplify/amplify-cli/pull/6780#discussion_r586647736 and remove unused stub methods from the test.

test(amplify-provider-awscloudformation): minify context stub

---

packages/amplify-cli/src/__tests__/commands/env.test.ts
packages/amplify-cli/src/commands/env.ts

*Issue #, if available:* https://github.com/aws-amplify/amplify-cli/issues/6188
*Description of changes:* This commit aliases `amplify env ls` to `amplify env list`

feat(cli): add 'amplify env ls' alias

---

packages/amplify-e2e-tests/src/__tests__/function_3.test.ts
packages/amplify-python-function-template-provider/resources/hello-world/index.py

We need a JSON string for the body in order to access it in our response message. See this comment: https://github.com/aws-amplify/amplify-js/issues/6390#issuecomment-740757548
I had this issue with my own function which was returning null on my JSON.stringify(response). I found the above comment and it made it work! i.e. I could access the return body.
No issue created as it's a one-line change.
Adding `json` library import and `json.dumps()` call in `packages/amplify-python-function-template-provider/resources/hello-world/index.py`
Updating relevant unit test in `packages/amplify-e2e-tests/src/__tests__/function_3.test.ts` by adding a `JSON.stringify()` call to match the `json.dumps()` call in the source file.
If there's an issue with …

fix: adding JSON stringify to example python function

---

packages/amplify-category-predictions/provider-utils/awscloudformation/cloudformation-templates/s3-cloudformation-template.json.ejs
packages/amplify-category-storage/resources/cloudformation-templates/s3-cloudformation-template.json.ejs

Hi all,
we have noticed that adding permissions to a lambda function that is triggered by another resource (e.g. an S3 bucket) will *remove* the permissions that lambda has on the triggering resource -- and you cannot re-add those permissions as that will introduce a cyclic dependency (the storage-stack depends on the function and the function-stack depends on the bucket). This is the behavior described in #1913 as well.
This behaviour is caused by using the same name `amplify-lambda-execution-policy` for both policies generated by the triggering resource and when adding permissions to the lambda.
I have solved that for now by changing the name of the policy generated by the triggering resource.
For now I have doubts about the following references to the name …

fix: use non-duplicate names for lambda execution role

---

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/path-manager.test.ts

Increase test coverage of amplify-cli package.
Note:
I faced an issue of jest https://github.com/facebook/jest/issues/10996 to change a behaviour of mocked modules and added tests for happy path for now.

test(cli): add test for path-manager extension

---

packages/amplify-provider-awscloudformation/src/system-config-manager.js

The configuration files can exist on a read-only mountpoint, and attempting to change the permissions
will fail then _even if the permissions are fine as they are_.

fix: do not attempt to modify a file when reading it

---

packages/amplify-provider-awscloudformation/package.json
packages/amplify-provider-awscloudformation/src/setup-new-user.js

*Issue #, if available:* Closes #6836 and #5664 
Escapes $ in IAM user creation URL string for Windows & WSL environments, since powershell treats it as environment var and therefore ignores it.
_More details_:
- Checks whether the platform is windows or WSL.
- using `process.platform` to check for windows.
- using an existing dependency `is-wsl` ( `open` depends on `is-wsl` ) to check for wsl.
- if it is either windows or wsl, $new is replaced by \`$new in deepLinkURL. on line 53, deepLinkURL is printed without ` to ensure that correct url is shown in the terminal.

fix(amplify-provider-awscloudformation): Fix amplify configure opening wrong IAM User Creation URL in Windows & WSL

---

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.test.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts
packages/amplify-e2e-core/src/utils/index.ts
packages/amplify-e2e-tests/functions/get-api-appsync.js
packages/amplify-e2e-tests/functions/mutation-appsync.js
packages/amplify-e2e-tests/src/__tests__/function_2.test.ts

when using the ff for generating the appsync iam policy use the old format if the ff is empty
ref #6675

fix(amplify-category-api): mantain ff in iam api policy

---

.circleci/config.yml
packages/amplify-e2e-tests/src/__tests__/function_3.test.ts

don't stringify string to compare to incoming string

feat(amplify-e2e-tests): removed json stringify

---

packages/amplify-appsync-simulator/src/__tests__/velocity/util/general-utils.test.ts
packages/amplify-appsync-simulator/src/velocity/util/general-utils.ts

AppSync utils uses `encodeURIComponent()` and `decodeURIComponent()` over `decodeURI` and `encodeURI`.
*Issue #, if available:* I haven't created the issue because I tested myself in the AppSync. 
Using the context: 
```
{
"identity": {
"accountId": "id-accountId",
"cognitoIdentityPoolId": "id-cognitoIdentityPoolId",
"cognitoIdentityId": "id-cognitoIdentityId",
"sourceIp": [
"x.x.x.x"
],
"username": "12314%40N32",
"userArn": "my:user:arn"
}
}
``` 
With the resolver: 
```
{
":userId": $util.dynamodb.toStringJson($util.urlDecode($context.identity.username))
}
```
You can see that AppSync decodes `12314%40N32` to `12314@N32`. 
It seems that
**decodeURI()**: It takes encodeURI(url) string so it cannot decoded characters (, / ? : @ & = + $ #)
**decodeURIComponent()**: …

Use encodeURIComponent over encodeURI

---

packages/amplify-category-notifications/lib/auth-helper.js
packages/amplify-category-notifications/lib/multi-env-manager.js
packages/amplify-category-notifications/lib/pinpoint-helper.js
packages/amplify-cli/src/extensions/amplify-helpers/remove-env-from-cloud.ts
packages/amplify-e2e-core/src/utils/sdk-calls.ts
packages/amplify-e2e-tests/src/__tests__/notifications.test.ts

*Issue #, if available:* #6866
This commit updates the notification delete process to remove the IAM policy that is created. This allows CloudFormation to clean up successfully (and removes the policy that was being left behind).

fix(amplify-category-notifications): clean up notifications IAM policy

---

packages/amplify-category-notifications/lib/auth-helper.js
packages/amplify-category-notifications/lib/multi-env-manager.js
packages/amplify-category-notifications/lib/pinpoint-helper.js
packages/amplify-cli/src/extensions/amplify-helpers/remove-env-from-cloud.ts
packages/amplify-e2e-core/src/utils/sdk-calls.ts
packages/amplify-e2e-tests/src/__tests__/notifications.test.ts

Reverts aws-amplify/amplify-cli#6872
Reverting for now as this needs the following policy to work 
- `iam:ListAttachedRolePolicies`

Revert "fix(amplify-category-notifications): clean up notifications IAM policy"

---

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts

*Issue #, if available:* Fixes #6719 
Package: amplify-category-function
Removes the validator for the prompt question: 'Select the categories you want this function to have access to.'
Fixes bug where user had to have atleast one category selected. This PR allows user to deselect all category options during that prompt.

fix: #6719 remove validator on function categories access prompt

---

packages/amplify-cli/src/extensions/amplify-helpers/delete-project.ts

I know I may be in the minority with my rejection of dark mode, but there are others like me too!    The `amplify delete` confirmation prompt is almost unreadable in my terminal:
This PR updates the message so that the text is all red.  I'm open to other suggestions for colors, but yellow just doesn't work.

fix: delete prompt text should be red, not yellow

---

packages/amplify-appsync-simulator/src/__tests__/velocity/index.test.ts
packages/amplify-appsync-simulator/src/velocity/index.ts

Some of the java methods would not work on the `$ctx.info` object. This PR makes sure they get converted to java Objects
*It works on my machine* 🙂 

fix(amplify-appsync-simulator): map info to Java objects

---

packages/amplify-util-mock/src/__tests__/utils/lambda/populate-cfn-params.test.ts
packages/amplify-util-mock/src/api/api.ts
packages/amplify-util-mock/src/utils/lambda/populate-cfn-params.ts

This commit updates function mocking to use the mock AWS access key value when the mock API server is running.
https://github.com/aws-amplify/amplify-cli/issues/6897
Local testing and unit tests.

fix(amplify-util-mock): mock AWS access key when server is running

---

packages/amplify-cli/src/__tests__/commands/env.test.ts
packages/amplify-cli/src/commands/env.ts

Added a warning log when a invalid subcommand for env is entered. 
Fixes #4969
Ran an invalid subcommand to check if the warning log was getting printed.

fix(amplify-cli): add a warning on entering invalid subcommand for amplify env

---

packages/amplify-go-function-runtime-provider/resources/localinvoke/main.go

This commit addresses two issues with deadline logic:
1. The timeout in milliseconds is converted to nanoseconds for
use with Go's Durations.
2. The deadline is updated to be time.Now() plus the provided
timeout. This prevents the function from being invoked with
an expired deadline.
#6407
Manual testing using the function provided in #6407

fix(amplify-go-function-runtime-provider): update deadline logic

---

.circleci/config.yml
packages/amplify-category-auth/resources/adminAuth/admin-queries-api-template.json.ejs
packages/amplify-e2e-tests/src/__tests__/function_2.test.ts

Fixes bug in creating a function with permissions to the AdminQueries API. The operation fails because the AdminQueries API does not output it's Id.
Fixes #6576
Added integration test to verify if lambda is added with AdminQueries API permissions.

fix(amplify-category-auth): add lambda with AdminQueries API permissions

---

packages/amplify-provider-awscloudformation/src/amplify-service-manager.js
packages/amplify-provider-awscloudformation/src/delete-env.js

#4952 
I deleted environment by creating two env in two different accounts also validate my changes by using admin ui credentials https://docs.amplify.aws/console/adminui/extend-cli#to-install-the-amplify-cli

fix(amplify-provider-awscloudformation): overriding credentials for env

---

packages/amplify-category-notifications/lib/auth-helper.js
packages/amplify-category-notifications/lib/multi-env-manager.js
packages/amplify-category-notifications/lib/pinpoint-helper.js
packages/amplify-cli/src/extensions/amplify-helpers/remove-env-from-cloud.ts
packages/amplify-e2e-core/src/utils/sdk-calls.ts
packages/amplify-e2e-tests/src/__tests__/notifications.test.ts

This is a revert of the revert in #6944. The relevant docs PR is https://github.com/aws-amplify/docs/pull/3081.
#6944, #6872, #6866

Reland: fix(amplify-category-notifications): clean up notifications IAM policy

---

package.json
scripts/link-bin.js
yarn.lock

Using the [pnpm/cmd-shim](https://github.com/pnpm/cmd-shim) library instead of [npm/cmd-shim](https://github.com/npm/cmd-shim) would fix the cross-drive linking issue for amplify-dev on Windows. [A PR](https://github.com/pnpm/cmd-shim/pull/18) on `pnpm/cmd-shim` fixed the issue whereas it's still [not fixed](https://github.com/npm/cmd-shim/issues/21) on `npm/cmd-shim`.
This PR adds the `pnpm/cmd-shim` library and updates the imports in `scripts/link-bin.js`
fixes #6950 
I checked the file at `C:\Users\Pawan\AppData\Local\Yarn\bin\amplify-dev.ps1` for proper linking and verified that the `amplify-dev` command is properly running in sample projects.

fix: cross-drive linking support for amplify-dev

---

.circleci/config.yml
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts

This PR adds a small condition to the step which prints info when a lambda function resource permissions are updated. This is in reference to my comment [here](https://github.com/aws-amplify/amplify-cli/pull/6766#issuecomment-805291533).
Tried removing resource access permissions from a lambda when lambda had access to only 1 resource. This means that after removing resource permissions the lambda should not have access to any resource attributes as environment variables and hence the line should not be printed as info.

fix(amplify-category-function): add condition for info printing

---

packages/amplify-provider-awscloudformation/src/__tests__/iterative-deployment/stack-progress-printer.test.ts

This test was failing locally because the output contains colors that are not present in the assertion logic.
N/A
Ran the test locally.

fix(amplify-provider-awscloudformation): fix test

---

packages/amplify-appsync-simulator/src/__tests__/utils/graphql-runner/query-and-mutation.test.ts
packages/amplify-appsync-simulator/src/utils/expose-graphql-errors.ts

Since [version 1.25.1 of amplify-appsync-simulator](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-appsync-simulator/CHANGELOG.md#1251-2021-02-10), the behavior when an error occurs in a resolver has changed.
When I am using Lambda as DataSource and an error occurs in Lambda, the error type is not GraphQLError. The errors are passed by `context.appsyncErrors`. The errors are filtered out from `errors` by `exposeGraphQLErrors` and I can not refer the error in `response.vtl`.
**It can also lead to necessary errors being filtered out from `errors`.**
In a real environment, the error does not seem to be filtered out.
I have removed the filter with GraphQLError and added a test to reproduce the issue.
By submitting …

fix(amplify-appsync-simulator): expose other than GraphQLError

---

packages/graphql-relational-schema-transformer/src/RelationalDBResolverGenerator.ts
packages/graphql-relational-schema-transformer/src/__tests__/RelationalDBResolverGenerator.test.ts
packages/graphql-relational-schema-transformer/src/__tests__/__snapshots__/RelationalDBResolverGenerator.test.ts.snap

Check the primary key type in order to generate a valid SQL statement to string and none string data types
[#5392 Update Mutations is not working in Serverless RDS GraphQ](https://github.com/aws-amplify/amplify-cli/issues/5392) 
The **Update** statement wasn't checking if the primary key was a String data type, so the sql statement generated didn't work 
The same behavior applies to the **Delete** sql statement
The change address this issues
```
{
"version": "2018-05-29",
"statements":   [
"UPDATE Tomatoes SET $update WHERE id=$ctx.args.updateTomatoesInput.Id",
"SELECT * FROM Tomatoes WHERE id='$ctx.args.updateTomatoesInput.Id'"
]
}
```
```
{
"version": "2018-05-29",
"statements":   [
"UPDATE Tomatoes SET $update WHERE …
```

fix(graphql-relational-schema-transformer): escape String primary key

---

packages/amplify-provider-awscloudformation/src/iterative-deployment/deployment-manager.ts

cfn is async to ddb gsi creation slowing the api call can wait for gsi operation to start before
checking a table with potentially wrong info

fix(amplify-provider-awscloudformation): add slow down on index check

---

packages/amplify-e2e-core/src/categories/lambda-function.ts

Fixed e2e test: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/27/workflows/2c0fd343-d520-4ccf-9bc9-9132f546e23b/jobs/410/steps
Ran failing e2e test locally:
amplify add function with additional permissions
✓ environment vars comment should update on permission update (92481 ms)

test: remove extraneous 'y' response from function e2e

---

packages/amplify-e2e-core/src/categories/lambda-function.ts

Fix failing e2e tests caused by previous PR https://github.com/aws-amplify/amplify-cli/pull/7031. The 'y' response is needed for `amplify add function`, but not used in `amplify update function`.
Full e2e run of function_2.test.ts
Test Suites: 1 passed, 1 total
Tests:       11 passed, 11 total
Snapshots:   1 passed, 1 total
Time:        3406.696 s

test: add the 'y' response back only for create flow in function e2e

---

.circleci/config.yml
packages/amplify-appsync-simulator/src/__tests__/scalars/AWSTimestamp.test.ts
packages/amplify-appsync-simulator/src/schema/appsync-scalars/index.ts

This commit updates the `AWSTimestamp` custom scalar to return literals as integers instead of strings. The AST representation of a literal is always a string, so it needs to be converted to an int before returning it for further processing.
https://github.com/aws-amplify/amplify-cli/issues/6436
Manual testing and unit tests added in this PR.

fix(amplify-appsync-simulator): parse AWSTimestamp literals as Ints

---

.github/ISSUE_TEMPLATE/2.feature_request.md
.github/ISSUE_TEMPLATE/3.usage-question.md
.github/workflows/release-follow-up.yaml
CONTRIBUTING.md

- Introduce an action to update issues/PRs referenced in published releases using https://github.com/marketplace/actions/release-follow-up
Any issue linked in the release body with the pattern `/<current-repo>/issues/<issue-number>` will be matched. If the issue exists in the current repo, a comment will be added referencing the release link. The corresponding `pending-release` label will be removed if it's present and the `referenced-in-release` label added.
Currently, issues and PRs are **not closed**, only commented on.
Also, 
- minor updates contrib guide
- replace the link to Amplify Console forum w/ GH 
- test the GH action in sandbox repos using similar labels
- test against the same changelog/release notes structure as the CLI repo
By submitting this pull request, I confirm that …

Add GitHub Action to update issues/PRs referenced in published releases

---

packages/amplify-category-function/src/index.ts

The PR clones the group name for postconfirmation trigger on group in the team-provider info
fixes: #2841
```bash
cd packages/amplify-e2e-tests
yarn e2e src/__tests__/function_*
yarn e2e src/__tests__/auth_*
```

fix: assign group env from source

---

.circleci/config.yml
packages/amplify-e2e-core/src/configure/index.ts
packages/amplify-e2e-core/src/init/initProjectHelper.ts
packages/amplify-provider-awscloudformation/src/aws-regions.js
packages/amplify-provider-awscloudformation/src/aws-utils/aws-amplify.js

https://github.com/aws-amplify/amplify-cli/pull/3992 added a list of supported regions in amplify-e2e-core. When https://github.com/aws-amplify/amplify-cli/pull/4092 was merged, it added a second list of supported regions, which has drifted from the other list. This commit consolidates the two lists.
Ran an e2e test locally.

fix(amplify-e2e-core): update source of truth for supported regions

---

.circleci/config.yml
packages/amplify-cli/src/commands/push.ts

This commit updates the push error handling to show the full schema errors from GraphQL compilation.
https://github.com/aws-amplify/amplify-cli/issues/6999
Attempted to push a GraphQL schema with errors and verified that all of the schema details were displayed.

fix(cli): display gql schema errors on failed push

---

.circleci/config.yml
packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-key-transformer/src/__tests__/KeyTransformer.test.ts

The `graphql-key-transformer` was making the `id` field required in the schema built after running the command `amplify api gql-compile`. This happens in case when the `id` field is defined as a secondary index in the `graphql.schema`.
Fixes #6630 
Added a unit test for the case when `id` is defined as secondary index in `graphql` schema

fix(graphql-key-transformer): optional id field if id not primary key

---

.circleci/config.yml
jest.config.js
packages/amplify-cli-core/src/errors/index.ts
packages/amplify-cli/src/__tests__/context-manager.test.ts
packages/amplify-cli/src/__tests__/usage-data.test.ts
packages/amplify-cli/src/__tests__/version-manager.test.ts
packages/amplify-cli/src/app-config/config.ts
packages/amplify-cli/src/commands/configure.ts
packages/amplify-cli/src/commands/publish.ts
packages/amplify-cli/src/commands/pull.ts
packages/amplify-cli/src/context-manager.ts
packages/amplify-cli/src/domain/amplify-usageData/IUsageData.ts
packages/amplify-cli/src/domain/amplify-usageData/NoUsageData.ts
packages/amplify-cli/src/domain/amplify-usageData/UsageData.ts
packages/amplify-cli/src/domain/amplify-usageData/UsageDataPayload.ts
packages/amplify-cli/src/domain/amplify-usageData/VersionManager.ts
packages/amplify-cli/src/index.ts
packages/amplify-cli/src/initialize-env.ts
packages/amplify-provider-awscloudformation/src/amplify-sts.ts
packages/amplify-provider-awscloudformation/src/aws-utils/aws-sts.ts
packages/amplify-provider-awscloudformation/src/utility-functions.js

Added additional fields to the usage data payload.

feat: added new fields to usage data

---

packages/amplify-provider-awscloudformation/src/__tests__/system-config-manager.test.ts
packages/amplify-provider-awscloudformation/src/configuration-manager.ts
packages/amplify-provider-awscloudformation/src/system-config-manager.js

throw helpful error if profile is missing keys, adapted from @nikhname's PR: https://github.com/aws-amplify/amplify-cli/pull/6567
#5777
Added unit tests and validated manually

fix(amplify-provider-awscloudformation): throw helpful error if profile is missing keys

---

packages/amplify-frontend-javascript/lib/configuration-manager.js
packages/amplify-frontend-javascript/lib/framework-config-mapping.js

fix(amplify-frontend-javascript): add project path to angular

---

packages/amplify-cli/src/extensions/amplify-helpers/git-manager.ts

Adds amplifyconfiguration.dart to gitignore list
1. Ran amplify-dev init locally.
2. Confirmed that .gitignore file was updated:
```
#amplify
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/logs
amplify/mock-data
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
amplify/backend/.temp
build/
dist/
node_modules/
aws-exports.js
awsconfiguration.json
amplifyconfiguration.json
amplifyconfiguration.dart
amplify-build-config.json
amplify-gradle-config.json
amplifytools.xcconfig
.secret-*
```

fix(cli): adds dart config to git ignore

---

.circleci/config.yml
packages/amplify-e2e-core/src/configure/index.ts
packages/amplify-e2e-tests/src/__tests__/configure-project.test.ts
packages/amplify-provider-awscloudformation/src/configuration-manager.ts

amplify configure project would not update `local-aws-info.json` when selecting "AWS access keys" in some cases.

fix: amplify configure project not updating access keys correctly

---

packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-walkthrough.js

This PR fixes two issues related to `amplify api add-graphql-datasource`:
1. Error handling is added so that the spinner does not keep the process alive in the case of an error. This is the first commit, and it wraps existing code in a `try...catch` block.
2. Additional error messaging is provided when the provided secret does not contain valid credentials for Aurora Serverless. This is the second commit.
#4384
Set up an Aurora Serverless cluster. Attempt to connect using a secret with both valid and invalid credentials.

fix: handle errors and provide better error message when adding data source

---

packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js

This commit updates `getStackEvents()` to reject on error. Prior to this change, an unhandled rejection would be created, but not returned for proper handling.
https://github.com/aws-amplify/amplify-cli/issues/7004

fix: return rejected promise in getStackEvents()

---

packages/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts

This commit skips over the admin queries REST API when consolidating the user's REST APIs.
Refs: https://github.com/aws-amplify/amplify-cli/issues/2084
Ran several failing E2E tests.

fix: skip admin queries when consolidating REST APIs

---

packages/amplify-category-storage/resources/triggers/s3/index.js
packages/amplify-util-mock/src/storage/storage.ts

Fixes the loadLambdaConfig call when executing a mock storage trigger. Also added a try catch around the lambda invocation so if it fails the whole mock server doesn't crash. Also changed the default storage trigger template from using the deprecated `context.done()` to using `async`
#7052
Validated running the mock server locally. This change is in old code that does not have tests and is not easily testable. However, I added TS types that will catch this error at compile time now.

fix: mock storage trigger invocation

---

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/get-cloud-init-status.test.ts

test(cli): add test for get cloud init status extensions

---

packages/amplify-category-function/src/commands/function/remove.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts
packages/amplify-cli-core/src/index.ts
packages/amplify-cli/src/extensions/amplify-helpers/remove-resource.ts

This PR fixes 3 error found during bugbash:
- filter out selected resource and Lambda Layers always from IAM access lists when access being added to functions
- When dependency error happens during resource remove don't print stacktrace
- Remove double resource prompt for `function remove`.
Manual testing

fix: 3 errors found during bugbash

---

packages/amplify-provider-awscloudformation/src/__tests__/system-config-manager.test.ts
packages/amplify-provider-awscloudformation/src/system-config-manager.ts

- Update profile logic to skip credential validation when the AWS `config` file has credential_process defined
- Add missing function parameter types for `system-config-manager.ts`
- Fixes support for using credentials sourced by an external process: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html
`yarn test` and manually tested multiple aws profile configurations

fix: skip credential validation when config has credential_process

---

packages/amplify-e2e-core/src/categories/auth.ts
packages/amplify-e2e-tests/src/__tests__/api_2.test.ts
packages/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts

It is possible that older REST APIs have never been updated to include the `policyResourceName` field on paths. This commit ensures that the field is present.
https://github.com/aws-amplify/amplify-cli/issues/7190
https://github.com/aws-amplify/amplify-cli/issues/7201

fix: ensure policy resource name when pushing REST APIs

---

jest.config.js
packages/amplify-graphql-function-transformer/.npmignore
packages/amplify-graphql-function-transformer/CHANGELOG.md
packages/amplify-graphql-function-transformer/README.md
packages/amplify-graphql-function-transformer/package.json
packages/amplify-graphql-function-transformer/src/__tests__/__snapshots__/amplify-graphql-function-transformer.test.ts.snap
packages/amplify-graphql-function-transformer/src/__tests__/amplify-graphql-function-transformer.test.ts
packages/amplify-graphql-function-transformer/src/graphql-function-transformer.ts
packages/amplify-graphql-function-transformer/src/index.ts
packages/amplify-graphql-function-transformer/tsconfig.json
packages/amplify-graphql-transformer-core/package.json
packages/amplify-graphql-transformer-core/src/index.ts
packages/amplify-graphql-transformer-core/src/utils/directive-wrapper.ts
packages/amplify-graphql-transformer-core/src/utils/index.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-context-provider.ts
packages/amplify-provider-awscloudformation/package.json
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts
yarn.lock

This commit ports the @function directive to v2 of the GraphQL
Transformer.
Manual and automated testing.

feat(graphql-function-transformer): port @function to v2

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/synthesize-resources.ts
packages/amplify-frontend-android/lib/amplify-config-helper.js
packages/amplify-frontend-flutter/lib/amplify-config-helper.js
packages/amplify-frontend-ios/lib/amplify-config-helper.js

Updated the fronted config files creator to have the correct authorization type for Admin Queries. The earlier implementation had AWS_IAM hardcoded. The updated config looks similar to this
```json
{
"api": {
"plugins": {
"AdminQueries": {
"endpointType": "REST",
"endpoint": "https://zzzz.execute-api.us-west-2.amazonaws.com/dev",
"region": "us-west-2",
"authorizationType": "AMAZON_COGNITO_USER_POOLS"
}
}
}
}
}
```
fix #6983

fix: generate correct auth mode for admin queries in amplifyconfiguration.json

---

jest.config.js
packages/amplify-graphql-http-transformer/.npmignore
packages/amplify-graphql-http-transformer/CHANGELOG.md
packages/amplify-graphql-http-transformer/README.md
packages/amplify-graphql-http-transformer/package.json
packages/amplify-graphql-http-transformer/src/__tests__/__snapshots__/amplify-graphql-http-transformer.test.ts.snap
packages/amplify-graphql-http-transformer/src/__tests__/amplify-graphql-http-transformer.test.ts
packages/amplify-graphql-http-transformer/src/graphql-http-transformer.ts
packages/amplify-graphql-http-transformer/src/index.ts
packages/amplify-graphql-http-transformer/tsconfig.json
packages/amplify-graphql-transformer-core/src/index.ts
packages/amplify-provider-awscloudformation/package.json
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts

This commit ports the `@http` directive to v2 of the GraphQL Transformer.
Note, the first commit is part of https://github.com/aws-amplify/amplify-cli/pull/7055, and will be rebased out once that PR lands.
Refs: https://github.com/aws-amplify/amplify-cli/issues/6217
Manual and automated testing.

feat: port @http to GraphQL Transformer v2

---

.circleci/config.base.yml
.circleci/config.yml

ci: update cypress base image to node 12
Cypress base image changed to node 12

ci: update cypress base image to node 12

---

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/get-userpoolgroup-list.test.ts

test(cli): add test for get-userpoolgroup-list.ts

---

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/get-plugin-instance.test.ts

test(cli): add test for get-plugin-instance extensions

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-defaults-appliers.ts

Fix an `update auth` issue when update flow could end up enabling identity pool that leads to unintended resources during push.
fix: #4657 preserve previous authSelections in update flow
Manual testing

fix: #4657 preserve previous authSelections in update flow

---

packages/amplify-category-api/src/index.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts

This commit adds logic to rebuild container based APIs during
push if necessary.
https://github.com/aws-amplify/amplify-cli/issues/6684
Follow the steps to reproduce in https://github.com/aws-amplify/amplify-cli/issues/6684.

fix: conditionally rebuild container apis on push

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/generate-auth-trigger-template.ts
packages/amplify-provider-awscloudformation/src/utils/upload-auth-trigger-template.ts

Added a check to check for authResource when breakcircularddependency is enabled for this PR #6968
Updated auth trigger lambda runtime to node12
* tested using running e2e test locally

fix: e2e failed tests for auth Triggers PR

---

packages/amplify-cli/src/__tests__/init-steps/s1-initFrontend.test.ts
packages/amplify-cli/src/init-steps/s0-analyzeProject.ts
packages/amplify-cli/src/init-steps/s1-initFrontend.ts

This commit updates `getSuitableFrontend()` to respect headless inputs. Prior to this change, all headless projects were defaulting to JavaScript.
Manual and unit testing.

fix: respect headless frontend input

---

install

Fixed checks for existing file paths in bash config files to prevent subsequent runs of the install script from inserting duplicates
https://github.com/aws-amplify/amplify-cli/issues/6300
Tested manually

fix: install script putting duplicate paths in bash config files

---

packages/amplify-cli-core/src/feature-flags/featureFlags.ts

Add the feature flag value for adding timestamp fields in modelgen. Related PR: https://github.com/aws-amplify/amplify-codegen/pull/114
Related docs PR: https://github.com/aws-amplify/docs/pull/3192
`yarn test`

chore: add Feature flag for timestamp field of modelgen

---

packages/amplify-frontend-ios/index.js

This syntax fails on older versions of Node.
Unit tests

fix: remove optional chaining in JS file

---

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts
packages/amplify-cli/src/extensions/amplify-helpers/invoke-plugin-method.ts

This PR enhances the handling of cross resource permission handling for `predictions` category to filter out those resources as it does not support it yet.
Also plugin invocation is enhanced to set `MethodNotFound` of the caller wants to handle it differently.
fixes the messaging part of #7269 enhancement
Manual testing

fix: cross resource permission handling

---

packages/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts

This commit updates the REST API policy generation to handle legacy `'r'` and `'rw'` values.
https://github.com/aws-amplify/amplify-cli/issues/7301
https://github.com/aws-amplify/amplify-cli/issues/7310
Manual testing

fix: handle legacy string permissions

---

packages/graphql-auth-transformer/src/__tests__/__snapshots__/SearchableAuthTransformer.test.ts.snap
packages/graphql-connection-transformer/src/__tests__/__snapshots__/NewConnectionTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/__tests__/__snapshots__/DynamoDBModelTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/definitions.ts
packages/graphql-elasticsearch-transformer/src/__tests__/__snapshots__/SearchableModelTransformer.test.ts.snap

fix #2564 
make primary key non nullable on delete input

fix(graphql-dynamodb-transformer): make primary key non null on del

---

packages/amplify-e2e-core/src/utils/nexpect.ts

This PR fixes the nexpect pathname parsing bug, where nexpect trims pathnames with spaces in it.
Fixes #7324 
The environment tests located in `amplify-e2e-tests` is passing.

fix: nexpect pathname parsing (#7324)

---

packages/amplify-frontend-javascript/lib/framework-config-mapping.js

This commit updates updates the handling of headless input to always respect JavaScript framework headless configuration options.
https://github.com/aws-amplify/amplify-cli/issues/7326
Followed steps to reproduce in https://github.com/aws-amplify/amplify-cli/issues/7326.

fix: respect headless frontend JS config input

---

packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/containers-walkthrough.ts

This commit makes the ECR repository name validation more strict.
https://github.com/aws-amplify/amplify-cli/issues/7322
Manual testing

fix: make ECR repository name validation more strict

---

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/addLayerToFunctionWalkthrough.test.ts
packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/removeWalkthrough.test.ts
packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/addLayerToFunctionUtil.test.ts
packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/buildLayer.test.ts
packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/lambda-layer-cloud-formation-template.test.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/removeLayerWalkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerConfiguration.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerMigrationUtils.ts
packages/amplify-cli-core/src/state-manager/pathManager.ts
packages/amplify-cli-core/src/state-manager/stateManager.ts

This change ensures the Lambda layer resource is in the update state after removing an individual version.
Manual testing and yarn test

fix: removing individual non-legacy layer regenerates cfn template

---

.circleci/config.base.yml
.circleci/config.yml

- change integration tests to use dev cli from the build job
- fix artifact path for screenshots and video
- Ran integ tests on fork

test: use build cli for integ test

---

packages/amplify-category-auth/resources/cloudformation-templates/user-pool-group-template.json.ejs

This commit reduces the scope of `iam:PassRole` to be limited to Amplify's `authRole` and `unauthRole`.
N/A
Manual testing - add Cognito user pool groups to a project and push. Any additional pointers on testing this feature are welcome.

fix: scope down usage of PassRole

---

packages/amplify-category-auth/src/index.js
packages/amplify-category-auth/src/provider-utils/awscloudformation/assets/cognito-defaults.js

This commit updates `externalAuthEnable()` to include the auth `sharedId` when creating an auth resource. The `sharedId` is given the lowest priority in the `authProps` object so that it will not overwrite any previously existing `sharedId`. It also uses the `sharedId` from `cognito-defaults` for consistency. This change prevents the creation of `snsundefined` roles.
N/A
Manual testing - create a new project, add a REST API with restricted access

fix: add `sharedId` in `externalAuthEnable()`

---

package.json
yarn.lock

This pull request is a proposal that can be either taken or left. I got confused when I used `yarn commit` but no indication of valid `scopes` was provided  during that potion of interaction. This resulted in me using an invalid scope, failing the commit, and re-running `yarn commit` with a valid scope from the failure error message.
A lerna `scopes` enum (from `@commitlint/config-lerna-scopes`) is currently enforced by commitlint. However, `commitizen` is not configured to be aware of that list of valid scopes. This makes it possible to call `yarn commit` and result in the generated commit failing the lint rule:
This pull request removes the dependency on `cz-conventional-changelog` and installs `@commitlint/cz-commitlint` as an alternative. `@commitlint/cz-commitlint` shares it's config …

build: use @commitlint/cz-commitlint instead of cz-conventional-changelog

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/message-printer.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/message-printer.ts

updated Auth SMS workflow check to handle the case when user name can be both email and phone number

fix: update auth sms workflow check

---

packages/amplify-util-mock/src/__e2e__/key-transformer.e2e.test.ts
packages/graphql-auth-transformer/src/__tests__/__snapshots__/OperationsArgument.test.ts.snap
packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts
packages/graphql-dynamodb-transformer/src/__tests__/__snapshots__/DynamoDBModelTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/resources.ts
packages/graphql-key-transformer/src/__tests__/__snapshots__/KeyTransformer.test.ts.snap
packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformer.e2e.test.ts

- create update and delete resolvers should check for model object key
- update unit tests to the new resolver change
- update mock and e2e packages to test change
- fix #7414 
- ran unit, mock, and e2e tests

fix(graphql-model-transformer): use modelobject key for mutation resolver creation

---

packages/amplify-category-function/package.json
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts
packages/amplify-cli/src/extensions/amplify-helpers/resource-status.ts
packages/amplify-e2e-core/src/categories/lambda-layer.ts
packages/amplify-e2e-tests/src/__tests__/layer-2.test.ts
packages/amplify-migration-tests/src/__tests__/update_tests/function_migration_update.test.ts
packages/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts

- Refactor layer hashing functionality to be more generic and handle the new design while for legacy layers preserve the old hashing for change detection
- Add new E2E test for lock file and `node_modules` removal
- Change the behavior of legacy function build to don't error out if no package manager was detected
- Manual testing
- New E2E test

refactor: change layer hashing method, generalize it, add e2e

---

packages/amplify-cli/src/__tests__/test-aborting.test.ts
packages/amplify-cli/src/display-banner-messages.ts
packages/amplify-cli/src/index.ts

Display layer migration message when deprecated layer versions are present

feat: display migration info when legacy layers are present in env

---

.circleci/config.base.yml
.circleci/config.yml
packages/amplify-e2e-tests/src/__tests__/function_4.test.ts

chore: update AMPLIFY_PATH env var in config for migration tests

---

packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts
packages/amplify-cli-core/src/state-manager/pathManager.ts
packages/amplify-cli-core/src/state-manager/stateManager.ts
packages/amplify-e2e-tests/src/__tests__/layer.test.ts

After an `amplify env checkout`, the displayed `amplify status` would sometimes incorrectly show Updated instead of No Changes when layer content remained untouched. This PR fixes that by copying the Cloudformation file and the description field stored in the `#current-cloud-backend` directory. This bug only affected the displayed status, and did not result in new layer versions being created on a subsequent push.
Also updated an inaccurate e2e test description.
Updated multi-environment e2e tests to check `amplify status`, which pass locally. Unit tests also pass locally.

fix: copy env specific data from ccb on env checkout

---

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambdaLayerWalkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/removeLayerWalkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/addLayerToFunctionUtils.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/lambda-layer-cloudformation-template.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerCloudState.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts

This PR fixes 2 issues around lambda functions:
- update function previously failed when the selected function referenced a non-existent lambda layer version
- when project had 2 lambda layers and both of them had changes a push failed because CFN logical resource id was the same
N/A
Manual testing

fix: lambda layer change handling

---

packages/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts

This commit updates the REST API migration logic to ensure that the API ID is a CFN Output, as the policy consolidation logic will rely on this during push.
Manual testing

fix: ensure REST API CFN outputs the API ID

---

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts

Change the scope of files the CLI checks for python lambda layers.
Now in the layer directory the following files are checked:
- Pipfile (if exists)
- Pipfile.lock (if exists)
- All other files recursively, but exluding `lib` - where `pip install` installs the dependencies 
N/A
Manual testing

fix: change scope of change detection for python layers

---

packages/amplify-cli/src/__tests__/test-aborting.test.ts
packages/amplify-cli/src/context-manager.ts
packages/amplify-cli/src/index.ts
packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js
packages/amplify-provider-awscloudformation/src/push-resources.ts

fix: catch no updates CFN error and fix CFN poller hang

---

packages/amplify-appsync-simulator/src/velocity/value-mapper/map.ts
packages/graphql-auth-transformer/src/__tests__/__snapshots__/OperationsArgument.test.ts.snap
packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts
packages/graphql-dynamodb-transformer/src/__tests__/__snapshots__/DynamoDBModelTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/definitions.ts
packages/graphql-dynamodb-transformer/src/resources.ts
packages/graphql-key-transformer/src/__tests__/__snapshots__/KeyTransformer.test.ts.snap
packages/graphql-transformers-e2e-tests/src/__tests__/DynamoDBModelTransformer.e2e.test.ts

For a model with some non-nullable field types
```gql
type ListContainer @model {
id: ID!
name: String
list: [String]
requiredList: [String]!
requiredListOfRequired: [String!]!
listOfRequired: [String!]
}
```
It generates the updateResolver 
```
#set( $optionalNonNullableFields = ["requiredList", "requiredListOfRequired"] )
#foreach( $field in $optionalNonNullableFields )
#if( $util.isNull($context.args.input.get($field)) && $context.arguments.input.keySet().contains($field) )
$util.error("An argument you marked as Non-Null is set to Null in the query or the body of your request.")
#end
#end
```
The resolver basically checks if the field exist and is set to null
The schema remains unchanged
```gql
input UpdateListContainerInput {
id: ID!
name: String
list: [String]
requiredList: [String] …
```

fix: validates optional non nullable fields to be not null 

---

packages/amplify-category-api/src/commands/api/add.js
packages/amplify-category-api/src/provider-utils/awscloudformation/index.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.ts
packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-tests/src/__tests__/api_2.test.ts

This commit allows `amplify add api` to add new paths to API Gateway based REST APIs.
https://github.com/aws-amplify/amplify-cli/issues/5379
Manual and E2E testing.

feat: support adding REST API paths in 'add api'

---

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/remove-resource.test.ts
packages/amplify-cli/src/extensions/amplify-helpers/remove-resource.ts

- make sure to await returned promise from deleteResourceFiles.
- make sure to await returned promise from emitError.
- change to empty object form empty array as default value of `questionOptions.serviceDeletionInfo`
- Increase test coverage of amplify-cli/extensions.

fix(cli): make sure to await returned promise from async functions

---

packages/amplify-provider-awscloudformation/src/__tests__/system-config-manager.test.ts
packages/amplify-provider-awscloudformation/src/system-config-manager.ts

Move profile credential validation to the top function, getProfiledAwsCredentials. Prevents erroneous errors on validation when a source profile is used
\#7311
Executed amplify-dev commands locally with and without source_profile configured

fix: Move credential validation to the top function call

---

packages/amplify-graphql-function-transformer/package.json
packages/amplify-graphql-http-transformer/package.json
packages/amplify-graphql-model-transformer/package.json
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-model-transformer/src/graphql-types/common.ts
packages/amplify-graphql-model-transformer/src/graphql-types/mutation.ts
packages/amplify-graphql-model-transformer/src/graphql-types/query.ts
packages/amplify-graphql-transformer-interfaces/src/index.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/index.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-context-provider.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-plugin-provider.ts
packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts

This commit updates the GraphQL v2 Transformer to correct a typo: tranformer -> transformer

fix: correct 'tranformer' typo

---

packages/graphql-transformers-e2e-tests/src/cognitoUtils.ts

This commit prevents emails being sent when new users are created during e2e tests.
Without this commit, running e2e tests could cause this error: 
```
Failed when signing up user
LimitExceededException: Exceeded daily email limit for the operation or the account. If a higher
limit is required, please configure your user pool to use your own Amazon SES configuration for
sending email.
```
I ran an integ test without this change. Failed with the above error. I then ran the same test with this change built in, and it passed.

test(graphql-transformers-e2e-tests): prevent SES ratelimit errors

---

packages/amplify-graphql-model-transformer/src/resolvers/query.ts
packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.tests.ts.snap

This commit removes an extra $ that was being generated in two places by the model transformer v2.
Manual testing and unit testing

fix: remove extra $ output of model transformer v2

---

packages/amplify-util-mock/src/CFNParser/appsync-resource-processor.ts
packages/amplify-util-mock/src/CFNParser/stack/index.ts
packages/amplify-util-mock/src/__tests__/utils/lambda/populate-cfn-params.test.ts
packages/amplify-util-mock/src/utils/lambda/populate-cfn-params.ts

This commit adds mock support for the CFN pseudo-parameter `AWS::URLSuffix`, which is used by the GraphQL transformer v2.
Manual and unit testing

fix: support AWS::URLSuffix CFN pseudo-param in mock

---

packages/amplify-util-mock/src/CFNParser/appsync-resource-processor.ts
packages/amplify-util-mock/src/CFNParser/intrinsic-functions.ts

This commit updates the mock functionality so that it can start successfully with GraphQL Transformer v2. The changes here reflect the fact that v2 includes the region in the S3 URL, and the Ref key is not always lowercase.
Note - successful startup also depends on https://github.com/aws-amplify/amplify-cli/pull/7416.
Manual testing

fix: let mock start successfully with gql transformer v2

---

packages/amplify-util-mock/src/__e2e__/connections-with-auth-tests.e2e.test.ts
packages/amplify-util-mock/src/__e2e__/dynamo-db-model-transformer.e2e.test.ts
packages/amplify-util-mock/src/__e2e__/function-transformer.e2e.test.ts
packages/amplify-util-mock/src/__e2e__/key-transformer.e2e.test.ts
packages/amplify-util-mock/src/__e2e__/key-with-auth.e2e.test.ts
packages/amplify-util-mock/src/__e2e__/model-auth-transformer.e2e.test.ts
packages/amplify-util-mock/src/__e2e__/model-connection-transformer.e2e.test.ts
packages/amplify-util-mock/src/__e2e__/model-connection-with-key-transformer.e2e.test.ts
packages/amplify-util-mock/src/__e2e__/multi-auth-model-auth-transformer.e2e.test.ts
packages/amplify-util-mock/src/__e2e__/per-field-auth-tests.e2e.test.ts
packages/amplify-util-mock/src/__e2e__/subscriptions-with-auth.e2e.test.ts
packages/amplify-util-mock/src/__e2e__/util-method-e2e.test.ts
packages/amplify-util-mock/src/__e2e__/versioned-model-transformer.e2e.test.ts

Reverts aws-amplify/amplify-cli#7572
#7572 fixed some e2e tests that were broken due to #7258 but #7258 had to be reverted due to other failing tests, so reverting this as well

Revert "test: add ff to gql test transformer"

---

packages/amplify-cli-core/src/feature-flags/featureFlags.ts

This PR adds a new feature flag used by codegen to emit provider value of `@auth` directives in iOS models.
Related amplify-codegen PR:https://github.com/aws-amplify/amplify-codegen/pull/184
N/A

chore: feature flag for @auth directive provider

---

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts
packages/amplify-e2e-tests/src/__tests__/function_4.test.ts
packages/amplify-e2e-tests/src/__tests__/layer-2.test.ts

- Fix the file path for `Pipfile.lock` when globbing a Python Lambda layer
- Add 2 e2e tests to cover recent fixes: https://github.com/aws-amplify/amplify-cli/pull/7537 https://github.com/aws-amplify/amplify-cli/pull/7545
Manual testing, e2e tests pass locally, `yarn test`

fix: file path for Pipfile.lock for python layer globbing, add e2e tests

---

packages/amplify-e2e-core/src/utils/nexpect.ts
packages/amplify-e2e-tests/Readme.md

- Change verbose flag name to be clear it can be used for local testing
- Filter ora spinner output so that the output can be sifted through easily
- Filter lines that only have invisible chalk characters
- Fix use of deprecated `isRegExp()` => `types.isRegExp()`
- Fixed some typos
Until now, output would have giant spans of text every time the spinner animation changed:
```bash
⠹ Deleting resources from the cloud. This may take a few minutes...
at onLine (../amplify-e2e-core/src/utils/nexpect.ts:460:21)
console.log
at onLine (../amplify-e2e-core/src/utils/nexpect.ts:460:21)
console.log
⠸ Deleting resources from the cloud. This may take a few minutes...
at onLine (../amplify-e2e-core/src/utils/nexpect.ts:460:21)
console.log
at onLine (../amplify-e2e-core/src/utils/nexpect.ts:460:21) …
```

test: update verbose flag to filter spinner output, update flag name

---

packages/amplify-cli/src/plugin-manager.ts
packages/amplify-cli/src/utils/post-install-initialization.ts

- removes the following messages but still prints errors if it encounters any:
```
renebrandel@renes-air Projects % amplify version
Initializing new Amplify CLI version...
Done initializing new version.
Scanning for plugins...
Plugin scan successful
```
- Tested it locally.

chore(): removed plugin scan messages & initialize new version messages

---

packages/amplify-category-notifications/lib/channel-Email.js

FromAddress and Identity are required parameters in UpdateEmailChannel() sdk call which were missing in current Implementation
* Tested manually

fix: added required parameters in Email notifications channel

---

.circleci/config.base.yml
.circleci/config.yml
.circleci/scan_artifacts.ts

Adding a additional step in E2E test to scan the test artifacts and if any of them are found, fail the build and delete the artifacts to prevent them from getting stored in CircleCI. The secret values scanned can be configured by setting up a comma separate environment variable `ENV_VAR_WITH_SECRETS` which contains the list of enviroment variables that has the secret values. For instance if the secret are stored in `MY_SECRET_ENV_1`, `MY_SECRET_ENV_2` then set `ENV_VAR_WITH_SECRETS` to `MY_SECRET_ENV_1, MY_SECRET_ENV_2`

ci: run e2e test artifact scanning

---

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts

When defining access permissions across resources, when the resource is in the same category (function access to function) the filtering expression was incorrect as the checked data was not passed in.
fixes: #7587 - resource filtering in same category for crud
Manual testing

fix: #7587 - resource filtering in same category for crud

---

packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts

This commit updates the name applied to DDB data sources in GraphQL Transformer v2. This name change allows the data source to work with the mock functionality.
Manual testing

fix: update DDB data source name in gql transformer v2

---

packages/amplify-e2e-tests/src/__tests__/api_2.test.ts

This commit adds a regression test for the case where a REST API is pushed without an ApiId output.
This is a regression test for https://github.com/aws-amplify/amplify-cli/pull/7538
The test in this PR.

chore: add regression test for #7538

---

packages/amplify-graphql-http-transformer/src/__tests__/amplify-graphql-http-transformer.test.ts
packages/amplify-graphql-http-transformer/src/graphql-http-transformer.ts
packages/graphql-http-transformer/src/__tests__/HttpTransformer.test.ts
packages/graphql-http-transformer/src/resources.ts

This commit adds support for a `${region}` template, that is replaced with the AWS region of the
environment. It works similarly to the exiting `${env}` template which returns the name of the current
amplify environment.
fix #6520
re https://github.com/aws-amplify/docs/pull/3203
I added unit tests. I also created an app using the feature it generated the expected data source  in AppSync.

feat(graphql-http-transformer): support ${region} template in @http url

---

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/check-case-sensitivity.test.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/legacy-add-resource.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/check-case-sensitivity.ts

This pull request addresses https://github.com/aws-amplify/amplify-cli/issues/6354 by throwing an error when an api will not be created properly due to a case sensitivity issue.
Amplify resource names are case-insensitive.
This pull request _only_ addresses the creation of APIs. It does not concern itself with other types of amplify resources.
**NOTE**: This commit uses `process.exit` directly from the helper util. I am not sure how to achieve this another way, but it feels wrong, so advice on that would be appreciated.
fix #6354
- unit tests added 
- `amplify-dev add api` attempted to create various combinations of valid and invalid amplify resources. Ex. `testblog` (succeeds) then `testBlog` (fails with error message), then `testblog` (update code path succeeds), then `test` (succeeds). …

fix: amplify-category-api case sensitivity failure

---

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/lambda-layer-cloud-formation-template.test.ts
packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/packageLayer.test.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/buildLayer.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/lambda-layer-cloudformation-template.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerMigrationUtils.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts
packages/amplify-e2e-core/src/categories/lambda-layer.ts
packages/amplify-migration-tests/src/__tests__/migration_tests/lambda-layer-migration/layer-migration.test.ts
packages/amplify-migration-tests/src/migration-helpers/legacy-lambda-layer.ts
packages/amplify-nodejs-function-runtime-provider/src/utils/legacyPackage.ts
packages/amplify-python-function-runtime-provider/src/util/packageUtils.ts

- Fix handling for migrated layers (created before v5.0.0) that have no associated runtime
- Improve handling of layers that have multiple runtimes
Fixes https://github.com/aws-amplify/amplify-cli/issues/7555
`yarn test` and ran all migration and e2e tests

fix: handle migrated layers with no runtime or multiple runtimes

---

packages/amplify-migration-tests/src/__tests__/migration_tests/lambda-layer-migration/layer-migration.test.ts
packages/amplify-migration-tests/src/migration-helpers/legacy-lambda-layer.ts

Fixed the migration test to deploy a new layer version, instead of updating a layer version permission
Ran both 4.52.0 and 4.28.2 layer migration tests locally

test(amplify-migration-tests): fix layer migration for no runtime test

---

packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/legacy-add-resource.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/check-case-sensitivity.ts

Fixing test failures: https://12990-145880460-gh.circle-artifacts.com/0/~/repo/packages/amplify-e2e-tests/amplify-e2e-reports/index.html
Ran locally

fix: unique api name check works when no existing apis

---

packages/amplify-e2e-tests/src/__tests__/function_2.test.ts

One of the e2e tests installs aws-appsync from npm at runtime. A recent breaking change in aws-appsync caused the test to start failing. This commit pins the version of aws-appsync to the last known good version.
Ran the modified e2e test.

fix: pin dependency version in e2e test

---

jest.config.js
packages/amplify-graphql-predictions-transformer/.npmignore
packages/amplify-graphql-predictions-transformer/CHANGELOG.md
packages/amplify-graphql-predictions-transformer/README.md
packages/amplify-graphql-predictions-transformer/assets/predictionsLambda.js
packages/amplify-graphql-predictions-transformer/package.json
packages/amplify-graphql-predictions-transformer/src/__tests__/__snapshots__/amplify-graphql-predictions-transformer.test.ts.snap
packages/amplify-graphql-predictions-transformer/src/__tests__/amplify-graphql-predictions-transformer.test.ts
packages/amplify-graphql-predictions-transformer/src/graphql-predictions-transformer.ts
packages/amplify-graphql-predictions-transformer/src/index.ts
packages/amplify-graphql-predictions-transformer/src/utils/action-maps.ts
packages/amplify-graphql-predictions-transformer/src/utils/constants.ts
packages/amplify-graphql-predictions-transformer/tsconfig.json
packages/amplify-graphql-searchable-transformer/src/cdk/create-streaming-lambda.ts
packages/amplify-graphql-transformer-core/src/graphql-api.ts
packages/amplify-graphql-transformer-interfaces/src/graphql-api-provider.ts
packages/amplify-provider-awscloudformation/package.json
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts

This commit ports the `@predictions` directive to v2 of the GraphQL Transformer.
Unit tests and manual testing.

feat: port @predictions to GraphQL Transformer v2

---

packages/amplify-go-function-runtime-provider/src/localinvoke.ts

With Go 1.16, If `localinvoke` was never built before, running `amplify mock function <go_function_name>` will fail with the following error:
```
Local invoker binary was not found, building it...
go: github.com/aws/aws-lambda-go@v1.15.0: missing go.sum entry; to add it:
go mod download github.com/aws/aws-lambda-go
<go_function_name> failed with the following error:
Error: Command failed with exit code 1: go build main.go
```
This is due to a behavior change in [Go 1.16](https://golang.org/doc/go1.16#go-command):
> Build commands like go build and go test no longer modify go.mod and go.sum by default. Instead, they report an error if a module requirement or checksum needs to be added or updated (as if the -mod=readonly flag were used). Module requirements and sums may be adjusted with go …

fix(amplify-go-function-runtime-provider): localinvoke build error with Go 1.16

---

packages/amplify-cli/src/init-steps/s0-analyzeProject.ts
packages/amplify-e2e-tests/src/environment/env.ts

Improves the `amplify env add` workflow.
Changes made:
1. Skip the `Do you want to use an existing environment?` question when `amplify env add` is executed.
2. On passing environment name in `amplify env add <envName>`, the new environment is directly added.
Fixes #6535 
`yarn test`

fix(amplify-cli): remove redundant prompt #6535

---

packages/amplify-category-notifications/__tests__/lib/channel-FCM.test.js
packages/amplify-category-notifications/lib/channel-FCM.js

this PR prevents a copy/paste issue where an extra newline character comes along with an fcm
key. It accomplishes this by trimming the whitespace from the ApiKey string.
fix #7440
- created new unit test
- ran `amplify add notification` with whitespace in my clipboard, checked that the cli received the trimmed version

fix(amplify-category-notifications): trim whitespace from fcm keys

---

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/getDependentFunction.test.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/getDependentFunction.ts

added check for undefined permissions when checking for API dependent functions
* added a unit tests for the undefined permissions

fix: check for undefined permissions when removing dependent permissions

---

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/addLayerToFunctionUtil.test.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/addLayerToFunctionUtils.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerConfiguration.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerMigrationUtils.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts
packages/amplify-e2e-core/src/categories/lambda-function.ts
packages/amplify-e2e-core/src/categories/lambda-layer.ts
packages/amplify-migration-tests/src/__tests__/migration_tests/lambda-layer-migration/layer-migration.test.ts
packages/amplify-migration-tests/src/migration-helpers/legacy-lambda-layer.ts

Handle loading, and disabling of non-migrated LL in add/update function flows:
```
? Do you want to configure advanced settings? Yes
...
? Do you want to enable Lambda layers for this function? Yes
? Provide existing layers or select layers in this project to access from this function (pick up to 5): (Press <space> to select, <a> to toggle all, 
<i> to invert selection)
❯◯ Provide existing Lambda layer ARNs
◯ LayerA123
- LayerB123 (Layer requires migration. Run "amplify function update" and choose this layer to migrate.)
```
Manual testing, yarn test, added migration test

fix: add/update function when some LL are not yet migrated

---

.circleci/config.base.yml
.circleci/config.yml
.circleci/publish.sh
package.json

Do an automatic tagged NPM release when a branch name is prefixed with `tagged-release/` or `tagged-release-without-e2e-tests/` . The release will run the full test suites (except for console-e2e-tests) when its in `tagged-release/*`. The tag name will be based on the branch name after the prefix

ci: add support for automatic tagged release

---

packages/amplify-category-function/src/provider-utils/awscloudformation/secrets/ssmClientWrapper.ts
packages/amplify-cli/src/extensions/amplify-helpers/delete-project.ts
packages/amplify-cli/src/extensions/amplify-helpers/remove-env-from-cloud.ts
packages/amplify-cli/src/init-steps/preInitSetup.ts
packages/amplify-provider-awscloudformation/src/amplify-service-manager.js
packages/amplify-provider-awscloudformation/src/amplify-service-migrate.js
packages/amplify-provider-awscloudformation/src/attach-backend.js
packages/amplify-provider-awscloudformation/src/configuration-manager.ts
packages/amplify-provider-awscloudformation/src/initializer.ts
packages/amplify-provider-awscloudformation/src/setup-new-user.js
packages/amplify-provider-awscloudformation/src/system-config-manager.ts
packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts
packages/amplify-provider-awscloudformation/src/utils/auth-types.ts
packages/amplify-util-mock/src/utils/lambda/populate-lambda-mock-env-vars.ts

- reference to `awsConfigInfo` with this name everywhere
- add `general` authType support when determining the auth type for a project
- added cleanup of Amplify state files after cloning a project to make sure other developers' resources are not leaking into the project (which later can lead to Forbidden or other errors during delete for example).
- guard spinner destruction when doing SSM operations
fixes: #7441 - init from git prompts for credentials twice
Manual testing of init and delete with various projects.

fix: #7441 - init from git prompts for credentials twice

---

packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts
packages/amplify-category-storage/src/__tests__/provider-utils/awscloudformation/cfn-template-utils.test.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/cfn-template-utils.ts
packages/amplify-cli-core/src/cfnUtilities.ts
packages/amplify-e2e-tests/src/__tests__/layer.test.ts

Handle non-existing CFN template in `#current-cloud-backend` when running `amplify env checkout` with a LL present that is not in the target environment.
Fixes #7640
Manual testing, local e2e test passes, yarn test passes

fix: checkout into existing env with new LL

---

packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs

Added policy with action iam:PassRole for MFALambdaRole
Added the a second Policy to MFALambdaRole to grant the role iam:PassRole on SNSRole

fix(amplify-category-auth): added passrole policy to MFALambaRole

---

.circleci/config.yml

In https://github.com/aws-amplify/amplify-cli/pull/7665, we switch to use temporary credentials (including the extra SESSION_TOKEN environment variable) in our e2e suite. 
Since SESSION_TOKEN is required for reading private repos, but is not supported by CircleCI, we also need to make the repo public.
This pull request uses the temporary credentials with SESSION_TOKEN to publish the image, but points to a public instead of private repository so that it can be pulled.
N/A
I published and pulled this image in my own circleci and aws account.

E2e image build

---

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/remove-resource.test.ts

Solved failing resource-test case issues by making all function input parameter file locations OS-specific
#7711 
1. cd packages/amplify-cli
2. yarn test 

bug(amplify-cli):resource-test file location issue resolved

---

package.json
packages/amplify-graphiql-explorer/package.json
yarn.lock

This commit bumps dependencies [recognized by dependabot](https://github.com/aws-amplify/amplify-cli/security/dependabot)
Cannot update: 
- immer@8.0.1 (@aws-amplify/datastore [depends on pinned version 6.0.1](https://github.com/aws-amplify/amplify-js/blob/master/packages/datastore/package.json#L55)
- browserslist@4.16.5 (react-dev-utils [depends on pinned version 4.14.2](https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/package.json#L57)
https://github.com/aws-amplify/amplify-cli/security/dependabot
`yarn test` still passes

chore: upgrade yarn packages recommended by dependabot

---

.circleci/config.base.yml
.circleci/config.yml
packages/amplify-console-integration-tests/src/profile-helper.ts
packages/amplify-e2e-core/src/configure/index.ts
packages/amplify-e2e-core/src/index.ts
packages/amplify-e2e-core/src/init/initProjectHelper.ts
packages/amplify-e2e-core/src/utils/envVars.ts
packages/amplify-e2e-core/src/utils/pinpoint.ts
packages/amplify-e2e-tests/sample.env
packages/amplify-e2e-tests/src/__tests__/import_auth_1.test.ts
packages/amplify-e2e-tests/src/__tests__/init.test.ts
packages/amplify-e2e-tests/src/aws-matchers/iamMatcher.ts
packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts
packages/amplify-e2e-tests/src/configure_tests.ts
packages/amplify-e2e-tests/src/init-special-cases/index.ts
packages/amplify-e2e-tests/src/schema-api-directives/authHelper.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/predictions-usage.ts
packages/amplify-migration-tests/sample.env
packages/amplify-migration-tests/src/configure_tests.ts
packages/amplify-migration-tests/src/migration-helpers/init.ts
packages/amplify-provider-awscloudformation/src/configuration-manager.ts
packages/amplify-provider-awscloudformation/src/setup-new-user.js
packages/amplify-util-mock/src/utils/dynamo-db/index.ts
packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthModelAuthTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/NonModelAuthFunction.e2e.test.ts

Currently we use long-lived, manually generated access tokens to set up AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables allowing our tests to run. This is a bad practice - authorization tokens should be automatically rotated to minimize risk of the tokens landing in the wrong hands.
This PR sets up the Amplify CLI codebase to use temporary credentials during CI. Temporary STS credentials use an additional parameter, AWS_SESSION_TOKEN, to authorize the requests.
The token rotator itself is a lambda that runs every hour:
https://github.com/johnpc/amplify-e2e-token-rotation-lambda
This has been tested in CI on my fork and all tests pass:
https://app.circleci.com/pipelines/github/johnpc/amplify-cli/144/workflows/fb12f075-d881-4c92-8cf7-f8647afb909e
By submitting this pull …

ci: add support for e2e token rotation

---

packages/graphql-transformer-core/src/GraphQLTransform.ts
packages/graphql-transformer-core/src/TransformFormatter.ts
packages/graphql-transformer-core/src/validation.ts

Updated GraphQL transformer to pass through @aws_lambda directive to output schema

feat: add @aws_lambda to GQL transformer pass through directive list

---

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/removeWalkthrough.test.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/removeLayerWalkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts
packages/amplify-e2e-core/src/categories/lambda-layer.ts
packages/amplify-e2e-tests/src/__tests__/layer.test.ts

Disable the removal of specific Lambda layer versions if a function in the project depends on it.
```
amplify remove function
? Choose the resource you would want to remove testMyLayer (layer)
When you delete a layer version, you can no longer configure functions to use it.
However, any function that already uses the layer version continues to have access to it.
? Choose the Layer versions you want to remove. (Press <space> to select, <a> to toggle all, <i> to invert selection)
- 2: Updated layer version 2021-06-25T20:45:29.892Z (Can't be removed. myFunction depends on this version.)
❯◯ 3: Updated layer version 2021-06-25T20:50:12.741Z
```
Manual testing and `yarn test`

fix: disable layer version removal if fn depends on pinned version

---

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/git-manager.test.ts
packages/amplify-cli/src/extensions/amplify-helpers/git-manager.ts

Previously, we used the #amplify pragma to show which block of .gitignore was managed by amplify.
This causes confusion for customers who think it is safe to add or remove lines this section of
their gitignore. The cli will blitz any changes to this section on amplify init or amplify pull. By
using a more explicit pragma, customers will realize they should not touch this section of the
gitignore.
docs https://github.com/aws-amplify/docs/pull/3330
fix #7250
created a new project and checked that .gitignore file was manipulated as expected

fix(cli): use more explicit amplify pragma in .gitignore

---

.circleci/config.base.yml
.circleci/config.yml
packages/amplify-console-integration-tests/src/profile-helper.ts
packages/amplify-e2e-core/src/index.ts
packages/amplify-e2e-core/src/init/initProjectHelper.ts
packages/amplify-e2e-core/src/utils/envVars.ts
packages/amplify-e2e-core/src/utils/pinpoint.ts
packages/amplify-e2e-tests/sample.env
packages/amplify-e2e-tests/src/__tests__/import_auth_1.test.ts
packages/amplify-e2e-tests/src/__tests__/init.test.ts
packages/amplify-e2e-tests/src/aws-matchers/iamMatcher.ts
packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts
packages/amplify-e2e-tests/src/configure_tests.ts
packages/amplify-e2e-tests/src/init-special-cases/index.ts
packages/amplify-e2e-tests/src/schema-api-directives/authHelper.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/predictions-usage.ts
packages/amplify-migration-tests/sample.env
packages/amplify-migration-tests/src/configure_tests.ts
packages/amplify-provider-awscloudformation/src/configuration-manager.ts
packages/amplify-provider-awscloudformation/src/setup-new-user.js
packages/amplify-util-mock/src/utils/dynamo-db/index.ts
packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthModelAuthTransformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/NonModelAuthFunction.e2e.test.ts

Reverts aws-amplify/amplify-cli#7665
This is not ready to merge because the container at 363619784618.dkr.ecr.us-east-1.amazonaws.com/amplify-cli-e2e-base-image-repo-public has not been uploaded yet.

Revert "ci: add support for e2e token rotation"

---

packages/amplify-category-analytics/provider-utils/awscloudformation/cloudformation-templates/pinpoint-cloudformation-template.json
packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs
packages/amplify-category-auth/resources/cloudformation-templates/user-pool-group-template.json.ejs
packages/amplify-category-predictions/provider-utils/awscloudformation/assets/identifyCFNGenerate.js
packages/amplify-category-predictions/provider-utils/awscloudformation/cloudformation-templates/identify-template.json.ejs
packages/amplify-e2e-tests/src/__tests__/migration/node.function.test.ts

Reverts aws-amplify/amplify-cli#7700
Node JS 14.x does not support the ZipFile Attribute yet causing failing e2e tests
`Invalid request provided: The ZipFile attribute is not supported for the runtime 'nodejs14.x'`

Revert "fix: upgrade node default runtime to 14"

---

packages/amplify-console-integration-tests/src/profile-helper.ts

The nightly integ tests did not have handling for the case where we're _not_ using the session token yet. This commit adds it so that the nightly tests will pass regardless of temporary vs permanent auth tokens

test(amplify-console-integration-tests): handle no session token

---

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/determineServiceSelection.ts
packages/amplify-category-function/src/commands/function/update.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/removeFunctionWalkthrough.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/determineServiceSelection.ts
packages/amplify-e2e-core/src/categories/lambda-function.ts

When calling `amplify update function`, the user is prompted to select whether they want to update a lambda function or lambda layer. This prompt should be skipped if only one of the two exist, and it should default as though option that exists was selected.
https://github.com/aws-amplify/amplify-cli/issues/7308
- manually tested case where only a function exists
- manually tested case where only a layer exists
- manually tested case where both exist
- manually tested case where neither exists
- updated e2e test

skip unnecessary prompt for 'amplify update function'

---

.circleci/config.yml
packages/amplify-cli-core/src/errors/index.ts
packages/amplify-cli/src/attach-backend-steps/a40-generateFiles.ts
packages/amplify-cli/src/attach-backend.ts
packages/amplify-cli/src/commands/push.ts
packages/amplify-e2e-core/src/init/amplifyPull.ts
packages/amplify-e2e-tests/src/__tests__/pull.test.ts
packages/amplify-provider-awscloudformation/src/configuration-manager.ts

When the developer runs `amplify pull` and chooses "no" when prompted: "Do you plan on modifying this backend?", the cli should not prompt for all the project configuration settings when `amplify pull` is called again to receive updates. Since the entire `amplify/` dir is removed when this option is selected, we lose project configuration context.
This change keeps the `amplify/` dir around, only deleting the backend directories, and maintains the state of the project configuration.
N/A
Ran `amplify pull` multiple times for admin ui, profile, and access key authenticated apps

fix(cli): prevent re-prompt of info on `amplify pull`

---

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/delete-project.test.ts
packages/amplify-cli/src/__tests__/extensions/amplify-helpers/remove-env-from-cloud.test.ts
packages/amplify-cli/src/extensions/amplify-helpers/delete-project.ts
packages/amplify-cli/src/extensions/amplify-helpers/remove-env-from-cloud.ts

this commit adds NotFoundException handling to the `amplify delete` operation. If cloud resources
are not found, then that part of the delete must already be done, so we should move on and continue
deletion.
fix #7515
- unit tests added
- ran `amplify-dev delete` on a project already deleted in the cloud

fix(cli): make delete clean local project if already deleted in cloud

---

packages/amplify-e2e-tests/src/__tests__/pull.test.ts

This commit removes an extraneous call to `deleteProject` in the e2e test `pull.test.ts`. Since the test does not maintain the amplify meta file, this `deleteProject` call fails and therefore the e2e test suite fails.
- ran e2e test, it passes now

test(amplify-e2e-tests): remove unneeded deleteProject call

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-request-adaptors.ts

The build is currently broken because it is using magic strings instead of the typescript-defined enums. This commit switches to use the enums and the build passes.
- ran `yarn setup-dev`, build was successful

chore(amplify-category-auth): use constants instead of magic strings

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/auth-sms-workflow-helper.test.ts

use `AttributeType` enum in tests instead of magic strings
- ran clean and unit tests

test(amplify-category-auth): use AttributeType enum in test

---

packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs

This commit fixes a bug where if `autoVerifiedAttributes` is undefined, the ejs template breaks.
- existing e2e test failure now passes

fix(amplify-category-auth): add handling for undefined autoVerifiedAttributes

---

packages/amplify-e2e-core/src/categories/lambda-layer.ts

this commit updates the lambda layer e2e helper so that it no longer expects a prompt to choose layer vs function, which is no longer needed since automatic detection was added in https://github.com/aws-amplify/amplify-cli/pull/7755
- failing test `yarn e2e src/__tests__/layer.test.ts` now passes
- failing test `yarn e2e src/__tests__/layer-2.test.ts` now passes

test(amplify-e2e-tests): assume function and layer lambdas are not being tested simultaneously

---

packages/amplify-e2e-core/src/categories/lambda-function.ts
packages/amplify-e2e-tests/src/__tests__/layer-2.test.ts
packages/amplify-migration-tests/src/__tests__/migration_tests/lambda-layer-migration/layer-migration.test.ts
packages/amplify-migration-tests/src/__tests__/update_tests/function_migration_update.test.ts

This commit adds a flag, `settings.layerOptions.layerAndFunctionExist` to e2e tests where the test should expect that the capability will need to be prompted on update.
- ran e2e migration and layer tests

test(amplify-e2e-tests): add layerAndFunctionExist param to trigger capability selection

---

packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs
packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthrough-types.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-defaults-appliers.ts
packages/amplify-cli-core/src/feature-flags/featureFlags.ts
packages/amplify-e2e-core/src/utils/sdk-calls.ts
packages/amplify-e2e-tests/src/__tests__/auth_5.test.ts

Added a way to only configure only TOTP. Configuring the user pool with any other attribute with 'phone_number' turn on SMS MFA
`yarn e2e src/__tests__/auth_*`

feat(amplify-category-auth): use EnabledMFAs to only configure TOTP

---

packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs
packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthrough-types.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-defaults-appliers.ts
packages/amplify-cli-core/src/feature-flags/featureFlags.ts
packages/amplify-e2e-core/src/utils/sdk-calls.ts
packages/amplify-e2e-tests/src/__tests__/auth_5.test.ts

Reverts aws-amplify/amplify-cli#7779
Reverting PR to not break the downstream changes will push it when the policy is accounted for

Revert "feat(amplify-category-auth): use EnabledMFAs to only configure TOTP"

---

.circleci/config.yml
packages/amplify-category-geo/package.json
packages/amplify-category-geo/src/__tests__/service-walkthroughs/mapWalkthrough.test.ts
packages/amplify-category-geo/src/__tests__/service-walkthroughs/placeIndexWalkthrough.test.ts
packages/amplify-category-geo/src/service-utils/constants.ts
packages/amplify-category-geo/src/service-utils/mapUtils.ts
packages/amplify-category-geo/src/service-utils/placeIndexUtils.ts
packages/amplify-category-geo/src/service-utils/resourceUtils.ts
packages/amplify-category-geo/src/service-walkthroughs/mapWalkthrough.ts
packages/amplify-category-geo/src/service-walkthroughs/placeIndexWalkthrough.ts
packages/amplify-category-geo/src/service-walkthroughs/resourceWalkthrough.ts
packages/amplify-frontend-javascript/lib/frontend-config-creator.js

Modifications to pricing plan walkthrough. The latest behavior is:
- All Geo resources will have the same pricing plan
- When creating the first Map or Place Index resource, a questionnaire is provided to help the developer set the pricing plan
- For subsequent Maps or Place Indices, the developer can change the pricing plan if his use-case has evolved. We provide this option through advanced configuration walkthrough. 
The Amazon Location Service does not currently support updating the Geo Resource properties through CFN. Hence, the pricing plan is set only when the first Geo resource is added and cannot be modified later. 
unit tests

fix(amplify-category-geo): modify the pricing plan walkthrough

---

packages/amplify-e2e-tests/package.json
packages/amplify-e2e-tests/src/__tests__/env.test.ts
packages/amplify-e2e-tests/src/environment/env.ts
packages/amplify-migration-tests/package.json

- Disabled e2e test coverage to marginally shorten test times
- Fix and enable disabled env import test
e2e test passed locally

test: turn off e2e test coverage, enable and fix import test

---

jest.config.js
packages/amplify-graphql-index-transformer/.npmignore
packages/amplify-graphql-index-transformer/CHANGELOG.md
packages/amplify-graphql-index-transformer/README.md
packages/amplify-graphql-index-transformer/package.json
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-primary-key-transformer.test.ts
packages/amplify-graphql-index-transformer/src/graphql-primary-key-transformer.ts
packages/amplify-graphql-index-transformer/src/index.ts
packages/amplify-graphql-index-transformer/src/resolvers.ts
packages/amplify-graphql-index-transformer/src/schema.ts
packages/amplify-graphql-index-transformer/src/types.ts
packages/amplify-graphql-index-transformer/src/utils.ts
packages/amplify-graphql-index-transformer/tsconfig.json
packages/amplify-provider-awscloudformation/package.json
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts

This commit adds a `@primaryKey` directive to v2 of the GraphQL Transformer. This is the first step toward replacing `@key` in v2. The next step is to add `@index` for implementing non-primary key indexes as part of the same npm package. Sync queries are not supported yet because, as far as I can tell, `@model` v2 does not support them yet.
Manual and automated tests. The tests in this PR include many of the existing `@key` tests. The remainder of the tests will be ported when `@index` is added.

feat: add @primaryKey directive to Transformer v2

---

packages/amplify-graphql-predictions-transformer/src/graphql-predictions-transformer.ts

`@predictions` requires that storage is configured. This commit moves the check out of the `before()` phase, as that is invoked even if `@predictions` is not used in the schema, leading to unnecessary errors.

fix: move storage check in @predictions v2

---

packages/amplify-cli-core/src/__tests__/featureFlags.test.ts

Fixed issue of non-matching substrings in amplify-cli-core package 
(Error was being thrown due \n not being recognized as a valid newline escape sequence character in Windows)
Fixed the issue by making \n os-specific in nature
#7813 
1. cd packages/amplify-cli-core
2. yarn test
(Successful completion of tests)

fix(amplify-cli-core):new-line escape sequence made os-specific

---

packages/amplify-category-geo/package.json
packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/mapStack.test.ts.snap
packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/placeIndexStack.test.ts.snap
packages/amplify-category-geo/src/__tests__/service-walkthroughs/placeIndexWalkthrough.test.ts
packages/amplify-category-geo/src/service-stacks/mapStack.ts
packages/amplify-category-geo/src/service-stacks/placeIndexStack.ts
packages/amplify-category-geo/src/service-utils/mapUtils.ts
packages/amplify-category-geo/src/service-utils/placeIndexUtils.ts
packages/amplify-category-geo/src/service-utils/resourceUtils.ts
packages/amplify-category-geo/src/service-walkthroughs/placeIndexWalkthrough.ts
packages/amplify-frontend-javascript/lib/frontend-config-creator.js

- These changes make the resource names environment specific for Geo resources. This fixes an issue where a developer checks out a new environment and pushes the Amplify stack. 
- JS Frontend creator uses the stack outputs to populate the `aws-exports` file. 
- Disable updating the pricing plan as it is not currently supported by Location Service.
Snapshot updated for generated CFN stacks.
Multi-Environment changes are manually tested. These will be included in e2e tests in another PR.

Env Specific resource names for Geo resources

---

packages/amplify-graphql-predictions-transformer/src/__tests__/amplify-graphql-predictions-transformer.test.ts
packages/amplify-graphql-transformer-core/src/index.ts

This commit exposes the `validateModelSchema()` function from the GraphQL Transformer core. This function is very helpful for validating the Transformer output schema's correctness. This commit also applies the validation to the `@predictions` v2 test suite.
cc: @lazpavel 
Test suite changes in this PR.

test: improve schema validation in tests

---

packages/amplify-headless-interface/schemas/api/1/AddApiRequest.schema.json
packages/amplify-headless-interface/schemas/api/1/UpdateApiRequest.schema.json
packages/amplify-headless-interface/src/interface/api/add.ts

Makes the Cognito Userpool Id optional for headless API commands. Enables you to setup both Auth and API both from the CI/CD pipelines.
If no Auth has been added to the project yet it will kick back with a proper error by default.
- Ran `yarn test`
- Ran a CI/CD pipeline w/ and w/o Auth added

feat: make cognito userpool id optional for headless mode

---

packages/amplify-util-mock/src/CFNParser/intrinsic-functions.ts
packages/amplify-util-mock/src/__tests__/CFNParser/intrinsic-functions.test.ts
packages/amplify-util-mock/src/__tests__/CFNParser/nested-aws-no-value.test.ts
packages/amplify-util-mock/src/utils/lambda/populate-cfn-params.ts

Environment variables can have now pseudo parameter values (i.e. AWS::NoValue) that will be substituted appropriately when running `amplify mock function`.
close #6122
- Manually tested with `amplify-dev`
- Created lambda function in test app
- Added environment variables with pseudo parameters like `AWS::NoValue` and `AWS::Region`
- Configure lambda function to return the values of these environment variables
- run `amplify-dev mock function`
- `yarn test`
- `yarn lint`

feat(amplify-util-mock): support pseudo parameters in environment variables when running `amplify mock function`

---

packages/amplify-category-geo/src/service-utils/mapUtils.ts
packages/amplify-category-geo/src/service-utils/placeIndexUtils.ts
packages/amplify-category-geo/src/service-utils/resourceUtils.ts

These changes fix a bug where the unauth access is not enabled on an identity pool when the Developer chooses to add guest access to Geo resources. 
tested with a JS sample app

fix(amplify-category-geo): enable unauth access for identity pool

---

packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/resolvers/mutation.ts
packages/amplify-graphql-model-transformer/src/resolvers/query.ts
packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.tests.ts.snap

`@model` v2 was generating incorrect VTL in a large number of cases. This commit fixes many of the cases found while working on the `@index` directive. It also moves some repeated code blocks into functions.
Porting E2E tests for `@key` to `@index`.

fix: misc @model v2 VTL cleanup

---

packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-primary-key-transformer.test.ts
packages/amplify-graphql-index-transformer/src/utils.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts

This commit updates GraphQL Transformer v2 to use the newly improved pluralization rules by default.
Manual and unit testing.

fix: use improved pluralization in graphql transformer v2

---

packages/amplify-provider-awscloudformation/src/push-resources.ts

since cfn-lint is deprecated, it does not always proper validate cloudformation. we've made validation errors non-blocking already in [#7132](https://github.com/aws-amplify/amplify-cli/issues/7132). This commit also addresses the log level so as not to confuse customers with a red error message.
fix
https://github.com/aws-amplify/amplify-cli/issues/7831

chore(amplify-provider-awscloudformation): reduce log level

---

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/packageFunction.test.ts
packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/packageLayer.test.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/buildFunction.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/constants.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageFunction.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts
packages/amplify-cli-core/src/state-manager/stateManager.ts
packages/amplify-cli-core/src/utils/fileSize.ts
packages/amplify-cli-core/src/utils/index.ts

Do a best effort size check on Lambda functions and Lambda layers so that we can catch some size limitation errors and can fast fail.
Manual testing with a project with various large files across layers and functions, `yarn test` passes

fix: improve size checks before packaging Lambda resources

---

packages/amplify-prompts/src/__tests__/printer.test.ts

Fix newline issue in test files

test: fix test line trim

---

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageFunction.ts

https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/1781/workflows/3745b435-ce9e-4d77-bc46-ea07c8a4307e/jobs/19114/steps
* Tested Manually and failed e2e test passed

fix: e2e tests by passing categoryName for the resource

---

packages/amplify-e2e-tests/src/__tests__/container-hosting.test.ts

Fix e2e test for container hosting
This PR makes use of existing ConfigureProject method to enable container based hosting.
Ran e2e test in local.

fix(container-hosting): e2e test fix

---

packages/amplify-category-api/src/provider-utils/awscloudformation/base-api-stack.ts
packages/amplify-e2e-tests/src/__tests__/container-hosting.test.ts

Ignore the test cases. TODO: need to find a way to force circle ci to use a specific AWS region.
Fix for container hosting.
Yarn test passes.
Manual Testing.

fix(container-hosting): ignore test cases

---

packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-model-transformer/src/graphql-types/mutation.ts
packages/amplify-graphql-model-transformer/src/wrappers/object-definition-wrapper.ts
packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.tests.ts.snap
yarn.lock

Fixed the input field type for enum types
- manual debug

fix(graphql-model-transformer): fixed input type field generation for enum types

---

packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
yarn.lock

Added name validation for @model type name against the reserved words. Changes are made on top of #7857
- ran yarn test
- migrated unit test from graphql-dynamodb-transformer
- manual debugging and testing
- CircleCI [build_test_deploy](https://app.circleci.com/pipelines/github/lazpavel/amplify-cli/139/workflows/0d8aa736-701a-4f73-81b3-3cb15fac5fe5) job

fix(graphql-model-transformer): added @model name reserved words validation

---

packages/amplify-cli/src/extensions/amplify-helpers/print.ts
packages/amplify-prompts/src/demo/demo.ts

Mark `context.print` deprecated in favor of `amplify-prompts`
Also removed some lines from the prompts demo file that were there just for testing

chore: add deprecated tag to context.print

---

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/environmentVariablesHelper.ts

{functionResource}-cloudformation-template.json file has the env variable in camel case format, so env variable
deletion should look for camel case version of the variable name
- created a project following the reproduction steps and confirmed that push succeeds
1. `amplify add function`, add sample env var, the `env_var_should_have_underscores` for the issue to occur
2. `amplify update function`, remove sample env var
3. `amplify push`
4. Observe error shown in this issue

fix(amplify-category-function): fixed issue for removing function env variable

---

packages/amplify-cli/src/commands/env/add.ts

Added await to the async function init invocation.
Before this, the post execution events were being called before the axtual completion of the add env command. 

fix: added await to init invocation

---

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/resource-status.test.ts
packages/amplify-cli/src/extensions/amplify-helpers/resource-status.ts
packages/amplify-e2e-core/src/init/amplifyPull.ts
packages/amplify-e2e-core/src/init/amplifyPush.ts

- "amplify pull" : Remove extraneous status message from  "pull flow"  ( since message is not present in API review spec  )
- E2E test : Remove table check from pull-flow (since prone to breaking from stylistic changes )
- E2E test : Fix incorrect command formulation for status -v
- Updated unit-tests to match new format.
folder: $CLI_ROOT/packages/amplify-e2e-tests
command: yarn e2e -- src/__tests__/env.test.ts -t 'init a project, pull, add auth, pull to override auth change'

(fix)e2e test failures for push,pull and amplify-status

---

packages/amplify-cli/package.json
yarn.lock

Add dependency on aws-cdk in amplify-cli
In local testing this appears to fix the pkg cli test failures here: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/1915/workflows/f027c33a-9785-4ff6-9468-69443fd4ef26
Issue is caused by a previous version of aws-cdk being incompatible with a newer version of [table](https://www.npmjs.com/package/table) which causes an error when printing `amplify status -v`
Ran failing tests locally

chore: add aws-cdk dep in amplify-cli

---

packages/amplify-e2e-tests/schemas/model_with_iam_auth.graphql
packages/amplify-e2e-tests/src/__tests__/import_auth_1.test.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts

If imported authRoleName is undefined (which is the case when only importing a user pool), then ref the root stack AuthRoleName by default
https://github.com/aws-amplify/amplify-cli/issues/7920
manually pushed project

fix: specify default auth role name on import auth

---

packages/amplify-cli/package.json
yarn.lock

Remove awscdk from amplify-cli package as the correct dependency is added and it seems to be causing an issue with packaged binary due to a version mismatch.

chore: remove awscdk from cli package

---

.circleci/local_publish_helpers.sh
package.json

Change packaged CLI script to use the CLI's `yarn.lock` file as a baseline, so packaged CLI will have the same dependencies packaged that the NPM version, it was not consistent before.
Note: frozen lockfile cannot be used because packaged CLI is getting Amplify CLI from a local verdaccio instance that updated the CLI package urls to a local verdaccio one, that file is thrown away after build, not commited back.

chore: add lock file use to packaged cli build for consistent builds

---

packages/amplify-provider-awscloudformation/src/__tests__/configuration-manager.test.ts
packages/amplify-provider-awscloudformation/src/configuration-manager.ts

The previous logic of `getConfigForEnv` had the side effect of modifying `context.exeInfo.awsConfigInfo`. In the case of creating a new environment, this caused the previous environments' config to overwrite the new environment config.
fixes https://github.com/aws-amplify/amplify-cli/issues/7977
Manually tested and added a unit test

fix: remove side effect from getConfigForEnv

---

packages/amplify-graphql-auth-transformer/package.json
packages/amplify-graphql-auth-transformer/src/accesscontrol/acm.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/resolvers/index.ts
packages/amplify-graphql-auth-transformer/src/resolvers/query.ts
packages/amplify-graphql-auth-transformer/src/utils/constants.ts
packages/amplify-graphql-auth-transformer/src/utils/definitions.ts
packages/amplify-graphql-auth-transformer/src/utils/iam.ts
packages/amplify-graphql-auth-transformer/src/utils/index.ts
packages/amplify-graphql-auth-transformer/src/utils/schema.ts
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/resolvers.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-model-transformer/src/resolvers/query.ts
packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.tests.ts.snap
packages/amplify-graphql-transformer-core/src/transformation/transformer-plugin-base.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/stack-manager-provider.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-model-provider.ts
packages/amplify-provider-awscloudformation/package.json
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts

- Updated Get Resolver Logic in order to maintain to maintain auth vtl logic pre query.
- updated snapshot tests to account for new get resolver logic
- Added Transform Schema logic
-  Adding Owner Arguments on Subscription Operations
- Adding AppSync Service Directives on Operations
- Adding ownerfield in model type
- Resolver Logic for Reads
- Get Resolver 
- List Resolver
- Field Resolver (if there is at least one role that is not allowed generate field resolver)
- IAM Policy Generation

feat: graphql auth v2 add schemaChanges, iam policy generation, and query/read resolvers

---

packages/graphql-transformers-e2e-tests/src/__tests__/PerFieldAuthTests.e2e.test.ts

Instead of creating username2 twice, update the test setup to create username2 and username3.
Ran one of the failing e2e tests.

fix: prevent creating duplicate user in test

---

packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformerV2.e2e.test.ts

This commit updates the `@searchable` v2 aggregates test to use a unique stack and bucket name to avoid race conditions with other tests.
Ran the E2E test.

fix: update GQL E2E test to use unique names

---

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/generalQuestionsWalkthrough.ts

Made inputted lambda function name's characters to match either character of only a-z and 0-9
package.json's name requires to follow the format : https://docs.npmjs.com/creating-a-package-json-file#required-name-and-version-fields
(To prevent any warning messages)
#7905 
Tested lambda function names restriction by creating a test-app and then running amplify add function command

feat(amplify-category-function):function names are made to match package.json's format (All Lowercase)

---

.circleci/config.yml
packages/amplify-category-function/src/provider-utils/awscloudformation/secrets/ssmClientWrapper.ts
packages/amplify-cli/src/commands/push.ts
packages/amplify-provider-awscloudformation/src/system-config-manager.ts

currently, the ora spinner is blocks the mfa prompt from appearing to the user. 
https://user-images.githubusercontent.com/4824042/128068323-40ac6cf4-0eb6-4c81-9f4e-bda0ed007ef9.mov
this commit makes sure a spinner is not running before prompting for mfa, then continues the spinner afterwords if required.
https://user-images.githubusercontent.com/4824042/128068364-6a8ceebb-4a6d-4d25-8f11-18eafd17643e.mov
fix https://github.com/aws-amplify/amplify-cli/issues/7848
Manually set up mfa and ran `amplify push`. See [before](https://user-images.githubusercontent.com/4824042/128068323-40ac6cf4-0eb6-4c81-9f4e-bda0ed007ef9.mov) and [after](https://user-images.githubusercontent.com/4824042/128068364-6a8ceebb-4a6d-4d25-8f11-18eafd17643e.mov) screen recordings.
By submitting this pull request, I …

fix(amplify-provider-awscloudformation): display mfa prompt

---

packages/amplify-cli-core/src/__tests__/cfnUtilities.test.ts
packages/amplify-cli-core/src/cfnUtilities.ts

Instead of creating a js-yaml schema that only contains conversions for cloudformation intrinsic
functions, we extend the built-in JSON-SCHEMA to inherit type conversions for bools, ints,
floats, etc.
See https://github.com/nodeca/js-yaml#load-string---options-
fix #7819
- Parsed yaml cloudformation templates with boolean, number, and float values, and observed correct types in the returned object
- `yarn test`
- `yarn lint`

fix(amplify-cli-core): extend js-yaml.JSON_SCHEMA to inherit json type conversions when parsing .yml cfn templates

---

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/__snapshots__/execPermissionsWalkthrough.test.ts.snap
packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.test.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts

A function attempting to add permissions is handled as new function when is not found in amplify meta.
fix #7970
- Unit Testing `yarn lerna --scope amplify-category-function run test`
- Manual Testing

fix(amplify-category-function): check for new function when adding permissions

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts

- made sure that the prompt loop has a way to terminate
- reproduced the issue with production version
- manually tested the changes and confirmed the issue is fixed

fix(amplify-category-auth): fixed walkthrough prompt after choosing same web & native app clients

---

yarn.lock

Update transient dependency `plist`. `plist` no longer has `xmldom` as a dependency, so it is removed from `yarn.lock`.
`yarn test` passed

chore: update transient dep plist, removes xmldom dep

---

packages/amplify-cli-core/package.json

Add missing `amplify-prompts` dependency to `amplify-cli-core`
`yarn test` passes

chore: add missing amplify-prompts dependency to package.json

---

.circleci/config.yml
packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/global-sandbox-mode.test.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/global-sandbox-mode.ts
packages/amplify-e2e-tests/schemas/model_with_sandbox_mode.graphql
packages/amplify-e2e-tests/src/__tests__/sandbox-mode.test.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformation/validation.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts

Adds `type AMPLIFY_GLOBAL @allow_public_data_access_with_api_key(in: string)` to user's GraphQL schema on `amplify api add` and adds an e2e test for generating a schema with sandbox mode and pushing resources.
Wrote e2e test and unit tests for changes. Also, tested locally with dev cli to generate schema.

feat(amplify-category-api): add global sandbox mode directive on schema generation

---

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/cronHelper.ts
packages/amplify-e2e-core/src/categories/lambda-function.ts

Adds `'in UTC'` when selecting a function start time or scheduled recurring time.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/8027
Locally built the cli and tested by adding and updating a function.

fix(amplify-category-function): specify UTC tz when selecting start time

---

packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CustomMessage/verification-link.js

Very simple typo fix, a variable called "seperator" was changed to separator, not affecting code logic itself, just an aesthetic fix.

fix: verification-link variable with small typo

---

packages/amplify-e2e-tests/src/__tests__/version-gating.test.ts

In CI project deletion is failing when the test was skipped for packaged CLI, a flag is added to control if we need to delete the project or not.
This only affects E2E test execution for packaged CLI for this particular test.
Manually ran E2E locally

test: fix version gating e2e test deletion

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/import/types.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/amplify-meta-updaters.ts
packages/amplify-e2e-tests/src/__tests__/auth_6.test.ts
packages/amplify-frontend-javascript/lib/frontend-config-creator.js

- added auth verification mechanisms to the front end config so they will be available for the UI 
- updated the e2e tests and checked that is passing

feat(amplify-category-auth): add auth verification mechanisms to front end config

---

packages/amplify-category-auth/src/index.js
packages/amplify-category-auth/src/provider-utils/awscloudformation/import/types.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/amplify-meta-updaters.ts
packages/amplify-cli/src/__tests__/extensions/amplify-helpers/ensure-amplify-meta-frontend-config.test.ts
packages/amplify-cli/src/extensions/amplify-helpers/on-category-outputs-change.ts

- ensure that for projects created before 5.2.0, on pull we populate the auth frontend config 
- `yarn test` passes,
- manual testing by creating a project with an older Amplify CLI and pulling into an empty folder populates the front end configuration

fix(amplify-category-auth): update front end config on pull

---

packages/amplify-graphql-auth-transformer/package.json
packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/field-auth-argument.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/amplify-admin-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/field-auth-argument.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/group-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/multi-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/owner-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/searchable-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/test-helpers.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/resolvers/field.ts
packages/amplify-graphql-auth-transformer/src/resolvers/helpers.ts
packages/amplify-graphql-auth-transformer/src/resolvers/mutation.create.ts
packages/amplify-graphql-auth-transformer/src/resolvers/mutation.delete.ts
packages/amplify-graphql-auth-transformer/src/resolvers/mutation.update.ts
packages/amplify-graphql-auth-transformer/src/resolvers/query.ts
packages/amplify-graphql-auth-transformer/src/resolvers/subscriptions.ts
packages/amplify-graphql-auth-transformer/src/utils/definitions.ts
packages/amplify-graphql-auth-transformer/src/utils/index.ts
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/resolvers/query.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/resolvers.ts
packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts

- `@auth` on sync query (conflict resolution)
- updated unit tests
- add has auth flag for deny by default with `@model`s that don't have `@auth`
- pass admin ui userpool id down into the resolver if admin ui is enabled

@auth support for datastore and add has auth flag

---

packages/amplify-e2e-tests/src/__tests__/version-gating.test.ts

Reverts aws-amplify/amplify-cli#8156

Revert "test: fix version gating e2e test deletion"

---

packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts
packages/amplify-cli/src/__tests__/extensions/amplify-helpers/get-api-key-config.test.ts
packages/amplify-cli/src/__tests__/extensions/amplify-helpers/show-global-sandbox-mode-warning.test.ts
packages/amplify-cli/src/__tests__/extensions/amplify-helpers/testData/mockLocalCloud/amplify-meta.json
packages/amplify-cli/src/extensions/amplify-helpers/get-api-key-config.ts
packages/amplify-cli/src/extensions/amplify-helpers/show-global-sandbox-mode-warning.ts
packages/amplify-e2e-tests/src/__tests__/sandbox-mode.test.ts
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-model-transformer/src/resolvers/common.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.tests.ts.snap
packages/amplify-graphql-transformer-core/package.json
packages/amplify-graphql-transformer-core/src/graphql-api.ts
packages/amplify-graphql-transformer-core/src/index.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/utils/index.ts
packages/amplify-graphql-transformer-core/src/utils/sandbox-mode.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts
yarn.lock

Changes set up the transformers to take in the sandbox directive (`allow_public_data_access_with_api_key`) and write to the auth resolvers. When sandbox mode is enabled, it allows API Key auth; when disabled, calls without an `@auth` directive are unauthorized.

feat(graphql-model-transformer): set up transformer for sandbox mode directive

---

packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/resolvers/common.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.tests.ts.snap

Makes sure that unauthorized is set when hasAuth flag is false.

fix(graphql-model-transformer): use hasAuth flag when sandbox mode is disabled

---

packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/CreateAuthChallenge.map.json

Remove prompt: "Enter the answer to your custom auth challenge"
`yarn test`, manually set up auth challenge triggers.

chore: remove value prompt for auth challenge trigger

---

packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs
packages/amplify-category-auth/src/commands/auth/update.js

`amplify update auth` is currently broken for CLI users that created auth before v5.2.0, because generated `parameters.json` file does not contain `aliasAttributes` key. This PR adds handling for the undefined alias attributes case, fixing `amplify update auth` for that case
https://github.com/aws-amplify/amplify-cli/issues/8221
Created auth using v5.1.0
Updated auth using v6 (including this change)

fix(amplify-category-auth): handle undefined aliasattributes

---

packages/amplify-graphql-transformer-core/src/transformation/transform.ts

When porting over some tests for the next version of transformers, a test was failing because the default value for this template was missing. This adds the default value for the API name.
Working on the `amplify-mock-utils` test highlighted that this value was missing. The tests to verify this will be a in a different PR.

fix(graphql-transformer-core): add default api name when generating stack

---

packages/amplify-prompts/src/demo/demo.ts
packages/amplify-prompts/src/prompter.ts

Makes a few small changes to the behavior of `prompter.pick`:
1. The hint text `(Use arrow keys or type to filter)` is printed after the prompt text
2. An an arrow prefix indicates the location of the cursor in the list
3. `enquirer` does not clear the stdout buffer on `SIGTSTP` (`ctrl + Z`), so added a listener to map it to process.exit() which is properly handled by `enquirer`
https://github.com/aws-amplify/amplify-cli/pull/8155#discussion_r707527629
Validated manually. All of these changes are config changes to the `enquirer` lib. There isn't any logic in our codebase to write tests for

feat: update pick styling, hint text, and ctrl+z listener

---

packages/amplify-cli-core/src/index.ts
packages/amplify-prompts/src/demo/demo.ts

Correct typos in amplify prompts.

chore(amplify-prompts): prompts typo fix

---

.circleci/config.yml
packages/amplify-category-geo/src/__tests__/commands/geo/add.test.ts
packages/amplify-category-geo/src/__tests__/commands/geo/remove.test.ts
packages/amplify-category-geo/src/__tests__/commands/geo/update.test.ts
packages/amplify-category-geo/src/commands/geo/add.ts
packages/amplify-category-geo/src/commands/geo/console.ts
packages/amplify-category-geo/src/commands/geo/remove.ts
packages/amplify-category-geo/src/commands/geo/update.ts
packages/amplify-category-geo/src/constants.ts
packages/amplify-category-geo/src/provider-controllers/index.ts
packages/amplify-category-geo/src/service-utils/resourceUtils.ts
scripts/split-e2e-tests.ts

Check if the Amplify project's region is supported by Amazon Location Service before allowing add/update/remove of Geo resources. 
[service region support doc](https://aws.amazon.com/location/faqs/#:~:text=Amazon%20Location%20Service%20is%20available,Asia%20Pacific%20(Tokyo)%20regions).
Modify the `split-e2e-tests` script to handle unsupported regions during region assignment.
unit testing

geo category check for unsupported regions

---

packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts

- validate resolver config per type only if project data store is enabled

fix(graphql-model-transformer): remove unnecessary warnings for resolver config per type

---

packages/amplify-graphql-model-transformer/package.json
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-domain.ts
packages/amplify-graphql-searchable-transformer/src/cdk/create-streaming-lambda.ts
packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
packages/amplify-graphql-transformer-core/package.json
packages/amplify-graphql-transformer-core/src/transformation/sync-utils.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resource-helper.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/resource-resource-provider.ts
packages/graphql-dynamodb-transformer/package.json
packages/graphql-transformer-common/package.json
yarn.lock

- ensure the IAM role name for graphql transformer does not exceed 64 characters
- ran `yarn test`

fix(graphql-model-transformer): iam role name does not exceed 64 chars

---

packages/amplify-category-geo/amplify-plugin.json
packages/amplify-category-geo/src/__tests__/commands/geo/remove.test.ts
packages/amplify-category-geo/src/commands/geo/remove.ts
packages/amplify-category-geo/src/index.ts
packages/amplify-category-geo/src/service-utils/resourceUtils.ts

Adds a pre-push event handler to check if current region is supported when Geo resources are present. 
Useful when using multi-environment setup to fail fast if region is not supported. 
`remove geo` workflow should work in unsupported region for dev to be able to remove Geo resources if he wants to. 
Tested with sample app

Add pre-push hook to verify region support

---

packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts

Multi-account e2e tests are now possible, but before we turn it on we should merge this PR to properly cleanup all the child accounts during the e2e resource cleanup phase.
- Ran this script against my personal aws account (with multiple child accounts)
- Ran this script against another aws account (with no child accounts)
the script behaves properly under both circumstances.

ci: support multi-account e2e cleanup

---

.circleci/config.yml
scripts/split-e2e-tests.ts

Removing geo tests from windows e2e tests due to some failures

test: dont run geo e2e tests on windows

---

.circleci/config.base.yml
.circleci/config.yml

Windows tests crash after success due to incompatibility with the retry bash script. This commit removes the retry wrapper around windows test runs.
Ran this against a "retry with ssh" on circleci

ci: remove retries as they cause windows to hang

---

.circleci/config.base.yml
.circleci/config.yml

I'm not sure what's wrong with windows bash yet, but in the meantime we should just use powershell which is how it worked before.

ci: use powershell to run windows tests

---

package.json

Adds a script to easily spin up an e2e test run in CCI. Simply run `yarn cloud-e2e` and it will kick off an e2e run in circle ci

chore: add cloud-e2e script

---

package.json
scripts/split-e2e-tests.ts

This adds another step to `yarn run split-e2e-tests` using the [CircleCi CLI](https://circleci.com/docs/2.0/local-cli/) to [validate the generated build.yml](https://support.circleci.com/hc/en-us/articles/360006735753-Validating-your-CircleCI-Configuration).
The CircleCI CLI must be installed (eg `brew install circleci`). 
This will notify us before attempting to use invalid CircleCI configuration.
- ran `yarn run split-e2e-tests` on valid and invalid configs

build: run circleci validator on split-e2e-tests

---

.circleci/local_publish_helpers.sh

Since we're running automated retries of flaky tests, we need to record metrics for when tests flake. This way we can follow up and address the flakiness.

ci: track flaky tests in cloudwatch

---

packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/schema.ts

- adds GSI index link field in the related type for has many directive
- adds GSI index field to Filter and Condition Inputs
- updates hasMany directive with the GSI index name
- tested local android datastore application before and after changes
- tested local iOS datastore application before and after changes
- tested local javascript datastore application before and after changes
- tested local flutter datastore application before and after changes

fix(graphql-relational-schema-transformer): has-many transformer update filter/condition inputs

---

packages/amplify-e2e-tests/schemas/transformer_migration/basic-model-v1.graphql
packages/amplify-e2e-tests/schemas/transformer_migration/basic-model-v2.graphql
packages/amplify-e2e-tests/src/GraphQLClient.ts
packages/amplify-e2e-tests/src/__tests__/transformer-migrations/model-migration.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/utils/schema.ts
packages/amplify-graphql-function-transformer/src/graphql-function-transformer.ts
packages/amplify-graphql-http-transformer/src/__tests__/amplify-graphql-http-transformer.test.ts
packages/amplify-graphql-http-transformer/src/graphql-http-transformer.ts
packages/amplify-graphql-index-transformer/src/resolvers.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-model-transformer/src/wrappers/object-definition-wrapper.ts
packages/amplify-graphql-predictions-transformer/src/__tests__/__snapshots__/amplify-graphql-predictions-transformer.test.ts.snap
packages/amplify-graphql-predictions-transformer/src/graphql-predictions-transformer.ts
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/resolvers.ts
packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
packages/amplify-graphql-transformer-core/src/transform-host.ts
packages/amplify-graphql-transformer-core/src/transformation/transformer-plugin-base.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts
packages/amplify-graphql-transformer-core/src/utils/directive-wrapper.ts
packages/amplify-graphql-transformer-interfaces/src/transform-host-provider.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-resolver-provider.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-model-provider.ts

- sets resolver and data source logical IDs as V1 to allow proper migration
- adds migration test for @model
- fixes auth resolver lookup when queries are renamed
- e2e migration for @model with key timestamps and queries override from v1 to v2 passes

fix(graphql-model-transformer): override resource logical id to fix v1 to v2 transformer migration

---

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/global-sandbox-mode.test.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/global-sandbox-mode.ts
packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-tests/schemas/model_with_sandbox_mode.graphql
packages/amplify-e2e-tests/src/__tests__/global_sandbox.test.ts
packages/amplify-graphql-transformer-core/src/transformation/validation.ts
packages/amplify-graphql-transformer-core/src/transformer-context/output.ts
packages/amplify-provider-awscloudformation/src/__tests__/utils/sandbox-mode-helpers.test.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts
packages/amplify-provider-awscloudformation/src/utils/sandbox-mode-helpers.ts

Changes the sandbox mode configuration to use the following config:
```graphql
input AMPLIFY { global_auth_rule: AuthorizationRule = { allow: public } }
```
Tested locally and changed the unit tests to test the initial parsing for `input AMPLIFY`. A fast follow up is to fix the skipped e2e test that creates a multi-model schema and deploys. (The schema passes locally.)

feat(amplify-provider-awscloudformation): change sandbox mode syntax

---

packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformerV2.e2e.test.ts

Add tests for searchable filters and aggregates.
- e2e test in local

add missing tests for searchable filters and aggregate types

---

packages/amplify-graphql-auth-transformer/src/__tests__/multi-auth.test.ts
packages/amplify-graphql-auth-transformer/src/utils/validations.ts

- update validation to allow private to work for oidc
- updated unit test to verify

fix: update auth vnext validation to use private for oidc

---

packages/amplify-cli-overrides-helper/package.json
packages/amplify-cli-overrides-helper/src/helpers/project-info.ts
packages/amplify-cli-overrides-helper/src/index.ts
packages/amplify-cli-overrides-helper/src/types.ts
packages/amplify-cli-overrides-helper/tsconfig.json

Adding getProjectInfo() helper function to the helpers package which would provide override and custom resource functions access to:
1. Project name
2. Current env name
This will enable customers to have conditional logic in code(override or custom-resources) per env.

feat: add get project info helper to overrides helper package

---

scripts/split-e2e-tests.ts

Updated the list of tests that needs to be excluded on windows e2e which are failing due to the way windows terminal splits the text and not matching the nexpect expectation.

ci: update split test to windows e2e

---

packages/amplify-e2e-tests/schemas/transformer_migration/predictions.graphql
packages/amplify-e2e-tests/src/__tests__/transformer-migrations/predictions-migration.test.ts

- v1 to v2 migration predictions e2e test

test(graphql-predictions-transformer): predictions directive migration v1 to v2 test

---

packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts

Problem:
The AppState API Gateway default endpoints have been hardcoded in the CLI configuration which puts a direct coupling between the CLI configuration and the AppState infrastructure where changes to the API infrastructure would require the CLI to be hot patched.
Solution:
Remove the hardcoded endpoints and replace with deterministic custom domains that do not change.
Testing Done:
yarn setup-dev
Updates config map to use custom domains rather than hard coded API Gateway endpoints
N/A
* Made code change
* built CLI locally with `yarn setup-dev`
* Created a new app in the console, enabled Admin UI
* Ran `amplify-dev pull`

fix: update endpoints to use custom domains in admin-helpers.ts

---

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/multi-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/multi-auth.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/resolvers/field.ts
packages/amplify-graphql-auth-transformer/src/resolvers/helpers.ts
packages/amplify-graphql-auth-transformer/src/resolvers/mutation.create.ts
packages/amplify-graphql-auth-transformer/src/resolvers/mutation.delete.ts
packages/amplify-graphql-auth-transformer/src/resolvers/mutation.update.ts
packages/amplify-graphql-auth-transformer/src/resolvers/query.ts
packages/amplify-graphql-auth-transformer/src/resolvers/search.ts
packages/amplify-graphql-auth-transformer/src/resolvers/subscriptions.ts
packages/amplify-graphql-auth-transformer/src/utils/definitions.ts
packages/amplify-graphql-auth-transformer/src/utils/index.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/utils.ts
packages/graphql-transformers-e2e-tests/src/IAMHelper.ts
packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthV2Transformer.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/cognitoUtils.ts

- allow optional identity pool to be passed into auth transformer
- this supports iam auth backed by a cognito identity pool (through amplify cli) this keeps all other authenticated identities with different arns to still be constricted to the same rules as private.
- updated unit and e2e

feat: allow optional idp arg into auth to allow provided auth role or authenticated identity

---

packages/amplify-graphql-transformer-core/package.json
packages/amplify-graphql-transformer-core/src/__tests__/transform-host.test.ts
packages/amplify-graphql-transformer-core/src/transform-host.ts

Replaces "_" in resolver logical IDs with a short hash to avoid resource name conflicts cause by removing the "_" altogether

fix: sub "_" with hash in resource logical ID in transformer v2

---

.circleci/config.base.yml
packages/amplify-e2e-core/src/categories/api.ts
scripts/split-e2e-tests.ts

This PR fixes various pipeline issues we're currently experiencing:
1. Currently, some tests bounce back and forth between using the Packaged CLI and node binary. This PR addresses that and ensures proper behavior across tests.
2. Currently, some newly added windows tests are failing. This PR adds those failing tests to the blacklist in split-e2e-tests
3. Currently, since we run a lot of parallel tests, we're running into character limits with github's reporting api. The result of this is that our CircleCI runs will seize up when this character limit is reached. This PR shortens our test run names to give us more leeway to add tests. 
See cloud-e2e circleci output demonstrating the success of these fixes.
By submitting this pull request, I confirm that my contribution is made under the …

Fix (1) pkg cli, (2) windows and (3) GitHub API character limit issues blocking e2e pipelines

---

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/global-sandbox-mode.test.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/global-sandbox-mode.ts
packages/amplify-e2e-tests/schemas/model_with_sandbox_mode.graphql
packages/amplify-e2e-tests/src/__tests__/global_sandbox.test.ts
packages/amplify-graphql-transformer-core/src/transformation/validation.ts
packages/amplify-provider-awscloudformation/src/__tests__/utils/sandbox-mode-helpers.test.ts
packages/amplify-provider-awscloudformation/src/utils/sandbox-mode-helpers.ts

changes the global authorization type to use `AuthRule` -> this also fixes the reported `amplify codegen models` bug.
Changed unit tests, tested locally, added codegen models to the e2e tests.

fix(amplify-category-api): change auth directive type and fix codegen bug

---

packages/amplify-graphql-transformer-migrator/src/__tests__/migration/__snapshots__/migrate-tests.ts.snap
packages/amplify-graphql-transformer-migrator/src/__tests__/migration/migrate-tests.ts

This commit adds unit tests in the GQL v2 migrator for the `@searchable` and `@function` directives.

test: add @searchable and @function migration unit tests

---

packages/amplify-graphql-transformer-migrator/package.json
packages/amplify-graphql-transformer-migrator/src/__tests__/migration/schema-inspector.test.ts
packages/amplify-graphql-transformer-migrator/src/schema-inspector.ts

Detect and gracefully exit if schema uses the deprecated paramterization of @connection

fix: gracefully exit on deprecated @connection parameterization

---

packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/graphql-types/mutation.ts

- updated how ID field is generated in mutation input objects to match V1
- https://app.asana.com/0/1174852957705151/1201295218402690/f

fix(graphql-model-transformer): fix model transformer ID generation when ID field is not specified

---

packages/amplify-category-api/src/commands/api/override.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/apigw-input-state.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/index.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.ts

fix: pushing multiple APIs at a time

---

packages/amplify-graphql-transformer-migrator/src/__tests__/migration/migrate-tests.ts
packages/amplify-graphql-transformer-migrator/src/__tests__/migration/schema-inspector.test.ts
packages/amplify-graphql-transformer-migrator/src/schema-inspector.ts

This commit prevents schemas with AppSync auth related directives from being automatically migrated from transformer v1 to v2. This is to prevent any unknown interactions between these directives and the new auth.

fix: don't migrate AppSync auth related directives

---

packages/amplify-e2e-tests/schemas/transformer_migration/http.graphql
packages/amplify-e2e-tests/src/__tests__/transformer-migrations/http-migration.test.ts

This commit adds a test that pushes an `@http` schema with gql transformer v1, updates the transformer to v2, and pushes again.

test: add @http migration test

---

packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-belongs-to-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/utils.ts

This allows the implicitly added 'id' field to be properly used.

fix: use output when looking up relational related type index

---

packages/amplify-graphql-transformer-migrator/src/schema-inspector.ts
packages/amplify-graphql-transformer-migrator/src/schema-migrator.ts

Gracefully exits migration if the "improvePluralization" FF is false.
Also fixes 3 other bugs in the exit early detection logic.
1. detection of overridden resolvers did not account for other files in the directory
2. detection of deprecated connection directives used .map instead of .some so it was always coming back truthy
3. the customResolvers check was excluded from the if statement to print the error message.

fix: exit migration if improvePluralization is false

---

packages/amplify-category-api/src/commands/api/update.js
packages/amplify-cli/src/commands/push.ts
packages/amplify-cli/src/extensions/amplify-helpers/push-resources.ts

Fixes 2 different issues that were causing duplicate error messages to be printed. The first was duplicate messages when updating an API if the graphql compile failed. The second was duplicate messages if the push operation failed.

fix: remove duplicate error messages

---

packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.ts
packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-tests/src/__tests__/apigw.test.ts

fix: stack generation logic when multiple paths ref same Lambda

---

packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts

This commit reloads the feature flags if `migrateToTransformerVersionFeatureFlag()` writes new values.

fix: reload feature flags after gql v2 flag migration

---

packages/amplify-graphql-auth-transformer/src/__tests__/accesscontrol.test.ts
packages/amplify-graphql-auth-transformer/src/accesscontrol/acm.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-many-to-many-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/graphql-many-to-many-transformer.ts

- allow duplicate auth rules for `manyToMany`
- unit test and local test

fix: allow duplicate auth rules when creating the join type

---

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/global-sandbox-mode.test.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/utils/global-sandbox-mode.ts
packages/amplify-e2e-tests/schemas/model_with_sandbox_mode.graphql
packages/amplify-provider-awscloudformation/src/__tests__/utils/sandbox-mode-helpers.test.ts
packages/amplify-provider-awscloudformation/src/utils/sandbox-mode-helpers.ts

Changes the Global Auth field from `global_auth_rule` to `globalAuthRule`. Non breaking as new projects and text specifies `globalAuthRule`, but the compile still works with `global_auth_rule`.
Run unit tests and test binary locally.

feat(amplify-provider-awscloudformation): change global_auth_rule to globalAuthRule for global auth

---

packages/amplify-graphql-transformer-migrator/src/__tests__/migration/__snapshots__/auth-tests.ts.snap
packages/amplify-graphql-transformer-migrator/src/__tests__/migration/auth-tests.ts

Adds unit tests to the known working cases for the migrator for the `@auth` directive.

test(graphql-transformer-migrator): adds unit tests for auth directive for migrations

---

packages/amplify-category-auth/resources/overrides-resource/override.ts
packages/amplify-category-auth/resources/overrides-resource/package.json
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/user-pool-group-stack-transform.ts
packages/amplify-category-storage/package.json
packages/amplify-category-storage/resources/overrides-resource/DynamoDB/override.ts
packages/amplify-category-storage/resources/overrides-resource/DynamoDB/package.json
packages/amplify-category-storage/resources/overrides-resource/S3/override.ts
packages/amplify-category-storage/resources/overrides-resource/S3/package.json
packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/ddb-stack-transform.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-transform.ts
packages/amplify-cli-core/src/overrides-manager/override-skeleton-generator.ts
packages/amplify-cli/amplify-plugin.json
packages/amplify-cli/src/__tests__/commands/build.test.ts
packages/amplify-cli/src/commands/build.ts
packages/amplify-cli/src/commands/export.ts
packages/amplify-cli/src/extensions/amplify-helpers/push-resources.ts
packages/amplify-e2e-core/src/categories/storage.ts
packages/amplify-provider-awscloudformation/resources/overrides-resource/override.ts
packages/amplify-provider-awscloudformation/resources/overrides-resource/package.json
packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-transform.ts

1. Rename "overrideProps" to "override"
2. Rename "props" parameter to "resources"
3. Remove "return props" requirement and test that it doesn't crash
4. "✔ Do you want to edit override.ts file now? (y/N)" should default to "true"
5. Support for: amplify build -> from amplify build-override
6. Changes are applied to all categories
7. use vm2 uniformly

feat: overrides uniformity accross all the categories

---

packages/amplify-category-storage/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.test.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-resource-api.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-user-input-state.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.ts

1. (fix) auto-migrate on headless s3 storage api
2. (fix) storage unit-tests for prompter function change
3. (fix) s3 cli-ux loop until permission selected

Ext overrides3 storage headless migrate

---

packages/graphql-transformers-e2e-tests/resources/jsonServer/src-server/index.js
packages/graphql-transformers-e2e-tests/src/__tests__/HttpTransformerV2.e2e.test.ts

This commit adds E2E tests for the `@http` v2 directive. This verifies `${env}`, `${aws_region}`, and request header behavior.

test: add more @http v2 E2E tests

---

packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-belongs-to-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/schema.ts

- updates has one and belongs to relationship fields and directive
- ensure hasOne without fields generates the connected field in the parent object similar to hasOne with fields to  create the same developer experience
- there are second parts PR on the codegen repository [here](https://github.com/aws-amplify/amplify-codegen/pull/281) and here 
- manual testing in a flutter app

fix(graphql-relational-transformer): fixed has one and belongs to relationship

---

packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/schema.ts
packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts
packages/graphql-connection-transformer/src/definitions.ts

- updates connected field for has many 
- manual testing for models generation in all platforms (js/android/ios/flutter)
- manual testing a full datastore app with ios

Has many connected field

---

packages/graphql-transformers-e2e-tests/resources/jsonServer/src-server/index.js
packages/graphql-transformers-e2e-tests/src/__tests__/HttpTransformerV2.e2e.test.ts

This commit adds an e2e test for `@http` v2 which verifies that data from the parent resolver can be accessed.

test: add @http v2 parent data e2e test

---

packages/amplify-cli/src/input-manager.ts
packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-provider-awscloudformation/amplify-plugin.json

Test passing
PASS  src/__tests__/configure-project.test.ts (153.965 s)
amplify configure project tests
✓ should update the project to use access keys (12781 ms)
✓ should update the project to use a profile (12998 ms)
✓ should update the project to remove a profile (12539 ms)
✓ should update the project to add access keys when configLevel is general (12626 ms)
✓ should update the project to use a profile (12653 ms)
PASS  src/__tests__/containers-api.test.ts (2270.977 s)
amplify api add
amplify api add
✓ init project, enable containers and add multicontainer api (1002251 ms)
✓ init project, enable containers and add multicontainer api push, edit and push (1259656 ms)
PASS  src/__tests__/custom_policies_container.test.ts (914.739 s)
✓ should init and deploy a api container, attach custom …

fix(cli): rewire override project to override rootStack internally

---

packages/amplify-provider-awscloudformation/src/__tests__/initializer.test.ts
packages/amplify-provider-awscloudformation/src/initializer.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts
packages/amplify-provider-awscloudformation/src/template-description-utils.ts

Add default descriptions to root and sub-stacks at create time.
SampleRoot-stack description: 
{"createdOn":"Mac","createdBy":"Amplify","createdWith":"6.3.1","stackType":"root","metadata":{}}
Sample category sub-stack description: 
{"createdOn":"Mac","createdBy":"Amplify","createdWith":"6.3.1","stackType":"storage-S3","metadata":{}}

feat: add default descriptions to cfn templates for metrics tracking

---

packages/amplify-category-custom/src/index.ts
packages/amplify-category-custom/src/utils/build-custom-resources.ts
packages/amplify-category-custom/src/utils/constants.ts
packages/amplify-category-custom/src/utils/dependency-management-utils.ts
packages/amplify-cli/src/__tests__/commands/build.test.ts
packages/amplify-cli/src/commands/build.ts
packages/amplify-cli/src/extensions/amplify-helpers/push-resources.ts
packages/amplify-cli/tsconfig.json

1. Moved "amplify-dependent-resources-ref.d.ts" to amplify/backend/types folder instead of having multiple copies in each of the custom resource folder.
2. Generate "amplify-dependent-resources-ref.d.ts" as a part of amplify build and amplify push commands.

feat: consolidate dependent resource types in backend/

---

packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/utils.ts

- V2 subscription resolver logical ID should match V1 subscription resolver logical ID

fix(graphql-model-transformer): subscription resolver logical id fix

---

packages/amplify-graphql-http-transformer/src/__tests__/amplify-graphql-http-transformer.test.ts
packages/amplify-graphql-http-transformer/src/graphql-http-transformer.ts
packages/amplify-graphql-predictions-transformer/src/__tests__/__snapshots__/amplify-graphql-predictions-transformer.test.ts.snap
packages/amplify-graphql-transformer-core/src/transform-host.ts

This commit overrides the logical IDs of http datasources
created by the gql v2 transformer to prevent issues when
migrating from v1. It also renames the `@http` stack to be
consistent with v1.

fix: override http datasource logical IDs

---

packages/amplify-category-auth/src/index.js
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-inputs-manager/auth-input-state.ts
packages/amplify-e2e-core/src/export/index.ts
packages/amplify-e2e-tests/src/__tests__/export-pull.test.ts

- fixing type error in auth when added userPool Groups
- failing in fetching export file: 
- error :     ENOENT: no such file or directory, open '/private/var/folders/6m/664b301s0qq5rtss4vtgdwhhthrrjc/T/amplify-e2e-tests/exporttest_54977cbc7_b05e178a/exportSrc/aws-exports.js'
86 |   function compareFileContents(path1: string, path2: string) {
87 |     const fileString1 = fs.readFileSync(path1, 'utf-8');
> 88 |     const fileString2 = fs.readFileSync(path2, 'utf-8');
|                            ^
89 |     const object1 = JSON.parse(fileString1.substring(fileString1.indexOf('{'), fileString1.lastIndexOf('}') + 1));
90 |     const object2 = JSON.parse(fileString2.substring(fileString2.indexOf('{'), fileString2.lastIndexOf('}') + 1));
91 |     expect(recursiveComapre(object1, …

fix: auth issue in export tests

---

packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-predictions-transformer/src/__tests__/__snapshots__/amplify-graphql-predictions-transformer.test.ts.snap
packages/amplify-graphql-transformer-core/src/transform-host.ts

This PR overrides the CDK generated logical IDs for Lambda and None datasources to be compatible with transformer v1. This PR also moves the existing DDB datasource override logic for consistency.

fix: override none,DDB,lambda datasource logical IDs

---

packages/amplify-graphql-transformer-core/src/transform-host.ts

This causes issues due to Amplify's use of `NONE_DS`, which is not alphanumeric.

fix: revert none data source logical id override

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/check-for-auth-migration.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/check-for-auth-migration.ts

- added auto Migration for Auth when using --forcePush or --yes or --headless
- Manual testing and unit tests added

fix: auto migrate auth for headless flows

---

packages/amplify-provider-awscloudformation/src/override-manager/index.ts
packages/amplify-provider-awscloudformation/src/override-manager/transform-resource.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts

- fix hosting e2e and hooks e2e
- ran hooks.test.ts and hostingPROD.test.ts

fix: hooks + hosting e2e

---

packages/amplify-provider-awscloudformation/src/__tests__/utils/sandbox-mode-helpers.test.ts
packages/amplify-provider-awscloudformation/src/utils/sandbox-mode-helpers.ts

Use warning method from `amplify-prompts` for messaging.
Ran locally and updated unit tests.

fix(amplify-provider-awscloudformation): use amplify prompts for warnings

---

packages/amplify-graphql-migration-tests/src/nested-stack-diff-rules.ts
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-transformer-core/src/transformation/sync-utils.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-context-provider.ts

- moved `@model` params to root stack
- updated sync table logical id
- removed table encryption should be using the default with SSE enabled but it's setting it to false. CFN still sets it to true so removing it to match v1 behavior.
- updated migration unit tests

fix: move @model params to root stack and fix ds logical id

---

packages/amplify-e2e-tests/src/__tests__/resolvers.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/amplify-admin-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/conflict-resolution.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/field-auth-argument.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/multi-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/owner-auth.test.ts
packages/amplify-graphql-auth-transformer/src/__tests__/searchable-auth.test.ts
packages/amplify-graphql-function-transformer/src/__tests__/amplify-graphql-function-transformer.test.ts
packages/amplify-graphql-http-transformer/src/__tests__/amplify-graphql-http-transformer.test.ts
packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-index-transformer.test.ts
packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-primary-key-transformer.test.ts
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-predictions-transformer/src/graphql-predictions-transformer.ts
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-many-to-many-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/relational-auth.test.ts
packages/amplify-graphql-searchable-transformer/src/__tests__/amplify-graphql-searchable-transformer.tests.ts
packages/amplify-graphql-transformer-core/src/cdk-compat/template-asset.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts
packages/amplify-provider-awscloudformation/src/__tests__/graphql-transformer/utils.test.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-config.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/utils.ts
packages/amplify-util-mock/src/__tests__/velocity/model-auth.test.ts
packages/amplify-util-mock/src/__tests__/velocity/multi-auth.test.ts
packages/amplify-util-mock/src/api/api.ts

- generates new projects with only `resolvers` directory (no `pipelineFunctions` directory) for transformer v2 projects
- gracefully handles existing pipelineFunctions directories by either porting resolvers to `resolvers` on compile or using the existing `pipelineFunctions` directory
- uses the `resolvers` directory when running `amplify mock`
- updates tests for v2 to use `resolvers` key in transformer output
- displays a warning to user when they are using pipelineFunctions instead of resolvers directory for custom and overrides
Updated the tests around using pipelineFunctions instead of resolvers; kept the unit tests that tested that both directories work for custom/overrides; running cloud e2e to confirm.
By submitting this pull request, I confirm that my contribution is made under …

Remove pipelineFunction references in favor of resolvers

---

packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs

update configure sms to include username attributes
created a cognito pool by selecting the user attributes as phone_number pushed and confirmed on the console all the values are valid

fix(amplify-category-auth): added username attributes to configure sms

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/handlers/resource-handlers.ts
packages/amplify-e2e-core/src/categories/auth.ts
packages/amplify-migration-tests/src/__tests__/migration_tests/overrides/auth-migration.test.ts

-fixes auth migration tests
- run auth-mmigration.test.ts locally

fix: fixes auth migration e2e

---

packages/amplify-provider-awscloudformation/src/override-manager/transform-resource.ts

remove --no-overrides param check from transformation step. This was causing Console CI/CD to fail as it uses that flag to avoid generating client-code in CI/CD.

fix: remove no-override check for category transformations

---

packages/amplify-e2e-core/src/categories/hosting.ts
packages/amplify-e2e-tests/src/__tests__/hostingPROD.test.ts
packages/amplify-e2e-tests/src/__tests__/init.test.ts
packages/amplify-provider-awscloudformation/src/initializer.ts
packages/amplify-provider-awscloudformation/src/override-manager/transform-resource.ts

-  fixes hosting tests when root stack is updated
-  fixed init tests

fix: init override test fix

---

packages/amplify-category-custom/src/utils/dependency-management-utils.ts
packages/amplify-cli/src/__tests__/extensions/amplify-helpers/git-manager.test.ts
packages/amplify-cli/src/extensions/amplify-helpers/git-manager.ts
packages/amplify-cli/src/input-manager.ts
packages/amplify-provider-awscloudformation/src/override-manager/transform-resource.ts

1.exclude amplify/backend/awscloudformation from gitignore path
2.add spinner when building resources

feat: exclude amplify/backend/awscloudformation from gitignore path

---

packages/amplify-category-custom/src/utils/common-questions.ts

resource-name needs to be alphanumeric conforming to amplify resource naming patterns,

fix: add alphanumeric validation on custom resource-name

---

packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformation/validation.ts

Removes references to `@allow_public_api_access` global directive that was used for Global Auth. This has been changed in favor of an `allow` field on an `input AMPLIFY`.

fix(graphql-transformer-core): remove the allow_public_global directive

---

packages/amplify-e2e-tests/src/__tests__/resolvers.test.ts
packages/amplify-graphql-transformer-core/src/index.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformation/types.ts
packages/amplify-provider-awscloudformation/src/__tests__/graphql-transformer/user-defined-slots.test.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/index.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/user-defined-slots.ts
packages/graphql-transformers-e2e-tests/src/__tests__/TransformerOptionsV2.e2e.test.ts

Adds capability to add custom slots/pipeline functions to resolvers and uploads them to AppSync and S3.
- wrote unit tests
- tested locally
- CLI e2e test
- transformer e2e test

feat(graphql-transformer-core): add support for user defined slots

---

packages/amplify-e2e-tests/src/__tests__/transformer-migrations/function-migration.test.ts

Add migration e2e test for v2 function directive.
- Run e2e in local.

test(graphql): migration e2e test for function directive v2

---

packages/amplify-category-storage/src/__tests__/provider-utils/awscloudformation/cdk-stack-builder/__snapshots__/ddb-stack-transform.test.ts.snap
packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/ddb-stack-transform.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/types.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/cfn-template-utils.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/import/import-dynamodb.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthrough-types/dynamoDB-user-input-types.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/dynamoDB-input-state.ts
packages/amplify-nodejs-function-template-provider/src/providers/crudProvider.ts
packages/amplify-nodejs-function-template-provider/src/utils/dynamoDBWalkthrough.ts

Updates the mapper for creating `build/parameters.json` from `cli-inputs.json` in the storage category. The mapper now maps the human readable field attribute names "string", "number", "list", etc. to the corresponding DynamoDB attribute type "S", "N", "L", etc.
It also removes the reverse mapping when importing a table and placing these properties in amplify-meta to match the original behavior.
Manually verified that table properties are properly populated in function CRUD template

fix: map readable attr name to ddb name in parameters.json

---

packages/amplify-category-auth/src/commands/auth/update.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/synthesize-resources.ts
packages/amplify-e2e-core/src/categories/auth.ts

Fixes a wait line in a test and fixes the updatingAuth object that hangs off of context to read from build/parameters.json instead of cli-inputs.json
Manually tested and ran the e2e test locally. The test failed due to not having some env vars set up right, but should be g2g.

fix: auth trigger params parsing and test wait lines

---

packages/amplify-cli/src/extensions/amplify-helpers/push-resources.ts

- handle multiple not configured auth directives during push

fix(cli): handle multiple unconfigured auth directives on push

---

packages/amplify-graphql-function-transformer/package.json
packages/amplify-graphql-http-transformer/package.json
packages/amplify-graphql-http-transformer/src/__tests__/__snapshots__/amplify-graphql-http-transformer.test.ts.snap
packages/amplify-graphql-http-transformer/src/__tests__/amplify-graphql-http-transformer.test.ts
packages/amplify-graphql-http-transformer/src/graphql-http-transformer.ts

This commit updates `@http` v2 to create pipeline resolvers instead of unit resolvers. This allows `@http` to be used with other directives such as `@auth`.
This commit also adds missing auth information to `@http` v2 and adds a missing `package.json` dependency to `@function` v2.

fix: create pipeline resolvers for @http v2

---

packages/amplify-graphql-default-value-transformer/src/graphql-default-value-transformer.ts

- changes to @default resolver to handle null in the same way as undefined arguments

fix(graphql-default-value-transformer): handle null same way as undefined with @default

---

packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/resolvers.ts
packages/amplify-graphql-index-transformer/src/schema.ts
packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/definitions.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
packages/amplify-graphql-model-transformer/src/graphql-types/common.ts
packages/amplify-graphql-model-transformer/src/resolvers/common.ts
packages/amplify-graphql-searchable-transformer/src/definitions.ts
packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformer-context/index.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-context-provider.ts
packages/graphql-transformer-common/src/connectionUtils.ts

- add global auth check on index resolvers
- for the following scenarios apply the appsync `@aws_api_key` directive when global auth is enabled on non auth models and their extended queries (ex. `@index`, `@searchable`, etc...)
- add sandbox flag into context
- update connection field function with ability to pass directive node array

fix: append apiKey if global auth is enabled and its not default auth

---

packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.tests.ts.snap
packages/amplify-graphql-searchable-transformer/src/definitions.ts
packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts

Add Enum fields to aggregate field type.
- yarn test
- manual test

fix(graphql): add enum to aggregate field type

---

packages/amplify-cli-core/src/overrides-manager/migration-message.ts

fix: remove trailing 's' in documentation link

---

packages/amplify-appsync-simulator/src/index.ts
packages/amplify-appsync-simulator/src/utils/auth-helpers/helpers.ts
packages/amplify-appsync-simulator/src/utils/auth-helpers/index.ts
packages/amplify-appsync-simulator/src/utils/index.ts
packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/conflict-resolution.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/owner-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/resolvers/query.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
packages/amplify-util-mock/src/__tests__/velocity/relational-auth.test.ts
packages/amplify-util-mock/src/velocity/index.ts

- add relational vtl test for 1:1 and 1:M which capture auth field logic
- update auth filter to not include none values as this causes unnecessary filtering
- default back to auth flag instead of using primaryField checks for regular and relational queries
- updated snapshot testing since the resolver logic changed

test: add relational vtl tests

---

packages/amplify-category-custom/resources/cdk-stack.ts.sample
packages/amplify-category-custom/src/utils/dependency-management-utils.ts

1. `amplify update custom` flow improvements to allow deselection of all other Amplify resource dependencies.
2. Update cdk sample skeleton app to not use cdk.fn.join as it's not needed + fix one typo + make comments better

Modify update custom flow + update cdk skeleton sample

---

packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-belongs-to-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/schema.ts

- fix for belongs to flutter datastore issue
- yarn test passes

fix(graphql-relational-transformer): fixes belongs to relation field name

---

packages/amplify-appsync-simulator/src/data-loader/index.ts
packages/amplify-appsync-simulator/src/data-loader/opensearch/index.ts
packages/amplify-util-mock/src/CFNParser/appsync-resource-processor.ts
packages/amplify-util-mock/src/CFNParser/resource-processors/appsync.ts
packages/amplify-util-mock/src/CFNParser/resource-processors/index.ts
packages/amplify-util-mock/src/CFNParser/resource-processors/lambda.ts
packages/amplify-util-mock/src/CFNParser/resource-processors/opensearch.ts
packages/amplify-util-mock/src/CFNParser/stack/types.ts

`@searchable` mocking is not currently implemented. However, it should still be possible to use mock with a schema containing `@searchable` - search queries will just not work properly. This commit updates mock to allow schemas with `@searchable`. Messages are now printed on initial startup, and each time a search query is executed.

fix: allow mock to run if @searchable is used

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/__snapshots__/auth-stack-transform.test.ts.snap
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts

fix: userPool retain policy

---

packages/amplify-category-auth/resources/overrides-resource/auth/package.json
packages/amplify-category-auth/resources/overrides-resource/userPoolGroups/package.json
packages/amplify-category-custom/resources/package.json
packages/amplify-category-storage/resources/overrides-resource/DynamoDB/package.json
packages/amplify-category-storage/resources/overrides-resource/S3/package.json
packages/amplify-provider-awscloudformation/resources/overrides-resource/package.json

Make the skeleton package.json reference to the versions of the override helpers to be released.

chore: update overrides helper package reference in skeleton samples

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts
packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts
packages/amplify-provider-awscloudformation/resources/update-idp-roles-cfn.json

- fixed resource.service when service is not defined
- fixed template for cognito triggers when rbreah circular dependency FF is OFF
#8873 
#8870 

fix: trigger when break circular dependency  FF is off

---

packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-resource-api.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-user-input-state.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/storage-configuration-helpers.ts

1. storage - migration fixes
2. headless-storage add/update ( unauth role fix)
Default parameters were undefined for required fields for this flow. Validated migration flows with only-groups, auth+guest+groups, only-auth+guest
https://github.com/aws-amplify/amplify-cli/issues/8875#issuecomment-969240042
- [*] PR description included
- [*] `yarn test` passes

fix: storage migration for only-groups and headless allowUnauthenticatedIdentities flag missing in auth

---

packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts

Fixes #8889 - avoids auto migration to new structure when running api-gql-compile/push in CI/CD

fix: stop auto-migration of storage during api gql-compile/push

---

packages/amplify-e2e-tests/schemas/transformer_migration/auth-model-v1.graphql
packages/amplify-e2e-tests/schemas/transformer_migration/auth-model-v2.graphql
packages/amplify-e2e-tests/src/__tests__/transformer-migrations/auth-migration.test.ts

differentiate v1 and v2 schema for auth migration tests

test(graphql): differentiate v1 and v2 schema for auth migration tests

---

packages/amplify-cli/src/__tests__/context-manager.test.ts
packages/amplify-cli/src/__tests__/version-manager.test.ts
packages/amplify-cli/src/context-manager.ts
packages/amplify-cli/src/domain/amplify-usageData/UsageData.ts
packages/amplify-cli/src/domain/amplify-usageData/UsageDataPayload.ts

Previously, we sent `accountId` along with all usageData reports. This was reverted (https://github.com/aws-amplify/amplify-cli/pull/7092) in an effort to mitigate https://github.com/aws-amplify/amplify-cli/issues/7090. 
However, I have re-implemented this change and I am unable to reproduce the customer issue that caused us to revert (again, https://github.com/aws-amplify/amplify-cli/issues/7090)
This PR re-adds the accountId to our usageData statistics. It also adds a new property to our usage data, `record` that allows us to include arbitrary additional data fields to our payloads.
- Wrote a plugin that uses the new `addRecord` functionality
- Attempted to reproduce the failure described in https://github.com/aws-amplify/amplify-cli/issues/7090, was unable to
- Interacted with projects …

feat: add accountid and arbitrary additional info in usagedata

---

.github/workflows/run-pr-e2e.yaml

This PR adds a github action that listens for when the `run-e2e` label is applied to a pull request. When this happens, it runs `yarn cloud-e2e` to create a branch that runs the full e2e suite on the pr before it's merged.
I tested this on my personal fork and it works! 

ci: add label to run cloud-e2e on prs

---

packages/amplify-e2e-core/src/categories/auth.ts
packages/amplify-e2e-tests/src/__tests__/migration/apigw-ext-migration.test.ts

Adds an e2e migration test for converting the AdminQueries API to support extensibility
Ran e2e test locally

test: admin queries extensibility migration test

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts

fix: auth cloudformation generation error leading to push failure

---

packages/amplify-graphql-transformer-migrator/src/__tests__/migration/__snapshots__/migrate-tests.ts.snap
packages/amplify-graphql-transformer-migrator/src/__tests__/migration/migrate-tests.ts
packages/amplify-graphql-transformer-migrator/src/migrators/connection/index.ts

This PR adds additional `@connection` unit tests to the GQL migrator tool. I also made a minor bug fix on lines 48-52 of `packages/amplify-graphql-transformer-migrator/src/migrators/connection/index.ts`, which triggered the linter to be run on that file.

test: add gql migrator @connection unit tests

---

packages/amplify-graphql-transformer-migrator/src/__tests__/migration/__snapshots__/migrate-tests.ts.snap
packages/amplify-graphql-transformer-migrator/src/__tests__/migration/migrate-tests.ts
packages/amplify-graphql-transformer-migrator/src/__tests__/migration/schema-inspector.test.ts
packages/amplify-graphql-transformer-migrator/src/__tests__/migration/schema-migrator.test.ts

This commit adds unit tests for the GQL migrator to verify scenarios such as overwritten resolvers, custom resolvers, the use of SQL, etc.

test: add additional gql migrator edge case unit tests

---

packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.tests.ts.snap
packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts

Use output type definition to generate searchable filters so that it includes the implicitly generated fields.
- yarn test

fix(graphql): use output type definition to generate searchable filter

---

packages/amplify-cli/src/extensions/amplify-helpers/apply-auth-mode.ts
packages/amplify-cli/src/extensions/amplify-helpers/push-resources.ts

add warning to missing auth modes on amplify push yes flag

fix(graphql): add warning to missing auth modes on amplify push yes flag

---

packages/amplify-graphql-transformer-migrator/src/__tests__/migration/__snapshots__/auth-tests.ts.snap
packages/amplify-graphql-transformer-migrator/src/__tests__/migration/auth-tests.ts
packages/amplify-graphql-transformer-migrator/src/migrators/auth/defaultAuth.ts
packages/amplify-graphql-transformer-migrator/src/migrators/auth/index.ts
packages/amplify-graphql-transformer-migrator/src/migrators/generators/index.ts

Fixes 2 issues with the schema migrator. One was erroneously adding a public auth rule and the other was not retaining the group auth rule params (group name or group claim).
The key line in the diff is 98 of `packages/amplify-graphql-transformer-migrator/src/migrators/auth/index.ts` where we are no longer calling `mergeAuthRules`. All the other deletions are functions that are no longer being used because that one is no longer used. And there are a bunch of lint fixes.

fix: passthrough group auth rule config

---

packages/amplify-graphql-transformer-migrator/src/schema-migrator.ts

- warns users about removing graphql comment when using migrator tool

chore(graphql-transformer-migrator): warn users about stripping out the comments in schema migration

---

packages/amplify-category-api/resources/awscloudformation/overrides-resource/APIGW/override.ts.sample
packages/amplify-category-api/resources/awscloudformation/overrides-resource/APIGW/package.json
packages/amplify-category-api/src/commands/api/override.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts
packages/amplify-category-storage/src/__tests__/provider-utils/awscloudformation/cdk-stack-builder/ddb-stack-transform.test.ts
packages/amplify-cli-extensibility-helper/package.json
packages/amplify-cli-extensibility-helper/src/index.ts
packages/amplify-cli-extensibility-helper/src/types/api/types.ts

fix: add missing types for override file, enable vm2

---

packages/amplify-provider-awscloudformation/src/resource-package/resource-export.ts
packages/amplify-provider-awscloudformation/src/resource-package/resource-packager.ts

fix(amplify-provider-awscloudformation): exclude admin queries APIGWAuth stack

---

packages/amplify-graphql-transformer-migrator/src/__tests__/migration/__snapshots__/auth-tests.ts.snap
packages/amplify-graphql-transformer-migrator/src/__tests__/migration/auth-tests.ts
packages/amplify-graphql-transformer-migrator/src/migrators/auth/ownerAuth.ts

Fixes migration of `{ allow: owner }` and `{ allow: groups }` to remove the private rule that is generated.

fix(graphql-transformer-migrator): fix incorrect migrations of owner and group based auth

---

packages/amplify-prompts/src/demo/demo.ts
packages/amplify-prompts/src/prompter.ts

Adds a min/max pick option to amplify-prompter

feat: add min / max selection to prompter.pick

---

packages/amplify-category-api/src/provider-utils/awscloudformation/utils/containers-artifacts.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/cloudformationHelpers.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/s3-trigger-helpers.ts
packages/amplify-cli-core/src/__tests__/cfnUtilities.test.ts
packages/amplify-cli-core/src/cfnUtilities.ts
packages/amplify-cli/src/extensions/amplify-helpers/resource-status-diff.ts
packages/amplify-cli/src/project-config-version-check.ts
packages/amplify-provider-awscloudformation/src/disconnect-dependent-resources/utils.ts
packages/amplify-provider-awscloudformation/src/pre-push-cfn-processor/cfn-pre-processor.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts
packages/amplify-provider-awscloudformation/src/resource-package/resource-export.ts
packages/amplify-provider-awscloudformation/src/resource-package/resource-packager.ts

Cleanup await calls for sync read cfn calls.

fix: remove await from sync read cfn calls

---

packages/amplify-category-api/resources/schemas/aPIGateway/APIGatewayCLIInputs.schema.json
packages/amplify-category-api/src/provider-utils/awscloudformation/apigw-input-state.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/types.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthrough-types/aPIGateway-user-input-types.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthrough-types/apigw-types.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.ts
packages/amplify-e2e-tests/src/__tests__/api_5.test.ts

Fixed some missing gaps and type errors regarding user pool group permissions for REST API extensibility.
e2e test `apigw.test.ts` passes, `amplify-cli` and `amplify-category-api` unit tests pass

fix: migration flow and cfn params when user pool groups are present, types

---

packages/amplify-graphql-transformer-migrator/src/__tests__/migration/__snapshots__/migrate-tests.ts.snap
packages/amplify-graphql-transformer-migrator/src/__tests__/migration/migrate-tests.ts
packages/amplify-graphql-transformer-migrator/src/migrators/connection/index.ts

Migrator was not correctly handling migration of relational directives without fields, added a unit test for our hasOne migration requirements
Running the migrator

Fix: migrate fieldless hasOne directives correctly

---

packages/amplify-graphql-transformer-core/src/index.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformation/types.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts
packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-resolver-provider.ts
packages/amplify-provider-awscloudformation/src/__tests__/graphql-transformer/user-defined-slots.test.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/user-defined-slots.ts

Updates the resolver slotting logic to support both request and response resolvers in each slot.
Manually verified and unit tested

fix: group response and request resolvers by slot

---

packages/amplify-e2e-tests/src/__tests__/transformer-migrations/predictions-migration.test.ts

Removes transformer FF logic from tests as default on in codebase 

fix: prediction migration test fix

---

packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts
packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts

- fetch bucket parameters from cli-inputs first , if not preset then parameters.json

fix: bucket parameters fetch logic

---

packages/amplify-prompts/src/__tests__/prompter.test.ts
packages/amplify-prompts/src/prompter.ts

Fixes a bug in `prompter.pick` where a string was returned instead of an array when returnSize was many and only one option was provided. Also added a little bit of cleanup to the options param.
Added unit tests and manually validated

fix: multiselect returns array when autoselecting

---

packages/amplify-provider-awscloudformation/src/resource-package/resource-packager.ts

Send file name instead of absolute file path to custom policies

fix(amplify-provider-awscloudformation): fixed path as file name

---

packages/amplify-e2e-tests/src/__tests__/__snapshots__/api_2.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/amplify-admin-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/multi-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/resolvers/helpers.ts

fix: use not equals for iam role check

---

packages/amplify-graphql-transformer-migrator/src/schema-inspector.ts

`@searchable` migration requires manual intervention. This commit introduces a warning when migrating a schema with `@searchable`.

fix: add migration warning when @searchable is used

---

packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js

fixes #9037
AWS.CloudFormation.DescribeStackResources() only returns 100 resources (https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DescribeStackResources.html) due to it's limits and it is recommended to use ListStackResources() instead. This is causing projects with > 100 Amplify resources to fail to fetch outputs from the nested cloudformation stacks and populate it in the amplify-meta.json file.

fix: change describeStackResources() call to listStackResources()

---

packages/amplify-graphql-auth-transformer/src/resolvers/query.ts

AppSync handles duplicate $s, but mock does not.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/9075

fix: remove extra $ in vtl template

---

packages/amplify-category-api/src/index.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/user-pool-group-stack-transform.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/ddb-stack-transform.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-transform.ts
packages/amplify-cli-core/resources/overrides-resource/package.json
packages/amplify-cli-core/resources/overrides-resource/tsconfig.json
packages/amplify-cli-core/resources/overrides-resource/tsconfig.resource.json
packages/amplify-cli-core/src/overrides-manager/override-skeleton-generator.ts
packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts
packages/amplify-e2e-tests/src/__tests__/api_7.test.ts
packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-transform.ts

- copy package.json  to current cloud backend
- changes appoverrides() fn to throw error when build is failed
- generates package.json in pull if not present

fix: console override build issue

---

packages/amplify-provider-awscloudformation/src/resource-package/resource-export.ts
packages/amplify-provider-awscloudformation/src/resource-package/resource-packager.ts

feat: make modifying root stack async

---

packages/amplify-category-api/src/index.ts

I haven't been able to reproduce #9097, but this may be related. Even if this does not address #9097, I think we should make this change.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/9097

fix: use __dirname instead of '.' in import path

---

packages/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts

The S3 upload path is only used to construct a URL. On Windows,
this would use a backslash instead of the desired forward slash.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/9091

fix: don't use path.join() for s3 upload path

---

packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-many-to-many-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/graphql-many-to-many-transformer.ts
packages/amplify-graphql-relational-transformer/src/schema.ts

This commit updates the `@manyToMany` directive to handle implicit primary keys when creating the join table.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/9110

fix: handle implicit primary keys in @manyToMany

---

packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts

fixes : #9112
- Changed harcoded path to fetch path via plugin
- tested manually

fix: trigger resources path

---

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/conflict-resolution.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/conflict-resolution.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts

- add datastore fields to allowed list
- https://github.com/aws-amplify/amplify-cli/issues/9101
- manual testing the issue graphql.schema
- `yarn tests` passes

fix(graphql-auth-transformer): fix datastore fields auth

---

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/apigw-input-state.test.ts
packages/amplify-category-api/src/index.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/apigw-input-state.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts
packages/amplify-provider-awscloudformation/src/resource-package/resource-packager.ts
packages/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts
packages/amplify-provider-awscloudformation/src/utils/env-level-constructs.ts

REST APIs that have a consolidated policy stack which have not yet been migrated fail to regenerate the policy stack when pushing with 7.5.0 - 7.5.4.
To workaround, migrate the REST API with `amplify update api`.
Fixes https://github.com/aws-amplify/amplify-cli/issues/9104

fix: migrate rest apis with protected routes on push

---

packages/amplify-cli-core/src/state-manager/pathManager.ts

- Fixes parameters.json path fetch based o previous parameters.json , cli-inputs and overridden categories

fix: Parameters file path fix based on cli-inputs

---

packages/amplify-e2e-tests/src/import-helpers/utilities.ts

Fixes fetch of parameters.json in import e2e tests
tests for import updated related to this PR : https://github.com/aws-amplify/amplify-cli/pull/9138

fix: fixes import e2e tests parameters file path

---

packages/amplify-cli/src/__tests__/context-manager.test.ts
packages/amplify-cli/src/context-manager.ts

Removed sts call which was taking a while and replaced it with meta

perf(cli): get AccountId from meta instead of sts

---

packages/amplify-graphql-transformer-core/src/__tests__/errors/index.test.ts
packages/amplify-graphql-transformer-core/src/errors/index.ts
packages/amplify-graphql-transformer-core/src/transformation/validation.ts
packages/graphql-function-transformer/src/__tests__/FunctionTransformer.test.ts
packages/graphql-transformer-core/src/__tests__/GraphQLTransform.test.ts
packages/graphql-transformer-core/src/__tests__/errors.test.ts
packages/graphql-transformer-core/src/__tests__/validation.test.ts
packages/graphql-transformer-core/src/errors.ts
packages/graphql-transformer-core/src/validation.ts

Updated the GraphQL transformer V1 and V2 to provide helpful error message when an incompitable
directive is used in the schema. The error message points to migration docs to provide clear
guidelines as how the error can be fixed

feat: provide helpful error message when GQL schema validation fails

---

packages/amplify-category-geo/src/service-utils/resourceUtils.ts

When enabling UnAuth or Guest access to a Geo resource, a confusing warning message is shown that Auth is not added to the app even though it is. This change fixes it. 
https://github.com/aws-amplify/amplify-cli/issues/9154
Manually tested the case in a JS app

fix(amplify-category-geo): refactor auth warnings

---

packages/amplify-appsync-simulator/src/__tests__/resolvers/pipeline-resolver.test.ts
packages/amplify-appsync-simulator/src/resolvers/function.ts
packages/amplify-appsync-simulator/src/resolvers/pipeline-resolver.ts

Updated amplify-graphql-simulator to pass changes made to the arguments in pipeline function to next function.

fix: pass updated args between pipeline function in mock

---

packages/amplify-appsync-simulator/src/__tests__/utils/auth-helpers/current-auth-mode.test.ts
packages/amplify-appsync-simulator/src/__tests__/utils/auth-helpers/helper.test.ts
packages/amplify-appsync-simulator/src/index.ts
packages/amplify-appsync-simulator/src/server/operations.ts
packages/amplify-appsync-simulator/src/type-definition.ts
packages/amplify-appsync-simulator/src/utils/auth-helpers/helpers.ts
packages/amplify-graphiql-explorer/src/App.tsx
packages/amplify-graphiql-explorer/src/AuthModal.tsx

Amplify Mock did not support selecting the roles that should be assumed when making GraphQL request
to mock server using GraphiQL explorer. Added option to select the role to be assumed when making
the request using IAM auth mode
fix #9107

fix: add support for IAM roles in mock

---

packages/amplify-e2e-tests/src/__tests__/export.test.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts
packages/amplify-provider-awscloudformation/src/resource-package/resource-packager.ts

Export relied on a non committed amplify meta to generate the root stack template

fix(amplify-provider-awscloudformation): use in memory meta for export

---

packages/amplify-category-api/src/commands/api/add-graphql-datasource.ts

There was an issue with the dynamic import not loading `supported-datasources` correctly, so it's been removed since the file it loads is quite small.

fix: add-graphql-datasource command

---

packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-one-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/graphql-has-many-transformer.ts
packages/amplify-graphql-relational-transformer/src/graphql-has-one-transformer.ts
packages/amplify-graphql-relational-transformer/src/utils.ts

If DataStore is enabled, Model A cannot have a `@hasOne` or `@hasMany` relationship with Model B if Model B also has a `@hasOne` or `@hasMany` relationship with Model A.

fix: prevent A <-> B @hasOne or @hasMany relationships with DS

---

packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-belongs-to-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/resolvers.ts

- added support for @belongsTo Int fields 

fix(graphql-relational-transformer): @belongsTo directive support for Int fields

---

packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts
packages/amplify-e2e-core/package.json
packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-core/src/utils/request.ts
packages/amplify-e2e-tests/src/__tests__/apigw.test.ts

The deployment resource needs a new logical id for each push to work properly. This PR adds a shortened uuid to make the logical id unique.
Fixes #9142
Manually added an additional route with the latest changes and confirmed it was properly deployed and returned the expected response.
`apigw.test.ts` and `api_5.test.ts` pass locally

fix: add missing salt to deployment logicalId

---

packages/amplify-category-api/src/index.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/apigw-input-state.ts
packages/amplify-cli-core/src/overrides-manager/migration-message.ts

- Update extensibility migration message to include a note that custom modifications to a CloudFormation template will not be preserved.
- Make REST API migration logic more robust to variable input from `api-params.json` and provide a better error message when no paths are defined.
https://github.com/aws-amplify/amplify-cli/issues/9225
`apigw-ext-migration.test.ts`  passes

fix: improve api migration logic, update migration prompt

---

packages/graphql-transformers-e2e-tests/src/__tests__/PredictionsTransformerTests.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/PredictionsTransformerV2Tests.e2e.test.ts

The transformer e2e tests started failing when a query is done to turn "this is a voice test" to German in both the V1 and V2 tests. Upon some investigation, it looks like the value that was expected, `Stimmetest`, is a correct translation for `voice test`.
Google translator and running e2e tests locally.

test(graphql-transformers-e2e-tests): add spelling of voice test in German

---

packages/amplify-e2e-tests/src/__tests__/export.test.ts

Changed the way the export test validates resources between push and export command. It relies on  the count of specific resources than the resource's logical id

test: fix test to match resource type count

---

packages/amplify-e2e-tests/src/__tests__/custom_policies_container.test.ts
packages/amplify-e2e-tests/src/__tests__/custom_policies_function.test.ts

fixed the the ssm-parameter to use amplify/*

test(amplify-e2e-tests): added amplify/ for custom-policies test

---

packages/amplify-console-integration-tests/src/consoleHosting/utils.ts

npx pulls latest by default, but the latest version of create-react-app dropped node 12 support
Validated that create-react-app does not support 12 and 12 is in use, ran npx locally using the new command format with version

Pin npx create-react-app

---

Dockerfile

NodeJS 12 is EOL in April, and an update to create-react-app (used in our e2e tests) now requires node 14+.
This commit bumps our e2e test docker image to use node 14.

ci: upgrade node to v14

---

packages/amplify-console-integration-tests/src/consoleHosting/utils.ts
packages/amplify-e2e-core/src/categories/hosting.ts

Corrected syntax for version pinning of npx create-react-app
Locally running with node14
- [c] PR description included

Fix: Version pinning syntax for create-react-app was wrong

---

.circleci/config.base.yml
.circleci/config.yml

An outdated ECR URI was being used for our E2E image, this corrects that
Pulled image and confirmed that the latest image built today was there

Fix: circle CI was referencing an old image for E2E testing

---

packages/amplify-graphql-default-value-transformer/src/__tests__/__snapshots__/amplify-grapphql-default-value-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/schema.ts
packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap
packages/amplify-graphql-model-transformer/src/graphql-types/query.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/schema.ts
packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.test.ts.snap
packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
packages/graphql-auth-transformer/src/__tests__/__snapshots__/SearchableAuthTransformer.test.ts.snap
packages/graphql-connection-transformer/src/__tests__/__snapshots__/ModelConnectionTransformer.test.ts.snap
packages/graphql-connection-transformer/src/__tests__/__snapshots__/NewConnectionTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/__tests__/__snapshots__/DynamoDBModelTransformer.test.ts.snap
packages/graphql-dynamodb-transformer/src/definitions.ts
packages/graphql-elasticsearch-transformer/src/SearchableModelTransformer.ts
packages/graphql-elasticsearch-transformer/src/__tests__/__snapshots__/SearchableModelTransformer.test.ts.snap

Partially reverts the behavior that was added in https://github.com/aws-amplify/amplify-cli/pull/8166. The array itself in the list type is still non-null but the elements are generated as nullable. This is because individual elements can come back as null if there is an error in the VTL resolver for that record
Manually verified and updated unit test snapshots

fix: generate list types will nullable elements

---

packages/amplify-cli/src/execution-manager.ts

- Removing the logic selecting overrides package for extensibility since  we changed the actual package to contain overrides.
- tested manually

fix: removing old FF logic for extensibility

---

packages/amplify-cli-core/.npmignore

- include tsconfig required for overrides in npmignore

fix: include tsconfig in npmignore

---

packages/amplify-graphql-transformer-core/src/types/amplify-api-resource-stack-types.ts

- changed type exposed for prediction lambda access from CfnRole to CfnPolicy

fix: predictions lambda access policy type

---

packages/amplify-provider-awscloudformation/src/aws-utils/IdentityPoolService.ts

- validate imported IdentityPool for assigned Roles
- [9286](https://github.com/aws-amplify/amplify-cli/issues/9286)

fix(amplify-provider-awscloudformation): validate IDP roles on import (ref #9286)

---

packages/graphql-transformer-core/src/util/transformConfig.ts

- fixed readFile so it will return a string instead of a buffer to match the object definition
- fixes the object comparison in the mock in order to decide if template needs to be updated

fix(amplify-util-mock): fix cleanup V2 resolvers on mock exit

---

packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts

GraphQL allows a string where an array of strings is expected.
This commit ensures that custom subscription names are handled
as arrays of strings.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/9199

fix: handle strings as custom subscription names

---

packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-one-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/utils.ts

This commit allows recursive @hasOne and @hasMany relationships
on the same model when DataStore is enabled.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/9335

fix: support recursive @hasOne/@hasMany with DataStore

---

packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/mapStack.test.ts.snap
packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/placeIndexStack.test.ts.snap
packages/amplify-category-geo/src/__tests__/service-stacks/mapStack.test.ts
packages/amplify-category-geo/src/__tests__/service-stacks/placeIndexStack.test.ts
packages/amplify-category-geo/src/__tests__/service-utils/serviceUtils.test.ts
packages/amplify-category-geo/src/__tests__/service-walkthroughs/mapWalkthrough.test.ts
packages/amplify-category-geo/src/__tests__/service-walkthroughs/placeIndexWalkthrough.test.ts
packages/amplify-category-geo/src/provider-controllers/map.ts
packages/amplify-category-geo/src/provider-controllers/placeIndex.ts
packages/amplify-category-geo/src/service-stacks/mapStack.ts
packages/amplify-category-geo/src/service-stacks/placeIndexStack.ts
packages/amplify-category-geo/src/service-utils/geofenceCollectionUtils.ts
packages/amplify-category-geo/src/service-utils/mapParams.ts
packages/amplify-category-geo/src/service-utils/mapUtils.ts
packages/amplify-category-geo/src/service-utils/placeIndexParams.ts
packages/amplify-category-geo/src/service-utils/placeIndexUtils.ts
packages/amplify-category-geo/src/service-utils/resourceUtils.ts
packages/amplify-category-geo/src/service-walkthroughs/mapWalkthrough.ts
packages/amplify-category-geo/src/service-walkthroughs/placeIndexWalkthrough.ts
packages/amplify-category-geo/src/service-walkthroughs/resourceWalkthrough.ts

Adds Walkthrough to enable developer to grant permissions for Maps, Search to users of cognito groups.
https://github.com/aws-amplify/amplify-cli/issues/7850
unit tests and tested in a JS app
When adding a Map or Search Index, if the Amplify backend already has one or more cognito groups added, we will give the developer choice to grant Read only permissions to cognito groups in addition to the Auth/UnAuth roles. This is necessary since Geofencing capability of geo only supports Group based access aimed to be used by Geofence Admin users and they might also need to access the Map and/or Search capabilities.
The Walkthrough will look like this for `update` and is the same for `add` command:
By submitting this pull request, I confirm that my contribution is made under the terms of the …

feat(amplify-category-geo): add ability to grant permissions for Maps and Search to cognito groups

---

packages/amplify-cli/src/extensions/amplify-helpers/resource-status-data.ts

#9214 is a duplicate of #9363, this PR fix the 2nd part of #9363 which helps with already corrupted project files, where User Pool Groups are already present in meta file, but Cognito addition failed.
Fixes #9363 

fix: #9363 - additional checks in case of previously failed add auth

---

packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-index-transformer.test.ts
packages/amplify-graphql-index-transformer/src/schema.ts

Make hash key as non null type for index transformer v2.
https://github.com/aws-amplify/amplify-cli/issues/7499
- yarn test
- manual test

fix(graphql): make hash key as non null type for index transformer

---

packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-primary-key-transformer.test.ts
packages/amplify-graphql-index-transformer/src/utils.ts

This commit updates the get and list queries generated by `@primaryKey` to handle the case where the model name is all lowercase characters.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/9402
Fixes: https://github.com/aws-amplify/amplify-cli/issues/9392

fix: update @primaryKey get/list queries for lowercase models

---

packages/amplify-cli/src/__tests__/commands/env.test.ts
packages/amplify-cli/src/commands/env/add.ts

This addresses confusion caused for developers who respond `no` to `Do you plan on modifying this backend?` during `amplify pull`.
Since they've made this choice, the necessary meta files are not in place to run commands like `amplify add env`, and when they attempt to do so, they see an error like:
```
File at path: '/Users/xss/tmp/amplify/backend/amplify-meta.json' does not exist
Error: File at path: '/Users/xss/tmp/amplify/backend/amplify-meta.json' does not exist
at Function.JSONUtilities.readJson (/Users/xss/repos/amplify-cli-dec16/packages/amplify-cli-core/lib/jsonUtilities.js:40:19)
at StateManager.getData (/Users/xss/repos/amplify-cli-dec16/packages/amplify-cli-core/lib/state-manager/stateManager.js:298:56)
at StateManager.getMeta …
```

chore: improve `add env` error handling

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/__snapshots__/auth-stack-transform.test.ts.snap
packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts

Updated username configuration settings based on aliasAttributes instead of requiredAttributes
fix: #8895

fix: update cognito stack builder to set case sensitivity based on aliasAttribute

---

packages/amplify-graphql-predictions-transformer/src/__tests__/__snapshots__/amplify-graphql-predictions-transformer-override.test.ts.snap
packages/amplify-graphql-predictions-transformer/src/__tests__/__snapshots__/amplify-graphql-predictions-transformer.test.ts.snap
packages/amplify-graphql-predictions-transformer/src/graphql-predictions-transformer.ts
packages/amplify-graphql-transformer-core/src/transform-host.ts
packages/amplify-util-mock/src/__e2e_v2__/searchable-transformer.e2e.test.ts

This commit updates GraphQL transformer v2 to attach a function name to Lambdas that it creates. The function name is required by the mock server.
This also updates the function name used by `@predictions` to the correct value.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/9253

Searchable mock start

---

packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/graphql-types/mutation.ts
packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts
packages/graphql-dynamodb-transformer/src/definitions.ts

- add id field to update input objects
- manually

fix(graphql-model-transformer): add id field to update input objects

---

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/environmentVariablesHelper.test.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/environmentVariablesHelper.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts
packages/amplify-cli-core/src/index.ts
packages/amplify-cli-core/src/isCI.ts
packages/amplify-cli-core/src/utils/open.ts
packages/amplify-cli/src/domain/amplify-usageData/UsageDataPayload.ts

Fixes a bug in the logic to fill in missing function env vars during push. The existing logic would only write the last env var to team provider rather than all of them. Also cleaned up some low-hanging fruit in the surrounding code.
fixes https://github.com/aws-amplify/amplify-cli/issues/8111
manually tested and added unit tests

fix: append missing env vars in team provider on push

---

packages/amplify-cli-core/src/deploymentSecretsHelper.ts
packages/amplify-cli/src/input-params-manager.ts
packages/amplify-cli/src/utils/headless-input-utils.ts
packages/amplify-cli/src/utils/team-provider-migrate.ts

Fix an issue when secret migration could fail when `~/.aws/amplify/deployment-secrets.json` does not have an `appSecrets` property persisted.
Fix the `--yes` flag usage as `exeInfo` is not initialized when this prompt was executing.
Fixes #9061

fix: #9061 secret migration could fail and --yes was not working

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts

When auth had only TOTP enabled stack building fails. This PR fixes that.
Fixes #9070 - at least this part: https://github.com/aws-amplify/amplify-cli/issues/9070#issuecomment-979104053
Manual testing

fix: #9070 TOTP only auth configs are failing

---

packages/amplify-e2e-tests/schemas/simple_model_new_primary_key.graphql
packages/amplify-e2e-tests/src/__tests__/api_6.test.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/amplify-graphql-resource-manager.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts

Fixes a bug with destructive iterative updates where deploying the "nextState" as the second step of the iterative deployment was causing failures because the original resolvers are updated with the template rather than the new resolvers. This caused CFN failures when the new template tried to reference resolvers that didn't exist yet. Fixed by removing this step from the iterative deployment as it is not needed. Also fixed a bug in the iterative deployment logic where we were checking for steps.length > 1 instead of > 0. We had never run into this case before because we didn't have any single step iterative deployments (although there is a potential future optimization we can make to iterative GSI updates to skip the last step and have it be added in the final deployment step) …

fix: remove next template from destructive iterative update

---

packages/amplify-cli/src/init-steps/s9-onSuccess.ts
packages/amplify-console-integration-tests/src/consoleHosting/consoleHosting.ts
packages/amplify-e2e-core/src/init/initProjectHelper.ts
packages/amplify-e2e-core/src/utils/pinpoint.ts
packages/amplify-e2e-tests/src/environment/env.ts
packages/amplify-e2e-tests/src/init-special-cases/index.ts
packages/amplify-migration-tests/src/migration-helpers/init.ts

Correcting the "pro-tip" to use "push" instead of "publish" when customers first initialize a project.

Correcting the "pro-tip" to use "push" instead of "publish"

---

packages/amplify-category-api/package.json
packages/amplify-cli/package.json
packages/amplify-provider-awscloudformation/package.json
yarn.lock

There is an out of date dependency on `amplify-provider-awscloudformation`, which is pulling in a number of older dependency versions. This commit fixes the dependency version.
This commit also updates some of our test suites to use the Node testing environment instead of the default of jsdom. This is done because the default does not properly handle some Node globals.
Refs: https://github.com/panva/jose/issues/307

fix: update dep and use node test environment

---

.circleci/config.base.yml

Some times e2e tests can fail in CI due to compilation error. These tests fail later in the pipeline when individual e2e tests are run. Updating the build process to run these tests early to detect any compilation issues so build can bail early

ci: build tests as part of build step in CI

---

packages/amplify-cli/package.json
packages/amplify-provider-awscloudformation/package.json
packages/amplify-util-mock/package.json
yarn.lock

This commit pins the `amplify-codegen` dependency to an exact version to ensure the same codegen is used across the packaged CLI and the one installed from npm.

chore: pin codegen dependency version

---

packages/amplify-migration-tests/src/migration-helpers/init.ts

migration test expectations need to look for "publish" and non-migration tests look for "push" in
```
.wait(/Try "amplify add api" to create a backend API and then "amplify (push|publish)" to deploy everything/)
```

test: use 'publish' for migration tests

---

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/environmentVariablesHelper.ts
packages/amplify-category-predictions/provider-utils/awscloudformation/prediction-category-walkthroughs/storage-api.js
packages/amplify-e2e-tests/src/__tests__/storage-5.test.ts

This commit fixes failing E2E tests by properly importing the uuid dependency.

fix: update uuid imports

---

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/environmentVariablesHelper.ts

Removing the isCI check from the missing environment variables workflow to unblock the pipeline. Will follow up with a PR to reinstate the check with some special logic to handle our CI environment differently
https://135684-145880460-gh.circle-artifacts.com/0/packages/amplify-e2e-tests/amplify-e2e-reports/index.html

fix: temporarily remove isCI check from env var flow

---

packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
packages/amplify-graphql-model-transformer/src/graphql-types/mutation.ts
packages/graphql-dynamodb-transformer/src/__tests__/DynamoDBModelTransformer.test.ts
packages/graphql-dynamodb-transformer/src/definitions.ts
packages/graphql-key-transformer/src/KeyTransformer.ts
packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformerLocal.e2e.test.ts

- make the id on update input field required
- yarn test
- e2e tests

fix: make update input id field required

---

packages/amplify-cli/package.json
packages/amplify-provider-awscloudformation/package.json
packages/amplify-util-mock/package.json
yarn.lock

Bumping up the dependency on codegen for the flutter-preview tagged release of CLI.
N/A - working to get the tagged release slightly updated with bug fixes in advance of full release.
Flutter team tested the codegen changes locally, and verified functionality.

chore: upgrade codegen version for flutter-preview tagged release

---

packages/graphql-transformers-e2e-tests/package.json
packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthV2.e2e.test.ts
yarn.lock

this PR reverts #9432 which broke graphql e2e tests. This pr fixes the issue #9432 attempted to solve by instead temporarily ignoring ts version mismatch errors

chore: ignore ts issues in test

---

packages/amplify-cli/package.json
yarn.lock

There is currently an issue caused by our dependency on the "colors" package. This is discussed in https://github.com/npkgz/cli-progress/issues/116 with remediation recommendation of pinning to version `1.4.0`.
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```
is being thrown during `npm install` in low memory environments (such as from amplify studio/console containers)

chore: pin colors version

---

packages/amplify-category-geo/resources/custom-geofence-collection-resource-handler.js
packages/amplify-category-geo/resources/custom-map-resource-handler.js
packages/amplify-category-geo/resources/custom-place-index-resource-handler.js
packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/geofenceCollectionStack.test.ts.snap
packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/mapStack.test.ts.snap
packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/placeIndexStack.test.ts.snap
packages/amplify-category-geo/src/__tests__/service-utils/resourceUtils.test.ts
packages/amplify-category-geo/src/__tests__/service-utils/serviceUtils.test.ts
packages/amplify-category-geo/src/__tests__/service-walkthroughs/geofenceCollectionWalkthrough.test.ts
packages/amplify-category-geo/src/__tests__/service-walkthroughs/mapWalkthrough.test.ts
packages/amplify-category-geo/src/__tests__/service-walkthroughs/placeIndexWalkthrough.test.ts
packages/amplify-category-geo/src/provider-controllers/geofenceCollection.ts
packages/amplify-category-geo/src/provider-controllers/map.ts
packages/amplify-category-geo/src/service-stacks/geofenceCollectionStack.ts
packages/amplify-category-geo/src/service-stacks/mapStack.ts
packages/amplify-category-geo/src/service-stacks/placeIndexStack.ts
packages/amplify-category-geo/src/service-utils/constants.ts
packages/amplify-category-geo/src/service-utils/geofenceCollectionParams.ts
packages/amplify-category-geo/src/service-utils/geofenceCollectionUtils.ts
packages/amplify-category-geo/src/service-utils/mapUtils.ts
packages/amplify-category-geo/src/service-utils/placeIndexUtils.ts
packages/amplify-category-geo/src/service-utils/resourceParams.ts
packages/amplify-category-geo/src/service-utils/resourceUtils.ts
packages/amplify-category-geo/src/service-walkthroughs/geofenceCollectionWalkthrough.ts
packages/amplify-category-geo/src/service-walkthroughs/mapWalkthrough.ts
packages/amplify-category-geo/src/service-walkthroughs/placeIndexWalkthrough.ts
packages/amplify-category-geo/src/service-walkthroughs/resourceWalkthrough.ts
packages/amplify-headless-interface/schemas/geo/1/AddGeoRequest.schema.json
packages/amplify-headless-interface/src/interface/geo/add.ts

Location service team updated their APIs to only allow `RequestBasedUsage` pricing plan for Geo resources thereby deprecating the Asset based pricing plans. The below list of changes are necessary in Amplify CLI Geo plugin to accommodate that change.
- Removes the pricing plan walkthrough from `add/update` commands. Set the `PricingPlan` value for a geo resource to always be `RequestBasedUsage`.
- Removes the `dataProvider` from geofence collection walkthrough as this corresponds to `PricingPlanDataSource` which is no longer required if `PricingPlan` is always `RequestBasedUsage`.
- Warn when `Esri` data provider is chosen that the resource cannot be used for tracking/routing commercial assets.
- Change the default data provider to `HERE`
unit testing, JS sample app
By submitting this …

Remove pricing plan walkthrough

---

.circleci/local_publish_helpers.sh
package.json

This PR fixes an issue where the pipeline is not using bash properly and has missing dependencies for the uibuilder.test.ts

ci: ensure bash and dependencies are being used
