aws-amplify/amplify-cli

packages/amplify-e2e-core/src/init/initProjectHelper.ts, packages/amplify-e2e-core/src/utils/nexpect.ts, packages/amplify-e2e-tests/src/__tests__/migration/node.function.test.ts
chore: move ci disable to push from init
=> chore: move ci disable to push from init

packages/graphql-transformers-e2e-tests/src/cognitoUtils.ts
=> test(graphql-transformers-e2e-tests): hard code region to us-west-2

packages/graphql-transformers-e2e-tests/package.json, packages/graphql-transformers-e2e-tests/resources/jsonServer/yarn.lock, packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthModelAuthTransformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/MutationCondition.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts
https://github.com/yuth/amplify-cli/commit/b30eadd697e8f099cf8da31f54bdd3b573c296c2
Test fixes extended from commit ^, updated the aws-appsync
=> test: test fixes for gql subscription

packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/promiseWithTimeout.ts
Swapped Graphql Client with Amplify JS to test Subscriptions
applying work from https://github.com/SwaySway/amplify-cli/commit/0f983455eece134e200c29cc14b114070ea42a79
=> test: uses amplify js for subscription

.github/PULL_REQUEST_TEMPLATE.md
- update PR template with checklist items
=> chore(pr request template): update PR template with checklist items

packages/amplify-cli/__mocks__/faked-plugin.js, packages/amplify-cli/src/__tests__/extensions/amplify-helpers/delete-project.test.ts
Increase test coverage of amplify-cli package.
=> test(cli): add test for delete-project extension

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/copy-batch.test.ts
=> test(cli): add test for copy-batch extension

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/docs-manager.test.ts, packages/amplify-cli/src/__tests__/extensions/amplify-helpers/envResourceParams.test.ts, packages/amplify-cli/src/__tests__/extensions/amplify-helpers/get-env-info.test.ts
Fixes unnecessary nested path. Can be fast-track as the diff does not affect any processing.
=> test(cli): refactor import path in extentsion tests

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/confirm-prompt.test.ts
Increase test coverage of cli.
=> test(cli): add test for confirm-prompt extension

packages/amplify-e2e-tests/src/amplify-app-helpers/amplify-app-validation.ts
Replacement PR for https://github.com/aws-amplify/amplify-cli/pull/6800
=> test: check boolean values instead of truthy/falsy

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/get-plugin.test.ts
Increase coverage for amplify-cli.
=> test(cli): add test for get-plugin extension

packages/amplify-cli/src/__tests__/utils/set-ops.test.ts
Increase coverage for amplify-cli.
=> test(cli): add test for utils/set-ops

packages/amplify-e2e-tests/package.json, packages/amplify-e2e-tests/src/__tests__/migration/api.key.migration2.test.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/amplify-graphql-resource-manager.ts, packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts, packages/graphql-transformer-core/src/__tests__/util/__snapshots__/amplifyUtils.test.ts.snap, packages/graphql-transformer-core/src/__tests__/util/amplifyUtils.test.ts, packages/graphql-transformer-core/src/index.ts, packages/graphql-transformer-core/src/util/amplifyUtils.ts, packages/graphql-transformer-core/src/util/index.ts, packages/graphql-transformer-core/src/util/sanity-check.ts
*Issue #6192 
*  passing a list of sanity checks to be performed over api 
* added e2e test for the same
=> fix: stop sanity check when resource is in create status

packages/amplify-e2e-tests/src/__tests__/function_3.test.ts
Fixes e2e test that invokes python lambda on the cloud
=> test: cloud lambda needs to match stringify

packages/amplify-category-auth/src/provider-utils/awscloudformation/index.js, packages/amplify-e2e-tests/src/environment/env.ts
=> fix: exclude env add from check

packages/amplify-console-hosting/utils/config-utils.js
This commit removes several redundant assignments and an `if` statement.
=> refactor(amplify-console-hosting): simplify config-utils code

packages/amplify-appsync-simulator/src/__tests__/utils/auth-helpers/current-auth-mode.test.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/utils/rest-api-path-utils.ts, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreSignup/PreSignup.map.json, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreSignup/cloudformation-templates/PreSignup.json.ejs, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreSignup/email-filter-allowlist-legacy.js, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreSignup/email-filter-allowlist.js, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreSignup/email-filter-denylist-legacy.js, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreSignup/email-filter-denylist.js, packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/trigger-flow-auth-helper.test.js, packages/amplify-category-auth/src/provider-utils/awscloudformation/assets/string-maps.js, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/trigger-flow-auth-helper.js, packages/amplify-cli-core/src/feature-flags/featureFlags.ts, packages/amplify-e2e-core/src/categories/auth.ts, packages/amplify-e2e-tests/src/__tests__/auth_4.test.ts, packages/amplify-frontend-javascript/lib/frontend-config-creator.js, packages/amplify-graphql-types-generator/src/swift/helpers.ts, packages/amplify-migration-tests/src/__tests__/update_tests/auth_migration_update.test.ts
This commit replaces the use of whitelist and blacklist throughout the codebase with allowlist and denylist.
No associated issue, but this builds on #6331 and #5497.
Local testing and E2E tests.
=> fix(cli): use more inclusive language

packages/amplify-provider-awscloudformation/src/__tests__/setup-new-user.test.ts
Follow up PR to https://github.com/aws-amplify/amplify-cli/pull/6908.
> lerna --scope amplify-provider-awscloudformation run test
=> test(amplify-provider-awscloudformation): add test for setup-new-user

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/construct-exeInfo.test.ts
=> test(cli): add test for construct-exeInfo extension

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/editor-selection.test.ts
=> test(cli): add test for editor selection extension

packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js
Introduces CFN logging  for debug purposes. This was reverted as a part to test out a deployment issue.
Reverts aws-amplify/amplify-cli#6119
=> feat(amplify-provider-awscloudformation): add CFN logging

packages/amplify-e2e-core/src/asciinema-recorder.ts
=> ci: update ascii recorder

packages/amplify-app/package.json, packages/amplify-app/src/index.js
Added explicit messaging for amplify app creation
=> feat: added more explicit messaging

packages/amplify-provider-awscloudformation/src/graphql-transformer/amplify-graphql-resource-manager.ts
dont create state dir when there are no template state changes
=> fix(amplify-provider-awscloudformation): fix state dir creation

packages/amplify-provider-awscloudformation/src/iterative-deployment/deployment-manager.ts, packages/amplify-provider-awscloudformation/src/iterative-deployment/helpers.ts, packages/amplify-provider-awscloudformation/src/iterative-deployment/state-machine.ts
- edit s3 url path
- move errors to message as stack truncates this
- include state value as string object
=> fix(amplify-provider-awscloudformation): fix http path for s3 url

packages/amplify-provider-awscloudformation/package.json, packages/graphql-transformers-e2e-tests/package.json, packages/graphql-transformers-e2e-tests/resources/jsonServer/package.json, yarn.lock
Update netmask dependency to version 2.0.2
=> chore(amplify-provider-awscloudformation): update netmask dependency

packages/amplify-app/src/index.js
Changed import to require
``` bash
cd packages/amplify-e2e-test/
yarn e2e src/__tests__/datastore-modelgen.test.ts
```
=> fix: fixed the import -> require

.circleci/config.yml
pin cypress version to 6.x to continue testing in node10
=> ci: pin cypress version

.circleci/config.base.yml, .circleci/config.yml
=> ci: pin cypress 6.8.0 until node10 EOL

.circleci/config.yml, yarn.lock
Update the transient cssnano dependency
=> chore: update yarn.lock

.circleci/config.yml, packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js
Added resourceName as identifier in trigger policy
tested locally
=> fix: adding resourceName to lambda trigger policy

packages/amplify-cli/src/context-manager.ts
=> fix: fixes e2e bug

packages/amplify-e2e-core/src/categories/storage.ts
increase timeout for addDDBWithGSIWithSettings
=> test(amplify-e2e-core): increase timeout for storage add

packages/amplify-e2e-core/src/categories/storage.ts
=> test(amplify-e2e-core): remove timeout setting for storage add

package.json
Added --include-dotfiles to pkg babel script. Tests were failing because the pkg cli couldn't find a .gitignore file.
https://1439-145880460-gh.circle-artifacts.com/0/packages/amplify-e2e-tests/amplify-e2e-reports/index.html
Ran failed tests locally against new pkg cli
=> add --include-dotfiles to pkg babel script

.circleci/config.yml
=> chore: remove amplify logging from graphql e2e

.circleci/config.yml, packages/amplify-cli-core/src/deploymentState.ts, packages/amplify-cli-core/src/feature-flags/featureFlags.ts, packages/amplify-cli-core/src/index.ts, packages/amplify-cli/src/extensions/amplify-helpers/push-resources.ts, packages/amplify-e2e-core/src/init/amplifyPush.ts, packages/amplify-e2e-core/src/utils/nexpect.ts, packages/amplify-e2e-core/src/utils/sdk-calls.ts, packages/amplify-e2e-tests/schemas/iterative-push/two-key-add/final-schema.graphql, packages/amplify-e2e-tests/schemas/iterative-push/two-key-add/initial-schema.graphql, packages/amplify-e2e-tests/src/__tests__/schema-iterative-rollback-1.test.ts, packages/amplify-e2e-tests/src/__tests__/schema-iterative-rollback-2.test.ts, packages/amplify-provider-awscloudformation/src/__tests__/iterative-deployment/deployment-state-manager.test.ts, packages/amplify-provider-awscloudformation/src/__tests__/iterative-deployment/state-machine.test.ts, packages/amplify-provider-awscloudformation/src/aws-utils/aws-s3.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/amplify-graphql-resource-manager.ts, packages/amplify-provider-awscloudformation/src/initialize-env.ts, packages/amplify-provider-awscloudformation/src/iterative-deployment/constants.ts, packages/amplify-provider-awscloudformation/src/iterative-deployment/deployment-manager.ts, packages/amplify-provider-awscloudformation/src/iterative-deployment/deployment-state-manager.ts, packages/amplify-provider-awscloudformation/src/iterative-deployment/helpers.ts, packages/amplify-provider-awscloudformation/src/iterative-deployment/index.ts, packages/amplify-provider-awscloudformation/src/iterative-deployment/iterative-rollback.ts, packages/amplify-provider-awscloudformation/src/iterative-deployment/state-machine.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts
- added updates to Deployment State Types in cli core
- Updated push at the root cli level to validate `--iterative-rollback`
- add iterative rollback before pushing resources
- changed the error stack for deployment errors to include messages as stack gets cut off
- add unit test for updated rollback state machine
- e2e tests on iterative rollback (each test is between 30-45min)
- implemented a trail of prev deployments when running iterative deployment (to be used by iterative rollback in case client loses connection) this deployment meta is then deleted if the cloud deployment is successful.
- State Dir is intended to be ephemeral CLI will also delete the s3 state dir in cloud on iterative deployment and rollback. 
By submitting this pull request, I confirm that my contribution is made …
=> feat(amplify-provider-awscloudformation):  add `--iterative-rollback`

packages/amplify-cli/src/__tests__/context-manager.test.ts, packages/amplify-cli/src/context-manager.ts
Removed sts call for usage-data 
=> fix: removing sts call for usage data

.circleci/config.base.yml, .circleci/config.yml, packages/amplify-e2e-core/src/utils/sdk-calls.ts, packages/amplify-e2e-tests/src/__tests__/schema-iterative-rollback-1.test.ts, packages/amplify-e2e-tests/src/__tests__/schema-iterative-rollback-2.test.ts, packages/amplify-provider-awscloudformation/src/aws-utils/aws-s3.ts, scripts/split-e2e-tests.ts
- update delete for delete all objects and delete directory
- update iterative rollback e2e to reference correct function
- update split e2e tests with rollback times
- ensure disable amplify logging environment variable is added into the ci config
=> fix: fix iterative delete for all objects and delete directory

packages/amplify-e2e-core/src/utils/sdk-calls.ts, packages/amplify-e2e-tests/src/__tests__/schema-iterative-update-locking.test.ts
=> test: update sdk calls and regex for iterative locking

packages/amplify-e2e-core/src/init/amplifyPush.ts, packages/amplify-e2e-tests/src/__tests__/schema-iterative-rollback-1.test.ts, packages/amplify-e2e-tests/src/__tests__/schema-iterative-rollback-2.test.ts, packages/amplify-provider-awscloudformation/src/iterative-deployment/deployment-state-manager.ts
=> Rollback e2e regex

packages/amplify-e2e-core/src/configure/index.ts
Fix failing e2e test for containers
Local run of e2e tests `configure-project.test.ts`, and `containers-api.test.ts`
=> test: update configure project helper to fix containers e2e

.circleci/config.base.yml, .circleci/config.yml
Update the CircleCI configuration to use contexts instead of using global environment variables  
=> ci: use CircleCI contexts to run tests

packages/amplify-category-function/src/index.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambdaLayerWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/constants.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerConfiguration.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerParams.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts, packages/amplify-e2e-core/src/categories/lambda-layer.ts, packages/amplify-e2e-tests/src/__tests__/layer.test.ts, packages/amplify-e2e-tests/src/environment/env.ts, packages/amplify-provider-awscloudformation/src/prePushLambdaLayerPrompt.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts
Added push flow and fixed the tests
=> feat: lambda layers new version push flow

.circleci/config.base.yml, .circleci/config.yml
=> ci: add context for graphql-e2e tests

packages/amplify-e2e-core/src/init/amplifyPush.ts, packages/amplify-e2e-tests/src/__tests__/schema-iterative-rollback-1.test.ts, packages/amplify-e2e-tests/src/__tests__/schema-iterative-rollback-2.test.ts, packages/amplify-provider-awscloudformation/src/iterative-deployment/deployment-manager.ts
=> fix: render spinner in stateChange update e2e to wait on spinner text

.circleci/config.base.yml, .circleci/config.yml
=> test: add e2e auth credentials context in amplify pkg e2e

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/execute-provider-utils.test.ts
=> test(cli): add test for execute provider utils extension

packages/amplify-provider-awscloudformation/src/__tests__/utils/amplify-resource-state-utils.test.ts
add tests for  `amplify-resource-state-utils.ts` in `amplify-provider-awscloudformation` package.
#7050 
`yarn test`
=> test(amplify-provider-awscloudformation): add tests for amplify-resource-state-utils.ts

packages/amplify-provider-awscloudformation/src/__tests__/utils/resolve-appId.test.ts
add tests for  `resolve-appId.ts` in `amplify-provider-awscloudformation` package.
#7050 
`yarn test`
=> test(amplify-provider-awscloudformation): add tests for resolve-appId.ts

packages/amplify-provider-awscloudformation/src/__tests__/iterative-deployment/stack-event-monitor.test.ts
add tests for  `stack-event-monitor.ts` in `amplify-provider-awscloudformation` package.
#7050 
`yarn test`
=> test(amplify-provider-awscloudformation): add tests for stack-event-monitor.ts

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/get_all_envs.test.ts
=> test(cli): add test for get_all_envs extension

.circleci/config.base.yml, .circleci/config.yml
=> test: add test auth credentials for nightly console integ

packages/amplify-e2e-core/src/configure/index.ts
Update mock access keys to pass new validation that was introduced in https://github.com/aws-amplify/amplify-cli/pull/6986
=> test: update mock access keys to pass new validation

packages/amplify-e2e-tests/src/__tests__/api_2.test.ts
This commit removes an unused import.
Ran an E2E test.
=> fix: remove unused import

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/get-category-pluginInfo.test.ts
=> test(cli): correcting test for get category pluginInfo extension

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/envResourceParams.test.ts
=> test(cli): correcting test for envResourceParams extension

packages/amplify-provider-awscloudformation/src/__tests__/utils/archiver.test.ts
add tests for  `utils/archiver.js` in `amplify-provider-awscloudformation` package.
closes #7050 
`yarn test`
=> test(amplify-provider-awscloudformation): add tests for utils/archiver.js

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts, packages/amplify-cli/src/__tests__/extensions/amplify-helpers/execute-provider-utils.test.ts, packages/amplify-e2e-tests/layerdata/python/PipFile, packages/amplify-e2e-tests/layerdata/python/index.py, packages/amplify-e2e-tests/src/__tests__/function_4.test.ts, packages/amplify-python-function-runtime-provider/src/util/packageUtils.ts
* fix python layer tests
* changed order to save layer state then cfn templates
* updated tests for the changes
=> fix: python layer tests

packages/amplify-provider-awscloudformation/src/__tests__/system-config-manager.test.ts, packages/amplify-provider-awscloudformation/src/system-config-manager.ts
fix incorrect validation introduced in https://github.com/aws-amplify/amplify-cli/pull/7017
Ran unit tests and successfully completed `amplify init` using an IAM role in a profile
=> fix: profile validation to include source_profile and role_arn

packages/amplify-category-function/src/index.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambdaLayerWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/removeLayerWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/addLayerToFunctionUtils.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/constants.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/convertLayersTypes.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/lambda-layer-cloudformation-template.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerCloudState.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerConfiguration.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts, packages/amplify-cli/src/commands/push.ts, packages/amplify-e2e-core/src/categories/lambda-layer.ts, packages/amplify-e2e-tests/layerdata/python/index.py, packages/amplify-provider-awscloudformation/src/constants.js, packages/amplify-provider-awscloudformation/src/lambdaLayerInvocations.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts
=> fix: various bug fixes, mainly generated cfn template

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/addLayerToFunctionWalkthrough.test.ts, packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/__snapshots__/convertLayersTypes.test.ts.snap, packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/addLayerToFunctionUtil.test.ts, packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/convertLayersTypes.test.ts, packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/packageLayer.test.ts
=> test: update unit tests for layers-rework

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts
=> fix: only package lambda layer when new version is created

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/removeWalkthrough.test.ts, packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/packageLayer.test.ts, packages/amplify-e2e-core/src/categories/lambda-layer.ts, packages/amplify-e2e-tests/src/__tests__/layer.test.ts
Added test to include test for remove layer tests
=> test: remove layer unit and e2e tests

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/removeWalkthrough.test.ts, packages/amplify-category-function/src/index.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambdaLayerWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/removeLayerWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/constants.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/lambda-layer-cloudformation-template.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerCloudState.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerConfiguration.ts, packages/amplify-category-function/src/provider-utils/supportedServicesType.ts, packages/amplify-cli/src/commands/push.ts, packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts, packages/amplify-provider-awscloudformation/src/lambdaLayerInvocations.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts
- Enable updating permissions for previously deployed layers
- Ensure `#current-cloud-backend` does not contain stale ephemeral state data
- Make listing layer versions consistent across `amplify update function` and `amplify remove function`
- Clean up various imports
yarn test and manual testing
=> fix: update previously deployed layer versions and dx/bug fixes

packages/amplify-category-function/src/provider-utils/awscloudformation/types/packaging-types.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageFunction.ts
=> fix: package Lambda functions correctly

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/addLayerToFunctionUtil.test.ts, packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/packageFunction.test.ts, packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/packageLayer.test.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambdaLayerWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/addLayerToFunctionUtils.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts, packages/amplify-e2e-core/src/init/amplifyPush.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts
=> fix: add layer to function dx, update prompt text

.circleci/config.base.yml, .circleci/config.yml
=> ci: update apt cache before installing java

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/get-imported-auth-properties.test.ts
=> test(cli): add test for get-imported-auth-properties extensions

packages/amplify-graphiql-explorer/src/AuthModal.tsx
Updated amplify-graphiql-explorer to expose a text area to support adding custom fields to cognito
JWT. This will allow selecting a custom claims auth claims in AppSync simulator
re #6106
=> feat: add mock support for custom fields in cognito jwt

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/get-frontend-plugins.test.ts
=> test(cli): add test for get frontend plugins extensions

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/update-backend-config.test.ts
=> test(cli): add test for update-backend-config.ts

.circleci/config.yml, Dockerfile
=> Update base image to NodeJS 12

.circleci/config.yml
=> ci: build image only from e2e-image-build

.circleci/config.base.yml
=> ci: run apt-get update before install

packages/amplify-graphql-function-transformer/package.json, packages/amplify-graphql-http-transformer/package.json, packages/amplify-graphql-model-transformer/package.json, packages/amplify-graphql-transformer-core/package.json, packages/amplify-graphql-transformer-interfaces/package.json
Add `publishConfig` to namespaced packages, to enable successful publish.
=> chore: add publish public to namespaced packages

packages/amplify-provider-awscloudformation/src/__tests__/system-config-manager.test.ts, packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js, packages/amplify-provider-awscloudformation/src/initializer.js, packages/amplify-provider-awscloudformation/src/system-config-manager.ts
The CLI throws ugly error if the initialization of project fails when the bucket limit is hit. This change shows list of errors instead of a stack trace
```
ROLLBACK_COMPLETE amplify-initfail-dev-160404 AWS::CloudFormation::Stack Fri Apr 30 2021 16:04:20 GMT-0700 (Pacific Daylight Time)
⠏ Initializing project in the cloud...An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
TypeError: Cannot read property 'Stacks' of null
at processStackCreationData (/Users/yathiraj/.config/yarn/global/node_modules/amplify-provider-awscloudformation/src/initializer.js:108:44)
at Object.run (/Users/yathiraj/.config/yarn/global/node_modules/amplify-provider-awscloudformation/src/initializer.js:80:7)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
``` …
=> fix: show error message when project initalization fail

packages/amplify-category-auth/package.json, packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs, packages/amplify-category-auth/resources/lambda-function.js, packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/trigger-flow-auth-helper.test.js, packages/amplify-category-auth/src/provider-utils/awscloudformation/constants.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthrough-types.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/generate-auth-trigger-template.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/synthesize-resources.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/trigger-flow-auth-helper.js, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/verification-bucket-name.ts, packages/amplify-cli-core/src/feature-flags/featureFlags.ts, packages/amplify-e2e-tests/src/__tests__/auth_2.test.ts, packages/amplify-e2e-tests/src/__tests__/function_1.test.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts, packages/amplify-provider-awscloudformation/src/utils/env-level-constructs.ts, packages/amplify-provider-awscloudformation/src/utils/upload-auth-trigger-template.ts, yarn.lock
Enabling Auth Triggers using custom lambda to break circular Dependency
* added an e2e test to check if trigger is enabled in UserPool
=> Enabling Auth Triggers using custom lambda

packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs
changed ejs template to check for empty trigger object
* manually testing the ejs template running e2e tests locally
=> fix: failing e2e tests 

Readme.md
- update min req node version
- Impacting change - https://github.com/aws-amplify/amplify-cli/pull/7214
- Documentation update - https://github.com/aws-amplify/docs/pull/3187
=> chore(readme): update min req node version

.circleci/config.base.yml, .circleci/config.yml
Expose e2e-test context to cleanup script task
=> ci: expose e2e test cotext for cleanup scripts

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/git-manager.test.ts
=> test(cli): add test for git-manager.ts

packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.ts
Update warning message when creating overlapping REST API paths
=> fix: update overlapping REST path warning

packages/amplify-graphql-docs-generator/__tests__/generator/utils/loading.test.ts, packages/amplify-graphql-docs-generator/fixtures/invalidSchema.json, packages/amplify-graphql-docs-generator/fixtures/schemaWithoutDataProperty.json
Increase test coverage of amplify-graphql-docs-generator.
lerna --scope amplify-graphql-docs-generator run test
=> test: add test for graphql-docs-generator

packages/amplify-provider-awscloudformation/src/iterative-deployment/deployment-manager.ts, packages/amplify-provider-awscloudformation/src/iterative-deployment/stack-event-monitor.ts, packages/amplify-provider-awscloudformation/src/utils/aws-logger.ts
- add logging in `deployment-manager` and `stack-event-monitor`
- add types for `aws-logger`
- add `maxRetries` option when creating DynamoDB Client
=> fix(amplify-provider-awscloudformation): add logger to iterative deployments

packages/amplify-e2e-core/src/categories/auth.ts, packages/amplify-e2e-tests/src/import-helpers/settings.ts
updated prompt with idp apple prompt
=> test: added prompt for apple id oauth

packages/amplify-e2e-core/src/categories/auth.ts, packages/amplify-migration-tests/src/__tests__/migration_tests/auth-deployment-migration/auth.deployment.secrets.test.ts
version 4.30.x still has the old walkthrough for social integration
=> test: added auth walkthrough for v30

packages/amplify-e2e-tests/src/__tests__/auth_2.test.ts
increment count as the CLI now supports Apple
=> test: modified count for supported identity providers

packages/amplify-cli-core/src/feature-flags/featureFlags.ts
Adds a CLI Feature Flag called `handleListNullabilityTransparently` to configure list nullability for Datastore Modelgen process. 
Relevant Codegen PR: https://github.com/aws-amplify/amplify-codegen/pull/142
Relevant docs PR: https://github.com/aws-amplify/docs/pull/3213
https://github.com/aws-amplify/amplify-codegen/issues/104
`yarn test`
=> chore: add Feature Flag to release changes related to Handling List nullability for Android, IOS Datastore modelgen

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/removeWalkthrough.test.ts, packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/lambda-layer-cloud-formation-template.test.ts, packages/amplify-category-function/src/index.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambdaLayerWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/removeLayerWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/addLayerToFunctionUtils.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/buildLayer.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/constants.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/lambda-layer-cloudformation-template.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerCloudState.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerConfiguration.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerMigrationUtils.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerParams.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts, packages/amplify-category-function/src/provider-utils/supported-services.ts, packages/amplify-category-function/src/provider-utils/supportedServicesType.ts, packages/amplify-provider-awscloudformation/src/constants.js, packages/amplify-provider-awscloudformation/src/lambdaLayerInvocations.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts
=> feat: migrate existing Lambda layer resources

packages/amplify-nodejs-function-runtime-provider/src/utils/legacyPackage.ts
=> fix: layer packaging

packages/amplify-e2e-core/src/categories/lambda-layer.ts, packages/amplify-e2e-core/src/init/amplifyPush.ts, packages/amplify-e2e-tests/src/__tests__/api_1.test.ts, packages/amplify-e2e-tests/src/__tests__/function_4.test.ts, packages/amplify-e2e-tests/src/__tests__/layer.test.ts
Fix existing layer e2e tests, to pass with recent layer changes.
Executing e2e tests
=> test: fix existing layer e2e tests to pass

packages/amplify-cli/src/__tests__/commands/init.test.ts, packages/amplify-cli/src/init-steps/postInitSetup.ts, packages/amplify-cli/src/init-steps/preInitSetup.ts
=> test(cli): add missing mocks

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/getDependentFunction.test.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/getDependentFunction.ts
Added an if condition to check for undefined value of dependsOn
* added a unit test condition to check for dependsOn 
=> fix: added check for undefined dependsOn

.circleci/config.yml, packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/message-printer.test.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/handlers/resource-handlers.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/message-printer.ts, packages/amplify-provider-awscloudformation/src/__tests__/display-helpful-urls.test.ts, packages/amplify-provider-awscloudformation/src/aws-utils/aws-sns.ts, packages/amplify-provider-awscloudformation/src/display-helpful-urls.js
This change enables Amplify CLI add support for querying the SNS SMS Sandbox status. The SDK changes are still not released but when the SDK change is available, CLI should be able to query the sandbox status.
=> feat: prep work for Cognito SMS Sandbox #2

.circleci/config.base.yml, .circleci/config.yml, package.json
=> chore: tagged release for layers - NOT FOR PRODUCTION

package.json, yarn.lock
=> build: update commitizen to latest

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/get-env-details.test.ts
=> test(cli): add test for get-env-details.ts

.github/ISSUE_TEMPLATE/config.yml, .github/workflows/lock.yaml
- chore(issue picker): add link to Discord server as an option for help
- chore(gh actions): add action to locked closed threads after 30 days of inactivity
=> chore(gh actions): lock closed issues after inactivity

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/auth-sms-workflow-helper.test.ts, packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/message-printer.test.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-sms-workflow-helper.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/message-printer.ts, packages/amplify-provider-awscloudformation/src/display-helpful-urls.js
remove duplicate function which had same code and update tests
=> chore: remove duplicate code

packages/amplify-category-auth/src/provider-utils/awscloudformation/constants.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthrough-types.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-request-adaptors.ts, packages/amplify-headless-interface/src/interface/auth/add.ts
=> feat(amplify-category-auth): adding apple as identity provider

packages/amplify-appsync-simulator/package.json, packages/amplify-category-auth/package.json, packages/amplify-category-predictions/package.json, packages/amplify-cli/package.json, packages/amplify-console-hosting/package.json, packages/amplify-console-integration-tests/package.json, packages/amplify-dynamodb-simulator/package.json, packages/amplify-e2e-tests/package.json, packages/amplify-migration-tests/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-provider-awscloudformation/src/aws-utils/aws-sns.ts, packages/amplify-provider-awscloudformation/src/configuration-manager.ts, packages/amplify-storage-simulator/package.json, packages/amplify-util-import/package.json, packages/amplify-util-mock/package.json, packages/graphql-relational-schema-transformer/package.json, packages/graphql-transformers-e2e-tests/package.json, yarn.lock
Update CLI to add support for SMS Sandbox support
=> feat: add support for SMS Sandbox

banner-message.json
=> feat: add banner message with SMS Sandbox messages

packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambdaLayerWalkthrough.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/updateDependentFunctionCfn.ts, packages/amplify-e2e-core/src/categories/lambda-layer.ts, packages/amplify-e2e-tests/src/__tests__/function_4.test.ts, packages/amplify-e2e-tests/src/__tests__/layer-2.test.ts, packages/amplify-e2e-tests/src/__tests__/layer.test.ts
=> test: update e2e tests, add types for settings parameters

.circleci/config.base.yml, .circleci/config.yml, packages/amplify-e2e-core/src/categories/lambda-layer.ts, packages/amplify-e2e-core/src/index.ts, packages/amplify-e2e-core/src/init/amplifyPush.ts, packages/amplify-e2e-tests/src/__tests__/layer.test.ts, packages/amplify-migration-tests/package.json, packages/amplify-migration-tests/src/__tests__/migration_tests/lambda-layer-migration/layer-migration.test.ts, packages/amplify-migration-tests/src/__tests__/update_tests/function_migration_update.test.ts, packages/amplify-migration-tests/src/migration-helpers/check-version.ts, packages/amplify-migration-tests/src/migration-helpers/index.ts, packages/amplify-migration-tests/src/migration-helpers/legacy-lambda-layer.ts
=> test: add migration tests for Lambda layers

packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/addLayerToFunctionUtils.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts, packages/amplify-cli-core/src/cliGetCategories.ts
=> refactor: address pr feedback

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/buildLayer.test.ts, packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/lambda-layer-cloud-formation-template.test.ts, packages/amplify-cli/src/display-banner-messages.ts, packages/amplify-e2e-core/src/utils/projectMeta.ts
Ran all Lambda layer e2e tests, yarn test
=> fix: display banner msg error when fn category missing from meta

packages/amplify-cli/src/display-banner-messages.ts, packages/amplify-e2e-core/src/index.ts, packages/amplify-migration-tests/src/migration-helpers/check-version.ts, packages/amplify-migration-tests/src/migration-helpers/legacy-lambda-layer.ts
=> refactor: address even more PR feedback

packages/amplify-provider-awscloudformation/src/aws-utils/aws-lambda.ts
=> fix: type mismatch after merge

.circleci/config.base.yml, .circleci/config.yml, packages/amplify-app/package.json, packages/amplify-cli/src/index.ts, packages/amplify-migration-tests/package.json
Breaking: bump CLI version to 5.0.0 for upcoming Lambda layers rework release
=> chore!: bump amplify-app to v5, fix migration tests

.circleci/config.base.yml, .circleci/config.yml
=> chore: update config.base.yml to require passing layer migration tests

packages/amplify-category-auth/src/provider-utils/awscloudformation/constants.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/index.js, packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthrough-types.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-request-adaptors.ts, packages/amplify-headless-interface/src/interface/auth/add.ts
=> Category auth/apple sign in - don't require SIWA on headless init

packages/amplify-cli/readme.md
Dummy change to trigger release workflow for tag version.
Could revert back in a subsequent PR.
=> chore: dummy change to release tag version

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json
updates the CLI dependency on codegen to `flutter-preview` tag.
`yarn setup-dev` installs latest tagged codegen.
Tested using a flutter app that it uses the preview modelgen. 
=> feat(amplify-cli): update codegen dependency to tag version

packages/amplify-e2e-tests/src/__tests__/api_2.test.ts
This commit fixes several warnings in the test file.
Ran the modified test.
=> chore: fix warnings in api_2.test.ts

.github/workflows/lock.yaml
- ~~chore(gh action): reduce # of days for closed PRs to become locked from **365** -> **30**~~
- chore(lock gh action): revert inactivity interval + reduce cron to 1 run per day
=> chore(gh action): reduce # of days of inactivity for closed PRs to become locked

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/remove-resource.test.ts
=> test: update test expect value

packages/amplify-util-mock/src/__e2e__/connections-with-auth-tests.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/dynamo-db-model-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/function-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/key-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/key-with-auth.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/model-auth-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/model-connection-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/model-connection-with-key-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/multi-auth-model-auth-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/per-field-auth-tests.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/subscriptions-with-auth.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/util-method-e2e.test.ts, packages/amplify-util-mock/src/__e2e__/versioned-model-transformer.e2e.test.ts
Adds the pluralization feature flag to the gql e2e tests. All other changes are linting changes
=> test: add ff to gql test transformer

packages/amplify-appsync-simulator/package.json, packages/amplify-util-mock/package.json, packages/graphql-transformers-e2e-tests/package.json, yarn.lock
Update dependencies in `package.json`'s instead of just `yarn.lock`.
Replaces https://github.com/aws-amplify/amplify-cli/pull/7424
`yarn test`
=> chore: update ws dependency to ^7.4.6

.circleci/config.yml, packages/amplify-e2e-tests/package.json, packages/amplify-e2e-tests/src/__tests__/frontend_config_drift.test.ts, packages/amplify-e2e-tests/src/frontend-config-drift.sh, yarn.lock
Moving a frontend config test into the e2e test suite
Ran tests locally
=> test: add frontend config drift check to e2e suite

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/get-provider-plugins.test.ts
=> test(cli): add test for get-provider-plugin.ts

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/input-validation.test.ts
=> test(cli): add test for input-validation extentions

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/cfn-api-artifact-handler.test.ts, packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/legacy-add-resource.test.ts, packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/check-case-sensitivity.test.ts
Fixes unit tests that broke due to https://github.com/aws-amplify/amplify-cli/pull/7615
ran tests locally
=> test: update tests for api name fix

packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerConfiguration.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts
Follow-up to https://github.com/aws-amplify/amplify-cli/pull/7603 which fixed the underlying issue. This PR fixes any projects in a broken state as a result of the migration miss.
https://github.com/aws-amplify/amplify-cli/issues/7622 https://github.com/aws-amplify/amplify-cli/issues/7555
Manual testing, `yarn test`
=> fix(amplify-category-function): incorrectly migrated layers' parameters.json

packages/amplify-cli-core/src/feature-flags/featureFlags.ts
Adds a Feature Flag to code generate DataStore models for Flutter Apps based on the null safety setting.
unit tests run successfully
=> feat(amplify-cli-core): add FF for flutter null safety release

packages/amplify-appsync-simulator/src/velocity/util/transform/dynamodb-filter.ts, packages/amplify-appsync-simulator/src/velocity/util/transform/index.ts, packages/amplify-graphql-model-transformer/src/resolvers/common.ts, packages/amplify-graphql-model-transformer/src/resolvers/mutation.ts, packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.tests.ts.snap
This commit contains the remaining fixes to get GraphQL Transformer v2 working with the mock functionality.
Manual testing.
=> fix: get mock working with gql transformer v2

packages/amplify-graphql-searchable-transformer/src/__tests__/amplify-graphql-searchable-transformer.tests.ts, packages/amplify-graphql-searchable-transformer/src/cdk/create-es-domain.ts
This change upgrades ElasticSearch from 6.x to 7.x.
[Link to Searchable RFC document](https://github.com/aws-amplify/amplify-cli/issues/7546)
NA.
- Manual test
- yarn test passed
=> feat(cli): upgrade elastic search version to 7.x

packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.tests.ts.snap, packages/amplify-graphql-searchable-transformer/src/generate-resolver-vtl.ts, packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
This change allows to use ElasticSearch sort with multiple fields.
[Link to Searchable RFC Document](https://github.com/aws-amplify/amplify-cli/issues/7546)
NA
- Manual testing
- yarn test passed
=> Category graphql/searchable sort multiple fields

packages/amplify-cli/src/attach-backend.ts
=> fix: show friendly error message when pull fails with EPERM

packages/amplify-console-integration-tests/src/consoleHosting/consoleHosting.ts
=> test(amplify-console-integration-tests): update the addEnvironment Function

packages/amplify-category-geo/src/commands/geo/add.ts, packages/amplify-category-geo/src/commands/geo/console.ts, packages/amplify-category-geo/src/commands/geo/remove.ts, packages/amplify-category-geo/src/commands/geo/update.ts, packages/amplify-category-geo/src/service-utils/constants.ts
Adds a preview banner to Geo workflows.
using JS sample app
=> fix(amplify-category-geo): add preview banner

packages/amplify-category-geo/src/__tests__/commands/geo/add.test.ts, packages/amplify-category-geo/src/__tests__/commands/geo/remove.test.ts, packages/amplify-category-geo/src/__tests__/commands/geo/update.test.ts, packages/amplify-category-geo/src/commands/geo/add.ts, packages/amplify-category-geo/src/commands/geo/console.ts, packages/amplify-category-geo/src/commands/geo/remove.ts, packages/amplify-category-geo/src/commands/geo/update.ts, packages/amplify-category-geo/src/service-utils/constants.ts
add preview banner for geo walkthroughs
unit tests and sample js app
=> Amplify geo staging

packages/amplify-e2e-core/src/categories/lambda-function.ts, packages/amplify-e2e-tests/src/schema-api-directives/common.ts, packages/amplify-e2e-tests/src/schema-api-directives/index.ts, packages/amplify-e2e-tests/src/schema-api-directives/tests/auth-customClaims.ts, packages/amplify-e2e-tests/src/schema-api-directives/tests/auth-fieldLevelAuth8.ts
- update function for auth schema e2e
- LayerOptions type update
- fix typos
=> test: update lambda function for auth schema tests

packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/cloudformation-templates/CreateAuthChallenge.json.ejs, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CustomMessage/cloudformation-templates/CustomMessage.json.ejs, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/DefineAuthChallenge/cloudformation-templates/DefineAuthChallenge.json.ejs, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostAuthentication/cloudformation-templates/PostAuthentication.json.ejs, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/cloudformation-templates/PostConfirmation.json.ejs, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreAuthentication/cloudformation-templates/PreAuthentication.json.ejs, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreSignup/cloudformation-templates/PreSignup.json.ejs, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreTokenGeneration/cloudformation-templates/PreTokenGeneration.json.ejs, packages/amplify-category-auth/provider-utils/awscloudformation/triggers/VerifyAuthChallengeResponse/cloudformation-templates/VerifyAuthChallengeResponse.json.ejs
“Delimited” was misspelled in comments generated in relation to Cognito triggers.
=> Fix typos in Cognito triggers

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/resource-status.test.ts, packages/amplify-cli/src/extensions/amplify-helpers/resource-status.ts
=> test(cli): add test for resource-status extensions

package.json, packages/amplify-graphiql-explorer/package.json, yarn.lock
Reverts aws-amplify/amplify-cli#7670
The original pull request is introducing build errors. The build errors need to be resolved in the local
=> Revert "chore: upgrade yarn packages recommended by dependabot"

.circleci/config.base.yml, .circleci/config.yml, packages/amplify-console-integration-tests/src/profile-helper.ts, packages/amplify-e2e-core/src/index.ts, packages/amplify-e2e-core/src/init/initProjectHelper.ts, packages/amplify-e2e-core/src/utils/envVars.ts, packages/amplify-e2e-core/src/utils/pinpoint.ts, packages/amplify-e2e-tests/sample.env, packages/amplify-e2e-tests/src/__tests__/import_auth_1.test.ts, packages/amplify-e2e-tests/src/__tests__/init.test.ts, packages/amplify-e2e-tests/src/aws-matchers/iamMatcher.ts, packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts, packages/amplify-e2e-tests/src/configure_tests.ts, packages/amplify-e2e-tests/src/init-special-cases/index.ts, packages/amplify-e2e-tests/src/schema-api-directives/authHelper.ts, packages/amplify-e2e-tests/src/schema-api-directives/tests/predictions-usage.ts, packages/amplify-migration-tests/sample.env, packages/amplify-migration-tests/src/configure_tests.ts, packages/amplify-provider-awscloudformation/src/configuration-manager.ts, packages/amplify-provider-awscloudformation/src/setup-new-user.js, packages/amplify-util-mock/src/utils/dynamo-db/index.ts, packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthModelAuthTransformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/NonModelAuthFunction.e2e.test.ts
Reverts aws-amplify/amplify-cli#7759
public repo is now created
=> Revert "Revert "ci: add support for e2e token rotation""

.circleci/publish.sh
It's pretty superficial, but I noticed this typo and figured I'd fix it instead of pretending I didn't see it :P 
=> build: fix typo in publish script

packages/amplify-provider-awscloudformation/src/system-config-manager.ts
Fixed typo in /amplify-provider-aws-cloudformation/src/system-config-manager.ts
=> chore: fixed typo

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/environmentVariablesHelper.ts
=> fix: correct behavior of --yes on push when missing env var

packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
This commit updates `@model` in GraphQL Transformer v2 to create the DynamoDB related CFN parameters and conditions.
Manual testing.
cc: @lazpavel since you're currently working on the model v2 tests.
=> fix: add DDB params to model v2

packages/amplify-e2e-tests/src/__tests__/api_1.test.ts, packages/amplify-e2e-tests/src/__tests__/function_6.test.ts
- add no change force push e2e checks on functions and api.
- ran e2e tests
=> test(amplify-e2e-tests): add no change force push e2e

.eslintrc.js
Fix lint errors from https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/1772/workflows/1b90d7dd-3364-4bc1-8247-1648af87c1b5/jobs/18981
=> fix: lint ignore

packages/amplify-prompts/package.json
=> test: force chalk colors in test in CCI

packages/amplify-e2e-tests/src/__tests__/api_1.test.ts
=> test(amplify-e2e-tests): fix casing for api name

packages/amplify-e2e-tests/src/__tests__/container-hosting.test.ts
Reverts aws-amplify/amplify-cli#7889
reason failing Tests: 
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/1794/workflows/94ce6c83-7231-41dd-9db8-b91a1d269de0/jobs/19210
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/1794/workflows/94ce6c83-7231-41dd-9db8-b91a1d269de0/jobs/19212
=> Revert "fix(container-hosting): e2e test fix"

packages/amplify-graphql-index-transformer/package.json, packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap, packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap, packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-index-transformer.test.ts, packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-primary-key-transformer.test.ts, packages/amplify-graphql-index-transformer/src/graphql-index-transformer.ts, packages/amplify-graphql-index-transformer/src/index.ts, packages/amplify-graphql-index-transformer/src/resolvers.ts, packages/amplify-graphql-index-transformer/src/schema.ts, packages/amplify-graphql-index-transformer/src/types.ts, packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts, packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts, packages/amplify-graphql-model-transformer/src/graphql-types/common.ts, packages/amplify-graphql-model-transformer/src/graphql-types/mutation.ts, packages/amplify-graphql-model-transformer/src/index.ts, packages/amplify-graphql-model-transformer/src/resolvers/mutation.ts, packages/amplify-graphql-model-transformer/src/resolvers/query.ts, packages/amplify-graphql-model-transformer/src/wrappers/object-definition-wrapper.ts, packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.tests.ts.snap, packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts, packages/graphql-transformers-e2e-tests/package.json, packages/graphql-transformers-e2e-tests/src/__tests__/IndexTransformer.e2e.test.ts, yarn.lock
This PR adds a new `@index` directive to the GraphQL Transformer v2. It also ports the `@key` E2E tests to v2. It also includes the commit from #7879 which is a bug fix needed to get the test suite passing.
Manual, unit, and E2E testing.
=> feat: add @index directive

packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/amplify-meta-updaters.ts, packages/amplify-e2e-tests/src/__tests__/auth_6.test.ts, packages/amplify-frontend-javascript/lib/frontend-config-creator.js, yarn.lock
- Changed label from loginMechanism(singular) to loginMechanisms(plural)
- See discussion [here](https://github.com/aws-amplify/amplify-cli/pull/7807/files#diff-6537e13815abae5d11be19e0e9fd3153a3e58b552955b29d5164f5cb4cdf94cfR37)
- local manual testing
- updated e2e test
=> chore(amplify-category-auth): updated login mechanisms label

packages/amplify-category-geo/src/__tests__/__snapshots__/index.test.ts.snap, packages/amplify-category-geo/src/__tests__/index.test.ts, packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/mapStack.test.ts.snap, packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/placeIndexStack.test.ts.snap, packages/amplify-category-geo/src/__tests__/service-utils/resourceUtils.test.ts, packages/amplify-category-geo/src/__tests__/service-walkthroughs/mapWalkthrough.test.ts, packages/amplify-category-geo/src/__tests__/service-walkthroughs/placeIndexWalkthrough.test.ts, packages/amplify-category-geo/src/commands/geo/add.ts, packages/amplify-category-geo/src/commands/geo/remove.ts, packages/amplify-category-geo/src/commands/geo/update.ts, packages/amplify-category-geo/src/index.ts, packages/amplify-category-geo/src/service-stacks/mapStack.ts, packages/amplify-category-geo/src/service-stacks/placeIndexStack.ts, packages/amplify-category-geo/src/service-utils/mapUtils.ts, packages/amplify-category-geo/src/service-utils/placeIndexUtils.ts, packages/amplify-category-geo/src/service-utils/resourceUtils.ts, packages/amplify-category-geo/src/service-walkthroughs/mapWalkthrough.ts, packages/amplify-category-geo/src/service-walkthroughs/placeIndexWalkthrough.ts
- Implement the `getPermissionPolicies` method for Geo plugin to grant requested permissions for Maps/Search
- Changing the `isDefault` property for a Geo resource should reflect in `amplify status` and also get updated in front-end configs post `amplify push`
- Throw useful error if geo plugin commands are used before `amplify init`
- Check if Geo resource name already exists in `add` workflow to re-prompt for a different name
unit tests are added/modifed
=> Amplify geo preview feedback items

packages/amplify-category-geo/src/__tests__/__snapshots__/index.test.ts.snap, packages/amplify-category-geo/src/__tests__/index.test.ts, packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/mapStack.test.ts.snap, packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/placeIndexStack.test.ts.snap, packages/amplify-category-geo/src/__tests__/service-utils/resourceUtils.test.ts, packages/amplify-category-geo/src/__tests__/service-walkthroughs/mapWalkthrough.test.ts, packages/amplify-category-geo/src/__tests__/service-walkthroughs/placeIndexWalkthrough.test.ts, packages/amplify-category-geo/src/commands/geo/add.ts, packages/amplify-category-geo/src/commands/geo/remove.ts, packages/amplify-category-geo/src/commands/geo/update.ts, packages/amplify-category-geo/src/index.ts, packages/amplify-category-geo/src/service-stacks/mapStack.ts, packages/amplify-category-geo/src/service-stacks/placeIndexStack.ts, packages/amplify-category-geo/src/service-utils/mapUtils.ts, packages/amplify-category-geo/src/service-utils/placeIndexUtils.ts, packages/amplify-category-geo/src/service-utils/resourceUtils.ts, packages/amplify-category-geo/src/service-walkthroughs/mapWalkthrough.ts, packages/amplify-category-geo/src/service-walkthroughs/placeIndexWalkthrough.ts
Release: update aws-exports upon default geo resource change, implement getPermissionPolicies
unit tests, JS sample app
=> Amplify geo preview feedback items (#7891)

packages/amplify-cli/package.json
=> chore: add uuid in amplify-cli deps

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, yarn.lock
Add missing CDK dependency to CLI package
=> chore: add missing dependency, fix cdk version

.github/ISSUE_TEMPLATE/1.bug_report.yaml
Update repro steps description
=> chore: update bug template

packages/amplify-e2e-tests/package.json, packages/amplify-e2e-tests/src/schema-api-directives/authHelper.ts, packages/amplify-e2e-tests/src/schema-api-directives/index.ts, packages/amplify-util-mock/package.json, packages/amplify-util-mock/src/__e2e__/connections-with-auth-tests.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/key-with-auth.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/model-auth-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/multi-auth-model-auth-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/per-field-auth-tests.e2e.test.ts, packages/amplify-util-mock/src/__e2e__/subscriptions-with-auth.e2e.test.ts, packages/graphql-transformers-e2e-tests/package.json, packages/graphql-transformers-e2e-tests/src/__tests__/ConnectionsWithAuthTests.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/KeyWithAuth.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/ModelAuthTransformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthModelAuthTransformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/MutationCondition.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/NewConnectionWithAuth.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/NonModelAuthFunction.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/PerFieldAuthTests.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/SearchableWithAuthTests.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthTest.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/cognitoUtils.ts, packages/graphql-transformers-e2e-tests/src/setupUserPool.ts, yarn.lock
=> test: update dependencies for schema e2e tests

packages/amplify-e2e-tests/src/schema-api-directives/index.ts
Fix e2e test failure: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/2064/workflows/6533d9b8-6bbb-4009-af66-f11b24795e1f/jobs/23001/steps
Ran e2e locally and it passed.
=> test: add ws back for subscriptions

packages/amplify-cli/__mocks__/invalid-plugin.js, packages/amplify-cli/__mocks__/non-event-handlers-plugin.js, packages/amplify-cli/__mocks__/valid-plugin.js, packages/amplify-cli/src/__tests__/plugin-helpers/verify-plugin.test.ts
Increase test coverage of amplify-cli/plugin-helpers.
=> test(cli): add test for verify-plugin plugin-helpers

packages/amplify-cli/src/__tests__/plugin-helpers/access-plugins-file.test.ts
Increase test coverage of amplify-cli/plugin-helpers.
=> test(cli): add test for access-plugins-file plugin-helpers

packages/amplify-category-api/package.json, packages/amplify-category-function/jest.config.js, packages/amplify-category-function/package.json, packages/amplify-category-hosting/package.json, packages/amplify-category-storage/package.json, packages/amplify-prompts/package.json, packages/graphql-relational-schema-transformer/package.json, packages/graphql-transformer-common/package.json
Fix jest config to be picked up by code cov
=> test: modified jest config for code cov to collect

packages/amplify-category-storage/package.json, packages/amplify-category-storage/tsconfig.json, packages/amplify-cli/package.json, packages/amplify-cli/tsconfig.json
Fix for missing package in `package.json` introduced in https://github.com/aws-amplify/amplify-cli/commit/45303a327567ab658345b06d01008fbb0184e6ae
`yarn test` passes
=> fix: add amplify-prompts dependency to package.json's

.circleci/config.base.yml, .circleci/config.yml
- update cypress base container image
- ran cci integ tests on fork
=> chore: update cypress container for integration tests

packages/amplify-e2e-core/src/categories/geo.ts, packages/amplify-e2e-core/src/utils/index.ts, packages/amplify-e2e-tests/src/__tests__/geo-add.test.ts, packages/amplify-e2e-tests/src/__tests__/geo-remove.test.ts, packages/amplify-e2e-tests/src/__tests__/geo-update.test.ts
Fix the e2e tests for Geo category plugin based on latest changes.
Includes Maps and Search functionality.
Ran the e2e tests locally.
=> Update Amplify geo e2e tests

package.json, packages/amplify-category-api/package.json, packages/amplify-category-function/package.json, packages/amplify-category-interactions/package.json, packages/amplify-category-storage/package.json, packages/amplify-cli-core/package.json, packages/amplify-util-headless-input/package.json, yarn.lock
A number of packages reference dependencies that are not listed in their respected package.json. This PR fixes some of them, but I did not check every package.
`yarn test`
=> chore: add missing dependencies to relevant package.json files

packages/amplify-category-api/resources/awscloudformation/container-templates/dockercompose-rest-express/express/package.json, packages/amplify-e2e-tests/package.json, packages/amplify-util-mock/package.json, packages/graphql-transformers-e2e-tests/package.json, yarn.lock
Ensure axios is bumped in all places, update aws-amplify version
This PR is aimed at getting merged in favor of https://github.com/aws-amplify/amplify-cli/pull/8128
`yarn test`
=> chore: update dependencies to bump axios everywhere

packages/amplify-cli/src/pre-deployment-pull.ts, packages/amplify-provider-awscloudformation/src/admin-login.ts, packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts
This PR adds environment variables that can be used for internal development against beta/gamma environments
I can set these environment variables to use non-prod backends.
=> chore(amplify-provider-awscloudformation): add env vars for configuring development against beta/gamma

how-to-write-a-transformer.md
Update the broken link in the `how-to-write-a-transformer.md` file.
=> Update link in how-to-write-a-transformer.md

packages/amplify-graphql-model-transformer/src/resolvers/subscriptions.ts
Fix typo in template generator
Used the transformer to generate resolvers locally.
=> fix(graphql-model-transformer): fix typo in print block

packages/amplify-cli/src/display-banner-messages.ts
https://github.com/aws-amplify/amplify-cli/issues/8147
=> fix: incorrect documentation link

packages/amplify-category-geo/package.json, packages/amplify-category-geo/src/__tests__/service-walkthroughs/mapWalkthrough.test.ts, packages/amplify-category-geo/src/__tests__/service-walkthroughs/placeIndexWalkthrough.test.ts, packages/amplify-category-geo/src/commands/geo/add.ts, packages/amplify-category-geo/src/commands/geo/console.ts, packages/amplify-category-geo/src/commands/geo/help.ts, packages/amplify-category-geo/src/commands/geo/remove.ts, packages/amplify-category-geo/src/commands/geo/update.ts, packages/amplify-category-geo/src/index.ts, packages/amplify-category-geo/src/provider-controllers/index.ts, packages/amplify-category-geo/src/provider-controllers/map.ts, packages/amplify-category-geo/src/provider-controllers/placeIndex.ts, packages/amplify-category-geo/src/service-utils/mapParams.ts, packages/amplify-category-geo/src/service-utils/resourceParams.ts, packages/amplify-category-geo/src/service-utils/resourceUtils.ts, packages/amplify-category-geo/src/service-walkthroughs/mapWalkthrough.ts, packages/amplify-category-geo/src/service-walkthroughs/placeIndexWalkthrough.ts, packages/amplify-category-geo/src/service-walkthroughs/removeWalkthrough.ts, packages/amplify-category-geo/src/service-walkthroughs/resourceWalkthrough.ts, packages/amplify-e2e-core/src/categories/geo.ts, packages/amplify-e2e-tests/src/__tests__/geo-add.test.ts, packages/amplify-e2e-tests/src/__tests__/geo-remove.test.ts, packages/amplify-e2e-tests/src/__tests__/geo-update.test.ts, packages/amplify-frontend-javascript/lib/frontend-config-creator.js
- Remove deprecated `context.print` and use `amplify-prompts` package for console outputs.
- Update Pricing Plan Walkthrough to include a clickable "learn more" option, also update wordings
- Correct the naming of Data provider to `HERE` in place index walkthrough
- Change the plugin name for JS frontend to `amazon_location_service`
https://github.com/aws-amplify/amplify-cli/issues/8096
unit tests and e2e tests are modified and locally run
=> fix(amplify-category-geo): pricing plan, data provider,  JS plugin name updates

packages/amplify-graphql-auth-transformer/src/accesscontrol/acm.ts, packages/amplify-graphql-auth-transformer/src/index.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/utils.ts
=> add command to show access control, admin ui fix, and fix field auth evaluation

packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts, packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts
=> fix: admin ui app state check and auth transformer index resolver name

packages/amplify-graphql-auth-transformer/src/resolvers/helpers.ts, packages/amplify-graphql-auth-transformer/src/resolvers/mutation.create.ts, packages/amplify-graphql-auth-transformer/src/resolvers/mutation.update.ts
=> fix: has auth typo and qref on field conditions for private rule

packages/amplify-cli-core/package.json, packages/amplify-provider-awscloudformation/package.json, packages/graphql-transformers-e2e-tests/resources/jsonServer/package.json, packages/graphql-transformers-e2e-tests/resources/jsonServer/yarn.lock, yarn.lock
=> build: update proxy agent

banner-message.json
This PR contains a placeholder empty message that we can update later when we figure out what the message should be
=> feat: add placeholder alias attributes warning message

packages/amplify-category-auth/src/commands/auth/remove.js
A rogue log line was accidentally merged to master
=> chore: remove rogue log line

packages/amplify-e2e-tests/src/__tests__/auth_6.test.ts
=> test: updated snapshot for auth zero config test

packages/amplify-category-auth/src/provider-utils/supported-services.ts
=> fix: added warning for usernameAttributes

packages/amplify-category-auth/src/commands/auth/remove.js
=> fix(amplify-category-auth): check for undefined aliasAttributes

banner-message.json
The messaging for amplify remove auth has been determined
=> Alias attribute warning

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/field-auth-argument.test.ts.snap, packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts, packages/amplify-graphql-auth-transformer/src/resolvers/helpers.ts, packages/amplify-graphql-auth-transformer/src/resolvers/mutation.create.ts, packages/amplify-graphql-auth-transformer/src/resolvers/mutation.delete.ts, packages/amplify-graphql-auth-transformer/src/resolvers/mutation.update.ts, packages/amplify-graphql-auth-transformer/src/resolvers/query.ts, packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap, packages/amplify-graphql-relational-transformer/src/resolvers.ts
=> fix: iam resolver check and relational payload

packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts
- provide correct directive definitions based on transformer version
- ran `yarn test`
- manual testing 
=> fix(graphql-model-transformer): provide correct directive definitions based on transformer version

.github/PULL_REQUEST_TEMPLATE.md
Adds another checklist item to the PR checklist for permissions around new SDK calls or CloudFormation actions
=> chore: add item to PR checklist

packages/amplify-graphql-relational-transformer/README.md, packages/amplify-graphql-relational-transformer/package.json, packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap, packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-many-to-many-transformer.test.ts, packages/amplify-graphql-relational-transformer/src/graphql-many-to-many-transformer.ts, packages/amplify-graphql-relational-transformer/src/index.ts, packages/amplify-graphql-relational-transformer/src/schema.ts, packages/amplify-graphql-relational-transformer/src/types.ts, packages/amplify-graphql-relational-transformer/src/utils.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts, packages/graphql-transformers-e2e-tests/src/__tests__/RelationalTransformers.e2e.test.ts
This PR adds a new `@manyToMany` directive.
Note to simplify reviewing this, the first six of the seven commits are #8035, so only the last commit needs reviewed here.
Manual, unit, and E2E testing.
=> feat: add @manytomany directive

packages/amplify-category-geo/package.json
update `aws-cdk` dependency to `~1.119.0`
unit testing
=> chore(amplify-category-geo): update cdk version

packages/amplify-category-geo/package.json, packages/amplify-cli/package.json, packages/amplify-frontend-android/lib/amplify-config-helper.js, packages/amplify-frontend-android/tests/__snapshots__/amplify-config-helper.test.js.snap, packages/amplify-frontend-android/tests/amplify-config-helper.test.js, packages/amplify-frontend-ios/lib/amplify-config-helper.js, packages/amplify-frontend-ios/tests/__snapshots__/amplify-config-helper.test.js.snap, packages/amplify-frontend-ios/tests/amplify-config-helper.test.js
Adds Geo related config for Maps and Search for iOS, Android frontends. 
changes reviewed here - https://github.com/aws-amplify/amplify-cli/pull/8031
=> Add geo config for Maps and Search - iOS, Android frontends

.circleci/config.yml, packages/amplify-category-auth/src/__tests__/commands/import.headless.test.ts, packages/amplify-category-auth/src/__tests__/commands/remove.test.js, packages/amplify-category-auth/src/commands/auth/remove.js, packages/amplify-category-auth/src/index.js, packages/amplify-category-geo/package.json, yarn.lock
=> fix: add missing await, fix import paths

packages/amplify-category-geo/package.json, packages/amplify-category-geo/src/service-walkthroughs/mapWalkthrough.ts, packages/amplify-category-geo/src/service-walkthroughs/placeIndexWalkthrough.ts
update dependency on `uuid`.
unit testing and iOS sample app. 
=> chore(amplify-category-geo): update uuid version

packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts, packages/amplify-graphql-auth-transformer/src/utils/index.ts, packages/amplify-graphql-auth-transformer/src/utils/schema.ts
=> fix: add datastore query in config for auth

packages/amplify-graphql-auth-transformer/src/resolvers/query.ts
=> fix: auth filter expression

packages/amplify-provider-awscloudformation/src/attach-backend.js
Adds check to print a helpful message for when there is an error fetching an s3 object
ref #8233
=> fix: add pull check for missing s3 objects, ref #8233

packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformerV2.e2e.test.ts
Fix for flaky searchable v2 E2E test.
=> fix(Searchable): confirm ES data propagate

packages/amplify-cli/src/extensions/amplify-helpers/get-api-key-config.ts, packages/amplify-graphql-auth-transformer/src/__tests__/amplify-admin-auth.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/field-auth-argument.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/group-auth.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/multi-auth.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/owner-auth.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/searchable-auth.test.ts, packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts, packages/amplify-graphql-auth-transformer/src/resolvers/helpers.ts, packages/amplify-graphql-auth-transformer/src/utils/constants.ts, packages/amplify-graphql-auth-transformer/src/utils/definitions.ts, packages/amplify-graphql-auth-transformer/src/utils/index.ts, packages/amplify-graphql-function-transformer/src/__tests__/__snapshots__/amplify-graphql-function-transformer.test.ts.snap, packages/amplify-graphql-function-transformer/src/__tests__/amplify-graphql-function-transformer.test.ts, packages/amplify-graphql-function-transformer/src/graphql-function-transformer.ts, packages/amplify-graphql-predictions-transformer/src/graphql-predictions-transformer.ts, packages/amplify-graphql-transformer-core/src/config/transformer-config.ts, packages/amplify-graphql-transformer-core/src/index.ts, packages/amplify-graphql-transformer-core/src/transformation/transform.ts, packages/amplify-graphql-transformer-core/src/transformation/validation.ts, packages/amplify-graphql-transformer-core/src/transformer-context/index.ts, packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts, packages/amplify-graphql-transformer-core/src/utils/authType.ts, packages/amplify-graphql-transformer-core/src/utils/index.ts, packages/amplify-graphql-transformer-interfaces/src/graphql-api-provider.ts, packages/amplify-graphql-transformer-interfaces/src/index.ts, packages/amplify-graphql-transformer-interfaces/src/transformer-context/transformer-context-provider.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts
=> fix: update iam auth to include roles in before template

packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap, packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-primary-key-transformer.test.ts.snap, packages/amplify-provider-awscloudformation/src/__tests__/utils/sandbox-mode-helpers.test.ts, packages/amplify-provider-awscloudformation/src/utils/sandbox-mode-helpers.ts
=> fix(amplify-provider-awscloudformation): invoke api function from invoker plugin

packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts, packages/amplify-graphql-transformer-core/src/transformation/transform.ts, packages/amplify-provider-awscloudformation/src/__tests__/utils/sandbox-mode-helpers.test.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts, packages/amplify-provider-awscloudformation/src/utils/sandbox-mode-helpers.ts
=> fix(amplify-provider-awscloudformation): remove sandbox mode directive from schema before transform

.circleci/config.base.yml, .circleci/config.yml
fix cci config to ensure deployment depends on node tests finishing
=> test: fix cci pipeline flow

.circleci/config.base.yml, .circleci/config.yml
=> test: remove aws cli win install step

packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts
=> fix: logic to display searchable instance warning

packages/amplify-cli-overrides-helper/src/index.ts, packages/amplify-provider-awscloudformation/src/aws-utils/aws-ssm.ts
Add rootStack types to override helper package
-Manually tested 
=> Add rootStack types to override helper package

.circleci/config.base.yml, .circleci/config.yml
This test timeout was reduced but it is now timing out in CCI: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/2834/workflows/16c14f26-ee36-4442-a0ca-417d9982664a/jobs/30721
=> test: revert test timeout change

.circleci/config.base.yml, .circleci/config.yml, scripts/split-e2e-tests.ts
Windows tests are failing right now due to rate limits on us-east-1. Skipping for now.
=> Skip rate limited windows tests

.circleci/config.base.yml, .circleci/config.yml, .circleci/local_publish_helpers.sh
After discussing more with the team, we have determined it is worth it to add automatic retries. This is a two-way door of course, if we don't like it we can always go back to 1 attempt.
=> ci: add automatic retry of failed tasks

.circleci/local_publish_helpers.sh
Retry logic had a bug where the exit code of the test run was not being passed back to the retry logic
=> ci: fix retry function

.circleci/config.base.yml, .circleci/config.yml
Fix incorrect context name for cleanup context. Also fixed post-step cleanup config
=> ci: fix cleanup script context

packages/amplify-provider-awscloudformation/src/__tests__/graphql-push-schema-checks.test.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts, packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts
- fix for open search instance type check
- manual tests
- unit tests added
=> fix(graphql-model-transformer): fix open search instance check for v1 and v2 transformers

packages/amplify-appsync-simulator/src/index.ts, packages/amplify-appsync-simulator/src/utils/auth-helpers/helpers.ts, packages/amplify-appsync-simulator/src/utils/graphql-runner/index.ts, packages/amplify-appsync-simulator/src/utils/index.ts, packages/amplify-appsync-simulator/src/velocity/index.ts, packages/amplify-util-mock/package.json, packages/amplify-util-mock/src/__e2e__/utils/cognito-utils.ts, packages/amplify-util-mock/src/__tests__/graphql-vtl/model-auth.test.ts, packages/amplify-util-mock/src/velocity/index.ts
- expose the VTL Template in AppSync Simulator
- Using the VTL Template to run VTL unit tests against the generated resolvers by the GraphQL transformer
- local unit test
=> test: add vtl unit tests using the appsync simulator

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/owner-auth.test.ts.snap, packages/amplify-graphql-auth-transformer/src/__tests__/owner-auth.test.ts, packages/amplify-graphql-auth-transformer/src/resolvers/mutation.create.ts
=> fix: fix null check for implied owner check

packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts, packages/amplify-category-api/src/provider-utils/supported-services.ts
Minor GraphQL Api name and api key prompt changes.
- Manual test
- yarn test
=> fix(graphql): minor api prompt fixes

packages/graphql-transformers-e2e-tests/src/__tests__/AuthV2Transformer.e2e.test.ts
Adds more V2 Transformer tests to cover additional acceptance criteria.
Ran e2e suite locally, but it still needs to be run on CI.
=> test(graphql-auth-transformer): add more e2e tests for deny-by-default behavior

packages/graphql-transformers-e2e-tests/src/__tests__/FunctionTransformerTestsV2.e2e.test.ts
Add e2e test for v2 graphql function directive.
- E2E in local
=> add e2e for v2 function directive

packages/amplify-provider-awscloudformation/src/graphql-transformer/utils.ts, packages/graphql-transformers-e2e-tests/src/__tests__/FunctionTransformerTestsV2.e2e.test.ts
=> fix: function dep fix and auth transformer e2e fix

packages/amplify-category-auth/resources/auth-custom-resource/hostedUIProviderLambda.js, packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/__snapshots__/auth-stack-transform.test.ts.snap, packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts
- Enabled SMS config when phone_number is selected
- Fixed Bug in HostedUI Providers Custom Resource Lambda Code
- Tested Manually
=> fix: admin UI integ test fix

packages/amplify-graphql-transformer-migrator/package.json, packages/amplify-graphql-transformer-migrator/src/__tests__/migration/__snapshots__/migrate-tests.ts.snap, packages/amplify-graphql-transformer-migrator/src/__tests__/migration/migrate-tests.ts
This commit updates the existing gql v2 migrator unit tests to be a bit simpler and more DRY. It also adds additional unit tests.
There will be more PRs to follow, but this should allow others to start adding tests as well.
Ran the unit tests added here.
=> test: update and add more gql v2 migrator unit tests

packages/amplify-e2e-tests/src/__tests__/transformer-migrations/predictions-migration.test.ts
- v1 to v2 migration predictions e2e test
=> test(graphql-predictions-transformer): predictions directive migration v1 to v2 test fix

packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts, packages/amplify-e2e-core/src/categories/api.ts
Label change for AppSync Lambda Authorizer Lambda
- e2e in local
- Manual test
=> appsync lambda auth label fix

packages/amplify-provider-awscloudformation/src/graphql-transformer/utils.ts
- removed unnecessary message
- https://app.asana.com/0/1174852957705151/1201298214780989/f
=> chore(amplify-provider-awscloudformation): removed unnecessary log message on get admin roles

packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts
=> fix: remove duplicate entry from admin ui backend mapping

packages/amplify-category-auth/resources/overrides-resource/package.json, packages/amplify-category-storage/resources/overrides-resource/DynamoDB/package.json, packages/amplify-category-storage/resources/overrides-resource/S3/package.json, packages/amplify-provider-awscloudformation/resources/overrides-resource/package.json
update package dependencies in overrides skeleton to match new tagged release
=> chore: update skeleton package json override dependencies

packages/amplify-graphql-migration-tests/src/__tests__/graphql-version-migration.test.ts, packages/amplify-graphql-migration-tests/src/migrate-schema-wrapper.ts, packages/amplify-graphql-migration-tests/src/test-case-registry.ts, packages/amplify-graphql-migration-tests/src/test-case-types.ts, packages/amplify-graphql-migration-tests/src/v1-transformer-provider.ts, packages/amplify-graphql-migration-tests/src/v2-transformer-provider.ts
Add more test schemas to migration test suite
=> test: add more test schemas

packages/amplify-cli-core/src/feature-flags/featureFlags.ts, packages/amplify-graphql-transformer-migrator/tsconfig.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts, packages/amplify-provider-awscloudformation/tsconfig.json
Allows the migrator to be triggered by transformGraphQLSchema when the V2 transformer is enabled
Running locally
=> Enable graphql migrator

scripts/split-e2e-tests.ts
=> ci: exclude prediction migration e2e on windows

packages/amplify-provider-awscloudformation/src/graphql-transformer/utils.ts
=> fix: add a check if the idp id exists

packages/amplify-cli-core/src/feature-flags/featureFlags.ts
Disable schema migration by default so it doesn't break existing flow
=> Do not offer schema migration by default

packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts, packages/amplify-e2e-core/src/categories/api.ts
=> fix: capitalization for filter, e2e test

packages/amplify-e2e-tests/schemas/transformer_migration/searchable-v1.graphql, packages/amplify-e2e-tests/schemas/transformer_migration/searchable-v2.graphql, packages/amplify-e2e-tests/src/__tests__/transformer-migrations/searchable-migration.test.ts, packages/amplify-graphql-auth-transformer/src/accesscontrol/acm.ts, packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts, packages/amplify-graphql-searchable-transformer/src/cdk/create-cfnParameters.ts, packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts
Searchable migration fix and e2e test.
- yarn test
- e2e test in local
=> searchable fix and migration e2e tests

packages/amplify-cli-core/src/state-manager/pathManager.ts, packages/amplify-cli-core/src/utils/validate-path.ts, packages/amplify-cli/src/commands/export.ts, packages/amplify-provider-awscloudformation/src/export-resources.ts
=> fix: test feedback fixes

packages/amplify-category-storage/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.test.ts
=> (fix) storage unit-tests for prompter function change

packages/graphql-transformers-e2e-tests/resources/jsonServer/src/index.ts
=> test: update json mock lambda version to Node 14

packages/amplify-category-api/src/index.ts, packages/amplify-category-auth/resources/schemas/awsCognito/CognitoCLIInputs.schema.json, packages/amplify-category-auth/src/index.js, packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthrough-types/awsCognito-user-input-types.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/transform-user-pool-group.js, packages/amplify-cli/src/extensions/amplify-helpers/resource-status.ts, packages/amplify-e2e-tests/src/__tests__/auth_1.test.ts, packages/amplify-e2e-tests/src/__tests__/interactions.test.ts
- interactions/ notification bug fix
- removes root stack changes prompt
- ran interactions/notifications e2e
- ran auth-4-e2e.tests.ts
=> fix: asana bug fixes

Dockerfile
=> ci: use npm v7 in the test images

packages/amplify-category-auth/resources/overrides-resource/package.json, packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/user-pool-group-stack-transform.ts, packages/amplify-category-storage/resources/overrides-resource/DynamoDB/package.json, packages/amplify-category-storage/resources/overrides-resource/S3/package.json, packages/amplify-cli/src/extensions/amplify-helpers/resource-status.ts, packages/amplify-cli/src/extensions/amplify-helpers/root-stack-status.ts, packages/amplify-provider-awscloudformation/resources/overrides-resource/package.json, packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-transform.ts
- changed root stack hashing
- fixed hooks and hosting e2e tests
=> Root stack fix

packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-belongs-to-transformer.test.ts, packages/amplify-graphql-relational-transformer/src/schema.ts
=> fix(graphql-relational-transformer): fix belongs to e2e test

packages/amplify-category-storage/Readme.md, packages/amplify-category-storage/src/commands/storage.ts, packages/amplify-e2e-core/src/categories/storage.ts, packages/amplify-e2e-tests/src/__tests__/storage-1.test.ts, packages/amplify-e2e-tests/src/__tests__/storage-5.test.ts
1. (fix) storage-5 build-overrides hang fix
2. (fix) override DDB StreamSpecification fails because of missing CFN
3. (fix) timeout adding lambda in add lambda when lambda exists
4. (fix) storage_migration_update hangs (partial)
5. (fix) help missing for storage overrides
=> Ext overrides4 storage e2e

packages/amplify-e2e-core/src/categories/storage.ts, packages/amplify-e2e-core/src/utils/headless.ts, packages/amplify-e2e-tests/src/__tests__/import_dynamodb_1.test.ts, packages/amplify-e2e-tests/src/__tests__/import_dynamodb_2.test.ts, packages/amplify-e2e-tests/src/__tests__/storage-5.test.ts, packages/amplify-e2e-tests/src/import-helpers/expects.ts, packages/amplify-e2e-tests/tsconfig.tests.json
=> test: update ignore pattern for build-tests, fix import ddb tests

packages/amplify-migration-tests/src/__tests__/migration_tests/overrides/init-migration.test.ts
=> test(amplify-migration-tests): path fix for override-root file

packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap, packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts
=> Model vnext unit test update

packages/amplify-e2e-core/src/categories/storage.ts
=> test: fix storage add walkthrough hanging in integ test

packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts
=> fix(amplify-category-auth): fixed the openId Connect provider auth

packages/amplify-e2e-core/src/categories/storage.ts, packages/amplify-e2e-core/src/utils/nexpect.ts, packages/amplify-e2e-tests/src/__tests__/import_auth_2.test.ts, packages/amplify-e2e-tests/src/__tests__/migration/node.function.test.ts
=> fix: fixed import_auth test

packages/amplify-category-storage/src/provider-utils/awscloudformation/import/import-dynamodb.ts, packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/dynamoDB-input-state.ts, packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.ts, packages/amplify-e2e-tests/src/__tests__/import_dynamodb_2.test.ts
=> fix: amplify meta output for imported ddb, type fixes

packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-sms-workflow-helper.ts
=> (fix) amplify status crashes when auth is legacy

packages/amplify-category-auth/CHANGELOG.md, packages/amplify-e2e-tests/src/__tests__/hosting.test.ts
- added auth chanelog
- hosting e2e fix
=> fix: added changelog and hosting e2e fix

packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-sms-workflow-helper.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/check-for-auth-migration.ts, packages/amplify-category-predictions/provider-utils/awscloudformation/prediction-category-walkthroughs/identify-walkthrough.js, packages/amplify-category-storage/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.test.ts, packages/amplify-category-storage/src/commands/storage/override.ts, packages/amplify-category-storage/src/provider-utils/awscloudformation/import/import-dynamodb.ts, packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.ts, packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.ts, packages/amplify-cli-core/src/feature-flags/featureFlags.ts, packages/amplify-cli-core/src/overrides-manager/index.ts, packages/amplify-cli-core/src/overrides-manager/migration-message.ts, packages/amplify-cli/src/extensions/amplify-helpers/resource-status-data.ts, packages/amplify-e2e-core/src/categories/auth.ts, packages/amplify-e2e-tests/src/import-helpers/expects.ts, packages/amplify-migration-tests/src/__tests__/update_tests/storage_migration_update.test.ts, packages/amplify-provider-awscloudformation/src/commands/awscloudformation/override.ts, packages/amplify-provider-awscloudformation/src/initializer.ts, packages/amplify-provider-awscloudformation/src/override-manager/transform-resource.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts
=> fix: update migration msg, ddb import e2e, lgtm errors

.circleci/config.base.yml, packages/amplify-migration-tests/package.json
=> ci: migration test cleanup

packages/amplify-e2e-tests/src/__tests__/export-pull.test.ts
=> test(amplify-e2e-tests): reduce the scope of the export pull test

packages/amplify-migration-tests/src/__tests__/update_tests/auth_migration_update.test.ts
- updated update auth tests
- ran auth-update tests locally
=> fix: Auth update migration e2e fix

packages/amplify-e2e-tests/src/import-helpers/expects.ts
=> test: remove mapping

packages/amplify-migration-tests/package.json
=> fix: CI fix

packages/amplify-graphql-transformer-migrator/src/schema-migrator.ts, packages/amplify-provider-awscloudformation/src/display-helpful-urls.js
Updates migration docs placeholder with actual link
=> docs: update migration docs link

packages/amplify-e2e-tests/src/__tests__/resolvers.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/amplify-admin-auth.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/conflict-resolution.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/field-auth-argument.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/multi-auth.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/owner-auth.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/searchable-auth.test.ts, packages/amplify-graphql-function-transformer/src/__tests__/amplify-graphql-function-transformer.test.ts, packages/amplify-graphql-http-transformer/src/__tests__/amplify-graphql-http-transformer.test.ts, packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-index-transformer.test.ts, packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-primary-key-transformer.test.ts, packages/amplify-graphql-model-transformer/src/__tests__/__snapshots__/model-transformer.test.ts.snap, packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts, packages/amplify-graphql-predictions-transformer/src/graphql-predictions-transformer.ts, packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-transformer.test.ts, packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-many-to-many-transformer.test.ts, packages/amplify-graphql-relational-transformer/src/__tests__/relational-auth.test.ts, packages/amplify-graphql-searchable-transformer/src/__tests__/amplify-graphql-searchable-transformer.tests.ts, packages/amplify-graphql-transformer-core/src/cdk-compat/template-asset.ts, packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts, packages/amplify-provider-awscloudformation/src/__tests__/graphql-transformer/utils.test.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-config.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/utils.ts, packages/amplify-util-mock/src/__tests__/velocity/model-auth.test.ts, packages/amplify-util-mock/src/__tests__/velocity/multi-auth.test.ts, packages/amplify-util-mock/src/api/api.ts
Re-reverting https://github.com/aws-amplify/amplify-cli/pull/8729
=> Rename pipeline resolvers

packages/amplify-e2e-core/src/categories/storage.ts, packages/amplify-e2e-tests/src/__tests__/storage-1.test.ts, packages/amplify-migration-tests/src/__tests__/update_tests/storage_migration_update.test.ts
=> (fix) e2e storage update-migration test

packages/amplify-migration-tests/package.json
=> test(amplify-migration-tests): added passwithNoTests with all

packages/amplify-e2e-tests/src/__tests__/api_6.test.ts, packages/amplify-provider-awscloudformation/src/index.ts
Fixes a bad merge where the rebuild flag from `amplify rebuild api` was not plumbed through correctly
Ran rebuild api e2e test locally
=> fix: rebuild api bad merge

packages/amplify-category-custom/src/utils/dependency-management-utils.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts, yarn.lock
- include custom lambda trigger template in ignore
=> fix: glob fix for auth trigger template

packages/amplify-migration-tests/src/__tests__/migration_tests/overrides/auth-migration.test.ts, packages/amplify-migration-tests/src/__tests__/update_tests/auth_migration_update.test.ts
- added a version check on one migration test
=> chore: added version check for auth migration

packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/message-printer.ts
- fix auth  successful message
=> fix: auth message printer

packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-builder.ts, packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-transform.ts, packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-user-input-state.ts
=> fix: storage params

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/check-for-auth-migration.test.ts, packages/amplify-category-storage/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.test.ts
=> test(amplify-category-storage): s3 walkthrough unit test fixes

yarn.lock
=> chore: update yarn.lock with latest changes

packages/amplify-category-auth/src/provider-utils/awscloudformation/handlers/resource-handlers.ts, packages/amplify-provider-awscloudformation/src/__tests__/commands/override.test.ts
- moved trigger logic up before saving cli-inputs
- ran auth_4.test.ts (passed)
=> fix: updated resource update logic

packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-user-input-state.ts, packages/amplify-e2e-core/src/categories/storage.ts
=> fix: storage migration permissions

packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-user-input-state.ts
=> fix: lowercase filename for linux

packages/amplify-provider-awscloudformation/src/export-resources.ts
=> fix: export manifest path for the export path

packages/amplify-category-storage/src/commands/storage/override.ts
This PR introduces overrides and export. Overrides enables customers to
extend or modify their resource categories. Export enables them to export their backend
and use it in a CDK app.
BREAKING CHANGE: The breaking change is in the workflow of auth and storage. Auth and Storage
categories can be overriden
=> ci: breaking change empty commit

packages/amplify-category-auth/resources/schemas/awsCognito/CognitoCLIInputs.schema.json, packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthrough-types/awsCognito-user-input-types.ts
=> fix: allow both email and phone number type

packages/amplify-util-mock/src/storage/storage.ts
=> fix: amplify-mock with build folder

packages/amplify-category-predictions/commands/predictions/remove.js
=> fix(amplify-category-predictions): fix bad import and exit

packages/amplify-category-auth/resources/schemas/awsCognito/CognitoCLIInputs.schema.json, packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/__snapshots__/auth-stack-transform.test.ts.snap, packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/__snapshots__/user-pool-group-stack-transform.test.ts.snap, packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-user-pool-group-stack-builder.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthrough-types/awsCognito-user-input-types.ts
- added useenabledMfa flag in parameters.json
- fixes passwordPolicyLength type in CLIInputs schema
- fixes UserPool deletion and naming in Cognito and userPool group CFN
=> fix: mfa bug and changed password policy type as string or number

packages/amplify-provider-awscloudformation/src/export-resources.ts, packages/amplify-provider-awscloudformation/src/resource-package/resource-export.ts
=> docs(amplify-provider-awscloudformation): removed doc link

packages/amplify-cli-extensibility-helper/src/types/project/types.ts, packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/__snapshots__/root-stack-builder.test.ts.snap, packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/__snapshots__/root-stack-transform.test.ts.snap, packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/root-stack-builder.test.ts, packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-transform.ts
- suppress bucket name from root stack types
- Minor fixes in root stack template
=> fix: suppress deployment bucket type and root stack fixes

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/field-auth-argument.test.ts.snap, packages/amplify-graphql-auth-transformer/src/__tests__/field-auth-argument.test.ts, packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
=> fix: update error message for auth on non null fields

packages/amplify-provider-awscloudformation/resources/update-idp-roles-cfn.json, packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js
- changes UpdateIDP lambda function to get roles role information before deletion
=> fix: authrole issue

packages/graphql-transformers-e2e-tests/src/__tests__/BelongsToTransformerV2.e2e.test.ts
=> test(graphql-relational-transformer): fix for belongs to e2e test

packages/amplify-e2e-tests/schemas/transformer_migration/auth-model-v1.graphql, packages/amplify-e2e-tests/schemas/transformer_migration/auth-model-v2.graphql, packages/amplify-e2e-tests/src/__tests__/transformer-migrations/auth-migration.test.ts
Add e2e migration tests for v2 auth directive.
- e2e in local
=> test(graphql): add auth directive migration e2e tests

package.json, packages/amplify-cli/src/__tests__/commands/upgrade.pkg.test.ts, packages/amplify-cli/src/commands/upgrade.ts, yarn.lock
Fixes `amplify upgrade` which was failing due to zlib issues in pkg-fetch images. Upgrades to the latest version of pkg to pull in the fix. Also fixes a bug where the download progress bar sometimes consumed a chunk of the stream before gunzip was attached causing the stream to be corrupted. Minor refactor of the piping code to use promises and stream pipelines as well.
Manually tested. We don't have a great way to test the upgrade workflow at the moment, but it's on the backlog.
=> fix: upgrade to latest pkg to fix zlib issue

packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthV2Transformer.e2e.test.ts
=> test(graphql-transformers-e2e-tests): shorten gql schema for multi auth

packages/amplify-e2e-core/src/categories/lambda-function.ts
Adds Lambda Authorizer as a Node.js option for REST API setup.
=> Fix e2e test

packages/amplify-e2e-core/src/export/index.ts
=> test: fix export test

packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/trigger-file-uploader.js
=> fix: remove hardcoding for build/parameters.json file for auth resource

packages/amplify-provider-awscloudformation/src/build-override-enabled-resources.ts, packages/amplify-provider-awscloudformation/src/initialize-env.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts
=> fix: build overrides for headless push with new env init scneario

packages/amplify-cli/src/commands/console.ts, packages/amplify-provider-awscloudformation/src/amplify-service-manager.js, packages/amplify-provider-awscloudformation/src/amplify-service-migrate.js
This commit clarifies language with respect to the AWS Console vs Amplify Admin UI.
Ran `amplify init` and `amplify console`, saw the expected output.
=> chore: remove console verbiage from amplify init

packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts
=> fix: change default to string for the 'hostedUIProviderCreds' input param

packages/amplify-cli/src/commands/export.ts
=> docs: fix spelling

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/apigw-input-state.test.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/apigw-input-state.ts
=> fix: add migration step for REST APIs, add input state unit test

packages/amplify-category-api/package.json, packages/amplify-category-api/src/commands/api/migrate.ts, packages/amplify-category-api/src/commands/api/override.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/utils/check-appsync-api-migration.ts
=> fix: enable scoped packages and minor fixes 

packages/amplify-category-geo/src/supportedServices.ts
Correct the spelling for `Geofencing` capability
unit testing
=> Minor Spelling error correction

packages/amplify-category-auth/CHANGELOG.md, packages/amplify-category-auth/package.json, packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.test.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts, packages/amplify-cli/CHANGELOG.md, packages/amplify-cli/package.json
=> chore: merge master branch into apigw-ext

packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/index.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/utils/migrate-api-override-resource.ts
=> fix: rebase fixes and bugs

packages/amplify-graphql-migration-tests/src/test-case-registry.ts
Added an E2E test for migration of custom timestamps
Created an actual project and did the E2E test myself
=> Test: Add test case for custom timestamps v1->v2 transform

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/__snapshots__/auth-stack-transform.test.ts.snap, packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.test.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/user-pool-group-stack-transform.ts
=> fix(amplify-category-auth): fix async await and update unit-tests

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/field-auth-argument.test.ts.snap, packages/amplify-graphql-auth-transformer/src/__tests__/field-auth-argument.test.ts, packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts, packages/amplify-graphql-auth-transformer/src/utils/index.ts
=> fix: update field auth check logic and error message

packages/amplify-provider-awscloudformation/src/__tests__/resource-package/resource-export.test.ts, packages/amplify-provider-awscloudformation/src/resource-package/resource-export.ts, packages/amplify-provider-awscloudformation/src/resource-package/resource-packager.ts
=> feat: added updated stack descriptions

packages/amplify-graphql-transformer-migrator/src/__tests__/migration/__snapshots__/auth-tests.ts.snap, packages/amplify-graphql-transformer-migrator/src/__tests__/migration/auth-tests.ts, packages/amplify-graphql-transformer-migrator/src/migrators/auth/ownerAuth.ts
Uses groups to also look for protected operations during migration.
=> fix(graphql-transformer-migrator): fix protected rules that come from groups

packages/amplify-graphql-transformer-migrator/src/__tests__/migration/__snapshots__/auth-tests.ts.snap, packages/amplify-graphql-transformer-migrator/src/__tests__/migration/auth-tests.ts
Adds migrator unit tests for `@auth` directive.
=> test(graphql-transformer-migrator): add migrator unit tests for auth

packages/amplify-category-api/resources/awscloudformation/overrides-resource/APIGW/override.ts.sample, packages/amplify-category-api/src/commands/api/add-graphql-datasource.ts, packages/amplify-category-api/src/commands/api/add.ts, packages/amplify-category-api/src/commands/api/console.ts, packages/amplify-category-api/src/commands/api/gql-compile.ts, packages/amplify-category-api/src/commands/api/push.ts, packages/amplify-category-api/src/commands/api/remove.ts, packages/amplify-category-api/src/commands/api/update.ts, packages/amplify-category-api/src/index.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.ts, packages/amplify-cli-extensibility-helper/src/index.ts, packages/amplify-cli-extensibility-helper/src/types/api/types.ts, packages/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts
Fixes for:
- Add function permissions for REST API fails
- Add function permissions for GraphQL API fails
- Update REST API with permissions for userpool groups fails
- Undefined message after ctrl+c in the middle of amplify update api (and other commands)
=> fix: error handling, various bugs

packages/amplify-graphql-transformer-migrator/src/__tests__/migration/__snapshots__/auth-tests.ts.snap
=> fix(amplify-category-api): update snapshot

packages/amplify-category-api/resources/awscloudformation/overrides-resource/AppSync/override.ts.sample, packages/amplify-category-api/resources/awscloudformation/overrides-resource/AppSync/tsconfig.json, packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts, packages/amplify-category-api/tsconfig.json, packages/amplify-cli-extensibility-helper/src/index.ts, packages/amplify-cli-extensibility-helper/src/types/api/amplify-api-resource-stack-types.ts, packages/amplify-graphql-transformer-core/src/types/amplify-api-resource-stack-types.ts, packages/amplify-graphql-transformer-core/src/types/utils.ts
- changed type to AmplifyApiGraphQlResourceStackTemplate
- changed resource to resources in override.ts.sample
- disable strict checking
- fixed lambda auth mode validation error
=> fix: tsconfig changes and renames

packages/amplify-category-api/resources/awscloudformation/overrides-resource/APIGW/package.json, packages/amplify-category-api/resources/awscloudformation/overrides-resource/AppSync/package.json, packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts, packages/amplify-cli-extensibility-helper/src/index.ts
=> fix: rest iam policy roles array, bump ext helper types version

packages/amplify-category-api/resources/awscloudformation/overrides-resource/APIGW/package.json, packages/amplify-category-api/resources/awscloudformation/overrides-resource/AppSync/package.json, packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts, packages/amplify-cli-extensibility-helper/src/index.ts
=> fix: rest iam policy roles array, bump ext helper types version (#8983)

packages/amplify-graphql-transformer-migrator/src/__tests__/migration/__snapshots__/auth-tests.ts.snap
=> fix: fixed snapshot

packages/amplify-e2e-tests/src/__tests__/transformer-migrations/predictions-migration.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/PredictionsTransformerTests.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/PredictionsTransformerV2Tests.e2e.test.ts
=> test(amplify-e2e-tests): fixed german translation for e2e test

packages/graphql-transformers-e2e-tests/src/__tests__/TransformerOptionsV2.e2e.test.ts
Missed during https://github.com/aws-amplify/amplify-cli/pull/8980 refactor.
=> test: update user defined slot in E2E test

packages/amplify-graphql-transformer-migrator/src/__tests__/migration/__snapshots__/auth-tests.ts.snap, packages/amplify-graphql-transformer-migrator/src/__tests__/migration/__snapshots__/migrate-tests.ts.snap, packages/amplify-graphql-transformer-migrator/src/migrators/connection/index.ts
- fix migrator connection to belongs to check
=> fix(graphql-transformer-migrator): fixed belongs to type relationship check

packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts, packages/amplify-cli-extensibility-helper/src/types/api/types.ts
=> fix: overriding multiple userPoolGroups, ext helper type, lambda cfn

packages/amplify-cli-core/src/category-interfaces/category-base-schema-generator.ts, packages/amplify-e2e-core/src/categories/api.ts, packages/amplify-e2e-core/src/categories/auth.ts, packages/amplify-migration-tests/src/__tests__/migration_tests/overrides/apigw-ext-migration.test.ts
=> test: moved migration test and fixed the workflow

packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts
=> fix: add missing property on path in cfn

.circleci/enable_auth.exp
=> test: fixed integ test walkthrough

packages/amplify-cli-core/src/category-interfaces/category-base-schema-generator.ts, packages/amplify-e2e-core/src/categories/api.ts, packages/amplify-e2e-core/src/categories/auth.ts, packages/amplify-migration-tests/src/__tests__/migration_tests/overrides/apigw-ext-migration.test.ts, packages/amplify-migration-tests/src/migration-helpers/api.ts
`amplify-migration-tests/src/__tests__/migration_tests/overrides/apigw-ext-migration.test.ts` passes
=> test: separate migration test helper from e2e

packages/amplify-e2e-core/src/categories/api.ts, packages/amplify-e2e-tests/src/__tests__/api_5.test.ts, packages/amplify-migration-tests/src/__tests__/migration_tests/overrides/apigw-ext-migration.test.ts
Update helper addRestApi to account for case when no Lambda functions exist in a project.
`api_5.test.ts` passed locally.
=> test: fix api_5.test.ts

packages/amplify-e2e-tests/src/__tests__/apigw.test.ts
`packages/amplify-e2e-tests/src/__tests__/apigw.test.ts` failed before the change, passed after.
=> test: add missing option to e2e test

packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts
one regression in previous PR fixed
=> fix: regression in bucket params fetch

packages/amplify-cli-extensibility-helper/src/types/api/amplify-api-resource-stack-types.ts
=> feat: descoped http and functions override

packages/amplify-category-api/resources/awscloudformation/overrides-resource/APIGW/package.json, packages/amplify-category-api/resources/awscloudformation/overrides-resource/AppSync/package.json, packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/utils/print-api-key-warnings.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/synthesize-resources.ts
=> fix: address feedback

packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts, packages/amplify-category-auth/src/commands/auth/remove.ts, packages/amplify-graphql-function-transformer/src/__tests__/amplify-graphql-function-transformer-override.test.ts, packages/amplify-graphql-http-transformer/src/__tests__/amplify-graphql-http-transformer-override.test.ts, packages/amplify-graphql-predictions-transformer/src/__tests__/amplify-graphql-predictions-transformer-override.test.ts, packages/amplify-provider-awscloudformation/src/download-api-models.ts
=> fix: addressed comments

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/utils/global-sandbox-mode.test.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts, packages/amplify-category-api/src/provider-utils/awscloudformation/utils/global-sandbox-mode.ts, packages/amplify-cli-core/src/index.ts, packages/amplify-cli-core/src/utils/doc-links.ts, packages/amplify-cli-core/src/utils/gql-transformer-version.ts, packages/amplify-provider-awscloudformation/src/__tests__/graphql-push-schema-checks.test.ts, packages/amplify-provider-awscloudformation/src/__tests__/utils/sandbox-mode-helpers.test.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts, packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts, packages/amplify-provider-awscloudformation/src/utils/sandbox-mode-helpers.ts, packages/amplify-util-mock/src/__tests__/api/lambda-arn-to-config.test.ts, packages/amplify-util-mock/src/api/lambda-arn-to-config.ts
=> docs: update graphql-transformer docs on version

packages/amplify-category-api/resources/awscloudformation/overrides-resource/APIGW/package.json, packages/amplify-category-api/resources/awscloudformation/overrides-resource/AppSync/package.json, packages/amplify-e2e-tests/src/__tests__/api_7.test.ts
=> chore: add ^ to version, disable override test

packages/amplify-e2e-core/src/categories/storage.ts
storage-1 e2e test passed locally
=> test: back2back wait text caused intermittent failures

packages/amplify-e2e-core/src/utils/api.ts, packages/amplify-e2e-tests/src/__tests__/__snapshots__/api_2.test.ts.snap, packages/amplify-e2e-tests/src/__tests__/api_2.test.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/utils.ts
=> fix: allow custom admin roles to be passed into gql transformer

packages/amplify-e2e-core/src/categories/api.ts
'adds a rest api and then adds a path to the existing api' of api_5.test.ts passes
=> test: account for prompter auto picking option

packages/amplify-graphql-auth-transformer/src/resolvers/helpers.ts
=> fix: update admin role check to make sure the name is not authRole or unauthRole

packages/amplify-e2e-tests/src/__tests__/__snapshots__/api_2.test.ts.snap, packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/amplify-admin-auth.test.ts.snap, packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/multi-auth.test.ts.snap
=> test: update snapshots for auth admin role check

packages/amplify-graphql-transformer-migrator/src/utils.ts
=> fix: api migrate command when rest apis are added

packages/amplify-util-mock/src/CFNParser/intrinsic-functions.ts, packages/amplify-util-mock/src/CFNParser/stack/index.ts
=> fix: update mock cfn parsing to support stack outputs in intrinsic fns

packages/amplify-cli/src/config-steps/c0-analyzeProject.ts
- fixes headless project configure
- manual test
=> fix(cli): fix headless project configure

packages/amplify-cli/src/config-steps/c0-analyzeProject.ts, packages/amplify-cli/src/input-params-manager.ts
- fix for headless project configure
=> fix(cli): fix for headless project configure

packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js
fixes #9037
Related - https://github.com/aws-amplify/amplify-cli/pull/9060
=> fix: aggreagate paginated results in cfn.listStackResources call

packages/amplify-cli-core/src/cliConstants.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts, packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-transform.ts
Fixes issue where a function could be missing parameters on push. The important changes are [here](https://github.com/aws-amplify/amplify-cli/pull/9144/files#diff-6f7b986fa50f2473577d65324b57c49e2f5d41655fcf29a8937dfbed5ee548ceR1099).
This PR also includes some refactoring and adds a missing apostrophe in an error message.
Fix: #9170
- `yarn test` passes for function and provider packages
- function_1.test.ts, function_2.test.ts passes
=> fix: function parameters not being properly added to root stack

packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts
=> fix: call the correct migration function for Admin Queries

packages/amplify-e2e-core/src/init/amplifyPush.ts, packages/amplify-migration-tests/src/__tests__/migration_tests/overrides/apigw-ext-migration.test.ts, packages/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts
=> fix: incorrect function parameters in invokePluginMethod call

packages/amplify-cli/src/commands/push.ts
display invalid directive error on amplify push
=> fix(graphql): display invalid directive error on amplify push

packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-domain.ts, packages/amplify-graphql-transformer-core/src/transformer-context/resource-helper.ts
The change skips truncating unresolved tokens from cdk
=> fix: skip truncating unresolved tokens

packages/amplify-util-mock/package.json, packages/amplify-util-mock/src/__e2e__/utils/index.ts, packages/amplify-util-mock/src/__e2e_v2__/function-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e_v2__/index-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e_v2__/model-relational-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e_v2__/model-relational-with-key-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e_v2__/model-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e_v2__/util-method.e2e.test.ts
Port non-auth mock util tests over for v2 transformers. (Auth tests to follow in a separate PR.)
=> test(amplify-util-mock): add e2e tests for new transformers

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, yarn.lock
=> build: codege gqlv2 fix

packages/amplify-provider-awscloudformation/src/push-resources.ts
#9144 incorrectly fixed a symptom instead of the root cause. The root cause was fixed by #9182.
This reverts the incorrect change made in #9144
#9197, #9205, #9223
=> fix: incorrect logic from PR #9144, fixes #9197, #9205

packages/amplify-e2e-core/src/utils/transformConfig.ts, packages/amplify-e2e-tests/package.json, packages/amplify-e2e-tests/schemas/custom_transformers/simple_custom_model.graphql, packages/amplify-e2e-tests/schemas/custom_transformers/simple_custom_transformer.js, packages/amplify-e2e-tests/src/__tests__/graphql-v2/custom-transformers.test.ts, packages/amplify-graphql-transformer-core/src/config/project-config.ts, packages/amplify-graphql-transformer-core/src/config/transformer-config.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts
This PR updates the v2 custom transformer loading logic to reflect reality.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/9180
=> fix: update gql v2 custom transformer loading logic

packages/amplify-e2e-core/src/categories/hosting.ts
Need to also pin create-react-app in the E2E core package
Following same validation as the previous PR, #9311
Just getting this spot up to date also
=> Pin create-react-app E2E core

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/multi-auth.test.ts.snap, packages/amplify-graphql-auth-transformer/src/__tests__/multi-auth.test.ts, packages/amplify-graphql-auth-transformer/src/resolvers/query.ts, packages/amplify-util-mock/src/__tests__/velocity/model-auth.test.ts
- fix key condition expression in auth transformer
- Fixes: https://github.com/aws-amplify/amplify-cli/issues/9222
- manually following reproduction steps with mock
- manually executing tests with the ticket schema and appsync
=> fix(graphql-auth-transformer): fix key condition expression

packages/amplify-graphql-model-transformer/src/__tests__/model-transformer.test.ts, packages/amplify-graphql-transformer-core/src/transformation/validation.ts
- pass through @aws_directive
- [9227](https://github.com/aws-amplify/amplify-cli/issues/9227)
- manual test
- regression test added
=> fix(graphql-model-transformer): @aws_lambda GQL transformer pass through directive list

packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts, packages/amplify-cli-extensibility-helper/src/types/auth/types.ts
- implemented method to add cfn resource via overrides in auth
- update types to include addResource calls
- tested Manually 
- 
=> fix: implemented method to add CFN resource via overrides in auth

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, yarn.lock
Update codegen package with tagged release
=> chore: update codegen with tagged release

packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-config.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts
=> refactor(graphql-transformer-core): removed duplicated load project method

packages/amplify-appsync-simulator/src/velocity/util/transform/dynamodb-filter.ts
Add support for 'in' expression to appsync simulator.
https://github.com/aws-amplify/amplify-cli/issues/9220
- yarn test
- manual test
=> fix(graphql): add *in* expression handler to appsync simulator

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/amplify-admin-auth.test.ts.snap, packages/amplify-graphql-auth-transformer/src/__tests__/amplify-admin-auth.test.ts, packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts, packages/amplify-graphql-auth-transformer/src/resolvers/field.ts, packages/amplify-graphql-auth-transformer/src/resolvers/helpers.ts, packages/amplify-util-mock/src/__tests__/velocity/admin-auth.test.ts
- return field name on the admin role check for field resolvers
- unit test
- vtl unit test
- fixes #9242 
- unit test
- vtl unit test
- local environment
=> fix: return field value for admin roles on field resolver

packages/amplify-provider-awscloudformation/src/__tests__/display-helpful-urls.test.ts, packages/amplify-provider-awscloudformation/src/display-helpful-urls.js
Fixes: https://github.com/aws-amplify/amplify-cli/issues/9160
=> fix: add gql transformer version to status output

packages/amplify-util-mock/src/__e2e_v2__/index-transformer.e2e.test.ts
=> test: fix index queryfield test

packages/amplify-category-api/src/provider-utils/supported-services.ts, packages/amplify-cli/src/extensions/amplify-helpers/editor-selection.ts
just fix naming convention
#8616 
=> chore: rename Mac OS -> macOS

packages/graphql-transformers-e2e-tests/package.json, yarn.lock
=> build: pin aws-amplify version to make it work with graphql-tag

.github/ISSUE_TEMPLATE/1.bug_report.yaml
- chore(bug report): add export command
=> chore(bug template): update export cmd

packages/amplify-e2e-core/src/init/initProjectHelper.ts, packages/amplify-migration-tests/src/migration-helpers/init.ts
#8573 updated the "pro-tip" from `"... to create a backend API and then "amplify publish" to deploy everything"` to `"to create a backend API and then "amplify push" to deploy everything"`
This PR updates expectations in e2e tests to match.
=> test: look for 'to create a backend API and then "amplify push" to deploy everything' in e2e

packages/amplify-e2e-tests/src/__tests__/custom_resources.test.ts
This commit updates a failing E2E test to properly import the uuid dependency.
=> test: update uuid import for failing e2e test

packages/amplify-cli/src/commands/status.ts
- add argument validation to `acm` option for `status api --acm` command as model name is required
- do a full schema compilation before generating Access Control Matrix to make sure that ACM is not generated for a schema with validation errors.
Fixes: #9400
Manual testing
=> fix: compile schema before acm generation and validate acm argument

packages/amplify-console-integration-tests/src/consoleHosting/consoleHosting.ts, packages/amplify-e2e-core/src/init/initProjectHelper.ts, packages/amplify-e2e-core/src/utils/pinpoint.ts, packages/amplify-e2e-tests/src/environment/env.ts, packages/amplify-e2e-tests/src/init-special-cases/index.ts
This PR extends #9445 for compatibly with all existing and future migration tests.
=> test: use regex every time in case of future migration tests

packages/amplify-codegen-appsync-model-plugin/package.json
=> chore: manual patch version bump

.circleci/local_publish_helpers.sh, packages/amplify-e2e-core/src/index.ts
This pr fixes a build script that is blocking the pipeline. it also pins colors.js for migration tests
=> fix pkg cli script

.circleci/local_publish_helpers.sh, packages/amplify-e2e-core/src/index.ts, packages/amplify-e2e-tests/src/__tests__/uibuilder.test.ts
This pr makes sure the uibuilder test passes by ensuring the react server spun up in the tests is killed
=> test: add timeout to uibuilder test

packages/amplify-e2e-tests/src/__tests__/apigw.test.ts
=> chore: build fix

packages/amplify-category-geo/resources/custom-map-resource-handler.js, packages/amplify-category-geo/resources/custom-place-index-resource-handler.js, packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/mapStack.test.ts.snap, packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/placeIndexStack.test.ts.snap, packages/amplify-category-geo/src/__tests__/service-utils/resourceUtils.test.ts, packages/amplify-category-geo/src/__tests__/service-utils/serviceUtils.test.ts, packages/amplify-category-geo/src/__tests__/service-walkthroughs/mapWalkthrough.test.ts, packages/amplify-category-geo/src/__tests__/service-walkthroughs/placeIndexWalkthrough.test.ts, packages/amplify-category-geo/src/provider-controllers/map.ts, packages/amplify-category-geo/src/provider-controllers/placeIndex.ts, packages/amplify-category-geo/src/service-stacks/mapStack.ts, packages/amplify-category-geo/src/service-stacks/placeIndexStack.ts, packages/amplify-category-geo/src/service-utils/constants.ts, packages/amplify-category-geo/src/service-utils/mapUtils.ts, packages/amplify-category-geo/src/service-utils/placeIndexUtils.ts, packages/amplify-category-geo/src/service-utils/resourceParams.ts, packages/amplify-category-geo/src/service-utils/resourceUtils.ts, packages/amplify-category-geo/src/service-walkthroughs/mapWalkthrough.ts, packages/amplify-category-geo/src/service-walkthroughs/placeIndexWalkthrough.ts, packages/amplify-category-geo/src/service-walkthroughs/resourceWalkthrough.ts, packages/amplify-e2e-core/src/categories/geo.ts, packages/amplify-e2e-tests/src/__tests__/geo-headless.test.ts, packages/amplify-headless-interface/schemas/geo/1/AddGeoRequest.schema.json, packages/amplify-headless-interface/src/interface/geo/add.ts, packages/amplify-util-headless-input/src/__tests__/assets/geo/add/validRequest.map.json, packages/amplify-util-headless-input/src/__tests__/geo/add/__snapshots__/index.test.ts.snap
Location service team updated their APIs to only allow `RequestBasedUsage` pricing plan for Geo resources thereby deprecating the Asset based pricing plans. The below list of changes are necessary in Amplify CLI Geo plugin to accommodate that change.
- Removes the pricing plan walkthrough from `add/update` commands. Set the `PricingPlan` value for a geo resource to always be `RequestBasedUsage`.
- Warn when `Esri` data provider is chosen that the resource cannot be used for tracking/routing commercial assets.
- Change the default data provider for Search to `HERE`.
For the customers who already have the Maps/Search added to their application, they need to `update` their Geo resources using `amplify update geo` and choose the existing Geo resource. The configuration for the resource can …
=> Remove pricing plan walkthrough for Maps and Search

packages/amplify-e2e-tests/src/__tests__/apigw.test.ts
=> chore: e2e test fix

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, yarn.lock
=> Codegen-version-bump

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, yarn.lock
Reverts aws-amplify/amplify-cli#9512
=> Revert "Codegen-version-bump"

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, yarn.lock
=> Codegen-version-bump-2.27.2

packages/amplify-e2e-tests/src/__tests__/containers-api.test.ts
=> test(api): fix api container tests

packages/amplify-e2e-tests/src/__tests__/containers-api-secrets.test.ts, packages/amplify-e2e-tests/src/__tests__/containers-api.test.ts
Split container api tests into separate files.
=> test(api): split api container tests

packages/amplify-cli-core/src/feature-flags/featureFlags.ts, packages/amplify-cli/src/commands/push.ts, packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts
- adds prompt to push graphql security updates
=> chore(amplify-app,amplify-provider-awscloudformation): security enhancement push required message

packages/amplify-cli/src/commands/push.ts
- fix checks for security notification prompt
=> fix(amplify-app): fix security enhancement notification

packages/amplify-cli/src/commands/push.ts
- Security enhancement notification update
=> fix(amplify-app): security enhancement notification fix

packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts, packages/amplify-category-auth/src/commands/auth/remove.ts, packages/amplify-cli/src/__tests__/extensions/amplify-helpers/remove-resource.test.ts, packages/amplify-cli/src/extensions/amplify-helpers/remove-resource.ts
This reverts commit edced3ef76da02bd269cf85c7287bfb74875d967.
This was causing widespread failures in the E2E test suite.
=> Revert "fix: handle auth and api dependency in state files correctly (#9528)

packages/amplify-graphql-maps-to-transformer/package.json
Fixes mapsTo lambda build script
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/6217/workflows/9b4f647e-01c9-44ff-a7d6-f85bf4f24f15/jobs/155382
Ran build script on clean package
=> fix: mapping lambda build script

packages/amplify-migration-tests/src/__tests__/migration_tests/lambda-layer-migration/layer-migration.test.ts
The test was using the an older version to cleanup the project, modified the deletion script to use the latest
=> test: invoke deletion using the latest version

packages/amplify-category-auth/package.json, packages/amplify-category-storage/package.json, packages/amplify-cli-core/package.json, packages/amplify-cli-core/tsconfig.json, packages/amplify-cli/package.json, packages/amplify-dotnet-function-runtime-provider/src/utils/detect.ts, packages/amplify-graphiql-explorer/package.json, packages/amplify-graphiql-explorer/tsconfig.json, packages/amplify-headless-interface/package.json, yarn.lock
=> chore: consolidate dependencies, remove unused code

.github/ISSUE_TEMPLATE/1.bug_report.yaml, .github/ISSUE_TEMPLATE/2.feature_request.yaml, .github/ISSUE_TEMPLATE/3.usage-question.md
Adds more text asking developers to remove sensitive information from their GitHub communication
=> chore: update templates to advise to remove sensitive data

packages/amplify-category-auth/resources/adminAuth/admin-auth-package.json
- removes unnecessary build scripts from AdminQueries `package.json`
- aligns provided package.json keys with other function templates (removes `author`, devDependencies)
ref #9656 
=> feat: update admin queries package dependencies, scripts

packages/amplify-cli/package.json, packages/amplify-cli/src/commands/console.ts, packages/amplify-cli/src/commands/logout.ts
- Replace usage of enquirer in the `amplify-cli` package with `amplify-prompts`
- Remove extra call to import the provider plugin
- Add a few missing types
=> chore(cli): remove enquirer direct dependency, extra import

packages/amplify-appsync-simulator/src/server/subscription/mqtt-server/client.ts, packages/amplify-cli/src/commands/push.ts, packages/amplify-cli/src/extensions/amplify-helpers/auth-notifications.ts, yarn.lock
- security enhancement notification, handle projects with schema directory
=> fix(cli): fix security enhancement notification for projects with schema dir

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, yarn.lock
Codegen version bump.
n/a
* `yarn test`
* @ragingsquirrel3 validated changes work as expected.
=> chore: upgrade to amplify-codegen@2.28.0

packages/amplify-e2e-core/src/categories/storage.ts, packages/amplify-e2e-tests/src/__tests__/storage-1.test.ts
~adding delay to avoid test from picking up previous pattern~
Using groups for walkthrough pattern
=> test: using the full message to match pattern for walkthrough

packages/amplify-cli-core/src/customPoliciesUtils.ts
Updates the URL displayed in the CLI to the new URL
Closes #9558
=> docs: update custom policies documentation url

scripts/check-version.ts
=> build: fix version check script for beta release

packages/amplify-graphql-schema-test-library/src/index.ts
These are a subset of schemas used by the library and DataStore teams.
=> test: add more schemas to schema library

packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.test.ts.snap
Update searchable snapshot for the PR https://github.com/aws-amplify/amplify-cli/pull/9265.
=> test(graphql): update snapshot for searchable index change

packages/amplify-category-api/resources/awscloudformation/container-templates/dockercompose-rest-express/python/requirements.txt
update container flask requirements.txt to resolve the issue with flask dependencies.
=> test(api): update container flask requirements.txt

CONTRIBUTING.md
updates community discord channel name and adds direct URL
`first-time-contributor` -> `contributing`
=> docs: update discord community contributing channel, add link

packages/amplify-appsync-simulator/src/__tests__/velocity/value-mapper/array.test.ts, packages/amplify-appsync-simulator/src/__tests__/velocity/value-mapper/decimal.test.ts, packages/amplify-appsync-simulator/src/__tests__/velocity/value-mapper/integer.test.ts, packages/amplify-appsync-simulator/src/__tests__/velocity/value-mapper/string.test.ts, packages/amplify-appsync-simulator/src/velocity/value-mapper/array.ts, packages/amplify-appsync-simulator/src/velocity/value-mapper/decimal.ts, packages/amplify-appsync-simulator/src/velocity/value-mapper/integer.ts, packages/amplify-appsync-simulator/src/velocity/value-mapper/map.ts, packages/amplify-appsync-simulator/src/velocity/value-mapper/mapper.ts, packages/amplify-appsync-simulator/src/velocity/value-mapper/string.ts, packages/amplify-util-mock/src/__tests__/velocity/vtl-behavior.test.ts, packages/amplify-velocity-template/src/compile/set.js
Fixes: https://github.com/aws-amplify/amplify-cli/issues/8774
=> fix: support Java numbers in appsync simulator

packages/amplify-cli-core/src/__tests__/hooks/hooksMeta.test.ts, packages/amplify-cli/resources/sample-hooks/pre-push.js.sample
Once, I try to change implementation to match documentation, but, it is not a safe change (https://github.com/aws-amplify/amplify-cli/pull/9347). So, I change comments for environment in sample hooks script. And I add test that implementation for environment in hooks script match documentation.
I also change documentation (https://github.com/aws-amplify/docs/pull/4049).
fix #9346 
=> change comments for environment in sample hooks script

packages/amplify-cli/src/commands/help.ts
This PR improves the grammar when directing customers to the troubleshooting docs.
https://github.com/aws-amplify/amplify-cli/issues/9766
=> chore: update troubleshooting message

packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts
- Fixes REST API `overrides.ts` build errors were mistakenly hidden and swallowed.
- Convert use of `.catch` to `try/catch`
Fixes #9695
Observed expected failure when building invalid TS
```ts
export function override(resources: AmplifyApiRestResourceStackTemplate) {
console.log('hello', world);
}
```
```bash
➜  api-override-example ad build
🛑 Failed to override api9f20b637 due to: Error: Packaging overrides failed with the error:
Command failed with exit code 2: /Users/johocke/test/api-override-example/amplify/backend/node_modules/.bin/tsc --project /Users/johocke/test/api-override-example/amplify/backend/api/api9f20b637/build/tsconfig.resource.json
../override.ts(22,24): error TS2304: Cannot find name 'world'..
```
By submitting this pull request, I confirm that my contribution is made …
=> fix(amplify-category-api): surface override build errors for REST APIs

packages/amplify-category-function/src/commands/function.ts
Add `console` in subcommands list on help.
fix #9886
Manual Testing: Run `amplify function`.
=> fix(amplify-category-function): Make sure to show `console` in subcommand list in function category

packages/amplify-appsync-simulator/src/__tests__/resolvers/pipeline-resolver.test.ts, packages/amplify-appsync-simulator/src/__tests__/resolvers/unit-resolver.test.ts
Fixes unit test failures due to changes in https://github.com/aws-amplify/amplify-cli/pull/9687
=> test(amplify-appsync-simulator): update unit tests

packages/amplify-graphql-auth-transformer/src/__tests__/acm-test-library.ts, packages/amplify-graphql-auth-transformer/src/__tests__/acm.test.ts
- added ACM test for various configurations
- contains changes from [9859](https://github.com/aws-amplify/amplify-cli/pull/9859) [only last commit needs reviewed]
=> Added ACM test for various configurations

packages/amplify-category-auth/src/__tests__/commands/enable.test.ts, packages/amplify-category-auth/src/__tests__/commands/import.headless.test.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/project-has-auth.ts
=> fix: error message when auth is already imported

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json
=> chore: bump codegen version

yarn.lock
=> chore: sync yarn.lock file

.circleci/config.base.yml, .circleci/config.yml, .circleci/local_publish_helpers.sh, packages/amplify-cli-npm/binary.ts
packaged cli binary should be available for arm64 linux machines.
n/a
built binary, tested it on arm64. cloud-e2e run with build/upload: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/7492/workflows/6fc46be1-9f94-4bd9-9c42-4b180cdc6bf5
=> ci: add arm64 linux deployment

packages/amplify-category-auth/src/index.js, packages/amplify-e2e-core/src/init/initProjectHelper.ts, packages/amplify-e2e-core/src/utils/index.ts, packages/amplify-e2e-core/src/utils/transform-current-project-to-git-pulled-project.ts, packages/amplify-e2e-tests/src/__tests__/init-special-case.test.ts, packages/amplify-provider-awscloudformation/src/initialize-env.ts
- Build resource first when adding a new env locally when project is git pulled
- Add missing await
- Already approved PR e2e fix: https://github.com/aws-amplify/amplify-cli/pull/10003
- Revert PR fix for console integration test : https://github.com/aws-amplify/amplify-cli/pull/10037
- e2e test for same scenario
=> fix: build resource when adding new env

yarn.lock
=> chore: bump resolved simple-plist version in yarn.lock

packages/amplify-util-uibuilder/src/__tests__/syncAmplifyUiComponents.test.ts, packages/amplify-util-uibuilder/src/commands/cloneComponentsFromEnv.ts, packages/amplify-util-uibuilder/src/commands/utils/amplifyUiBuilderService.ts, packages/amplify-util-uibuilder/src/commands/utils/syncAmplifyUiBuilderComponents.ts
- refactored `exportComponents` & `exportThemes` api calls to use `nextToken`
- centralized use of `getAmplifyUIBuilderService`
=> chore: add pagination for export Component&Theme

CONTRIBUTING.md, package.json, yarn.lock
- Bump `@commitlint` dependencies to latest
- Remove dependency on commitizen
- Remove section on using commitizen in contributing guide
- Update stale sections of the contributing guide
Manually checked that an invalid commit was rejected, and this commit was accepted.
=> chore: update commit related dependencies, update CONTRIBUTING.md

packages/amplify-util-uibuilder/package.json
- Updated CodegenUI Packages to `2.2.0`
- Updated `aws-sdk` to use latest uibuilder sdk changes
=> update uibuilder pkg dependencies

packages/amplify-frontend-javascript/lib/frontend-config-creator.js
reverts #10147 - breaking windows e2e tests
=> chore(amplify-app): reverts #10147

packages/amplify-e2e-tests/src/__tests__/uibuilder.test.ts, yarn.lock
=> test: update component in uibuilder e2e

.circleci/local_publish_helpers.sh
=> chore: fix upload pkg script

packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts, yarn.lock
- Fixed the logic to handle a non-existant amplify-meta file to match previous behavior that was changed in https://github.com/aws-amplify/amplify-cli/pull/10022
- Building the CLI updated the `yarn.lock` file
=> fix: amplify meta file resolution, update yarn.lock

packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts
Fixed a couple of mistakes made during refactoring: https://github.com/aws-amplify/amplify-cli/pull/10022
=> fix: accidental changes to meta file reading and resource status filter

jest.config.js, packages/amplify-category-geo/src/__tests__/service-utils/resourceUtils.test.ts, packages/amplify-category-geo/src/__tests__/service-walkthroughs/mapWalkthrough.test.ts, packages/amplify-category-geo/src/__tests__/service-walkthroughs/placeIndexWalkthrough.test.ts, packages/amplify-category-geo/src/service-utils/mapUtils.ts, packages/amplify-category-geo/src/service-utils/resourceUtils.ts, packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts, packages/amplify-e2e-core/src/categories/auth.ts, packages/amplify-e2e-tests/src/__tests__/auth_10.test.ts
- update backend-config.json file on auth/geo category update
- e2e test added
- unit tests updated
=> fix(amplify-category-auth,amplify-category-geo): update backend-config on auth/geo category update

packages/amplify-category-geo/src/service-walkthroughs/mapWalkthrough.ts
Updates the default style listed in the advanced settings prompt to Navigation.
See: https://github.com/aws-amplify/amplify-cli/pull/10168
=> update default style in advanced settings prompt

packages/amplify-graphql-auth-transformer/src/__tests__/owner-auth.test.ts, packages/amplify-graphql-auth-transformer/src/resolvers/subscriptions.ts
Reverts aws-amplify/amplify-cli#10199
Fixes: https://github.com/aws-amplify/amplify-cli/issues/10254
=> Revert "refactor: use a prefix matching for the claim in subscriptions"

packages/amplify-provider-awscloudformation/package.json, packages/amplify-provider-awscloudformation/src/push-resources.ts, yarn.lock
The cfn-lint project is no more supported and is outdate removing it
=> fix: remove unsupported cfn-lint

package.json, packages/amplify-velocity-template/package.json, yarn.lock
This PR updates our nth-check dependency to 2.x
=> chore: update nth-check

package.json, yarn.lock
This PR upgrades our glob-parent dependency to 6.x
=> chore: update glob-parent

packages/amplify-cli-core/src/feature-flags/featureFlags.ts, packages/amplify-graphql-auth-transformer/src/__tests__/accesscontrol.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/acm.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/amplify-admin-auth.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/conflict-resolution.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/custom-auth.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/field-auth-argument.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/group-auth.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/multi-auth.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/searchable-auth.test.ts, packages/amplify-graphql-auth-transformer/src/__tests__/test-helpers.ts, packages/amplify-graphql-auth-transformer/src/resolvers/helpers.ts, packages/amplify-graphql-auth-transformer/src/utils/constants.ts, packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-many-to-many-transformer.test.ts, packages/amplify-graphql-relational-transformer/src/__tests__/relational-auth.test.ts, packages/amplify-graphql-relational-transformer/src/__tests__/test-helpers.ts, packages/amplify-util-mock/src/__tests__/velocity/admin-auth.test.ts, packages/amplify-util-mock/src/__tests__/velocity/model-auth.test.ts, packages/amplify-util-mock/src/__tests__/velocity/multi-auth.test.ts, packages/amplify-util-mock/src/__tests__/velocity/relational-auth.test.ts, packages/amplify-util-mock/src/__tests__/velocity/test-helper.ts, packages/graphql-transformers-e2e-tests/src/__tests__/AuthV2Transformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/IndexWithAuthV2.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/MultiAuthV2Transformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/PerFieldAuthV2Transformer.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/RelationalWithAuthV2.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/SearchableWithAuthV2.e2e.test.ts, packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsWithAuthV2.e2e.test.ts
This pull request extracts the feature flag and helper methods from https://github.com/aws-amplify/amplify-cli/pull/10196 so that the mutation, query, search, and subscription pull requests can use the code and be merged/tested independently.
=> Add feature flag and resolver helpers for identity claim changes

packages/amplify-graphql-auth-transformer/src/__tests__/owner-auth.test.ts, packages/amplify-graphql-auth-transformer/src/resolvers/subscriptions.ts
Reverts aws-amplify/amplify-cli#10264
Re-reverts https://github.com/aws-amplify/amplify-cli/pull/10199
=> feat: matches identity claim for subscription (revert)

packages/amplify-graphiql-explorer/config/webpack.config.js, packages/amplify-graphiql-explorer/public/index.html
Reverts aws-amplify/amplify-cli#10308
Breaks integration tests
=> Revert "fix: explicitly assign buffer to node.global"

packages/amplify-cli/src/__tests__/init-steps/s0-analyzeProject.test.ts, packages/amplify-cli/src/__tests__/utils/win-utils.test.ts
=> fix: windows unit test for missing path assertion

packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts, packages/amplify-cli-extensibility-helper/src/index.ts, packages/amplify-e2e-tests/src/__tests__/apigw.test.ts, packages/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts
fix path append logic when the relative path is `/`
`yarn test` passes, e2e test `apigw.test.ts` passes locally
=> fix: root path handling for REST APIs

packages/amplify-cli-npm/binary.ts
Manual change to sync cli-internal and npm packge versions
=> fix: npm package version bump

packages/amplify-cli-npm/binary.ts
- Previous PR tag merged with fix tag  instead of feat tag which is required as per conventional commits to increase minor version
cloud-e2e : https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli 
=> feat: bump npm package version

yarn.lock
=> chore: fixes dependabot cross-fetch dependency

.eslintrc.js
=> chore: update unused vars lint rule

packages/amplify-cli-npm/tsconfig.json
- Ensure a minor bump in `amplify-cli-npm` with a feat commit
- Fixed formatting in `tsconfig.json`
=> feat: minor bump for amplify-cli-npm

packages/amplify-category-auth/src/index.js
- Removes context.print
- Not needed
=> chore: remove console logging from amplify auth event

packages/amplify-e2e-core/src/init/deleteProject.ts
=> test: delete projects even if stack is in a failed state

.eslint-dictionary.json, packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts
- this are the exact same changes that were added for api category: https://github.com/aws-amplify/amplify-category-api/pull/467
=> chore(amplify-e2e-tests): update cleanup script to correctly use assumed creds

packages/amplify-category-auth/package.json, packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/__snapshots__/user-pool-group-stack-transform.test.ts.snap, packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/user-pool-group-stack-transform.test.ts, packages/amplify-category-auth/src/index.js, packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-user-pool-group-stack-builder.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/user-pool-group-stack-transform.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/generate-user-pool-group-stack-template.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/synthesize-resources.ts
- fixed regression for populating custom policies for analytics category in userPool groups 
- [] `yarn test` passes
=> fix: userpool groups custom policies regression

packages/amplify-e2e-core/src/utils/nexpect.ts, packages/amplify-e2e-tests/src/__tests__/analytics.test.ts, packages/amplify-e2e-tests/src/__tests__/api_1.test.ts, packages/amplify-e2e-tests/src/__tests__/custom_policies_function.test.ts, packages/amplify-e2e-tests/src/__tests__/function_1.test.ts, packages/amplify-e2e-tests/src/__tests__/function_10.test.ts, packages/amplify-e2e-tests/src/__tests__/function_2.test.ts, packages/amplify-e2e-tests/src/__tests__/function_3.test.ts, packages/amplify-e2e-tests/src/__tests__/function_5.test.ts, packages/amplify-e2e-tests/src/__tests__/function_6.test.ts, packages/amplify-e2e-tests/src/__tests__/function_7.test.ts, packages/amplify-e2e-tests/src/__tests__/function_9.test.ts, packages/amplify-e2e-tests/src/__tests__/migration/node.function.test.ts, packages/amplify-migration-tests/src/__tests__/update_tests/function_migration_update.test.ts
- changes e2e tests to use uuid instead of random numers in function names
=> test(amplify-e2e-tests): changes function names to use uuid instead of random

.eslint-dictionary.json, packages/amplify-provider-awscloudformation/src/__tests__/graphql-resource-manager/diff-test-helper.ts, packages/amplify-provider-awscloudformation/src/graphql-resource-manager/amplify-graphql-resource-manager.ts
Handle GSI change on root template
=> handle GSI change on root template

packages/amplify-provider-awscloudformation/src/resourceParams.js
=> fix: added auth provider userPool check on root stack auth parameters

packages/amplify-cli/src/domain/amplify-usageData/IUsageData.ts, packages/amplify-cli/src/domain/amplify-usageData/UsageData.ts, packages/amplify-prompts/src/__tests__/stopwatch.test.ts, packages/amplify-prompts/src/prompter.ts, packages/amplify-prompts/src/stopwatch.ts
Added additional field that measure prompt time
=> feat: prompt interaction time

packages/amplify-cli-npm/tsconfig.json
- bumps amplify-cli-npm version to keep in sync with amplify-cli-internal
=> feat: no-op feat commit to force version bump

packages/amplify-migration-tests/src/__tests__/migration_tests/overrides/apigw-ext-migration.test.ts
=> test: fix import of initJSProfileWithProfile

packages/amplify-cli/src/commands/diagnose.ts
=> doc: added doc link and additional prompts

.eslint-dictionary.json, packages/amplify-category-custom/src/utils/build-custom-resources.ts, packages/amplify-cli/src/__tests__/context-manager.test.ts, packages/amplify-cli/src/__tests__/test-aborting.test.ts, packages/amplify-cli/src/__tests__/usage-data.test.ts, packages/amplify-cli/src/domain/amplify-usageData/IUsageData.ts, packages/amplify-cli/src/domain/amplify-usageData/NoUsageData.ts, packages/amplify-cli/src/domain/amplify-usageData/UsageData.ts, packages/amplify-cli/src/domain/amplify-usageData/UsageDataPayload.ts, packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js, packages/amplify-provider-awscloudformation/src/pre-push-cfn-processor/cfn-pre-processor.ts
=> feat: implemented push normalization

packages/amplify-cli-core/src/feature-flags/featureFlags.ts
Adding a new feature flag which will be used for the index directive. Currently leaving false until we have released the functionality, at which point I'll update so new projects use the flag.
N/A
N/A
=> chore: add feature flag (currently disabled, for index name auto generation

packages/amplify-cli-npm/run.ts
Sync version for the no op commit
=> feat: no op commit to sync versions

packages/amplify-cli/src/commands/diagnose.ts
Skip flag if headless flag introduced
=> fix: headless diagnose prompt

packages/amplify-graphiql-explorer/config/webpack.config.js, packages/amplify-graphiql-explorer/public/index.html
Reverts aws-amplify/amplify-cli#10314
=> Revert "Revert "fix: explicitly assign buffer to node.global""

packages/amplify-provider-awscloudformation/resources/rootStackTemplate.json, packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/__snapshots__/root-stack-builder.test.ts.snap, packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/__snapshots__/root-stack-transform.test.ts.snap, packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-builder.ts
Reverts aws-amplify/amplify-cli#10584
Reapplying the secure traffic PR with dependsOn for S3 bucket creation.
=> Revert "Revert "chore: block insecure traffic to deployment bucket""

packages/amplify-cli-core/src/feature-flags/featureFlags.ts
Reverts aws-amplify/amplify-cli#10603
=> Revert "Revert "chore: add FF for primary key connection field attributes""

packages/amplify-cli-npm/package.json, packages/amplify-cli/package.json
BREAKING CHANGE: this is a breaking change
BREAKING CHANGE: this is a breaking change
=> feat!: breaking change

.github/ISSUE_TEMPLATE/1.bug_report.yaml
updating GH template to include project Identifiers
=> doc: update to add project identifier

.circleci/config.base.yml
- add filter to e2e cleanup scripts
=> chore: filter e2e cleanup script branches

packages/amplify-cli-npm/install.ts, packages/amplify-cli/src/index.ts
=> feat: no-op commit

nx.json
This follows up https://github.com/aws-amplify/amplify-cli/pull/10663. This should be merged after `dev` branch is created and the base branch has been switched in GitHub.
=> chore: change default base in nx config to dev

.circleci/config.yml
Renames the branch param to `"dev"`.
=> chore: change branch name to dev in nightlys

packages/amplify-provider-awscloudformation/src/__tests__/override-manager/transform-resource.test.ts, packages/amplify-provider-awscloudformation/src/override-manager/transform-resource.ts
- added a debug log  instead of info()
- updated unit tests for the same
=> fix: override msg for non-overrides categories

packages/amplify-cli/package.json, packages/amplify-cli/src/__tests__/test-aborting.test.ts, packages/amplify-cli/src/version-notifier.ts, yarn.lock
- update update-notifier package version
=> fix: updates updateNotifier version

packages/amplify-cli/package.json, packages/amplify-cli/src/__tests__/test-aborting.test.ts, packages/amplify-cli/src/version-notifier.ts, yarn.lock
Reverts aws-amplify/amplify-cli#10691
=> Revert "fix: updates updateNotifier version"

.circleci/config.base.yml, package.json, scripts/tag-rc.sh
This updates the dev:publish script so that the rc candidate is tagged with the correct semver version.
=> chore: update script for rc

.circleci/config.base.yml, CONTRIBUTING.md, package.json
Removes the remaining references to `master`.
=> chore: remove references to master

packages/amplify-appsync-simulator/package.json
Adds the public package config to appsync-simulator as a scoped package.
=> chore: make package public

packages/amplify-cli/src/__tests__/serializable-error.test.ts, packages/amplify-cli/src/domain/amplify-usageData/SerializableError.ts
=> feat: redacted error trace

packages/amplify-util-uibuilder/package.json, yarn.lock
Reverts aws-amplify/amplify-cli#10766 due to failures: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/9744/workflows/28e4d18c-ea66-4a5a-8a56-7b9a78262c6e
=> Revert "fix(uibuilder): change recommended ui-react version"

packages/amplify-provider-awscloudformation/src/admin-login.ts
- handle undefined exception logging in admin login
=> chore: handle undefined exception logging in admin login

scripts/release-rc.sh
Fixes an typo in the release script that will raise an error because looking for a missing argument. 
=> chore: fix typo in release script to use correct var name

.circleci/publish.sh
=> chore: fix release script to run correct publish script

package.json, yarn.lock
=> chore: bump got to ^11.8.5

package.json, yarn.lock
=> chore: bump undici to ^5.8.0

.circleci/local_publish_helpers.sh, scripts/tag-rc.sh
Update tag, create pkg, and upload pkg scripts to execute on all RC branches
=> chore: fix scripts on rc branches

package.json
Changes post release script to push release commit to `release` branch after publish.
=> chore: update post publish script

package.json, scripts/finish-release.sh, scripts/release-rc.sh
Pauses the local release scripts at steps that require resolving merge conflicts. Also changes the behavior of the `finish-release.sh` script to open a compare link rather than a pull request for sanity checking the merge
=> chore: qol improvements to local release scripts

packages/amplify-console-hosting/src/utils/config-utils.js, packages/amplify-provider-awscloudformation/src/amplify-service-migrate.js
Fixes a couple issues with the TPI refactor PR that were caught by the console integ tests.
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/10278/workflows/6b0412f3-d069-4038-8e80-8676a7cfb1f3/jobs/333968/steps
Ran the tests locally
=> fix: bugs in TPI refactor caught by console integ tests

.circleci/local_publish_helpers.sh
Makes a couple fixes to the script that assumes child account credentials during test runs:
1. If some part of assuming the child account fails, we fall back to the parent account instead of failing
2. The parent account is filtered out of the list-accounts call -- this caused failures when the parent account tried to assume a role in itself
3. cleaned up the logical flow a bit and broke some of the nested commands into a few different lines
Various test failures
Ran script locally, E2E running at https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e/foyleef/assume-role-fix
=> test: improvements to assume child acct script

packages/amplify-cli/src/__tests__/usage-data.test.ts, packages/amplify-cli/src/context-manager.ts, packages/amplify-cli/src/domain/amplify-usageData/NoUsageData.ts, packages/amplify-cli/src/domain/amplify-usageData/UsageData.ts, packages/amplify-cli/src/domain/amplify-usageData/UsageDataPayload.ts, packages/amplify-cli/src/domain/amplify-usageData/UsageDataTypes.ts, packages/amplify-cli/src/domain/amplify-usageData/index.ts, packages/amplify-cli/src/execution-manager.ts, packages/amplify-cli/src/extensions/amplify-helpers/push-resources.ts, packages/amplify-cli/src/initialize-env.ts, packages/amplify-cli/tsconfig.json
Fixing lint errors before making changes to usage data code
`yarn test`
=> chore: usage data lint fixes

packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/generate-auth-trigger-template.ts
Bumps nested auth lambda trigger runtime to node 14. Also includes some lint updates
fixes: https://github.com/aws-amplify/amplify-cli/issues/10887
E2E suite running here: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e/foyleef/node-runtime-bump
=> chore: bump auth lambda trigger runtime to node 14

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, yarn.lock
Upgrade codegen dependency version via `ncu --deep --upgrade --filter "amplify-codegen" && yarn`
N/A
Unit tests, will run e2e tests as well. e2e tests available here https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e%2Falharris%2Fupdate-codegen-version-sep-2
=> chore: update codegen dependency

packages/amplify-cli-core/src/cfnUtilities.ts, packages/amplify-provider-awscloudformation/src/__tests__/initializer.test.ts, packages/amplify-provider-awscloudformation/src/__tests__/pre-push-cfn-processor/cfn-pre-processor.test.ts, packages/amplify-provider-awscloudformation/src/__tests__/resource-package/resource-export.test.ts, packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/__snapshots__/root-stack-transform.test.ts.snap, packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/root-stack-transform.test.ts, packages/amplify-provider-awscloudformation/src/initializer.ts, packages/amplify-provider-awscloudformation/src/pre-push-cfn-processor/cfn-pre-processor.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts, packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-builder.ts, packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-transform.ts, packages/amplify-provider-awscloudformation/src/root-stack-builder/stack-synthesizer.ts, packages/amplify-provider-awscloudformation/src/template-description-utils.ts
- Use `JSONUtilities.stringify` instead of `JSON.stringify` when rendering CloudFormation to support minification
- Various lint fixes
Fixes https://github.com/aws-amplify/amplify-cli/issues/10479
`yarn test` and will run the e2e tests before merging
=> fix: support for minify flag in CFNUtilities

packages/amplify-environment-parameters/package.json
Bump `amplify-cli-core` to `3.0.0` in the `amplify-environment-parameters` package.
=> chore: ensure the same version of amplify-cli-core is used

packages/amplify-cli-npm/index.ts
Getting the version of the `cli-internal` package back in sync with the `cli-npm` package.
Because an rc release commit made it back into the git history on the dev branch, this threw off the version computation for future versions. This commit forces it back in sync.
Ran `lerna version` locally and verified that it produced the same version bump for the npm and internal package
=> feat: force minor version bump

packages/amplify-provider-awscloudformation/src/initializer.ts
Merging to tagged release branch, not dev
Tested manually
=> feat: allow overriding name of IAM role names before init

packages/amplify-category-auth/src/provider-utils/awscloudformation/index.js, packages/amplify-e2e-core/src/init/amplifyPull.ts, packages/amplify-e2e-tests/src/__tests__/auth_2.test.ts
Resolve environment specific parameters when `--yes` flag is present during `amplify pull`
Fixes https://github.com/aws-amplify/amplify-cli/issues/11010
=> fix: headless pull with Oauth social providers

.circleci/config.base.yml
Removes duplicate scripts from the release jobs.
=> chore: removes merging to main script since it already occurs in a later script

packages/amplify-category-analytics/package.json
The analytics category was depending upon an older version of amplify-prompts
=> chore(amplify-category-analytics): bump amplify-prompts to 2.5.0

yarn.lock
Upgrade lerna.
Running `yarn test` and running integration tests to ensure there are no regressions.
=> chore: apply lerna patch 5.5.1 -> 5.5.2

packages/amplify-category-geo/src/__tests__/service-walkthroughs/geofenceCollectionWalkthrough.test.ts, packages/amplify-category-geo/src/__tests__/service-walkthroughs/mapWalkthrough.test.ts, packages/amplify-category-geo/src/__tests__/service-walkthroughs/placeIndexWalkthrough.test.ts, packages/amplify-category-geo/src/provider-controllers/geofenceCollection.ts, packages/amplify-category-geo/src/provider-controllers/index.ts, packages/amplify-category-geo/src/provider-controllers/map.ts, packages/amplify-category-geo/src/provider-controllers/placeIndex.ts, packages/amplify-category-geo/src/service-walkthroughs/removeWalkthrough.ts
Various lint error fixes and formatting fixes
`yarn test` passes
=> chore(category-geo): lint fixes

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
=> docs: add semver label tag contributing guides and pull request todo

packages/amplify-category-notifications/package.json
- update version for amplify-cli-core to fix builds
build failing on dev
- manually tested
=> chore:  update amplify-cli-core version for notifications pkg

packages/amplify-util-uibuilder/package.json, yarn.lock
- updates codegen-ui version to 2.4.0 as this version includes supports for responsive apps by
- adding breakpoint support in the theme when running `amplify pull`
- adding a hook in codegen'd components to switch between different breakpoint variants
=> feat(amplify-util-uibuilder): update codegen-ui with responsive app support

.circleci/config.base.yml
- Adding version  and commit info to github release step
```
yarn run v1.18.0
$ /home/circleci/repo/node_modules/.bin/ts-node scripts/github-release.ts
(node:88) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'trim' of undefined
at getArgs (/home/circleci/repo/scripts/github-common.ts:42:30)
at /home/circleci/repo/scripts/github-release.ts:22:38
at step (/home/circleci/repo/scripts/github-release.ts:33:23)
at Object.next (/home/circleci/repo/scripts/github-release.ts:14:53)
at /home/circleci/repo/scripts/github-release.ts:8:71
at new Promise (<anonymous>)
at __awaiter (/home/circleci/repo/scripts/github-release.ts:4:12)
at main (/home/circleci/repo/scripts/github-release.ts:21:14)
at Object.<anonymous> (/home/circleci/repo/scripts/github-release.ts:26:1)
at …
```
=> fix: error in updating github release

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, yarn.lock
* bump version of amplify-codegen to v3.2.0
N/A
N/A
=> chore: bump version of amplify-codegen to v3.2.0

packages/amplify-category-geo/src/__tests__/__snapshots__/index.test.ts.snap, packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/placeIndexStack.test.ts.snap, packages/amplify-category-geo/src/service-stacks/placeIndexStack.ts, packages/amplify-category-geo/src/service-utils/placeIndexUtils.ts
Update placeIndex read policy to include geo:getPlace
Docs PR: https://github.com/aws-amplify/docs/pull/4615
``yarn test``
=> chore(cli): update placeIndex read policy to include geo:getPlace

packages/amplify-category-notifications/src/notifications-amplify-meta-types.ts, packages/amplify-category-notifications/src/pinpoint-helper.ts
=> fix: notifications status after env checkout

packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/synthesize-resources.ts, packages/amplify-cli/package.json, packages/amplify-e2e-tests/src/__tests__/init-special-case.test.ts, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, yarn.lock
This includes hotfixes for the following:
https://github.com/aws-amplify/amplify-cli/commit/125486d8a702bebf7a8d1e9867fca7f8aaaeec38
https://github.com/aws-amplify/amplify-cli/commit/4ef1f5561ee020b4241c0bf0e076942ffb2f5af4
=> chore: cherry pick dev commits over to hotfix branch

packages/amplify-category-auth/package.json, packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.test.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/index.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/stack-synthesizer.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/user-pool-group-stack-transform.ts
- lint fixes in auth category for cdkV2
-  ;int fixes diabled are:
- // eslint-disable-next-line spellcheck/spell-checker,
- /* eslint-disable import/no-cycle */
=> chore: auth lint fixes for cdk V2

packages/amplify-category-custom/src/utils/generate-cfn-from-cdk.ts, packages/amplify-category-storage/package.json, packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/ddb-stack-builder.ts, packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/ddb-stack-transform.ts, packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-builder.ts, packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-transform.ts, packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/types.ts
lint fixes in storage category
=> chore: Storage category lint fixes

packages/amplify-cli-extensibility-helper/src/helpers/project-info.ts, packages/amplify-cli-extensibility-helper/src/types.ts, packages/amplify-cli-extensibility-helper/src/types/api/amplify-api-resource-stack-types.ts, packages/amplify-cli-extensibility-helper/src/types/api/types.ts, packages/amplify-cli-extensibility-helper/src/types/auth/types.ts, packages/amplify-cli-extensibility-helper/src/types/project/types.ts, packages/amplify-cli-extensibility-helper/src/types/storage/types.ts, packages/amplify-cli/package.json, packages/amplify-cli/src/extensions/amplify-helpers/resource-status-diff.ts, packages/amplify-provider-awscloudformation/src/network/stack.ts, packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-transform.ts, packages/amplify-provider-awscloudformation/src/root-stack-builder/stack-synthesizer.ts
Linting is removed for below files for failing unit tests 
```
- packages/amplify-provider-awscloudformation/src/__tests__/utils/consolidate-apigw-policies.test.ts
- packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/root-stack-builder.test.ts
- packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-builder.ts
- packages/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts
```
=> chore: lint fixes in provider and npm package

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, yarn.lock
* execute `yarn update-data-dependencies` to bump codegen version.
* Expose `getModelIntrospection` plugin method call for ui helper.
N/A
Studio UI team has validated that `getModelIntrospection` plugin method works as expected with a tagged release.
=> chore: execute yarn update-data-dependencies

packages/amplify-cli-core/resources/overrides-resource/package.json
Fixes https://github.com/aws-amplify/amplify-cli/issues/11253
#11253
=> fix: override dependency for auth

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, yarn.lock
bump version of amplify-codegen to v3.3.1
See https://github.com/aws-amplify/amplify-codegen/pull/500
=> chore: bump version of amplify-codegen to v3.3.1

packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/trigger-file-uploader.ts
=> chore: fix AmplifyError build error

packages/amplify-category-analytics/src/provider-utils/awscloudformation/index.ts, packages/amplify-e2e-tests/src/__tests__/analytics-2.test.ts
- fixes incorrect parameters in analytics getPermissionPolicies signature
- manual tests
- e2e test added
=> fix: add function access to analytics

packages/amplify-category-function/src/provider-utils/awscloudformation/utils/cronExpression.ts
=> fix: fix typo in cronExpression.ts

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/question-factories/core-questions.test.js, packages/amplify-category-auth/src/provider-utils/awscloudformation/question-factories/core-questions.js
#11299 
ran through the CLI prompts
- [n/a] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
=> chores(amplify-category-auth): signinwithapple fix

packages/amplify-cli-npm/index.ts
no op feat commit to force version bump
=> feat: no op version bump

packages/amplify-cli-core/src/errors/project-not-initialized-error.ts
Change reference to Amplify Admin UI to Amplify Studio
=> fix: change reference to Amplify Admin UI to Amplify Studio

packages/amplify-cli/package.json, packages/amplify-container-hosting/package.json, packages/amplify-graphql-migration-tests/package.json, packages/amplify-util-mock/package.json, yarn.lock
Hotpatch 
N/A
Running e2e tests, and generating a tagged release for manual smoke testing.
Tagged release can be pulled (once deployed) by running `npm i -g @aws-amplify/cli@update-data-dependencies-hotpatch-2`
=> chore: hotpatch commit for data hotpatch

packages/amplify-category-geo/resources/custom-device-location-tracking-resource-handler.js, packages/amplify-category-geo/resources/custom-geofence-collection-resource-handler.js, packages/amplify-category-geo/src/__tests__/service-walkthroughs/deviceLocationTrackerWalkthrough.test.ts, packages/amplify-category-geo/src/provider-controllers/deviceLocationTracking.ts, packages/amplify-category-geo/src/provider-controllers/index.ts, packages/amplify-category-geo/src/service-utils/deviceLocationTrackingUtils.ts, packages/amplify-category-geo/src/service-walkthroughs/deviceLocationTrackingWalkthrough.ts, packages/amplify-e2e-core/src/categories/geo.ts, packages/amplify-e2e-tests/src/__tests__/geo-add-g.test.ts, packages/amplify-e2e-tests/src/__tests__/geo-remove-3.test.ts, packages/amplify-e2e-tests/src/__tests__/geo-update-2.test.ts, packages/amplify-e2e-tests/src/__tests__/geo-update-3.test.ts, packages/amplify-frontend-android/lib/amplify-config-helper.js, packages/amplify-frontend-android/tests/__snapshots__/amplify-config-helper.test.js.snap, packages/amplify-frontend-android/tests/amplify-config-helper.test.js, packages/amplify-frontend-ios/lib/amplify-config-helper.js, packages/amplify-frontend-ios/tests/__snapshots__/amplify-config-helper.test.js.snap, packages/amplify-frontend-ios/tests/amplify-config-helper.test.js
- Added walkthrough for updating a tracker
- Added walkthrough for removing a tracker
- added e2e tests
- Passing tests in cloud-e2e
- https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/12383/workflows/20d15341-ee98-4d8f-8756-5e105d8aef30/jobs/471158
- https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/12383/workflows/20d15341-ee98-4d8f-8756-5e105d8aef30/jobs/471017
- https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/12383/workflows/20d15341-ee98-4d8f-8756-5e105d8aef30/jobs/471250
=> feat(geo): Added walkthrough for Update tracker and Remove tracker

yarn.lock
Updates the lockfile to match dependencies that were upgraded in https://github.com/aws-amplify/amplify-cli/pull/11343
=> fix: update yarn lock to match specified dependencies

scripts/update-data-dependencies.sh
I made these changes to make supporting the `feature/rds-support` branch a bit easier. Change is already present there.
N/A
Tested on the `feature/rds-support` branch where the package.json file specifies the tag to use.
https://github.com/aws-amplify/amplify-cli/blob/feature/rds-support/package.json#L49
=> chore: update update-data-dependencies.sh script to allow for bumping to a tag version

packages/amplify-util-uibuilder/src/commands/utils/notifyMissingPackages.ts
I changed required and requires to require in the "pull" warning message to make it grammatically correct.
[11397](https://github.com/aws-amplify/amplify-cli/issues/11397)
I ran yarn-test. This is just a change to a print-out.
=> fix(cli): fix grammar in pull warning message

.circleci/config.base.yml, .circleci/local_publish_helpers.sh, .circleci/publish.sh
**This PR solves the following:**
- Builds all binaries in every build including pull requests. I.e. this can be caught earlier than in e2e tests https://github.com/aws-amplify/amplify-cli/pull/11371 .
- It verifies all binaries sizes against hardcoded threshold.
- Parallelizes binary builds, so it's no longer needed to skip some to save time. And to make sure PR build time is kept same.
**PR validation**
Before:
After:
**E2E tests**
Before:
After:
**Verification step**
=> chore: add binary validation in all builds

packages/amplify-cli/package.json, packages/amplify-e2e-tests/src/__tests__/__snapshots__/studio-modelgen.test.ts.snap, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, yarn.lock
Add hardcoded modelName change for dart modelgen.
Full changelog: https://github.com/aws-amplify/amplify-codegen/releases/tag/amplify-codegen%403.3.3
=> chore: bump amplify codegen to 3.3.3

scripts/finish-release.sh
=> chore: fix merge commit message in finish release script

.circleci/config.base.yml, .circleci/config.yml, packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts, scripts/split-e2e-tests.ts
Currently, our E2E tests execute using Linux VM - Large instances, but we only utilize about 33% CPU/RAM on average.
This updates our E2E to use medium executors for all of our E2E jobs - except those where CPU is important, such as our build/integtests/buildPkgBinaries jobs.
This will hopefully reduce our costs by about 50%, from 200k credits per run, to 100k credits per run.
I have also addressed a possible concern that some tests might require more resources. For those tests, we can simple add them to an exception list, so that they get to use the Large instances.
E2E Runs: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e%2Faluja%2Freduce-ci-costs
(all tests pass, geo-update is flaky on all other branches as well)
Here are the results of some of the most …
=> fix: resource usage cost

.circleci/config.base.yml, .github/ISSUE_TEMPLATE/1.bug_report.yaml, .github/ISSUE_TEMPLATE/2.feature_request.yaml, packages/amplify-e2e-tests/src/__tests__/schema-iterative-update-4.test.ts
=> chore: merge dev to cdkv2

packages/amplify-cli-npm/index.ts
Force a minor version bump in the cli-npm package to get cli-npm and cli-internal versions back in sync
=> feat: force minor version bump in cli-npm package

packages/amplify-category-auth/CHANGELOG.md, packages/amplify-category-auth/package.json, packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/handlers/resource-handlers.test.ts, packages/amplify-category-auth/src/provider-utils/awscloudformation/handlers/resource-handlers.ts, packages/amplify-cli-npm/CHANGELOG.md, packages/amplify-cli-npm/package.json, packages/amplify-cli/CHANGELOG.md, packages/amplify-cli/package.json, packages/amplify-e2e-tests/CHANGELOG.md, packages/amplify-e2e-tests/package.json
=> Dev main merge

packages/amplify-category-notifications/src/multi-env-manager.ts, packages/amplify-category-notifications/src/notifications-amplify-meta-api.ts, packages/amplify-e2e-core/src/init/amplifyPull.ts, packages/amplify-e2e-tests/src/__tests__/notifications-sms-pull.test.ts, packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts, packages/amplify-migration-tests/src/__tests__/migration_tests/notifications-migration/notifications-migration-4.test.ts, packages/amplify-migration-tests/src/migration-helpers/notifications-helpers.ts, scripts/split-e2e-tests.ts
making a hotfix with a cherry-picked commit
fixes #9955 #11376
=> fix: pull project with removed notifications

.circleci/config.base.yml
Added version verification step in CircleCI as a dependency of the deploy step.
Can not validate changes until next release.
=> fix: add version verification as dependency of deploy

packages/amplify-e2e-core/src/init/amplifyPush.ts, packages/amplify-e2e-core/src/init/initProjectHelper.ts
- removes an unused e2e helper method
=> chore: removes unused e2e helper method

packages/amplify-cli-logger/src/Redactor.ts, packages/amplify-cli-logger/src/__tests__/Redactor.test.ts
Updates the redactor used when uploading diagnose assets to also look for the word "secret" in files before uploading
Manually validated and updated the existing unit test
=> fix: update redactor scanning logic

packages/amplify-category-geo/src/__tests__/service-utils/mapParams.test.ts, packages/amplify-category-geo/src/service-utils/mapParams.ts, packages/amplify-category-geo/src/service-utils/resourceParams.ts, packages/amplify-category-geo/src/service-walkthroughs/mapWalkthrough.ts, packages/amplify-headless-interface/API.md, packages/amplify-headless-interface/schemas/geo/1/AddGeoRequest.schema.json, packages/amplify-headless-interface/src/interface/geo/add.ts
- New map styles were added.
- "VectorOpenDataStandardLight"
https://github.com/aws-amplify/amplify-cli/issues/11620
=> feat(category-geo): add new map style 2022.12

.editorconfig, .eslintrc.js, .vscode/settings.json, package.json, packages/amplify-opensearch-simulator/API.md, yarn.lock
Updated linting rules. Removed most custom rules. Relaxed some linting rules on test files.
The project was rebuilt from a clean state with a clean yarn cache. As there are already linting violations in the current codebase, this PR should not represent a meaningful change to developer workflow.
=> feat: more focused linting rules

packages/amplify-migration-tests/src/__tests__/migration_tests_v10/__snapshots__/geo.migration.test.ts.snap, packages/amplify-migration-tests/src/__tests__/migration_tests_v10/geo.migration.test.ts, packages/amplify-migration-tests/src/__tests__/migration_tests_v10/storage.migration.test.ts, packages/amplify-migration-tests/src/migration-helpers/check-version.ts, packages/amplify-migration-tests/src/migration-helpers/utils.ts, scripts/split-e2e-test-filters.ts, scripts/split-e2e-tests.ts
=> chore: add geo migration test

yarn.lock
=> chore: fix undici dependency warnings

.github/workflows/dependency-review.yml, yarn.lock
This PR adds dependency scan on each PR in order to prevent introduction of vulnerable dependencies. This shortens existing feedback loop, i.e. we'll get failed check before we even merge code.
References:
https://stackoverflow.com/questions/71068152/how-to-trigger-dependabot-scan-on-developer-pull-requests
https://github.blog/changelog/2022-04-06-github-action-for-dependency-review-enforcement/
**Happy case**
**Failure injection.**
=> chore: add dependency scan on PR

packages/amplify-cli/src/commands/helpers/projectUtils.ts
chore: updated the resolution for nested project error
=> chore: update resolution message for nested project init errors

packages/amplify-util-uibuilder/src/commands/utils/detachedFormCleanup.ts, packages/amplify-util-uibuilder/src/commands/utils/syncAmplifyUiBuilderComponents.ts, packages/amplify-util-uibuilder/src/utils/prePushHandler.ts
Some light refactoring based on feedback from a previous PR.
=> chore: code cleanup - renaming args, removing repetitive try catch

packages/amplify-cli/src/commands/env/remove.ts
Call `invokeDeleteEnvParamsFromService` upon removing an environment to delete environment parameters from PS.
=> feat: delete parameters from ps upon remove env

package.json
Removes api extract pre-push hook
=> chore: remove verify-api pre-push hook

packages/amplify-category-analytics/src/provider-utils/awscloudformation/service-walkthroughs/kinesis-walkthrough.ts
- changed prompt to match failing test string 
=> chore: Kinesis e2e fix

packages/amplify-provider-awscloudformation/src/utils/upload-env-parameters.ts
Ensure only `standard` parameters are used.
=> fix: ensure standard parameters

package.json, packages/amplify-category-analytics/API.md, packages/amplify-category-function/API.md, packages/amplify-category-function/src/index.ts, packages/amplify-category-function/src/provider-utils/awscloudformation/secrets/ssmClientWrapper.ts, packages/amplify-category-geo/src/provider-controllers/import.ts, packages/amplify-cli-core/API.md, packages/amplify-e2e-core/src/categories/auth.ts, packages/amplify-e2e-tests/src/__tests__/function_3b.test.ts, packages/amplify-e2e-tests/src/import-helpers/settings.ts, packages/amplify-e2e-tests/src/import-helpers/utilities.ts, packages/amplify-migration-tests/src/__tests__/migration_tests_v10/dotnet_runtime_update_migration.test.ts, packages/amplify-opensearch-simulator/API.md, packages/amplify-prompts/API.md, packages/amplify-prompts/src/prompter.ts, yarn.lock
- Update TS dependency to latest
- Consolidate TS dependencies in `yarn.lock`
- Address newly flagged type errors
=> chore: upgrade typescript

package.json, yarn.lock
- Upgrade lerna to latest ^6.x ([CHANGELOG](https://github.com/lerna/lerna/blob/main/CHANGELOG.md))
- Remove direct dependency on nx since it's included with lerna
yarn dev-build and yarn test succeed 
=> chore: upgrade lerna to latest

packages/amplify-category-notifications/src/__tests__/notifications.test.ts, packages/amplify-category-notifications/src/notifications-amplify-meta-api.ts
- fix notification channel enabled check
- manual tests
- added unit test
=> fix: notification channel enabled check

packages/amplify-e2e-core/src/configure/index.ts, packages/amplify-e2e-tests/src/__tests__/amplify-configure.test.ts, packages/amplify-migration-tests/package.json, packages/amplify-migration-tests/src/configure_tests.ts, packages/amplify-provider-awscloudformation/src/__tests__/setup-new-user.test.ts, packages/amplify-provider-awscloudformation/src/constants.js, packages/amplify-provider-awscloudformation/src/setup-new-user.ts
Updates the create user workflow to link to the IAM console v2 and our docs describing how to create the user.
Manually validated that the links and flow works as expected. Updated unit tests
Corresponding docs PR: https://github.com/aws-amplify/docs/pull/5078
E2E Run: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e/foyleef/user-creation
=> chore: update user creation flow links with IAM v2 console

packages/amplify-cli-core/src/help/help-helpers.ts, packages/amplify-cli/src/display-banner-messages.ts
With XR category:
Without:
Manual testing.
=> fix: warn about xr deprecation

packages/amplify-cli-npm/index.ts, packages/amplify-cli/src/index.ts
=> feat: force version bump

scripts/split-e2e-tests-v2.ts
Excludes simulator tests from running on windows
=> fix: exclude simulator tests from running on windows

scripts/split-e2e-tests-v2.ts
=> test: exclude new analytics/notifications tests on windows

packages/amplify-cli/src/display-banner-messages.ts
=> chore: update xr deprecation message

packages/amplify-category-predictions/src/provider-utils/awscloudformation/prediction-category-walkthroughs/identify-walkthrough.js
=> fix: prompt grammar issue

.circleci/config.base.yml, package.json, packages/amplify-category-hosting/package.json, scripts/verify-extract-api.sh, scripts/verify-yarn-lock.sh
This adds PR verification that `yarn.lock` does not drift from package.json declarations.
https://github.com/aws-amplify/amplify-cli/pull/11941/commits/f7bf33f43b1763ab3aebdfa916a80e91b5bcf5a7
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/15659/workflows/da24d385-ca9c-4e51-9bc3-ead12ab03c6a
=> chore: verify yarn lock

packages/amplify-e2e-core/src/utils/sdk-calls.ts
Fix for test failure: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/15631/workflows/0ca2ad51-e583-481a-839e-12d9b69865f6/jobs/766504
e2e test passes locally
=> test: compare values after JSON is parsed

packages/amplify-provider-awscloudformation/src/amplify-service-manager.ts, packages/amplify-provider-awscloudformation/src/initializer.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts
Minimal lint fixes and typings required to convert `amplify-service-manager.js` to TS. No functional changes. This update is to make the diff of [this PR](https://github.com/aws-amplify/amplify-cli/pull/10839) more isolated
No functional changes. E2E running here: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e/foyleef/ts-conversion
=> chore: convert amplify-service-manager from js to ts

packages/amplify-e2e-tests/src/__tests__/__snapshots__/studio-modelgen.test.ts.snap
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/15819/workflows/42570365-0e4c-4731-844e-fb9e14ce6e09/jobs/773478/steps
=> fix: studio modelgen e2e test

CONTRIBUTING.md
Updates contributing with more detailed instructions for running unit tests.
=> chore: update contributing with more information on testing

packages/amplify-e2e-tests/src/__tests__/parameter-store.test.ts
Add e2e test to ensure TPI file is recreated in various pull scenarios
e2e test passes locally
=> test: pull parameters with and without restore flag

packages/amplify-category-notifications/src/channel-fcm.ts
This awaits a previously unawaited call to the pinpoint sdk.
=> fix: await pinpoint response

packages/amplify-cli-npm/CHANGELOG.md, packages/amplify-cli-npm/index.ts, packages/amplify-cli-npm/package.json, packages/amplify-cli/CHANGELOG.md, packages/amplify-cli/package.json, packages/amplify-cli/src/index.ts, packages/amplify-container-hosting/CHANGELOG.md, packages/amplify-container-hosting/package.json
=> chore: dev main merge

packages/amplify-cli/package.json, packages/amplify-container-hosting/package.json, packages/amplify-graphql-migration-tests/package.json, packages/amplify-util-mock/package.json, yarn.lock
chore: bump api category deps for rc
N/A
e2es and additional tests in data repo
e2e test suite: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/16051/workflows/8d4cfecf-3997-4553-a765-b3e59b33d064
=> chore: bump deps for rc

packages/amplify-cli/package.json, packages/amplify-container-hosting/package.json, packages/amplify-graphql-migration-tests/package.json, packages/amplify-util-mock/package.json, yarn.lock
chore: bump api category deps for dev branch
e2es and additional tests in data repo
e2e test suite: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/16047/workflows/40ce1edf-efaa-4a1e-aab1-4d80638fdf8e
=> chore: bump api category deps

.prettierrc, .vscode/settings.json, package.json, yarn.lock
Add prettier settings to .prettierrc and reference them from the vscode settings file.
=> fix: explicitly define prettier config options

.circleci/config.base.yml, .prettierignore, packages/amplify-container-hosting/resources/express-template/public/index.html
This PR:
- fails build if formatting is not kept up to standard see https://prettier.io/docs/en/cli.html#--check 
- ignores couple of files where not keeping standard is justified
Error mode:
=> chore: enforce prettier

.github/workflows/closed-issue-message.yml, package.json
…pt to compare branch with dev
Fixes misformatted code. Fixes prettify script to run prettier on all files changed compared to dev.
=> chore: fixed linting issue that got into dev. Fix prettify:changes script.

Readme.md
Removes the enhancement badge from the readme since we no longer use that label
=> Remove enhancement badge from readme

packages/amplify-provider-awscloudformation/src/disconnect-dependent-resources/utils.ts
- handle the case where StackResources is empty or undefined and print a better message than `'Cannot read property 'PhysicalResourceId' of undefined'`
=> fix: handle fault for function stack not found in stack resources

.github/codeql/codeql-config.yml, .github/workflows/codeql.yaml
=> chore: ignore tests in codeql scan

.circleci/publish.sh
Fixes the publish script to properly expand args with spaces (such as commit messages in this case)
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/16747/workflows/6b3acd66-6098-4b7f-afa7-2230a49c4153/jobs/813645
ssh-ed into failed job, modified script and reran it
=> chore: properly expand args in publish script

packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts
Fixes 
Ran change locally with test account parent.
=> chore: fix cleanup script

packages/amplify-e2e-tests/src/__tests__/parameter-store-1.test.ts, packages/amplify-e2e-tests/src/__tests__/parameter-store-2.test.ts, scripts/split-e2e-tests-v2.ts
=> test: split e2e test file

package.json, packages/amplify-cli/src/domain/amplify-usageData/NoUsageData.ts, packages/amplify-cli/src/domain/amplify-usageData/VersionManager.ts, packages/amplify-graphql-migration-tests/src/test-case-registry.ts, packages/amplify-provider-awscloudformation/src/graphql-resource-manager/amplify-graphql-resource-manager.ts, packages/amplify-provider-awscloudformation/src/graphql-resource-manager/utils.ts, packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-builder.ts, packages/amplify-provider-awscloudformation/src/root-stack-builder/stack-synthesizer.ts, packages/amplify-provider-awscloudformation/src/setup-new-user.ts, packages/amplify-python-function-template-provider/src/index.ts, packages/amplify-util-mock/src/CFNParser/intrinsic-functions.ts, packages/amplify-util-mock/src/CFNParser/resource-processors/appsync.ts, packages/amplify-util-mock/src/CFNParser/resource-processors/iam.ts, packages/amplify-util-mock/src/CFNParser/resource-processors/opensearch.ts, packages/amplify-util-mock/src/__tests__/CFNParser/intrinsic-functions.test.ts, packages/amplify-util-mock/src/api/api.ts, packages/amplify-util-mock/src/api/lambda-trigger-handler.ts, packages/amplify-util-mock/src/api/resolver-overrides.ts
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e%2Fsobkamil%2Fno-unused-vars-2
=> chore: address some of no-unused-vars

packages/amplify-console-hosting/src/utils/table-utils.js
I've added import of singleton spinner from cli core, in order not to create a new ora spinner that blocks the mfa input
below is the output of `amplify status`
Before:
After:
Manual testing + `yarn test`
=> fix: display mfa prompt during hosting domains fetching

packages/amplify-provider-awscloudformation/src/__tests__/utils/resolve-appId.test.ts
I had initially added logic to the resolveAppId function, but decided to revert the changes.
This PR brings the minor simplifications I made to the existing unit tests.
Ran unit test locally
=> test: simplify unit test mocks for resolveAppId()

packages/amplify-console-hosting/src/hosting/index.js, packages/amplify-console-hosting/src/hosting/manual/publish.js, packages/amplify-console-hosting/src/utils/amplify-console-utils.js
Extension of a contributor's PR #12175 
- [x PR description included
- [n/a] Relevant documentation is changed or added (and PR referenced)
- [n/a] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [n/a] [Pull request labels](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#labels) are added
=> chore: switching from ora to cli-core spinner

packages/amplify-cli/src/extensions/amplify-helpers/push-resources.ts
update error details in AmplifyFault during category push
N/A
N/A
=> fix: update error details in AmplifyFault during category push

packages/amplify-cli-core/src/__tests__/help.test.ts, packages/amplify-cli-core/src/help/commands-info.ts
- improves usage by adding all options
- adds a few flags like `--debug`, `--appId`, `--envName`
- minor spelling correction(s)
- removes duplicate `push` subcommand entries for categories
n/a, but this will enable docs generation
=> chore: improve cli help usage docs, add/rm flags

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, yarn.lock
=> update codegen to 3.4.0

scripts/finish-release.ts
Handles the error thrown by `simple-git`'s when attempting to merge when there are conflicts.
=> chore: handle simple-git merge error

packages/amplify-e2e-tests/custom-resources/custom-cdk-stack-with-storage.ts, packages/amplify-e2e-tests/src/__tests__/custom-resource-with-storage.test.ts
=> fix: broken build

packages/amplify-e2e-tests/custom-resources/custom-cdk-stack-with-storage.ts
=> fix: fix failing custom storage e2e test

packages/amplify-e2e-core/src/categories/custom.ts, packages/amplify-e2e-tests/custom-resources/custom-cdk-stack-with-storage.ts, packages/amplify-e2e-tests/custom-resources/custom-cdk-stack.ts, packages/amplify-migration-tests/custom-resources/custom-cdk-stack-v10.ts, packages/amplify-migration-tests/custom-resources/custom-cdk-stack-vLatest.ts, packages/amplify-migration-tests/src/__tests__/migration_tests_v10/custom-stack.migration.test.ts
Fix custom resources tests.
- fix migration test CFN resource prompt reaction
- remove names from custom stacks to avoid conflicts in case cleanup is skipped
=> fix: custom resource tests

packages/amplify-cli-npm/CHANGELOG.md, packages/amplify-cli-npm/package.json, packages/amplify-cli/CHANGELOG.md, packages/amplify-cli/package.json, packages/amplify-migration-tests/CHANGELOG.md, packages/amplify-migration-tests/package.json, packages/amplify-provider-awscloudformation/CHANGELOG.md, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/CHANGELOG.md, packages/amplify-util-mock/package.json
Release PR for dev-main-merge-ae2012145.
This PR merges main into dev.
=> chore(release): Merge main into dev

packages/amplify-provider-awscloudformation/src/admin-modelgen.ts
Fixes https://github.com/aws-amplify/amplify-studio/issues/866 
=> fix: generate model introspection regardless of studio

.circleci/config.base.yml
=> chore: use small executor at wait step

packages/amplify-util-uibuilder/package.json, yarn.lock
**Bug Fixes**
clear button on create form should reset select field (https://github.com/aws-amplify/amplify-codegen-ui/issues/939) ([326b579](https://github.com/aws-amplify/amplify-codegen-ui/commit/326b579b558bf19b04cf8deb7a85f8eeccc7f189))
make operandType more generic (https://github.com/aws-amplify/amplify-codegen-ui/issues/933) ([19bc806](https://github.com/aws-amplify/amplify-codegen-ui/commit/19bc806c43a0b230dc94423e3007e28cc5e3da17))
nested json array text field doesn't update (https://github.com/aws-amplify/amplify-codegen-ui/issues/948) ([bf95b98](https://github.com/aws-amplify/amplify-codegen-ui/commit/bf95b98d47c75aad75f3e229f0f7e103110d32bd))
**Features**
add optional or required decorator on form labels (https://github.com/aws-amplify/amplify-codegen-ui/issues/936) …
=> fix(amplify-util-uibuilder): update codegen-ui to 2.11.0

packages/amplify-category-storage/src/provider-utils/awscloudformation/index.ts, packages/amplify-console-hosting/src/hosting/cicd/enable.js, packages/amplify-console-hosting/src/hosting/cicd/index.js, packages/amplify-console-hosting/src/hosting/cicd/initEnv.js, packages/amplify-console-hosting/src/hosting/index.js, packages/amplify-console-hosting/src/hosting/manual/enable.js, packages/amplify-console-hosting/src/hosting/manual/index.js, packages/amplify-console-hosting/src/hosting/manual/initEnv.js, packages/amplify-console-hosting/src/hosting/manual/publish.js, packages/amplify-console-hosting/src/utils/amplify-context-utils.js, packages/amplify-console-hosting/src/utils/config-utils.js, packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js
Enabled eslint for all files temporarily to specifically target no-floating-promises lint rule.
Also tighten the `eslint-disabled` rule on few javascript files
N/A
e2e tests
=> fix: all floating promises

.yarnrc, CONTRIBUTING.md, scripts/verify-yarn-lock.sh, yarn.lock
- use npm registry
- add validation to assure we don't resolve yarnpkg
- update to contribution guide.
=> chore: use npm registry

packages/amplify-provider-awscloudformation/src/__tests__/print-cdk-migration-warning.test.ts, packages/amplify-provider-awscloudformation/src/print-cdk-migration-warning.ts, packages/amplify-provider-awscloudformation/src/push-resources.ts
-catching the detector error if it fails
=> fix: throws a warning for detector

.yarnrc
Executed
```
$ yarn policies set-version
Resolving latest to a url...
Downloading https://github.com/yarnpkg/yarn/releases/download/v1.22.19/yarn-1.22.19.js...
Saving it into /Users/sobkamil/git/amplify-cli/.yarn/releases/yarn-1.22.19.js...
Updating /Users/sobkamil/git/amplify-cli/.yarnrc...
Done!
```
per https://classic.yarnpkg.com/en/docs/cli/policies/#toc-policies-set-version
=> chore: upgrade yarn

packages/amplify-provider-awscloudformation/src/__tests__/system-config-manager.test.ts, packages/amplify-provider-awscloudformation/src/system-config-manager.ts
- fixes sso type configuration
- manual tests
=> fix: sso login

packages/amplify-console-integration-tests/src/consoleHosting/utils.ts, packages/amplify-e2e-core/src/categories/hosting.ts, scripts/cci-workflow-results.ts
Upgrade react scripts used in e2e tests to `5.0.1`.
The `4.x` line is EOL at this time and it has dependencies that don't work on latest Ubuntu due to SSL1.1 deprecation.
Plus bonus fix of one of cci scripts.
Extensive e2e testing on other branch. https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e%2Fsobkamil%2Fbump-pkg-node
=> chore: bump create-react-app scripts

codebuild_specs/build_image.yml
This is a starting point for the image build pipeline
=> ci: add build image yml

codebuild_specs/base.yml, codebuild_specs/build_pkg_binaries_arm.yml, codebuild_specs/build_pkg_binaries_macos.yml, codebuild_specs/build_pkg_binaries_win.yml, codebuild_specs/mock_e2e_tests.yml, codebuild_specs/run_e2e_tests_linux.yml, codebuild_specs/run_e2e_tests_win.yml, codebuild_specs/test.yml, codebuild_specs/upload_pkg_binaries.yml, codebuild_specs/verify_versions_match.yml, shared-scripts.sh
=> ci: amplify cli install support

Dockerfile, codebuild_specs/build_image.yml, rename_to_fetched.sh, scripts.sh
=> chore: update docker to copy node binaries

Dockerfile
=> ci: fix pathing for pkg cache

scripts/split-e2e-tests-v2.ts
- exclude an auth test for windows 
- tested manually
=> chore: exclude auth test on windows

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, packages/amplify-util-uibuilder/package.json, yarn.lock
bumping codegen dependencies to catch amplify-cli-core dependencies changes
- [] `yarn test` passes
=> chore: bump codegen deps

packages/amplify-e2e-tests/src/__tests__/__snapshots__/studio-modelgen.test.ts.snap
=> fix: codegen version in snapshots

codebuild_specs/e2e_workflow.yml, codebuild_specs/pr_workflow.yml
Breaks down workflows into respective buildspec files. Needs to map 1:1 with different CodeBuild job. This needs to be paired with CodeBuild changes. Further investigation should be done to see if we can inject .yml code from base into separate jobs.
When a PR is made with dev as the main branch, kick off PR workflow (different from e2e workflow).
- [n/a] `yarn test` passes
- [n/a] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [n/a] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
=> chore: add two new workflows

packages/amplify-category-auth/resources/adminAuth/admin-auth-package.json, packages/amplify-category-notifications/package.json, yarn.lock
=> chore: update yarn

packages/amplify-category-auth/package.json, packages/amplify-category-storage/package.json, packages/amplify-provider-awscloudformation/package.json, yarn.lock
Update `vm2` dependency to ^3.9.16
=> chore: update vm2 to ^3.9.16

Dockerfile, codebuild_specs/build_image.yml
Adding dependencies required for testing that existed in circle ci image.
=> install additional tools to testing image

packages/amplify-category-interactions/src/provider-utils/awscloudformation/cloudformation-templates/lex-cloudformation-template.json.ejs, packages/amplify-category-interactions/src/provider-utils/awscloudformation/function-template-dir/index.js.ejs
This PR makes interactions lambdas run on node 18.
E2E tests.
=> feat: run interactions lambda on nodejs18

packages/amplify-e2e-tests/src/__tests__/delete.test.ts
=> test: fix e2e test

packages/amplify-category-auth/resources/adminAuth/admin-auth-cognitoActions.js, packages/amplify-category-auth/resources/adminAuth/admin-auth-package.json, packages/amplify-category-auth/resources/adminAuth/admin-queries-function-template.json.ejs
This PR makes admin app run on node18.
=> chore: run admin app on node18

packages/amplify-e2e-core/src/utils/envVars.ts
Missed [one commit](https://github.com/aws-amplify/amplify-cli/pull/11790) on last merge from main into dev. This should fix most of the new e2e test failures.
=> chore: fix failing e2e tests

packages/amplify-e2e-tests/src/schema-api-directives/tests/predictions-usage.ts
[Failing e2e test related to S3 change](https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/19362/workflows/4a6d45f1-a6b8-489d-afae-ddfa91fb4dfb/jobs/928962), this will permit us to get meaningful feedback from the test while accounting for S3 bucket permission changes.
yarn test, e2e test run
=> chore: modify failing e2e test

scripts/split-e2e-tests-v2.ts
add hooks-c e2e to windows exclusion list
Failing e2e example: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/19482/workflows/99bc9a86-9e15-4f46-bbef-4cb6596a1da9/jobs/933282
=> test: add hooks-c e2e to windows exclusion list

packages/amplify-e2e-tests/package.json, packages/amplify-e2e-tests/src/__tests__/smoketest.test.ts, scripts/split-e2e-tests-v2.ts
=> Run smoketests with e2e

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, packages/amplify-util-uibuilder/package.json, yarn.lock
Update Codegen version to 4.0.0.
=> chore(codegen): update codegen version to 4.0.0

packages/amplify-category-storage/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.test.ts, packages/amplify-cli-core/src/types.ts
Updates $TSContext type to reflect that [getResourceStatus](https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-cli/src/extensions/amplify-helpers/resource-status-data.ts#L159) is an async function
=> chore: update TSContext type

packages/amplify-frontend-javascript/CHANGELOG.md
noticed this while doing a dev/cb diff
=> chore: cleanup missed file

packages/amplify-cli-npm/index.ts, packages/amplify-cli/src/index.ts
=> fix: version bump

packages/amplify-category-hosting/index.js
remove link to issue that was not really informative to solve this issue.
Closes #12591 
=> chore: provide better mitigation steps for hosting error

CONTRIBUTING.md
This section is no longer relevant. We fixed lint warnings and enforce it at build now.
=> chore: remove lint section from contributing.md

packages/amplify-util-mock/src/utils/lambda/find-lambda-triggers.ts, packages/amplify-util-mock/src/utils/lambda/load-lambda-config.ts
Fix 2 random lint warnings to get us below threshold.
=> fix: lint warnings

packages/amplify-cli-npm/index.ts, packages/amplify-cli/src/index.ts
=> feat: bump version

scripts/verify-yarn-lock.sh
Check for duplicate entries with `yarn dedupe`
Can be merged after https://github.com/aws-amplify/amplify-cli/pull/12755
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/20816/workflows/65b0b2b7-bdfa-4c74-9b08-67a6f6c2d8ef/jobs/982041
=> chore: check for duplicates in yarn.lock

packages/amplify-e2e-tests/src/__tests__/smoketest.test.ts
Fixes https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/20881/workflows/468fd9d8-b8cb-4089-a3e0-f79df2e23416/jobs/985277 .
=> fix: smoke test flakiness

.circleci/local_publish_helpers.sh
=> chore: verdaccio wait performance

scripts/finish-release.ts
=> chore: fix finish release script

scripts/github-release.ts
Adds `make_latest` flag to github release script
=> fix: github release script

packages/amplify-migration-tests/src/__tests__/migration_tests_v11/__snapshots__/auth-app-client-secret-migration.test.ts.snap
=> chore: update snapshot with  jest 29

Dockerfile
Added dependencies listed in the cypress [docs](https://docs.cypress.io/guides/continuous-integration/introduction#Dependencies)
=> ci: add os dependencies for cypress

packages/amplify-category-auth/resources/auth-custom-resource/hostedUIProviderLambda.js
=> chore: refactor hostedUIProviderLambda.js to use async await

packages/amplify-console-hosting/src/utils/amplify-console-utils.js, packages/amplify-console-hosting/src/utils/build-utils.js, packages/amplify-provider-awscloudformation/src/admin-login.ts
avoid empty and string rejects
N/A
=> fix: avoid empty and string rejects

.eslint-dictionary.json, packages/amplify-category-storage/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.test.ts, packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.ts
Add PartiQL permissions to IAM policy.
Note I've also done my best to lint the file. I've ignored some of the errors where the complexity out strips my knowledge of the project.
#8430
Visual inspection. It is a very simple change and maps the permissions I've added in my production app.
=> Category storage/partiql permissions

packages/amplify-e2e-tests/src/__tests__/uibuilder.test.ts
Ensure child process is torn down even if test fails
=> test: make test teardown resilient to failures

scripts/split-e2e-tests-codebuild.ts, scripts/split-e2e-tests-v2.ts
=> chore: remove lambda python test from windows suite

.gitignore
Ignore logs so that it's easier to keep logs in local package. Otherwise, I have to delete my logs every time....
=> chore: ignore logs

scripts/wait-for-all-codebuild.ts
=> chore: swap try-catch for if-else in wait script

codebuild_specs/build_linux.yml, codebuild_specs/build_pkg_binaries_arm.yml, codebuild_specs/build_pkg_binaries_linux.yml, codebuild_specs/build_pkg_binaries_macos.yml, codebuild_specs/build_pkg_binaries_win.yml, codebuild_specs/integration_test.yml, codebuild_specs/mock_e2e_tests.yml, codebuild_specs/publish_to_local_registry.yml, codebuild_specs/scripts-windows/wait-windows.sh, codebuild_specs/test.yml, codebuild_specs/upload_pkg_binaries.yml, codebuild_specs/validate_cdk_version.yml, codebuild_specs/verify_api_extract.yml, codebuild_specs/verify_versions_match.yml, codebuild_specs/verify_yarn_lock.yml, scripts/wait-for-all-codebuild.ts, shared-scripts.sh
=> chore: fail wait job if preceding job fails

.circleci/config.base.yml
Restore amplify-pkg-version in rc release
=> fix: amplify-pkg-version in rc release

packages/amplify-graphql-migration-tests/src/v2-transformer-provider.ts, packages/amplify-util-mock/src/__e2e_v2__/searchable-transformer.e2e.test.ts, packages/amplify-util-mock/src/__e2e_v2__/util-method.e2e.test.ts, yarn.lock
Update to use new sandbox as a transformer param.
N/A
Unit + E2E Tests
=> update sandbox param

codebuild_specs/e2e_workflow_generated.yml, codebuild_specs/wait_for_ids.json, packages/amplify-migration-tests/src/__tests__/migration_tests_v12/__snapshots__/auth-app-client-secret-migration.test.ts.snap, scripts/split-e2e-test-filters.ts
=> fix: typo in migration tests manifest

.circleci/publish-step-1-set-versions.sh
=> fix: publish release script

.circleci/config.base.yml
=> fix: github publish commit hash

scripts/split-e2e-tests-v2.ts
=> fix: typo in split-e2e-tests-v2.ts

.circleci/config.base.yml, packages/amplify-app/src/index.js, packages/amplify-e2e-core/src/utils/index.ts, shared-scripts.sh
Fix amplify app regex to capture `<major>.<minor>.<fix>` prefix correctly.
Previous version was incorrectly processing tag/rc versions.
CB:
https://us-east-1.console.aws.amazon.com/codesuite/codebuild/671107461633/projects/AmplifyCLI-E2E-Testing/batch/AmplifyCLI-E2E-Testing%3Af6bdb9ac-5a93-4898-86d1-a01f1907a4b5?region=us-east-1
CCI:
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e%2Fsobkamil%2Ffix-modelgen-test
=> fix: amplify app version regex

packages/amplify-graphql-migration-tests/src/v2-transformer-provider.ts
There was a failing test that seemed to block some local dev but not CI, updating that test.
N/A
CI flow
=> fix: update GraphQLTransform input types

packages/amplify-e2e-tests/src/__tests__/auth_5g.test.ts
=> test: fix import in auth 5g test

packages/amplify-e2e-tests/src/__tests__/auth_4c.test.ts
=> chore: remove unused imports

.circleci/codebuild-checkout.sh
Fixing
```
HEAD detached at 6d5675b8b4
nothing to commit, working tree clean
CODEBUILD_SOURCE_VERSION=6d5675b8b4391b3283a36f534c84f9d43d25f664
BRANCH_NAME=
CODEBUILD_WEBHOOK_TRIGGER=branch/dev
CODEBUILD_SOURCE_VERSION_REF=6d5675b8b4391b3283a36f534c84f9d43d25f664 refs/heads/dev
6d5675b8b4391b3283a36f534c84f9d43d25f664 refs/remotes/origin/dev
BRANCH_NAME must be defined for non-PR builds
```
=> fix: dev build

packages/amplify-cli/package.json, packages/amplify-container-hosting/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, packages/amplify-util-uibuilder/package.json, yarn.lock
=> chore: bump data deps

packages/amplify-e2e-tests/Readme.md, packages/amplify-e2e-tests/sample.env, packages/amplify-migration-tests/Readme.md, packages/amplify-migration-tests/sample.env
- update README and sample env for e2e test and migration test
=> chore(amplify-e2e-tests): update readme and sample env

codebuild_specs/e2e_workflow_generated.yml, codebuild_specs/pr_workflow.yml, codebuild_specs/verify_e2e_workflow_generated.yml, shared-scripts.sh
Add validation of generated e2e workflow.
=> ci: verify e2e workflow

package.json, yarn.lock
Bump word-wrap to ^1.2.4 with resolution in root `package.json`.
Both PR and E2E validation passed.
=> chore: bump word-wrap with resolution

packages/amplify-e2e-tests/src/__tests__/function_2d.test.ts, packages/amplify-nodejs-function-template-provider/resources/lambda/crud/app.js.ejs
This adds list all functionality to crud ddb template.
=> feat: add list all to lambda crud template

shared-scripts.sh
=> fix: release scripts

codebuild_specs/release_workflows/post_publish_push_to_git.yml
Codebuild jobs fail if they dependOn[somejob] and [somejob] does not produce artifacts.
In this case, [somejob] is the post_publish job, and our github_release job depends on it.
=> ci: add artifact to unblock github release step

.circleci/codebuild-checkout.sh
PR and E2E workflow on this PR.
=> ci: add sanity check to cb checkout script

.circleci/cb-publish-step-1-set-versions.sh, .circleci/cb-publish-step-3-npm.sh, .circleci/cb-publish-step-4-push-to-git.sh, .circleci/codebuild-checkout.sh, .circleci/local_publish_helpers_codebuild.sh, scripts/cloud-cli-utils.sh, scripts/cloud-release.sh
**This PR:**
- Changes CodeBuild scripts to use `PROJECT_NAME` instead of branch names to drive behavior, i.e. PR, release, rc, tagged release. This drops dependency on branch convention on the CodeBuild side.
- Tagged release client side scripts ask for branch and npm tag.
- Validation is added to scripts to expect npm tag in env vars.
- Validation is added to prevent tagged releases from special branches (main, hotfix, dev, release)
- Validation is added to require release going from release branch
**Out of scope**
This PR does not change client side portion of RC builds, i.e. RC branch convention is still followed, but it's not required by RC pipeline.
**PR and E2E workflows**
**Tagged release**
By submitting this pull request, I confirm that my contribution is made under the terms of …
=> ci: remove branch convention

packages/amplify-cli-npm/index.ts, packages/amplify-cli/src/index.ts
Minor version bump to account for this feature:
=> feat: bump version to 12.4.0

packages/amplify-cli-npm/index.ts, packages/amplify-cli/src/index.ts
We have couple of feats in https://github.com/aws-amplify/amplify-cli/compare/v12.4.0...aws-amplify:amplify-cli:dev?expand=1 .
Therefore making sure that main CLI package ships with minor version bump.
PR checks are sufficient for this change.
=> feat: update main CLI version

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, packages/amplify-util-uibuilder/package.json, yarn.lock
Fixes issue with relative types import path in graphql statements
=> chore: upgrade amplify-codegen

package.json, yarn.lock
Fix semver releated dependabot alerts:
- https://github.com/aws-amplify/amplify-cli/security/dependabot/185
- https://github.com/aws-amplify/amplify-cli/security/dependabot/183
- https://github.com/aws-amplify/amplify-cli/security/dependabot/182
=> fix: dependabot alert for semver

packages/amplify-cli/src/index.ts
There is feature in this release payload. Bumping minor version
=> feat: bump npm version to 12.7.0

package.json, packages/amplify-e2e-tests/package.json, packages/amplify-frontend-javascript/package.json, packages/amplify-graphiql-explorer/package.json, yarn.lock
Bumping @babel/core to patched version for dependabot alert.
=> chore: bump @babel/core to 7.23.2

yarn.lock
bumping crypto.js to patch
https://github.com/aws-amplify/amplify-cli/security/dependabot/199
=> fix: bump crypto.js

packages/amplify-e2e-tests/src/__tests__/uibuilder.test.ts
The codegen service had a recent change to generate the utils.js file in any case. Previously, it was just for apps with forms.
amplify pull
=> chore: update uibuilder test with utils file

.github/workflows/smoke-tests.yml
Propagating fix for missing `node-gyp` dependency to smoke test workflow.
https://github.com/aws-amplify/amplify-cli/pull/13395#discussion_r1387064252
Test run https://github.com/aws-amplify/amplify-cli/actions/runs/7226620347
=> test: fix smoke tests

packages/amplify-appsync-simulator/package.json, yarn.lock
Updates ip dependency.
PR checks.
=> chore: update ip dependency

package.json, yarn.lock
Updates undici dependency
Pr checks.
=> chore: update undici dependency

.github/ISSUE_TEMPLATE/config.yml
removes the blank template to enable better visibility.
=> removes blank template

yarn.lock
Updates express js dependency.
Pr checks.
=> chore: update express dependency

package.json, yarn.lock
Bumps `tar` dependency.
Note: the bump is via override as lerna depends on it and doesn't have a fix in 6.x line.
=> chore: update tar dependency

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, packages/amplify-util-uibuilder/package.json, yarn.lock
Wrong codegen has been packaged into binary (the top level resolutions did not work).
This PR pins codegen in all packages instead.
=> chore: use 4.7.3 codegen

Readme.md
Update readme with gen 2 GA wording
=> update readme with gen 2 GA messaging

package.json, yarn.lock
=> chore: update mysql2 to ^3.9.8

yarn.lock
upgrade package 'braces' to 3.0.3
Result:
=> chore: upgrade braces to 3.0.3

yarn.lock
=> chore: bump ws versions

packages/amplify-gen1-codegen-auth-adapter/src/auth_render_adapter.test.ts, packages/amplify-gen1-codegen-auth-adapter/src/auth_render_adapter.ts, packages/amplify-gen2-codegen/src/auth/source_builder.test.ts, packages/amplify-gen2-codegen/src/auth/source_builder.ts, packages/amplify-gen2-codegen/src/function/lambda.ts, packages/amplify-gen2-codegen/src/index.ts, packages/amplify-gen2-codegen/src/resource/resource.test.ts, packages/amplify-gen2-codegen/src/resource/resource.ts, packages/amplify-gen2-codegen/src/storage/source_builder.ts, packages/amplify-migration/src/app_storage_definition_fetcher.ts, packages/amplify-migration/src/index.ts, packages/amplify-provider-awscloudformation/src/utils/resolve-appId.ts
Stubs `defineFunction` calls for auth lambda triggers.
Unit tests to validate that expected stubs are present in generated source code. Manually verified against a deployed amplify app to validate that the hooks are being rendered as expected.
=> Auth triggers

package.json, yarn.lock
Bump version for fast-xml-parser.
=> chore: bump versions

packages/amplify-gen2-codegen/src/backend/synthesizer.test.ts, packages/amplify-gen2-codegen/src/backend/synthesizer.ts, packages/amplify-gen2-codegen/src/data/source_builder.test.ts, packages/amplify-gen2-codegen/src/data/source_builder.ts, packages/amplify-gen2-codegen/src/index.ts, packages/amplify-gen2-codegen/src/resource/resource.test.ts, packages/amplify-gen2-codegen/src/resource/resource.ts, packages/amplify-gen2-codegen/src/todo_error.test.ts, packages/amplify-gen2-codegen/src/todo_error.ts, packages/amplify-migration/package.json, packages/amplify-migration/src/amplify_stack_parser.ts, yarn.lock
Small fixes and QoL improvements for data codegen. Add schema property and new error helper that throws an error if there is a pending todo item.
=> fix: bugfixes for data codegen

packages/amplify-cli-core/src/feature-flags/featureFlags.ts
Add enableGen2Migration feature flag for data.
If set to true:
* Set all DynamoDB tables removal policy to retain.
* Add mapping of model name -> table name to CFN output.
N/A
N/A
---
=> feat: add enableGen2Migration feature flag

packages/amplify-cli-npm/index.ts, packages/amplify-gen1-codegen-auth-adapter/API.md, packages/amplify-gen1-codegen-auth-adapter/src/auth_render_adapter.test.ts, packages/amplify-gen1-codegen-auth-adapter/src/auth_render_adapter.ts, packages/amplify-gen2-codegen/API.md, packages/amplify-gen2-codegen/src/auth/source_builder.test.ts, packages/amplify-gen2-codegen/src/auth/source_builder.ts, packages/amplify-migration/src/app_auth_definition_fetcher.ts
Sign Up User Attributes and Groups Codegen implementation
Unit tests, manually verified against a deployed app to check if added groups and user attributes are being generated.
=>  feat: signup user attributes/groups auth codegen

.circleci/local_publish_helpers_codebuild.sh, packages/amplify-appsync-simulator/package.json, packages/amplify-storage-simulator/package.json, yarn.lock
Bump version of express in order to address https://github.com/aws-amplify/amplify-cli/security/dependabot/253
Before:
After:
=> chore: bump express version

package.json, yarn.lock
Bump send version to fix https://github.com/aws-amplify/amplify-cli/security/dependabot/255
=> chore: bump send

packages/amplify-migration/README.md
Add README for Gen2 migrations CLI package.
=> Gen2 Migration readme file

packages/amplify-migration-template-gen/src/resolvers/cfn-condition-resolver.test.ts, packages/amplify-migration-template-gen/src/resolvers/cfn-condition-resolver.ts, packages/amplify-migration-template-gen/src/types.ts
Add condition resolver to resolve conditions in resources being moved as part of refactor. 
manual testing of template gen command, unit testing
=> feat(migrate-template-gen): add condition resolver

packages/amplify-cli/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, packages/amplify-util-uibuilder/package.json, yarn.lock
Release https://github.com/aws-amplify/amplify-codegen/pull/888
E2E run: https://us-east-1.console.aws.amazon.com/codesuite/codebuild/671107461633/projects/AmplifyCLI-E2E-Testing/batch/AmplifyCLI-E2E-Testing:3808dfeb-0ed4-4857-b48d-7a32c4f5ea17?region=us-east-1
---
=> chore: update codegen packages

packages/amplify-migration-template-gen/src/resolvers/cfn-dependency-resolver.test.ts, packages/amplify-migration-template-gen/src/resolvers/cfn-dependency-resolver.ts
Add CFN dependency resolver to remove dependencies not part of refactor operation.
local testing, unit tests.
=> Gen2 migrations template gen - add cfn dependency resolver

packages/amplify-migration-template-gen/src/category-template-generator.test.ts, packages/amplify-migration-template-gen/src/category-template-generator.ts, packages/amplify-migration-template-gen/src/index.ts, packages/amplify-migration-template-gen/src/migration-readme-generator.test.ts, packages/amplify-migration-template-gen/src/migration-readme-generator.ts, packages/amplify-migration-template-gen/src/resolvers/cfn-condition-resolver.ts, packages/amplify-migration-template-gen/src/resolvers/cfn-output-resolver.ts, packages/amplify-migration-template-gen/src/resolvers/cfn-parameter-resolver.ts
1. Resolve Gen1 dependencies to Gen2 counterparts while moving for refactor operation
2. Resolve all stack outputs instead of only those being moved since there are resources which reference other resources not being moved
3. Throw validation error when no resources are found to be moved/removed in Gen1/Gen2 stack
=> Gen2 migration template gen

packages/amplify-gen2-codegen/API.md, packages/amplify-gen2-codegen/src/backend/synthesizer.test.ts, packages/amplify-gen2-codegen/src/backend/synthesizer.ts, packages/amplify-gen2-codegen/src/index.ts, packages/amplify-gen2-codegen/src/storage/source_builder.ts, packages/amplify-migration/src/app_storage_definition_fetcher.ts
Updated storage codegen
- Added removal policy
- Added bucket encryption
- Added s3 bucketName
=> Migrations

scripts/cloud-e2e.sh
On Windows $USERNAME is used instead of $USER. Adds an if block to `cloud-e2e.sh` to see if $USER is empty, if it is uses $USERNAME.
N/A
Verified by running e2e on another PR without committing these changes to that PR. 
=> fix: update script for cloud e2e tests for windows users

scripts/cloud-e2e.sh
=> chore: fix cloud e2e script

packages/amplify-migration-e2e/src/__tests__/migration_codegen_e2e.test.ts, packages/amplify-migration-e2e/src/__tests__/migration_templategen_e2e.test.ts, packages/amplify-migration-e2e/src/index.ts, packages/amplify-migration-e2e/src/migrationReadmeParser.ts, packages/amplify-migration-e2e/src/sandbox.ts, packages/amplify-migration-e2e/src/secrets.ts, packages/amplify-migration-e2e/src/templategen.ts, packages/amplify-migration/package.json
Added more test cases for the rollback commands of stack refactor which is a part of the templategen command
Manual validating by checking the console whether the resources are being created, deployed, deleted successfully. Assertion statements.
=> feat: added tests for rollback commands of templategen command

packages/amplify-cli/package.json, packages/amplify-container-hosting/package.json, packages/amplify-provider-awscloudformation/package.json, packages/amplify-util-mock/package.json, packages/amplify-util-uibuilder/package.json, yarn.lock
- Bump the version of plugins in Amplify CLI
- ran `yarn update-data-packages` to update 
=> Update data packages to latest release tag

packages/amplify-gen1-codegen-auth-adapter/API.md, packages/amplify-gen1-codegen-auth-adapter/src/auth_render_adapter.ts, packages/amplify-gen2-codegen/API.md, packages/amplify-gen2-codegen/src/auth/source_builder.ts, packages/amplify-gen2-codegen/src/backend/synthesizer.test.ts, packages/amplify-gen2-codegen/src/backend/synthesizer.ts, packages/amplify-gen2-codegen/src/index.ts, packages/amplify-migration/src/app_auth_definition_fetcher.ts
- Added codegen for userPoolClient configuration
- Added retain policy for identity pool, user pool and s3 bucket
- Fixed a bug in s3 encryption algorithm codegen
Added unit tests
=> fix: added user pool client codegen

packages/amplify-cli/package.json, packages/amplify-container-hosting/package.json, packages/amplify-util-uibuilder/package.json, yarn.lock
* upgrade to latest api category tagged release
---
=> chore: upgrade to latest api category tagged release

packages/amplify-velocity-template/package.json, yarn.lock
Updates versions of nanoid via mocha.
=> fix: bump versions

packages/amplify-gen2-codegen/src/backend/synthesizer.test.ts, packages/amplify-gen2-codegen/src/backend/synthesizer.ts, packages/amplify-migration-template-gen/src/migration-readme-generator.test.ts, packages/amplify-migration-template-gen/src/migration-readme-generator.ts
Add a tag to force deployment post refactor in gen2 codegen
unit tests
=> fix: add tag to force deployment post refactor in gen2 codegen

.github/workflows/build-test-mac.yml, packages/amplify-category-auth/src/__tests__/commands/update.test.ts, packages/amplify-cli/src/__tests__/amplify-exception-handler.test.ts, packages/amplify-cli/src/__tests__/flow-report.test.ts, packages/amplify-cli/src/__tests__/serializable-error.test.ts, packages/amplify-cli/src/__tests__/test-aborting.test.ts, packages/amplify-cli/src/__tests__/usage-data.test.ts, packages/amplify-cli/src/domain/amplify-usageData/FlowReport.ts, packages/amplify-cli/src/domain/amplify-usageData/SerializableError.ts, packages/amplify-cli/src/domain/amplify-usageData/UsageData.ts
Update what data gets collected by telemetry
=> Fix: update telemetry collection

packages/amplify-gen2-codegen/src/data/source_builder.test.ts, packages/amplify-gen2-codegen/src/data/source_builder.ts
Change name of some data migrations props.
migratedAmplifyGen1DynamoDbTableMap -> migratedAmplifyGen1DynamoDbTableMappings
modelTableNameMap -> modelNameToTableNameMapping
---
=> fix: update data prop names

packages/amplify-migration/src/command-handler.test.ts, packages/amplify-migration/src/command-handlers.ts
Remove gen1 config files in `prepare` command based on the `SourceDir` property in `amplify/.config/project-config.json`
local testing, unit testing
=> feat(migrate): remove gen1 config files in prepare command

packages/amplify-category-custom/resources/package.json
=> chore(deps): bump aws-cdk-lib from 2.184.1 to 2.187.0

packages/amplify-migration/package.json, yarn.lock
update lock file for cli-core
`yarn && yarn build`
=> fix: update package and yarn lock file for cli-core

packages/amplify-cli-npm/index.ts, packages/amplify-cli/src/index.ts
Big SDK migrations PR is going out, want to ensure we have a minor version bump because of it.
Ensured that PR checks bumped to the right version
=> feat: version bump
