aws-amplify/amplify-cli

.circleci/config.base.yml
.circleci/local_publish_helpers.sh
package.json

This pr _properly_ uses `yarn yarn-use-bash` and uses `rimraf` instead of `rm -rf`. This fixes the `build_pkg_binaries` pipeline step ([proof](https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/5843/workflows/02640dbb-eb23-4a05-80cc-fafaeece9967/jobs/139587)).

fix: use bash when calling yarn pkg-all

---

packages/amplify-cli/package.json
packages/amplify-provider-awscloudformation/package.json
packages/amplify-util-mock/package.json

Use caret version codegen in tag `amplify-codegen-e2e-tests`. This will be used by codegen repo e2e tests only.

chore: use caret codegen for tag release

---

packages/amplify-util-uibuilder/src/commands/utils/notifyMissingPackages.ts

uibuilder can allow any version of ui-react

chore: allow any ui-react version for uibuilder

---

packages/amplify-util-uibuilder/src/__tests__/notifyMissingPackages.test.ts

this test is no longer meaningful because no specific dependency versions are required (all use `*`).

test: remove outdated test

---

packages/amplify-util-uibuilder/package.json
yarn.lock

This module was pulling in outdated versions.
Refs: https://github.com/aws-amplify/amplify-cli/pull/9287

chore: update amplify-util-uibuilder dependencies

---

packages/amplify-appsync-simulator/src/__tests__/velocity/value-mapper/array.test.ts
packages/amplify-appsync-simulator/src/velocity/value-mapper/array.ts
packages/amplify-appsync-simulator/src/velocity/value-mapper/string.ts

AppSync simulator did not implement indexOf method on list.  When the values were mapped to their Java equivalent JS implementation Array.indexOf method did always return -1. Implemented indexOf method in JavaArray class
fix #8830

fix: velocity list.indexOf method

---

packages/amplify-velocity-template/src/compile/blocks.js
packages/amplify-velocity-template/src/compile/compile.js
packages/amplify-velocity-template/tests/foreach.test.js
packages/amplify-velocity-template/tests/runner/spec.js

Velocity template renderer implemented in Amplify CLI was continuing execution of statements that were after the `#break` statement and breaking of loop happened only at the end of the `#foreach` loop. Updated the code to not to run any statements that are after `#break` statement
fix #8779

fix: velocity #break statement handling

---

packages/amplify-cli/package.json
packages/amplify-provider-awscloudformation/package.json
packages/amplify-util-mock/package.json
yarn.lock

Bumping the amplify-codegen version to v2.26.23.
Several fixes for modelgen with GraphQL V2 transformer. The tests are done by all amplify library teams.

fix: GraphQL V2 fix for codegen

---

packages/amplify-category-api/package.json
packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.test.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-builder.ts
packages/amplify-e2e-tests/src/__tests__/apigw.test.ts
yarn.lock

fix #5183
Enables CORS for default 4xx and 5xx api gateway for easier debugging.
It also allows `Amplify.API` to auto correct clockskew, see: https://github.com/aws-amplify/amplify-js/issues/6494
#5183
Manually tested.
Would be happy to add unit test if you can point me to where I should add the unit tests.

feat(amplify-category-api): enable default 4xx and 5xx api gateway cors response

---

packages/amplify-category-custom/src/utils/generate-cfn-from-cdk.ts

Custom stacks build with CDK now populated with environment containing account and region placeholders
refs #9360
Using tests

fix: populating custom resource stack with account/region placeholders

---

packages/graphql-auth-transformer/package.json
packages/graphql-connection-transformer/package.json
packages/graphql-dynamodb-transformer/package.json
packages/graphql-http-transformer/package.json
packages/graphql-key-transformer/package.json
packages/graphql-transformer-common/package.json
packages/graphql-transformer-core/package.json
packages/graphql-versioned-transformer/package.json

This commit cleans up the dependencies in the GraphQL Transformer
v1. The changes are based on the output of depcheck.

fix: clean up missing and unused GraphQL v1 dependencies

---

packages/amplify-util-uibuilder/package.json

This commit updates amplify-util-uibuilder to use jest-junit
settings consistent with other packages in the repo. This also
allows the report output to be picked up by the project's
.gitignore instead of creating an untracked file each time
the test suite is run.

test: update uibuilder junit settings

---

packages/amplify-category-custom/src/utils/generate-cfn-from-cdk.ts

Reverts aws-amplify/amplify-cli#9361
Breaking e2e test `packages/amplify-e2e-tests/src/__tests__/custom_resources.test.ts`

Revert "fix: populating custom resource stack with account/region placeholders"

---

packages/amplify-cli/src/attach-backend-steps/a40-generateFiles.ts
packages/amplify-cli/src/commands/env/checkout.ts
packages/amplify-cli/src/init-steps/s9-onSuccess.ts
packages/amplify-frontend-android/lib/frontend-config-creator.js
packages/amplify-frontend-flutter/lib/frontend-config-creator.js
packages/amplify-frontend-ios/lib/frontend-config-creator.js
packages/amplify-frontend-javascript/lib/frontend-config-creator.js

This change fixes 2 issues. 
1. When a new environment is initialized, the frontend configuration files (like aws-exports.js) were not updated before a push was performed. This was due to CLI trying to retain custom configuration value that might have been added externally. Created a list of configuration keys that are reserved for the CLI and can't be overriden
2. When a project is pulled and used for frontend development, pulling it again did not update the configuration file. This change includes fix for that
fix #9416

fix: fix amplify pull and init to regenerated frontend configuration 

---

packages/amplify-graphql-predictions-transformer/src/__tests__/__snapshots__/amplify-graphql-predictions-transformer-override.test.ts.snap
packages/amplify-graphql-predictions-transformer/src/__tests__/__snapshots__/amplify-graphql-predictions-transformer.test.ts.snap
packages/amplify-graphql-transformer-core/src/transform-host.ts
packages/amplify-util-mock/src/CFNParser/resource-processors/lambda.ts

The `@searchable` and `@predictions` directives create a Lambda
function via `context.api.host.addLambdaFunction()`. This commit
updates `addLambdaFunction()` to not set the optional `functionName`
in the CFN. This lets CFN generate a unique name.
The mock functionality also needed to be updated because mock
expects all Lambdas to have this optional property. If the CFN
does not contain a `functionName`, fall back to the resource name.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/9480

fix: remove functionName from transform-host lambdas

---

packages/amplify-graphql-auth-transformer/package.json
packages/amplify-graphql-auth-transformer/src/__tests__/group-auth.test.ts
packages/amplify-graphql-auth-transformer/src/resolvers/field.ts
packages/amplify-graphql-auth-transformer/src/resolvers/mutation.create.ts
packages/amplify-graphql-auth-transformer/src/resolvers/mutation.delete.ts
packages/amplify-graphql-auth-transformer/src/resolvers/mutation.update.ts
packages/amplify-graphql-auth-transformer/src/resolvers/query.ts

With this PR the custom claims specified for the dynamic groups will be parsed into a list so that it allows multiple dynamic groups to be specified and to fix the functionality which was working in the GraphQL Transformer v1. Currently it will either return items the user shouldn't even be allowed to access, or will thrown an `Unauthorized` error when accessing the items they should be allowed to view.
The custom claim included in the JWT could either be a string:
```json
{
"tenants": "05949c86-6c1a-4f13-8bb5-bdbee322f0d6",
...
}
```
or a list:
```json
{
"tenants": "[\"05949c86-6c1a-4f13-8bb5-bdbee322f0d6\",\"c812425e-77f3-4362-aac1-67da9aa30c3f\",\"b3c3ab8a-c89b-4690-884b-82a22e3f64d5\"]",
...
}
```
At the moment, the generated mutation for creating an entity, for example, doesn't parse …

fix: parse dynamic groups custom claim to list

---

packages/amplify-e2e-tests/src/__tests__/uibuilder.test.ts

This e2e test is failing in master, but passing locally with this change. The issue was the uibuilder endpoint was referencing a region not associated with the app.

test: use proper region in uibuilder test

---

packages/amplify-category-api/src/provider-utils/awscloudformation/base-api-stack.ts

The logic that container rest api uses to determine the `isInitialPush` flag is flawed. This results in incorrect processing of the secret files even though there are no changes made to the api.
https://github.com/aws-amplify/amplify-cli/issues/8384
- Manual test
- e2e test in local

fix(api): container rest api push treats incorrect initial push behavior

---

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/owner-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/owner-auth.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/resolvers/query.ts
packages/amplify-graphql-auth-transformer/src/utils/schema.ts
packages/amplify-util-mock/src/__tests__/velocity/model-auth.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/IndexWithAuthV2.e2e.test.ts

- update listX primaryField (auth field that is a part of the primaryKey) to append to authFilter instead of appending to `ModelQueryExpression`
- if primaryKey (aka partitionKey) is in the args for listX, any other rules which don't use the sort key will be used first. If those are not applicable, any auth rules on the sort Key will be used to modify the request. If all else fails the request is unauthorized.
- unit
- vtl mock
- e2e

fix: listX operations with no args where authField is used in primaryKey

---

.eslintrc.js
packages/amplify-graphql-schema-test-library/.npmignore
packages/amplify-graphql-schema-test-library/CHANGELOG.md
packages/amplify-graphql-schema-test-library/README.md
packages/amplify-graphql-schema-test-library/package.json
packages/amplify-graphql-schema-test-library/src/__tests__/index.test.ts
packages/amplify-graphql-schema-test-library/src/index.ts
packages/amplify-graphql-schema-test-library/tsconfig.json

This commit adds the initial version of a new package, `@aws-amplify/graphql-schema-test-library`, which is intended to contain a collection of schemas that can be shared among teams for common validation.
cc: @alharris-at. Are there any specific schemas you'd like to see included here? I'd like to balance including schemas that codegen can test and finds useful, while not duplicating the CLI's full test suite.

chore: add test schema library package

---

packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts
packages/amplify-category-auth/src/commands/auth/remove.ts
packages/amplify-cli/src/__tests__/extensions/amplify-helpers/remove-resource.test.ts
packages/amplify-cli/src/extensions/amplify-helpers/remove-resource.ts

When a GraphQL API is added/updated in a project, currently there is no `dependsOn` managed between the two resources,  and then the `auth` resource was removed, the `push` operation failed.
This PR updates the `add` and `update` functionality to properly manage the `dependsOn` between the two resources if the API has Cognito auth mode configured.
This PR also updates the `remove` behavior to list all the dependent resources, not just the first one in the error message.
Fixes #9341
Manual testing, updated unit test for remove

fix: #9341 - handle auth and api dependency in state files correctly

---

packages/amplify-provider-awscloudformation/src/__tests__/graphql-transformer/utils.test.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/utils.ts

Applies the CFN template pre-processor to nested API stacks. The template pre-processor is responsible for applying certain resource config across all CLI generated resources such as S3 encryption and IAM role permissions boundaries.
fixes https://github.com/aws-amplify/amplify-cli/issues/9583
manually tested and added unit test

fix: apply cfn pre-push transformer to nested api stacks

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts

This PR addresses issues reported on https://github.com/aws-amplify/amplify-cli/issues/9525 by informing customers of drift between Cognito user pool configuration and their requested parameters in cli-inputs.json, rather than waiting for CloudFormation to eventually fail and roll back with an error message that is tricky to track down how to fix it.

fix: handle failed pushes from cognito drift

---

packages/amplify-category-geo/package.json
packages/amplify-cli/package.json

A stray beta version already exists on GitHub and npm which
prevented a release from going through. This commit bumps
the version to unblock the release.

chore: manually bump amplify-category-geo version

---

packages/amplify-cli/package.json
packages/amplify-graphql-auth-transformer/package.json
packages/amplify-graphql-migration-tests/package.json
packages/amplify-graphql-relational-transformer/package.json
packages/amplify-graphql-schema-test-library/package.json
packages/amplify-provider-awscloudformation/package.json
packages/amplify-util-mock/package.json

This commit bumps the `@auth` v2 version number to avoid conflicting with stray beta releases.

chore: manually bump @aws-amplify/graphql-auth-transformer version

---

packages/amplify-cli-core/src/feature-flags/featureFlags.ts
packages/amplify-cli/src/__tests__/extensions/amplify-helpers/auth-notifications.test.ts
packages/amplify-cli/src/commands/push.ts
packages/amplify-cli/src/extensions/amplify-helpers/auth-notifications.ts
packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/field-auth-argument.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/field-auth-argument.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/graphql-transformer-core/src/index.ts

This pull requests separates out generation of field-level resolvers from checking for errors on types with subscriptions configured.

fix: separate out subscription errors from field level resolver generation

---

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/auth-notifications.test.ts
packages/amplify-cli/src/extensions/amplify-helpers/auth-notifications.ts

- scopes the auth notification to v2 transformer
- fixes the recursive updates to schema files by using a returned base case rather than setting a variable

fix: fix modify gql schema base case; scope auth notif to v2

---

packages/amplify-category-notifications/lib/channel-Email.js
packages/amplify-category-notifications/lib/pinpoint-helper.js

This PR fixes an issue where, if a Pinpoint project is deleted manually via AWS Console, the `notifications` category could not be removed from the amplify project. It accomplishes this by treating a `NotFoundException` on deletion as a successful deletion.
https://github.com/aws-amplify/amplify-cli/issues/9036
```
amplify add notifications && amplify push
delete pinpoint manually
amplify remove notifications && amplify push
amplify pull/push no longer recreates the notifications category.
```

fix: allow pinpoint category removal after manual deletion

---

packages/amplify-e2e-core/src/asciinema-recorder.ts
packages/amplify-e2e-core/src/utils/nexpect.ts

When E2E tests timeout in nexpect, to see the error one has to play the entire asciinema by loading the test report page from the artifact section. Updating the timeout error message to include the few lines of screen recording to surface it in the exception

test: print recorded screen frames when nextpect times out in E2E tests

---

packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-tests/src/__tests__/api_5.test.ts
packages/amplify-provider-awscloudformation/package.json
packages/amplify-provider-awscloudformation/src/__tests__/utils/consolidate-apigw-policies.test.ts
packages/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts
yarn.lock

Change REST API policy size calculation logic and numbers. The resource gets collapsed into a single resource with `*` when all the HTTP verbs are allowed for a path.
N/A
Manual deployments

 fix: rest api policy size calculation

---

packages/amplify-category-auth/resources/auth-custom-resource/hostedUIProviderLambda.js
packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/__snapshots__/auth-stack-transform.test.ts.snap
packages/amplify-e2e-tests/src/__tests__/auth_1.test.ts

On a pull when and then executing another push the auth the idp updater/creator custom lambda resource throws an error since the credentials do not exist

fix: do not update idp if credentials not present

---

packages/amplify-e2e-tests/src/__tests__/__snapshots__/function_9.test.ts.snap

Updated snapshot because of change in Lambda Snapshot

test: updated snapshot for functions_9

---

packages/amplify-appsync-simulator/src/__tests__/scalars/AWSURL.test.ts
packages/amplify-appsync-simulator/src/__tests__/scalars/__snapshots__/AWSURL.test.ts.snap

The message shown on `ERR_INVALID_URL` errors changed slightly in Node 16. This commit updates two `AWSURL` unit tests to pass across supported Node.js versions.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/9703

test: fix failing AWSURL unit tests on Node 16

---

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts
packages/amplify-e2e-core/src/categories/lambda-function.ts
packages/amplify-e2e-tests/src/__tests__/function_9.test.ts

When updating a function, removes to category length validation so that a user can remove all category access.
Fixes https://github.com/aws-amplify/amplify-cli/issues/8010
I tested this locally by duplicating the Issue steps, and it works as requested now.

fix(amplify-category-function): allow user to update function without length validation

---

packages/amplify-graphql-searchable-transformer/src/__tests__/__snapshots__/amplify-graphql-searchable-transformer.test.ts.snap
packages/amplify-graphql-searchable-transformer/src/__tests__/amplify-graphql-searchable-transformer.test.ts
packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts

When datastore is enabled, opensearch must add the `_version` to the response type.
Fixes https://github.com/aws-amplify/amplify-cli/issues/9632
- yarn test
- manual test

fix(searchable): unwrap _version field correctly when datastore is enabled

---

packages/amplify-graphql-auth-transformer/src/__tests__/__snapshots__/amplify-admin-auth.test.ts.snap
packages/amplify-graphql-auth-transformer/src/__tests__/amplify-admin-auth.test.ts
packages/amplify-graphql-auth-transformer/src/resolvers/mutation.update.ts

Allow `update` mutation to respect cognito authentication for IAM private rule.
Fixes https://github.com/aws-amplify/amplify-cli/issues/9502
- Manual test
- yarn test

fix(graphql): allow iam private rule to access update mutation when authenticated by cognito

---

packages/amplify-category-geo/src/__tests__/__snapshots__/index.test.ts.snap
packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/placeIndexStack.test.ts.snap
packages/amplify-category-geo/src/service-stacks/placeIndexStack.ts
packages/amplify-category-geo/src/service-utils/placeIndexUtils.ts

Add permissions to search for Suggestions using a place index resource. This is a new feature that will be supported by Amplify Geo JS.
Docs PR: https://github.com/aws-amplify/docs/pull/4033

feat(amplify-category-geo): add permissions for suggestions

---

packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-tests/src/__tests__/mock-api.test.ts
packages/amplify-graphql-transformer-core/src/transformation/transform.ts
packages/amplify-graphql-transformer-core/src/transformation/types.ts
packages/amplify-provider-awscloudformation/src/__tests__/graphql-transformer/utils.test.ts
packages/amplify-util-mock/src/api/api.ts
packages/amplify-util-mock/src/api/resolver-overrides.ts

- mark userDefinedSlots in order to prevent the mock to delete them on exit

fix(amplify-util-mock): do not delete overridden slot files on mock exit

---

packages/amplify-category-auth/package.json
packages/amplify-cli/package.json
packages/amplify-nodejs-function-template-provider/package.json

Bump up the conflicting beta package versions.
- @aws-amplify/amplify-category-auth@2.5.1-beta.0 tag already exists
- amplify-nodejs-function-template-provider@2.3.1-beta.0 is already published to npm

chore(version): bump up conflicting beta packages

---

packages/amplify-provider-awscloudformation/src/graphql-transformer/utils.ts

Handle sandbox pull scenario with no environment info.
This fixes the below error.
```
$ amplify pull --sandboxId <app_id>
UndeterminedEnvironmentError: Current environment cannot be determined
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
Successfully generated models. Generated models can be found in /Users/testuser/Projects/eager/src
```

fix(graphql): handle sandbox pull with no environment info

---

packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-many-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/schema.ts
packages/graphql-transformers-e2e-tests/src/__tests__/RelationalTransformers.e2e.test.ts

hasMany directive on a model with queries: null generate incorrect filter input for Scalar list type, this PR will fix that behavior.
```graphql
type Foo @model {
bars: [Bar] @hasMany
}
type Bar @model(queries: null) {
strings: [String]
}
```
Fixes https://github.com/aws-amplify/amplify-cli/issues/9737
- yarn test
- manual test (create api with the provided schema and amplify push)

fix(graphql): hasMany on model with (queries: null) generate correct scalar filter type

---

.circleci/local_publish_helpers.sh
packages/amplify-e2e-core/failed-test-reporter.js
packages/amplify-e2e-tests/package.json

E2E tests are flaky due to the resource constraint and cause the pipeline to fail frequently. When the tests fail, all the tests in that suite gets rerun instead of the ones that failed. This causes the retry to run longer and makes probability of already passed test failing possible. With this change, the retry will run only the failed tests when retrying to run them.
This is an example execution where the only the failed tests were re-run
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/6576/workflows/bb0bd11d-18c7-41ef-8e80-ca607a04ea40/jobs/165144/parallel-runs/0/steps/0-106

ci: retry failed e2e test in ci 

---

packages/amplify-category-auth/provider-utils/awscloudformation/triggers/function-template-dir/trigger-index.js

adds `context` argument to entrypoint handler, passes on to custom module handler
fixes #9563
ref #8102

fix: add `context` to custom function handler entrypoint, ref #9563

---

packages/amplify-graphql-auth-transformer/src/__tests__/owner-auth.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/utils/schema.ts
packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-index-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/resolvers.ts
packages/amplify-graphql-transformer-core/src/index.ts
packages/amplify-graphql-transformer-core/src/utils/index.ts
packages/amplify-graphql-transformer-core/src/utils/schema-utils.ts

- fix key schema lookup when using @auth with LSI
- manual deploy using customer schema and validated that succeeded
- added new unit tests

fix(graphql-auth-transformer): fix relational map key schema lookup when using LSI

---

packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-index-transformer.test.ts
packages/amplify-graphql-index-transformer/src/__tests__/amplify-graphql-primary-key-transformer.test.ts
packages/amplify-graphql-index-transformer/src/graphql-index-transformer.ts
packages/amplify-graphql-index-transformer/src/graphql-primary-key-transformer.ts

This commit adds validation to @primaryKey and @index to disallow
lists for the fields used by these directives.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/5860

fix: disallow lists in @primaryKey and @index fields

---

packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap
packages/amplify-graphql-index-transformer/src/resolvers.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-has-many-transformer.test.ts.snap

Create and update mutations generate a VTL snippet that verifies
that partial sort keys are not provided. However, this snippet
only checks for the arguments in `$ctx.args.input`, which does
not include default or computed values. These values are available
alongside the user inputs in a variable called `$mergedValues`.
This commit updates the argument checking logic to use the
merged values instead of the raw input values.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/9666

fix: include default values in index arg validation

---

jest.config.js
packages/amplify-graphql-auth-transformer/src/__tests__/group-auth.test.ts
packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts
packages/amplify-graphql-auth-transformer/src/resolvers/mutation.update.ts
packages/amplify-graphql-auth-transformer/src/utils/definitions.ts
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
packages/amplify-util-mock/src/__tests__/velocity/model-auth.test.ts
packages/graphql-transformers-e2e-tests/src/__tests__/AuthV2Transformer.e2e.test.ts

- pass parameters into update resolver to properly identity when empty list refers to allow all
-  e2e passes
- unit test and e2e test added

fix(graphql-auth-transformer): update resolver should allow if update operation is set

---

packages/amplify-category-function/src/__tests__/index.test.ts
packages/amplify-category-function/src/index.ts

When pulling or checking out a new environment that had a function with secrets configured, the `secretsPathAmplifyAppId` parameter was not being populated in `team-provider-info.json`. This causes push failures when the parameter cannot be resolved.
The fix updates the function category initEnv logic to copy the appId from `amplify-meta.json` into the correct location in `team-provider-info.json` on init env. This follows the same patter for updating the s3 bucket and key for the function zip asset.
fixes https://github.com/aws-amplify/amplify-cli/issues/8513
Unit test and manually verified that pulling a project into a new directory and then pushing works.

fix: set secretsPathAmplfiyAppId on initEnv when function has secrets

---

packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts

The parameters for OpenSearch should be created in the API stack since they're not easily set in the child stack. Brings us back into alignment with docs.
A related docs PR to switch from elastic to opensearch: https://github.com/aws-amplify/docs/pull/4066
#9728
Created an application and validated that I could set the searchable instance type

fix: move searchable parameters to api stack V2

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/__snapshots__/auth-request-adaptor.test.ts.snap
packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/auth-request-adaptor.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthrough-types/cognito-user-input-types.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-request-adaptors.ts
packages/amplify-e2e-tests/src/__tests__/auth_5.test.ts
packages/amplify-e2e-tests/src/__tests__/auth_7.test.ts
packages/amplify-headless-interface/schemas/auth/1/AddAuthRequest.schema.json
packages/amplify-headless-interface/schemas/auth/1/UpdateAuthRequest.schema.json
packages/amplify-headless-interface/schemas/auth/2/AddAuthRequest.schema.json
packages/amplify-headless-interface/schemas/auth/2/UpdateAuthRequest.schema.json
packages/amplify-headless-interface/src/interface/auth/add.ts
packages/amplify-headless-interface/src/interface/auth/update.ts
packages/amplify-migration-tests/src/__tests__/migration_tests/overrides/auth-migration.test.ts
packages/amplify-util-headless-input/src/__tests__/authVersionUpgrades.ts
packages/amplify-util-headless-input/src/__tests__/upgradePipeline.test.ts
packages/amplify-util-headless-input/src/authVersionUpgrades.ts
packages/amplify-util-headless-input/src/index.ts
packages/amplify-util-headless-input/src/upgradePipelines.ts

passwordRecovery options were mapped to autoVerified attributes in the v1 headless schema. the v2 schema instead specified autoVerifiedAttributes explicitly. Additionally, a translation function is added to map incoming v1 requests to the correct v2 request.
Related docs PR: https://github.com/aws-amplify/docs/pull/4046
fixes https://github.com/aws-amplify/amplify-cli/issues/9756
Manually, added unit tests, updated e2e tests

fix: map headless auth pw recovery to auto-verified attrs

---

packages/amplify-category-interactions/provider-utils/awscloudformation/function-template-dir/index.js.ejs

This PR adds a missing delete handler for the custom LambdaCallout created when adding a Lex bot via the `interaction` category.
https://github.com/aws-amplify/amplify-cli/issues/7996
Manually ran
```
amplify init
amplify add interaction
amplify push
```
confirmed that the bot had been created, then ran
```
amplify remove interaction
amplify push
```
confirmed that the bot no longer existed. Without this change, the bot was still visible in the AWS Lex console.

fix: remove bot from cloud on 'amplify remove interaction'

---

packages/amplify-nodejs-function-template-provider/resources/lambda/crud/package.json.ejs

Move `aws-sdk` to devDependencies because it's already included in the Lambda runtime, bump versions of express and body-parser to latest
Manually setup REST API that integrated the CRUD lambda function template to modify DynamoDB with updated package.json.

fix: aws-sdk to dev dependency for node crud template, bump versions

---

packages/graphql-transformer-core/src/collectDirectives.ts

This commit improves the error messaging during `amplify update api` to be more clear when the developer's graphql syntax is invalid.
Currently, this is the error that the developer sees:
```
🛑 Syntax Error: Unexpected Name "haoentuhaoesnug9r234hbkjekhoasueoa"
GraphQLError: Syntax Error: Unexpected Name "haoentuhaoesnug9r234hbkjekhoasueoa"
at syntaxError (/Users/xss/repos/amplify-cli-dec16/node_modules/graphql/error/syntaxError.js:15:10)
at Parser.unexpected (/Users/xss/repos/amplify-cli-dec16/node_modules/graphql/language/parser.js:1463:41)
at Parser.parseDefinition (/Users/xss/repos/amplify-cli-dec16/node_modules/graphql/language/parser.js:157:16)
at Parser.many (/Users/xss/repos/amplify-cli-dec16/node_modules/graphql/language/parser.js:1518:26)
at Parser.parseDocument …
```

chore: improve graphql syntax error message

---

packages/amplify-cli/src/__tests__/push-notifications.test.ts
packages/amplify-cli/src/extensions/amplify-helpers/auth-notifications.ts

- fix notification logic when API resource directory doesn't exist, for example when api is added with `amplify codegen add --apiId {apiId}`
- manual testing 
-- `amplify init` (remove `securityEnhancementNotification` or init with an older API)
-- `amplify codegen add --apiId {apiId}`
-- `amplify push`
- `yarn test` 
- unit tests added

fix(cli): fix notification logic when API resource directory doesn't exist

---

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/getDependentFunction.test.ts
packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/updateDependentFunctionCfn.test.ts
packages/amplify-category-function/src/index.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/getDependentFunction.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/loadFunctionParameters.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/updateDependentFunctionCfn.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts
packages/amplify-provider-awscloudformation/src/utils/remove-dependent-function.ts

Reverts aws-amplify/amplify-cli#9769
CircleCI Failure: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/6712
Failures in API and Function tests

Revert "fix: use existing rather than deleted models"

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/__snapshots__/auth-stack-transform.test.ts.snap
packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/stack-synthesizer.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/user-pool-group-stack-transform.ts

Adds a dependency from the oAuthCustomResource to the hostedUIProvidersCustomResource. The lack of this dependency caused push failures when updating oAuth config with a new provider as the new provider was not added before attempting to update the provider config.
Also removed some unused method parameters and fixed a class name typo.
fixes https://github.com/aws-amplify/amplify-cli/issues/7388
Manually verified and added a unit test

fix: add HostedUIProvider dependency to OAuth Custom Lambda

---

packages/amplify-util-uibuilder/package.json
packages/amplify-util-uibuilder/src/commands/utils/createUiBuilderComponent.ts
yarn.lock

A failing test is currently blocking the pipeline. This PR fixes the issue by correcting the node_modules path to codegen-ui that was causing the failure.
- e2e tests now pass
- ran uibuilder smoke tests on pkg-cli and amplify-dev

Fix uibuilder e2e tests

---

packages/amplify-console-hosting/package.json

This PR adds a `copyfiles` build step to ensure `amplify-console-hosting/lib/hosting/templates/amplifyhosting-template.json` gets included in the amplify-console-hosting bundle.
The specific test failure that this addresses can be found here: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/6848/workflows/dc278740-e5b8-43ed-96a8-e1438b7d8402/jobs/177994
Full stack trace:
```
error: uncaughtException: File at path: '/home/circleci/repo/packages/amplify-console-hosting/lib/hosting/templates/amplifyhosting-template.json' does not exist date=Mon Mar 07 2022 02:34:01 GMT+0000 (Coordinated Universal Time), pid=571, uid=3434, gid=3434, cwd=/tmp/amplify-e2e-tests/console-hosting_3e649783f_f98f2202, execPath=/usr/local/bin/node, version=v14.18.1, argv=[/usr/local/bin/node, …
```

build: ensure amplifyhosting-template.json is included in final bundle

---

packages/amplify-cli-core/src/customPoliciesUtils.ts

Improve error message when custom-policies.json validation fails. The message will now include the path with the failure message.
fixes https://github.com/aws-amplify/amplify-cli/issues/9861
Tested manually. Message used to look like:
```
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Invalid custom IAM policies in the envvartest function.
Edit <project-dir>/amplify/backend/function/envvartest/custom-policies.json to fix
Learn more about custom IAM policies for function: https://docs.amplify.aws/cli/function/#access-existing-aws-resource-from-lambda-function
should be array
```
and now looks like:
```
🛑 envvartest function custom-policies.json failed validation:
- [0].Resource should be array
✖ An error occurred when pushing the …
```

fix: improve error message on custom policies validation failure

---

packages/amplify-category-api/src/__tests__/provider-utils/awscloudformation/cfn-api-artifact-handler.test.ts
packages/amplify-category-api/src/index.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts
packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts
packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-core/src/utils/projectMeta.ts
packages/amplify-migration-tests/src/__tests__/migration_tests/overrides/api-migration.test.ts

When extensibility was implemented, api updates were blocked unless the resource was migrated. This change allows updates to the resource without requiring an update
fixes https://github.com/aws-amplify/amplify-cli/issues/9675
manually verified and added a migration e2e test

fix: allow api updates without migration

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts

- PreSignUp naming bug fix 
- added unit test checks for permissions

fix: fixes preSignup trigger naming

---

packages/amplify-category-storage/src/commands/storage/update.ts

force ending `amplify update storage` does not print a stray undefined message
Closes #9829
Ran reproduction steps, `undefined` doesn't print anymore

fix: remove stray `undefined` message on `ctrl+c`

---

.eslintrc.js

Relaxes the naming convention rules a bit and removes the rule that requires type information (this was causing linting in some test files to fail and generally making lint slower than it needs to be)

style: relax naming convention rules

---

packages/amplify-category-storage/src/__tests__/provider-utils/awscloudformation/cdk-stack-builder/__snapshots__/s3-stack-builder.test.ts.snap
packages/amplify-category-storage/src/__tests__/provider-utils/awscloudformation/cdk-stack-builder/ddb-stack-transform.test.ts
packages/amplify-category-storage/src/__tests__/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-builder.test.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-builder.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-transform.ts

ListObjectsV2 command requires List permissions to the entire bucket before listing objects in subfolders.
List permissions are assigned using the "ListBucket" permission. Adding multiple statements to the policy required an update to the  s3-stack generator code.
#9439 
1. Add logic in triggerLambda to list all objects in S3 bucket  and subfolders. 
2. Add predictions advance workflow for Rekognition lambda and verify list access permission still works for triggerLambda.

 fix: enable 'listBucket' access to entire bucket for trigger lambda

---

.circleci/config.base.yml

I'm seeing e2e test hosts intermittently running out of memory (see example: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/6860/workflows/e647898f-ad82-46fe-95e2-0735b3310940/jobs/178939). This PR bumps our resource class so that this doesn't happen.

ci: use large CCI hosts

---

packages/amplify-category-auth/src/index.js
packages/amplify-e2e-core/src/init/initProjectHelper.ts
packages/amplify-e2e-core/src/utils/index.ts
packages/amplify-e2e-core/src/utils/transform-current-project-to-git-pulled-project.ts
packages/amplify-e2e-core/src/utils/transformCurrentProjectToGitPulledProject.ts
packages/amplify-e2e-tests/src/__tests__/init-special-case.test.ts
packages/amplify-provider-awscloudformation/src/initialize-env.ts

- Build resource first when adding a new env locally when project is git pulled
- Add missing await
- e2e test for same scenario

fix: build resource when adding new env

---

packages/amplify-category-geo/src/service-walkthroughs/geofenceCollectionWalkthrough.ts
packages/amplify-e2e-core/src/categories/geo.ts
packages/amplify-e2e-tests/src/__tests__/geo-add.test.ts
packages/amplify-e2e-tests/src/__tests__/geo-populate.test.ts
packages/amplify-e2e-tests/src/__tests__/geo-remove.test.ts
packages/amplify-e2e-tests/src/__tests__/geo-update.test.ts

- Adds redirect to `update auth` flow from the flow to add `Geofencing` capability. This helps developers who are getting started with Amplify CLI to easily get setup with their Geofence Collection resource in a single flow without needing them to terminate the `add geo` flow, trigger `update auth` then re-run `add geo`.
- Selects the only cognito group present in the project as default during setting the access permissions for a Geofence Collection resource. Since this is related to permissions, we want to be careful and require the developer to hit `enter` confirming that the selected group is the one he wants to use.
- Added e2e tests for Geofencing capability which includes `add, update and remove` commands.
Tested in JS sample app.
By submitting this pull request, I confirm that my …

fix(amplify-category-geo): trigger update auth flow to add cognito user group

---

.eslintrc.js

- Turns off `no-shadow` in favor of the corresponding TS rule
- Enforces a 50 line limit for functions (excluding comments and blank lines)
- Enforces a max statement depth of 2
- Enforces JSDoc for exported / public class methods, TS interfaces, types and enums

style: tweak a few lint rules

---

.circleci/config.base.yml

Currently, stages are failing in CI because the `scan_artifacts` step takes longer than 10 minutes. CCI kills the process after it takes up 10m without emitting any output.
This PR adds a progress indicator so that on call dev can see the progress and timeouts are prevented.
N/A

ci: prevent timeouts on scan_artifacts job

---

package.json
packages/amplify-e2e-tests/package.json
packages/amplify-provider-awscloudformation/package.json

Currently, some of the packages in the CLI repo have expectations around dependencies existing which they get transitively through lerna (i.e. I don't declare a dependency on `@types/lodash` but it exists in the root because at least 2 deps in the repo do depend on it). This makes a few of those explicit. These were identified while working through a workstream to separate graphql transformers into a new repo (which will be tracked separately).
N/A
Built and ran `yarn test` on the package.
After building, there were no changes to `yarn.lock` which is expected, since there should be no new or changed package version associated with this change, just ensuring that if we were to pull these repos apart, we maintain the right dep tree.
By submitting this pull request, I confirm that my …

chore: explicitly declare some dependencies we're pulling implicitly today

---

packages/graphql-transformer-core/src/__tests__/util/amplifyUtils.test.ts

Currently a unit test in the `graphql-transformer-core` is depending locally on a test in `amplify-provider-awscloudformation` which is not a real dependency, this works today because we can just import the type directly. Removing the reference in this PR and just injecting a mock FF provider for the purposes of the test.
N/A
Test Passes

fix: remove undeclared reference on a type from amplify-provider-awscloudformation from test

---

packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts
packages/graphql-elasticsearch-transformer/src/resources.ts

While prepping to split the first round of data and cli packages, I realized we had a few places where we were importing locally from src, rather than from `lib` of the distributed package. This addresses the two issues I spotted. I was hoping to get a generalized solution and check in place using something like tslint/no-submodule-imports, but it looks like we aren't onboarded w/ tslint yet, and I couldn't get the eslint package no-internal-modules working quite as expected, so ended up just addressing these two.
N/A
Built and ran unit tests.
Current path imports (fails unless local)
* https://unpkg.com/@aws-amplify/graphql-transformer-core@0.16.2/src/transformation/types.d.ts
* https://unpkg.com/graphql-transformer-core@7.4.9/src/TransformerContext.d.ts
Updated path imports
* …

fix: use lib paths instead of src to reference submodule imports across data-cli split

---

packages/amplify-e2e-tests/overrides/override-root.ts
packages/amplify-e2e-tests/src/__tests__/init.test.ts
packages/amplify-migration-tests/src/__tests__/migration_tests/overrides/init-migration.test.ts
packages/amplify-provider-awscloudformation/src/initializer.ts

This PR enables applying auth role overrides to new environments. Replaces https://github.com/aws-amplify/amplify-cli/pull/9677 which could not be updated due to branch protection rules.
https://github.com/aws-amplify/amplify-cli/issues/9643
```
amplify-dev init
amplify-dev override project
amplify-dev push
amplify-dev add env envb
```
Without this change, the result is that `envb` uses an auth role that does not match the override. With this change, `envb` uses an auth role that _does_ match the override.

fix: allow init with auth role name overrides

---

packages/amplify-cli-core/src/deploymentState.ts
packages/amplify-provider-awscloudformation/src/aws-utils/aws-s3.ts
packages/amplify-provider-awscloudformation/src/iterative-deployment/deployment-state-manager.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts

The deployment-state.json is created during "iterative updates" in GraphQL schema deployments. This file is not deleted after completion of the deployment.  Future iterative updates fail if the deployment-state.json file exists but is not in "IDLE" state. 
The fix deletes the deployment-state.json file after the completion of any deployment ( success or failure ) . 
#9665 
manual tests:
1. Force iterative updates on a GraphQL schema.
2. Check deployment-state.json is getting created when deployment is in progress.
3. Validate that deployment-state.json is deleted after deployment concludes.
integration test:
schema-iterative-update-locking test succeeds
- [*] PR description included
- [*] `yarn test` passes
By submitting this pull request, I confirm that my contribution is made under the …

Fix deployment state cleanup

---

packages/amplify-e2e-tests/src/__tests__/init.test.ts

Update sandbox pull e2e test to validate aws-exports.js, models/index.js and models/schema.js files.

fix(test): check aws-exports on sandbox pull

---

packages/amplify-graphql-maps-to-transformer/src/__tests__/__integ__/__snapshots__/with-many-to-many.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/__snapshots__/amplify-graphql-many-to-many-transformer.test.ts.snap
packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-many-to-many-transformer.test.ts
packages/amplify-graphql-relational-transformer/src/graphql-many-to-many-transformer.ts
packages/amplify-graphql-relational-transformer/src/schema.ts
packages/graphql-transformers-e2e-tests/src/__tests__/RelationalTransformers.e2e.test.ts

Currently @manyToMany directive is not including sort key(s) in the relation table and erroring out on gql compile, this is stopping customers from using manyToMany directive when the table contains a sort key. This change will fix that issue.
Fixes https://github.com/aws-amplify/amplify-cli/issues/9526
- yarn test
- manual test

fix(graphql): include sort key(s) in many to many directive relation model

---

packages/amplify-category-api/resources/awscloudformation/container-templates/dockercompose-rest-express/python/requirements.txt

Upgrade flask version for the python api. This is required to fix the failing container api tests.

fix(container-api): upgrade flask version for the python api

---

.circleci/config.base.yml
.circleci/local_publish_helpers.sh

-x64 is now being generated in filenames by generatePkgCli, and needs to be referenced in CCI.

Update pkg cli names to use -x64 when needed

---

packages/amplify-cli-npm/binary.ts

The first invocation of the `amplify` binary takes several seconds on Mac and Windows OSs. This commit moves the first invocation into the postinstall script so that the customer's manual CLI invocation feels snappy.
n/a

chore: prevent cold pkg start by warming binary immediately after installation

---

.circleci/config.base.yml

This PR removes the `-x64` suffix from binary names (introduced when `arm64` support was added) for GitHub releases to support curl installation script.
n/a

ci: use legacy binary names for github releases

---

packages/amplify-cli-npm/package.json

this pr adds a dev dependency to @aws-amplify/cli on @aws-amplify/cli-internal so that when the internal version updates, it propagates the version bump to the public package.

chore: ensure cli stays in sync with internal cli version

---

Dockerfile

our pipeline now requires `awscli` and `cypress`, so our docker image needs to be updated to include all required dependencies so we don't have to install them at run time.

chore: add dependencies necessary for aws-cli and cypress

---

Dockerfile

this pr fixes an issue where the second half of the && update and install instruction isn't being executed. The update appears to have succeeded without incident though
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/7679/workflows/4b4b8234-154b-4502-b3c9-c276826b6d56/jobs/215203

chore: separate update from install steps

---

packages/amplify-category-geo/src/service-stacks/mapStack.ts
packages/amplify-category-geo/src/service-utils/resourceUtils.ts
packages/amplify-e2e-core/src/categories/geo.ts

This PR fixes two small issues causing e2e failures on [geo-remove](https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/7694/workflows/41afd811-2421-4e31-ae3c-103e7144fccd/jobs/217351) and [geo-headless](https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/7694/workflows/41afd811-2421-4e31-ae3c-103e7144fccd/jobs/217351) test suites.

test: fix failing geo tests

---

Dockerfile

Our e2e container docker file installs default-jdk (which is jdk8) as well as explicitly installing jdk 11. Only jdk 11 is needed.

only install java once

---

packages/amplify-appsync-simulator/package.json
yarn.lock

`moment-timezone@0.5.27`, and `@types/moment-timezone@0.5.12` have a mismatch which leads to the error `Property 'tz' does not exist on type 'Moment'`. This will be apparent if you build the package here outside the scope of the monorepo.
Bumping to a newer version of moment which bundles it's own types, and gets rid of this issue.
N/A
`yarn setup-dev && yarn test`

fix: bump moment-timezone, and remove deprecated types dep

---

package.json

`amplify-dev` was showing a warning:
```
➜  amplify-dev init
The following official plugins are missing or inactive:
codegen: util | amplify-codegen@2.28.1
Note: It is recommended to run this command from the root of your app directory
```
This is because the `@aws-amplify/cli` package was renamed to `@aws-amplify/cli-internal` so the nohoist reference also needed to be changed.
n/a
Cloned `master` branch, `yarn setup-dev` and `amplify-dev init` shows the error.
Cloned this branch, `yarn setup-dev` and `amplify-dev init` does not show the error.

chore: fix nohoist of amplify-codegen

---

packages/amplify-nodejs-function-template-provider/resources/lambda/crud/event.json
packages/amplify-nodejs-function-template-provider/resources/lambda/serverless/event.json

To be useful and perform correctly, the event.json structure needs to
conform to the Lambda proxy integration format.  The previous non-proxy
integration default is somewhat misleading.
It could be argued that even this update is slightly misleading since `queryStringParameters` would usually not be used with a `POST` event, but I thought it would be more helpful to include the most common parameters.

docs: ✏️ Provide useful default event structure for APIG fns

---

packages/amplify-graphql-transformer-core/src/cdk-compat/file-asset.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts

This commit updates two `instanceof` checks to instead check
the constructor name. This is done to better support custom
transformers. Because custom transformers `import`/`require`
potentially different copies of the transformer modules,
the `instanceof` checks do not work. This required v2 custom
transformers to rely on `NODE_PATH` hacks and other
workarounds.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/9362
Duplicates https://github.com/aws-amplify/amplify-cli/pull/9970 because @cjihrig's fork of amplify-cli no longer exists so the change cannot be rebased.

fix: improve instanceof checks to support custom transformers

---

.github/CODEOWNERS

Add data gql cohort to codeowners for packages to move, this allows the data team to approve PRs as they take ownership of these packages.
N/A
N/A

chore: add data gql cohort to codeowners for packages to move

---

.eslint-dictionary.json

syntax error occurs in .eslintrc.json because of the missing comma in json array, when execute eslint.
Run `yarn yarn lint-fix`

chore: fix syntax error in .eslintrc.js

---

packages/amplify-graphql-auth-transformer/src/__tests__/owner-auth.test.ts
packages/amplify-graphql-auth-transformer/src/resolvers/subscriptions.ts

This makes subscription resolvers compatible with new default "sub:username" identity claim, and the resolvers are also backwards compatible with the old "username" default.

refactor: use a prefix matching for the claim in subscriptions

---

.circleci/config.base.yml
.circleci/config.yml
.circleci/local_publish_helpers.sh
.eslint-dictionary.json
package.json
packages/amplify-cli-npm/binary.ts
packages/amplify-cli-npm/package.json
packages/amplify-graphql-transformer-core/src/cdk-compat/file-asset.ts
packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts
yarn.lock

Since shipping Amplify CLI 8.0.0, we're vending platform specific binaries downloaded as a post install script of `@aws-amplify/cli` npm package. 
This commit adds compression to the binaries to reduce network overhead of that download, speeding up install times, reducing variability caused by different network conditions, and overall limiting impact on bandwidth for CLI users. A ~72% improvement!
Linux: 696 MB to 197 MB
MacOS: 701 MB to 198 MB
Windows: 690 MB to 195 MB
n/a
* cloud-e2e: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e%2Fxss%2Fbinary-compression&filter=all
* tagged release: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=tagged-release-without-e2e-tests%2Fbinary-compression-2&filter=all
By submitting this pull …

ci: upload gzipped pkg binaries

---

.circleci/local_publish_helpers.sh

Our post install script expects -x64 suffix but it's not being uploaded that way. This commit fixes that.

chore: use -x64 suffix for binaries

---

packages/amplify-cli-npm/binary.ts

There is an accidental space in the amplify binary path. this pr removes it.

fix: remove accidental space from amplify path

---

packages/amplify-cli/src/extensions/amplify-helpers/trigger-flow.ts

In 8.0.0, a change was released that replaced `inquirer` calls with our internal `prompter` library. In doing so, calls that were previously using `inquirer.confirm` were replaced with `prompter.yesOrNo`. This changed the behavior so that the prompter would respond to changes with the `--yes` flag with a yes, rather than default option (which could be no). 
This could cause unexpected code paths to be hit, which manifested in other unnecessary prompts appearing and unnecessary attempts to open programs (like browsers and code editors) emitting cryptic stack traces. These primarily manifested in CI/CD environments.
This change correctly replaces `inquirer.confirm` with `prompter.confirmContinue` instead of `prompter.yesOrNo`. 
Fixes https://github.com/aws-amplify/amplify-cli/issues/10164
- …

fix: use confirmContinue instead of yesOrNo behavior in conversion from inquirer to prompter

---

.circleci/config.base.yml

This change moves the installation of cypress to _before_ the react server has started. This is necessary because there is a race condition where the react development server is starting at the same time that yarn is mucking with `node_modules` contents. This can cause the react server to not start and the pipeline step to fail and require a retry.
n/a

ci: reduce integration-test pipeline step flakiness

---

packages/amplify-cli-npm/binary.ts

When v8.0.0 was released, the behavior for running `amplify uninstall` became... different. 
The `amplify uninstall` command was intended for users of the packaged CLI binary. It essentially causes the binary to self-destruct.
Previously, if amplify was installed via NPM, the cli would do nothing except emit a message instructing the caller to run `npm uninstall -g @aws-amplify/cli` instead of running `amplify uninstall`.
Now in NPM installations, since all cli commands are proxied to a packaged binary, run `amplify uninstall` causes the underlying binary to be destroyed. However, subsequent CLI commands will detect that the binary is missing and reinstall it.
```
npm i -g @aws-amplify/cli
amplify uninstall # success! amplify is removed
amplify version # One sec while I download the …
```

chore: fix amplify uninstall command

---

packages/amplify-graphql-searchable-transformer/src/cdk/create-streaming-lambda.ts

Upgrade searchable streaming python lambda to runtime 3.8
Fixes https://github.com/aws-amplify/amplify-cli/issues/10242
- Manual test
- e2e test in local

fix(graphql): upgrade searchable streaming lambda python version

---

packages/amplify-appsync-simulator/package.json
packages/amplify-category-api/resources/awscloudformation/container-templates/dockercompose-rest-express/express/package.json
packages/amplify-category-api/resources/awscloudformation/container-templates/dockerfile-rest-express/package.json
packages/amplify-category-api/resources/awscloudformation/container-templates/graphql-express/package.json
packages/amplify-category-auth/package.json
packages/amplify-category-auth/resources/adminAuth/admin-auth-package.json
packages/amplify-category-function/package.json
packages/amplify-category-geo/package.json
packages/amplify-category-predictions/package.json
packages/amplify-category-storage/package.json
packages/amplify-cli/package.json
packages/amplify-console-hosting/package.json
packages/amplify-console-integration-tests/package.json
packages/amplify-dynamodb-simulator/package.json
packages/amplify-e2e-tests/package.json
packages/amplify-migration-tests/package.json
packages/amplify-nodejs-function-template-provider/resources/lambda/crud/package.json.ejs
packages/amplify-provider-awscloudformation/package.json
packages/amplify-storage-simulator/package.json
packages/amplify-util-import/package.json
packages/amplify-util-mock/package.json
packages/amplify-util-uibuilder/package.json
packages/graphql-relational-schema-transformer/package.json
packages/graphql-transformers-e2e-tests/package.json
yarn.lock

This PR updates our AWS SDK to ^2.814.0

chore: bump aws-sdk version

---

packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-walkthrough.ts
tsconfig.base.json

Currently, there is a bug for applications using RDS-backed apis with Studio / headless CI environments:
```
amplify init
amplify add api
amplify api add-graphql-datasource # using instructions from https://docs.amplify.aws/cli-legacy/graphql-transformer/relational/
amplify push 
amplify pull # prompts/fails if headless args are set 
```
The root cause of the issue is the RDS metadata is stored in team-provider-info.json, which is not available on `amplify pull` from an empty workspace.
This PR implements a bit of a ~~hack~~ creative solution that reads the necessary values from pulled cloud formation templates when available instead of prompting.
This can be removed when team-provider-info is moved to a service.
n/a
- manually created rds app and pulled it headlessly. failed without the …

fix: remove prompt from rds headless pull

---

packages/amplify-util-mock/src/CFNParser/resource-processors/appsync.ts
packages/amplify-util-mock/src/__tests__/CFNParser/resource-processors/appsync.test.ts
packages/amplify-util-mock/src/__tests__/CFNParser/stack/index.test.ts

Changes the field name provided by the FunctionArn exposed attribute for processed appsync function resources so that it references the correct property.
Previously, the exposed attribute pointed to the 'Ref' field which did not exist. It should point to the 'ref' field. This was causing 'amplify mock api' to fail if the resource's FunctionArn was referenced later on in the template.
I've also updated a related test file to fix a broken test case and lint errors.
No existing issue.
Added a unit test to verify that the property referenced by FunctionArn is defined in the resource.
I've also made this change in my local development environment where I came upon this issue.

fix(amplify-util-mock): Change exposed attr to reference correct attr

---

packages/amplify-provider-awscloudformation/resources/rootStackTemplate.json
packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/__snapshots__/root-stack-builder.test.ts.snap
packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/__snapshots__/root-stack-transform.test.ts.snap
packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-builder.ts

Reverts aws-amplify/amplify-cli#10272
This PR requires a `s3:PutPublicAccessBlock` on the Amplify Role
CREATE_FAILED      DeploymentBucket AWS::S3::Bucket Sat Apr 23 2022 07:24:10 GMT+0000 (Coordinated Universal Time) API: 
s3:PutPublicAccessBlock Access Denied

Revert "fix: update s3 bucket policies to adhere to best practices"

---

packages/amplify-cli/package.json
packages/amplify-provider-awscloudformation/package.json
packages/amplify-util-mock/package.json
yarn.lock

Merged from https://github.com/aws-amplify/amplify-cli/pull/10201 since I no longer have access to push to that branch or update the PR.
Now that each CLI release has a consistent dependency tree for all users, reverting our dependencies for codegen to use caret dependencies.
N/A
`yarn setup-dev && yarn test`

chore: revert to caret version of codegen dependencies after mv bump

---

packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts
packages/amplify-provider-awscloudformation/src/utility-functions.js

Rename some of the `AppSync` named methods in the provider, and leave aliased methods in place for backwards compatibility until clients are migrated off.
N/A
Ran unit tests, remaining tests will run in the pipeline.

chore: alias appsync provider methods, and rename to graphql

---

packages/amplify-provider-awscloudformation/src/upload-appsync-files.js

Create API directory hash with the build directory. The intent is to detect changes in resolvers when the schema has not changed.

fix: remove exclusion of build directory on appsync upload

---

packages/amplify-graphql-auth-transformer/src/__tests__/searchable-auth.test.ts
packages/amplify-graphql-auth-transformer/src/resolvers/search.ts

Pulls in support for query requests and search with colon delimited claim to handle both `<username>` claim and `<sub>::<username>` claim. Built on top of https://github.com/aws-amplify/amplify-cli/pull/10196.

feat: support search with colon delimited claim

---

packages/amplify-graphiql-explorer/config/webpack.config.js
packages/amplify-graphiql-explorer/public/index.html

After a discussion with @josefaidt , the Initial change which explicitly initialized global.buffer in `polyfills.ts` has been removed and the `buffer` library is now imported through a webpack.config plugin. 
10304
amplify mock does not correctly render GraphiQL explorer and Cognito fails OIDC token generation with the error
"Error: Error when generating OIDC token: Buffer is not defined". 
The change explicitly defines global ( if missing on platforms ) and assigns buffer to global .
Test:
```
amplify add api   (graphql + cognito user pools + iam auth)
amplify mock 
```
and Update graphql schema 
```
type Todo
@model
@auth(rules: [{ allow: public }, { allow: private, provider: iam }]) {
id: ID!
name: String!
description: String
}
```
GraphiQL UI works fine.
- [*] PR description included …

fix: explicitly assign buffer to node.global

---

packages/amplify-provider-awscloudformation/src/upload-appsync-files.js

Reverts aws-amplify/amplify-cli#10248

chore: Revert "fix: remove exclusion of build directory on appsync upload"

---

yarn.lock

chore: update yarn.lock to resolve to the same version of ejs

---

packages/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts

Add `--no-bin-links` flag to both yarn and npm install commands to prevent packaging issues for nodejs

fix: prevent symlinks on nodejs package install

---

packages/amplify-provider-awscloudformation/src/__tests__/system-config-manager.test.ts
packages/amplify-provider-awscloudformation/src/system-config-manager.ts

When using credential_process in the AWS profile (to get SSO to work for example) the ProcessCredentials Provider is used.
When using the default chain from the aws-sdk no options are passed to it and it default to using AWS_PROFILE.
With this change, we detect ```credential_process``` and specifically pass the profile name into the credential chain to ensure it gets used.
The problem this solves for me is when using multiple environments.
When adding an environment with ```aws env add``` even though a profile is picked, if it is using credential_process it won't be used.
In my patrticular use case the environments are in multiple accounts.
I suspect most people are using environments in the same account and have an AWS_PROFILE set so the default fallback works.
I haven't added any tests …

fix(amplify-provider-awscloudformation): Ensure the right profile is used with SSO and with credential_process

---

packages/amplify-category-analytics/src/provider-utils/awscloudformation/cloudformation-templates/pinpoint-cloudformation-template.json

When an AppId is provided the analytics module is not responsible for creating the pinpoint
resource. There is a condition named ```ShouldCreatePinpointApp``` to check for this.
The auth and unAuth roles had this permission specified, which is unnecessary as the resources
within them already have an if which outputs different values based on this condition.
My app was failing to be able to UpdateEndpoint before I made these changes

fix(amplify-category-analytics): ensure pinpoint permissions are created

---

.circleci/config.base.yml

Creates a CI trigger to run the full test suite nightly.

chore: enable cron for full test suite

---

.circleci/config.base.yml

Fixes the broke master runs and creates a nightly workflow for running e2e test suite.

chore: remove the nightly workflow from build/test/deploy and add its own workflow

---

packages/amplify-provider-awscloudformation/src/graphql-transformer-factory/directive-definitions.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer-factory/transformer-factory.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema-v1.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema-v2.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts

chore: wrap getTransformerFactory behind a single API

---

packages/amplify-provider-awscloudformation/src/graphql-transformer-factory/directive-definitions.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer-factory/transformer-factory.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema-v1.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema-v2.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts

This reverts commit bff1ce505ea8c6483be05a9144e83a648f950897.

Revert "chore: wrap getTransformerFactory behind a single API (#10373)"

---

.eslint-dictionary.json
packages/amplify-cli/src/plugin-helpers/scan-plugin-platform.ts
packages/amplify-cli/src/plugin-helpers/verify-plugin.ts
packages/amplify-cli/src/plugin-manager.ts

refactor: plugin platform code cleanup

---

packages/amplify-provider-awscloudformation/src/graphql-transformer-factory/directive-definitions.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer-factory/transformer-factory.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema-v1.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema-v2.ts
packages/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts

This reverts commit c2629f6ac6aba05d205e6a3622a8cfa9f8c2d0bf.

Revert "Revert "chore: wrap getTransformerFactory behind a single API (#10373)" (#10390)"

---

packages/amplify-cli/src/__tests__/commands/upgrade.pkg.test.ts
packages/amplify-cli/src/commands/upgrade.ts

Spawn amplify cli after upgrade to allow the kernel to load process into memory. This resolves the cold-start problem for CLI post `amplify upgrade`.
Thank you for your Pull Request! Please provide a description above and review
the requirements below.
-->
1. update code to disable checks for dev-mode or version-check
2.`amplify upgrade`
3. validate that CLI is executed and the version of the latest amplify cli is displayed on the screen. 
4. `time amplify --version`
Repeat the above process with an upgrade from an older version of the CLI.

chore: reduce time required to re-run amplify-cli after upgrade

---

packages/amplify-cli-npm/binary.ts

The PR replace the current raw cloudfront distribution with an aliased end point

feat: alias cloudfront package destination 

---

packages/amplify-category-api/src/__tests__/graphql-transformer/graphql-push-schema-checks.test.ts
packages/amplify-category-api/src/graphql-transformer/api-utils.ts

Use `OpenSearchInstanceType` for transformer v2 pre push check. `ElasticSearchInstanceType` will be checked afterwards when OS is not found
fix #10362 

fix: opensearch instance type check during push

---

packages/amplify-util-mock/src/utils/lambda/populate-cfn-params.ts

Fix unused parameter `_` shadowing `lodash` and causing the error on `amplify mock function`: `_.get is not a function`
Failing e2e test: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/8554/workflows/2a064fa1-f90d-475c-a9ef-1600b686b548/jobs/254635

fix(amplify-util-mock): fn parameter shadowing lodash

---

package.json
yarn.lock

https://github.com/aws-amplify/amplify-cli/pull/10381 didn't fully fix the issue. Subsequent runs of `yarn` would revert the `yarn.lock` file to the previous state. This PR fixes that.

fix: update transient cross-fetch with resolution

---

packages/amplify-cli/src/commands/plugin/verify.ts

Fix typo
When running amplify plugin verify, I have the following message:
The current directory **faied** Amplify CLI plugin verification
Fix typo error

fix: typo in amplify plugin verify flow

---

packages/amplify-cli-core/src/feature-flags/featureFlags.ts

- added feature flag to allow changing naming convention for primary key connection fields from 
* ff = false (current): toPascalCase(Type, RelatedType, ‘Id’)
* ff = true: toPascalCase(Type, RelatedType, RelatedTypeFieldName)

chore(amplify-cli-core): connection field naming convention feature flag

---

packages/amplify-provider-awscloudformation/src/utility-functions.js

Fix function references for `getGraphQLApiKeys` and `getGraphQLAPIs` by replacing `this` with `module.exports`.
Fixes aws-amplify/amplify-category-api#38
I ran `amplify add codegen --apiId API_ID` in my project and the command completed successfully, whereas it was previously falling with the error: `this.getGraphQLApiKeys is not a function`.

Fix references to `getGraphQLApiKeys` and `getGraphQLAPIs` functions

---

packages/amplify-cli/src/extensions/amplify-helpers/resource-status-data.ts

Currently model codegen fails for datastore enabled api on first push, this change is intended to fix it.
The tests will be added to the data package once this goes live.
- yarn test
- manual test

fix(graphql): resolve model codegen issue on first push for datastore enabled api

---

.circleci/config.yml

Adds a nightly setup job that triggers e2e tests nightly. The new workflow triggers and API call to CI that will start the nightly e2e during after hours.

chore: add nightly trigger for e2e tests

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthroughs/auth-questions.js
packages/amplify-e2e-tests/src/__tests__/auth_4.test.ts

- Checks for authProviders to be an empty array instead of defined
- Updated an e2e test case for the same
- updated unit tests

fix: oauth amplify appId Issue

---

packages/amplify-python-function-runtime-provider/shim/shim.py

Shamelessly borrowed the defaults from https://github.com/awslabs/aws-lambda-powertools-python/blob/29497d47d63b2e795c2a9d81eaca3985dfe8f071/aws_lambda_powertools/logging/lambda_context.py\#L4
Adds context information (if it was not provided already) to lambda functions when amplify mock is run
performed steps in issue, with modified code. Issue appeared to be resolved.

feat: add mock context to python shim

---

packages/amplify-e2e-core/src/utils/sdk-calls.ts
packages/amplify-e2e-tests/src/__tests__/auth_6.test.ts
packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts
packages/amplify-provider-awscloudformation/src/initializer.ts

- duplicates changes from api category repo for parallelizing e2e resources cleanup job
- PR: https://github.com/aws-amplify/amplify-category-api/pull/478
- adds milliseconds to stackName in circleCI env in order to avoid `bucket already exists` issue in the e2e tests
- executed locally the cleanup script

chore: parallelize account and resource cleanup for e2e testing

---

packages/amplify-cli-core/package.json
packages/amplify-cli/package.json
packages/amplify-provider-awscloudformation/package.json
yarn.lock

Update remaining deps for api category (missed in initial PR)
This was generated by installing `npm-check-updates` and running with a filter for the packages in the category Repo.
```
ncu \
--deep \
--update \
--filter "@aws-amplify/graphql-auth-transformer @aws-amplify/graphql-default-value-transformer @aws-amplify/graphql-function-transformer @aws-amplify/graphql-http-transformer @aws-amplify/graphql-index-transformer @aws-amplify/graphql-maps-to-transformer @aws-amplify/graphql-model-transformer @aws-amplify/graphql-predictions-transformer @aws-amplify/graphql-relational-transformer @aws-amplify/graphql-schema-test-library @aws-amplify/graphql-searchable-transformer @aws-amplify/graphql-transformer-core @aws-amplify/graphql-transformer-interfaces …
```

chore: update remaining api category dependencies

---

packages/amplify-cli/src/__tests__/commands/upgrade.pkg.test.ts
packages/amplify-cli/src/commands/upgrade.ts

Reverted code to check version on installation to resolve #10528 
Removed code and test to run amplify --version on the installed binary immediately. 
#10528 
yarn test upgrade.pkg
- [*] PR description included
- [*] `yarn test` passes
- [*] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

fix: revert running amplify version on install

---

.circleci/config.base.yml

Adds the nightly pipeline parameters to the base config to use when setting up the nightly e2e tests. This is to fix this type of error: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/8776/workflows/9a23a616-050f-4ed0-9cad-1e2ba3d0e7f7/jobs/261559

fix: add pipeline parameters from api call to generated config

---

packages/amplify-cli/src/__tests__/commands/diagnose.test.ts
packages/amplify-cli/src/__tests__/flow-report.test.ts
packages/amplify-cli/src/commands/diagnose.ts
packages/amplify-cli/src/commands/helpers/encryption-helpers.ts
packages/amplify-cli/src/domain/amplify-usageData/FlowReport.ts

Generate identical project identifier for flow data and reporter

fix: create same identifier for flow data and reporter

---

.eslintrc.js

Allow template literals because the `avoidEscape: true` option does not account for string templates, and then ends up automatically converting \`'foo' bar\` =>  '\\'foo\\' bar'

style: allow string template literals

---

packages/amplify-e2e-core/src/export/index.ts
packages/amplify-provider-awscloudformation/src/export-resources.ts

This PR updates the `docs.amplify.aws/cli/usage/export-to-cdk` url to use `https://` which makes it clickable from the CLI. It also matches the other links to the docs emitted by the CLI.

chore: update link to use https so that it is clickable from the CLI

---

packages/amplify-cli-core/src/feature-flags/featureFlags.ts

- adds FF required for amplify-category-api package to change the logic around connection field attributes for primary keys

chore: add FF for primary key connection field attributes

---

packages/amplify-e2e-tests/src/__tests__/codegen/add_codegen.ts
packages/amplify-e2e-tests/src/__tests__/delete.test.ts
packages/amplify-e2e-tests/src/codegen/add.ts

Adding a regression test for basic happy-case functionality from https://github.com/aws-amplify/amplify-category-api/issues/38 this issue. Verified that using CLI v8.1.0 will fail the second test here.
https://github.com/aws-amplify/amplify-category-api/issues/38
Ran test, and verified test failed for 8.1.0

chore: add e2e tests for codegen add, both with and without apiId

---

packages/amplify-provider-awscloudformation/resources/rootStackTemplate.json
packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/__snapshots__/root-stack-builder.test.ts.snap
packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/__snapshots__/root-stack-transform.test.ts.snap
packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-builder.ts

Reverts aws-amplify/amplify-cli#10533
Impacts amplify-studio by configuring Block-Public-Access configuration on the deployment bucket.

Revert "chore: block insecure traffic to deployment bucket"

---

packages/amplify-cli-core/src/feature-flags/featureFlags.ts

This adds a new feature flag, not yet defaulting to true for new projects. The purpose is to deep merge directive defaults, so that if the default is:
```json
{
"foo": "bar",
"obj": {
"val": true,
"this": "that"
}
}
```
and a customer provides
```json
{
"obj": {
"val": false
}
}
```
the result will be
```json
{
"foo": "bar",
"obj": {
"val": false,
"this": "that"
}
}
```
instead of the current result, which is
```json
{
"foo": "bar",
"obj": {
"val": false
}
}
```
since only top level values are currently being merged for config defaults.
Documentation PR will be coming, I'm waiting until the feature is actually out. This enables work on the API category
Internally tracked
It's a feature flag, no way to validate changes
By submitting this pull request, I confirm that my contribution is made …

Feature: add disabled flag for deep merging directive defaults

---

.eslint-dictionary.json
packages/amplify-provider-awscloudformation/src/__tests__/graphql-resource-manager/diff-test-helper.ts
packages/amplify-provider-awscloudformation/src/graphql-resource-manager/amplify-graphql-resource-manager.ts

To improve the performance of delta table, data team is working on changing the structure of the delta sync table. This change adds a new GSI on the delta table and this resource definition exists on the api root template.
Amplify deploys the GSI changes iteratively but the current implementation doesn't handle the GSI change if the table exist on the root template. This fix will handle the GSI changes found on the root template of the api.
The tests will be added to the data package along with the delta table gsi change.
- manual test
- yarn test

fix(graphql): handle gsi change iterative update of delta sync table exists on root template

---

packages/amplify-cli-core/src/feature-flags/featureFlags.ts

We will be releasing a fix to an issue in Auth GraphQL V2 transformer that the `ownerField` is not auto-populated when there is a combination of both static group based auth and owner auth rules on a Model type. 
This Feature Flag is added to achieve backwards compatibility for existing V2 Transformer customers after this change is released in the `API` category plugin.
This FF is currently always set to `false` but will be flipped to `true` as default for new customers after the fix is released in the `API` category plugin.
https://github.com/aws-amplify/amplify-category-api/issues/37

Add FF to auto populate owner field if static Auth checks are successful

---

packages/amplify-util-mock/package.json
packages/amplify-util-mock/src/CFNParser/resource-processors/appsync.ts
packages/amplify-util-mock/src/__tests__/api/find-lambda-triggers.test.ts
packages/amplify-util-mock/src/__tests__/api/lambda-invoke.test.ts
packages/amplify-util-mock/src/__tests__/api/lambda-trigger-handler.test.ts
packages/amplify-util-mock/src/api/api.ts
packages/amplify-util-mock/src/api/lambda-invoke.ts
packages/amplify-util-mock/src/api/lambda-trigger-handler.ts
packages/amplify-util-mock/src/utils/dynamo-db/index.ts
packages/amplify-util-mock/src/utils/lambda/find-lambda-triggers.ts
packages/amplify-util-mock/src/utils/lambda/load-lambda-config.ts
packages/amplify-util-mock/src/utils/lambda/populate-cfn-params.ts

Customers with lambda triggers setup on `@model` types in their Appsync API schema [following this guide](https://docs.amplify.aws/cli/usage/lambda-triggers/#as-a-part-of-the-graphql-api-types-with-model-annotation) can now take advantage of this feature to test their triggers in a mock environment by simply using `amplify mock api`.
The asynchronous DDB stream listeners will poll for any available records @ 4 times per sec and invoke the attached `function` trigger. The default configurations that the Amplify CLI uses to create the `function` trigger are used in the mock. 
https://github.com/aws-amplify/amplify-category-api/issues/332
https://github.com/aws-amplify/amplify-category-api/issues/269
Unit and Manual testing with many-to-many triggers-models relationships.
By submitting this …

Add Mocking support for DynamoDB lambda triggers

---

.circleci/config.yml

Changing the nightly e2es to run at 2AM ET so that they are running overnight.

chore: change nightly to 8 hours earlier

---

.circleci/config.base.yml

These triggers aren't being used because the nightlys are invoked here: https://github.com/aws-amplify/amplify-cli/blob/nightly-jobs/.circleci/config.yml.
These also are creating this error that we see in builds:
```
No configuration was found in your project. Please refer to https://circleci.com/docs/2.0/ to
get started with your configuration.
```
Deleting these triggers in favor of the nightly triggers that are invoked via CI API.

chore: remove unused CI triggers

---

.circleci/config.base.yml

- moves console integration steps from beta pipeline to dev
- removes test steps from release pipeline since already executed in dev pipeline
- disabled beta jobs

chore: remove unnecessary beta/release pipeline steps

---

packages/amplify-console-integration-tests/package.json
packages/amplify-e2e-tests/package.json
packages/amplify-migration-tests/package.json

- fixes e2e failures caused by scoping the amplify-e2e-core

chore: fix dependabot alert e2e tests

---

.circleci/config.base.yml

- stop executing console integ tests in PRs e2e

chore: do not execute console integ tests on pr e2e

---

.circleci/config.base.yml
package.json
scripts/github-release.ts
scripts/release-rc.sh

This pull request includes:
- a script to run when promoting an RC to distribution channels (GitHub releases and NPM)
- added CI step to pull the release commit into a release branch so that release can open PR of release commit
- added CI step to reset `main` to match the latest release
- added to GitHub release payload the release commit so that tag/release includes commit

chore: reset release branches

---

packages/amplify-provider-awscloudformation/src/index.ts

Use the region and other options as provided in the client creation call. Will fix the issue with cross region resource mapping.
Uncovered in e2e test failure in unsupported geo region.

fix: use correct region as provided in client call

---

packages/amplify-provider-awscloudformation/src/push-resources.ts

**Problem:**
Amplify Studio is currently using the unzipper library to stream
metatdata files out of the zip file in the customer's deployment bucket
in order to retrieve data it needs for deployments and/or display in the
UI. However, this library is out of active development and has
significant error handling bugs that causing the Amplify Backend control
plane availability to degrade.
**Solution:**
Upload the needed metadata files to the s3 bucket outside of the zip
file so they are accessible with a single GetObject call and reaching
into the zip file is no longer required.
N/A
```
yarn setup-dev
amplify-dev init
amplify-dev add auth
amplify-dev push
```
Manually check the S3 console to see if files exist outside the zip
```
amplify-dev remove auth
amplify-dev push
```
Manually check …

chore: upload metadata files required by Studio to the deployment bucket root

---

packages/amplify-e2e-core/src/init/adminUI.ts
packages/amplify-e2e-core/src/utils/retrier.ts
packages/amplify-e2e-core/src/utils/sleep.ts
packages/amplify-e2e-tests/package.json
packages/amplify-e2e-tests/src/__tests__/api_2.test.ts

Refactored the studio setup polling logic to use the `retry` function in our test utils and tweaked the retry settings. Also used the `BackendEnvironmentName` from the initial response in the subsequent polling calls
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/9603/workflows/61796c9d-787a-40e3-bd4c-b6b041868f74/jobs/302223
ran e2e tests locally in multiple regions

test: fix polling logic in studio e2e test

---

packages/amplify-cli/src/commands/publish.ts
packages/amplify-e2e-core/src/categories/hosting.ts
packages/amplify-e2e-tests/src/__tests__/hosting.test.ts

- Enables yes flag on amplify publish when there no changes in backend for CICD operations
- added an e2e check for above scenario

fix: enables -yes flag on amplify publish

---

.circleci/config.base.yml
package.json
scripts/promote-rc.sh
scripts/release-rc.sh

This pull request does the following:
- removes the `deploy` step at the end of the e2e tests that run when a PR is merged to `dev`
- updates the `release-rc.sh` script to handle releasing an RC from a SHA
- adds a `promote-rc.sh` script to promote the release candidate to release in NPM

Remove deploy from dev

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/__snapshots__/auth-stack-transform.test.ts.snap
packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts

Fixes RefreshToken sometimes not using correct units if it had been manually modified in the past ie https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/606#issuecomment-735740045
use explicit tokenValidityUnits 'days' for userPoolClient refreshToken otherwise units may not match what the CLI implies.
N/A
Added tests and validated CFN.
- [X ] PR description included

use explicit tokenValidityUnits 'days' for userPoolClient refreshToken

---

packages/amplify-util-mock/src/storage/storage.ts

The amplify mock mode does not support [AWS::S3::Bucket FilterRule](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfiguration-config-filter-s3key-rules.html) properly.
Name of FilterRule can be set to `prefix` or `suffix`.
But [the code](https://github.com/aws-amplify/amplify-cli/blob/87d15cb3e1c75fbd978c6fc7966e42b42e5d856a/packages/amplify-util-mock/src/storage/storage.ts#L122) checks only the prefix.
As a result, if you have `suffix` FilterRule, the value of `triggerName` becomes `undefined`, and the amplify mock mode crashes in [the method](https://github.com/aws-amplify/amplify-cli/blob/87d15cb3e1c75fbd978c6fc7966e42b42e5d856a/packages/amplify-util-mock/src/storage/storage.ts#L133).
This PR fixes this issue.
- …

fix: support AWS::S3::Bucket FilterRule properly in the mock mode

---

packages/amplify-appsync-simulator/src/velocity/util/general-utils.ts

`$util.parseJson` function in the simulator doesn't follow the same logic as in Appsync when actually running the resolvers. The latter simply returns `null` when the input cannot be parsed. The only change I added it this one:
```js
parseJson(value) {
try {
return JSON.parse(value);
} catch (_) {
return null;
}
}
```
all the rest if just due to code formatting.

Appsync simulator/fix parse json

---

packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts

In amplify-provider-awscloudformation, pass proxyAgent to `fetch()`.
#8536
- yarn test, then `amplify-provider-awscloudformation:test` is passed.
- In  behind a proxy, set HTTP_PROXY variable and `amplify-dev pull --appId xxxxxx --envName dev`
- I don't set HTTP_PROXY variable and `amplify-dev pull --appId xxxxxx --envName dev`

fix: pass httpProxy agent to node-fetch.

---

.circleci/local_publish_helpers.sh

When running `pkg-all-local` include macos binary

chore: include macos binary when running pkg local

---

.circleci/publish.sh
.circleci/verdaccio.yaml
scripts/finish-release.sh
scripts/promote-rc.sh
scripts/release-rc.sh

Fixes a few different release script issues:
1. adds an if statement in the tagged release script to publish to `@latest` when publishing locally to verdaccio and publish to `@<tag>` when publishing to npm
2. uses `git checkout` instead of `git switch` where applicable because the git version in CCI does not support `switch`
3. Updates the verdaccio config to not allow proxying `@aws-amplify/cli-internal` to npm. This is a safety measure against installing an unexpected version of the CLI when packaging the binaries
4. A few tweaks to the publish scripts that run locally. The main change is fixing the exit code handling logic around merges that cannot be completed automatically
local release scripts were tested as much as possible locally.
Doing an e2e run here to make sure verdaccio …

chore: fix publish scripts and verdaccio config

---

packages/amplify-e2e-core/src/init/amplifyPush.ts
packages/amplify-e2e-tests/src/__tests__/api_2.test.ts

- updates the timeout for api2 e2e test to avoid flakiness

test: update api e2e timeout

---

packages/amplify-cli/package.json
packages/amplify-provider-awscloudformation/package.json
packages/amplify-util-mock/package.json
yarn.lock

Bump the codegen version to `v3.0.5`
The main feature introduced is the modelgen support for custom primary key to be consumed by datastore of amplify libraries. The feature is behind the feature flag and set as false for both old and new projects.

chore: bump the codegen version

---

packages/amplify-cli/src/__tests__/commands/status.test.ts
packages/amplify-cli/src/commands/status.ts

- handle `amplify status api -acm Table` command for multi-file schema api projects
- manual tests

fix: handle status api acm for multi file schema projects

---

packages/amplify-python-function-runtime-provider/src/util/packageUtils.ts

extend file exclusion list to reduce package size
Issue #,
https://github.com/aws-amplify/amplify-cli/issues/5566
https://github.com/aws-amplify/amplify-cli/issues/9919
https://github.com/aws-amplify/amplify-cli/issues/10942 (partially)

Reduce Python package size

---

CONTRIBUTING.md

When setting up environment from scratch (brand new mac with zero tools installed) I noticed that we have the following gaps:
- DynamoDB simulator depends on `java` which is not explicitly mentioned in setup guide.
-  it's hard to discover where `amplify-dev` command is. Therefore adding a line in the CONTRIBUTING guide to add Yarn's global bin to PATH - that's where the `amplify-dev` ends up being.
The result can be seen [here](https://github.com/sobolk/amplify-cli/blob/add-yarn-global-to-contribution-guide/CONTRIBUTING.md#local-environment-setup)

docs(cli): added yarn global bin instruction to CONTRIBUTING guide

---

packages/amplify-dynamodb-simulator/__test__/index.test.js
packages/amplify-dynamodb-simulator/index.js

Under certain circumstances the JVM running DynamoDB simulator may print extra lines before printing out the actual DynamoDB simulator output. For example such output has been observed on Amazon managed device when running existing `reports on invalid dbPath values` test.
```
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true
Invalid directory for database creation.
```
The changes are:
- Change regex that's looking for known error message to be multi-line. I.e. account for the fact that there might be more in the output.
- Add test that covers it.
Added test covering that case.
- [ x] `yarn test` passes
- [ x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
By submitting this pull request, I …

fix: account for extra lines when detecting known dynamodb simulator errors

---

packages/amplify-provider-awscloudformation/src/push-resources.ts

Ora does not support multiple spinners, i.e. when uploads go in parallel with Promise.all on top of them. This is known Ora limitation that leads to corrupted console output.
This change:
- disables spinner at each concurrent file upload.
- adds one spinner on top of batch upload.
Manual verification (no established automation for spinner testing).

fix: upload files spinner when executing amplify push command

---

package.json
scripts/update-data-dependencies.sh
yarn.lock

Today this is executed manually, yanking out of a runbook and instead codifying as a build target.
N/A
Ran locally, and node-check-updates ran as expected.

chore: add build target to simplify bumping data dependencies

---

packages/amplify-environment-parameters/package.json

Fix amplify-environment-parameters. Mark it as public. To avoid.
```
lerna http fetch PUT 402 https://registry.npmjs.org/@aws-amplify%2famplify-environment-parameters 706ms
lerna ERR! E402 You must sign up for private packages
```
- [x ] `yarn test` passes

fix: mark amplify-environment-parameters as having publish access

---

packages/amplify-provider-awscloudformation/src/graphql-resource-manager/amplify-graphql-resource-manager.ts

Add in a condition to detect destructive updates when a sort key is added to a primary key, currently there is no warning and deploys just fail, using the `--allow-destructive-graphql-schema-updates` flag doesn't work
This is tied to the API category PR which adds in the sanity check and warning https://github.com/aws-amplify/amplify-category-api/pull/714
This is the same condition that I used in the API category, manually tested to verify it picks up the right changes

fix: detect added sort key

---

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/update-tracked-files.test.ts
packages/amplify-cli/src/commands/push.ts
packages/amplify-cli/src/extensions/amplify-helpers/update-tracked-files.ts

This inserts a whitespace in the `cli-inputs.json` file on `amplify push` when `AttributesRequireVerificationBeforeUpdate` is detected in the local build directory and not in the cloud-backend build directory.
The build directory is not usually tracked for local <--> cloud diffs, so updating the cli-inputs.json file (a tracked file) will allow a push without `--force` tag. When the whitespace is inserted, the `push` script detects a change in the and will push the entire updated build directory.
I performed the following test:
- install amplify v9.2.1
- run `amplify init` on project
- run `amplify add auth` on project
- run `amplify push` on project
- run `amplify-dev` pull with the locally build bin
- run `amplify-dev push`
Result: the CLI detects a change and will update the auth …

feat: append whitespace to cli-inputs.json for updated build dir

---

packages/amplify-provider-awscloudformation/src/__tests__/utils/auto-updates.test.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts
packages/amplify-provider-awscloudformation/src/utils/auto-updates.ts

This sets up a function that will check the diff between the local build directory and the `#cloud-backend` directory to check for diffs and let the developer know (via console output warning) that generated files have changed. This PR looks specifically for Cognito attributes related to user verification, and lets the user know that the generated files have been changed and will be updated in their Amplify app for them. 
Unit tests; ensure all integration tests are passing.

feat: show warning when the cloud backend build dir does not match local backend build dir

---

.circleci/config.base.yml
.circleci/publish.sh
packages/amplify-cli-core/src/errors/amplify-exception.ts
packages/amplify-cli/src/attach-backend-steps/a40-generateFiles.ts
packages/amplify-cli/src/attach-backend.ts
packages/amplify-e2e-core/src/init/amplifyPull.ts
packages/amplify-e2e-tests/package.json
packages/amplify-e2e-tests/src/__tests__/pull.test.ts
packages/amplify-environment-parameters/src/environment-parameter-manager.ts
scripts/unified-changelog.ts

Reinstates some logic that was removed in https://github.com/aws-amplify/amplify-cli/pull/10679
When pulling a project that hits the "restore backend" codepath (ie when the #current-cloud-backend directory does not exist), previous versions of the CLI would read in the `team-provider-info.json` file before wiping and reconstructing the `amplify` directory contents. The above PR removed this read which caused the TPI file to not be fully reconstructed on pull. This PR reinstates the initial read and reinstates the original code for including the TPI contents in the reconstructed file.
**update**
A few additional patches have been added to this PR:
1. There was a bug in the stack trace assignment in AmplifyException that has been fixed
2. The changelog generation logic has been fixed to …

fix: retain TPI on "restore backend" codepath

---

.circleci/config.base.yml
.circleci/config.yml

This change updates our caching so that we don't need to cache yarn dependencies and executables twice.
Currently, we build the binaries with both linux and windows, but our binary build process actually builds both.
Moving forward, our linux executor will build the binaries, cache them, and then the linux & windows executors can utilize the binaries from the same cache.
This should shave some time off our e2e pipeline because the windows build process takes almost 30 minutes sometimes, and our linux build process is much faster, in about 10 minutes.
From 27 minutes down to 9 minutes for our 'build' command.
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/11290/workflows/1741745d-f156-41dd-bdc7-311d8e59bf54
Here are the e2e results: …

Update CircleCI jobs and cache to speed up e2e

---

packages/amplify-e2e-core/src/utils/nexpect.ts

This is a follow up to fix additional issues with Geo, and any test that uses sendCtrlA.
Problem: sendCtrlA was also sending a carriageReturn, which might unintentionally skip any prompts after it. Tests were using sendCtrlA and following it up with sendCarriageReturn, which produced 2 carriage returns (bad).
Example, in geo-remove-3
Solution: sendCtrlA will no longer send a carriageReturn. All existing tests will continue to explicitly use sendCarriageReturn after using sendCtrlA.
E2E Results (All Passing): https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/11427/workflows/350ad677-bbb9-4b72-8d4a-069ab2819d91
Tests that were affected by this, based on usage of sendCtrlA+sendCarriageReturn, call chain depth of 2:
auth_1.test.ts
auth_4.test.ts
auth-migration.test.ts …

fix: bug with carriage return after ctrl A

---

packages/amplify-cli/src/__tests__/init-steps/s0-analyzeProject.test.ts
packages/amplify-cli/src/init-steps/s0-analyzeProject.ts

This commit reverts a part of https://github.com/aws-amplify/amplify-cli/pull/10679
As part of that change, we no longer checked the contents of the team-provider-info file to determine if an environment already exists when doing an `amplify init`. This caused some issues for customers using init to attach existing environments to their local projects. We now fall back to checking the contents of the `team-provider-info.json` file for existing environments on init.
https://github.com/aws-amplify/amplify-cli/issues/11120
Manually tested, added unit tests and running the e2e tests here: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/11461/workflows/049075f2-67e0-4327-bbe3-b6067b8160ea
By submitting this pull request, I confirm that my contribution is made under the terms …

fix: fallback to tpi when looking for existing envs on init

---

packages/amplify-appsync-simulator/package.json
packages/amplify-category-auth/package.json
packages/amplify-category-custom/package.json
packages/amplify-category-function/package.json
packages/amplify-category-geo/package.json
packages/amplify-category-hosting/package.json
packages/amplify-category-notifications/package.json
packages/amplify-category-storage/package.json
packages/amplify-category-xr/package.json
packages/amplify-cli-core/package.json
packages/amplify-cli-logger/package.json
packages/amplify-cli/package.json
packages/amplify-container-hosting/package.json
packages/amplify-dynamodb-simulator/package.json
packages/amplify-environment-parameters/package.json
packages/amplify-frontend-ios/package.json
packages/amplify-frontend-javascript/package.json
packages/amplify-graphql-migration-tests/package.json
packages/amplify-nodejs-function-runtime-provider/package.json
packages/amplify-prompts/package.json
packages/amplify-storage-simulator/package.json
packages/amplify-util-headless-input/package.json
packages/amplify-util-mock/package.json
packages/amplify-util-uibuilder/package.json

Add jest flag `--logHeapUsage` to track how much memory our unit tests are using
`yarn test`

chore: log heap usage on unit test runs

---

.circleci/local_publish_helpers.sh

Currently, building our binaries for arm64 adds a significant amount of time to our release process, largely due to errors with generating bytecode that occur on every file in node_modules. This process typically takes about 35 minutes to run, but is currently taking 1h 19m due to a recent increase in our node_modules folder. The additional time has led to failures with publishing our binaries to S3 due to a 1h timeout for our aws cli login.
This change reduces the time it takes to build our CLI binaries on release,release_rc,run-e2e-with-rc, & tagged-release branches by about an hour, by eliminating the bytecode errors. As a result, our CLI binaries can successfully publish to S3 again.
Resulting files in S3:
CI Run:
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/11594/ …

fix: release process fails due to timeout from bytecode issues with arm64

---

.github/workflows/issue-pending-response.yml

adds GitHub action to remove `pending-response` label when issue author responds, thus helping us define an entrypoint to triaging without also relying on GitHub notifications
n/a

feat: add github action to remove pending-response labels

---

packages/amplify-util-uibuilder/src/__tests__/shouldRenderComponents.test.ts
packages/amplify-util-uibuilder/src/__tests__/syncAmplifyUiComponents.test.ts
packages/amplify-util-uibuilder/src/clients/amplify-studio-client.ts
packages/amplify-util-uibuilder/src/commands/generateComponents.ts
packages/amplify-util-uibuilder/src/commands/utils/shouldRenderComponents.ts

problem: having the admin check as a part of the studio client instance assumes the app is already studio enabled
solution: move out studio app check into static function and also don't throw error on failed app check this is so other flows are not blocked

fix(amplify-util-uibuilder): make studio app check static

---

packages/amplify-cli/src/__tests__/extensions/amplify-helpers/delete-project.test.ts
packages/amplify-e2e-core/src/utils/nexpect.ts
packages/amplify-provider-awscloudformation/src/amplify-service-manager.ts

Merging into `tpi-multi-env-refactor`
- fixed an issue where on an environment parameter was not correctly injected on Windows
- updated spinner mock for failing delete unit test
- some lint fixes
e2e passed: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/11850/workflows/fc91151e-5fbb-4ceb-914f-550a6ced5acd

fix: account for Windows only params in nexpect

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/synthesize-resources.ts
packages/amplify-e2e-tests/src/__tests__/init-special-case.test.ts

Fixes https://github.com/aws-amplify/amplify-cli/issues/11211 .
The fix is to use `cli-inputs.json` instead of `parameters.json` for identity pool related logic.
https://github.com/aws-amplify/amplify-cli/issues/11211
- Got manual repro of https://github.com/aws-amplify/amplify-cli/issues/11211 working.
- Ran `auth_3` e2e tests that are covering a former bugfix related to change that broke init
- Added user pools to the `test init on a git pulled project` to cover this regression.
- [ x] `yarn test` passes
- [ x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)

fix: failing env init when user pool is defined

---

.github/workflows/issue-pending-response.yml

Scopes down built-in GITHUB_TOKEN to only allow issue read/write
tested in a dummy repo to ensure token has necessary permissions

chore: scope GITHUB_TOKEN to only issue write

---

packages/amplify-prompts/src/flags.ts

Adds an internal environment variable check to the printer debug logic so that debug logs can be printed by setting an environment variable.
This will allow us to get debug logging in local or test environments without having to specify `--debug` to every command
Manually tested

chore: add internal debug env var to printer

---

packages/amplify-cli/src/attach-backend-steps/a10-queryProvider.ts
packages/amplify-cli/src/attach-backend-steps/a30-initFrontend.ts
packages/amplify-cli/src/attach-backend-steps/a40-generateFiles.ts
packages/amplify-cli/src/commands/export.ts
packages/amplify-cli/src/commands/push.ts
packages/amplify-cli/src/config-steps/c0-analyzeProject.ts
packages/amplify-cli/src/config-steps/c1-configFrontend.ts
packages/amplify-cli/src/config-steps/c2-configProviders.ts
packages/amplify-cli/src/context-extensions.ts
packages/amplify-cli/src/execution-manager.ts
packages/amplify-cli/src/extensions/amplify-helpers/on-category-outputs-change.ts
packages/amplify-cli/src/extensions/amplify-helpers/show-helpful-provider-links.ts
packages/amplify-cli/src/init-steps/s0-analyzeProject.ts
packages/amplify-cli/src/init-steps/s1-initFrontend.ts
packages/amplify-cli/src/init-steps/s2-initProviders.ts
packages/amplify-cli/src/init-steps/s9-onSuccess.ts
packages/amplify-cli/src/plugin-helpers/verify-plugin.ts

- Remove dynamic require()s where possible in the `amplify-cli-internal` package
- Converted a number of `.forEach` loops to `for...of` for simpler `await` usage
`yarn test`, e2e passes

refactor(amplify-cli): convert require()s to import()s

---

packages/amplify-e2e-tests/src/__tests__/hostingPROD.test.ts
packages/amplify-e2e-tests/src/__tests__/tags.test.ts

Recently, we've been getting alerts due to CloudFront distributions pointing to buckets that don't exist.
This is being caused by a condition where we delete the bucket, and then delete the project afterwards.
The CloudFront distribution momentarily exists without a bucket, and triggers the alert.
If you are curious why we need to manually delete the s3 bucket afterwards, its because of this bug:
https://github.com/aws-amplify/amplify-cli/issues/10478
Here is a successful E2E run with these changes:
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/12047/workflows/11f327a9-4364-4f92-9749-3a70d7b28cb7

chore: fix dangling bucket bug that triggers alerts

---

packages/amplify-category-notifications/src/__tests__/notifications.test.ts
packages/amplify-category-notifications/src/migrations/index.ts

- notifications `update` command is just an alias, the migration check should look for `configure`
- manual test

fix: trigger analytics migration on update/configure notifications

---

.github/ISSUE_TEMPLATE/1.bug_report.yaml
.github/ISSUE_TEMPLATE/2.feature_request.yaml
.github/ISSUE_TEMPLATE/3.usage-question.md

Adds `pending-triage` to all new bug and feature request issue submissions. This will help automate the triage workflow and reduce overhead of manually assigning this label by converging on using `pending-triage` as the triage entrypoint rather than both "no label" and "pending-triage"
**UPDATE:** 
also adds `pending-triage` to new question submissions, further consolidating the triage entrypoint

chore: add `pending-triage` to new bug, feature, question issues

---

packages/amplify-cli/src/__tests__/context-manager.test.ts
packages/amplify-cli/src/__tests__/execution-manager.test.ts
packages/amplify-cli/src/__tests__/test-aborting.test.ts
packages/amplify-cli/src/amplify-exception-handler.ts
packages/amplify-cli/src/domain/amplify-usageData/NoUsageData.ts
packages/amplify-cli/src/domain/amplify-usageData/UsageData.ts
packages/amplify-cli/src/domain/amplify-usageData/UsageDataTypes.ts

- prints the deepest amplify exception only
- on debug prints third party exception
- manual changes

fix: updates to error handler print format

---

packages/amplify-e2e-core/src/utils/nexpect.ts

Fixed an issue where an environment parameter was not correctly injected on Windows. This is not currently affecting any e2e tests, but it caused failures in this closed [PR](https://github.com/aws-amplify/amplify-cli/pull/11226).
The reason the original code doesn't work is because of these lines, [here](https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-e2e-core/src/utils/nexpect.ts#L701) and [here](https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-e2e-core/src/utils/nexpect.ts#L706), that `unshift` a parameter on Windows environments.
e2e passed in another PR targeting a feature branch: https://github.com/aws-amplify/amplify-cli/pull/11223
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

test(amplify-e2e-core): account for Windows only params in nexpect

---

.eslint-dictionary.json
packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-core/src/utils/projectMeta.ts
packages/amplify-e2e-tests/schemas/model_with_owner_and_iam_auth.graphql
packages/amplify-e2e-tests/src/__tests__/import_auth_1.test.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts

Add the default unauth role name reference for import auth since it is required for child stacks.
Fix https://github.com/aws-amplify/amplify-category-api/issues/677

fix: add default ref for unauthrole for imported auth

---

packages/amplify-cli-core/src/feature-flags/featureFlags.ts

* Enable the feature flag by default to auto-set `@index` names.
* Relevant Docs Update: https://github.com/aws-amplify/docs/pull/4801
N/A
Running e2e suite with feature flag enabled by default. Verified docs examples, and verified a few `@hasMany` relationship examples to verify that custom indexes work in relationships, and codegen is consistent with `gql-compile` output.

feat: enable auto-naming indexes for new project

---

packages/amplify-e2e-tests/src/__tests__/uibuilder.test.ts
packages/amplify-util-uibuilder/package.json
packages/amplify-util-uibuilder/src/__tests__/createUiBuilderComponent.test.ts
packages/amplify-util-uibuilder/src/__tests__/generateComponents.test.ts
packages/amplify-util-uibuilder/src/__tests__/syncAmplifyUiComponents.test.ts
packages/amplify-util-uibuilder/src/commands/utils/codegenResources.ts
packages/amplify-util-uibuilder/src/commands/utils/syncAmplifyUiBuilderComponents.ts

Use the default theme from amplify ui in the users project if they don't own their own themes.
Upgrade codegen-ui in util-uibuilder package
https://app.asana.com/0/1202185248783861/1203287913178604/f
Unit test
In a new account without a theme, I went through the getting started instructions for Form builder. And the default theme was used and generated instead.

fix: generate default theme if user has no themes

---

packages/amplify-headless-interface/src/interface/api/add.ts
packages/amplify-headless-interface/src/interface/api/update.ts

Add config option to API headless for extending API keys
https://github.com/aws-amplify/amplify-category-api/issues/598
No functional changes yet, this is an optional addition to headless input

feat: add API key extension headless config

---

packages/amplify-category-geo/src/__tests__/service-utils/mapParams.test.ts
packages/amplify-category-geo/src/service-utils/mapParams.ts
packages/amplify-category-geo/src/service-walkthroughs/mapWalkthrough.ts
packages/amplify-headless-interface/schemas/geo/1/AddGeoRequest.schema.json
packages/amplify-headless-interface/src/interface/geo/add.ts

- Two new map styles were added.
- "RasterHereExploreSatellite"
- "HybridHereExploreSatellite"
https://github.com/aws-amplify/amplify-cli/issues/11261

feat(category-geo): add two new map styles 2022.10

---

CONTRIBUTING.md
package.json

Removed git precommit hook for yarn lints.
Currently, the linter is configured suboptimally, and creates many warnings in the codebase. The precommit hook would fail if there were any linter errors. This implicitly encourages skipping the precommit hook altogether. The precommit hook runs other important scripts that should not be skipped. Disabling the precommit lint check will allow the other precommit scripts to be a part of the developer workflow.
Also updated `CONTRIBUTING.md` to change the reference to the non-existent `lint` npm script, and updated the example husky object.
Reinstalled dependencies, verified that the `husky` hooks were being called with `HUSKY_DEBUG=true`.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

fix: remove precommit hook for lints

---

packages/amplify-cli-core/src/feature-flags/featureFlags.ts

Enabling Custom Primary Key feature flag for new projects.
Docs updates will be posted independently by Product.
N/A
Tests + E2E Tests will run.
[E2E Test Run](https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/12463/workflows/c34fe08a-5d74-43b0-9f84-1bb8bb8d9db4)

feat: enable cpk feature flag for new projects

---

packages/amplify-category-auth/resources/overrides-resource/auth/package.json
packages/amplify-category-auth/resources/overrides-resource/userPoolGroups/package.json
packages/amplify-category-custom/resources/package.json
packages/amplify-category-storage/resources/overrides-resource/DynamoDB/package.json
packages/amplify-category-storage/resources/overrides-resource/S3/package.json
packages/amplify-cli-core/resources/overrides-resource/package.json
packages/amplify-provider-awscloudformation/resources/overrides-resource/package.json

Update `@aws-amplify/cli-extensibility-helper` to correct version that's based on CDK v2 in override templates.
- [ x] `yarn test` passes

fix: update override templates use extensibility helper with CDK v2

---

packages/amplify-e2e-core/src/utils/index.ts

Fixes type mismatch in the `amplify-e2e-core` module. Introduced in https://github.com/aws-amplify/amplify-cli/pull/11365.

fix: parse true and false strings from env vars

---

.circleci/local_publish_helpers.sh

-  fix for arm64 binary pkg fail from tagged release branch : https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/12428/workflows/c68e39e3-441d-4f14-923e-953a2a51fa62/jobs/476066
- Inspired from this : https://github.com/vercel/pkg#other-considerations 
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/12428/workflows/c68e39e3-441d-4f14-923e-953a2a51fa62/jobs/476066
- fix tested on tagged-release branch : https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/12445/workflows/302d61c1-9c93-45f3-adb6-f41f64f77d4a

chore: fix npx pkg arm64 binary creation

---

packages/amplify-e2e-tests/overrides/override-js-error.txt
packages/amplify-e2e-tests/src/__tests__/init_e.test.ts
packages/amplify-provider-awscloudformation/src/initializer.ts

This update ensures that we check if the overrides.js file exist before trying to execute override logic, so that it doens't throw all the time, and we can now throw if there is a runtime error.
E2E run: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/12371/workflows/33547174-f9dc-415c-9e47-b8d918e2bfc9

chore: update initializer logic to perform checks on override files

---

packages/amplify-provider-awscloudformation/src/override-manager/transform-resource.ts

This is a workaround to detect specific override errors coming from the API repository, because if we import AmplifyException in that repo/package it creates a cyclic dependency.
In the meantime, if an error with overrides occurs in the API category, it will throw errors with this special property that we can detect in CLI using this logic.

fix: add check for api repo overrides errors

---

package.json
packages/amplify-graphiql-explorer/package.json
yarn.lock

Updates `babel-loader` to `^8.3.0` in both the root `package.json` and in the `graphi-explorer` package.

chore: upgrade babel-loader to ^8.3.0

---

yarn.lock

Interactive upgrade of `@pmmmwh/react-refresh-webpack-plugin` dependency that bumps dependencies in tree.

chore: bump patch on dependency

---

packages/amplify-category-notifications/package.json
packages/amplify-category-notifications/src/__tests__/apns-cert-config.test.ts
packages/amplify-category-notifications/src/__tests__/apns-key-config.test.ts
packages/amplify-category-notifications/src/__tests__/channel-apns.test.ts
packages/amplify-category-notifications/src/__tests__/channel-fcm.test.ts
packages/amplify-category-notifications/src/apns-cert-config.ts
packages/amplify-category-notifications/src/apns-key-config.ts
packages/amplify-category-notifications/src/channel-apns.ts
packages/amplify-category-notifications/src/channel-email.ts
packages/amplify-category-notifications/src/channel-fcm.ts
packages/amplify-category-notifications/src/channel-sms.ts
packages/amplify-category-notifications/src/validate-filepath.ts

- migrates notifications category to use amplify-prompter library instead of inquirer

chore: migrate notifications category to amplify-prompter

---

packages/amplify-provider-awscloudformation/src/__tests__/admin-login.test.ts
packages/amplify-provider-awscloudformation/src/admin-login.ts

This pull request suppresses errors when the browser fails to launch. This might happen if a developer is using a non-GUI machine to run CLI or the user's machine has blocked processes from launching the browser. The fix suppresses the error and prompts the user to manually populate their Amplify login key.
The PR also replaces the `ora` package with the `AmplifySpinner` in the prompt.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/11240
Fixes: https://github.com/aws-amplify/amplify-cli/issues/11176
Added a unit test that raises an error when `open` is invoked that tests the spinner successfully starts and stops. Additionally, integration tests will be run to ensure no regressions.
By submitting this pull request, I confirm that my contribution is made under the terms of the …

fix: suppress errors when browser launch fails

---

packages/amplify-e2e-core/src/nexpect-reporter.js

I just created this [same PR](https://github.com/aws-amplify/amplify-category-api/pull/1006) in our API repo for an identical change, here is the summary:
Often, when tests fail we are unable to playback the artifacts, and must scan through a bunch of .cast files to figure out the error trail. This process is very manual and slow, often there are ten files or more, and they currently don't print in-order, so you have to look through each one to find the error.
Instead, we can use labels that use timestamps, & and order indicator, so that it is easier to find the file that contains the error, usually the first file that occurs before the "amplify delete" teardown step.
This is BEFORE, it is not possible to quickly identify the error, or to see any type of ordering/metadata about each file: …

fix: add human readable names to artifact files

---

packages/amplify-e2e-core/src/nexpect-reporter.js

Tests are passing in dev, but they show an error due to some jobs having very long artifact names.
This truncates the suffix appended to artifacts to ensure names don't get too long.
Here is the e2e run for this fix: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e/aluja/fix-dev-build-long-names

chore: truncate long file names to fix dev build

---

.circleci/local_publish_helpers.sh

Now that we have 27 e2e accounts, listAccounts requires 2 api calls instead of 1 (automatic pagination , 20 per page).
This is causing us to throttle when all 300+ jobs are starting up. We can avoid this issue by staggering the kickoff time for some of these tests when they try to setup their auth credentials.
I haven't seen the issue pop up again, here is the new e2e run: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/12697/workflows/c5598891-c30f-4d1c-93de-dad5cc9cd3be
Here is the original error:

chore: add random delay to spread sdk calls

---

.circleci/config.base.yml
scripts/github-prerelease.ts

Make release upload arm binary to github.

fix: include arm64 in github release

---

packages/amplify-cli/src/__tests__/attach-backend.test.ts
packages/amplify-cli/src/attach-backend.ts

Fixes an issue where pull when selecting "no" to "do you want to modify this backend" would fail because it was looking for the Amplify AppId in the backend/amplify-meta.json file. This change switches back to using the team-provider-info.json file.
Fixes: https://github.com/aws-amplify/amplify-cli/issues/11415
manually tested, added a unit test and running e2e here: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e/foyleef/no-backend-app

fix: fallback to tpi for amplify app when no backend dir

---

packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts
packages/amplify-cli-core/src/errors/amplify-exception.ts
packages/amplify-e2e-tests/src/__tests__/function-permissions.test.ts

- fixed regression introduced by error name changed for resource policy method not found
- e2e test added

fix: handle lambda permissions for notifications category

---

packages/amplify-util-uibuilder/package.json
packages/amplify-util-uibuilder/src/__tests__/notifyMissingPackages.test.ts
yarn.lock

UI Builder is updating the `@aws-amplify/codegen-ui` and `@aws-amplify/codegen-ui-react` version it uses to `2.5.5` to address the following issues:
* fix checkbox to reflect correct state
* Fix [object Object] displayed for AWSJSON field
* Fix array of JSONs crashing render
* fix “less than char” validation
* recommend versions of ui-react and aws-amplify that will fix predicates
* allow style-related overrides to be passed in
* address model names colliding with component types
* support nested arrays
* allow empty string for URL field
- team bug bash
- `yarn test`

chore: update codegen-ui to 2.5.5

---

.circleci/config.base.yml

Recently, executor names were updated to be more specific:
linux-e2e-executor -> linux-e2e-executor-medium
A recent addition to the config file did not get this update; this fixes that.
Setup succeeded: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e/aluja/update-executor-name-to-fix-build

chore: update to match new executor naming

---

.circleci/config.base.yml
packages/amplify-e2e-tests/src/__tests__/schema-iterative-update-4.test.ts

Currently, we have a 45 minute timeout in CircleCI that prevents tests from running for extended periods of time without providing any updates/progress; we do this on purpose because we don't want tests to hang forever. 
This works great for every test, except this one, which does an 8 step iterative deployment.
This test takes about 45 minutes to run, and doesn't provide any feedback to the test runner (console output). This simple addition will ensure that the test runner knows that progress is being made, and prevent the test from being terminated.

chore: fix 'no console output' timeout for a long running test

---

.github/ISSUE_TEMPLATE/1.bug_report.yaml
.github/ISSUE_TEMPLATE/2.feature_request.yaml

aligns usage of Title Case issue template names
- migrates `Bug report` -> `Bug Report`
- migrates `Feature request` -> `Feature Request`
I'm also open to migrating "Usage Question" to "Usage question". I don't have strong opinions but would prefer consistency
n/a

chore: migrate issue templates name to Title Case

---

packages/amplify-cli/src/index.ts

This is a re-based version of this old PR https://github.com/aws-amplify/amplify-cli/pull/11380. @AaronZyLee 's Commit history is maintained.
This is a follow-up of api PR https://github.com/aws-amplify/amplify-category-api/pull/931 for suppressing the CDK warning msgs to the CLI level to prevent the output in commands other than api category.
These warning msgs are only populated when the debug mode is on.
https://github.com/aws-amplify/amplify-category-api/issues/1048
By running amplify-dev status api -acm <modelName> and amplify-dev mock

fix: suppress CDK deprecation warning in CLI base level

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/__snapshots__/generate-auth-trigger-template.test.ts.snap
packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/generate-auth-trigger-template.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/generate-auth-trigger-template.ts

This adds a `dependsOn` for an auth category resource: Custom Resource has a dependency on Lambda trigger and its IAM resources, so they should be deployed synchronously.
The issue was identified by @awsluja, who has been investigating broken/flaky tests.
Snapshot test unit for this behavior.

fix: add a dependsOn to custom resource for auth trigger

---

packages/amplify-util-uibuilder/package.json
packages/amplify-util-uibuilder/src/__tests__/createUiBuilderComponent.test.ts
packages/amplify-util-uibuilder/src/commands/utils/codegenResources.ts
yarn.lock

- Update codegen packages to 2.5.6 to address the following issue:
- misconfiguring the toggle field component for nested boolean values.
- Update index file generating logic to not render when no valid schemas passed. 

fix: address UI Builder component generation errors

---

packages/amplify-provider-awscloudformation/src/__tests__/graphql-resource-manager/dynamodb-gsi-utils.test.ts
packages/amplify-provider-awscloudformation/src/graphql-resource-manager/dynamodb-gsi-helpers.ts

**Given** that a sort key is specified on an index that is already part of the primary key of the model type, for example,
```
type Todo @model {
id: ID!
createdDate: AWSDateTime! @index(name : "byCreatedDate", sortKeyFields: ["id"])
}
```
**When** a Customer deletes the index and pushes their change with the `enableIterativeGSIUpdates` feature flag set to `true`,
**Then Currently** in the process of deleting the GSI and associated Attribute Definitions, we also delete the Attribute Definition of the primary key from the Table definition.
** With this fix** we add a check that the attributes referenced in the key schema of the Table do not get removed when deleting the GSI related configuration.
Internally Tracked
Unit test and success iterative deploy from a sample app.
By submitting …

fix: iterative gsi deployment - incorrect AttributeDefinitions

---

packages/amplify-cli/src/commands/diagnose.ts

Currently when no backend is pulled (Answer No to "Do you plan on modifying this backend?), diagnose flows fail. Either by triggering an error to be thrown, or by running `amplify diagnose`.
The changes remove assumptions that a backend is always present.
https://github.com/aws-amplify/amplify-cli/issues/11066

fix: diagnose error if backend not pulled

---

.circleci/local_publish_helpers.sh

This changes how do we gate binary size in such a way that:
- we put strict threshold on uncompressed binary size
- we put more permissive sanity check on compressed binary size because compression is not predictable.
Example when compressed size grew but uncompressed dropped.
Left is dev , right is cdkv2 branch.
The sizes has been based on current state of dev.

chore: check uncompressed binary size

---

.circleci/config.base.yml
.github/ISSUE_TEMPLATE/1.bug_report.yaml
.github/ISSUE_TEMPLATE/2.feature_request.yaml
packages/amplify-e2e-tests/src/__tests__/env-unmodified-backend.test.ts
packages/amplify-e2e-tests/src/__tests__/schema-iterative-update-4.test.ts
packages/amplify-e2e-tests/src/environment/env.ts

Changed pullEnvironment test function so that it accepts appId and envName paramaters.
Added 3 E2E tests to test fixes that will be made for Github issues #11372 and #11487.

test(cli): multienv e2e tests revisions

---

.circleci/config.base.yml
nx.json

This PR:
- sets max parallel to 8 for all nx jobs (instead of default 3)
- bumps linux executor to xlarge for build step to bring more cores.
Other considerations.
Setting parallel to 8 is going to slightly speed up local dev loop as well.
Unfortunatelly NX does not allow dynamic configuration based on number of CPUs. So setting this to 8 seems like a good compromise given how powerful average dev machine is.
Linux build
Before:
After:
Windows build
Before:
After:

chore: make build faster

---

.circleci/local_publish_helpers.sh
packages/amplify-cli/bin/amplify.production.template
packages/amplify-cli/src/domain/amplify-usageData/getUsageDataUrl.ts

- injects `production` into the `process.env.NODE_ENV` value in our build
- filters out the usage data for non production builds

chore: filter out usage data from dev instances

---

packages/amplify-provider-awscloudformation/src/initializer.ts

- converts promise-based chain to async await for easier reading

chore: convert storeCurrentCloudBackend from promise-based chain to async await for easier reading

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/handlers/resource-handlers.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/handlers/resource-handlers.ts

auth config parameters are split into environment-specific parameters and environment-agnostic parameters. This splitting happens based on a known set of keys in the config object. However, we were filtering on a "request" object instead of the cliInputs object, causing some keys to slip through the filter
Manually tested and added a unit test.  E2E is running here: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/13359/workflows/c1c5fe14-f1dc-469e-9809-52775cf7b461

fix: properly filter cli-inputs

---

.circleci/config.base.yml
nx.json
package.json

This PR fixes how sources sets are used to determine changes for build and test steps.
Testing in parallel was causing pretty long and non deterministic spin-locks between packages in dependency graph.
I.e. package that was testing itself was writing files that re-triggered build in parallel execution.
Based on https://github.com/nrwl/nx-examples/blob/master/nx.json
and https://nx.dev/more-concepts/customizing-inputs
Before:
After:

chore: fix unit tests parallelization

---

.circleci/config.base.yml
.circleci/config.yml
.circleci/local_publish_helpers.sh
scripts/split-e2e-tests.ts

Currently, our e2e-cleanup script that runs after each e2e workflow takes about 10-20 minutes to run, but we can't trigger a new job or re-run without cancelling the entire workflow.
Cancelling the workflow prevents the cleanup script from running to completion, and we don't want to do that.
As shown below, 95% of cleanup jobs run 36 minutes or less (P95 metric), this will bring the P95 down to ~40 seconds.
This change **delegates the cleanup step to a separate job, that can run independent of the E2E run**, so that we can allocate time to our cleanup script without preventing re-runs of E2E.
This will also allow us to expand on our cleanup script without compromising due to how long it takes to run the cleanup.
Additionally, **tests that don't run on windows no longer depend on the …

chore: delegate cleanup script

---

.circleci/config.base.yml
packages/amplify-e2e-tests/src/__tests__/transformer-migrations/searchable-migration.test.ts
packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js

- Implement exponential backoff at polling cfn events (inspired by https://github.com/aws-amplify/amplify-cli/pull/10959 and https://stackoverflow.com/questions/14969657/setinterval-with-exponential-time-decrease )
- Increase test timeout to accommodate for searchable-migration test duration.
I injected `console.log('Delay ' + delay + ' Attempt ' + readStackEventsCalls);` into `readStackEvents` and ran one of the e2e tests. Below is outcome.
E2E test run.
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/13698/workflows/634b1e55-3c58-49fe-b88e-db161cafb298

fix: back off on cfn event pull

---

packages/amplify-cli/src/__tests__/amplify-exception-handler.test.ts
packages/amplify-cli/src/amplify-exception-handler.ts
packages/amplify-cli/src/index.ts

As per https://nodejs.org/api/process.html#event-unhandledrejection the event `unhandledRejection` is emitted whenever a Promise is rejected and no error handler is attached to the promise. However the promise can be rejected with just a simple message as well like `Promise.reject("message")` instead of an Error object like `Promise.reject(new Error("message")`.
This PR fixes that such that rejection with any message will yield the right message in `AmplifyError` instead of `UnknownFault`
Unit tests for the new method.
However testing the unhandledRejection event handler is blocked on https://github.com/facebook/jest/issues/5620

chore: Handle rejected promises that weren't caught or awaited anywhere in the code

---

packages/amplify-e2e-core/src/utils/add-circleci-tags.ts
packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts

This cleans up orphan App Sync apis  that led to quota exhaustion.
App Sync apis don't carry creation time, so we're adding a tag to track this.

chore: cleanup orphan appsync apis

---

packages/amplify-util-uibuilder/package.json
packages/amplify-util-uibuilder/src/__tests__/utils.ts
yarn.lock

Recent upgrades in `amplify-codegen` in the CLI as well as the major version bump for `@aws-amplify/datastore` has introduced regressions in UI Builder functionality:
* Collection generation for models with relationships is broken
* Accessing `hasOne` and `belongsTo` related records is broken in collections
We have several customers reporting issues in Github. Issue: https://github.com/aws-amplify/amplify-studio/issues/763
The new version of `codegen-ui` addresses the above issues.
unit & e2e tests in `codegen-ui`

fix(amplify-util-uibuilder): update codegen-ui to 2.7.2

---

packages/amplify-cli/package.json
packages/amplify-e2e-tests/src/__tests__/__snapshots__/studio-modelgen.test.ts.snap
packages/amplify-provider-awscloudformation/package.json
packages/amplify-util-mock/package.json
yarn.lock

This fixes an Amplify Studio reported issue with schemas having bi-directional hasOne directives.
E2e test link https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/14376/workflows/38159936-5bba-491f-bbe5-8577daf21ad3

chore: bump codegen version to 3.3.5

---

package.json

This changes the pre-push husky script to run a clean and build before doing the api verification.
Currently, extract-api can generate different outputs when the application hasn't been built clean compared to a clean build. This causes unnecessary runs on the CI when the cleanly built repository fails the api check. Including a clean and rebuild of the packages in the precommit hook will reduce the unnecessary CI runs.

fix: change extract-api to clean and rebuild before running on push

---

packages/amplify-prompts/src/prompter.ts

Updates the selected/unselected indicator in prompt multi-select lists to be more distinct
Before the indicator was a green vs gray ✓, now it is a blue ● or gray ○
PR also includes lint fixes. The only functional change is lines 269-271
Manually validated. There's not really a way to write a unit test for this because it is just tweaking a parameter on the enquirer input

fix: make prompter multi-select indicator more distinct

---

.gitignore
.vscode/amplify-cli.code-workspace
.vscode/settings.json
packages/amplify-e2e-tests/.vscode/settings.json

The `.vscode/amplify-cli.code-workspace` defines two folders in a code workspace. This allows more a more convenient way to run individual e2e tests from the jest test explorer for users of vscode. E2E tests can now be run with the correct configuration inline in the code, or using the test explorer from the main activity bar. 

feat: added code workspace to simplify running individual e2e tests

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/__snapshots__/auth-stack-transform.test.ts.snap
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts

Sets the [NoEcho](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#parameters-section-structure-properties) flag on the OAuth parameter passed to the auth stack. This prevents this parameter from being printed in the CloudFormation console and CloudFormation events
Manually validated and updated existing snapshot tests

fix: set NoEcho flag on OAuth creds CFN param

---

packages/amplify-opensearch-simulator/API.md
packages/amplify-provider-awscloudformation/src/index.ts

Fixes a problem exporting the function to delete parameters from PS that prevented the function from being called with `context.amplify.invokePluginMethod`.

fix: delete from ps export problem

---

packages/amplify-opensearch-simulator/API.md
packages/amplify-provider-awscloudformation/src/__tests__/utils/delete-from-service.test.ts
packages/amplify-provider-awscloudformation/src/index.ts
packages/amplify-provider-awscloudformation/src/utils/delete-from-service.ts
packages/amplify-provider-awscloudformation/src/utils/get-ssm-sdk-parameters.ts

This PR fixes a bug where the wrong key was being passed to the delete handler.

fix: correct deleting wrong keys

---

packages/amplify-cli/bin/amplify
packages/amplify-cli/bin/amplify.production.template
packages/amplify-cli/src/domain/amplify-usageData/getUsageDataUrl.ts
packages/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts

- uses CLI_DEV variable to filter usage data instead of NODE_ENV

fix: do not overload NODE_ENV env parameter for usage data filtering

---

packages/amplify-cli/src/__tests__/usage-data.test.ts
packages/amplify-cli/src/domain/amplify-usageData/UsageDataPayload.ts
packages/amplify-cli/src/domain/amplify-usageData/UsageDataTypes.ts

Persist downstream exceptions in usage metrics that are not of type 'AmplifyException`
Pending items:
unit tests

chore: Persist downstream exceptions in usage metrics

---

packages/amplify-provider-awscloudformation/src/__tests__/aws-utils/aws-cfn.test.js
packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js

Change: do not filter AWS::CloudFormation::Stack type failure events if they have valid error message
While displaying error messages from a failed CFN deployment, library filters out any stack events that are for `AWS::CloudFormation::Stack` type resource. As a result situations where the cfn template had errors are not displayed to the customer. As an example see the before and after CX
**Before**
```console
Deploying resources into prod environment. This will take a few minutes. ⠸
Deploying root stack app11533 [ ---------------------------------------- ] 0/2
Deployment failed.
Deploying root stack app11533 [ ====================-------------------- ] 1/2
amplify-app11533-prod-144550   AWS::CloudFormation::Stack     UPDATE_ROLLBACK_COMPLETE      
functionapp11533bc562f1e …
```

chore: correctly filter failed cfn events for displaying error messages

---

.circleci/config.base.yml

Happened to bump into a missing flag value for `--maxWorkers` when looking through the config files

fix: add missing maxWorkkers parameter to config.base.yml

---

packages/amplify-provider-awscloudformation/src/__tests__/utils/delete-from-service.test.ts
packages/amplify-provider-awscloudformation/src/utils/delete-from-service.ts

Adds a filter to retrieved parameters that ensures that only parameters that begin with "AMPLIFY_" are deleted from PS.

fix: add filter for parameters starting with AMPLIFY_

---

packages/amplify-cli/src/execution-manager.ts
packages/amplify-cli/src/extensions/amplify-helpers/push-resources.ts
packages/amplify-environment-parameters/API.md
packages/amplify-environment-parameters/src/__tests__/environment-parameter-manager.test.ts
packages/amplify-environment-parameters/src/environment-parameter-manager.ts

Add a generic fallback prompt for missing CloudFormation parameter values. Any prompts that handle specific parameters, such as environment variables in the function category, will be executed first.

feat: prompt for missing backend parameters

---

packages/amplify-e2e-core/src/utils/sdk-calls.ts
packages/amplify-provider-awscloudformation/src/utils/delete-from-service.ts

This change skips deleting parameters from parameter store upon deleting an environment or an Amplify project if no app ID can be resolved.

fix: skip deleting from parameter store if no app id

---

packages/amplify-provider-awscloudformation/src/utils/delete-from-service.ts

This change bypasses the delete call to parameter store if there are no parameters to delete.

fix: skip deleting from parameter store if no parameters to delete

---

packages/amplify-category-hosting/__tests__/index.test.js
packages/amplify-category-hosting/__tests__/lib/S3AndCloudFront/configuration-manager.test.js
packages/amplify-category-hosting/__tests__/lib/S3AndCloudFront/helpers/configure-CloudFront.test.js
packages/amplify-category-hosting/__tests__/lib/S3AndCloudFront/helpers/configure-Publish.test.js
packages/amplify-category-hosting/__tests__/lib/S3AndCloudFront/helpers/configure-Website.test.js
packages/amplify-category-hosting/__tests__/lib/S3AndCloudFront/s3Index.test.js
packages/amplify-category-hosting/commands/hosting/remove.js
packages/amplify-category-hosting/index.js
packages/amplify-category-hosting/lib/S3AndCloudFront/configuration-manager.js
packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/configure-CloudFront.js
packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/configure-Publish.js
packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/configure-Website.js
packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/validate-website-doc-name.js
packages/amplify-category-hosting/lib/S3AndCloudFront/index.js
packages/amplify-category-hosting/package.json

- migrate hosting category from inquirer to prompter library

chore: migrate hosting category from inquirer to prompter library

---

packages/amplify-cli-core/src/state-manager/pathManager.ts
packages/amplify-cli/src/initialize-env.ts
packages/amplify-provider-awscloudformation/src/__tests__/system-config-manager.test.ts
packages/amplify-provider-awscloudformation/src/configuration-manager.ts
packages/amplify-provider-awscloudformation/src/system-config-manager.ts

We had some logic to handle AWS credential_process profiles, but we were not actually calling the credential process (or at least not in all cases). This change calls the credential process when we are initially resolving credentials.
I updated some error handling to use AmplifyError and remove some calls to process.exit because it caused some hanging spinners if the credential process fails.
There is also a change to respect the `AWS_CONFIG_FILE` and `AWS_SHARED_CREDENTIALS_FILE` environment variables when resolving the path to the aws config and credentials files.
There are also an unfortunate amount of lint fixes :(
fixes https://github.com/aws-amplify/amplify-cli/issues/11319 https://github.com/aws-amplify/amplify-cli/issues/4488
Manually tested, updated existing unit tests and …

fix: get credentials from credential_process in aws profile config

---

packages/amplify-category-analytics/src/analytics-resource-api.ts
packages/amplify-category-auth/src/index.js
packages/amplify-category-notifications/src/channel-sms.ts
packages/amplify-category-notifications/src/commands/notifications/add.ts
packages/amplify-category-notifications/src/commands/notifications/configure.ts
packages/amplify-category-notifications/src/multi-env-manager.ts
packages/amplify-e2e-tests/src/__tests__/notifications-multi-env.test.ts

- since notifications requires pinpoint analytics and auth to be in the cloud changing env should force a push for the required resources
- fixes the undefined exception when setting the Id to the output section
- small refactoring to remove duplicate code
- e2e test added and manual testing

fix: adding new environment when having a project with notifications

---

.circleci/config.base.yml
.vscode/amplify-cli.code-workspace
packages/amplify-category-auth/package.json
packages/amplify-category-function/package.json
packages/amplify-category-geo/package.json
packages/amplify-category-notifications/package.json
packages/amplify-category-storage/package.json
packages/amplify-cli-core/package.json
packages/amplify-cli-extensibility-helper/package.json
packages/amplify-cli-logger/package.json
packages/amplify-cli/package.json
packages/amplify-dynamodb-simulator/package.json
packages/amplify-environment-parameters/package.json
packages/amplify-frontend-ios/package.json
packages/amplify-graphql-migration-tests/package.json
packages/amplify-opensearch-simulator/jest.config.js
packages/amplify-opensearch-simulator/package.json
packages/amplify-prompts/jest.config.js
packages/amplify-prompts/package.json
packages/amplify-provider-awscloudformation/package.json
packages/amplify-util-headless-input/package.json
scripts/collect-test-coverage.ts

This PR moves all jest configurations to the `"jest"` block of each project's `package.json`. Additionally, a `collectCoverageFrom` option is added to each Jest config.
In some projects, Jest configs were stored in both a `jest.config.js` file and the `package.json` `"jest"` block. This is a no-op. Since the majority of projects were using the Jest config in `package.json`, all packages were standardized on that norm.
Additionally, a `collectCoverageFrom` option was added to each Jest config file. In the absence of the `collectCoverageFrom` option, coverage statistics were only collected on files that are actually loaded during testing. This can lead to underreporting coverage.
See [the jest documentation](https://jestjs.io/docs/cli#--collectcoveragefromglob).
Ran tests, verified tests …

chore: jest config normalization

---

packages/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts

modifies error to print package manager name, mitigates the following error on push if npm or yarn is not found on the system:
```
:octagonal_sign: Packaging lambda function failed. Could not find [object Object] executable in the PATH
```
tbd
n/a

fix: node function executable not found error to print pm name

---

packages/amplify-util-uibuilder/src/__tests__/prePushHandler.test.ts
packages/amplify-util-uibuilder/src/utils/prePushHandler.ts

Update code to remove the datastore type. We will use the type from codegen when it's exported in the future. As for now, there's no need to use datastore and we'd like to remove the import.
This also removes the datastore dependency.

chore: remove datastore Schema type dependency

---

packages/amplify-provider-awscloudformation/API.md
packages/amplify-provider-awscloudformation/src/utils/upload-env-parameters.ts

This change JSON stringifies values before they are uploaded to parameter store. This ensures that only strings are uploaded and ensures that values can be converted back to their original types when they are downloaded from parameter store.

fix: json stringify values before upload to ps

---

packages/amplify-util-mock/src/CFNParser/stack/index.ts
packages/amplify-util-mock/src/__tests__/CFNParser/stack/index.test.ts

When traversing the resource attribute for intrinsic dependencies, the previous method will stop at node with more than 1 attributes, which means attribute such as  `Properties.Parameters` will never be visited for finding the dependencies. The PR is to fix this bug.
fix https://github.com/aws-amplify/amplify-category-api/issues/1014

fix(mock): topo sort for resource in mock

---

packages/amplify-util-uibuilder/package.json
yarn.lock

Update codegen packages to 2.8.0:
- data model relationships support
- support bidirectional hasMany
- fixes for forms validations
- fix for nonModel fields in forms
unit & e2e tests in codegen-ui
1 failure when running locally:
```
packages/amplify-cli/src/__tests__/test-aborting.test.ts
test SIGINT with execute
thrown: "Exceeded timeout of 5000 ms for a test.
```

fix(amplify-util-uibuilder): update codegen-ui to 2.8.0

---

packages/amplify-category-notifications/src/__tests__/channel-email.test.ts
packages/amplify-category-notifications/src/channel-email.ts

- stores role arn for email channel notifications to amplify meta channel output section
- manual and unit tests

fix: store email channel role arn to amplify meta output

---

packages/amplify-provider-awscloudformation/package.json
yarn.lock

Missed one dep in https://github.com/aws-amplify/amplify-cli/pull/11751. All should be graphql 15 now.

chore: upgrade missed graphql dep to 15

---

packages/amplify-environment-parameters/API.md
packages/amplify-environment-parameters/src/environment-parameter-manager.ts

- replaces _.set with _.setWith when generating TPI resource entries as _.set will generate N-length array if N key from path array is a number, see https://github.com/lodash/lodash/issues/1316#issuecomment-120753100

fix: null entries in TPI file when project has number value resource name

---

packages/amplify-cli-core/API.md
packages/amplify-cli-core/src/utils/windows-utils.ts
packages/amplify-cli/src/amplify-exception-handler.ts
packages/amplify-e2e-tests/src/__tests__/opensearch-simulator/opensearch-simulator.test.ts
packages/amplify-opensearch-simulator/src/index.ts
packages/amplify-util-mock/src/CFNParser/resource-processors/appsync.ts
packages/amplify-util-mock/src/__e2e__/utils/index.ts
packages/amplify-util-mock/src/__e2e_v2__/searchable-transformer.e2e.test.ts
packages/amplify-util-mock/src/api/api.ts
scripts/split-e2e-tests-v2.ts

Fixes modal test in `opensearch-simulator.test`.
The principal change is refactoring `isWindowsPlatform` to be a method that returns a boolean, instead of a direct proxy to `process.platform`. This makes it simpler and safer to mock the value of `isWindowsPlatform`.
All files that depend on `isWindowsPlatform` are not refactored to use `isWindowsPlatform()`. The `opensearch-simulator` test is refactored to remove the platform modality and to mock that value instead. 
The opensearch test cannot be run on windows. It has been added to the windows exclusion list for e2e tests.

fix: modal windows test for opensearch simulator

---

package.json
packages/amplify-category-hosting/package.json
packages/amplify-category-predictions/package.json

- fixes out of sync internal package dependencies
- add step to clear nx cache when running `yarn clean`

chore: fix dependency versions and update clean command

---

packages/amplify-cli-core/API.md
packages/amplify-cli-core/package.json
packages/amplify-cli-core/src/context/context-extensions.ts
packages/amplify-cli-core/src/index.ts
packages/amplify-cli-core/src/types.ts
packages/amplify-cli/src/__tests__/init-steps/s0-analyzeProject.test.ts
packages/amplify-cli/src/context-manager.ts
packages/amplify-cli/src/plugin-manager.ts
packages/amplify-opensearch-simulator/API.md
yarn.lock

Moves `context-extensions` to `amplify-cli-core`.
Context Extensions attaches most of the properties to the Amplify Context. The file has no amplify dependencies except a reference to the context interface (in its previous state, the `Context` class in `amplify-cli/`, now `$TSContext`).
With this file in `amplify-cli`, mocking context is difficult because depending on `amplify-cli/` in other projects creates a circular dependency. Moving this file to `amplify-cli-core` makes it easier to mock.

chore: move context-extensions to amplify-cli-core

---

.circleci/config.base.yml
.circleci/lint_pr.sh

When both PR validation job and e2e tests are run for the same PR then e2e linting result wins and is show in GH checks.
However in e2e run lint is no-op... https://github.com/aws-amplify/amplify-cli/blob/4316a610477594f11b7e9b35d97554e5a839e1e9/.circleci/lint_pr.sh#L5-L8
Therefore, we should exclude linting from e2e run.
Unfortunately circle ci doesn't have a good mechanism to only run lint on PR jobs (see https://ruarfff.com/circleci-pr-only/ ). But hence we do run pr validation and e2e tests on PRs usually. Just excluding lint from e2e seems like a cheap and effective solution.

chore: dont lint in e2e runs

---

packages/amplify-cli-extensibility-helper/API.md
packages/amplify-cli-extensibility-helper/src/index.ts

This is a small PR that exports a type used by already public `getProjectInfo`. So that customers can import that type and use it to define symbols that store return of getProjectInfo() calls.
- [] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)

fix: export AmplifyProjectInfo

---

.circleci/local_publish_helpers.sh

Trailing `=` sign is causing retries to skip failed tests and it is masking failures.
See https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/15796/workflows/8ed3fe53-e2f6-4793-bb3e-193ec29583db/jobs/772859 .

fix: e2e test retry

---

package.json
scripts/extract-formatting-changes.ts

This script isolates formatting changes between two revisions. This is a helpful tool to reduce formatting noise in PRs. It will allow developers submit two PRs, the first with formatting changes, the second with functional changes in code.

chore: script to isolate formatting changes between commits

---

packages/amplify-cli-npm/index.ts
packages/amplify-cli/package.json
packages/amplify-container-hosting/package.json
yarn.lock

Bump the API plugin dependency to version `4.1.6-legacyrdsfix.0` that has the fix to legacy RDS transformers.
[Full e2e pipeline](https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/15880/workflows/5d800d6e-35ac-4259-918c-495e2ea8c960)

fix: bump API plugin version to update legacy rds transformers

---

packages/amplify-e2e-core/src/init/amplifyPush.ts

This fixes schema iterative rollback e2e tests. The problem is in the e2e testing code.
The original regression was introduced in https://github.com/aws-amplify/amplify-cli/pull/11651/files#diff-7e3c46591dfadf6a28b860b355600ed92ba329b54f0119a0ec959db990361e27
This PR fixes expected error message.
By running affected tests.

fix: iterative rollback e2e tests

---

packages/amplify-category-custom/tsconfig.json

`@aws-amplify/amplify-cli-extensibility-helper` depends on `@aws-amplify/amplify-category-custom` and contains a reference in it's [tsconfig](https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-cli-extensibility-helper/tsconfig.json#L9).
`@aws-amplify/amplify-category-custom` does not depend on the extensibility-helper package so I removed the entry.

chore: remove circular reference from tsconfig

---

scripts/extract-formatting-changes.ts

Fixes botched logic for determining a branch's name

fix: branch name logic format script

---

packages/amplify-cli/src/extensions/amplify-helpers/push-resources.ts
packages/amplify-environment-parameters/API.md
packages/amplify-environment-parameters/src/__tests__/environment-parameter-manager.test.ts
packages/amplify-environment-parameters/src/environment-parameter-manager.ts

This PR reduces the parameters which are validated on push to only the resources being pushed.
Fixes https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/15994/workflows/e7662d31-b6d1-438b-8410-e9662d443274/jobs/780641/tests
`notifications-multi-env.test.ts` passed locally

fix: filter parameter validation when pushing subset of resources

---

packages/amplify-provider-awscloudformation/src/utils/ssm-utils/env-parameter-ssm-helpers.ts
packages/amplify-provider-awscloudformation/src/utils/ssm-utils/exp-backoff-executor.ts

- Fix throttling logic to catch error code `ThrottlingException` in addition to `Throttling`
- Call `SSM.putParameter` in `executeSdkPromisesWithExponentialBackoff`

fix: throttling logic for ParameterStore SDK calls

---

packages/amplify-category-notifications/src/display-utils.ts

During an `amplify env add` and `amplify env checkout` with notifications, I ran into this spinner line being repeated thousands of times:
The spinner at the bottom of the output keeps flickering.
After changing the notifications spinner to a single printed line, the output looks like a typical deployment.
Manually tested `amplify env add`

fix: notifications and deploy spinners clashing

---

packages/amplify-cli-core/src/help/commands-info.ts

Removes a duplicate push subcommand under "api" in commands-info.ts.

fix: remove duplicate api push in commands-info.ts

---

CONTRIBUTING.md
package.json

Adds a couple of useful prettier related commands to `package.json`.
The CI pipeline now fails if any file in the repository is not formatted correctly.
These commands will make it easier to format the codebase to match the CI specification.

chore: add prettier commands

---

.github/workflows/closed-issue-message.yml

- This PR will introduce a GitHub workflow to the Amplify CLI repository.
- The workflow will present a comment visibility warning when an issue is closed.
- It will guide the community members to take appropriate actions since its hard for Amplify team to keep up with new comments on closed issues.
- This GitHub action workflow is being referenced from the `aws-actions` repository: https://github.com/aws-actions/closed-issue-message.
- We already have a similar feature live within the Hosting repository: https://github.com/aws-amplify/amplify-hosting/pull/2820

feat(cli): closed-issue-message workflow

---

.circleci/config.base.yml
packages/amplify-cli/API.md
packages/amplify-cli/src/domain/amplify-toolkit.ts

This PR is part of a larger effort to make the Amplify Toolkit easier to use.
Currently, the toolkit is using a pattern similar to a singleton to store references to imported modules in the class. Because `require` already caches imported modules, this redirection is not necessary. Additionally, the Toolkit is using redirection around the import path that does not provide additional value, and makes the file more difficult to understand.
This change removes both the singleton pattern and the multiple `path.join`s around the requires.

chore: refactor amplify toolkit's singleton and import patterns

---

packages/amplify-category-auth/resources/overrides-resource/auth/override.ts.sample
packages/amplify-category-auth/resources/overrides-resource/userPoolGroups/override.ts.sample
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/user-pool-group-stack-transform.ts
packages/amplify-category-storage/resources/overrides-resource/DynamoDB/override.ts.sample
packages/amplify-category-storage/resources/overrides-resource/S3/override.ts.sample
packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/ddb-stack-transform.ts
packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-transform.ts
packages/amplify-cli-extensibility-helper/API.md
packages/amplify-cli-extensibility-helper/src/types.ts
packages/amplify-e2e-core/src/utils/index.ts
packages/amplify-e2e-core/src/utils/overrides.ts
packages/amplify-e2e-tests/overrides/override-auth.ts
packages/amplify-e2e-tests/overrides/override-root.ts
packages/amplify-e2e-tests/overrides/override-storage-ddb.ts
packages/amplify-e2e-tests/overrides/override-storage-s3.ts
packages/amplify-e2e-tests/src/__tests__/auth_6.test.ts
packages/amplify-e2e-tests/src/__tests__/init_e.test.ts
packages/amplify-e2e-tests/src/__tests__/storage-5.test.ts
packages/amplify-migration-tests/src/__tests__/migration_tests/overrides/init-migration.test.ts
packages/amplify-migration-tests/src/__tests__/migration_tests_v10/auth-override.migration.test.ts
packages/amplify-provider-awscloudformation/resources/overrides-resource/override.ts.sample
packages/amplify-provider-awscloudformation/src/initializer.ts
packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-transform.ts

This PR injects `AmplifyProjectInfo` into override functions as second parameter.

feat: inject project info into overrides

---

packages/amplify-e2e-core/src/init/amplifyPush.ts
packages/amplify-e2e-core/src/utils/projectMeta.ts
packages/amplify-e2e-tests/src/__tests__/minify-cloudformation.test.ts
packages/amplify-provider-awscloudformation/src/__tests__/utils/minify-json.test.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts
packages/amplify-provider-awscloudformation/src/upload-appsync-files.js
packages/amplify-provider-awscloudformation/src/utils/minify-json.ts

When the `--minify` flag is passed in, post-process generated CFN files to read them back into memory, and rewrite in a shortened form. This will allow us to remove minify handling from the various places it exists today elsewhere in code, and have a single (or small number) of places where the Amplify CLI handles this.
https://github.com/aws-amplify/amplify-cli/issues/7680
Added unit tests, and verified manually via `amplify-dev` that that w/ and w/o `--minify` flag behaves as expected for both standard and iterative deployment use-cases (previous attempts to resolve this haven't resolved iterative deployments, leaving customers in a state where initial deploy succeeds, and adding/editing relationships will fail).
Added an e2e test that verifies that both my nested stack files and …

fix: post-process cfn files for minification, consolidating concern of minification a bit

---

package.json

Adds an npm script that runs the same checks that are used in the CI. This is helpful for local development to ensure a push will not fail due to a build/lint/style issue.

chore: add build-and-verify script that runs ci checks locally

---

packages/amplify-cli-core/src/utils/open.ts
packages/amplify-cli/package.json
packages/amplify-cli/src/extensions/amplify-helpers/open-editor.ts

This PR handles any errors that are caused by trying to open a URL or an app. Without the `error` listener, when the spawned child process errors out, it bubbles up and get caught here and ends up terminating the application.
https://github.com/aws-amplify/amplify-cli/blob/73eb14a42a1dda2608ba65f84ea629fa417ec8e6/packages/amplify-cli/src/index.ts#L47
By preventing it from bubbling up, we ensure the cli-flow can continue, since failure to open the app/url automatically is not a critical functionality.
Also update the error message (we only ever see this error in linux distributions where xdg-utils is not installed)
https://github.com/aws-amplify/amplify-cli/issues/12004
Slightly trickier. Somehow the dev build is behaving differently than the production binary. On the same machine and the …

fix: correctly handle spawned process errors

---

.circleci/publish.sh

Fixes a backlog item to work around [this bug in lerna](https://github.com/lerna/lerna/issues/1066) where failed publish commands still exit with success. In the past, this has caused our publish job to continue even when the npm publish failed.
This change wraps the `lerna publish` command in a function that scans for `lerna: ERR!` in the output and fails if found
Manually verified as close to the real thing as I could locally. Running e2e now which will verify that the publish to verdaccio is working correctly. This will give confidence that the other publish command will also work correctly.

chore: exit publish script on lerna failure

---

packages/amplify-prompts/src/prompter.ts

- limits the amplify prompter.pick display list to 10 items
- manual test

fix: limit the prompter list display options to 10 entries

---

package.json
packages/amplify-cli/src/plugin-helpers/scan-plugin-platform.ts

`amplify plugin scan` every time adds `"packaged-node-modules"` to `pluginDirectories` list in `~/.amplify/plugins.json`. So after several plugin scanning it looks like this:
```json
"pluginDirectories": [
"cli-local-node-modules",
"cli-parent-directory",
"global-node-modules",
"packaged-node-modules",
"packaged-node-modules",
"packaged-node-modules",
"packaged-node-modules",
"packaged-node-modules",
"packaged-node-modules",
"packaged-node-modules"
]
```
I've added check if `"packaged-node-modules"` already exists in this list
I've build cli binary and tested it locally. I also ran `yarn test`

fix: remove unnecessary update of pluginDirectories with 'packaged-node-modules'

---

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/buildLayer.test.ts

Left this over from reverting changes to function-runtime reversion.

chore: remove aws-amplify from previous PRs leftover.

---

packages/amplify-cli/src/index.ts

When commands are deemed invalid by the input-manager, the command is set to "help" but the plugin is not changed. This leads to invalid commands still being routed to non-core plugins, which sometimes results in users being prompted, even after a message showing that the command is invalid is printed. This change stops commands from being routed to plugins by setting the plugin to core. The plugin that executes the help command does not matter, as all plugins yield the same top-level help. See the first photo below for an example of a prompt appearing after an invalid command message and the second photo for the new behavior.
#12118 
- [] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
By submitting this pull request, I confirm that …

fix: do not route to plugin when command is invalid

---

packages/amplify-e2e-tests/src/__tests__/custom_resources.test.ts
packages/amplify-e2e-tests/src/__tests__/graphql-v2/api_lambda_auth_2.test.ts

Fixes 2 e2e tests:
- Skips custom resource build with local registry on windows
- Loosens assertion in schema auth test - we only care about "Not Authorized" part there.

chore: fix e2e tests

---

packages/amplify-frontend-ios/lib/amplify-xcode.js

The package name is changed with the scope added since last release. Resolve the xcode binary path accordingly so that the script will run successfully.
Fix https://github.com/aws-amplify/amplify-studio/issues/47
`amplify-dev codegen models` in an amplify swift project

fix(amplify-frontend-ios): xcode scirpt binary path resolves correctly

---

packages/amplify-provider-awscloudformation/src/__tests__/configuration-manager.test.ts
packages/amplify-provider-awscloudformation/src/configuration-manager.ts

When configuring a project to use access keys instead of a profile there was a bug where the configured region was not being used and instead trying to resolve a region using environment variables. This change fixes the behavior to use the region specified in the CLI walkthrough for setting up a new user.
Manually validated and added unit tests

fix: use configured region when manually configuring credentials

---

packages/amplify-provider-awscloudformation/src/__tests__/system-config-manager.test.ts
packages/amplify-provider-awscloudformation/src/system-config-manager.ts

The AWS SDK ProcessCredentials class requires the AWS_SDK_LOAD_CONFIG environment variable to be set in order for the credential process in `~/.aws/config` to take precedence over `~/.aws/credentials`. This change forces that environment variable to be set while executing the credential process
fixes https://github.com/aws-amplify/amplify-cli/issues/12120
Manually tested and added a unit test

fix: force ProcessCredentials to prefer config file

---

.circleci/config.yml

The `build` in `e2e_resource_cleanup` keeps crashing randomly. Bumping executor to same size as we use in `build_test_deploy_v3` workflow.

chore: use xlarge for cleanup build step

---

.circleci/config.base.yml
.circleci/local_publish_helpers.sh
nx.json
packages/amplify-cli-core/API.md
packages/amplify-cli-core/src/cfnUtilities.ts
packages/amplify-cli-core/src/context/context-extensions.ts
packages/amplify-cli-core/src/jsonUtilities.ts
packages/amplify-cli-core/src/types.ts
packages/amplify-e2e-tests/package.json

This PR:
- makes sure that retry loop of e2e tests re-runs only failed tests not all tests
- make `yarn clean && yarn build-tests` possible (not leveraged in workspace build eventually due to other dependencies on full build but nice to have).
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e%2Fsobkamil%2Fimprove-e2e-tests

test: improve resiliency of e2e tests on windows

---

packages/amplify-category-analytics/src/__tests__/migrations/in-app-messaging-migration.test.ts
packages/amplify-category-analytics/src/migrations/in-app-messaging-migration.ts

- the migration added for analytics/notifications should not happen if there isn't a pinpoint app added to the project
- manual test

fix: prevent analytics/notifications migration if there is not a pinpoint app added

---

packages/amplify-category-interactions/src/provider-utils/awscloudformation/service-walkthroughs/lex-walkthrough.js

— removes default value from interactions intent and slot name, it was added by mistake during inquirer to prompt migration
— manual test

fix: remove default value from interactions intent and slot

---

packages/amplify-category-notifications/src/channel-fcm.ts

- change FCM label for ApiKey to Server Key in order to match firebase console label and to avoid confusion

fix: change FCM ApiKey to Server Key label as displayed in firebase console

---

packages/amplify-util-mock/src/api/api.ts

fixes #11657
This fixes the dynamo local journal causing lstat issues.
I tested with adding many transactions to the system. With the fix the mock setup doesn't error when the journal appears briefly.

fix(util-mock): fix chokidar.watch choking on mock db-journal

---

.eslintrc.js

This [PR](https://github.com/aws-amplify/amplify-cli/pull/12113) replaced all usages of .set with .setWith from lodash's library. With this PR, I have implemented a lint rule that will give a warning in text editor that will prevent the resurgence of _.set
#11894 
- [n/a] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [n/a] Relevant documentation is changed or added (and PR referenced)
- [n/a] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

chore: adding eslint rule to prevent using _.set()

---

packages/amplify-category-auth/resources/overrides-resource/auth/package.json
packages/amplify-category-auth/resources/overrides-resource/userPoolGroups/package.json
packages/amplify-category-custom/resources/package.json
packages/amplify-category-storage/resources/overrides-resource/DynamoDB/package.json
packages/amplify-category-storage/resources/overrides-resource/S3/package.json
packages/amplify-cli-core/resources/overrides-resource/package.json
packages/amplify-migration-tests/custom-resources/custom-cdk-stack-vLatest.package.json
packages/amplify-provider-awscloudformation/resources/overrides-resource/package.json

Updates references to `@aws-amplify/cli-extensibility-helper` to use `^3.0.0`.

chore: update cli-extensibility-helper references

---

packages/amplify-e2e-core/src/init/initProjectHelper.ts
packages/amplify-e2e-core/src/utils/git-operations.ts
packages/amplify-e2e-tests/custom-resources/custom-cdk-stack-with-storage.ts
packages/amplify-e2e-tests/src/__tests__/custom-resource-with-storage.test.ts
packages/amplify-provider-awscloudformation/src/initialize-env.ts

The function for generating types was getting called when the cfn files were not yet generated for all resources. This happened because the order of the array of resources did not have custom as the last resource. The types were being built in the custom category. The fix is to build the types again after all of the cfn files have been created in amplify init. 
[# 11847](https://github.com/aws-amplify/amplify-cli/issues/11847)

fix: export storage types bug

---

.circleci/config.base.yml
packages/amplify-e2e-core/src/utils/git-operations.ts
packages/amplify-e2e-tests/src/__tests__/custom-resource-with-storage.test.ts

This test is failing on windows because some paths it is trying to use are too long for git on windows. This should allow these long paths. It also slightly shortens the name of the custom resource. I couldn't shorten the name of the project without the test failing locally. 

fix: windows test failing on long paths

---

packages/amplify-e2e-tests/src/__tests__/custom-resource-with-storage.test.ts

This E2E test on windows is failing with this message. This may be due to the project name. I also realized that the path on line 41 should not depend on the project name.

fix: windows test failing change path and project name

---

scripts/split-e2e-tests-v2.ts

Follow up on https://github.com/aws-amplify/amplify-cli/pull/12240 .
Missed one test that require windows exclusion until next release.

chore: exclude custom resource test on windows temporarily

---

packages/amplify-migration-tests/custom-resources/custom-cfn-stack.json
packages/amplify-migration-tests/src/__tests__/migration_tests_v10/custom-stack.migration.test.ts
packages/amplify-provider-awscloudformation/src/__tests__/print-cdk-migration-warning.test.ts
packages/amplify-provider-awscloudformation/src/print-cdk-migration-warning.ts

- added a check to stop cdk v1 warning for non cdk custom resource
- manually tested
- updated e2e to check for specific issue

fix: stops cdk v1 warning for non cdk custom resource

---

packages/amplify-migration-tests/custom-resources/custom-cfn-stack.json
packages/amplify-migration-tests/src/__tests__/migration_tests_v10/custom-stack.migration.test.ts
packages/amplify-provider-awscloudformation/src/__tests__/print-cdk-migration-warning.test.ts
packages/amplify-provider-awscloudformation/src/print-cdk-migration-warning.ts

* fix: stops cdk warning for non cdk custom resource
* fix: added unit test
---------

fix: stops cdk v1 warning for non cdk custom resource (#12241)

---

packages/amplify-e2e-core/src/init/deleteProject.ts
packages/amplify-e2e-tests/schemas/relational_models_v2.graphql
packages/amplify-e2e-tests/schemas/searchable_model_v2.graphql
packages/amplify-e2e-tests/src/__tests__/api_6a.test.ts
packages/amplify-e2e-tests/src/__tests__/api_6c.test.ts
packages/amplify-e2e-tests/src/rebuild-test-helpers/index.ts
packages/amplify-provider-awscloudformation/src/graphql-resource-manager/amplify-graphql-resource-manager.ts

Fixed the failure of `amplify api rebuild` for the following scenarios:
- Multiple models (appsync function dependencies between table stacks)
- Relational models (connection stack)
- Models with `@searchable` defined (searchable stack)
**Note: for `@searchable` rebuild the open search domain will be kept but the other resources (IAM roles, streaming lambda functions) will be removed and regenerated.**
The root cause is that some parameters of nested stack refers to the other nested stacks(including tables, connection and searchable), whereas the `Outputs` of them are dropped during the first stage of deployment. The change is to use null placeholder values to replace the references mentioned above in the api root template.
Given the following schema
```GraqhQL
input AMPLIFY { …
```

fix(api): add null placeholder for nested stack during api rebuild

---

.circleci/config.base.yml
.circleci/config.yml
.circleci/local_publish_helpers.sh
scripts/split-e2e-tests-v2.ts

Increase parallelization factor in tests.

chore: increase parallelization in e2e tests

---

.circleci/config.base.yml

chore: use nodejs 14.x compatible with CDK

---

packages/amplify-cli/src/__tests__/commands/push.test.ts
packages/amplify-cli/src/commands/push.ts
packages/amplify-cli/src/domain/amplify-toolkit.ts
packages/amplify-cli/src/extensions/amplify-helpers/current-cloud-backend-utils.ts
packages/amplify-cli/src/extensions/amplify-helpers/push-resources.ts
packages/amplify-e2e-tests/src/__tests__/push.test.ts

— skips backend sync on force push, as force push is ignoring resource status and always executes the push
— this also helps to override deployed backed in case if the deployed backed zip is corrupted
— manual changes
— unit tests added
— `yarn test` and `yarn e2e` pass

fix: skip backend sync on force push

---

.circleci/config.yml
Dockerfile

These changes fetch the pkg Node.js binaries from a private S3 bucket and include them in the image when it is built.

chore: image build with binaries

---

.circleci/config.base.yml

Force registry in build jobs to fix:

fix: set registry in build steps

---

packages/amplify-cli/bin/amplify
packages/amplify-cli/bin/amplify.production.template

This PR suppresses deprecation warnings, i.e.:
- AWS SDK message that's coming when we decide to upgrade it.
- Cloudform deprecated package.json (for the NodeJS 18 upgrade).

chore: don't show deprecation warnings in binary

---

packages/amplify-provider-awscloudformation/package.json
packages/amplify-provider-awscloudformation/src/__tests__/aws-utils/S3Service.test.ts
packages/amplify-provider-awscloudformation/src/aws-utils/S3Service.ts
packages/amplify-util-import/src/IS3Service.ts

- workaround for aws-sdk bug where calling `headBucket` for a opt-in region bucket will throw and error if s3 client is initialized with a different region
- retry headBucket call on error with the bucket region as s3 client option
- unit and e2e tests pass

fix: handle bucket exists check for s3 buckets in opt in regions

---

packages/amplify-e2e-core/src/utils/help.ts

Windows didn't like something about the way I was checking the help output before. This way fixes it. Here is a passing E2E run: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/17864/workflows/a799afc3-64b8-4157-9e76-1d83b303d576

test: fix help tests on windows with regex

---

packages/amplify-dotnet-function-template-provider/resources/lambda/global.json

This PR lowers required baseline net6 version to `6.0.100` in lambda templates. So that users who install net6 via apt-get on ubuntu can use it without modifying their lambda projects.
This setting does not control what customer's net6 version is it just widens allowed range of versions.
See more here https://devblogs.microsoft.com/dotnet/dotnet-6-is-now-in-ubuntu-2204/

chore: revise net6 baseline

---

packages/amplify-e2e-tests/src/__tests__/custom-resource-with-storage.test.ts
packages/amplify-e2e-tests/src/__tests__/custom_resources.test.ts
scripts/cci-utils.ts
scripts/split-e2e-tests-v2.ts

This brings back custom resource tests previously included on windows.

chore: undo custom resource exclusions on windows

---

Dockerfile
codebuild_specs/build_image.yml

This adds support for pkg cache.

ci: e2e image build pkg cache

---

packages/amplify-provider-awscloudformation/src/__tests__/admin-login.test.ts
packages/amplify-provider-awscloudformation/src/admin-login.ts

- resets `readline.terminal` property on close
- workaround for this readline related issue: https://github.com/nodejs/node/issues/31762#issuecomment-671208044
- manual test in windows env

fix: reset readline terminal property on close

---

codebuild_specs/build_image.yml

Codebuild images will be tagged with the branch name <tag> portion.
For example,
codebuild-image/latest will produce an image with a tag of "latest"
codebuild-image/<tag> will produce an image with a tag of <tag>
We can manually override the default branch tag by running manual CodeBuild job with overrides, specifying a CUSTOM_TAG parameter of the tag that we would like to use.

ci: allow custom image tag & use branch name to determine default tag

---

.circleci/config.base.yml
package.json

Sets yarn concurrency to potentially mitigate 
```
#!/bin/bash -eo pipefail
yarn run production-build
yarn run v1.22.19
$ yarn --frozen-lockfile --cache-folder ~/.cache/yarn && nx run-many --target=build --all
[1/4] Resolving packages...
[2/4] Fetching packages...
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://registry.yarnpkg.com/cosmiconfig/-/cosmiconfig-7.0.1.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, chmod '/home/circleci/.cache/yarn/v6/npm-cosmiconfig-7.0.1-714d756522cace867867ccb4474c5d01bbae5d6d-integrity/node_modules/cosmiconfig/dist/Explorer.d.ts'"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit …
```

fix: yarn failures

---

.circleci/config.base.yml
packages/amplify-e2e-tests/src/__tests__/init_d.test.ts

This PR:
- updates windows image
- build e2e workspace on node 18
- executes windows e2e tests on node 18
This change does not affect the build of binary.
Full e2e test suite, including all windows tests.
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/18197/workflows/d6082ea4-d3a5-4280-98eb-9d72480d8c61

chore: run e2e tests on windows on node18

---

packages/amplify-provider-awscloudformation/package.json
packages/amplify-provider-awscloudformation/src/__tests__/graphql-resource-manager/diff-test-helper.ts
packages/amplify-provider-awscloudformation/src/__tests__/graphql-resource-manager/gsi-test-helpers.ts
packages/amplify-provider-awscloudformation/src/graphql-resource-manager/dynamodb-gsi-helpers.ts
packages/amplify-provider-awscloudformation/src/graphql-resource-manager/gsi-diff-helpers.ts
packages/amplify-provider-awscloudformation/src/graphql-resource-manager/utils.ts

This PR changes imports of types from `cloudform` to import from `cloudform-types`.
This is to drop dependency on `cloudform` which gives DEP-xx warnings on Node 18 as it has incompatible statement in `package.json`.
The companion PR on data side - https://github.com/aws-amplify/amplify-category-api/pull/1365 .
This is a minimal change that solves the warning problem. However this PR does not re-enable warning yet, we need both CLI and data changes in and release cycle.
Alternatives considered but not pursued:
- Updating `cloudform` to latest. While it solves the original problem, the latest version includes one TS file in the package and would make us create custom ignore-transform rule in every package that has dependency (direct or transitive) on cloud-types.
E2E tests.
By submitting …

chore: import from clodform-types instead of cloudform

---

packages/amplify-e2e-core/src/asciinema-recorder.ts
packages/amplify-e2e-core/src/index.ts
packages/amplify-e2e-core/src/utils/nexpect.ts
packages/amplify-e2e-core/src/utils/verbose-logging.ts
packages/amplify-e2e-tests/Readme.md
packages/amplify-e2e-tests/src/setup-tests.ts

1. Changes VERBOSE_LOGGING env var to accept "stdout" or "files" instead of true/false. When "stdout" is set, CLI output is piped to the test harness stdout. When "files" is set, CLI output is piped to log files (existing behavior)
3. Only jitters the test start delay when `isCI()` returns true (to avoid unnecessary delays when running tests locally)
4. Only sets the jest retry if `isCI()` is true
6. Updates the e2e test readme with some notes about this new behavior
Manually running e2e tests locally

chore: some QoL improvements for locally debugging e2e tests

---

codebuild_specs/base.yml
codebuild_specs/run_e2e_tests_linux.yml
shared-scripts.sh

This enables parent-child role assumption for e2e testing in codebuild.

ci: e2e test setup for assume role in test account org

---

packages/amplify-e2e-tests/overrides/override-root.ts
packages/amplify-e2e-tests/src/__tests__/init_e.test.ts
packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-transform.ts

- added a specific check to apply overrides when init is 
- manually tested
- updated an e2e test to check for specific conditions

fix: apply overrides when forcePush is set with init

---

packages/amplify-e2e-core/src/utils/pinpoint.ts
packages/amplify-e2e-tests/src/__tests__/delete.test.ts

- fixes pinpoint e2e client to use the region from amplifyMeta instead of a hardcoded region mapping

test: fix e2e pinpoint client region

---

.circleci/config.base.yml

I recently created a tagged release that I left a debugger, and since the build doesn't run the linter (or yarn test), it wasn't caught until further down the QA process. We should add at least a few checkpoints to ensure the build is successful at runtime.

chore: add linter to tagged e2e process

---

packages/amplify-util-uibuilder/package.json
yarn.lock

Icon processing is broken because the schemas are saved with lower-cased "object" as the value type. We had added a condition that starts rendering this type as a string instead of an actual array.
Testing in the codegen-ui repo.
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/19080/workflows/be8d34f8-3fa5-419e-88a9-0240a6511161

fix(amplify-util-uibuilder): fix icon regression

---

packages/amplify-cli/src/commands/console.ts
packages/amplify-provider-awscloudformation/src/__tests__/utils/admin-helpers.test.ts
packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts

Adds some graceful fallback logic to the function that determines if an app has studio enabled. Specifically, if AppState is not available in us-east-1 (the "global" region), the logic will now fallback to looking for a region in `amplify-meta.json` and if not found there will finally prompt for a region.
It also fixes a bug in our console open logic that was not properly accounting for the return type of `isAmplifyAdminApp`
Added unit tests and simulated this failure locally by modifying `/etc/hosts` to make AppState appear unavailable
E2E is running now: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e/foyleef/no-appstate

fix: graceful fallback if us-east-1 AppState unavailable

---

packages/amplify-console-hosting/src/commands/add.js
packages/amplify-console-hosting/src/commands/configure.js
packages/amplify-console-hosting/src/commands/publish.js
packages/amplify-console-hosting/src/commands/remove.js
packages/amplify-console-hosting/src/commands/serve.js
packages/amplify-console-hosting/src/commands/status.js
packages/amplify-console-hosting/src/error/validation-error.js
packages/amplify-console-hosting/src/index.js

Fixes `cannot read 'name' property of undefined`
https://github.com/aws-amplify/amplify-cli/issues/12495

fix(amplify-console-hosting): handle undefined errors

---

.circleci/config.base.yml
packages/amplify-category-hosting/index.js
packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/file-uploader.js
packages/amplify-category-hosting/lib/S3AndCloudFront/index.js
packages/amplify-cli/package.json
packages/amplify-e2e-core/src/categories/hosting.ts
packages/amplify-e2e-tests/src/__tests__/export-pull-a.test.ts
packages/amplify-e2e-tests/src/__tests__/export-pull-b.test.ts
packages/amplify-e2e-tests/src/__tests__/export-pull-c.test.ts
packages/amplify-e2e-tests/src/__tests__/export-pull-d.test.ts
packages/amplify-e2e-tests/src/__tests__/hosting.test.ts
packages/amplify-e2e-tests/src/__tests__/s3-sse.test.ts
packages/amplify-e2e-tests/src/__tests__/tags.test.ts

Due to S3's new security changes, amplify-category-hosting's ability to use an S3 bucket to host a dev site no longer works by default. When a user runs `amplify publish`, they run into a `The bucket does not allow ACLs` error.
The new experience would not allow developers to use Dev mode and attaches a CloudFront distribution by default.
If a user has a dev bucket with hosting enabled in HTTP, there's a workaround for that listed in #12503 
Info on S3 Change: S3 bucket with Access Control Lists enabled is removed and the ability to https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/
#12503 

fix: update defaults for hosting S3 and remove dev option

---

packages/amplify-cli-core/src/hooks/hooksExecutor.ts
packages/amplify-e2e-tests/src/__tests__/hooks-c.test.ts

An error in the logic was causing post-push hooks to be invoked twice in hosting builds.
Fixes #9996
Manually tested both pre and post hooks with `amplify-dev init --envName dev --forcePush --yes`, added e2e test

fix: double hooks invocation (fixes #9996)

---

packages/amplify-provider-awscloudformation/src/utils/ssm-utils/exp-backoff-executor.ts

This PR updates the exponential backoff logic for AWS-SDK calls to Parameter Store
- Add a minimum 1 second delay between retried calls
- Increase the base retry delay from 200ms to 500ms

fix: add min delay to exp backoff

---

packages/amplify-category-function/src/events/prePushHandler.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/utils/ensure-lambda-arn-outputs.ts

don't throw for missing backend-config.json in prepush function handler

fix: don't throw for missing backend-config in prepush function handler

---

packages/amplify-util-uibuilder/package.json
scripts/split-e2e-tests-v2.ts

fix: exclude smoketests on windows; remove extraneous dependency

---

packages/amplify-cli/bin/amplify

`cloudform` (not `cloudform-types` ! ) is now gone from all `package.json` files and `yarn.lock`. Therefore we bring back deprecation warnings when `amplify-dev` is used.
Green E2E test run

chore: enable deprecation warnings in non-prod CLI

---

packages/amplify-cli/package.json
packages/amplify-e2e-tests/src/__tests__/__snapshots__/studio-modelgen.test.ts.snap
packages/amplify-provider-awscloudformation/package.json
packages/amplify-util-mock/package.json
packages/amplify-util-uibuilder/package.json
yarn.lock

- Revert the `__typename` change in doc generator
- Downgrade amplify codegen to version 3 to avoid version mismatch error from JS datastore so that the CI jobs can stay healthy

chore: bump codegen version to 3.4.4

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/__snapshots__/auth-stack-transform.test.ts.snap
packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/lambda-callout-migrations/__snapshots__/auth-cognito-stack-builder.test.ts.snap
packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/lambda-callout-migrations/auth-cognito-stack-builder.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts

Since there is a reference to the providers, this adds a dependency on the new Cognito third party provider resources for the clients.
This also fixes a test to capture a snapshot instead of the code snippet.
Updated the snapshots to include the dependencies. e2e tests are in progress on another branch.

fix: add custom resource dependency to the newly created provider resources

---

packages/amplify-category-auth/resources/auth-custom-resource/hostedUIProviderLambda.js

This changes this from `all` to `allSettled` to make sure that all the promises are resolved, and that the promise does not terminate on the first failure.
This will need to happen in the follow up e2e tests. An e2e test will be written that will delete the provider resource manually before the migration, then test that the stack update is successful. (@jhockett is working on that test)

fix: use all settled promise method to wait until deletes are attempted

---

codebuild_specs/migration_tests_v10.yml
codebuild_specs/migration_tests_v5.yml
codebuild_specs/migration_tests_v6.yml

This fixes the artifact path allowing the migration tests to pass.

ci: fix migration tests

---

packages/amplify-migration-tests/src/__tests__/migration_tests_v10/__snapshots__/auth-add-all.migration.test.ts.snap
packages/amplify-provider-awscloudformation/src/push-resources.ts

Passes in an empty array to the parser when hosted provider meta is `undefined`.
This happens in some scenarios when auth is imported. Example failures:
- https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/19803/workflows/7cdaa460-1252-4856-82b9-e0c87a11e43b/jobs/943841/tests#failed-test-0
- https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/19803/workflows/7cdaa460-1252-4856-82b9-e0c87a11e43b/jobs/943845/tests#failed-test-0
This PR also adds some of the snapshot changes for the migration tests that show adding identity providers and removing the custom lambda callouts.
Fixed e2e tests will confirm the change works.

fix: parse empty array when provider meta is undefined

---

packages/amplify-cli/src/commands/pull.ts
packages/amplify-e2e-core/src/init/amplifyPull.ts
packages/amplify-e2e-tests/src/__tests__/pull.test.ts

Do not throw error if `amplify/.config/local-env-info.json` is missing when executing `amplify pull`.
Fixes #12492
e2e test passes locally, tested manually

fix: do not throw when localEnvInfo is missing on pull (fixes 12492)

---

packages/amplify-cli/src/commands/build.ts
packages/amplify-cli/src/extensions/amplify-helpers/push-resources.ts
packages/amplify-e2e-core/src/init/amplifyPush.ts
packages/amplify-e2e-tests/src/__tests__/function_12.test.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts

- passed resource and category info to nested functions 
- only calling schema transform if api is getting deployed
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/19710/workflows/3677e12c-cc33-4b2e-a195-782485133701

fix: deploy category resources when calling amplify push <categoryName>

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/index.ts

`amplify auth console` and selecting userpool currently opens the v1 version of cognito userpool dashboard. 
The PR updates the URL to open the v2 version of the dashboard.
could not find any tests. if any, please provide me the path or link i can add the test if needed.
https://github.com/aws-amplify/amplify-cli/issues/12046

feat: update console auth command url to v2 dashboard

---

packages/amplify-e2e-core/package.json
packages/amplify-e2e-core/src/utils/auth-utils.ts
packages/amplify-e2e-core/src/utils/index.ts
packages/amplify-e2e-tests/src/__tests__/import_auth_1a.test.ts
packages/amplify-e2e-tests/src/__tests__/import_auth_3.test.ts
packages/amplify-e2e-tests/src/__tests__/pinpoint/analytics-pinpoint-config-util.ts
packages/amplify-e2e-tests/src/__tests__/pinpoint/notifications-pinpoint-config-util.ts
packages/amplify-e2e-tests/src/__tests__/transformer-migrations/auth-migration.test.ts
packages/amplify-e2e-tests/src/__tests__/transformer-migrations/function-migration.test.ts
packages/amplify-e2e-tests/src/schema-api-directives/common.ts
packages/amplify-e2e-tests/src/schema-api-directives/functionTester.ts
packages/amplify-e2e-tests/src/schema-api-directives/index.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/auth-customClaims.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/auth-customClaims2.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/auth-owner10.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/auth-owner11.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/auth-owner8.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/auth-owner9.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/auth-private2.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/auth-public1.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/auth-public2.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/auth-usingOidc.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/function-chaining.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/function-differentRegion.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/function-example2.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/key-howTo4.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/predictions-usage.ts
packages/amplify-e2e-tests/src/schema-api-directives/tests/searchable-usage.ts

This PR moves auth related e2e helper functions to `amplify-e2e-core` so that they can also be used in the `amplify-migration-tests` package.

refactor: move e2e test helpers to e2e-core package

---

packages/amplify-util-uibuilder/package.json
packages/amplify-util-uibuilder/src/__tests__/createUiBuilderComponent.test.ts
packages/amplify-util-uibuilder/src/commands/utils/codegenResources.ts
yarn.lock

- **codegen-ui:** fix multiple has one relationships ([#1005](https://github.com/aws-amplify/amplify-codegen-ui/issues/1005)) ([96b7b9d](https://github.com/aws-amplify/amplify-codegen-ui/commit/96b7b9dc3e9e70e1d8527d9abb59334b0bb56ca7))
- parse operand value when field is number type ([#1013](https://github.com/aws-amplify/amplify-codegen-ui/issues/1013)) ([ad9ba60](https://github.com/aws-amplify/amplify-codegen-ui/commit/ad9ba606ab381b2b4759f19f9310a0901dd10fa8))
- upgrade node and pin lerna version in circleci ([#1002](https://github.com/aws-amplify/amplify-codegen-ui/issues/1002)) ([2c70073](https://github.com/aws-amplify/amplify-codegen-ui/commit/2c700733928c28348ab100832b3c9e4fb56ef8a5))
- Add `processFile` to util renderer
- exporting processFile to be used in studio …

fix: update codegen ui version and add processFile util function

---

packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/types.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/constants.ts

Fixes the instance when:
- user 1 creates auth
- user 1 pushes
- user 2 pulls auth
- user 2 force pushes
This will be covered by an e2e test for switching directories.

fix: skip adding cfn params when user pool inputs are absent

---

Dockerfile

- bump stunnel to 5.69
- update to use North American download server
Taken from stunnel patch [notes](https://www.stunnel.org/NEWS.html):
```md
Version 5.69, 2023.03.04, urgency: MEDIUM
New features
Improved logging performance with the "output" option.
Improved file read performance on the WIN32 platform.
DH and kDHEPSK ciphersuites removed from FIPS defaults.
Set the LimitNOFILE ulimit in stunnel.service to allow for up to 10,000 concurrent clients.
Bugfixes
Fixed the "CApath" option on the WIN32 platform by applying https://github.com/openssl/openssl/pull/20312.
Fixed stunnel.spec used for building rpm packages.
Fixed tests on some OSes and architectures by merging Debian 07-tests-errmsg.patch (thx to Peter Pentchev).
Version 5.68, 2023.02.07, urgency: HIGH
Security bugfixes
OpenSSL …
```

chore: update stunnel download in Dockerfile

---

.github/CODEOWNERS

Add codeowners to ensure that CI/CD files and folders are reviewed by certain members of our team.

ci: Add codeowners for CI/CD files & folders

---

package.json

fix: use and operator instead of semicolon to run unit tests

---

packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/generalQuestionsWalkthrough.test.ts
packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/generalQuestionsWalkthrough.ts

when adding a function with the same name as an existing function, the cli throws errors that are not helpful.
debug:
```
Error: test is present in amplify-meta.json
at AmplifyToolkit.updateamplifyMetaAfterResourceAdd (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/update-amplify-meta.js:127:15)
at createFunctionResources (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-function/lib/provider-utils/awscloudformation/utils/storeResources.js:47:21)
at addFunctionResource (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-function/lib/provider-utils/awscloudformation/index.js:88:56)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async Object.executeAmplifyCommand …
```

fix: throw message when adding lambda function with same name

---

packages/amplify-prompts/API.md
packages/amplify-prompts/src/__tests__/printer.test.ts
packages/amplify-prompts/src/printer.ts
packages/amplify-util-mock/src/__tests__/func/__snapshots__/index.test.ts.snap
packages/amplify-util-mock/src/__tests__/func/index.test.ts
packages/amplify-util-mock/src/func/index.ts

displays error message instead of object or stack trace 
https://github.com/aws-amplify/amplify-cli/issues/12626

feat: display error message instead of object

---

scripts/cloud-e2e.sh

Using 'run-e2e' for the upstream branch name causes circleci jobs to trigger. We don't want to cut circleci files yet, so this alternative allows us to trigger codebuild jobs without triggering the circleci jobs.

ci: rename e2e branch to avoid triggering circleci job

---

.circleci/local_publish_helpers.sh
codebuild_specs/scripts-windows/run-e2e-windows.sh
shared-scripts.sh

This is a small change that prevents any changes to the circleci e2e script, while supporting both circleci/codebuild during the transition.
CircleCI e2e: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=run-e2e/aluja/codebuild-cleanup

ci: separate codebuild & cci differences

---

.circleci/config.base.yml
.circleci/publish-codebuild.sh
.circleci/publish.sh

This PR:
- removes redundant upload
- adds validation that binaries exists for `release` and `release rc` 

chore: validate binary presence before npm publish in release

---

.circleci/scan_artifacts_codebuild.ts
codebuild_specs/run_e2e_tests_windows.yml
packages/amplify-e2e-core/src/categories/api.ts
packages/amplify-e2e-core/src/utils/index.ts

There is a difference in the way that paths are resolved in CircleCI vs CodeBuild. This was causing many Windows tests to fail because the paths to schemas would not resolve correctly.
This PR also enables artifacts for Windows tests.

fix: adjust path finding for schemas in codebuild

---

packages/amplify-console-integration-tests/src/setup-tests.ts
packages/amplify-e2e-tests/src/setup-tests.ts
packages/amplify-migration-tests/src/setup-tests.ts

When yarn script is run, it adds a temporary path to `PATH`. During the migration tests, this path is removed. The pattern matching on macOS did not cover all scenarios, so this removes the `/tmp` from the pattern to just look for `/xfs-`.
Tested on my personal computer (macOS, M1). Run e2e tests to confirm migration tests pass.

fix: fix yarn path

---

packages/amplify-category-notifications/src/commands/notifications/configure.ts
packages/amplify-e2e-core/src/categories/notifications.ts
packages/amplify-e2e-tests/src/__tests__/notifications-sms-update.test.ts

- when updating the notifications channel without passing the channel name as the command line argument, the customer is prompted to select the channel name, we incorrectly checked that the command line value is also set.
- e2e added
- e2e tests pass

fix: update notification channel name lookup

---

scripts/generate_single_test_buildspec_codebuild.ts

chore: fix unallowed characters in single test split script

---

packages/amplify-e2e-core/src/utils/sdk-calls.ts
packages/amplify-e2e-tests/src/__tests__/import_auth_1b.test.ts
packages/amplify-e2e-tests/src/__tests__/pull-2.test.ts
packages/amplify-e2e-tests/src/import-helpers/walkthroughs.ts

- Make SDK call to check number of user pools for test so we know if we need to filter userpools or not in prompt
- Refactor some eslint disable comments away

test: fix pull-2 when multiple userpools present

---

packages/amplify-cli-core/package.json
packages/amplify-cli/package.json
packages/amplify-e2e-core/src/utils/nexpect.ts
yarn.lock

Update the `ci-info` package to make the CI check disabling logic work for any CI provider
Fixes the failing node.function.test.ts in CodeBuild due to this [line](https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-e2e-tests/src/__tests__/migration/node.function.test.ts#L91).

chore: update ci-info to use new CI detection logic

---

packages/amplify-e2e-tests/src/__tests__/function_15.test.ts
packages/amplify-provider-awscloudformation/src/push-resources.ts

- converted from `Promise.all` to `for-of await` to fix the lambda function build concurrency issue
- manual test
- e2e test added
Steps to reproduce:
```
1. amplify init --yes
2. amplify add function (nodejs default values)
3. amplify push
4. edit the index.js from nodejs function to get into the update status
5. amplify add function (python or go)
6. amplify push
```

fix: build lambda functions build concurrency

---

packages/amplify-util-mock/src/__tests__/api/api.test.ts
packages/amplify-util-mock/src/api/index.ts

* Import custom port named `graphqlPort` from `amplify/mock.json`, and add capability to run GraphQL mock on the given port.
**mock.json**
* `port` for DynamoDB Local
* `graphqlPort` for AppSync Simulator
```json
{
"port": 8000
"graphqlPort": 8001
}
```
https://github.com/aws-amplify/amplify-category-api/issues/384
#
* add `graphqlPort` into `amplify/mock.json` like below
```json
{
"graphqlPort": 8001
}
```
* graphql mock server successfully ran on the given port
* also checked mock server running on port 20002 without `mock.json`

Add custom port support for GraphQL mock

---

packages/amplify-e2e-tests/src/__tests__/uibuilder.test.ts

Reverts aws-amplify/amplify-cli#12799
Causes test to fail: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/21317/workflows/76b43c76-cd33-4a1f-9fb4-721e848a3e56/jobs/1002553

Revert "test: make test teardown resilient to failures"

---

packages/amplify-provider-awscloudformation/src/__tests__/admin-modelgen.test.ts
packages/amplify-provider-awscloudformation/src/admin-modelgen.ts

If the customer is using multiple GraphQL schema files located at `<amplify/backend/api/<api_name>/schema>` folder instead of a single `schema.graphql` file, the current behavior is to fail softly by throwing the following error:
```
ENOENT: no such file or directory... schema.graphql
```
This error message occurs during the admin modelgen flow where we upload the Studio CMS artifacts to deployment S3 bucket. 
The current behavior is that we fail to update the schema, but generate and update the modelgen files in S3 bucket. When customer tries to open the Schema editor in Studio console, it fails to load.
With this change, we check and early return if we detect that there is no single schema file. In addition we display a warning message. …

fix: warn about multiple schema files in admin modelgen task

---

packages/amplify-frontend-flutter/lib/dart-fs.js
packages/amplify-frontend-flutter/package.json
packages/amplify-frontend-flutter/tests/amplify-config-helper.test.js

We are experimenting with some new config layouts and the current parsing behavior prevents changing the config structure. This expands on the current behavior to allow more flexibility in the config file contents.

chore: Refine Dart config parsing

---

packages/amplify-cli/package.json
packages/amplify-cli/src/__tests__/usage-data.test.ts
packages/amplify-cli/src/domain/amplify-usageData/UsageData.ts
yarn.lock

- removed throw statement from usage data

fix: usage data should not throw errors

---

packages/amplify-nodejs-function-template-provider/resources/lambda/lambda-auth/event.json

https://github.com/aws-amplify/amplify-cli/pull/11428 introduced a fake account id that is disallowed by our secret scanning. This PR switches the fake account id to an allowed value.

chore: remove disallowed secret pattern match

---

packages/amplify-provider-awscloudformation/src/utils/admin-login-server.ts

Return the error message to studio if storing tokens fails during the login flow.
N/A

fix: return login token error to studio

---

packages/amplify-category-hosting/__tests__/lib/S3AndCloudFront/helpers/file-uploader.test.js
packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/file-uploader.js
packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/upload-file.js

This PR is to mitigate https://github.com/aws-amplify/amplify-cli/issues/2087 as proposed by @timoteialbu .
**Issue**: since `index.html` is not always uploaded to S3 at last, it sometimes causes file not found issue if a dependent file is uploaded after index.html
**Fix**: `await Promise.all` all other files except `index.html`, then upload `index.html` at the end.
**Note**: 
1. This PR is just a mitigation. To fundamentally resolve the issue, users need to enable some sort of cache or versionize.
2. I've checked some popular build tools and they all use `index.html`. The build tools I checked are: angular-cli@16,  react@18.2.0 + cra@5.0.1, react + next@13.4.7, react + vite@4.3.9, vue@3.3.4, vue + nuxt@3.5.2, vue + vite@4.3.9
https://github.com/aws-amplify/amplify-cli/issues/2087
By …

fix: s3 upload index.html at last

---

.husky/commit-msg
.husky/pre-commit
.husky/pre-push
CONTRIBUTING.md
package.json
scripts/package-json-check.sh

After https://github.com/aws-amplify/amplify-cli/pull/12869, it has some issues:
1. error message in exist local folder
> Can't find Husky, skipping post-commit hook
> You can reinstall it using 'npm install husky --save-dev' or delete this hook
2. if clone a new repo, the hook would not work
**Reason**: Husky doesn't use config in package.json after version 7 ([ref](https://stackoverflow.com/a/68761163/12610324))
**Fix**: This PR is to migrate the setup to make husky@8 works. [Migration Guide](https://typicode.github.io/husky/getting-started.html)

chore: migrate to husky@8

---

codebuild_specs/aggregate_e2e_reports.yml
codebuild_specs/pr_workflow.yml
shared-scripts.sh

PR workflows were failing due to the wait script attempting to query the e2e project for batch build details. It should be querying the PR project batches instead. This updates the code to rely on PROJECT_NAME to determine which batches it should query. Also, the PR workflow still had dependsOn relationships which aren't needed anymore, as of https://github.com/aws-amplify/amplify-cli/pull/12882.

ci: fix wait for script, update PR workflow to match

---

package.json
scripts/split-e2e-tests-codebuild.ts

The way that wait_for_ids.json is generated always fails the linter. This change makes sure that prettier is run on the file directly after it is generated. 

chore: auto format wait_for_ids.json after splitting tests

---

packages/amplify-cli-npm/binary.ts

PKG_CLI_CLOUDFRONT_URL is not set in CircleCI. So initially that value was resolving to undefined. Now it will fall into the "else if" and the url will be determined by the hash alone.

fix: add check for codebuild when updating url

---

packages/amplify-cli/src/init-steps/s9-onSuccess.ts

This warning is redundant as of this PR: https://github.com/aws-amplify/amplify-cli/pull/10839/files
Whenever the app id can't be resolved, customers would see a warning that they had reached the app limit even when they had not. Removing this warning will alleviate some confusion. 

chore: remove redundant app id error

---

packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/generate-auth-trigger-template.test.ts
packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/generate-auth-trigger-template.ts

fix: add permissions boundary for IAM Role created for auth trigger
N/A
manually executing the use case and unit tests

fix: add permissions boundary to IAM Role created for auth trigger

---

packages/amplify-cli-npm/binary.ts

This line was missing from the url logic, it was previously spilt up to work with CodeBuild and CircleCI and the line was lost in the process. Commit hash is required to download the binary during CI.
Follow up to: https://github.com/aws-amplify/amplify-cli/pull/12924

ci: fix commit hash missing on codebuild

---

packages/amplify-category-custom/src/__tests__/utils/build-custom-resources.test.ts
packages/amplify-category-custom/src/utils/build-custom-resources.ts
packages/amplify-cli-core/src/__tests__/hooks/hooksExecutor.test.ts
packages/amplify-cli-core/src/hooks/skipHooks.ts
packages/amplify-cli-core/src/overrides-manager/override-skeleton-generator.ts
packages/amplify-cli/src/__tests__/execution-manager.test.ts
packages/amplify-e2e-tests/src/__tests__/auth_6.test.ts
packages/amplify-e2e-tests/src/__tests__/custom_resources.test.ts
packages/amplify-e2e-tests/src/__tests__/init_e.test.ts
packages/amplify-e2e-tests/src/__tests__/storage-5.test.ts

This adds support for aborting deployments if skipping overrides and custom resources is optionally set by the flag AMPLIFY_CLI_DISABLE_SCRIPTING_FEATURES.

fix: skip overrides and custom flag

---

packages/amplify-cli-core/API.md
packages/amplify-cli-core/package.json
packages/amplify-cli-core/src/utils/arn-parser.ts
packages/amplify-cli-core/src/utils/index.ts
packages/amplify-provider-awscloudformation/src/__tests__/aws-utils/IdentityPoolService.test.ts
packages/amplify-provider-awscloudformation/src/aws-utils/IdentityPoolService.ts
yarn.lock

Allow more than 1 forward slash in role arns for authenticated and unauthenticated roles when importing auth
This PR is nearly a duplicate of #12987, but it targets the hotfix branch.
Fixes https://github.com/aws-amplify/amplify-cli/issues/12817
Manually imported auth (Cognito User Pool and Identity Pool) with multiple slashes in the IAM role names for auth and unauth. Created test web app to confirm account creation and sign-in/sign-out.
These steps fail with 12.2.0 CLI, but succeed with PR changes.

fix: parsing arn with multiple slashes when importing auth

---

packages/amplify-e2e-tests/src/__tests__/custom-resource-with-storage.test.ts
packages/amplify-e2e-tests/src/__tests__/import_s3_3.test.ts
packages/amplify-e2e-tests/src/__tests__/init-special-case.test.ts
packages/amplify-e2e-tests/src/__tests__/layer-1.test.ts
packages/amplify-e2e-tests/src/__tests__/parameter-store-2.test.ts
packages/amplify-e2e-tests/src/__tests__/tags.test.ts
packages/amplify-e2e-tests/src/__tests__/with-babel-config.test.ts
packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts

Some bucket names were not being generated with a 'test' substring to match the cleanup regex.
This will allow those tests to produce buckets which can be cleaned up by the cleanup script.

ci: update env names to match cleanup regex

---

shared-scripts.sh

IS_AMPLIFY_CI is not set during verify-api-extract in CircleCI; this updates it to match in CodeBuild, which sets it globally.
For codebuild to be the same, we need to manually unset IS_AMPLIFY_CI.
If we don't do this, IS_AMPLIFY_CI flag is detected during the install of amplify-cli-npm package during verify-api-extract, which would try to download the pkg cli using the commit hash instead of from production. The download the amplify-cli is caused by a post install script, and is not relevant to the verify-api-extract step.
See for more context: https://github.com/aws-amplify/amplify-cli/pull/13012/files/a34d2ddb08d759b778f092d490d8e3043df432ab#r1276765401

ci: fix verify-api-extract codebuild

---

packages/amplify-e2e-tests/src/__tests__/layer-1.test.ts

This PR fixes the failing `layer-1.test.ts` e2e test due to the environment name being too long
https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/22457/workflows/f59c5276-1241-40b8-a6a5-8cd0f2b85d40/jobs/1038177

test: fix layer e2e, env name has 10 character limit

---

packages/amplify-frontend-ios/lib/amplify-xcode.js

adds quotes to `--path` option values to prevent breaking when absolute path to amplify project contains spaces
fixes #12593

fix(amplify-frontend-ios): encapsulate path option values with quotes

---

scripts/cloud-e2e.sh

Currently when running `yarn cloud-e2e` it creates a branch in this repo before authenticating. If authentication fails, the branch is left behind. This PR switches the order of these two steps.
Ran `yarn cloud-e2e`

chore: move authentication before branch creation in cloud-e2e script

---

packages/amplify-cli-core/src/utils/packageManager.ts

Remove the `.cmd` extension from `yarn` for Windows since it's not needed and causes issues with teams working across multiple OS's
https://us-east-1.console.aws.amazon.com/codesuite/codebuild/671107461633/projects/AmplifyCLI-E2E-Testing/batch/AmplifyCLI-E2E-Testing:1306a0c1-9604-4ed5-906c-96f456d5bf3a?region=us-east-1#
I'm relying on this [test](https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-e2e-tests/src/__tests__/function_14.test.ts) for verification.

fix: do not store windows specific package manager extension

---

package.json
scripts/cloud-pr.sh

Ability to kick off PR run manually.
```
yarn cloud-pr
```
```
$ yarn cloud-pr
What is your PR number ? 13070
Did you submit PR from fork (y/n)? y
PIN for sobkamil:
Press the button on your U2F token...
Successfully authenticated using u2f, session cookie saved in /Users/sobkamil/.midway/cookie
Successfully signed SSH public key /Users/sobkamil/.ssh/id_ecdsa.pub. The SSH certificate was saved in /Users/sobkamil/.ssh/id_ecdsa-cert.pub
2023/08/03 13:26:54 This profile appears to be ada managed, so there is no need to explicitly update.
2023/08/03 13:26:54 Your credentials will be pulled automatically, so you may continue on with your workflow.
https://us-east-1.console.aws.amazon.com/codesuite/codebuild/671107461633/projects/AmplifyCLI-PR-Testing/batch/AmplifyCLI-PR-Testing:732a33ba-6411-493 …
```

chore: manual pr build script

---

.circleci/config.yml

Setup job is required to run release/release_rc/tagged-release.*, so we can disable those workflows by locking down the setup job so it only runs during PR/E2E workflows.

ci: disable release workflows

---

.circleci/codebuild-checkout.sh
scripts/cloud-pr.sh

I keep running into weird corner cases with manual PR build like:
- if submitted from branch from main repo, branch ref is passed to CB
- if submitted from fork, current inference works well
- if submitted from fork but also pushed to e2e branch before,  somehow ref to e2e branch lands in CB
In order to simplify this, and because we have control over submitting manual build. I define an env var that I pass from manual script that is then used in CB to infer that we're in PR workflow.

chore: simplify manual pr script

---

codebuild_specs/e2e_workflow.yml
codebuild_specs/e2e_workflow_base.yml
codebuild_specs/e2e_workflow_generated.yml
codebuild_specs/lint.yml
codebuild_specs/pr_workflow.yml
shared-scripts.sh

ci: add lint in cb

---

.circleci/local_publish_helpers.sh
.circleci/local_publish_helpers_codebuild.sh
packages/amplify-cli-npm/binary.ts

Reverts aws-amplify/amplify-cli#13071, uploading pkg binaries step is now failing when there is a version conflict; see failure here https://tiny.amazon.com/s9vu3e41/IsenLink

Revert "test: remove extra hash"

---

codebuild_specs/pr_workflow.yml
scripts/wait-for-all-codebuild.ts

This PR:
- adds 2 jobs to PR workflow that were missed comparing to CCI workflow.
- configured retries in "wait for jobs" script to reduce impact from throttling

ci: add build test standalone and verify pkg cli to pr workflow

---

.github/workflows/codeql-tests.yaml
.github/workflows/codeql.yaml

Currently, starting e2e tests on a PR cause our CodeQL action to run again. This PR updates the action to ignore e2e branches.
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/customizing-code-scanning#avoiding-unnecessary-scans-of-pull-requests
See checks below. E2e tests were intentionally cancelled.

ci: configure codeql to ignore e2e branches

---

packages/amplify-cli/package.json
packages/amplify-provider-awscloudformation/package.json
packages/amplify-util-mock/package.json
packages/amplify-util-uibuilder/package.json
yarn.lock

Bump amplify codegen to 4.3.0, which includes swift modelgen change of improved pluralization

chore: bump amplify-codegen

---

.circleci/cb-publish-step-1-set-versions.sh
.circleci/publish-step-1-set-versions.sh
scripts/cloud-release.sh
scripts/finish-release.ts
scripts/promote-rc-codebuild.sh
scripts/promote-rc.sh
scripts/release-rc-codebuild.sh
scripts/release-rc.sh
scripts/tag-rc.sh

Team members run into a problem of `git rev-parse --short` yielding extra characters locally if they have more remotes connected to repository. This then impacts release scripts which are unable to find relevant RC branches when promoting RCs.
In order to reduce probability of that happening this PR increases minimum short hash size to 15 (from 10 that seems to be picked by default).

ci: use longer rc hashes

---

.circleci/cb-publish-step-4-push-to-git.sh

There's no point running push hooks in release pipelines. 

ci: skip push hooks in releases

---

packages/amplify-provider-awscloudformation/src/aws-utils/aws-cognito-client.ts

Handle profile load gracefully like other aws client factories do. So that they use default cred chain as fallback.
See for reference:
https://github.com/aws-amplify/amplify-cli/blob/5140bb223512c10f675e75fe8cc193e674ce796d/packages/amplify-provider-awscloudformation/src/aws-utils/aws-s3.ts#L52-L57
https://github.com/aws-amplify/amplify-cli/blob/5140bb223512c10f675e75fe8cc193e674ce796d/packages/amplify-provider-awscloudformation/src/aws-utils/aws-ssm.ts#L12-L17
Existing E2E tests.

fix: handle profile load in cognito client factory

---

.circleci/cb-publish-step-1-set-versions.sh

The `[ci skip]` flag was used by CircleCI to not run workflow after pushing release commit.
In CodeBuild we no longer trigger releases from push events, so this flag is no longer useful.

ci: remove skip ci flag

---

scripts/release-rc-codebuild.sh

The RC branch creation script attempts to merge main. Sometimes that merge results in extra commit added to RC branch. When that happens the RC branch name does not match RC version that we publish. This then makes RC promotion fail as scripts are looking for wrong sha. 
We used to mitigate this by hand by creating missing branch (i.e. renaming).
This PR adds an action to rc script to rename branch to match HEAD commit if needed.
Tested by changing upstream to fork and executing script.
**No merge commit scenario**
```
bcd0740fa72c:amplify-cli sobkamil$ ./scripts/release-rc-codebuild.sh 68a4d18fdfdd93568702e2ec96c6dde5f94da6a6
Fetching origin
Fetching upstream
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
warning: The last gc …
```

ci: account for merge in rc script

---

packages/amplify-cli-logger/.npmignore
packages/amplify-environment-parameters/.npmignore
packages/amplify-frontend-flutter/.npmignore
packages/amplify-frontend-javascript/.npmignore
packages/amplify-prompts/.npmignore
packages/amplify-util-mock/.npmignore
packages/amplify-util-uibuilder/.npmignore

I've noticed that we ship unnecessary files to npm.
Repro:
- create any npm project `npm init`
- add latest `@aws-amplify/cli-internal` as dependency
- `npm install`
- search for `describe` (or some other test keyword) in node_modules.
E2E tests https://us-east-1.console.aws.amazon.com/codebuild/home?region=us-east-1#/builds/build-batch/AmplifyCLI-E2E-Testing:d4b76a83-a078-4741-b0bb-0743f81cae3b/view/new

fix: exclude tests from npm publish

---

packages/amplify-e2e-tests/src/cleanup-codebuild-resources.ts
packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts

This fixes a bug where stacks were classified as stale even if they were younger than 2hrs.
Debugged E2E workflow with https://github.com/aws-amplify/amplify-cli/commit/66c7ee7d0d64a9a2c6f2c72af3209a8c0f929211 .

ci: fix cleanup script - stale stack detection

---

packages/amplify-provider-awscloudformation/src/__tests__/graphql-resource-manager/dynamodb-gsi-utils.test.ts
packages/amplify-provider-awscloudformation/src/graphql-resource-manager/amplify-graphql-resource-manager.ts
packages/amplify-provider-awscloudformation/src/graphql-resource-manager/dynamodb-gsi-helpers.ts

Adding a new flag to support overriding DynamoDB GSI limits for customers with limit increases in dynamodb. Also fix printing the name since in general it's not a string, but a `Ref` object.
By executing `amplify push --disable-gsi-limit-check` the limit checks will be disabled.
Relevant docs update: https://github.com/aws-amplify/docs/pull/5836
https://github.com/aws-amplify/amplify-category-api/issues/1812
Unit Tests, and ran w/ a `setup-dev` target, with a stubbed out low value.

feat: add flag to disable gsi limit check in iterative deployments

---

.github/CODEOWNERS

This PR changes `CODEOWNERS` file to require a member of `amplify-cli-admins` group to approve the change.
Github evaluates branch protection rules (in a form we have them) in such a way that:
1. It requires quorum (min number of reviewers) this can be anybody with write access to repo.
2. It requires a code owners to approve changes under certain paths. At least one code owner approval fulfills this requirement.
Therefore combination of rules above serves effectively as two tier approval process.

chore: require amplify cli admin to approve pull requests

---

scripts/cloud-e2e.sh
scripts/cloud-pr.sh

This PR is to address cases when one of commands fails in the middle of `cloud-e2e` and `cloud-pr` scripts.
Before change script was proceeding and gave confusing output like this:
```
./scripts/cloud-pr.sh: line 10: ada: command not found
The config profile (cb-ci-account) could not be found
https://us-east-1.console.aws.amazon.com/codesuite/codebuild//projects/AmplifyCLI-PR-Testing/batch/?region=us-east-1
```
I.e. absence of `ada` tool resulted in cascade of failures instead of stopping just there.
Additionally switching to less privilidged `CodeBuildE2E` role.
1. Running `yarn cloud-pr` to validate this PR.
1. Tested negative case by injecting error.
```
bcd0740fa72c:amplify-cli sobkamil$ yarn cloud-pr
What is your PR number ? 23456
PIN for sobkamil:
Press the button on your U2F …
```

ci: fail fast in pr and e2e scripts

---

packages/amplify-cli/src/__tests__/execution-manager.test.ts
packages/amplify-cli/src/execution-manager.ts

We are releasing support for codegen and modelgen without an amplify project being initialized. In order for this to work, the customer will specify a few required cli options, include the modelgen `target` (a superset of amplify frontend), `model-schema` location, and `output-dir`.
However, due to the postModelgenHook, even after a successful execution of modelgen in a non-amplify environment, we see the amplify-frontend-ios package failing due to failure to retrieve backends/paths/etc.
Because we don't generally want lifecycle hooks to fail in this modified runtime environment, I'm disabling them in general if the flags indicating running in an uninitialized state are present, and to log a message indicating this as well.
N/A
Updated unit tests, and verified w/ `setup-dev`.
By …

feat: ensure modelgen does not throw an error when running in an uninitialized directory

---

packages/amplify-prompts/src/__tests__/spinner.test.ts
packages/amplify-prompts/src/progressbars/spinner.ts

This PR makes Spinner noop in non-TTY terminals.
Customers who spawn CLI process as child process or stream logs to files observe control characters and transitions in output. These are not needed in these scenarios and only obscure output.
1. Added unit tests
2. Ran full e2e suite.
3. Manual checks
1. Stream to logs withouth fix
2. Stream to logs with fix
3. push in TTY terminal to validate spinner is rendering
**Before change - log to file**
**After change - log to file**
**TTY**
(see spinner next to "This will take few minutes", the other is harder to catch as it uploads faster).

fix: don't render spinner in non-TTY terminal

---

.circleci/cb-publish-step-2-verdaccio.sh
.circleci/cb-publish-step-3-npm.sh

Fixes lerna publish script to explicitly exit when ERR! happens.
1. This PR's build and e2e tests job (this does run publish to verdaccio).
2. Tested added snippet with faked error.
```
bcd0740fa72c:~ sobkamil$ nano test_publish.sh
bcd0740fa72c:~ sobkamil$ touch /tmp/publish-results
bcd0740fa72c:~ sobkamil$ ./test_publish.sh
Success! Lerna publish succeeded.
bcd0740fa72c:~ sobkamil$ cp ./lerna_error.txt /tmp/publish-results
bcd0740fa72c:~ sobkamil$ ./test_publish.sh
Fail! Lerna error.
bcd0740fa72c:~ sobkamil$ echo $?
1
bcd0740fa72c:~ sobkamil$ cat test_publish.sh
number_of_lerna_errors=$(grep -c "lerna ERR" /tmp/publish-results)
if [[ number_of_lerna_errors -gt 0 ]]; then
echo "Fail! Lerna error."
exit 1;
else
echo "Success! Lerna publish succeeded."
fi
bcd0740fa72c:~ sobkamil$ cate …
```

fix: lerna publish script

---

packages/amplify-cli/package.json
packages/amplify-provider-awscloudformation/package.json
packages/amplify-util-mock/package.json
packages/amplify-util-uibuilder/package.json
yarn.lock

Includes fix for multiple swift files
Upgrade amplify-codegen to include fix for https://github.com/aws-amplify/amplify-codegen/issues/711

chore: upgrade amplify-codegen

---

.circleci/local_publish_helpers_codebuild.sh
package.json
packages/amplify-appsync-simulator/package.json
packages/amplify-category-auth/package.json
packages/amplify-category-function/package.json
packages/amplify-category-geo/package.json
packages/amplify-category-notifications/package.json
packages/amplify-category-predictions/package.json
packages/amplify-category-storage/package.json
packages/amplify-cli-npm/index.ts
packages/amplify-cli/package.json
packages/amplify-console-integration-tests/package.json
packages/amplify-dynamodb-simulator/package.json
packages/amplify-e2e-core/package.json
packages/amplify-e2e-tests/package.json
packages/amplify-environment-parameters/package.json
packages/amplify-opensearch-simulator/package.json
packages/amplify-provider-awscloudformation/package.json
packages/amplify-util-mock/package.json
packages/amplify-util-uibuilder/package.json
packages/amplify-util-uibuilder/src/__tests__/generateComponents.test.ts
packages/amplify-util-uibuilder/src/__tests__/notifyMissingPackages.test.ts
packages/amplify-util-uibuilder/src/commands/generateComponents.ts
packages/amplify-util-uibuilder/src/commands/utils/notifyMissingPackages.ts
yarn.lock

Update the StartCodegenJob operation to be backwards compatible for amplify js. StartCodegenJob is now passed the relevant local project dependencies for codegen to know which version of amplify js to codegen.
E.g. If the local project has a dependecy of `aws-amplify ^5.0.2`, then codegen will generate v5 compatible code. If there are no dependencies yet, codegen will generate the latest code available and recommend to install the dependencies.
Linux threshold increase:
The new aws-sdk version is needed to finish the feature. It also triggered the linux arm compressed threshold to be crossed. This increases the limit so it can pass.
NA
Unit test
Testing against a personal app
Currently running e2e tests, I'll update when they complete here.
By submitting this pull request, I confirm that …

feat(amplify-util-uibuilder): amplify js backwards compatibility

---

package.json
packages/amplify-category-function/src/provider-utils/awscloudformation/secrets/functionSecretsStateManager.ts
packages/amplify-e2e-core/src/categories/lambda-function.ts
packages/amplify-e2e-tests/src/__tests__/function_7.test.ts

Intentionally add secrets already in the cloud with `operation: 'retain'` when syncing secret deltas, this will ensure local secrets do not get removed and the removal pushed to the cloud.
Manual validation:
1. `amplify-dev init -y`
2. `amplify-dev add function` - Add function with 1 secret
3. `amplify-dev push`
4. `amplify-dev env add devtwo` - Add another env
5. `amplify-dev push` - Push function with 1 secret to new env
6. `amplify-dev function configure` - Add new secret
7. `amplify-dev push` - Push new secret to env devtwo
8. `amplify-dev env checkout dev` - Switch to dev env, function locally still has 2 secrets
9. `amplify-dev push` - Push new secret, observe old secret still exists
Add and run new e2e test.
By submitting this pull request, I confirm that my contribution is made …

fix: add retained secrets to syncSecretDeltas

---

packages/amplify-cli-core/src/overrides-manager/override-skeleton-generator.ts
packages/amplify-e2e-tests/src/__tests__/init_e.test.ts

After running `amplify override`, if the VS Code `settings.json` file exists, set the exclude flag for the awscloudformation folder (where the `override.ts` file is created) to `false` from `true` so users can see the file in VS Code.
Manual verification and updated e2e test to assert the flag is properly changed after override.

fix: set awscloudformation flag to false in vscode settings after override

---

packages/amplify-e2e-tests/src/__tests__/transformer-migrations/predictions-migration.test.ts
packages/amplify-provider-awscloudformation/src/__tests__/aws-utils/IdentityPoolService.test.ts
packages/amplify-provider-awscloudformation/src/aws-utils/IdentityPoolService.ts

Correctly parse Cognito user/identity pools with `service-role` prepended (e.g. `arn:aws:iam::<account-id>:role/service-role/roleName`).
#13345
Manually with `amplify-dev import auth` and Cognito user/identity pools with `service-role`.
Updated unit tests and added IAM regex validation for roles.

fix: parse cognito pools with service role

---

packages/amplify-e2e-core/src/init/amplifyPull.ts

Modify `amplifyStudioHeadlessPull` to use `TEST_PROFILE_NAME` so that it works with `default` profile locally.
running test locally.

test: use test profile name

---

packages/amplify-cli/package.json
packages/amplify-container-hosting/package.json
packages/amplify-util-uibuilder/package.json
yarn.lock

Added region support for HKG
Full changelog: https://github.com/aws-amplify/amplify-category-api/releases/tag/%40aws-amplify%2Famplify-category-api%405.7.7

chore: bump api category to 5.7.7

---

package.json
yarn.lock

Addresses: https://github.com/aws-amplify/amplify-cli/security/dependabot/196

chore: bump undici to ^5.26.2

---

yarn.lock

Addresses https://github.com/aws-amplify/amplify-cli/security/dependabot/200

chore: upgrade browserify-sign to 4.2.2

---

.circleci/cb-publish-step-4-push-to-git.sh

This adds missing `--no-verify` to tag push which blocked release.
Fix is targeting hotfix branch to get it in releasable state and will be cherry-picked into `dev`
```
[Container] 2023/11/08 20:35:38.725824 Waiting for agent ping
[Container] 2023/11/08 20:35:39.726711 Waiting for DOWNLOAD_SOURCE
[Container] 2023/11/08 20:36:11.290254 Phase is DOWNLOAD_SOURCE
[Container] 2023/11/08 20:36:11.433794 CODEBUILD_SRC_DIR=/codebuild/output/src850/src/github.com/aws-amplify/amplify-cli
[Container] 2023/11/08 20:36:11.434123 CODEBUILD_SRC_DIR_publish_to_npm_publish_to_npm=/codebuild/output/src850/src/publish_to_npm/publish_to_npm
[Container] 2023/11/08 20:36:11.434922 YAML location is /codebuild/output/src850/src/github.com/aws-amplify/amplify-cli/codebuild_specs/release_workflows/post_publish_push …
```

fix: github push script

---

packages/amplify-migration-tests/src/__tests__/migration_tests_v12/auth-hosted-ui-lambda-migration.test.ts
scripts/cloud-cli-utils.sh
scripts/cloud-pr.sh

This PR:
1. adds credential refresh to auth migration test (it sometimes hits token expiry)
2. removes deprecated `--aea` option from scripts

test: add credential refresh to long-running test

---

packages/amplify-provider-awscloudformation/package.json
packages/amplify-provider-awscloudformation/src/amplify-service-manager.ts
packages/amplify-provider-awscloudformation/src/initializer.ts
yarn.lock

**Issue**: canary run `amplify init ....` sometimes have "The specified bucket does not exist" error.
**Hypothesis**: the S3 bucket name is not random enough, so the bucket could be accidentally deleted by another task.
**Fix**: Make the bucket name more random

fix: s3 bucket name randomizer

---

codebuild_specs/e2e_workflow_base.yml
codebuild_specs/e2e_workflow_generated.yml
codebuild_specs/run_e2e_tests_windows.yml
codebuild_specs/scripts-windows/run-e2e-windows.sh
scripts/select-region-for-e2e-test.ts
scripts/split-e2e-tests-codebuild.ts
shared-scripts.sh

This PR's goal is to remove as much of `CLI_REGION` assignment from generated e2e workflow as possible to free up space (cb yml files have hard size limit).
Therefore:
1. Split e2e test script does not assign region unless test is force-pinned to some region.
2. Adds a script that assigns region at runtime using job identifier.
E2E test run
From handful of jobs:

build: assign region at runtime in e2e tests

---

packages/amplify-provider-awscloudformation/resources/update-idp-roles-cfn.json

When auth is removed, set the auth and unauth role policies to deny
Manually verified with a local deployment. Existing tests are passing (yet to run e2e). We can write an e2e test for this, but want to get the fix out first.

fix: set policy effect deny when removing auth

---

packages/amplify-cli-core/package.json
packages/amplify-cli/package.json
yarn.lock

https://github.com/aws-amplify/amplify-cli/security/dependabot/209
Before:
```
❯ yarn why lodash.set
└─ nock@npm:13.2.1
└─ lodash.set@npm:4.3.2 (via npm:^4.3.2)
```
After:
```
❯ yarn why lodash.set
```

fix: dependabot alert for lodash.set

---

packages/amplify-graphiql-explorer/package.json
yarn.lock

Bump webpack dependency versions.

fix: bump webpack deps version

---

packages/amplify-cli-core/src/__tests__/hooks/hooksExecutor.test.ts
packages/amplify-cli-core/src/hooks/hooksExecutor.ts

When `execa` handles a hooks file that executes very fast, we have a race condition where `execa` will try to pipe inputs to the child process's `stdin` after the process finishes causing an `EPIPE` error (Refer to https://github.com/sindresorhus/execa/issues/474).
The change is to not have `execa` reject initially so we can determine what to do:
- If the hooks file executed successfully (child process exit code is 0), then we continue execution.
- If not, then we go through our existing error handling.
Also updated how we pipe `stdout` for the child process, this caused the misconception that the hooks file was not running at all (no `echo` in the hooks file is presented).
Added unit tests and manually tested with the following pre-push and post-push hooks files:
```ts
// pre-push.sh …
```

fix(amplify-cli-core): gracefully handle execa race condition

---

packages/amplify-cli/src/__tests__/input-validation.test.ts
packages/amplify-cli/src/index.ts
packages/amplify-cli/src/input-manager.ts

If `@aws-amplify/cli` is installed globally and you run `npx amplify ...` for Amplify Gen 2 then you get an unhelpful command not found error.
This PR updates the error message to direct users to either install Gen 2 CLI or update their execute command to use Gen 2.
Unit tests and manually with `amplify-dev generate config`:

chore(cli-internal): direct to gen2 for command not found error

---

packages/amplify-provider-awscloudformation/package.json
packages/amplify-provider-awscloudformation/src/aws-utils/aws-s3.ts
packages/amplify-provider-awscloudformation/src/download-api-models.ts
packages/amplify-provider-awscloudformation/src/zip-util.ts
packages/amplify-provider-awscloudformation/tsconfig.json
yarn.lock

This PR is a partial revert of https://github.com/aws-amplify/amplify-cli/pull/13493/files which caused https://github.com/aws-amplify/amplify-cli/issues/13681 .
I.e. using `s3.upload` API for all uploads puts a memory pressure due to https://github.com/aws/aws-sdk-js/issues/2552 .
This PR changes file uploading logic to buffer all files below 5mb in memory. This partially restoring previous behavior but avoiding full revert to `s3.putObject` API call which doesn't have retries.
https://github.com/aws-amplify/amplify-cli/issues/13681
PR checks and E2E tests.
Manual verification on `t2.nano` with sample test project where `ENOMEM` has been reproduced. 

fix: reduce memory pressure while uploading files

---

packages/amplify-category-auth/resources/adminAuth/admin-auth-cognitoActions.js

Added pagination for listGroups admin api action. Cognito listGroups API returns nextToken not PaginationToken.
Ref :- https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListGroups.html
https://github.com/aws-amplify/amplify-cli/issues/13722
Lambda code :-
Results :-
- [Y] PR description included
- [Y ] `yarn test` passes

fix(amplify-category-auth): added pagination for listGroups api action

---

scripts/wait-for-all-codebuild.ts
shared-scripts.sh

After https://github.com/aws-amplify/amplify-cli/pull/13738, there are 2 problems found:
1. the log only works if `accountForFailures` is `true`
2. if `CODEBUILD_WEBHOOK_TRIGGER` is `unset` or `null`, `accountForFailures` would become the 5th param
In this PR:
- moved the `CODEBUILD_WEBHOOK_TRIGGER` log out of the `accountForFailures` check
- set a default value `empty` for `CODEBUILD_WEBHOOK_TRIGGER`
tested in codebuild

fix: log batch trigger

---

packages/amplify-go-function-runtime-provider/src/runtime.ts

After https://github.com/aws-amplify/amplify-cli/pull/13671/files#diff-9e8ed84544b6574832f1d34bde8bc4fffff3558a54806adb09b4884758ff618aR105, Go project would fail if it has more functions than `main.go`. 
To fix it, we need to build all Go files instead of only `main.go`.
Special thanks to @ykethan  for diving into this issue.
https://github.com/aws-amplify/amplify-cli/issues/13725
verified with my local test project. 

fix: fix Go project with multiple files

---

codebuild_specs/build_pkg_binaries_arm.yml
codebuild_specs/build_pkg_binaries_linux.yml
codebuild_specs/build_pkg_binaries_macos.yml
codebuild_specs/build_pkg_binaries_win.yml
codebuild_specs/e2e_workflow.yml
codebuild_specs/e2e_workflow_base.yml
codebuild_specs/e2e_workflow_generated.yml
codebuild_specs/pr_workflow.yml
codebuild_specs/publish_to_local_registry.yml
codebuild_specs/release_workflows/hotfix_workflow.yml
codebuild_specs/release_workflows/release_rc_workflow.yml
codebuild_specs/release_workflows/release_workflow.yml
codebuild_specs/release_workflows/tagged_release_without_e2e_workflow.yml
codebuild_specs/upload_pkg_binaries.yml
codebuild_specs/verify_pkg_cli.yml
codebuild_specs/verify_versions_match.yml
codebuild_specs/wait_upb.json

This PR removes active polling that was in place to mitigate CodeBuild graph evaluation inefficiencies. Please see https://github.com/aws-amplify/amplify-cli/pull/13121 for details about inefficiencies.
These inefficiencies has been adressed and this PR removes most of active polling. The only place with active polling that remains is the job that runs after all e2e tests and needs to await on all job ids. Producing `depends-on` statement for that job must remain in place for now due to us hitting YML file size limits.
Kicked off PR and E2E workflows.
Observed that jobs are awaiting on only required ones from previous level of nesting.
See

chore: reduce active polling in code build workflows

---

packages/amplify-cli-core/src/extractZip.js

Currently we are abandoning a zip entry after creating a red stream for it which doesn't get closed as nobody read from it.
This PR avoids creating read stream for zip entries that we won't be extracting.
Also adds a log message when we detect symlink

fix: do not create read stream for zip entries that are not being extracted

---

packages/amplify-cli-core/package.json
packages/amplify-cli-core/src/__tests__/extractZip.test.ts
packages/amplify-cli-core/src/extractZip.js
packages/amplify-provider-awscloudformation/src/attach-backend.ts
packages/amplify-provider-awscloudformation/src/utils/archiver.js
yarn.lock

This PR removes `types/` folder from backend -> current cloud backend -> s3 -> current cloud backend -> backend flow.
The types folder is always regenerated, therefore it's not needed to include it in that flow.
1. added unit tests for unzipper
2. full e2e run

fix: skip types in current cloud backend

---

packages/amplify-category-notifications/src/__tests__/channel-fcm.test.ts
packages/amplify-category-notifications/src/channel-fcm.ts

migrate FCM channel authentication from ApiKey to ServiceToken based
https://github.com/aws-amplify/amplify-cli/issues/13688
Manually tested and unit tested.

fix: migrate FCM channel authentication from ApiKey to ServiceToken based

---

packages/amplify-cli-core/src/feature-flags/featureFlags.ts

Add a new FF for data plugin to allow customers to opt-in for a subscriptions field redaction behavior.
- If the feature flag is disabled (when set to `false`), relational fields will be over-redacted in mutations response and subscribed clients won't receive this data in payload.
- If the feature flag is enabled (when set to `true`), subscriptions will inherit the auth rules of the model for the relational fields. It means that the relational fields won't be over-redacted on mutations.

fix(cli): add feature flag to control subscription field redaction behavior

---

packages/amplify-provider-awscloudformation/resources/rootStackTemplate.json
packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/__snapshots__/root-stack-builder.test.ts.snap
packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/__snapshots__/root-stack-transform.test.ts.snap
packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-builder.ts

Re-applying changes initially attempted in https://github.com/aws-amplify/amplify-cli/pull/10533
For more details on implementation, see guidance here: https://repost.aws/knowledge-center/s3-bucket-policy-for-config-rule
Tests updated to ensure ssl is enforced.

fix: enforce ssl on s3 deployment bucket

---

packages/amplify-gen1-codegen-auth-adapter/src/auth_render_adapter.ts
packages/amplify-gen1-codegen-auth-adapter/src/index.ts
packages/amplify-gen2-codegen/src/auth/source_builder.test.ts
packages/amplify-gen2-codegen/src/auth/source_builder.ts
packages/amplify-gen2-codegen/src/backend/synthesizer.test.ts
packages/amplify-gen2-codegen/src/backend/synthesizer.ts
packages/amplify-gen2-codegen/src/index.ts
packages/amplify-migration/src/app_auth_definition_fetcher.ts
packages/amplify-migration/src/index.ts

Adds a comment to the directory where the Gen 1 source for a given trigger is stored:
```typescript
import { defineAuth, defineFunction } from "@aws-amplify/backend";
export const auth = defineAuth({
loginWith: {
email: true,
},
triggers: {
/*
Source code for this function can be found in your Amplify Gen 1 Directory.
See amplify/backend/function/authwithcustompasswoc8d0cd5bPostAuthentication/src
*/
postAuthentication: defineFunction({}),
},
multifactor: {
mode: "OPTIONAL",
totp: false,
},
}); 
```
Unit tests and manual validation

Feat: Auth triggers comments to gen 1 function source directory

---

packages/amplify-cli-core/API.md
packages/amplify-gen1-codegen-auth-adapter/API.md
packages/amplify-gen1-codegen-auth-adapter/src/auth_render_adapter.ts
packages/amplify-gen1-codegen-auth-adapter/src/index.ts
packages/amplify-gen2-codegen/API.md
packages/amplify-gen2-codegen/src/auth/source_builder.ts
packages/amplify-gen2-codegen/src/function/lambda.test.ts
packages/amplify-gen2-codegen/src/function/lambda.ts
packages/amplify-gen2-codegen/src/index.ts
packages/amplify-gen2-codegen/src/storage/source_builder.test.ts
packages/amplify-gen2-codegen/src/storage/source_builder.ts
packages/amplify-gen2-codegen/src/test_utils/ts_node_printer.ts
packages/amplify-migration/API.md
packages/amplify-migration/src/app_storage_definition_fetcher.ts
packages/amplify-migration/src/index.ts

Begins adding triggers for storage. Refactors `defineFunction` codegen into its own module. Updates API files for last several PRs.
Unit tests

feat: storage triggers

---

packages/amplify-migration/src/data_definition_fetcher.test.ts
packages/amplify-migration/src/data_definition_fetcher.ts

Handles cases where the data stack is undefined during data codegen in apps that do not have data configured.

fix: data definition fetcher handle undefined data stack

---

packages/amplify-appsync-simulator/package.json
packages/amplify-appsync-simulator/src/server/index.ts
yarn.lock

Remove dependency on poorly maintained "ip" package, which has an open security advisory https://github.com/indutny/node-ip/issues/150
Implement an equivalent `getLocalIpAddress()` function that returns the first internal IP address. This is used by clients of the `appsync-sumulator` to connect to.
https://github.com/aws-amplify/amplify-cli/issues/13890
Ran `yarn lerna run --scope @aws-amplify/amplify-appsync-simulator test`

fix: remove node-ip dependency

---

packages/amplify-e2e-tests/src/__tests__/auth/user-groups-s3-access.test.ts

Currently S3 access E2E tests are looking for `Access Denied` when expecting user group that does not have permissions to interact with S3 bucket. The new message received is now something like:
`User: <user group arn> is not authorized to perform: s3:GetObject on resource: <S3 bucket> because no identity-based policy allows the s3:GetObject action`
Update E2E test to expect `not authorized to perform` instead of `Access Denied`.

fix: update message when expecting S3 to throw

---

packages/amplify-gen1-codegen-auth-adapter/package.json
packages/amplify-gen1-codegen-data-adapter/package.json
packages/amplify-gen1-codegen-function-adapter/package.json
packages/amplify-gen1-codegen-storage-adapter/package.json
packages/amplify-gen2-codegen/package.json
packages/amplify-migration-codegen-e2e/package.json
packages/amplify-migration/package.json

Add` public` access to `publishConfig` to be able to publish gen2 migration packages to `npm`.

fix: make gen2 migration packages public

---

packages/amplify-migration/src/index.ts

Added a validation to check for empty object in case of unsupported categories

fix: check for empty objects

---

packages/amplify-gen2-codegen/src/data/source_builder.test.ts
packages/amplify-gen2-codegen/src/data/source_builder.ts

fix: move importedModels key up to defineData. It should be like the following (not nested under `importedAmplifyDynamoDBTableMap`).
```typescript
export const data = defineData({
importedAmplifyDynamoDBTableMap: { Todo: "my-todo-mapping" },
importedModels: ["Todo"],
schema: "TODO: Add your existing graphql schema here"
});
```
N/A
Add new unit test.

fix: move importedModels key up to defineData

---

packages/amplify-migration-template-gen/src/resolvers/cfn-parameter-resolver.test.ts
packages/amplify-migration-template-gen/src/resolvers/cfn-parameter-resolver.ts

Add CFN parameter resolver to resolve Gen1 resources with parameters before refactoring them into Gen2 stack.
TODO: Add code to retrieve secret values in params using CLI utils: https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-cli/src/extensions/amplify-helpers/envResourceParams.ts#L62
Local testing, unit tests 

Gen2 Migration template gen: Add CFN parameter resolver

---

packages/amplify-cli/src/commands/init.ts

This PR adds validation to make sure that AppId passed via command line parameters match with appid stored in metadata files.
This is similar to existing validation that pull does here https://github.com/aws-amplify/amplify-cli/blob/33c10fdd6b3b53644a9162208b984a58f6871946/packages/amplify-cli/src/commands/pull.ts#L41-L45
I did the following manually:
1. Created an app. Appid `d2qe95s9uhn10w`
2. Attempted to run init flow with different app id , i.e. `amplify init --amplify "{\"envName\":\"dev\",\"appId\":\"d3jmsv5lpeg234\"}" --yes  --forcePush`

fix: prevent init if local files belong to other app

---

packages/amplify-migration-template-gen/package.json
packages/amplify-migration-template-gen/src/resolvers/cfn-output-resolver.test.ts
packages/amplify-migration-template-gen/src/resolvers/cfn-output-resolver.ts

Add CFN outputs resolver to resolve Output references in Gen1 and Gen2 stacks prior to Refactor operation.
local testing, unit tests.

Gen2 migration - Resolve CFN Outputs

---

packages/amplify-migration-template-gen/src/category-template-generator.test.ts
packages/amplify-migration-template-gen/src/category-template-generator.ts
packages/amplify-migration-template-gen/src/resolvers/cfn-output-resolver.ts
packages/amplify-migration-template-gen/src/resolvers/cfn-parameter-resolver.ts
packages/amplify-migration-template-gen/src/types.ts

Add category template generator to output CFN templates for each step of refactor. The class is category agnostic and will expose 3 methods to facilitate generation of templates needed for refactor:
1. Preprocess gen1 stack resolving parameters, outputs, conditions and dependencies
2. Remove gen2 resources prior to refactor, resolving output Refs
3. Move gen1 resources from gen1 stack to gen2 stack for refactor operation
**Note**: Each step generates the necessary templates under `.amplify/migration/templates/<category>` folder but the steps will be executed later on by the customer following the `README.md` file.
Local testing, unit tests

feat(migrate-template-gen): add category template generator

---

packages/amplify-migration-template-gen/src/template-generator.test.ts
packages/amplify-migration-template-gen/src/template-generator.ts

Add template generator to instantiate category-specific generators and read me generators and orchestrate their corresponding methods to generate templates and README files.
local testing, unit tests

Gen2 migration template gen

---

packages/amplify-cli/API.md
packages/amplify-cli/src/context-manager.ts
packages/amplify-cli/src/index.ts
packages/amplify-gen2-codegen/src/auth/source_builder.ts
packages/amplify-gen2-codegen/src/function/source_builder.ts
packages/amplify-migration/package.json
packages/amplify-migration/src/index.ts
yarn.lock

- Added a usageData metric for the codegen command
- Added the word `set` in update secret command for auth
- Updated the path to copy the source code from in functions
Tested in Beta, the metric getting generated successfully

fix: add usage data metrics for codegen

---

packages/amplify-appsync-simulator/package.json
packages/amplify-storage-simulator/package.json
yarn.lock

Bump `express` which bumps `cookie`to address https://github.com/aws-amplify/amplify-cli/security/dependabot/268

chore: bump cookie

---

packages/amplify-migration-template-gen/src/migration-readme-generator.test.ts
packages/amplify-migration-template-gen/src/migration-readme-generator.ts
packages/amplify-migration-template-gen/src/resolvers/cfn-output-resolver.test.ts
packages/amplify-migration-template-gen/src/resolvers/cfn-output-resolver.ts
packages/amplify-migration-template-gen/src/template-generator.test.ts
packages/amplify-migration-template-gen/src/template-generator.ts

- Add rollback step for stack refactor
- Skip instead of throwing error when `GetAtt` prop is not implemented for a resource
local testing, unit tests

Add rollback step for stack refactor

---

packages/amplify-migration-template-gen/src/category-template-generator.test.ts
packages/amplify-migration-template-gen/src/category-template-generator.ts
packages/amplify-migration-template-gen/src/cfn-stack-name-extractor.ts
packages/amplify-migration-template-gen/src/migration-readme-generator.ts
packages/amplify-migration-template-gen/src/resolvers/cfn-parameter-resolver.ts
packages/amplify-migration-template-gen/src/types.ts

Resolve CFN pseudo parameter references, e.g. [`AWS::StackName`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-stackname).  This is needed since Gen1 Bucket name has a `Ref` on the Gen 1 StackName and needs to be resolved prior to moving it to Gen2 stack.
unit tests

Resolve CFN pseudo parameter references

---

packages/amplify-util-mock/package.json
packages/amplify-util-mock/src/__tests__/utils/dynamo-db/helper.test.ts
packages/amplify-util-mock/src/__tests__/utils/dynamo-db/index.test.ts
packages/amplify-util-mock/src/__tests__/utils/dynamo-db/util.test.ts
yarn.lock

bump versions of path-to-regexp from 6.2.x to 8.2.0

fix: bump versions

---

packages/amplify-gen1-codegen-auth-adapter/API.md
packages/amplify-gen1-codegen-auth-adapter/src/auth_render_adapter.test.ts
packages/amplify-gen1-codegen-auth-adapter/src/auth_render_adapter.ts
packages/amplify-gen2-codegen/API.md
packages/amplify-gen2-codegen/src/auth/source_builder.ts
packages/amplify-gen2-codegen/src/backend/synthesizer.test.ts
packages/amplify-gen2-codegen/src/backend/synthesizer.ts
packages/amplify-gen2-codegen/src/index.ts
packages/amplify-migration/src/app_auth_definition_fetcher.ts

- Filter `userAttributes` to include only required attributes and not all Standard Attributes in `auth/resource.ts`
- Set userNameAtttributes to `undefined` instead of `[]` in `backend.ts`
- Modify codegen to include `identityPoolName` in `backend.ts`
Manually creating an application and running migrate command and checking the generated code. Unit tests.

fix: include only required userAttributes and generate identityPoolName in backend file

---

packages/amplify-e2e-tests/src/cleanup-codebuild-resources.ts
packages/amplify-e2e-tests/src/cleanup-e2e-resources.ts

Cleanup oidc providers after running tests.

chore: cleanup google oidc providers after tests

---

.eslint-dictionary.json
packages/amplify-migration-e2e/package.json
packages/amplify-migration-e2e/src/__tests__/migration_codegen_e2e.test.ts
packages/amplify-migration-e2e/src/__tests__/migration_templategen_e2e.test.ts
packages/amplify-migration-e2e/src/assertions.ts
packages/amplify-migration-e2e/src/envVariables.ts
packages/amplify-migration-e2e/src/gen1ResourceDetailsFetcher.ts
packages/amplify-migration-e2e/src/gen2ResourceDetailsFetcher.ts
packages/amplify-migration-e2e/src/index.ts
packages/amplify-migration-e2e/src/migrationReadmeParser.ts
packages/amplify-migration-e2e/src/sandbox.ts
packages/amplify-migration-e2e/src/sdk_calls.ts
packages/amplify-migration-e2e/src/templategen.ts
packages/amplify-migration-e2e/src/updatePackageJson.ts
yarn.lock

Added e2e integration test for templategen command which runs as a part of the `yarn e2e-migration` command
Manually checked and verified the deployed stack resources, assertion statements

feat: templategen command e2e integration tests

---

packages/amplify-cli/src/commands/init.ts

Environment variable which can be set locally or in studio to skip appId mismatch check that happens during init.

fix: add opt-out for appId mismatch check during init

---

packages/amplify-migration-template-gen/package.json
packages/amplify-migration-template-gen/src/cfn-stack-updater.ts
packages/amplify-migration-template-gen/src/custom-test-matchers.ts
packages/amplify-migration-template-gen/src/migration-readme-generator.test.ts
packages/amplify-migration-template-gen/src/migration-readme-generator.ts
packages/amplify-migration-template-gen/src/resolvers/cfn-output-resolver.ts
packages/amplify-migration-template-gen/src/setup-jest.ts
packages/amplify-migration-template-gen/src/template-generator.test.ts
packages/amplify-migration-template-gen/src/template-generator.ts
packages/amplify-migration-template-gen/src/types.ts
yarn.lock

Automate the first 2 steps of template gen prior to refactor by executing `updateStack` on behalf of the customers:
1. Resolving refs, conditions and dependencies in Gen1 stack
2. Removing dummy resource in Gen2 stack
Note: Haven't changed the command name (`execute`) yet. Will be part of another PR.
Ran the template gen command locally.

feat: automate preprocessing steps for refactor

---

packages/amplify-migration-template-gen/src/migration-readme-generator.test.ts
packages/amplify-migration-template-gen/src/migration-readme-generator.ts

Use AWS CLI new `@=`  operator to support nested file protocols needed for stack refactor operations. This will remove the need for uploading the templates to S3 bucket.
AWS CLI >= 2.20 (https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst)
> * feature:shorthand: Adds support to shorthand syntax for loading parameters from files via the ``@=`` assignment operator.
Local testing using `generate-templates` command and running stack refactor operations from `README` file.

feat(migrate-template-gen): use nested file protocol operator using @

---

.gitignore
Dockerfile
codebuild_specs/build_image.yml

Adds a new linux image version for dotnet8.
Also -IMPORTANT: updates logic so that we don't always publish to 'latest' tag.
This will allow us to pin our builds to specific versions, without replacing the 'latest' image when the ECR pipeline runs.

New Linux Image version

---

packages/amplify-migration-template-gen/API.md
packages/amplify-migration-template-gen/package.json
packages/amplify-migration-template-gen/src/category-template-generator.test.ts
packages/amplify-migration-template-gen/src/category-template-generator.ts
packages/amplify-migration-template-gen/src/oauth-values-retriever.test.ts
packages/amplify-migration-template-gen/src/oauth-values-retriever.ts
packages/amplify-migration-template-gen/src/template-generator.test.ts
packages/amplify-migration-template-gen/src/template-generator.ts
packages/amplify-migration-template-gen/src/types.ts
packages/amplify-migration/package.json
packages/amplify-migration/src/command-handlers.ts
yarn.lock

Retrieve oauth values (Facebook, Amazon, Google, Apple) for auth gen1 stack update using Cognito and SSM. This is a required pre-step before stack refactoring.
Ran template gen locally and it successfully updated:
```
../node_modules/.bin/migrate to-gen-2 generate-templates --from amplify-oauthexecute-dev-19e93 --to amplify-mygen2app-oauthexecute-sandbox-cfab5267c9
```

Gen2 migration- Retrieve oauth values for Gen1 stack update

---

packages/amplify-migration/src/command-handlers.ts
packages/amplify-migration/src/commands/gen2/execute/execute_command.test.ts
packages/amplify-migration/src/commands/gen2/execute/execute_command.ts
packages/amplify-migration/src/commands/gen2/gen2_command_factory.ts

Rename the `generate-templates` to `execute` command since we are going to automate the preprocessing of gen1 and gen2 stack updates as well as stack refactor operations.
**Note**: Stack refactor operation has not yet been automated since the stack refactor APIs are not yet launched.
Confirmed with @josefaidt  on the command name.
`yarn test`

fix(migrate): rename generate-templates to execute command

---

codebuild_specs/build_windows.yml
codebuild_specs/run_e2e_tests_windows.yml
codebuild_specs/scripts-windows/shared-scripts-windows.sh
packages/amplify-dotnet-function-runtime-provider/amplify-plugin.json
packages/amplify-dotnet-function-runtime-provider/src/constants.ts
packages/amplify-dotnet-function-runtime-provider/src/index.ts
packages/amplify-dotnet-function-runtime-provider/src/utils/detect.ts
packages/amplify-dotnet-function-runtime-provider/src/utils/invoke.ts
packages/amplify-dotnet-function-runtime-provider/src/utils/package.ts
packages/amplify-dotnet-function-template-provider/amplify-plugin.json
packages/amplify-dotnet-function-template-provider/resources/lambda/Crud/Function.csproj.ejs
packages/amplify-dotnet-function-template-provider/resources/lambda/Crud/aws-lambda-tools-defaults.json.ejs
packages/amplify-dotnet-function-template-provider/resources/lambda/HelloWorld/Function.csproj.ejs
packages/amplify-dotnet-function-template-provider/resources/lambda/HelloWorld/aws-lambda-tools-defaults.json.ejs
packages/amplify-dotnet-function-template-provider/resources/lambda/Serverless/Function.csproj.ejs
packages/amplify-dotnet-function-template-provider/resources/lambda/Serverless/aws-lambda-tools-defaults.json.ejs
packages/amplify-dotnet-function-template-provider/resources/lambda/Trigger/Function.csproj.ejs
packages/amplify-dotnet-function-template-provider/resources/lambda/Trigger/aws-lambda-tools-defaults.json.ejs
packages/amplify-dotnet-function-template-provider/resources/lambda/global.json
packages/amplify-e2e-core/src/categories/lambda-function.ts
packages/amplify-e2e-tests/src/__tests__/function_3a_dotnet.test.ts
packages/amplify-e2e-tests/src/__tests__/function_3b.test.ts
packages/amplify-e2e-tests/src/__tests__/import_s3_3.test.ts
packages/amplify-migration-tests/src/migration-helpers/lambda-function.ts

Re: https://aws.amazon.com/blogs/compute/introducing-the-net-8-runtime-for-aws-lambda/
Migrate Lambda functions to .Net 8
Related: https://github.com/aws-amplify/amplify-cli/pull/14023

feat: lambda dotnet 8 support

---

packages/amplify-gen2-codegen/src/backend/synthesizer.test.ts
packages/amplify-gen2-codegen/src/backend/synthesizer.ts

Add import for removal policy in gen2 codegen `backend.ts` file for auth.
`yarn test`

fix: add import for removal policy in gen2 codegen

---

packages/amplify-e2e-tests/src/__tests__/uibuilder.test.ts

Fixes:
- issue with cypress invalid config file when using require('cypress') - likely traced to recent changes in node/cross-spawn, but that is out of scope for this fix
- issue with installation of required dependencies leading to compilation issues during test execution

fix: UIBuilder test

---

.github/workflows/smoke-tests.yml

Fix smoke tests on windows.
The error:
```
{"version":2,"width":120,"height":30,"timestamp":55.785,"title":"Recording","env":{}}
[0.084,"o","\u001b[40muser@host\u001b[49m\u001b[30m⮀\u001b[39m\u001b[44mC:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\amplify-e2e-tests\\amplify-app_940519\u001b[49m\u001b[34m⮀\u001b[39m C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe npx.cmd amplify-app --yes\r\n"]
[0.151,"o","\u001b[2J\u001b[m\u001b[H\u001b]0;Administrator: C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\u0007\u001b[?25h"]
[0.42,"o","\u001b]0;npm\u0007"]
[0.508,"o","\u001b]0;npm exec amplify-app --yes\u0007"]
[1.955,"o","\u001b[1mnpm\u001b[22m \u001b[33mwarn \u001b[94mexec \u001b[mThe following package was not found and will be installed: amplify-app@4.3.12\r\n"] …
```

fix: smoke tests on windows

---

packages/amplify-e2e-tests/src/__tests__/transformer-migrations/model-migration.test.ts
scripts/cloud-cli-utils.sh
scripts/cloud-pr.sh
scripts/cloud-rollback.sh

Add a hardcoded delay in `model-migration.test.ts` to account for IAM role propagation. (I experimented with using an IAM waiter rather than a hardcoded delay, but couldn't get it to work in my local environment in the time I allocated for investigation. 20s seems a reasonable price to pay on a ~1600s total test run.)
**Other changes**
* Support a new `USE_FIDO_KEY` environment variable when invoking cloud utilities, to add the `-f` flag to `mwinit` invocations.
The `model-migration.test.ts` E2E test, which was previously reliably failing on Linux after applying new Data package versions, now passes reliably in both Linux & Windows.
- E2E failures are unrelated to this change, as evidenced by those failures appearing in other E2E runs against `dev`
By submitting this pull request, I …

test: wait for IAM role propagation in migration test

---

packages/amplify-gen2-codegen/src/backend/synthesizer.test.ts
packages/amplify-gen2-codegen/src/backend/synthesizer.ts
packages/amplify-gen2-codegen/src/index.ts
packages/amplify-gen2-codegen/src/npm_package/renderer.test.ts
packages/amplify-gen2-codegen/src/npm_package/renderer.ts
packages/amplify-gen2-codegen/src/renderers/package_json.test.ts
packages/amplify-gen2-codegen/src/renderers/package_json.ts

QA bug fixes:
- Do not replace `package.json` `dependencies` and `devDependencies`. Only override ones that are needed.
- Pin dependencies to match the versions set in `create-amplify` npx command
- Set `generateSecret: false` when `ClientSecret` is not defined. This will prevent creation of a new user pool client post refactor
- Preserve `package.json` name
- Change logical id of user pool client to indicate its a Native one
Manual testing, unit tests

fix: package json name and deps, always set generateSecrets prop

---

.github/actions/run-smoke-tests/action.yml
.github/workflows/smoke-tests.yml

Update to non-deprecated version of `actions/upload-artifact` since we were previously using `v3.1.2`, see:
- Failing run: https://github.com/aws-amplify/amplify-cli/actions/runs/12814158049
- More info https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Also make artifact names unique so job doesn't fail when more than one version is input.
https://github.com/aws-amplify/amplify-cli/actions/runs/12815143580

fix: update actions/upload-artifact

---

packages/amplify-migration/src/app_auth_definition_fetcher.test.ts
packages/amplify-migration/src/app_functions_definition_fetcher.ts
packages/amplify-migration/src/backend_environment_selector.ts
packages/amplify-migration/src/command-handlers.ts
packages/amplify-migration/src/commands/gen2/gen2_command.ts
packages/amplify-migration/src/commands/gen2/gen2_command_factory.test.ts
packages/amplify-migration/src/printer.ts

QA bug fixes/improvements:
- Choose current environment instead of listing all and asking customer to select one
- Update .gitignore to gen2 specific files
- Look for `Cognito` service name for grabbing the resource name since `Cognito-UserPool-Groups` can also co-exist
- Derive function names from `output` key instead of the resource name since in the case of triggers, they are different
- Remove `demandCommands` to surface top level handler errors
Local testing, unit tests

fix: choose current env, update gitignore for gen2, choose function name from output prop

---

packages/amplify-cli-core/src/overrides-manager/override-skeleton-generator.ts

This reverts commit 30c9f0ce2935c3b3871baa2bb01007638b3ffcc9.
@brianlenz  I'm sorry but I have to revert https://github.com/aws-amplify/amplify-cli/pull/13858 .
Upon further verification it turned out that it doesn't work with `npm`. I haven't checked `pnpm` but this is enough signal to revert.
Repro steps:
1. Create amplify project
2. Add auth and data
3. Override auth and data.
4. `cd amplify/backend/ && rm yarn.lock && rm -rf node_modules && npm install && cd .. && cd ..`
5. `amplify build`

Revert "fix(amplify-cli-core): use build script for overrides (#13858)"

---

packages/amplify-provider-awscloudformation/src/iterative-deployment/deployment-manager.ts

When using `general` configLevel for aws credentials, deployment manager was failing because it expected amplify-cli to resolve credentials (and hence region) whereas `general` config implies that credentials are managed by customers and resolved by aws-sdk automatically without cli doing anything. This change removes the validation and instead defaults to AWS client's `region` instead of taking it away completely to reduce the scope of this change.
Reference: https://docs.amplify.aws/gen1/react/tools/cli/usage/headless/#--providers-1
See [this](https://github.com/aws-amplify/amplify-cli/blob/aab715db07578b7790498b9ad791db7d3a0b4d5c/packages/amplify-provider-awscloudformation/src/aws-utils/aws-amplify.js#L34-L42) for a similar example.
Manually tested before and after and confirmed that …

fix: load region from AWS client if the credentials are managed by AWS-SDK

---

packages/amplify-cli-core/API.md
packages/amplify-gen1-codegen-data-adapter/API.md
packages/amplify-gen1-codegen-data-adapter/src/get_data_definition.test.ts
packages/amplify-gen1-codegen-data-adapter/src/get_data_definition.ts
packages/amplify-gen2-codegen/API.md
packages/amplify-gen2-codegen/src/data/source_builder.test.ts
packages/amplify-gen2-codegen/src/data/source_builder.ts
packages/amplify-gen2-codegen/src/index.ts
packages/amplify-migration/src/backend_environment_selector.ts
packages/amplify-migration/src/data_definition_fetcher.test.ts
packages/amplify-migration/src/data_definition_fetcher.ts

Add table mappings for all envs to Gen 2 Codegen.
```
import { defineData } from \"@aws-amplify/backend\";
export const data = defineData({
// Replace each environment name with the corresponding branch name. Use \"sandbox\" for your sandbox environment.
importedAmplifyDynamoDBTableMap: {
prod: { Todo: 'todo-table-prod' },
staging: { Todo: 'todo-table-staging' },
/**
* Unable to find the table mapping for this environment.
* This could be due the enableGen2Migration feature flag not being set to true for this environment.
* Please enable the feature flag and push the backend resources.
* If you are not planning to migrate this environment, you can remove this key.
*/
dev: {}
},
schema: \"TODO: Add your existing graphql schema here\"
});
```
N/A
Unit tests
By submitting this pull request, …

feat: include all envs in gen 2 data codegen

---

packages/amplify-cli-core/API.md
packages/amplify-migration-template-gen/API.md
packages/amplify-migration-template-gen/package.json
packages/amplify-migration-template-gen/src/cfn-stack-refactor-updater.ts
packages/amplify-migration-template-gen/src/cfn-stack-updater.ts
packages/amplify-migration-template-gen/src/custom-test-matchers.ts
packages/amplify-migration-template-gen/src/resolvers/cfn-output-resolver.test.ts
packages/amplify-migration-template-gen/src/resolvers/cfn-output-resolver.ts
packages/amplify-migration-template-gen/src/template-generator.test.ts
packages/amplify-migration-template-gen/src/template-generator.ts
packages/amplify-migration-template-gen/src/types.ts
packages/amplify-migration/src/command-handlers.ts
packages/amplify-util-mock/package.json
yarn.lock

- Add refactor support to gen2 migration tool.
- Refactor bug fix for Fn::GetAtt support for Iam role. In our case, when we add phone number as username in Auth, a SNS role is created that is referenced by GetAtt in the user pool sms config property. 
local testing, unit tests
```../../amplify-migrate/lib/migrate.js to-gen-2 execute --from <GEN1_ROOT_STACK> --to <GEN2_ROOT_STACK>```

feat: add refactor operation to gen2 migration

---

.circleci/local_publish_helpers_codebuild.sh

When building a tagged release, the size of the binary seems to increase to 970 MB, while the cloud pr on the same branch is 880 MB. While this is being investigated, to unblock migration testing, we are temporarily increasing the size of threshold to 1000 MB.

fix: temporary increase to binary size to unblock migrations testing

---

packages/amplify-gen2-codegen/src/data/source_builder.test.ts
packages/amplify-gen2-codegen/src/data/source_builder.ts

Change table map to array of mappings and change top level property name to `migratedAmplifyGen1DynamoDbTableMap`.
```typescript
defineData({
schema,
migratedAmplifyGen1DynamoDbTableMap: [{
branchName: 'dev',
modelTableNameMap: {
ImportedModel: 'ImportedModel-1234-dev',
},
}],
});
```
---

refactor: use array table map and change property name

---

packages/amplify-gen1-codegen-storage-adapter/src/storage_access.test.ts
packages/amplify-gen1-codegen-storage-adapter/src/storage_access.ts
packages/amplify-gen2-codegen/src/backend/synthesizer.test.ts
packages/amplify-gen2-codegen/src/backend/synthesizer.ts
packages/amplify-gen2-codegen/src/function/source_builder.test.ts
packages/amplify-gen2-codegen/src/function/source_builder.ts
packages/amplify-migration/src/command-handlers.ts

- During `prepare` phase, add an environment variable to customers Amplify Hosting build for their gen 1 backend name - https://app.asana.com/0/1206146466379945/1209214806262350
- Throw new error in function resource.ts - https://app.asana.com/0/1209297236712871/1209207544854343
- Fix the identity provider type for LoginWithAmazon - https://app.asana.com/0/1209297236712871/1209313621506855
- Fix the storage access groups
Unit tests

fix: added dynamic reference to the env name in backend.ts and fixed a couple of bugs

---

packages/amplify-gen1-codegen-auth-adapter/src/auth_render_adapter.test.ts
packages/amplify-gen1-codegen-auth-adapter/src/auth_render_adapter.ts
packages/amplify-gen2-codegen/src/index.ts
packages/amplify-migration-template-gen/src/category-template-generator.test.ts
packages/amplify-migration-template-gen/src/category-template-generator.ts
packages/amplify-migration-template-gen/src/types.ts
packages/amplify-migration/README.md

- Generate data code conditionally
- Set username attributes explicitly if present
- Don't set `phone` in `loginWith` object  in order to match the gen1 template
- Add support for native userpool client refactor
test locally with the codegen command, unit tests

fix: conditional data codegen, phone attribute, add support for native userpool client refactor

---

.circleci/local_publish_helpers_codebuild.sh
packages/amplify-migration/src/command-handlers.ts
packages/amplify-migration/src/main_parser_factory.test.ts
packages/amplify-migration/src/main_parser_factory.ts

- Set CLI_ENV to production for usage metrics. The migration tool is not part of CLI and does not have preprod stages.
- Emit usage error metrics when execute fails. The error message we are emitting is a generic one at this point.  If needed, we can sanitize the errors from execute command and pass it here
- Revert package size checks back to the ones in `dev` branch. Sizes are back to below threshold. There was only instance of the size increase and we are not able to figure out the root cause
- Remove `.amplify/migration` dir prior if already exists, prior to creation and moving of the directory
unit tests, ran command locally without env variable set (`AMPLIFY_CLI_BETA_USAGE_TRACKING_URL`):
```
unset AMPLIFY_CLI_BETA_USAGE_TRACKING_URL
../amplify-cli/node_modules/.bin/migrate to-gen-2 …
```

fix(migrate): set CLI_ENV to production for usage metrics

---

.github/actions/run-smoke-tests/action.yml
.github/workflows/smoke-tests-manual.yml
.github/workflows/smoke-tests.yml

The runners we were previously using for smoke tests on mac have gone out of support. Updating to the new runners requires that we update Ruby as well (see: https://github.com/ruby/setup-ruby/issues/568). 
See successful smoke test run: https://github.com/aws-amplify/amplify-cli/actions/runs/13426677491

Fix mac smoke tests

---

Dockerfile
codebuild_specs/build_image.yml

This PR bumps node version to 22.
Companion PR https://github.com/aws-amplify/amplify-cli/pull/14079 .
I got passing E2E run using image override.

Upgrade Node to 22.

---

packages/amplify-cli-npm/index.ts
packages/amplify-cli/src/index.ts

BREAKING CHANGE: Update node to 22
Lerna didn't pickup this commit correctly. https://github.com/aws-amplify/amplify-cli/commit/9cd702273c4f7d8627f6dc6e78f53924fda82b12 .
Fixing this by adding "BREAKING CHANGE: Update node to 22" to commit message.
Ran lerna locally.

feat!: Update node to 22

---

packages/amplify-gen2-codegen/src/function/source_builder.test.ts
packages/amplify-gen2-codegen/src/function/source_builder.ts

add node 20 and 22 version support for functions.
unit tests

Gen2 migrations - support node 20 and 22 in functions

---

packages/amplify-gen1-codegen-function-adapter/src/function_render_adapter.ts
packages/amplify-gen2-codegen/API.md
packages/amplify-gen2-codegen/src/index.ts
packages/amplify-migration/src/command-handler.test.ts
packages/amplify-migration/src/command-handlers.ts
packages/amplify-migration/src/data_definition_fetcher.test.ts
packages/amplify-migration/src/data_definition_fetcher.ts

If amplify.yml does not exist at the root of their project, get the buildSpec by making the getApp call, update the Gen1 command and create amplify.yml file with the updated buildspec
if amplify.yml exists at the root, update the buildspec by replacing Gen1 command to Gen2 command
Gen1 command: amplifyPush --simple
Gen2 command: npx ampx pipeline-deploy
https://app.asana.com/0/1209548398662247/1209172037882456

fix: update amplify.yml file with the gen2 command

---

packages/amplify-gen2-codegen/src/backend/synthesizer.test.ts
packages/amplify-gen2-codegen/src/backend/synthesizer.ts
packages/amplify-gen2-codegen/src/index.ts
packages/amplify-migration/src/app_auth_definition_fetcher.ts
packages/amplify-migration/src/command-handler.test.ts
packages/amplify-migration/src/command-handlers.ts

1) codegen idp in backend.ts: https://app.asana.com/0/1209548398662250/1209688082354480/f
`const providerSetupResult = (backend.auth.stack.node.children.find(child => child.node.id === "amplifyAuth") as any).providerSetupResult;
Object.keys(providerSetupResult).forEach(provider => {
const providerSetupPropertyValue = providerSetupResult[provider];
if (providerSetupPropertyValue.node && providerSetupPropertyValue.node.id.toLowerCase().endsWith("idp")) {
userPoolClient.node.addDependency(providerSetupPropertyValue);
}
});`
2) don't throw an error if buildSpec is not found during getApp call: https://app.asana.com/0/1209548398662250/1209731110320988/f
3) don't generate auth/resource.ts if authCategory doesn't exist
By submitting this pull request, I confirm that my contribution is made under …

fix: add idp codegen and fix a couple of minor bugs

---

packages/amplify-gen1-codegen-auth-adapter/src/auth_render_adapter.test.ts
packages/amplify-gen1-codegen-auth-adapter/src/auth_render_adapter.ts
packages/amplify-gen2-codegen/src/backend/synthesizer.ts
packages/amplify-gen2-codegen/src/data/source_builder.test.ts
packages/amplify-gen2-codegen/src/function/source_builder.ts
packages/amplify-gen2-codegen/src/index.ts
packages/amplify-gen2-codegen/src/npm_package/renderer.test.ts
packages/amplify-gen2-codegen/src/npm_package/renderer.ts
packages/amplify-gen2-codegen/src/resource/resource.ts
packages/amplify-gen2-codegen/src/ts_factory_utils.ts
packages/amplify-migration-template-gen/src/template-generator.test.ts
packages/amplify-migration-template-gen/src/template-generator.ts
packages/amplify-migration-template-gen/src/types.ts
packages/amplify-migration/src/command-handlers.ts
packages/amplify-migration/src/error_handler.test.ts
packages/amplify-migration/src/error_handler.ts
packages/amplify-migration/src/migrate.ts

- Skip `PreTokenGenerationConfig` key from Cognito during `prepare`
- Add new line to separate import, body and export statements in codegen
- Wrap `throw new Error` call expression in a statement. This adds a semicolon at the end
- Add `@types/node` to fix `process.env` type errors
- Resolve CFN parameters in Gen2 stack during revert
- Surface errors during  Gen2 codegen in `prepare` command
- Add support for `--debug` flag for `prepare` command to output the stack trace
local testing with `prepare`, `execute` and `revert` commands

Gen2 migrations QA fixes

---

packages/amplify-gen2-codegen/src/backend/synthesizer.test.ts
packages/amplify-gen2-codegen/src/backend/synthesizer.ts
packages/amplify-migration-template-gen/src/migration-readme-generator.test.ts
packages/amplify-migration-template-gen/src/migration-readme-generator.ts

- Remove commented out codegen for adding RETAIN policies to User pool, Identity Pool, S3 bucket as its already handled by Gen2 CDK code for CI deployments. Sandbox deployments are intentionally overriden to be deleted
- Add a Commented out line for deleting User pool domain from Gen2 stack. This is because Gen1 did not have User Pool Domains as part of CFN but had a custom resource adding them. Post refactor, if we don't add this line the deploy would fail saying Invalid request for OAuth apps.
Local testing, unit tests

Gen2 migrations execute

---

packages/amplify-gen1-codegen-function-adapter/API.md
packages/amplify-gen1-codegen-function-adapter/src/function_render_adapter.test.ts
packages/amplify-gen1-codegen-function-adapter/src/function_render_adapter.ts
packages/amplify-gen2-codegen/API.md
packages/amplify-gen2-codegen/src/backend/synthesizer.test.ts
packages/amplify-gen2-codegen/src/backend/synthesizer.ts
packages/amplify-gen2-codegen/src/function/source_builder.ts
packages/amplify-gen2-codegen/src/index.ts
packages/amplify-migration/package.json
packages/amplify-migration/src/app_functions_definition_fetcher.ts
packages/amplify-migration/src/command-handler.test.ts
packages/amplify-migration/src/command-handlers.ts
yarn.lock

**Codegen custom resource**
Copy custom/ folder from gen1 -> gen2
Update cdk-stack.ts file to remove @aws-amplify/cli-extensibility-helper dependency
-- Check for existence of AmplifyHelpers.addResourceDependency and throw an error if found (errorMessage to be updated)
-- Replace AmplifyHelpers.getProjectInfo() with {envName: 'envName', projectName: 'projectName'}
-- Replace AmplifyHelpers.AmplifyResourceProps with {category: 'custom', resourceName: resource}
-- Remove the import statement import * as AmplifyHelpers from '@aws-amplify/cli-extensibility-helper';
**Add scheduling in functions**

fix: codegen custom resources and added function scheduling

---

packages/amplify-migration-template-gen/package.json
packages/amplify-migration-template-gen/src/template-generator.ts
yarn.lock

Replace console logs with ora for async tasks in template gen flow.
Local testing
```
../amplify-cli/node_modules/.bin/migrate to-gen-2 revert --to amplify-testora-dev-8fb33 --from amplify-mygen2app-ora-sandbox-2681f0acba --debug
✔ Moved auth resources from Gen2 to Gen1 stack successfully
Moved resources back to Gen1 stack successfully.
✔ Moved your Gen1 backend files to amplify
```

fix(migrate-template-gen): replace console logs with ora for async tasks

---

packages/amplify-migration-template-gen/src/migration-readme-generator.ts
packages/amplify-migration-template-gen/src/template-generator.ts
packages/amplify-migration/src/command-handler.test.ts
packages/amplify-migration/src/command-handlers.ts

- Formatting changes: 
-  Add space between Gen1 and Gen2 in outputs
- Use `custom` to depict moving custom resources instead of the resource logical ids
- Custom resource conditional error handling based on presence/absence of comments
-  Use single or double quotes in `env` parameter regex in custom resource file to add default value 
ran the prepare and execute commands locally, unit tests

fix: custom resource error handling, formatting messages

---

packages/amplify-migration-e2e/package.json
packages/amplify-migration-template-gen/src/resolvers/cfn-output-resolver.test.ts
packages/amplify-migration-template-gen/src/resolvers/cfn-output-resolver.ts
packages/amplify-migration-template-gen/src/template-generator.test.ts
packages/amplify-migration-template-gen/src/template-generator.ts
packages/amplify-migration-template-gen/src/types.ts

- Initialize non-custom category generator without custom predicate
- Support Lambda function ARN replace in output resolver (needed for S3 auto delete objects in `storage` category)
ran `execute` command locally, unit tests.

Initialize non-custom category generator without custom predicate

---

packages/amplify-go-function-runtime-provider/src/localinvoke.ts

https://github.com/aws-amplify/amplify-cli/blob/e936bfd8a4527eba1576548301fe460dc1250005/packages/amplify-go-function-runtime-provider/src/localinvoke.ts#L73-L73
To fix the problem, we should avoid using `execa.command` with a dynamically constructed command string. Instead, we can use `execa` with an array of arguments to safely pass the executable and its arguments without shell interpretation. This approach ensures that the input is not interpreted by the shell, preventing command injection.
1. Replace the use of `execa.command` with `execa` and pass the executable and arguments as an array.
2. Ensure that the `lambdaExecutablePath` and `lambdaExecutableDir` are passed as separate arguments to avoid shell interpretation.
Dynamically constructing a shell command with inputs from …

fix Unsafe shell command constructed from library input shell-quote() OS Command Injection

---

packages/amplify-category-auth/package.json
packages/amplify-category-custom/package.json
packages/amplify-category-geo/package.json
packages/amplify-category-storage/package.json
packages/amplify-cli-core/package.json
packages/amplify-cli-extensibility-helper/package.json
packages/amplify-cli/package.json
packages/amplify-e2e-tests/package.json
packages/amplify-migration-tests/package.json
packages/amplify-provider-awscloudformation/package.json
packages/amplify-util-mock/package.json
yarn.lock

Follow up on https://github.com/aws-amplify/amplify-cli/pull/14175#discussion_r2054444573 .
We pin CDK version in Gen1 CLI. Restoring that behavior.

fix: pin CDK version again

---

packages/amplify-migration-e2e/package.json
packages/amplify-migration-e2e/src/__tests__/migration_codegen_e2e.test.ts
packages/amplify-migration-e2e/src/__tests__/migration_templategen_e2e.test.ts
packages/amplify-migration-e2e/src/assertions.ts
packages/amplify-migration-e2e/src/gen1ResourceDetailsFetcher.ts
packages/amplify-migration-e2e/src/index.ts
packages/amplify-migration-e2e/src/sandbox.ts
packages/amplify-migration-e2e/src/sdk_calls.ts
packages/amplify-migration-e2e/src/templategen.ts
yarn.lock

- Fix revert gen2 migration e2e test
e2e tests that regress revert flow

test: revert gen2 migration e2e test

---

packages/amplify-migration-template-gen/src/template-generator.ts

remove extraneous assert. This was not causing any failures, but is not needed at this point in the code (was added before a code refactor).
`yarn test`, manual testing.
```
../amplify-cli/node_modules/.bin/migrate to-gen-2 execute --from amplify-testref2-dev-8a7e3 --to amplify-mygen2app-ref4-sandbox-f1676df4a6 --debug
✔ Updated Gen 1 auth stack successfully
✔ Updated Gen 2 auth stack successfully
✔ Moved auth resources from Gen 1 to Gen 2 stack successfully
Generated .README file(s) successfully under .amplify/migration/templates directory.
```

chore: remove extraneous assert

---

.circleci/local_publish_helpers_codebuild.sh
codebuild_specs/e2e_workflow_base.yml
codebuild_specs/e2e_workflow_generated.yml
packages/amplify-cli/tsconfig.json
packages/amplify-migration/src/command-handler.test.ts

- remove migration package from cli tsconfig as its a standalone executable
-  Add depends on to `upb` instead of `build_linux`.  I checked the s3 verdaccio cache for the failed run and it was created at `18:04 UTC` while this run was started at `18:03 UTC`. When I traced the `depend-on`  for the migration test it was set to `build_linux` instead of `upb` (upload package binaries). `upb` transitively depends on `build_linux`. So we should be good.
`yarn build`, `yarn test`

chore: remove migration package from cli tsconfig as its a standalone executable

---

packages/amplify-category-analytics/src/commands/analytics/add.ts
packages/amplify-category-analytics/src/commands/analytics/push.ts
packages/amplify-category-analytics/src/commands/analytics/update.ts
packages/amplify-category-interactions/src/commands/interactions/push.js
packages/amplify-category-interactions/src/commands/interactions/update.js
packages/amplify-category-notifications/src/commands/notifications/add.ts
packages/amplify-category-notifications/src/commands/notifications/configure.ts
packages/amplify-category-notifications/src/commands/notifications/status.ts

Pinpoint is reaching end of life on October 30,2026 and stop accepting new customers May 20, 2025. Currently Analytics and Notifications use Pinpoint and will become unusable after October 30, 2026. 
This PR adds warnings to commands in the notifications and analytics categories to warn customers about Pinpoint's looming end of life. 
Removing the ability to use Analytics with Pinpoint will be in a separate PR since it will involve a lot of e2e test changes (and may result in our notifications e2e tests no longer being functional).
Additionally, some warnings are added to interactions commands about Lex V1 reaching end of life. 
Ensured the warnings appeared when running the commands. 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Add warnings for Pinpoint categories
